<?php

return [
    'footer_index' => 'पुस्तकालय',
    'footer_crest_eyebrow' => 'सत्य पुस्तकालय का समापन',
    'footer_crest_quote' => '“दक्षिण चीन सागर में शांति की नींव <b>अंतरराष्ट्रीय कानून</b> पर आधारित है।”',
    'footer_crest_sub' => 'नफ़रत नहीं · केवल सत्य',
    'footer_nav_aria' => 'पृष्ठ के अंत की कार्रवाइयाँ',
    'footer_btn_top' => 'ऊपर जाएँ',
    'footer_btn_verdict' => 'PCA 2016 का निर्णय',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'नाइन-डैश लाइन का दावा',
    'footer_brand_eyebrow' => 'विशेष विषय · वियतनाम की संप्रभुता',
    'footer_brand_body' => 'नाइन-डैश लाइन को वस्तुनिष्ठ सत्य, अंतरराष्ट्रीय कानून, PCA 2016 के निर्णय और ऐतिहासिक दस्तावेज़ों के माध्यम से समझाया गया है — यह <strong>"पैरासेल द्वीपसमूह और स्प्रैटली द्वीपसमूह"</strong> की संप्रभुता पर गहन पृष्ठों का पूरक है। चीन के निराधार दावों को इतिहास और साक्ष्यों के आधार पर अस्वीकार किया गया है।',
    'footer_refs_title' => 'संदर्भ स्रोत',
    'footer_ref1' => 'PCA का निर्णय, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — पूर्ण पाठ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ऐतिहासिक दस्तावेज़ और प्राचीन मानचित्र',
    'footer_toc_title' => 'पृष्ठ की विषय-सूची',
    'footer_toc1' => 'नाइन-डैश लाइन क्या है',
    'footer_toc2' => 'उत्पत्ति',
    'footer_toc3' => 'यह विवादास्पद क्यों है',
    'footer_toc4' => 'अंतरराष्ट्रीय विरोध क्यों',
    'footer_toc5' => 'मूक साक्षी',
    'footer_toc6' => 'PCA 2016 का निर्णय',
    'footer_toc7' => 'पैरासेल द्वीपसमूह – स्प्रैटली द्वीपसमूह',
    'footer_copy_eyebrow' => 'गैर-लाभकारी परियोजना',
    'footer_copy_title' => 'पैरासेल द्वीपसमूह – स्प्रैटली द्वीपसमूह वियतनाम का है',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — वियतनाम की संप्रभुता पारिस्थितिकी का हिस्सा, नाइन-डैश लाइन पर विशेष विषय पृष्ठ।',
    'footer_copy_body' => 'नाइन-डैश लाइन के दावे की व्याख्या <strong>वस्तुनिष्ठ सत्य</strong>, <strong>अंतरराष्ट्रीय कानून</strong>, PCA 2016 के निर्णय और ऐतिहासिक दस्तावेज़ों के माध्यम से की गई है — यह पैरासेल द्वीपसमूह और स्प्रैटली द्वीपसमूह की संप्रभुता पर गहन पृष्ठों का पूरक है।',
    'footer_copy_ecosystem_aria' => 'एक ही परियोजना के पृष्ठ',
    'footer_copy_ecosystem_label' => 'एक ही पारिस्थितिकी तंत्र',
    'footer_copy_disclaimer' => 'यह सामग्री शिक्षा और जागरूकता बढ़ाने के लिए है; यह वियतनाम सरकार के आधिकारिक रुख का स्थान नहीं लेती।',
    'footer_copy' => '<strong>© :year नाइन-डैश लाइन</strong> — गैर-लाभकारी परियोजना <strong>पैरासेल द्वीपसमूह – स्प्रैटली द्वीपसमूह वियतनाम का है</strong> का एक भाग, निम्न पारिस्थितिकी तंत्र का हिस्सा: <a href="https://paracelislands.net/hi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/hi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/hi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/hi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/hi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'साइट सामग्री की प्रतिबद्धता',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 का निर्णय',
    'footer_chip3' => 'ऐतिहासिक साक्ष्य',
    'footer_chip4' => 'प्राचीन मानचित्र',
    'footer_chip5' => 'वस्तुनिष्ठ सत्य',
    'footer_chip6' => 'दक्षिण चीन सागर में शांति',
];
