<?php

return [
    'footer_index' => 'पुस्तकालय',
    'footer_crest_eyebrow' => 'सत्य के पुस्तकालय का समापन',
    'footer_crest_quote' => '“दक्षिण चीन सागर में शांति <b>अंतरराष्ट्रीय कानून</b> की नींव पर निर्मित होती है।”',
    'footer_crest_sub' => 'घृणा नहीं · केवल सत्य',
    'footer_nav_aria' => 'पृष्ठ के अंत की कार्रवाइयाँ',
    'footer_btn_top' => 'पृष्ठ के शीर्ष पर जाएँ',
    'footer_btn_verdict' => 'PCA 2016 का निर्णय',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'नाइन-डैश लाइन',
    'footer_brand_body' => 'वस्तुनिष्ठ तथ्यों, अंतरराष्ट्रीय कानून और ऐतिहासिक दस्तावेज़ों पर आधारित एक व्याख्यात्मक साइट — जो नाइन-डैश लाइन के दावे को नारों से नहीं, प्रमाणों से खारिज करती है।',
    'footer_refs_title' => 'संदर्भ स्रोत',
    'footer_ref1' => 'PCA का निर्णय, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — पूर्ण पाठ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ऐतिहासिक सामग्री और प्राचीन मानचित्र',
    'footer_toc_title' => 'पृष्ठ विषय-सूची',
    'footer_toc1' => 'नाइन-डैश लाइन क्या है',
    'footer_toc2' => 'उद्गम',
    'footer_toc3' => 'विवाद क्यों पैदा करती है',
    'footer_toc4' => 'अंतरराष्ट्रीय समुदाय विरोध क्यों करता है',
    'footer_toc5' => 'मूक साक्षी',
    'footer_toc6' => 'PCA 2016 का निर्णय',
    'footer_toc7' => 'पैरासेल द्वीपसमूह - स्प्रैटली द्वीपसमूह',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — दक्षिण चीन सागर के बारे में वस्तुनिष्ठ सत्य।<br>इकोसिस्टम: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'निर्देशांक नहीं',
];
