<?php

return [
    'nav_logo_name' => 'नाइन-डैश लाइन',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'नाइन-डैश लाइन',
    'nav_rail_aria' => 'अनुभाग अनुसार नेविगेशन',
    'nav_rail_what' => 'परिभाषा',
    'nav_rail_origin' => 'उद्गम',
    'nav_rail_dispute' => 'विवाद',
    'nav_rail_opposition' => 'विरोध',
    'nav_rail_witnesses' => 'प्राचीन मानचित्र',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'पैरासेल द्वीपसमूह - स्प्रैटली द्वीपसमूह',
    'nav_sound_off' => 'पृष्ठभूमि संगीत चालू करें',
    'nav_sound_on' => 'पृष्ठभूमि संगीत बंद करें',
    'nav_share' => 'साझा करें',
    'dialog_title' => 'प्रदर्शन भाषा',
    'language' => 'भाषा',
    'display_hint' => ':count भाषाएँ',
    'search_placeholder' => 'भाषा खोजें…',
    'cancel' => 'रद्द करें',
    'apply' => 'लागू करें',
    'sound_off' => 'पृष्ठभूमि ध्वनि चालू करें',
    'sound_on' => 'पृष्ठभूमि ध्वनि बंद करें',
    'lang_trigger' => 'भाषा चुनें',
    'close' => 'बंद करें',
    'no_results' => 'कोई भाषा नहीं मिली',
    'contribute' => 'साझा करें',
];
