<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Sanningens bibliotekets avslutning',
    'footer_crest_quote' => '“Freden i Sydkinesiska havet bygger på grunden av <b>internationell rätt</b>.”',
    'footer_crest_sub' => 'Inget hat · Endast sanningen',
    'footer_nav_aria' => 'Åtgärder längst ned på sidan',
    'footer_btn_top' => 'Till toppen',
    'footer_btn_verdict' => 'PCA:s utslag 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Anspråk på Niostrecksgränsen',
    'footer_brand_eyebrow' => 'Temasida · Vietnams suveränitet',
    'footer_brand_body' => 'Förklarar Niostrecksgränsen genom objektiva fakta, internationell rätt, PCA:s utslag 2016 och historiska källor — som ett komplement till de fördjupade sidorna om suveräniteten över de två ögrupperna <strong>"Paracelöarna och Spratlyöarna"</strong>. Bemöter Kinas orimliga anspråk med historia och bevis.',
    'footer_refs_title' => 'Källor',
    'footer_ref1' => 'PCA:s utslag, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — fulltext',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiska källor & gamla kartor',
    'footer_toc_title' => 'Sidans innehållsförteckning',
    'footer_toc1' => 'Vad Niostrecksgränsen är',
    'footer_toc2' => 'Ursprung',
    'footer_toc3' => 'Varför det är omstritt',
    'footer_toc4' => 'Varför det avvisas internationellt',
    'footer_toc5' => 'Tysta vittnen',
    'footer_toc6' => 'PCA:s utslag 2016',
    'footer_toc7' => 'Paracelöarna – Spratlyöarna',
    'footer_copy_eyebrow' => 'Icke-vinstdrivet projekt',
    'footer_copy_title' => 'Paracelöarna – Spratlyöarna tillhör Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — En temasida om Niostrecksgränsen i Vietnams suveränitetsekosystem.',
    'footer_copy_body' => 'Förklarar anspråket på Niostrecksgränsen genom <strong>objektiva fakta</strong>, <strong>internationell rätt</strong>, PCA:s utslag 2016 och historiska källor — som ett komplement till de fördjupade sidorna om suveräniteten över de två ögrupperna Paracelöarna och Spratlyöarna.',
    'footer_copy_ecosystem_aria' => 'Sidor inom samma projekt',
    'footer_copy_ecosystem_label' => 'Samma ekosystem',
    'footer_copy_disclaimer' => 'Innehållet är avsett för utbildning och ökad medvetenhet; det ersätter inte den officiella ståndpunkten från Vietnams stat.',
    'footer_copy' => '<strong>© :year Niostrecksgränsen</strong> — En del av det icke-vinstdrivna projektet <strong>Paracelöarna – Spratlyöarna tillhör Vietnam</strong> inom systemet: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sidans innehållslöfte',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA:s utslag 2016',
    'footer_chip3' => 'Historiska bevis',
    'footer_chip4' => 'Gamla kartor',
    'footer_chip5' => 'Objektiva fakta',
    'footer_chip6' => 'Fred i Sydkinesiska havet',
];
