<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Avslutning på sanningens bibliotek',
    'footer_crest_quote' => '“Freden i Sydkinesiska havet bygger på grunden av <b>internationell rätt</b>.”',
    'footer_crest_sub' => 'Inget hat · Bara sanning',
    'footer_nav_aria' => 'Åtgärder i sidfoten',
    'footer_btn_top' => 'Till toppen',
    'footer_btn_verdict' => 'PCA-domen 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Niostrecksgränsen',
    'footer_brand_body' => 'En förklarande webbplats byggd på objektiva fakta, internationell rätt och historiska dokument — som bemöter Niostrecksgränsens anspråk med bevis, inte slagord.',
    'footer_refs_title' => 'Källor',
    'footer_ref1' => 'PCA-domen, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — fullständig text',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiska dokument och gamla kartor',
    'footer_toc_title' => 'Sidans innehåll',
    'footer_toc1' => 'Vad är Niostrecksgränsen',
    'footer_toc2' => 'Ursprung',
    'footer_toc3' => 'Varför den är omstridd',
    'footer_toc4' => 'Varför omvärlden motsätter sig den',
    'footer_toc5' => 'Tysta vittnen',
    'footer_toc6' => 'PCA-domen 2016',
    'footer_toc7' => 'Paracelöarna – Spratlyöarna',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektiv sanning om Sydkinesiska havet.<br>Ekosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Inga koordinater',
];
