<?php

return [
    'nav_logo_name' => 'Niostrecksgränsen',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Niostrecksgränsen',
    'nav_rail_aria' => 'Navigera efter avsnitt',
    'nav_rail_what' => 'Definition',
    'nav_rail_origin' => 'Ursprung',
    'nav_rail_dispute' => 'Tvisten',
    'nav_rail_opposition' => 'Motstånd',
    'nav_rail_witnesses' => 'Gamla kartor',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelöarna – Spratlyöarna',
    'nav_sound_off' => 'Aktivera bakgrundsmusik',
    'nav_sound_on' => 'Inaktivera bakgrundsmusik',
    'nav_share' => 'Dela',
    'dialog_title' => 'Visningsspråk',
    'language' => 'Språk',
    'display_hint' => ':count språk',
    'search_placeholder' => 'Sök språk…',
    'cancel' => 'Avbryt',
    'apply' => 'Tillämpa',
    'sound_off' => 'Aktivera ljud',
    'sound_on' => 'Inaktivera ljud',
    'lang_trigger' => 'Välj språk',
    'close' => 'Stäng',
    'no_results' => 'Inga språk hittades',
    'contribute' => 'Dela',
];
