<?php

return [
    'opposition_index' => 'Invändningar',
    'opposition_label' => 'Varför omvärlden motsätter sig',
    'opposition_title' => 'Invändningar bygger på',
    'opposition_title_accent' => 'lag, inte känslor',
    'opposition_lead' => 'Kort efter att Niostrecksgränsen lades fram inför FN 2009 motsatte sig flera länder och forskare den — med konkreta juridiska argument.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maj',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesien',
    'opposition_voice1_body' => 'Bara en dag efter att Kina lade fram Niostrecksgränsens karta till FN:s generalsekreterare (7/5/2009) skickade dessa länder var för sig protestnoter och avvisade anspråket.',
    'opposition_voice1_chip1' => 'Protestnot',
    'opposition_voice1_chip2' => 'Stämmer inte med UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippinerna',
    'opposition_voice2_body' => 'Skickade ett diplomatiskt brev till FN och förklarade att Kinas anspråk i Sydkinesiska havet var ”utan grund i internationell rätt” — en förutsättning för den senare skiljedomstolsprocessen.',
    'opposition_voice2_chip1' => 'Förutsättning för PCA-målet',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'USA:s utrikesdepartement — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analysen visade att kartorna från olika år var inkonsekventa när det gäller gränslinjens placering; att linjen trängde in på fastlandet i stället för att följa mittlinjen; och att många formationer inte uppfyllde kriterierna för en ”ö” och därför inte kunde ge en EEZ.',
    'opposition_voice3_chip1' => 'Uppfyller inte de juridiska kraven',
    'opposition_voice3_chip2' => 'Officiell analys',
    'opposition_voice4_year' => 'Akademiskt',
    'opposition_voice4_title' => '”Historiskt vattenområde” är föråldrat',
    'opposition_voice4_body' => 'Detta begrepp gäller endast vikar och vatten nära kusten — det kan inte omfatta ett helt och stort öppet havsområde. År 2003 avvisade även Taiwan den politiken för ”historiskt vattenområde”, som hade nämnts 1993.',
    'opposition_voice4_chip1' => 'Inte ens kinesiska forskare är eniga',
];
