<?php

return [
    'opposition_index' => 'Invändningar',
    'opposition_label' => 'Varför omvärlden motsätter sig',
    'opposition_title' => 'Invändningar bygger på',
    'opposition_title_accent' => 'lag, inte känslor',
    'opposition_lead' => 'Kort efter att Niostrecksgränsen lades fram för FN år 2009 motsatte sig många länder och forskare detta — med konkreta juridiska argument.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maj',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesien',
    'opposition_voice1_body' => 'Redan en dag efter att Kina lade fram sin karta över Niostrecksgränsen för Förenta nationernas generalsekreterare (7/5/2009) skickade dessa länder var för sig protestnotor och avvisade anspråket.',
    'opposition_voice1_chip1' => 'Protestnot',
    'opposition_voice1_chip2' => 'Inte förenligt med UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippinerna',
    'opposition_voice2_body' => 'Skickade ett diplomatiskt brev till Förenta nationerna och förklarade att Kinas anspråk i Sydkinesiska havet var “utan grund i internationell rätt” — ett förspel till den efterföljande skiljeförfarandet.',
    'opposition_voice2_chip1' => 'Förspel till PCA-målet',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'USA:s utrikesdepartement — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analysen visade att kartorna från olika år inte var konsekventa när det gäller linjens läge; att linjen trängde in på land i stället för att utgå från mittlinjen; och att många objekt inte uppfyllde kraven för att räknas som “öar” med rätt till EEZ.',
    'opposition_voice3_chip1' => 'Uppfyller inte de juridiska kriterierna',
    'opposition_voice3_chip2' => 'Officiell analys',
    'opposition_voice4_year' => 'Akademiskt',
    'opposition_voice4_title' => '“Historiska vatten” är föråldrat',
    'opposition_voice4_body' => 'Detta begrepp gäller endast för vikar och havsvikar nära kusten — det kan inte omfatta ett helt stort öppet havsområde. År 2003 avvisade även Taiwan själv politiken om “historiska vatten” som hade framförts 1993.',
    'opposition_voice4_chip1' => 'Inte ens kinesiska forskare är eniga',
];
