<?php

return [
    'sovereignty_index' => 'Paracelöarna – Spratlyöarna',
    'sovereignty_label' => 'Den oundvikliga slutsatsen',
    'sovereignty_title' => 'Paracelöarna – Spratlyöarna',
    'sovereignty_title_accent' => 'tillhör Vietnam',
    'sovereignty_lead' => 'Denna sida förklarar Niostrecksgränsen. Slutsatsen besvarar den följande frågan: vem har suveränitet över de två ögrupperna Paracelöarna och Spratlyöarna? Enligt historisk förvaltning och internationell rätt är det konsekventa svaret Vietnam.',
    'sovereignty_thesis_label' => 'Sammanfattande tes',
    'sovereignty_thesis_lock1' => 'Ingen rättslig koordinat',
    'sovereignty_thesis_lock2' => 'PCA 2016 underkände',
    'sovereignty_thesis_lock3' => 'Historiska kartor omfattar inte',
    'sovereignty_thesis_body' => 'Efter de sex avsnitten ovan står tre saker klart: Niostrecksgränsen är ritad för hand och saknar rättsliga koordinater; skiljedomstolen 2016 underkände anspråket; och Kinas egna äldre kartor omfattade inte Sydkinesiska havet. Vietnams suveränitet bygger inte på slagord utan på att den vietnamesiska staten — från Nguyễn-härskarnas tid — fredligt och kontinuerligt har förvaltat området när de två ögrupperna fortfarande var terra nullius.',
    'sovereignty_spine_caption' => 'Kontinuerliga förvaltningspunkter',
    'sovereignty_spine_title' => 'En obruten tidslinje',
    'sovereignty_spine_range' => '1600-talet → nutid',
    'sovereignty_chron1_year' => '1600-talet',
    'sovereignty_chron1_title' => 'Hoang Sa-kåren',
    'sovereignty_chron1_body' => 'Nguyễn-härskarna sände Hoang Sa-kåren för att utföra undersökningar, mäta farleder och utnyttja havet — ett faktiskt utövande av förvaltning.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kung Gia Long',
    'sovereignty_chron2_body' => 'Hissade flaggan på Paracelöarna och bekräftade Vietnams suveränitet inför dåtidens omvärld.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kung Minh Mạng',
    'sovereignty_chron3_body' => 'Lät mäta, resa stelar och föra in ögrupperna på hovets officiella kartor.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuerlig rättslig succession',
    'sovereignty_chron4_body' => 'Frankrike erkände och fortsatte förvaltningen; Paracelöarna införlivades i Thừa Thiên-provinsen — en grund för dagens vietnamesiska stat.',
    'sovereignty_chron5_year' => 'Nutid',
    'sovereignty_chron5_title' => 'Rätt och praxis',
    'sovereignty_chron5_body' => 'Vietnam förvaltar i enlighet med UNCLOS, diplomati och arkiv; anspråket enligt Niostrecksgränsen kan inte ersätta dessa bevis.',
    'sovereignty_balance_label' => 'Bevisbalans',
    'sovereignty_balance_medallion_title' => 'Jämförelse mellan de två sidorna',
    'sovereignty_vn_tag' => 'Den vietnamesiska sidan',
    'sovereignty_vn_title' => 'Suveränitet fastställd genom handling',
    'sovereignty_vn_body' => 'Verkligt besittande när området fortfarande var terra nullius, följt av öppen och långvarig förvaltning genom seklerna — med kungliga dokument, stelar, kartor och administrativa handlingar. Detta är förenligt med UNCLOS och internationell sedvana.',
    'sovereignty_dash_tag' => 'Niostrecksgränsens sida',
    'sovereignty_dash_title' => 'Ett anspråk kan inte uppväga bevis',
    'sovereignty_dash_body' => 'En linje ritad 1948, utan koordinater, underkändes av PCA 2016 och strider mot UNCLOS — såsom avsnitt 03 till 06 har visat. Därför kan slutsatsen om de två ögruppernas suveränitet inte bygga på Niostrecksgränsen.',
    'sovereignty_seal_quote' => 'Vietnam löser tvister med <strong>fredliga medel</strong>, på grundval av internationell rätt — särskilt UNCLOS 1982 — med sikte på ett Sydkinesiskt hav präglat av fred, samarbete och utveckling.',
    'sovereignty_seal_cite' => 'Vietnams ståndpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Huvudprojektet i samma ekosystem',
    'sovereignty_next_title' => 'Läs hela bevisningen om Paracelöarna – Spratlyöarna',
    'sovereignty_next_body' => 'Det detaljerade materialet — dokument, kartor, tidslinjer och juridiska argument — finns på <strong>paracelislands.net</strong>, där ämnet om de två ögruppernas suveränitet behandlas i sin helhet. Sidan du läser nu knyter bara samman logiken från Niostrecksgränsen till den slutsatsen.',
    'sovereignty_next_cta' => 'Öppna paracelislands.net',
];
