<?php

return [
    'sovereignty_index' => 'Paracelöarna – Spratlyöarna',
    'sovereignty_label' => 'Nödvändig slutsats',
    'sovereignty_title' => 'Paracelöarna – Spratlyöarna',
    'sovereignty_title_accent' => 'tillhör Vietnam',
    'sovereignty_lead' => 'Den här sidan förklarar Niostrecksgränsen. Slutsatsen besvarar nästa fråga: vem har suveränitet över de två ögrupperna Paracelöarna och Spratlyöarna? Enligt den historiska förvaltningen och internationell rätt är svaret konsekvent Vietnam.',
    'sovereignty_thesis_label' => 'Samlad tes',
    'sovereignty_thesis_lock1' => 'Ingen juridisk koordinat',
    'sovereignty_thesis_lock2' => 'PCA 2016 underkände',
    'sovereignty_thesis_lock3' => 'Gamla kartor omfattar inte',
    'sovereignty_thesis_body' => 'Efter de sex avsnitten ovan är tre saker tydliga: Niostrecksgränsen är handritad och saknar juridiska koordinater; skiljedomstolen 2016 underkände anspråket; äldre kartor från Kina omfattade inte Sydkinesiska havet. Vietnams suveränitet bygger inte på slagord utan på att den vietnamesiska staten — från Nguyễn-härskarnas tid — fredligt och kontinuerligt har förvaltad området när de två ögrupperna fortfarande var ingenmansland.',
    'sovereignty_spine_caption' => 'Kontinuerliga förvaltningspunkter',
    'sovereignty_spine_title' => 'En oavbruten tidslinje',
    'sovereignty_spine_range' => '1600-talet → nutid',
    'sovereignty_chron1_year' => '1600-talet',
    'sovereignty_chron1_title' => 'Hoàng Sa-flottiljen',
    'sovereignty_chron1_body' => 'Nguyễn-härskarna sände Hoàng Sa-flottiljen för att kartlägga, mäta sjöleder och bedriva verksamhet till havs — ett faktiskt utövande av förvaltning.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kung Gia Long',
    'sovereignty_chron2_body' => 'Hissade flaggan på Paracelöarna och bekräftade Vietnams suveränitet inför samtiden.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kung Minh Mạng',
    'sovereignty_chron3_body' => 'Lät mäta, resa stenar och föra in ögruppen på hovets officiella kartor.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuitet i arv',
    'sovereignty_chron4_body' => 'Frankrike erkände och fortsatte förvaltningen; Paracelöarna införlivades i Thừa Thiên-provinsen — en grund för dagens vietnamesiska stat.',
    'sovereignty_chron5_year' => 'Nutid',
    'sovereignty_chron5_title' => 'Lag och praxis',
    'sovereignty_chron5_body' => 'Vietnam förvaltar enligt UNCLOS, diplomati och arkiv; anspråket med Niostrecksgränsen kan inte ersätta detta bevis.',
    'sovereignty_balance_label' => 'Bevisbalans',
    'sovereignty_balance_medallion_title' => 'Jämförelse av två sidor',
    'sovereignty_vn_tag' => 'Den vietnamesiska sidan',
    'sovereignty_vn_title' => 'Suveränitet fastställd genom handling',
    'sovereignty_vn_body' => 'Verklig besittning när landet ännu var ingenmansland, följt av öppen förvaltning i flera århundraden — med kejserliga edikter, stenar, kartor och administrativa dokument. Detta är förenligt med UNCLOS och internationell sedvana.',
    'sovereignty_dash_tag' => 'Niostrecksgränsens sida',
    'sovereignty_dash_title' => 'Ett anspråk kan inte väga upp bevis',
    'sovereignty_dash_body' => 'En linje ritad 1948, utan koordinater, underkänd av PCA 2016 och i strid med UNCLOS — som avsnitten 03 till 06 visat. Därför kan slutsatsen om de två ögruppernas suveränitet inte bygga på Niostrecksgränsen.',
    'sovereignty_seal_quote' => 'Vietnam löser tvister med <strong>fredliga medel</strong>, på grundval av internationell rätt — särskilt UNCLOS 1982 — med sikte på ett Sydkinesiskt hav präglat av fred, samarbete och utveckling.',
    'sovereignty_seal_cite' => 'Vietnams ståndpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Huvudprojektet i samma ekosystem',
    'sovereignty_next_title' => 'Läs hela bevisningen om Paracelöarna – Spratlyöarna',
    'sovereignty_next_body' => 'Den detaljerade akten — dokument, kartor, tidslinje och juridiska argument — finns på <strong>paracelislands.net</strong>, där ämnet om de två ögruppernas suveränitet redovisas i sin helhet. Sidan du läser länkar bara logiskt från Niostrecksgränsen till den slutsatsen.',
    'sovereignty_next_cta' => 'Öppna paracelislands.net',
];
