<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internationell skiljedom',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tre "nej"',
    'verdict_lead' => 'Den 12 juli 2016 meddelade Permanenta skiljedomstolen (PCA) i Haag — inrättad enligt bilaga VII till UNCLOS, i målet Filippinerna mot Kina — en dom som avvisade anspråket på Niostrecksgränsen. <em>Klicka på varje kort för att läsa ordalydelsen.</em>',
    'verdict_card1_khong' => 'NEJ',
    'verdict_card1_title' => 'historisk rätt',
    'verdict_card1_short' => 'Det finns ingen rättslig grund för Kina att hävda historiska rättigheter till resurser i havsområdet inom Niostrecksgränsen.',
    'verdict_card1_quote' => '“Det finns ingen rättslig grund för att Kina hävdar historiska rättigheter till de resurser som finns i havsområdet inom Niostrecksgränsen.”',
    'verdict_card1_more' => '+ Läs domen',
    'verdict_card2_khong' => 'NEJ',
    'verdict_card2_title' => 'bildande av EEZ',
    'verdict_card2_short' => 'Ingen av enheterna i Spratlyöarna uppfyller villkoren för att skapa en exklusiv ekonomisk zon för Kina — inte ens Ba Binh-ön.',
    'verdict_card2_quote' => '“Ingen enhet i Spratlyöarna har förmåga att skapa en exklusiv ekonomisk zon.”',
    'verdict_card2_more' => '+ Läs domen',
    'verdict_card3_khong' => 'NEJ',
    'verdict_card3_title' => 'lagligt agerande',
    'verdict_card3_short' => 'Kina kränkte Filippinernas suveräna rättigheter, hindrade fiske och skadade den marina miljön.',
    'verdict_card3_quote' => '“Kina har kränkt Filippinernas suveräna rättigheter, ingripit i fisket vid Scarboroughrevet och orsakat allvarlig skada på korallrevsmiljön.”',
    'verdict_card3_more' => '+ Läs domen',
    'verdict_extra1' => 'Niostrecksgränsen, som Kina själv har ritat, är <strong>inte förenlig</strong> med UNCLOS 1982.',
    'verdict_extra2' => 'Kina har skadat ekosystemet i Spratlyöarna genom överexploatering och uppförande av konstgjorda öar.',
    'verdict_extra3' => 'Kinas agerande ökar risken för konflikt med Filippinerna.',
    'verdict_extra4' => 'Ba Binh-ön (som kontrolleras av Taiwan) kan inte heller skapa en EEZ.',
    'verdict_subtitle' => 'Varför strider den mot UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 avgränsar tydligt havszonerna utifrån kuststatens baslinjer. Anspråket på Niostrecksgränsen går utanför denna ram och kan därför inte förenas med den.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialhav (sjömil)',
    'verdict_zone1_body' => 'Det nationella havsområde som en stat har suveränitet över, räknat från baslinjen.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Exklusiv ekonomisk zon',
    'verdict_zone2_body' => 'EEZ — kuststaten har suveräna rättigheter till resurser inom detta område.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalsockel (max, sjömil)',
    'verdict_zone3_body' => 'Rättigheter till havsbottnens resurser, enligt fastställda geologiska villkor.',
    'verdict_foot' => 'Inom denna ram har "historiska rättigheter" över ett helt öppet havsområde — såsom Niostrecksgränsen antyder — <em>ersatts</em> av UNCLOS rättsordning, som även Kina själv är part i.',
];
