<?php

return [
    'witnesses_index' => 'Gamla kartor',
    'witnesses_label' => 'Gamla kinesiska kartor',
    'witnesses_title' => 'Den sydligaste gränsen når endast',
    'witnesses_title_accent' => 'Hainanön',
    'witnesses_lead' => 'De gamla kartor som ritats av kinesiska författare — ordnade kronologiskt — visar alla att <em>Hainanön är Kinas sydligaste punkt</em>, utan Paracelöarna eller Spratlyöarna. Materialet har sammanställts utifrån <em>Vietnams nationella suveränitet över Paracelöarna och Spratlyöarna</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Använd förstoringsglas',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— territoriets sydligaste punkt —',
    'witnesses_map1_svg_era' => 'Songdynastin · 1136',
    'witnesses_map1_title' => 'Karta från Songdynastin, 1136',
    'witnesses_map1_body' => 'Kinas territorium slutar vid Hainanön — Paracelöarna och Spratlyöarna låg utanför dess område.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anvilles gräns',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anvilles karta, 1735',
    'witnesses_map2_body' => 'Ritad av J.-B. B. d\'Anville; en kopia från 1740 överlämnades en gång av Tysklands förbundskansler till Kinas ledare. Qingdynastins territorium slutade vid Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"Kinas sydligaste punkt"',
    'witnesses_map3_svg_era' => 'Kejsardömets provinskarta · 1904',
    'witnesses_map3_title' => 'Kejsardömets provinskarta över geografi i sin helhet',
    'witnesses_map3_body' => 'Tryckt av Qingdynastin — anger tydligt att Kinas territoriums sydligaste punkt är Hainanön.',
    'witnesses_quote' => 'Kinas egna publicerade kartor ritade inte in Paracelöarna eller Spratlyöarna som en del av deras territorium.',
    'witnesses_timeline_aria' => 'Tidslinje över gamla kinesiska kartor',
    'witnesses_year_aria' => 'Datering',
    'lightbox_aria' => 'Visa förstorad bild',
    'lightbox_close' => 'Stäng',
    'lightbox_prev' => 'Föregående bild',
    'lightbox_next' => 'Nästa bild',
];
