<?php

return [
    'footer_index' => 'લાઇબ્રેરી',
    'footer_crest_eyebrow' => 'સત્યની લાઇબ્રેરીનું સમાપન',
    'footer_crest_quote' => '“દક્ષિણ ચીન સમુદ્રમાં શાંતિનો આધાર <b>આંતરરાષ્ટ્રીય કાયદા</b> પર છે.”',
    'footer_crest_sub' => 'દ્વેષ નહીં · માત્ર સત્ય',
    'footer_nav_aria' => 'પાનાના તળિયાની ક્રિયાઓ',
    'footer_btn_top' => 'પાનાના શરૂઆતમાં પાછા જાઓ',
    'footer_btn_verdict' => 'PCA 2016 નો ચુકાદો',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'નાઇન-ડૅશ લાઇનનો દાવો',
    'footer_brand_eyebrow' => 'વિશેષ વિષય · વિયેતનામની સાર્વભૌમત્વ',
    'footer_brand_body' => 'નાઇન-ડૅશ લાઇન અંગે નિષ્પક્ષ તથ્યો, આંતરરાષ્ટ્રીય કાયદા, PCA 2016ના ચુકાદા અને ઐતિહાસિક દસ્તાવેજો દ્વારા સ્પષ્ટીકરણ — <strong>"પેરાસેલ ટાપુઓ અને સ્પ્રેટલી ટાપુઓ"</strong> પર સાર્વભૌમત્વ વિષયક ઊંડાણપૂર્વકના પાનાઓનું પૂરક. ચીનના અયોગ્ય દાવાઓને ઇતિહાસ અને પુરાવાઓ દ્વારા ખંડિત કરે છે.',
    'footer_refs_title' => 'સંદર્ભ સ્ત્રોતો',
    'footer_ref1' => 'PCA નો ચુકાદો, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — સંપૂર્ણ લખાણ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ઐતિહાસિક દસ્તાવેજો અને પ્રાચીન નકશાઓ',
    'footer_toc_title' => 'પાનાનું વિષયસૂચિ',
    'footer_toc1' => 'નાઇન-ડૅશ લાઇન શું છે',
    'footer_toc2' => 'ઉદ્ભવ',
    'footer_toc3' => 'તે વિવાદાસ્પદ કેમ છે',
    'footer_toc4' => 'આંતરરાષ્ટ્રીય સમુદાય કેમ વિરોધ કરે છે',
    'footer_toc5' => 'મૌન સાક્ષીઓ',
    'footer_toc6' => 'PCA 2016 નો ચુકાદો',
    'footer_toc7' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ',
    'footer_copy_eyebrow' => 'લાભરહિત પ્રોજેક્ટ',
    'footer_copy_title' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ વિયેતનામના છે',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — વિયેતનામની સાર્વભૌમત્વ પરિપ્રેક્ષ્યમાં નાઇન-ડૅશ લાઇન વિષયક વિશેષ પાનું.',
    'footer_copy_body' => 'નાઇન-ડૅશ લાઇનના દાવાની વ્યાખ્યા <strong>નિષ્પક્ષ તથ્યો</strong>, <strong>આંતરરાષ્ટ્રીય કાયદા</strong>, PCA 2016ના ચુકાદા અને ઐતિહાસિક દસ્તાવેજો દ્વારા કરે છે — પેરાસેલ ટાપુઓ અને સ્પ્રેટલી ટાપુઓ પર સાર્વભૌમત્વ વિષયક ઊંડાણપૂર્વકના પાનાઓનું પૂરક.',
    'footer_copy_ecosystem_aria' => 'એક જ પ્રોજેક્ટના પાનાઓ',
    'footer_copy_ecosystem_label' => 'એક જ ઇકોસિસ્ટમ',
    'footer_copy_disclaimer' => 'આ સામગ્રી શિક્ષણ અને જાગૃતિ વધારવા માટે છે; તે વિયેતનામ સરકારના અધિકૃત અભિપ્રાયનું સ્થાન લેતી નથી.',
    'footer_copy' => '<strong>© :year નાઇન-ડૅશ લાઇન</strong> — "પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ વિયેતનામના છે" નામના લાભરહિત પ્રોજેક્ટનો એક ભાગ, સિસ્ટમ હેઠળ: <a href="https://paracelislands.net/gu" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/gu" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/gu" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/gu" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/gu" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'પાનાની સામગ્રી પ્રતિબદ્ધતાઓ',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 નો ચુકાદો',
    'footer_chip3' => 'ઐતિહાસિક પુરાવા',
    'footer_chip4' => 'પ્રાચીન નકશાઓ',
    'footer_chip5' => 'નિષ્પક્ષ સત્ય',
    'footer_chip6' => 'દક્ષિણ ચીન સમુદ્રમાં શાંતિ',
];
