<?php

return [
    'footer_index' => 'ગ્રંથાલય',
    'footer_crest_eyebrow' => 'સત્યના ગ્રંથાલયનું સમાપન',
    'footer_crest_quote' => '“દક્ષિણ ચીન સમુદ્રમાં શાંતિનો આધાર <b>આંતરરાષ્ટ્રીય કાયદા</b> પર છે.”',
    'footer_crest_sub' => 'દ્વેષ નહીં · માત્ર સત્ય',
    'footer_nav_aria' => 'પાના અંતની ક્રિયાઓ',
    'footer_btn_top' => 'પાનાની શરૂઆત પર જાઓ',
    'footer_btn_verdict' => 'PCA 2016નો ચુકાદો',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'નાઇન-ડૅશ લાઇનની દાવો',
    'footer_brand_eyebrow' => 'વિશેષ વિષય · વિયેતનામની સાવરેનિટી',
    'footer_brand_body' => 'નાઇન-ડૅશ લાઇનને નિષ્પક્ષ તથ્યો, આંતરરાષ્ટ્રીય કાયદા, PCA 2016ના ચુકાદા અને ઐતિહાસિક દસ્તાવેજો દ્વારા સમજાવે છે — બે દ્વીપસમૂહોની <strong>"પેરાસેલ ટાપુઓ અને સ્પ્રેટલી ટાપુઓ"</strong>ની સાવરેનિટી પરના ઊંડાણપૂર્વકના પાનાંઓને પૂરક બનાવે છે. ચીનના અયોગ્ય દાવાને ઇતિહાસ અને પુરાવાઓ દ્વારા ખંડિત કરે છે.',
    'footer_refs_title' => 'સંદર્ભ સ્ત્રોતો',
    'footer_ref1' => 'PCAનો ચુકાદો, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — સંપૂર્ણ લખાણ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ઐતિહાસિક દસ્તાવેજો અને પ્રાચીન નકશાઓ',
    'footer_toc_title' => 'પાનાંની સામગ્રી સૂચિ',
    'footer_toc1' => 'નાઇન-ડૅશ લાઇન શું છે',
    'footer_toc2' => 'ઉદભવ',
    'footer_toc3' => 'વિવાદ કેમ ઊભો થાય છે',
    'footer_toc4' => 'આંતરરાષ્ટ્રીય વિરોધ કેમ છે',
    'footer_toc5' => 'શાંત સાક્ષીઓ',
    'footer_toc6' => 'PCA 2016નો ચુકાદો',
    'footer_toc7' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ',
    'footer_copy_eyebrow' => 'બિનલાભકારી પ્રોજેક્ટ',
    'footer_copy_title' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ વિયેતનામના છે',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — વિયેતનામની સાવરેનિટી生态તંત્રમાં નાઇન-ડૅશ લાઇન પરનો વિશેષ વિષય પાનું.',
    'footer_copy_body' => 'નાઇન-ડૅશ લાઇનના દાવાને <strong>નિષ્પક્ષ તથ્યો</strong>, <strong>આંતરરાષ્ટ્રીય કાયદા</strong>, PCA 2016ના ચુકાદા અને ઐતિહાસિક દસ્તાવેજો દ્વારા સમજાવે છે — પેરાસેલ ટાપુઓ અને સ્પ્રેટલી ટાપુઓની સાવરેનિટી પરના ઊંડાણપૂર્વકના પાનાંઓને પૂરક બનાવે છે.',
    'footer_copy_ecosystem_aria' => 'આ પ્રોજેક્ટના અન્ય પાનાંઓ',
    'footer_copy_ecosystem_label' => 'એક જ生态તંત્રમાં',
    'footer_copy_disclaimer' => 'આ સામગ્રી શિક્ષણ અને જાગૃતિ વધારવા માટે છે; તે વિયેતનામ સરકારના સત્તાવાર અભિપ્રાયનું સ્થાન લેતી નથી.',
    'footer_copy' => '<strong>© :year નાઇન-ડૅશ લાઇન</strong> — બિનલાભકારી પ્રોજેક્ટ <strong>પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ વિયેતનામના છે</strong>નો એક ભાગ, આ સિસ્ટમનો સભ્ય: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'પાનાંની સામગ્રી પ્રતિબદ્ધતા',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016નો ચુકાદો',
    'footer_chip3' => 'ઐતિહાસિક પુરાવા',
    'footer_chip4' => 'પ્રાચીન નકશાઓ',
    'footer_chip5' => 'નિષ્પક્ષ તથ્યો',
    'footer_chip6' => 'દક્ષિણ ચીન સમુદ્રમાં શાંતિ',
];
