<?php

return [
    'footer_index' => 'ગ્રંથાલય',
    'footer_crest_eyebrow' => 'સત્યના ગ્રંથાલયનો અંત',
    'footer_crest_quote' => '“દક્ષિણ ચીન સમુદ્રમાં શાંતિનું નિર્માણ <b>આંતરરાષ્ટ્રીય કાયદા</b>ના આધાર પર થાય છે.”',
    'footer_crest_sub' => 'દ્વેષ નહીં · માત્ર સત્ય',
    'footer_nav_aria' => 'પાનાના અંતના ક્રિયાકલાપો',
    'footer_btn_top' => 'પાનાની શરૂઆત પર પાછા',
    'footer_btn_verdict' => 'PCA 2016 નો ચુકાદો',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'નાઇન-ડૅશ લાઇન',
    'footer_brand_body' => 'વસ્તુનિષ્ઠ સત્ય, આંતરરાષ્ટ્રીય કાયદા અને ઐતિહાસિક દસ્તાવેજો પર આધારિત એક સ્પષ્ટીકરણાત્મક વેબસાઇટ — પુરાવા દ્વારા નાઇન-ડૅશ લાઇનના દાવાને નકારે છે, સૂત્રોથી નહીં.',
    'footer_refs_title' => 'સંદર્ભ સ્ત્રોતો',
    'footer_ref1' => 'PCA નો ચુકાદો, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — સંપૂર્ણ પાઠ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ઐતિહાસિક સામગ્રી અને પ્રાચીન નકશાઓ',
    'footer_toc_title' => 'પાનાનું વિષય સૂચિ',
    'footer_toc1' => 'નાઇન-ડૅશ લાઇન શું છે',
    'footer_toc2' => 'ઉદ્ભવ',
    'footer_toc3' => 'તે વિવાદાસ્પદ કેમ છે',
    'footer_toc4' => 'આંતરરાષ્ટ્રીય સમુદાય કેમ વિરોધ કરે છે',
    'footer_toc5' => 'મૌન સાક્ષીઓ',
    'footer_toc6' => 'PCA 2016 નો ચુકાદો',
    'footer_toc7' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — દક્ષિણ ચીન સમુદ્ર વિશેની વસ્તુનિષ્ઠ સત્ય.<br>ઇકોસિસ્ટમ: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'અક્ષાંશ-રેખાંશ નથી',
];
