<?php

return [
    'nav_logo_name' => 'નાઇન-ડૅશ લાઇન',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'નાઇન-ડૅશ લાઇન',
    'nav_rail_aria' => 'વિભાગવાર નેવિગેશન',
    'nav_rail_what' => 'વ્યાખ્યા',
    'nav_rail_origin' => 'ઉદ્ભવ',
    'nav_rail_dispute' => 'વિવાદ',
    'nav_rail_opposition' => 'વિરોધ',
    'nav_rail_witnesses' => 'પ્રાચીન નકશા',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'પેરાસેલ ટાપુઓ – સ્પ્રેટલી ટાપુઓ',
    'nav_sound_off' => 'પૃષ્ઠભૂમિ સંગીત ચાલુ કરો',
    'nav_sound_on' => 'પૃષ્ઠભૂમિ સંગીત બંધ કરો',
    'nav_share' => 'શેર કરો',
    'dialog_title' => 'પ્રદર્શન ભાષા',
    'language' => 'ભાષા',
    'display_hint' => ':count ભાષાઓ',
    'search_placeholder' => 'ભાષા શોધો…',
    'cancel' => 'રદ કરો',
    'apply' => 'લાગુ કરો',
    'sound_off' => 'પૃષ્ઠભૂમિ અવાજ ચાલુ કરો',
    'sound_on' => 'પૃષ્ઠભૂમિ અવાજ બંધ કરો',
    'lang_trigger' => 'ભાષા પસંદ કરો',
    'close' => 'બંધ કરો',
    'no_results' => 'કોઈ ભાષા મળી નથી',
    'contribute' => 'શેર કરો',
];
