<?php

return [
    'witnesses_index' => 'પુરાતન નકશાઓ',
    'witnesses_label' => 'શાંત સાક્ષીઓ',
    'witnesses_title' => 'ના પુરાતન નકશાઓ',
    'witnesses_title_accent' => 'તેમના પોતાના',
    'witnesses_lead' => 'ઘણી સદીઓ સુધી, ચીનના અધિકૃત નકશાઓમાં <em>હૈનાન ટાપુને પ્રદેશના દક્ષિણતમ બિંદુ</em> તરીકે નોંધવામાં આવ્યું છે — સમગ્ર દક્ષિણ ચીન સમુદ્રને ઘેરી લેતી કોઈ U-આકારની રેખા નહોતી. દક્ષિણ સીમા પર નજીકથી નજર કરવા માટે લેન્સનો ઉપયોગ કરો.',
    'witnesses_hint' => '⌖ લૂપથી જુઓ',
    'witnesses_map1_svg_hainan' => 'હૈનાન 海南',
    'witnesses_map1_svg_south' => '— પ્રદેશનો દક્ષિણતમ બિંદુ —',
    'witnesses_map1_svg_era' => 'સોંગ વંશ · 1136',
    'witnesses_map1_title' => 'સોંગ વંશનો નકશો, 1136',
    'witnesses_map1_body' => 'ચીનનો પ્રદેશ હૈનાન ટાપુએ અટકે છે — પેરાસેલ ટાપુઓ અને સ્પ્રેટલી ટાપુઓ તેના ક્ષેત્રાધિકારની બહાર છે.',
    'witnesses_map2_svg_hainan' => 'હૈનાન',
    'witnesses_map2_svg_south' => 'd\'Anville સીમા',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anvilleનો નકશો, 1735',
    'witnesses_map2_body' => 'J.-B. B. d\'Anville દ્વારા દોરાયેલ; 1740ની નકલ જર્મન ચાન્સેલરે એક વખત ચીનના નેતૃત્વને ભેટ આપી હતી. ચિંગ વંશનો પ્રદેશ હૈનાન સુધી અટકે છે.',
    'witnesses_map3_svg_hainan' => '海南 હૈનાન',
    'witnesses_map3_svg_south' => '"ચીનનો દક્ષિણતમ બિંદુ"',
    'witnesses_map3_svg_era' => 'ક્વાંગથુંગ શીજી તુજી · 1904',
    'witnesses_map3_title' => 'ક્વાંગથુંગ શીજી તુજીનું સમગ્ર નકશો',
    'witnesses_map3_body' => 'ચિંગ વંશ દ્વારા છાપેલ — તેમાં સ્પષ્ટ રીતે ચીનના પ્રદેશનો દક્ષિણતમ બિંદુ હૈનાન ટાપુ તરીકે દર્શાવવામાં આવ્યો છે.',
    'witnesses_quote' => 'તેમના પૂર્વજોના દસ્તાવેજોમાં જ નાઇન-ડૅશ લાઇન દોરવામાં આવી નહોતી.',
];
