<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Pungkasan perpustakaan kasunyatan',
    'footer_crest_quote' => '“Tentrem ing Segara Cina Kidul dibangun ing dhasar <b>Hukum internasional</b>.”',
    'footer_crest_sub' => 'Tanpa sengit · Mung kasunyatan',
    'footer_nav_aria' => 'Tumindak ing pérangan ngisor kaca',
    'footer_btn_top' => 'Menyang ndhuwur kaca',
    'footer_btn_verdict' => 'Putusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Yeniké Klaim Garis Sembilan Garis Putus',
    'footer_brand_eyebrow' => 'Kaca tema · Kedaulatan Vietnam',
    'footer_brand_body' => 'Njlentrehake Garis Sembilan Garis Putus liwat kasunyatan objektif, hukum internasional, putusan PCA 2016 lan bahan sejarah — minangka pelengkap kanggo kaca-kaca jero babagan kedaulatan loro kapuloan <strong>"Kapuloan Paracel lan Kapuloan Spratly"</strong>. Nolak klaim sing ora nduwèni dasar saka Tiongkok nganggo sejarah lan bukti.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Putusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks lengkap',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta lawas',
    'footer_toc_title' => 'Dhaftar isi kaca',
    'footer_toc1' => 'Apa iku Garis Sembilan Garis Putus',
    'footer_toc2' => 'Asal-usule',
    'footer_toc3' => 'Napa dadi kontroversi',
    'footer_toc4' => 'Napa ditentang internasional',
    'footer_toc5' => 'Saksi bisu',
    'footer_toc6' => 'Putusan PCA 2016',
    'footer_toc7' => 'Kapuloan Paracel – Kapuloan Spratly',
    'footer_copy_eyebrow' => 'Proyek nirlaba',
    'footer_copy_title' => 'Kapuloan Paracel – Kapuloan Spratly kagungan Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Kaca tema babagan Garis Sembilan Garis Putus ing ékosistem kedaulatan Vietnam.',
    'footer_copy_body' => 'Njlentrehake klaim Garis Sembilan Garis Putus liwat <strong>kasunyatan objektif</strong>, <strong>hukum internasional</strong>, putusan PCA 2016 lan bahan sejarah — minangka pelengkap kanggo kaca-kaca jero babagan kedaulatan loro kapuloan Kapuloan Paracel lan Kapuloan Spratly.',
    'footer_copy_ecosystem_aria' => 'Kaca-kaca sakproyek',
    'footer_copy_ecosystem_label' => 'Siji ékosistem',
    'footer_copy_disclaimer' => 'Isiné dimaksudaké kanggo pendidikan lan ningkataké kawruh; ora nggantèkaké pandhangan resmi saka Negara Vietnam.',
    'footer_copy' => '<strong>© :year Garis Sembilan Garis Putus</strong> — Bagean saka proyek nirlaba <strong>Kapuloan Paracel – Kapuloan Spratly kagungan Vietnam</strong> ing sistem: <a href="https://paracelislands.net/jv" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/jv" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/jv" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/jv" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/jv" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Komitmen isi kaca',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Putusan PCA 2016',
    'footer_chip3' => 'Bukti sejarah',
    'footer_chip4' => 'Peta lawas',
    'footer_chip5' => 'Kasunyatan objektif',
    'footer_chip6' => 'Tentrem Segara Cina Kidul',
];
