<?php

return [
    'footer_index' => 'Pustaka',
    'footer_crest_eyebrow' => 'Panutup pustaka bebener',
    'footer_crest_quote' => '“Tentrem ing Segara Cina Kidul dibangun ing dhasar <b>Hukum internasional</b>.”',
    'footer_crest_sub' => 'Ora sengit · Mung bebener',
    'footer_nav_aria' => 'Tumindak ing sisih ngisor kaca',
    'footer_btn_top' => 'Mbalik menyang ndhuwur',
    'footer_btn_verdict' => 'Putusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Garis Sembilan Garis Putus',
    'footer_brand_body' => 'Situs penjelasan adhedhasar bebener objektif, hukum internasional, lan dokumen sejarah — mbantah klaim Garis Sembilan Garis Putus nganggo bukti, dudu slogan.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Putusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks lengkap',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta kuna',
    'footer_toc_title' => 'Daftar isi kaca',
    'footer_toc1' => 'Apa kuwi Garis Sembilan Garis Putus',
    'footer_toc2' => 'Asal-usul',
    'footer_toc3' => 'Napa dadi kontroversi',
    'footer_toc4' => 'Napa ditentang internasional',
    'footer_toc5' => 'Saksi bisu',
    'footer_toc6' => 'Putusan PCA 2016',
    'footer_toc7' => 'Kapuloan Paracel – Kapuloan Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Bebener objektif ngenani Segara Cina Kidul.<br>Ekosistem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Tanpa koordinat',
];
