<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Panutup perpustakaan bebener',
    'footer_crest_quote' => '“Rukun ing Segara Tiongkok Kidul dibangun ing dhasar <b>Hukum internasional</b>.”',
    'footer_crest_sub' => 'Ora sengit · Mung bebener',
    'footer_nav_aria' => 'Tumindak ing ngisor kaca',
    'footer_btn_top' => 'Mbalik menyang ndhuwur',
    'footer_btn_verdict' => 'Putusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Pratelan Garis Sembilan Garis Putus',
    'footer_brand_eyebrow' => 'Kaca tema · Kadhaulatan Vietnam',
    'footer_brand_body' => 'Nerangake Garis Sembilan Garis Putus liwat bebener objektif, hukum internasional, putusan PCA 2016, lan bahan sejarah — minangka pelengkap kanggo kaca-kaca jero babagan kadhaulatan loro kapuloan <strong>"Kapuloan Paracel lan Kapuloan Spratly"</strong>. Nolak pratelan ora masuk akal saka Tiongkok nganggo sejarah lan bukti.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Putusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks lengkap',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta lawas',
    'footer_toc_title' => 'Daftar isi kaca',
    'footer_toc1' => 'Apa kuwi Garis Sembilan Garis Putus',
    'footer_toc2' => 'Asal-usulé',
    'footer_toc3' => 'Napa dadi sengketa',
    'footer_toc4' => 'Napa ditentang internasional',
    'footer_toc5' => 'Saksi meneng',
    'footer_toc6' => 'Putusan PCA 2016',
    'footer_toc7' => 'Paracel – Spratly',
    'footer_copy_eyebrow' => 'Proyek nirlaba',
    'footer_copy_title' => 'Paracel – Spratly iku kagungané Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Kaca tema babagan Garis Sembilan Garis Putus ing ékosistem kadhaulatan Vietnam.',
    'footer_copy_body' => 'Nerangake pratelan Garis Sembilan Garis Putus liwat <strong>bebener objektif</strong>, <strong>hukum internasional</strong>, putusan PCA 2016, lan bahan sejarah — minangka pelengkap kanggo kaca-kaca jero babagan kadhaulatan loro kapuloan Paracel lan Spratly.',
    'footer_copy_ecosystem_aria' => 'Kaca-kaca siji proyek',
    'footer_copy_ecosystem_label' => 'Sajroning ékosistem sing padha',
    'footer_copy_disclaimer' => 'Konten iki kanggo pendidikan lan ningkataké kesadaran; ora ngganteni pandhangan resmi saka Negara Vietnam.',
    'footer_copy' => '<strong>© :year Garis Sembilan Garis Putus</strong> — Bagéan saka proyek nirlaba <strong>Paracel – Spratly iku kagungané Vietnam</strong> ing sistem: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Komitmen isi kaca',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Putusan PCA 2016',
    'footer_chip3' => 'Bukti sejarah',
    'footer_chip4' => 'Peta lawas',
    'footer_chip5' => 'Bebener objektif',
    'footer_chip6' => 'Rukuné Segara Tiongkok Kidul',
];
