<?php

return [
    'nav_logo_name' => 'Garis Sembilan Garis Putus',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Garis Sembilan Garis Putus',
    'nav_rail_aria' => 'Pandhu arah miturut bagean',
    'nav_rail_what' => 'Définisi',
    'nav_rail_origin' => 'Asal-usul',
    'nav_rail_dispute' => 'Pasulayan',
    'nav_rail_opposition' => 'Panentangan',
    'nav_rail_witnesses' => 'Peta kuna',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Kapuloan Paracel – Kapuloan Spratly',
    'nav_sound_off' => 'Uripake musik latar',
    'nav_sound_on' => 'Pateni musik latar',
    'nav_share' => 'Enggo bareng',
    'dialog_title' => 'Basa tampilan',
    'language' => 'Basa',
    'display_hint' => ':count basa',
    'search_placeholder' => 'Golèk basa…',
    'cancel' => 'Batal',
    'apply' => 'Terapake',
    'sound_off' => 'Uripake swara latar',
    'sound_on' => 'Pateni swara latar',
    'lang_trigger' => 'Pilih basa',
    'close' => 'Tutup',
    'no_results' => 'Ora ditemokaké basa',
    'contribute' => 'Enggo bareng',
];
