<?php

return [
    'opposition_index' => 'Aja',
    'opposition_label' => 'Kenging punapa internasional nentang',
    'opposition_title' => 'Nentang adhedhasar',
    'opposition_title_accent' => 'undhang-undhang, dudu rasa',
    'opposition_lead' => 'Sasampunipun Garis Sembilan Garis Putus diajukake marang Perserikatan Bangsa-Bangsa ing taun 2009, kathah negara lan sarjana sampun nentang — kanthi argumentasi hukum kang cetha.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mei',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Mung sedina sawisé Tiongkok ngaturaké peta Garis Sembilan Garis Putus marang Sekretaris Jenderal Perserikatan Bangsa-Bangsa (7/5/2009), negara-negara iki genti-genti ngirim nota diplomatik protes, nolak klaim kasebut.',
    'opposition_voice1_chip1' => 'Nota protes',
    'opposition_voice1_chip2' => 'Ora cocog karo UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipina',
    'opposition_voice2_body' => 'Ngirim layang diplomatik menyang Perserikatan Bangsa-Bangsa, nyatakaké yèn klaim Tiongkok ing Segara China Kidul iku “ora nduwèni dhasar miturut hukum internasional” — dadi landhesan kanggo gugatan menyang Tribunal Arbitrase sawisé iku.',
    'opposition_voice2_chip1' => 'Landhesan gugatan PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kementerian Luar Negeri Amerika Serikat — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analisis nuduhaké: peta-peta ing taun-taun béda ora konsisten ing posisi garis; garis mau mlebu menyang daratan dudu nganggo garis tengah; akèh entitas ora cukup nyukupi syarat “pulo” kanggo nduwèni EEZ.',
    'opposition_voice3_chip1' => 'Ora nyukupi kahanan hukum',
    'opposition_voice3_chip2' => 'Analisis resmi',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '“Banyu sajarah” wis ora relevan',
    'opposition_voice4_body' => 'Konsep iki mung ditrapaké kanggo teluk utawa banyu cedhak pesisir — ora bisa ngliputi sakabehing wilayah segara jembar. Ing taun 2003, Taiwan dhéwé uga wis nolak kawicaksanan “banyu sajarah” sing tau disinggung ing taun 1993.',
    'opposition_voice4_chip1' => 'Malah sarjana Tiongkok ora sarujuk kabeh',
];
