<?php

return [
    'opposition_index' => 'Tandhingan',
    'opposition_label' => 'Kenging punapa donya nentang',
    'opposition_title' => 'Tandhingan adhedhasar',
    'opposition_title_accent' => 'hukum, dudu raos',
    'opposition_lead' => 'Sanalika Garis Sembilan Garis Putus dipunaturaken dhateng Perserikatan Bangsa-Bangsa ing taun 2009, kathah negara lan para akademisi sampun nentang — kanthi alesan hukum ingkang cetha.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mei',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Mung sawengi sawisé Tiongkok ngaturaken peta Garis Sembilan Garis Putus dhateng Sekretaris Jenderal Perserikatan Bangsa-Bangsa (7/5/2009), negara-negara punika gantian ngirim nota diplomatik protes, nolak klaim punika.',
    'opposition_voice1_chip1' => 'Nota protes',
    'opposition_voice1_chip2' => 'Ora selaras karo UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipina',
    'opposition_voice2_body' => 'Ngirim layang diplomatik dhateng Perserikatan Bangsa-Bangsa, mratelakaken bilih klaim Tiongkok ing Segara Cina Kidul punika “tanpa dhasar miturut hukum internasional” — dados dhasar tumrap gugatan dhateng Tribunal Arbitrase salajengipun.',
    'opposition_voice2_chip1' => 'Dhasar gugatan PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kementerian Luar Negeri Amerika Sarékat — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analisis nuduhaken: peta-peta ing taun beda-beda ora ajeg ing posisi garis wates; garis punika mlebet dhateng daratan tinimbang migunakaken garis tengah; kathah unsur boten nyukupi standar “pulo” supados saged gadhah EEZ.',
    'opposition_voice3_chip1' => 'Ora nyukupi syarat hukum',
    'opposition_voice3_chip2' => 'Analisis resmi',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '“Banyu sajarah” sampun ketinggalan jaman',
    'opposition_voice4_body' => 'Konsep punika namung trep tumrap teluk, lekukan banyu ing pinggir pesisir — boten saged nglimputi sakabehe tlatah segara ingkang amba. Ing taun 2003, Taiwan piyambak ugi sampun nampik kawicaksanan “banyu sajarah” ingkang nate dipunaturaken taun 1993.',
    'opposition_voice4_chip1' => 'Malah para sarjana Tiongkok ugi boten sarujuk',
];
