<?php

return [
    'sovereignty_index' => 'Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_label' => 'Kasimpulan sing mesthi',
    'sovereignty_title' => 'Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_title_accent' => 'iku kagungané Vietnam',
    'sovereignty_lead' => 'Kaca iki nerangake Garis Sembilan Garis Putus. Bagean kasimpulan mangsuli pitakon sabanjuré: sapa sing duwé kedaulatan marang loro kapuloan Kapuloan Paracel lan Kapuloan Spratly? Miturut sajarah pamréntahan lan hukum internasional, wangsulan sing konsisten yaiku Vietnam.',
    'sovereignty_thesis_label' => 'Argumentasi gabungan',
    'sovereignty_thesis_lock1' => 'Ora ana koordinat legal',
    'sovereignty_thesis_lock2' => 'PCA 2016 nolak',
    'sovereignty_thesis_lock3' => 'Peta kuna ora nyakup',
    'sovereignty_thesis_body' => 'Sawisé enem bagean ing ndhuwur, telung perkara wis cetha: Garis Sembilan Garis Putus digambar tangan, ora nduwèni koordinat legal; Pengadilan Arbitrase taun 2016 nolak klaim kasebut; peta kuna saka Tiongkok dhéwé ora nyakup Segara Cina Kidul. Kedaulatan Vietnam ora adhedhasar slogan, nanging adhedhasar tumindak nagara Vietnam — wiwit jaman para panguwasa Nguyễn — sing ngatur kanthi tentrem lan terus-terusan nalika loro kapuloan kuwi isih dadi tanah tanpa panguwasa.',
    'sovereignty_spine_caption' => 'Tenger pamréntahan sing terus-terusan',
    'sovereignty_spine_title' => 'Siji garis wektu, tanpa putus',
    'sovereignty_spine_range' => 'Abad kaping XVII → saiki',
    'sovereignty_chron1_year' => 'Abad XVII',
    'sovereignty_chron1_title' => 'Papatonga Hoàng Sa',
    'sovereignty_chron1_body' => 'Para panguwasa Nguyễn ngutus Papatonga Hoàng Sa kanggo nliti, ngukur alur segara, lan ngupaya asil ing segara — nindakake wewenang pamréntahan nyata.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Prabu Gia Long',
    'sovereignty_chron2_body' => 'Nandur gendera ing kapuloan Hoàng Sa, negesake kedaulatan Vietnam ing ngarepé jagad wektu semana.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Prabu Minh Mạng',
    'sovereignty_chron3_body' => 'Ngukur, ngadegaké prasasti, lan nyathet kapuloan kuwi ing peta resmi kraton.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Warisan sing terus nyambung',
    'sovereignty_chron4_body' => 'Prancis ngakoni lan nerusaké pamréntahan; nggabungaké Hoàng Sa menyang provinsi Thừa Thiên — dhasar kanggo Nagara Vietnam saiki.',
    'sovereignty_chron5_year' => 'Saiki',
    'sovereignty_chron5_title' => 'Hukum lan praktik',
    'sovereignty_chron5_body' => 'Vietnam ngatur adhedhasar UNCLOS, diplomasi, lan arsip; klaim Garis Sembilan Garis Putus ora bisa nggantèkaké bukti iki.',
    'sovereignty_balance_label' => 'Keseimbangan bukti',
    'sovereignty_balance_medallion_title' => 'Mbandhingaké loro sisih',
    'sovereignty_vn_tag' => 'Sisih Vietnam',
    'sovereignty_vn_title' => 'Kedaulatan ditemtokake liwat tumindak',
    'sovereignty_vn_body' => 'Pangrebutan nyata nalika tanah isih tanpa panguwasa, banjur diatur kanthi terbuka ing pirang-pirang abad — ana châu bản, prasasti, peta, lan arsip administratif. Cara iki selaras karo UNCLOS lan praktik internasional.',
    'sovereignty_dash_tag' => 'Sisih Garis Sembilan Garis Putus',
    'sovereignty_dash_title' => 'Klaim ora bisa ngimbangi bukti',
    'sovereignty_dash_body' => 'Siji garis digambar taun 1948, tanpa koordinat, wis ditolak dening PCA 2016 lan bertentangan karo UNCLOS — kaya sing wis diterangake ing bagean 03 nganti 06. Mula, kasimpulan bab kedaulatan loro kapuloan ora bisa didhasaraké marang Garis Sembilan Garis Putus.',
    'sovereignty_seal_quote' => 'Vietnam ngrampungi pasulayan kanthi <strong>cara tentrem</strong>, adhedhasar hukum internasional — utamané UNCLOS 1982 — kanthi tujuan Segara Cina Kidul sing tentrem, kerja bareng, lan maju.',
    'sovereignty_seal_cite' => 'Panyatané Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyek utama ing ékosistem sing padha',
    'sovereignty_next_title' => 'Waca bukti lengkap bab Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_next_body' => 'Berkas rinci — dokumen, peta, garis wektu, lan alesan hukum — ana ing situs <strong>paracelislands.net</strong>, sing njlentrehaké kanthi pepak topik kedaulatan loro kapuloan. Kaca sing kokwaca iki mung nyambungaké logika saka Garis Sembilan Garis Putus menyang kasimpulan kuwi.',
    'sovereignty_next_cta' => 'Bukak paracelislands.net',
];
