<?php

return [
    'sovereignty_index' => 'Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_label' => 'Panutup kang mesthi',
    'sovereignty_title' => 'Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_title_accent' => 'yaiku kagungane Vietnam',
    'sovereignty_lead' => 'Kaca iki nerangake Garis Sembilan Garis Putus. Bagéan panutup mangsuli pitakon sabanjuré: sapa kang nduwèni kedaulatan marang loro kapuloan, yaiku Kapuloan Paracel lan Kapuloan Spratly? Miturut sajarah pamréntahan lan hukum internasional, wangsulane konsisten yaiku Vietnam.',
    'sovereignty_thesis_label' => 'Poin gabungan',
    'sovereignty_thesis_lock1' => 'Ora ana koordinat hukum',
    'sovereignty_thesis_lock2' => 'PCA 2016 mbantah',
    'sovereignty_thesis_lock3' => 'Peta kuna ora nyakup kabeh',
    'sovereignty_thesis_body' => 'Sawisé enem bagean ing ndhuwur, telung perkara wis cetha: Garis Sembilan Garis Putus digambar tangan, ora nduwèni koordinat hukum; Pengadilan Arbitrase taun 2016 mbantah klaim mau; peta kuna saka Tiongkok dhéwé ora nyakup Segara Cina Kidul. Kedaulatan Vietnam ora gumantung marang slogan, nanging marang kasunyatan yèn negara Vietnam — wiwit jaman para priyayi Nguyễn — wis ngatur kanthi tentrem lan ajeg nalika loro kapuloan mau isih dadi tanah sing durung dikuwasani sapa-sapa.',
    'sovereignty_spine_caption' => 'Tandha pamréntahan sing terus lumaku',
    'sovereignty_spine_title' => 'Siji linimasa, tanpa pedhot',
    'sovereignty_spine_range' => 'Abad XVII → saiki',
    'sovereignty_chron1_year' => 'Abad XVII',
    'sovereignty_chron1_title' => 'Tim Hoàng Sa',
    'sovereignty_chron1_body' => 'Para priyayi Nguyễn ngutus tim Hoàng Sa kanggo nliti, ngukur dalan segara, lan ngupaya asil saka segara — nindakake kakuwatan pamréntahan nyata.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Prabu Gia Long',
    'sovereignty_chron2_body' => 'Nandur gendera ing Kapuloan Paracel, negesake kedaulatan Vietnam ing ngarepe donya nalika semana.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Prabu Minh Mạng',
    'sovereignty_chron3_body' => 'Nglakoni pangukuran, ngadegaké prasasti, lan nyatet kapuloan ing peta resmi kraton.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Diterusake kanthi ajeg',
    'sovereignty_chron4_body' => 'Prancis ngakoni lan nerusake pamréntahan; Kapuloan Paracel digandhengake marang provinsi Thừa Thiên — dadi dhasar tumrap Negara Vietnam saiki.',
    'sovereignty_chron5_year' => 'Saiki',
    'sovereignty_chron5_title' => 'Hukum lan praktik',
    'sovereignty_chron5_body' => 'Vietnam ngatur adhedhasar UNCLOS, diplomasi, lan arsip; klaim Garis Sembilan Garis Putus ora bisa ngganteni bukti iki.',
    'sovereignty_balance_label' => 'Imbangé bukti',
    'sovereignty_balance_medallion_title' => 'Mbandhingaké loro sisih',
    'sovereignty_vn_tag' => 'Sisih Vietnam',
    'sovereignty_vn_title' => 'Kedaulatan ditemtokaké liwat tumindak',
    'sovereignty_vn_body' => 'Pangrebutan nyata nalika wilayah isih tanpa sing nguwasani, banjur dipréntah kanthi terbuka sajrone pirang-pirang abad — ana châu bản, prasasti, peta, lan arsip administratif. Cara iki selaras karo UNCLOS lan praktik internasional.',
    'sovereignty_dash_tag' => 'Sisih Garis Sembilan Garis Putus',
    'sovereignty_dash_title' => 'Klaim ora bisa nutupi bukti',
    'sovereignty_dash_body' => 'Siji garis sing digambar taun 1948, tanpa koordinat, wis dibantah déning PCA 2016 lan ora selaras karo UNCLOS — kaya sing wis diterangake ing bagean 03 nganti 06. Kuwi sebabé kesimpulan babagan kedaulatan loro kapuloan ora bisa dhasarake marang Garis Sembilan Garis Putus.',
    'sovereignty_seal_quote' => 'Vietnam ngrampungaké pasulayan kanthi <strong>cara tentrem</strong>, adhedhasar hukum internasional — utamané UNCLOS 1982 — kanthi tujuan Segara Cina Kidul sing tentrem, kerja sama, lan maju.',
    'sovereignty_seal_cite' => 'Sikap Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyek utama ing ékosistem sing padha',
    'sovereignty_next_title' => 'Waca bukti lengkap babagan Kapuloan Paracel – Kapuloan Spratly',
    'sovereignty_next_body' => 'Berkas rinci — dokumen, peta, linimasa, lan argumentasi hukum — ana ing kaca <strong>paracelislands.net</strong>, sing medharaké topik kedaulatan loro kapuloan kanthi pepak. Kaca sing saiki panjenengan waca mung nyambungaké logika saka Garis Sembilan Garis Putus marang kesimpulan mau.',
    'sovereignty_next_cta' => 'Bukak paracelislands.net',
];
