<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Putusan internasional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'telu "Ora"',
    'verdict_lead' => 'Tanggal 12/7/2016, Pengadilan Arbitrase Tetap (PCA) ing The Hague — didadekake miturut Lampiran VII UNCLOS, ing prakara Filipina nglawan Tiongkok — wis nerbitake putusan sing nolak klaim Garis Sembilan Garis Putus. <em>Klik saben kertu kanggo maca teks lengkap.</em>',
    'verdict_card1_khong' => 'ORA',
    'verdict_card1_title' => 'hak historis',
    'verdict_card1_short' => 'Ora ana dhasar hukum kanggo Tiongkok nyebut hak historis marang sumber daya ing perairan sing ana ing njero Garis Sembilan Garis Putus.',
    'verdict_card1_quote' => '“Ora ana dhasar hukum kanggo Tiongkok nyebut hak historis marang sumber daya sing ana ing perairan ing njero Garis Sembilan Garis Putus.”',
    'verdict_card1_more' => '+ Maca putusan',
    'verdict_card2_khong' => 'ORA',
    'verdict_card2_title' => 'obyek sing mbentuk EEZ',
    'verdict_card2_short' => 'Ora ana siji wae obyèk ing Kapuloan Spratly sing cukup syarat kanggo mbentuk zona ekonomi eksklusif kanggo Tiongkok — kalebu Pulo Ba Bình.',
    'verdict_card2_quote' => '“Ora ana siji wae obyèk ing Kapuloan Spratly sing bisa mbentuk zona ekonomi eksklusif.”',
    'verdict_card2_more' => '+ Maca putusan',
    'verdict_card3_khong' => 'ORA',
    'verdict_card3_title' => 'tumindak sah',
    'verdict_card3_short' => 'Tiongkok nglanggar hak kedaulatan Vietnam, ngalangi panangkepan iwak, lan ngrusak lingkungan segara.',
    'verdict_card3_quote' => '“Tiongkok wis nglanggar hak kedaulatan Vietnam, campur tangan ing kegiatan panangkepan iwak ing Karang Scarborough lan nimbulake karusakan serius marang lingkungan terumbu karang.”',
    'verdict_card3_more' => '+ Maca putusan',
    'verdict_extra1' => 'Garis Sembilan Garis Putus sing digambar dhewe dening Tiongkok <strong>ora cocog</strong> karo UNCLOS 1982.',
    'verdict_extra2' => 'Tiongkok nyebabake karusakan ekosistem Kapuloan Spratly liwat eksploitasi berlebihan lan pambangunan pulo artifisial.',
    'verdict_extra3' => 'Tumindak-tumindak Tiongkok nambah risiko konflik karo Vietnam.',
    'verdict_extra4' => 'Pulo Ba Bình (sing dikuwasani Taiwan) uga ora bisa mbentuk EEZ.',
    'verdict_subtitle' => 'Napa iki bertentangan karo UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 kanthi cetha netepake zona-zona segara adhedhasar garis dasar negara pesisir. Klaim Garis Sembilan Garis Putus ngluwihi kerangka iki mula ora bisa diselaraskan.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Laut wilayah (mil laut)',
    'verdict_zone1_body' => 'Wilayah segara negara sing nduweni kadaulatan, diukur saka garis dasar.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona ekonomi eksklusif',
    'verdict_zone2_body' => 'EEZ — negara pesisir nduweni hak kedaulatan marang sumber daya ing wates iki.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Landas kontinen (maksimum, mil laut)',
    'verdict_zone3_body' => 'Hak marang sumber daya dhasar segara, miturut kahanan geologi sing ditemtokake.',
    'verdict_foot' => 'Ing kerangka iki, “hak historis” sing nyakup sakabehe segara lepas — kaya sing diandharake déning Garis Sembilan Garis Putus — <em>wis diganti</em> dening rezim hukum UNCLOS sing uga dianggotai déning Tiongkok.',
];
