<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Putusan internasional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'telung "Ora"',
    'verdict_lead' => 'Tanggal 12/7/2016, Pengadilan Arbitrase Tetap (PCA) ing The Hague — kawangun adhedhasar Lampiran VII UNCLOS, ing perkara Filipina nglawan Tiongkok — wis maringi putusan sing nolak klaim Garis Sembilan Garis Putus. <em>Klik saben kartu kanggo maca teks asline.</em>',
    'verdict_card1_khong' => 'ORA',
    'verdict_card1_title' => 'hak sajarah',
    'verdict_card1_short' => 'Ora ana dhasar hukum supaya Tiongkok negesake hak sajarah marang sumber daya ing segara sing klebu ing Garis Sembilan Garis Putus.',
    'verdict_card1_quote' => '“Ora ana dhasar hukum kanggo Tiongkok negesake hak sajarah marang sumber daya sing ana ing segara ing njero Garis Sembilan Garis Putus.”',
    'verdict_card1_more' => '+ Waca putusan',
    'verdict_card2_khong' => 'ORA',
    'verdict_card2_title' => 'unsur sing mbentuk EEZ',
    'verdict_card2_short' => 'Ora ana unsur ing Kapuloan Spratly sing pantes mbentuk zona ekonomi eksklusif kanggo Tiongkok — kalebu Pulo Ba Bình.',
    'verdict_card2_quote' => '“Ora ana siji wae unsur ing Kapuloan Spratly sing bisa mbentuk zona ekonomi eksklusif.”',
    'verdict_card2_more' => '+ Waca putusan',
    'verdict_card3_khong' => 'ORA',
    'verdict_card3_title' => 'tumindak legal',
    'verdict_card3_short' => 'Tiongkok nglanggar hak kedaulatan Vietnam, ngalangi nelayan, lan ngrusak lingkungan segara.',
    'verdict_card3_quote' => '“Tiongkok wis nglanggar hak kedaulatan Vietnam, campur tangan ing kegiatan nelayan ing Scarborough Shoal lan nyebabake karusakan serius marang lingkungan terumbu karang.”',
    'verdict_card3_more' => '+ Waca putusan',
    'verdict_extra1' => 'Garis Sembilan Garis Putus sing digambar dhewe dening Tiongkok <strong>ora cocog</strong> karo UNCLOS 1982.',
    'verdict_extra2' => 'Tiongkok nyebabake karusakan ekosistem ing Kapuloan Spratly liwat eksploitasi berlebihan lan pambangunan pulo buatan.',
    'verdict_extra3' => 'Tumindak Tiongkok nambah risiko konflik karo Vietnam.',
    'verdict_extra4' => 'Pulo Ba Bình (dikuasai Taiwan) uga ora bisa mbentuk EEZ.',
    'verdict_subtitle' => 'Napa iki tabrakan karo UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 kanthi cetha netepake zona-zona segara adhedhasar garis dasar negara pesisir. Klaim Garis Sembilan Garis Putus ngluwihi kerangka iki mula ora bisa diselaraské.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Laut wilayah (mil laut)',
    'verdict_zone1_body' => 'Wilayah segara negara sing nduweni kadhaulatan, diukur saka garis dasar.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona ekonomi eksklusif',
    'verdict_zone2_body' => 'EEZ — negara pesisir nduweni hak kedaulatan marang sumber daya ing wilayah iki.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Landas kontinen (maksimal, mil laut)',
    'verdict_zone3_body' => 'Hak marang sumber daya dhasar segara, miturut kahanan geologi sing ditemtokake.',
    'verdict_foot' => 'Ing kerangka iki, “hak sajarah” sing nyakup sakabèhé segara lepas — kaya sing diandharake dening Garis Sembilan Garis Putus — <em>wis diganti</em> dening rezim hukum UNCLOS sing uga dadi anggota Tiongkok.',
];
