<?php

return [
    'footer_index' => 'Bibliotheek',
    'footer_crest_eyebrow' => 'Sluit de bibliotheek van de waarheid af',
    'footer_crest_quote' => '“Vrede in de Zuid-Chinese Zee wordt opgebouwd op de basis van <b>internationaal recht</b>.”',
    'footer_crest_sub' => 'Geen haat · Alleen waarheid',
    'footer_nav_aria' => 'Footer-acties',
    'footer_btn_top' => 'Naar boven',
    'footer_btn_verdict' => 'PCA-uitspraak 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Negenstreepjeslijn',
    'footer_brand_body' => 'Een verklarende site gebaseerd op objectieve feiten, internationaal recht en historische documenten — die de aanspraken van de Negenstreepjeslijn weerlegt met bewijs, niet met slogans.',
    'footer_refs_title' => 'Bronnen',
    'footer_ref1' => 'PCA-uitspraak, 12-07-2016',
    'footer_ref2' => 'UNCLOS 1982 — volledige tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historisch materiaal & oude kaarten',
    'footer_toc_title' => 'Inhoudsopgave',
    'footer_toc1' => 'Wat is de Negenstreepjeslijn',
    'footer_toc2' => 'Oorsprong',
    'footer_toc3' => 'Waarom het controversieel is',
    'footer_toc4' => 'Waarom de internationale gemeenschap bezwaar maakt',
    'footer_toc5' => 'Stille getuigen',
    'footer_toc6' => 'PCA-uitspraak 2016',
    'footer_toc7' => 'Paraceleilanden – Spratly-eilanden',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objectieve waarheid over de Zuid-Chinese Zee.<br>Ecysteem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Zonder coördinaten',
];
