<?php

return [
    'footer_index' => 'Bibliotheek',
    'footer_crest_eyebrow' => 'Afsluiting van de bibliotheek van de waarheid',
    'footer_crest_quote' => '“Vrede in de Oostelijke Zee wordt gebouwd op de basis van <b>internationaal recht</b>.”',
    'footer_crest_sub' => 'Geen haat · Alleen de waarheid',
    'footer_nav_aria' => 'Acties onderaan de pagina',
    'footer_btn_top' => 'Naar boven',
    'footer_btn_verdict' => 'PCA-uitspraak 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Aanspraak op de Negenstreepjeslijn',
    'footer_brand_eyebrow' => 'Thematische pagina · Soevereiniteit van Vietnam',
    'footer_brand_body' => 'Een uitleg van de Negenstreepjeslijn aan de hand van objectieve feiten, internationaal recht, de PCA-uitspraak van 2016 en historische documenten — als aanvulling op de diepgaande pagina\'s over de soevereiniteit over de twee archipels <strong>"Paraceleilanden en Spratly-eilanden"</strong>. Weerlegt de onredelijke aanspraak van China met geschiedenis en bewijs.',
    'footer_refs_title' => 'Bronnen',
    'footer_ref1' => 'PCA-uitspraak, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — volledige tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historische documenten & oude kaarten',
    'footer_toc_title' => 'Inhoudsopgave',
    'footer_toc1' => 'Wat is de Negenstreepjeslijn',
    'footer_toc2' => 'Oorsprong',
    'footer_toc3' => 'Waarom het omstreden is',
    'footer_toc4' => 'Waarom de internationale gemeenschap zich ertegen verzet',
    'footer_toc5' => 'Stille getuigen',
    'footer_toc6' => 'PCA-uitspraak 2016',
    'footer_toc7' => 'Paraceleilanden – Spratly-eilanden',
    'footer_copy_eyebrow' => 'Non-profitproject',
    'footer_copy_title' => 'Paraceleilanden – Spratly-eilanden behoren toe aan Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Thematische pagina over de Negenstreepjeslijn binnen het soevereiniteits-ecosysteem van Vietnam.',
    'footer_copy_body' => 'Een uitleg van de aanspraak op de Negenstreepjeslijn via <strong>objectieve feiten</strong>, <strong>internationaal recht</strong>, de PCA-uitspraak van 2016 en historische documenten — als aanvulling op de diepgaande pagina\'s over de soevereiniteit over de twee archipels Paraceleilanden en Spratly-eilanden.',
    'footer_copy_ecosystem_aria' => 'Paginas uit hetzelfde project',
    'footer_copy_ecosystem_label' => 'Binnen hetzelfde ecosysteem',
    'footer_copy_disclaimer' => 'De inhoud is bedoeld voor educatie en bewustwording; zij vervangt niet het officiële standpunt van de Vietnamese staat.',
    'footer_copy' => '<strong>© :year Negenstreepjeslijn</strong> — Een onderdeel van het non-profitproject <strong>Paraceleilanden – Spratly-eilanden behoren toe aan Vietnam</strong> binnen het netwerk: <a href="https://paracelislands.net/nl" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/nl" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/nl" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/nl" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/nl" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Toezeggingen voor de inhoud van de pagina',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-uitspraak 2016',
    'footer_chip3' => 'Historisch bewijs',
    'footer_chip4' => 'Oude kaarten',
    'footer_chip5' => 'Objectieve feiten',
    'footer_chip6' => 'Vrede in de Oostelijke Zee',
];
