<?php

return [
    'nav_logo_name' => 'Negenstreepjeslijn',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Negenstreepjeslijn',
    'nav_rail_aria' => 'Navigatie per onderdeel',
    'nav_rail_what' => 'Definitie',
    'nav_rail_origin' => 'Oorsprong',
    'nav_rail_dispute' => 'Geschil',
    'nav_rail_opposition' => 'Bezwaar',
    'nav_rail_witnesses' => 'Oude kaarten',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paraceleilanden – Spratly-eilanden',
    'nav_sound_off' => 'Achtergrondmuziek aan',
    'nav_sound_on' => 'Achtergrondmuziek uit',
    'nav_share' => 'Delen',
    'dialog_title' => 'Weergavetaal',
    'language' => 'Taal',
    'display_hint' => ':count talen',
    'search_placeholder' => 'Zoek taal…',
    'cancel' => 'Annuleren',
    'apply' => 'Toepassen',
    'sound_off' => 'Achtergrondgeluid aan',
    'sound_on' => 'Achtergrondgeluid uit',
    'lang_trigger' => 'Kies taal',
    'close' => 'Sluiten',
    'no_results' => 'Geen taal gevonden',
    'contribute' => 'Delen',
];
