<?php

return [
    'opposition_index' => 'Tegenstand',
    'opposition_label' => 'Waarom de internationale gemeenschap bezwaar maakt',
    'opposition_title' => 'Tegenstand gebaseerd op',
    'opposition_title_accent' => 'het recht, niet op emoties',
    'opposition_lead' => 'Kort nadat de Negenstreepjeslijn in 2009 bij de Verenigde Naties was ingediend, maakten veel landen en wetenschappers bezwaar — met specifieke juridische argumenten.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mei',
    'opposition_voice1_title' => 'Vietnam · Maleisië · Indonesië',
    'opposition_voice1_body' => 'Al één dag nadat China de kaart van de Negenstreepjeslijn had voorgelegd aan de secretaris-generaal van de Verenigde Naties (7/5/2009), stuurden deze landen achtereenvolgens diplomatieke nota\'s van protest en verwierpen zij de aanspraak.',
    'opposition_voice1_chip1' => 'Protestnota',
    'opposition_voice1_chip2' => 'Niet in overeenstemming met UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipijnen',
    'opposition_voice2_body' => 'Zij stuurde een diplomatieke brief naar de Verenigde Naties en verklaarde dat China\'s aanspraak in de Zuid-Chinese Zee "geen grondslag heeft volgens het internationaal recht" — een voorloper van de daaropvolgende arbitragezaak.',
    'opposition_voice2_chip1' => 'Aanleiding voor de PCA-zaak',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Amerikaans ministerie van Buitenlandse Zaken — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'De analyse wijst uit: kaarten uit verschillende jaren zijn inconsistent wat betreft de positie van de lijn; de lijn dringt het vasteland binnen in plaats van een middellijn te volgen; veel entiteiten voldoen niet aan de criteria voor een "eiland" om een EEZ te hebben.',
    'opposition_voice3_chip1' => 'Voldoet niet aan de juridische voorwaarden',
    'opposition_voice3_chip2' => 'Officiële analyse',
    'opposition_voice4_year' => 'Academisch',
    'opposition_voice4_title' => '"Historische wateren" zijn verouderd',
    'opposition_voice4_body' => 'Dit concept is alleen van toepassing op baaien en kustwateren dicht bij de kust — het kan niet een hele uitgestrekte open zee omvatten. In 2003 verwierp ook Taiwan zelf het beleid van "historische wateren" dat het in 1993 had genoemd.',
    'opposition_voice4_chip1' => 'Zelfs Chinese academici zijn het niet eens',
];
