<?php

return [
    'sovereignty_index' => 'Paraceleilanden - Spratly-eilanden',
    'sovereignty_label' => 'Noodzakelijke conclusie',
    'sovereignty_title' => 'Paraceleilanden - Spratly-eilanden',
    'sovereignty_title_accent' => 'behoren toe aan Vietnam',
    'sovereignty_lead' => 'Deze pagina legt de Negenstreepjeslijn uit. Het slot beantwoordt de volgende vraag: wie heeft soevereiniteit over de twee archipels, de Paraceleilanden en de Spratly-eilanden? Volgens historische bestuurlijke praktijk en internationaal recht is het consequente antwoord: Vietnam.',
    'sovereignty_thesis_label' => 'Samengevat standpunt',
    'sovereignty_thesis_lock1' => 'Geen juridische coördinaten',
    'sovereignty_thesis_lock2' => 'Verworpen door het PCA in 2016',
    'sovereignty_thesis_lock3' => 'Oude kaarten dekken het niet af',
    'sovereignty_thesis_body' => 'Na de zes bovenstaande onderdelen zijn drie punten duidelijk: de Negenstreepjeslijn is met de hand getekend en heeft geen juridische coördinaten; het Arbitragehof uit 2016 verwierp de claim; en oude kaarten van China zelf omvatten de Zuid-Chinese Zee niet volledig. De Vietnamese soevereiniteit berust niet op leuzen, maar op het feit dat de Vietnamese staat — vanaf de tijd van de Nguyễn-heersers — beide archipels vreedzaam en onafgebroken heeft bestuurd toen zij nog terra nullius waren.',
    'sovereignty_spine_caption' => 'Mijlpalen van onafgebroken bestuur',
    'sovereignty_spine_title' => 'Een ononderbroken tijdlijn',
    'sovereignty_spine_range' => '17e eeuw → heden',
    'sovereignty_chron1_year' => '17e eeuw',
    'sovereignty_chron1_title' => 'De Paraceelgroep',
    'sovereignty_chron1_body' => 'De Nguyễn-heersers stuurden de Paraceelgroep eropuit om de zee te verkennen, zeeroutes te meten en op zee te exploiteren — een uitoefening van feitelijk bestuur.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Koning Gia Long',
    'sovereignty_chron2_body' => 'Hij plantte de vlag op de Paraceleilanden en bevestigde daarmee de soevereiniteit van Vietnam voor de wereld van zijn tijd.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Koning Minh Mạng',
    'sovereignty_chron3_body' => 'Er werden metingen uitgevoerd, stèles opgericht en de archipel werd opgenomen op de officiële kaarten van het hof.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Voortgezette opvolging',
    'sovereignty_chron4_body' => 'Frankrijk erkende en zette het bestuur voort; het lijfde de Paraceleilanden in bij de provincie Thừa Thiên — een basis voor de huidige Vietnamese staat.',
    'sovereignty_chron5_year' => 'Heden',
    'sovereignty_chron5_title' => 'Recht en praktijk',
    'sovereignty_chron5_body' => 'Vietnam bestuurt op basis van UNCLOS, diplomatie en archiefstukken; de claim van de Negenstreepjeslijn kan dit bewijs niet vervangen.',
    'sovereignty_balance_label' => 'Bewijs in balans',
    'sovereignty_balance_medallion_title' => 'Twee kanten vergeleken',
    'sovereignty_vn_tag' => 'De Vietnamese zijde',
    'sovereignty_vn_title' => 'Soevereiniteit vastgesteld door handelingen',
    'sovereignty_vn_body' => 'Werkelijke inbezitneming toen het gebied nog terra nullius was, gevolgd door openbare en voortdurende bestuurlijke uitoefening door de eeuwen heen — met keizerlijke documenten, stèles, kaarten en administratieve dossiers. Deze aanpak is in overeenstemming met UNCLOS en internationale gebruiken.',
    'sovereignty_dash_tag' => 'De Negenstreepjeslijn-zijde',
    'sovereignty_dash_title' => 'Een claim vervangt geen bewijs',
    'sovereignty_dash_body' => 'Een lijn getrokken in 1948, zonder coördinaten, is in 2016 door het PCA verworpen en strijdig met UNCLOS — zoals de onderdelen 03 tot en met 06 uiteenzetten. Daarom kan de conclusie over de soevereiniteit over de twee archipels niet op de Negenstreepjeslijn worden gebaseerd.',
    'sovereignty_seal_quote' => 'Vietnam lost geschillen op met <strong>vreedzame middelen</strong>, op basis van internationaal recht — in het bijzonder UNCLOS 1982 — en streeft naar een vreedzame, coöperatieve en ontwikkelingsgerichte Zuid-Chinese Zee.',
    'sovereignty_seal_cite' => 'Standpunt van Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Belangrijk project binnen hetzelfde ecosysteem',
    'sovereignty_next_title' => 'Lees het volledige bewijs over de Paraceleilanden - Spratly-eilanden',
    'sovereignty_next_body' => 'Het gedetailleerde dossier — documenten, kaarten, tijdlijn en juridische argumenten — staat op <strong>paracelislands.net</strong>, waar het onderwerp van de soevereiniteit over beide archipels volledig wordt uiteengezet. De pagina die u leest verbindt alleen de logica van de Negenstreepjeslijn met die conclusie.',
    'sovereignty_next_cta' => 'Open paracelislands.net',
];
