<?php

return [
    'sovereignty_index' => 'Paraceleilanden - Spratly-eilanden',
    'sovereignty_label' => 'Onvermijdelijke conclusie',
    'sovereignty_title' => 'Paraceleilanden - Spratly-eilanden',
    'sovereignty_title_accent' => 'behoren toe aan Vietnam',
    'sovereignty_lead' => 'Deze pagina legt de Negenstreepjeslijn uit. Het slotgedeelte beantwoordt de volgende vraag: wie heeft soevereiniteit over de twee archipels, de Paraceleilanden en de Spratly-eilanden? Volgens de bestuurlijke geschiedenis en het internationale recht is het consequente antwoord: Vietnam.',
    'sovereignty_thesis_label' => 'Samengevat standpunt',
    'sovereignty_thesis_lock1' => 'Geen juridische coördinaten',
    'sovereignty_thesis_lock2' => 'PCA 2016 verworpen',
    'sovereignty_thesis_lock3' => 'Oude kaarten dekken het niet',
    'sovereignty_thesis_body' => 'Na de zes bovenstaande onderdelen zijn drie punten duidelijk: de Negenstreepjeslijn is met de hand getekend en heeft geen juridische coördinaten; het Arbitragehof heeft in 2016 de aanspraak verworpen; en de oude kaarten van China zelf omvatten de Zuid-Chinese Zee niet. De soevereiniteit van Vietnam berust niet op slogans, maar op het feit dat de Vietnamese staat — vanaf de tijd van de Nguyễn-heersers — de twee archipels vreedzaam en onafgebroken heeft bestuurd toen zij nog niemandsland waren.',
    'sovereignty_spine_caption' => 'Mijlpaal van voortdurende bestuurshandeling',
    'sovereignty_spine_title' => 'Een tijdlijn zonder onderbreking',
    'sovereignty_spine_range' => '17e eeuw → heden',
    'sovereignty_chron1_year' => '17e eeuw',
    'sovereignty_chron1_title' => 'De Hoàng Sa-eenheid',
    'sovereignty_chron1_body' => 'De Nguyễn-heersers stuurden de Hoàng Sa-eenheid om zeeën te verkennen, waterwegen op te meten en op zee te exploiteren — een uitoefening van feitelijk bestuur.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Koning Gia Long',
    'sovereignty_chron2_body' => 'Hij hees de vlag op de Paraceleilanden en bevestigde daarmee de soevereiniteit van Vietnam in de ogen van de toenmalige wereld.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Koning Minh Mạng',
    'sovereignty_chron3_body' => 'De eilanden werden opgemeten, er werden stèles opgericht en ze werden op de officiële kaarten van het hof vastgelegd.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Ononderbroken opvolging',
    'sovereignty_chron4_body' => 'Frankrijk erkende en zette het bestuur voort; de Paraceleilanden werden bij de provincie Thừa Thiên gevoegd — een basis voor de huidige Vietnamese staat.',
    'sovereignty_chron5_year' => 'Heden',
    'sovereignty_chron5_title' => 'Recht en praktijk',
    'sovereignty_chron5_body' => 'Vietnam beheert dit volgens UNCLOS, diplomatie en archiefstukken; de aanspraak van de Negenstreepjeslijn kan dit bewijs niet vervangen.',
    'sovereignty_balance_label' => 'Bewijsevenwicht',
    'sovereignty_balance_medallion_title' => 'Vergelijking van beide kanten',
    'sovereignty_vn_tag' => 'De Vietnamese zijde',
    'sovereignty_vn_title' => 'Soevereiniteit vastgesteld door daden',
    'sovereignty_vn_body' => 'Werkelijke bezetting toen het gebied nog niemandsland was, gevolgd door openbare en eeuwenlange bestuursuitoefening — met keizerlijke documenten, stèles, kaarten en administratieve dossiers. Deze aanpak strookt met UNCLOS en de internationale praktijk.',
    'sovereignty_dash_tag' => 'De kant van de Negenstreepjeslijn',
    'sovereignty_dash_title' => 'Een aanspraak kan het bewijs niet compenseren',
    'sovereignty_dash_body' => 'Een lijn getekend in 1948, zonder coördinaten, die in 2016 door het PCA is verworpen en in strijd is met UNCLOS — zoals in de onderdelen 03 tot en met 06 is uiteengezet. Daarom kan de conclusie over de soevereiniteit over de twee archipels niet op de Negenstreepjeslijn worden gebaseerd.',
    'sovereignty_seal_quote' => 'Vietnam lost geschillen op met <strong>vreedzame middelen</strong>, op basis van het internationale recht — in het bijzonder UNCLOS 1982 — met als doel een Zuid-Chinese Zee die vreedzaam, coöperatief en ontwikkelingsgericht is.',
    'sovereignty_seal_cite' => 'Standpunt van Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Het hoofdproject binnen hetzelfde ecosysteem',
    'sovereignty_next_title' => 'Lees het volledige bewijs over de Paraceleilanden - Spratly-eilanden',
    'sovereignty_next_body' => 'Het gedetailleerde dossier — documenten, kaarten, tijdlijnen en juridische argumenten — staat op <strong>paracelislands.net</strong>, waar het onderwerp soevereiniteit over de twee archipels volledig wordt uitgewerkt. De pagina die u nu leest verbindt de logica van de Negenstreepjeslijn met die conclusie.',
    'sovereignty_next_cta' => 'Open paracelislands.net',
];
