<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internationale uitspraak',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'drie keer “Nee”',
    'verdict_lead' => 'Op 12 juli 2016 deed het Permanent Hof van Arbitrage (PCA) in Den Haag — ingesteld op grond van Bijlage VII van UNCLOS, in de zaak die de Filipijnen tegen China had aangespannen — uitspraak en verwierp het de aanspraak op de Negenstreepjeslijn. <em>Klik op elk kaartje om de volledige tekst te lezen.</em>',
    'verdict_card1_khong' => 'NEE',
    'verdict_card1_title' => 'historisch recht',
    'verdict_card1_short' => 'Er bestaat geen rechtsgrond voor China om historisch recht te claimen op hulpbronnen in de zee binnen de Negenstreepjeslijn.',
    'verdict_card1_quote' => '“Er bestaat geen rechtsgrond voor China om historisch recht te claimen op hulpbronnen in de zee binnen de Negenstreepjeslijn.”',
    'verdict_card1_more' => '+ Lees de uitspraak',
    'verdict_card2_khong' => 'NEE',
    'verdict_card2_title' => 'een entiteit die een EEZ kan creëren',
    'verdict_card2_short' => 'Geen enkele entiteit in de Spratly-eilanden voldoet aan de voorwaarden om voor China een exclusieve economische zone te creëren — zelfs Taipingdao niet.',
    'verdict_card2_quote' => '“Geen enkele entiteit in de Spratly-eilanden is in staat een exclusieve economische zone te creëren.”',
    'verdict_card2_more' => '+ Lees de uitspraak',
    'verdict_card3_khong' => 'NEE',
    'verdict_card3_title' => 'rechtmatige handeling',
    'verdict_card3_short' => 'China schond de soevereine rechten van de Filipijnen, belemmerde de visserij en schaadde het mariene milieu.',
    'verdict_card3_quote' => '“China heeft de soevereine rechten van de Filipijnen geschonden, ingegrepen in de visserijactiviteiten bij Scarborough Shoal en ernstige schade toegebracht aan het koraalrifmilieu.”',
    'verdict_card3_more' => '+ Lees de uitspraak',
    'verdict_extra1' => 'De Negenstreepjeslijn, door China zelf getekend, is <strong>niet in overeenstemming</strong> met UNCLOS 1982.',
    'verdict_extra2' => 'China heeft het ecosysteem van de Spratly-eilanden schade toegebracht door overexploitatie en de aanleg van kunstmatige eilanden.',
    'verdict_extra3' => 'De handelingen van China vergroten het risico op een conflict met de Filipijnen.',
    'verdict_extra4' => 'Ook Taipingdao (onder controle van Taiwan) kan geen EEZ creëren.',
    'verdict_subtitle' => 'Waarom botst dit met UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 bakent de zeegebieden duidelijk af op basis van de basislijnen van de kuststaat. De aanspraak op de Negenstreepjeslijn gaat buiten dit kader en kan daarom niet ermee worden vergeleken.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territoriale zee (zeemijl)',
    'verdict_zone1_body' => 'Een zeegebied onder nationale soevereiniteit, gemeten vanaf de basislijn.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Exclusieve economische zone',
    'verdict_zone2_body' => 'EEZ — de kuststaat heeft binnen dit gebied soevereine rechten op hulpbronnen.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Continentaal plat (maximaal, zeemijl)',
    'verdict_zone3_body' => 'Rechten op de hulpbronnen van de zeebodem, volgens vastgestelde geologische voorwaarden.',
    'verdict_foot' => 'Binnen dit kader is “historisch recht” op een volledige open zee — zoals de Negenstreepjeslijn suggereert — <em>vervangen</em> door het juridische regime van UNCLOS, waarvan China zelf ook partij is.',
];
