<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internationaal arrest',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'drie keer “Nee”',
    'verdict_lead' => 'Op 12 juli 2016 deed het Permanent Hof van Arbitrage (PCA) in Den Haag — ingesteld op grond van Bijlage VII van UNCLOS, in de zaak Filipijnen tegen China — uitspraak en verwierp het de Negenstreepjeslijn-claim. <em>Klik op elke kaart om de volledige tekst te lezen.</em>',
    'verdict_card1_khong' => 'NEE',
    'verdict_card1_title' => 'historische rechten',
    'verdict_card1_short' => 'Er bestaat geen rechtsgrond voor China om historische rechten te claimen op hulpbronnen in de zee binnen de Negenstreepjeslijn.',
    'verdict_card1_quote' => '“Er is geen rechtsgrond voor China om historische rechten te claimen op de hulpbronnen in de zee binnen de Negenstreepjeslijn.”',
    'verdict_card1_more' => '+ Lees de uitspraak',
    'verdict_card2_khong' => 'NEE',
    'verdict_card2_title' => 'formatie die een EEZ creëert',
    'verdict_card2_short' => 'Geen enkele formatie in de Spratly-eilanden komt in aanmerking om voor China een exclusieve economische zone te creëren — ook niet het eiland Ba Bình.',
    'verdict_card2_quote' => '“Geen enkele formatie in de Spratly-eilanden is in staat een exclusieve economische zone te creëren.”',
    'verdict_card2_more' => '+ Lees de uitspraak',
    'verdict_card3_khong' => 'NEE',
    'verdict_card3_title' => 'rechtmatige handelingen',
    'verdict_card3_short' => 'China schond de soevereine rechten van de Filipijnen, hinderde de visserij en beschadigde het mariene milieu.',
    'verdict_card3_quote' => '“China heeft de soevereine rechten van de Filipijnen geschonden, zich bemoeid met de visserij bij Scarborough Shoal en ernstige schade toegebracht aan het koraalrifmilieu.”',
    'verdict_card3_more' => '+ Lees de uitspraak',
    'verdict_extra1' => 'De door China zelf getekende Negenstreepjeslijn is <strong>niet in overeenstemming</strong> met UNCLOS 1982.',
    'verdict_extra2' => 'China heeft het ecosysteem van de Spratly-eilanden beschadigd door overexploitatie en het aanleggen van kunstmatige eilanden.',
    'verdict_extra3' => 'De acties van China vergroten het risico op een conflict met de Filipijnen.',
    'verdict_extra4' => 'Ook het eiland Ba Bình (onder bestuur van Taiwan) kan geen EEZ creëren.',
    'verdict_subtitle' => 'Waarom botst dit met UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 bakent de maritieme zones duidelijk af op basis van de basislijnen van de kuststaat. De claim van de Negenstreepjeslijn reikt verder dan dit kader en kan daarom niet ermee worden verenigd.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territoriale zee (zeemijl)',
    'verdict_zone1_body' => 'Maritieme zone van de staat waarover soevereiniteit geldt, gemeten vanaf de basislijn.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Exclusieve economische zone',
    'verdict_zone2_body' => 'EEZ — de kuststaat heeft binnen dit gebied soevereine rechten op hulpbronnen.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Continentaal plat (maximaal, zeemijl)',
    'verdict_zone3_body' => 'Rechten op hulpbronnen van de zeebodem, volgens vastgestelde geologische voorwaarden.',
    'verdict_foot' => 'Binnen dit kader is “historisch recht” dat een hele open zee zou omvatten — zoals de Negenstreepjeslijn suggereert — <em>vervangen</em> door het juridische regime van UNCLOS, waarvan ook China partij is.',
];
