<?php

return [
    'footer_index' => 'Bibliotēka',
    'footer_crest_eyebrow' => 'Faktu bibliotēkas noslēgums',
    'footer_crest_quote' => '“Miers Dienvidķīnas jūrā balstās uz <b>starptautiskajām tiesībām</b>.”',
    'footer_crest_sub' => 'Nav naida · Tikai patiesība',
    'footer_nav_aria' => 'Apakšlapas darbības',
    'footer_btn_top' => 'Uz augšu',
    'footer_btn_verdict' => 'PCA 2016 nolēmums',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Deviņu svītru līnijas pretenzija',
    'footer_brand_eyebrow' => 'Tematiska lapa · Vjetnamas suverenitāte',
    'footer_brand_body' => 'Deviņu svītru līnijas skaidrojums, balstoties uz objektīviem faktiem, starptautiskajām tiesībām, PCA 2016 nolēmumu un vēstures avotiem — kā papildinājums padziļinātām lapām par suverenitāti pār abām salu grupām <strong>"Paraselu salas - Spratlija salas"</strong>. Ķīnas nepamatotās pretenzijas tiek atspēkotas ar vēsturi un pierādījumiem.',
    'footer_refs_title' => 'Atsauces',
    'footer_ref1' => 'PCA nolēmums, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — pilns teksts',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Vēstures avoti un seni kartogrāfiskie materiāli',
    'footer_toc_title' => 'Lapas saturs',
    'footer_toc1' => 'Kas ir Deviņu svītru līnija',
    'footer_toc2' => 'Izcelsme',
    'footer_toc3' => 'Kāpēc tā ir strīdīga',
    'footer_toc4' => 'Kāpēc starptautiski tiek iebilsts',
    'footer_toc5' => 'Klusie liecinieki',
    'footer_toc6' => 'PCA 2016 nolēmums',
    'footer_toc7' => 'Paraselu salas – Spratlija salas',
    'footer_copy_eyebrow' => 'Nepeļņas projekts',
    'footer_copy_title' => 'Paraselu salas – Spratlija salas pieder Vjetnamai',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematiska lapa par Deviņu svītru līniju Vjetnamas suverenitātes ekosistēmā.',
    'footer_copy_body' => 'Deviņu svītru līnijas pretenzijas skaidrojums, balstoties uz <strong>objektīviem faktiem</strong>, <strong>starptautiskajām tiesībām</strong>, PCA 2016 nolēmumu un vēstures avotiem — kā papildinājums padziļinātām lapām par suverenitāti pār Paraselu salām un Spratlijas salām.',
    'footer_copy_ecosystem_aria' => 'Tā paša projekta lapas',
    'footer_copy_ecosystem_label' => 'Tajā pašā ekosistēmā',
    'footer_copy_disclaimer' => 'Saturs ir paredzēts izglītošanai un informētības veicināšanai; tas neaizstāj Vjetnamas valsts oficiālo nostāju.',
    'footer_copy' => '<strong>© :year Deviņu svītru līnija</strong> — Daļa no nepeļņas projekta <strong>Paraselu salas – Spratlija salas pieder Vjetnamai</strong>, kas ietilpst šādā sistēmā: <a href="https://paracelislands.net/lv" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/lv" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/lv" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/lv" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/lv" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Lapas satura apņemšanās',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 nolēmums',
    'footer_chip3' => 'Vēstures pierādījumi',
    'footer_chip4' => 'Senas kartes',
    'footer_chip5' => 'Objektīva patiesība',
    'footer_chip6' => 'Miers Dienvidķīnas jūrā',
];
