<?php

return [
    'footer_index' => 'Bibliotēka',
    'footer_crest_eyebrow' => 'Patiesības bibliotēkas noslēgums',
    'footer_crest_quote' => '“Miers Dienvidķīnas jūrā balstās uz <b>starptautiskajām tiesībām</b>.”',
    'footer_crest_sub' => 'Nav naida · Tikai patiesība',
    'footer_nav_aria' => 'Darbības lapas apakšdaļā',
    'footer_btn_top' => 'Uz lapas augšdaļu',
    'footer_btn_verdict' => 'PCA 2016 spriedums',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Deviņu svītru līnija',
    'footer_brand_body' => 'Faktu, starptautisko tiesību un vēsturisko dokumentu pamatots skaidrojošs portāls — atspēko Deviņu svītru līnijas pretenzijas ar pierādījumiem, nevis saukļiem.',
    'footer_refs_title' => 'Atsauces',
    'footer_ref1' => 'PCA spriedums, 12.07.2016.',
    'footer_ref2' => '1982. gada UNCLOS — pilns teksts',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Vēsturiskie materiāli un senās kartes',
    'footer_toc_title' => 'Lapas saturs',
    'footer_toc1' => 'Kas ir Deviņu svītru līnija',
    'footer_toc2' => 'Izcelsme',
    'footer_toc3' => 'Kāpēc tā ir pretrunīga',
    'footer_toc4' => 'Kāpēc starptautiskā sabiedrība iebilst',
    'footer_toc5' => 'Klusie liecinieki',
    'footer_toc6' => 'PCA 2016 spriedums',
    'footer_toc7' => 'Paraselu salas – Spratlija salas',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektīva patiesība par Dienvidķīnas jūru.<br>Ekosistēma: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => '1982. gada UNCLOS',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Nav koordinātu',
];
