<?php

return [
    'footer_index' => 'Bibliotēka',
    'footer_crest_eyebrow' => 'Patiesības bibliotēkas noslēgums',
    'footer_crest_quote' => '“Miers Dienvidķīnas jūrā ir balstīts uz <b>starptautiskajām tiesībām</b>.”',
    'footer_crest_sub' => 'Bez naida · Tikai patiesība',
    'footer_nav_aria' => 'Darbības lapas apakšā',
    'footer_btn_top' => 'Uz lapas sākumu',
    'footer_btn_verdict' => 'PCA 2016 spriedums',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Deviņu svītru līnijas pretenzijas',
    'footer_brand_eyebrow' => 'Tematiskā lapa · Vjetnamas suverenitāte',
    'footer_brand_body' => 'Deviņu svītru līnijas skaidrojums, balstoties uz objektīviem faktiem, starptautiskajām tiesībām, PCA 2016 spriedumu un vēstures avotiem — papildinājums padziļinātām lapām par abu arhipelāgu <strong>"Paraselu salas un Spratlija salas"</strong> suverenitāti. Ķīnas nepamatotās pretenzijas tiek noraidītas, balstoties uz vēsturi un pierādījumiem.',
    'footer_refs_title' => 'Atsauces',
    'footer_ref1' => 'PCA spriedums, 2016. gada 12. jūlijs',
    'footer_ref2' => 'UNCLOS 1982 — pilns teksts',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Vēstures avoti un seni kartogrāfiskie materiāli',
    'footer_toc_title' => 'Lapas saturs',
    'footer_toc1' => 'Kas ir Deviņu svītru līnija',
    'footer_toc2' => 'Izcelsme',
    'footer_toc3' => 'Kāpēc tā ir pretrunīga',
    'footer_toc4' => 'Kāpēc starptautiskā sabiedrība to noraida',
    'footer_toc5' => 'Klusie liecinieki',
    'footer_toc6' => 'PCA 2016 spriedums',
    'footer_toc7' => 'Paraselu salas – Spratlija salas',
    'footer_copy_eyebrow' => 'Bezpeļņas projekts',
    'footer_copy_title' => 'Paraselu salas – Spratlija salas pieder Vjetnamai',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematiskā lapa par Deviņu svītru līniju Vjetnamas suverenitātes ekosistēmā.',
    'footer_copy_body' => 'Deviņu svītru līnijas pretenziju skaidrojums, balstoties uz <strong>objektīviem faktiem</strong>, <strong>starptautiskajām tiesībām</strong>, PCA 2016 spriedumu un vēstures avotiem — papildinājums padziļinātām lapām par Paraselu salu un Spratlija salu suverenitāti.',
    'footer_copy_ecosystem_aria' => 'Saistītās projekta lapas',
    'footer_copy_ecosystem_label' => 'Tā pati ekosistēma',
    'footer_copy_disclaimer' => 'Saturs paredzēts izglītošanai un informētības veicināšanai; tas neaizstāj Vjetnamas valsts oficiālo nostāju.',
    'footer_copy' => '<strong>© :year Deviņu svītru līnija</strong> — Daļa no bezpeļņas projekta <strong>Paraselu salas – Spratlija salas pieder Vjetnamai</strong> šādā sistēmā: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Lapas satura apņemšanās',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 spriedums',
    'footer_chip3' => 'Vēstures pierādījumi',
    'footer_chip4' => 'Senas kartes',
    'footer_chip5' => 'Objektīva patiesība',
    'footer_chip6' => 'Miers Dienvidķīnas jūrā',
];
