<?php

return [
    'nav_logo_name' => 'Deviņu svītru līnija',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Deviņu svītru līnija',
    'nav_rail_aria' => 'Navigācija pēc sadaļām',
    'nav_rail_what' => 'Definīcija',
    'nav_rail_origin' => 'Izcelsme',
    'nav_rail_dispute' => 'Strīdi',
    'nav_rail_opposition' => 'Iebildumi',
    'nav_rail_witnesses' => 'Senās kartes',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paraselu salas – Spratlija salas',
    'nav_sound_off' => 'Ieslēgt fona mūziku',
    'nav_sound_on' => 'Izslēgt fona mūziku',
    'nav_share' => 'Dalīties',
    'dialog_title' => 'Attēlošanas valoda',
    'language' => 'Valoda',
    'display_hint' => ':count valodas',
    'search_placeholder' => 'Meklēt valodu…',
    'cancel' => 'Atcelt',
    'apply' => 'Piemērot',
    'sound_off' => 'Ieslēgt fona skaņu',
    'sound_on' => 'Izslēgt fona skaņu',
    'lang_trigger' => 'Izvēlēties valodu',
    'close' => 'Aizvērt',
    'no_results' => 'Valoda nav atrasta',
    'contribute' => 'Dalīties',
];
