<?php

return [
    'opposition_index' => 'Iebildumi',
    'opposition_label' => 'Kāpēc starptautiski iebilst',
    'opposition_title' => 'Iebildumi, kas balstīti uz',
    'opposition_title_accent' => 'likumu, nevis emocijām',
    'opposition_lead' => 'Tūlīt pēc tam, kad Deviņu svītru līnija 2009. gadā tika iesniegta Apvienotajām Nācijām, vairākas valstis un akadēmiķi tai iebilda — ar konkrētiem juridiskiem argumentiem.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maijs',
    'opposition_voice1_title' => 'Vjetnama · Malaizija · Indonēzija',
    'opposition_voice1_body' => 'Jau vienu dienu pēc tam, kad Ķīna iesniedza Deviņu svītru līnijas karti Apvienoto Nāciju Organizācijas ģenerālsekretāram (7.05.2009.), šīs valstis pakāpeniski nosūtīja protesta notis, noraidot šo pretenziju.',
    'opposition_voice1_chip1' => 'Protesta nota',
    'opposition_voice1_chip2' => 'Nav saderīga ar UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipīnas',
    'opposition_voice2_body' => 'Nosūtīja diplomātisku vēstuli Apvienotajām Nācijām, paziņojot, ka Ķīnas pretenzijām Dienvidķīnas jūrā nav “starptautisko tiesību pamata” — tas kļuva par priekšnoteikumu vēlākajai tiesvedībai šķīrējtiesā.',
    'opposition_voice2_chip1' => 'PCA lietas priekšnoteikums',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'ASV Valsts departaments — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analīze norādīja: dažādu gadu kartēs līniju atrašanās vieta nav konsekventa; līnija iestiepjas kontinentālajā teritorijā, nevis tiek vilkta pa viduslīniju; daudzas vienības neatbilst “salas” statusam, lai tām būtu EEZ.',
    'opposition_voice3_chip1' => 'Nesasniedz juridiskās prasības',
    'opposition_voice3_chip2' => 'Oficiāla analīze',
    'opposition_voice4_year' => 'Akadēmiski',
    'opposition_voice4_title' => '“Vēsturisko ūdeņu” koncepcija ir novecojusi',
    'opposition_voice4_body' => 'Šī koncepcija attiecas tikai uz līčiem un piekrastes lagūnām — to nevar attiecināt uz plašu atklātas jūras teritoriju. 2003. gadā arī pati Taivāna noraidīja “vēsturisko ūdeņu” politiku, kas bija minēta 1993. gadā.',
    'opposition_voice4_chip1' => 'Pat Ķīnas akadēmiķi nav vienisprātis',
];
