<?php

return [
    'opposition_index' => 'Iebildumi',
    'opposition_label' => 'Kāpēc starptautiskā sabiedrība iebilst',
    'opposition_title' => 'Iebildumi balstās uz',
    'opposition_title_accent' => 'likumu, nevis emocijām',
    'opposition_lead' => 'Tiklīdz Deviņu svītru līnija 2009. gadā tika iesniegta Apvienoto Nāciju Organizācijai, vairākas valstis un akadēmiskā vide to iebilda — ar konkrētiem tiesiskiem argumentiem.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maijs',
    'opposition_voice1_title' => 'Vjetnama · Malaizija · Indonēzija',
    'opposition_voice1_body' => 'Jau vienu dienu pēc tam, kad Ķīna 2009. gada 7. maijā iesniedza Deviņu svītru līnijas karti ANO ģenerālsekretāram, šīs valstis secīgi nosūtīja iebildumu notas, noraidot šo pretenziju.',
    'opposition_voice1_chip1' => 'Iebildumu nota',
    'opposition_voice1_chip2' => 'Nav saderīga ar UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => 'Filipīnas',
    'opposition_voice2_body' => 'Nosūtīja diplomātisku vēstuli Apvienoto Nāciju Organizācijai, paziņojot, ka Ķīnas pretenzijas Dienvidķīnas jūrā ir “bez pamata starptautiskajās tiesībās” — tas kļuva par priekšnosacījumu vēlākajai lietai šķīrējtiesā.',
    'opposition_voice2_chip1' => 'PCA lietas priekšvēstnesis',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '12/05',
    'opposition_voice3_title' => 'ASV Valsts departaments — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analīze norādīja: dažādu gadu kartēs līniju atrašanās vieta nav konsekventa; līnija ieiet sauszemi, nevis seko viduslīnijai; daudzi veidojumi neatbilst “salu” statusam, lai tiem būtu EEZ.',
    'opposition_voice3_chip1' => 'Neatbilst tiesiskajām prasībām',
    'opposition_voice3_chip2' => 'Oficiāla analīze',
    'opposition_voice4_year' => 'Akadēmiskā vide',
    'opposition_voice4_title' => '“Vēsturisko ūdeņu” koncepcija ir novecojusi',
    'opposition_voice4_body' => 'Šis jēdziens attiecas tikai uz līčiem un piekrastes ielokiem — to nevar attiecināt uz veselu plašu atklātās jūras teritoriju. 2003. gadā arī pati Taivāna noraidīja 1993. gadā izteikto “vēsturisko ūdeņu” politiku.',
    'opposition_voice4_chip1' => 'Pat Ķīnas akadēmiķi nav vienisprātis',
];
