<?php

return [
    'sovereignty_index' => 'Paraselu salas - Spratlija salas',
    'sovereignty_label' => 'Neizbēgams secinājums',
    'sovereignty_title' => 'Paraselu salas - Spratlija salas',
    'sovereignty_title_accent' => 'pieder Vjetnamai',
    'sovereignty_lead' => 'Šī lapa skaidro Deviņu svītru līniju. Noslēgums atbild uz nākamo jautājumu: kam pieder suverenitāte pār abiem arhipelāgiem — Paraselu salām un Spratlija salām? Saskaņā ar pārvaldības vēsturi un starptautiskajām tiesībām konsekventa atbilde ir Vjetnama.',
    'sovereignty_thesis_label' => 'Apkopotais apgalvojums',
    'sovereignty_thesis_lock1' => 'Nav juridisku koordinātu',
    'sovereignty_thesis_lock2' => 'PCA 2016 noraidīja',
    'sovereignty_thesis_lock3' => 'Senās kartes to neaptver',
    'sovereignty_thesis_body' => 'Pēc sešām iepriekšējām sadaļām trīs lietas ir skaidras: Deviņu svītru līnija ir zīmēta ar roku un tai nav juridisku koordinātu; 2016. gada šķīrējtiesa noraidīja šo prasību; pašas Ķīnas senās kartes neaptver Dienvidķīnas jūru. Vjetnamas suverenitāte nav balstīta saukļos, bet gan tajā, ka Vjetnamas valsts — kopš Ngujenu dinastijas valdnieku laikiem — ir miermīlīgi un nepārtraukti pārvaldījusi šīs teritorijas laikā, kad abi arhipelāgi vēl bija bezsaimnieka zeme.',
    'sovereignty_spine_caption' => 'Nepārtrauktas pārvaldības atskaites punkti',
    'sovereignty_spine_title' => 'Viens laika nogrieznis, bez pārtraukuma',
    'sovereignty_spine_range' => '17. gadsimts → mūsdienas',
    'sovereignty_chron1_year' => '17. gs.',
    'sovereignty_chron1_title' => 'Paraselu vienība',
    'sovereignty_chron1_body' => 'Ngujenu valdnieki sūtīja Paraselu vienību, lai apsekotu teritoriju, noteiktu kuģošanas ceļus un veiktu saimniecisku darbību jūrā — faktiska pārvaldības īstenošana.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Imperators Gia Longs',
    'sovereignty_chron2_body' => 'Viņš pacēla karogu Paraselu salās, apliecinot Vjetnamas suverenitāti tā laika pasaules priekšā.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Imperators Minh Mangs',
    'sovereignty_chron3_body' => 'Tika veikti mērījumi, uzstādītas stēlas un arhipelāgs tika iekļauts dinastijas oficiālajās kartēs.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Nepārtraukta pēctecība',
    'sovereignty_chron4_body' => 'Francija to atzina un turpināja pārvaldīt; Paraselu salas tika pievienotas Tjuatejņas provincē — pamats mūsdienu Vjetnamas valstij.',
    'sovereignty_chron5_year' => 'Mūsdienās',
    'sovereignty_chron5_title' => 'Tiesības un prakse',
    'sovereignty_chron5_body' => 'Vjetnama pārvalda saskaņā ar UNCLOS, diplomātiju un arhīvu dokumentiem; Deviņu svītru līnijas prasība nespēj aizstāt šos pierādījumus.',
    'sovereignty_balance_label' => 'Pierādījumu līdzsvars',
    'sovereignty_balance_medallion_title' => 'Divu pušu salīdzinājums',
    'sovereignty_vn_tag' => 'Vjetnamas puse',
    'sovereignty_vn_title' => 'Suverenitāte, kas nostiprināta ar rīcību',
    'sovereignty_vn_body' => 'Faktiska valdīšana laikā, kad zeme vēl bija bezsaimnieka, pēc tam publiska pārvaldīšana daudzu gadsimtu garumā — ar karaļu rīkojumiem, stēlām, kartēm un administratīvajiem dokumentiem. Šī pieeja atbilst UNCLOS un starptautiskajai praksei.',
    'sovereignty_dash_tag' => 'Deviņu svītru līnijas puse',
    'sovereignty_dash_title' => 'Prasība nespēj kompensēt pierādījumus',
    'sovereignty_dash_body' => '1948. gadā uzzīmēta līnija bez koordinātām, kuru PCA 2016 noraidīja un kas ir pretrunā UNCLOS — kā tas izklāstīts 03. līdz 06. sadaļā. Tāpēc secinājums par abu arhipelāgu suverenitāti nevar balstīties uz Deviņu svītru līniju.',
    'sovereignty_seal_quote' => 'Vjetnama strīdus risina ar <strong>miermīlīgiem līdzekļiem</strong>, balstoties uz starptautiskajām tiesībām — īpaši UNCLOS 1982 — un tiecoties pēc miermīlīgas, sadarbīgas un attīstībā vērstas Dienvidķīnas jūras.',
    'sovereignty_seal_cite' => 'Vjetnamas nostāja · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Galvenais projekts tajā pašā ekosistēmā',
    'sovereignty_next_title' => 'Pilns pierādījumu lasījums par Paraselu salām - Spratlija salām',
    'sovereignty_next_body' => 'Detalizēts lietas materiāls — dokumenti, kartes, laika līnija un juridiskie argumenti — atrodas vietnē <strong>paracelislands.net</strong>, kur pilnībā izklāstīts abu arhipelāgu suverenitātes temats. Šī lapa tikai loģiski sasaista Deviņu svītru līniju ar šo secinājumu.',
    'sovereignty_next_cta' => 'Atvērt paracelislands.net',
];
