<?php

return [
    'sovereignty_index' => 'Paraselu salas - Spratlija salas',
    'sovereignty_label' => 'Neizbēgams secinājums',
    'sovereignty_title' => 'Paraselu salas - Spratlija salas',
    'sovereignty_title_accent' => 'pieder Vjetnamai',
    'sovereignty_lead' => 'Šī lapa skaidro Deviņu svītru līniju. Noslēguma daļa atbild uz nākamo jautājumu: kam pieder suverenitāte pār abām salām — Paraselu salām un Spratlija salām? Saskaņā ar pārvaldības vēsturi un starptautiskajām tiesībām konsekventa atbilde ir Vjetnama.',
    'sovereignty_thesis_label' => 'Kopsavilkuma tēze',
    'sovereignty_thesis_lock1' => 'Nav juridisku koordinātu',
    'sovereignty_thesis_lock2' => 'PCA 2016 noraidīja',
    'sovereignty_thesis_lock3' => 'Vecās kartes to neaptver',
    'sovereignty_thesis_body' => 'Pēc sešām iepriekšējām sadaļām ir skaidri trīs punkti: Deviņu svītru līnija ir zīmēta ar roku, tai nav juridisku koordinātu; 2016. gada šķīrējtiesa noraidīja šo prasību; pašas Ķīnas vecās kartes neaptver Dienvidķīnas jūru. Vjetnamas suverenitāte nav balstīta saukļos, bet gan faktā, ka Vjetnamas valsts — jau Nguyễn dinastijas valdnieku laikā — miermīlīgi un nepārtraukti pārvaldīja šo teritoriju, kad abas salas vēl bija nevienam nepiederoša zeme.',
    'sovereignty_spine_caption' => 'Nepārtrauktas pārvaldības atskaites punkti',
    'sovereignty_spine_title' => 'Viens nepārtraukts laika posms',
    'sovereignty_spine_range' => '17. gadsimts → mūsdienas',
    'sovereignty_chron1_year' => '17. gs.',
    'sovereignty_chron1_title' => 'Hoàng Sa vienība',
    'sovereignty_chron1_body' => 'Nguyễn valdnieki nosūtīja Hoàng Sa vienību veikt izpēti, mērīt kuģošanas maršrutus un veikt darbības jūrā — īstenojot faktisku pārvaldību.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Gia Longs',
    'sovereignty_chron2_body' => 'Tika pacelts karogs Paraselu salās, apliecinot Vjetnamas suverenitāti tā laika pasaulei.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Minh Mangs',
    'sovereignty_chron3_body' => 'Salas tika uzmērītas, uzstādītas stēlas un iekļautas galma oficiālajās kartēs.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Nepārtraukta pēctecība',
    'sovereignty_chron4_body' => 'Francija to atzina un turpināja pārvaldību; Paraselu salas tika pievienotas Thừa Thiên provincē — pamats mūsdienu Vjetnamas valstij.',
    'sovereignty_chron5_year' => 'Mūsdienās',
    'sovereignty_chron5_title' => 'Tiesības un prakse',
    'sovereignty_chron5_body' => 'Vjetnama pārvalda saskaņā ar UNCLOS, diplomātiju un arhīvu materiāliem; Deviņu svītru līnijas prasība nespēj aizstāt šos pierādījumus.',
    'sovereignty_balance_label' => 'Pierādījumu līdzsvars',
    'sovereignty_balance_medallion_title' => 'Divu pušu salīdzinājums',
    'sovereignty_vn_tag' => 'Vjetnamas puse',
    'sovereignty_vn_title' => 'Suverenitāte nostiprināta ar darbībām',
    'sovereignty_vn_body' => 'Faktiska iegūšana laikā, kad zeme bija nevienam nepiederoša, kam sekoja atklāta pārvaldība vairāku gadsimtu garumā — ar imperatora rīkojumiem, stēlām, kartēm un administratīviem dokumentiem. Šī pieeja atbilst UNCLOS un starptautiskajai praksei.',
    'sovereignty_dash_tag' => 'Deviņu svītru līnijas puse',
    'sovereignty_dash_title' => 'Prasība nevar aizstāt pierādījumus',
    'sovereignty_dash_body' => '1948. gada līnija bez koordinātām tika noraidīta PCA 2016 un ir pretrunā UNCLOS — kā parādīts 03. līdz 06. sadaļā. Tāpēc secinājumu par abu salu suverenitāti nevar balstīt uz Deviņu svītru līniju.',
    'sovereignty_seal_quote' => 'Vjetnama strīdus risina ar <strong>miermīlīgiem līdzekļiem</strong>, balstoties uz starptautiskajām tiesībām — īpaši UNCLOS 1982 —, lai panāktu mieru, sadarbību un attīstību Dienvidķīnas jūrā.',
    'sovereignty_seal_cite' => 'Vjetnamas nostāja · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Galvenais projekts tajā pašā ekosistēmā',
    'sovereignty_next_title' => 'Pilnīga liecību lasāmviela par Paraselu salām - Spratlija salām',
    'sovereignty_next_body' => 'Detalizētais materiāls — dokumenti, kartes, laika līnija un juridiskie argumenti — ir pieejams vietnē <strong>paracelislands.net</strong>, kur visaptveroši izklāstīta abu salu suverenitātes tēma. Lapa, ko pašlaik lasāt, tikai loģiski sasaista Deviņu svītru līniju ar šo secinājumu.',
    'sovereignty_next_cta' => 'Atvērt paracelislands.net',
];
