<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Starptautisks nolēmums',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trīs "Nē"',
    'verdict_lead' => '2016. gada 12. jūlijā Pastāvīgā šķīrējtiesa (PCA) Hāgā — izveidota saskaņā ar UNCLOS VII pielikumu, lietā Filipīnu prasība pret Ķīnu — pieņēma nolēmumu, ar kuru noraidīja Deviņu svītru līnija prasības. <em>Noklikšķiniet uz katras kartītes, lai izlasītu pilnu tekstu.</em>',
    'verdict_card1_khong' => 'NĒ',
    'verdict_card1_title' => 'vēsturisko tiesību',
    'verdict_card1_short' => 'Nav juridiska pamata, lai Ķīna varētu apgalvot vēsturiskās tiesības uz resursiem jūrā, kas atrodas Deviņu svītru līnija robežās.',
    'verdict_card1_quote' => '“Nav juridiska pamata tam, lai Ķīna izvirzītu vēsturiskās tiesības uz resursiem, kas atrodas jūras zonā Deviņu svītru līnija iekšpusē.”',
    'verdict_card1_more' => '+ Lasīt nolēmumu',
    'verdict_card2_khong' => 'NĒ',
    'verdict_card2_title' => 'objekta, kas rada EEZ',
    'verdict_card2_short' => 'Neviens no Spratlija salas esošajiem objektiem neatbilst kritērijiem, lai Ķīnai radītu ekskluzīvo ekonomisko zonu — tostarp arī Ba Binh sala.',
    'verdict_card2_quote' => '“Neviens no objektiem Spratlija salās nespēj radīt ekskluzīvo ekonomisko zonu.”',
    'verdict_card2_more' => '+ Lasīt nolēmumu',
    'verdict_card3_khong' => 'NĒ',
    'verdict_card3_title' => 'likumīgas rīcības',
    'verdict_card3_short' => 'Ķīna pārkāpa Filipīnu suverēnās tiesības, traucēja zvejai un nodarīja kaitējumu jūras videi.',
    'verdict_card3_quote' => '“Ķīna ir pārkāpusi Filipīnu suverēnās tiesības, iejaukusies zvejas darbībās Scarborough sēklī un nodarījusi nopietnu kaitējumu koraļļu rifu videi.”',
    'verdict_card3_more' => '+ Lasīt nolēmumu',
    'verdict_extra1' => 'Ķīnas pašu uzzīmētā Deviņu svītru līnija <strong>nav saderīga</strong> ar 1982. gada UNCLOS.',
    'verdict_extra2' => 'Ķīna, pārmērīgi izmantojot resursus un būvējot mākslīgās salas, nodarījusi kaitējumu Spratlija salu ekosistēmai.',
    'verdict_extra3' => 'Ķīnas rīcība ir palielinājusi konflikta risku ar Filipīnām.',
    'verdict_extra4' => 'Ba Binh sala (ko kontrolē Taivāna) arī nevar radīt EEZ.',
    'verdict_subtitle' => 'Kāpēc tas ir pretrunā ar UNCLOS?',
    'verdict_subtitle_body' => '1982. gada UNCLOS skaidri nosaka jūras zonas, balstoties uz piekrastes valsts bāzes līniju. Deviņu svītru līnija prasījums pārsniedz šo ietvaru, tādēļ tos nevar salāgot.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoriālā jūra (jūras jūdzes)',
    'verdict_zone1_body' => 'Valsts jūras josla, pār kuru valstij ir suverēna vara, mērīta no bāzes līnijas.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Ekskluzīvā ekonomiskā zona',
    'verdict_zone2_body' => 'EEZ — piekrastes valstij šajā teritorijā ir suverēnās tiesības uz resursiem.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentālais šelfs (maks., jūras jūdzes)',
    'verdict_zone3_body' => 'Tiesības uz jūras gultnes resursiem, saskaņā ar noteiktiem ģeoloģiskiem nosacījumiem.',
    'verdict_foot' => 'Šajā ietvarā “vēsturiskās tiesības”, kas aptver veselu atklātās jūras teritoriju — kā to paredz Deviņu svītru līnija — <em>ir aizstātas</em> ar UNCLOS tiesisko režīmu, kura dalībniece ir arī Ķīna.',
];
