<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Starptautiskais nolēmums',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trīs "nē"',
    'verdict_lead' => '2016. gada 12. jūlijā Pastāvīgā arbitrāžas tiesa (PCA) Hāgā — izveidota saskaņā ar UNCLOS VII pielikumu lietā, ko Filipīnas bija ierosinājušas pret Ķīnu — pieņēma nolēmumu, ar kuru tika noraidīta Deviņu svītru līnija. <em>Noklikšķiniet uz katras kartītes, lai lasītu pilnu tekstu.</em>',
    'verdict_card1_khong' => 'NĒ',
    'verdict_card1_title' => 'vēsturiskām tiesībām',
    'verdict_card1_short' => 'Nav juridiska pamata, lai Ķīna varētu atsaukties uz vēsturiskām tiesībām uz resursiem ūdeņos, kas atrodas Deviņu svītru līnijā.',
    'verdict_card1_quote' => '“Nav juridiska pamata, lai Ķīna varētu atsaukties uz vēsturiskām tiesībām uz resursiem ūdeņos, kas atrodas Deviņu svītru līnijā.”',
    'verdict_card1_more' => '+ Lasīt nolēmumu',
    'verdict_card2_khong' => 'NĒ',
    'verdict_card2_title' => 'subjektam, kas rada EEZ',
    'verdict_card2_short' => 'Neviena no Spratlija salu arhipelāga vienībām nav pietiekama, lai Ķīnai radītu ekskluzīvo ekonomisko zonu — arī Ba Binh sala.',
    'verdict_card2_quote' => '“Neviena no Spratlija salu arhipelāga vienībām nespēj izveidot ekskluzīvo ekonomisko zonu.”',
    'verdict_card2_more' => '+ Lasīt nolēmumu',
    'verdict_card3_khong' => 'NĒ',
    'verdict_card3_title' => 'likumīgai rīcībai',
    'verdict_card3_short' => 'Ķīna pārkāpa Filipīnu suverēnās tiesības, traucēja zvejai un kaitēja jūras videi.',
    'verdict_card3_quote' => '“Ķīna ir pārkāpusi Filipīnu suverēnās tiesības, iejaukusies zvejas darbībās Scarborough sēklī un nodarījusi nopietnu kaitējumu koraļļu rifu videi.”',
    'verdict_card3_more' => '+ Lasīt nolēmumu',
    'verdict_extra1' => 'Ķīnas paša uzzīmētā Deviņu svītru līnija <strong>nav saderīga</strong> ar 1982. gada UNCLOS.',
    'verdict_extra2' => 'Ķīna ir nodarījusi kaitējumu Spratlija salu ekosistēmai pārmērīgas ieguves un mākslīgo salu būvniecības dēļ.',
    'verdict_extra3' => 'Ķīnas rīcība ir palielinājusi konflikta risku ar Filipīnām.',
    'verdict_extra4' => 'Ba Binh sala (Taivānas kontrolē) arī nevar izveidot EEZ.',
    'verdict_subtitle' => 'Kāpēc tas ir pretrunā ar UNCLOS?',
    'verdict_subtitle_body' => '1982. gada UNCLOS skaidri nosaka jūras zonu robežas, balstoties uz piekrastes valsts bāzes līnijām. Deviņu svītru līnijas prasība pārsniedz šo ietvaru, tāpēc to nav iespējams savienot.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoriālā jūra (jūras jūdzes)',
    'verdict_zone1_body' => 'Valsts jūras teritorija ar suverenitāti, skaitot no bāzes līnijas.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Ekskluzīvā ekonomiskā zona',
    'verdict_zone2_body' => 'EEZ — piekrastes valstij šajā zonā ir suverēnās tiesības uz resursiem.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentālais šelfs (maksimums, jūras jūdzes)',
    'verdict_zone3_body' => 'Tiesības uz jūras gultnes resursiem, atbilstoši noteiktiem ģeoloģiskiem nosacījumiem.',
    'verdict_foot' => 'Šajā ietvarā “vēsturiskās tiesības”, kas aptver visu atklāto jūras zonu — kā to paredz Deviņu svītru līnija — <em>ir aizstātas</em> ar UNCLOS tiesisko režīmu, kura dalībvalsts ir arī Ķīna.',
];
