<?php

return [
    'footer_index' => 'Aklatan',
    'footer_crest_eyebrow' => 'Pagtatapos ng aklatan ng katotohanan',
    'footer_crest_quote' => '“Ang kapayapaan sa Dagat Timog Tsina ay nakabatay sa <b>Pandaigdigang Batas</b>.”',
    'footer_crest_sub' => 'Walang poot · Katotohanan lamang',
    'footer_nav_aria' => 'Mga aksyon sa ibaba ng pahina',
    'footer_btn_top' => 'Pabalik sa itaas',
    'footer_btn_verdict' => 'Pasya ng PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linya ng Siyam na Guhit',
    'footer_brand_body' => 'Isang paliwanag na nakabatay sa obhetibong katotohanan, pandaigdigang batas, at mga makasaysayang dokumento — itinatakwil ang pag-aangkin sa Linya ng Siyam na Guhit sa pamamagitan ng ebidensya, hindi ng mga islogan.',
    'footer_refs_title' => 'Mga sanggunian',
    'footer_ref1' => 'Pasya ng PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — buong teksto',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Mga makasaysayang materyales at sinaunang mapa',
    'footer_toc_title' => 'Talaan ng nilalaman ng pahina',
    'footer_toc1' => 'Ano ang Linya ng Siyam na Guhit',
    'footer_toc2' => 'Pinagmulan',
    'footer_toc3' => 'Bakit ito pinagtatalunan',
    'footer_toc4' => 'Bakit ito tinututulan sa internasyonal na antas',
    'footer_toc5' => 'Tahimik na mga saksi',
    'footer_toc6' => 'Pasya ng PCA 2016',
    'footer_toc7' => 'Kapuluang Paracel – Kapuluang Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Obhetibong katotohanan tungkol sa Dagat Timog Tsina.<br>Ecosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Walang koordinada',
];
