<?php

return [
    'footer_index' => 'Aklatan',
    'footer_crest_eyebrow' => 'Pagtatapos ng aklatan ng katotohanan',
    'footer_crest_quote' => '“Ang kapayapaan sa Dagat Timog Tsina ay nakabatay sa <b>Internasyonal na Batas</b>.”',
    'footer_crest_sub' => 'Walang poot · Katotohanan lamang',
    'footer_nav_aria' => 'Mga aksyon sa ibaba ng pahina',
    'footer_btn_top' => 'Bumalik sa itaas',
    'footer_btn_verdict' => 'Pasyang PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Pag-angkin sa Linya ng Siyam na Guhit',
    'footer_brand_eyebrow' => 'Espesyal na pahina · Soberanya ng Biyetnam',
    'footer_brand_body' => 'Ipinaliliwanag ang Linya ng Siyam na Guhit sa pamamagitan ng objektibong katotohanan, internasyonal na batas, pasyang PCA 2016, at mga historikal na dokumento — karagdagan sa mga masusing pahina tungkol sa soberanya ng dalawang kapuluan <strong>"Kapuluang Paracel at Kapuluang Spratly"</strong>. Pinabubulaanan ang walang saysay na pag-aangkin ng Tsina sa pamamagitan ng kasaysayan at ebidensya.',
    'footer_refs_title' => 'Mga sanggunian',
    'footer_ref1' => 'Pasyang PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — buong teksto',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Mga historikal na dokumento at sinaunang mapa',
    'footer_toc_title' => 'Talaan ng nilalaman ng pahina',
    'footer_toc1' => 'Ano ang Linya ng Siyam na Guhit',
    'footer_toc2' => 'Pinagmulan',
    'footer_toc3' => 'Bakit ito pinagtatalunan',
    'footer_toc4' => 'Bakit ito tinututulan sa internasyonal na antas',
    'footer_toc5' => 'Mga tahimik na saksi',
    'footer_toc6' => 'Pasyang PCA 2016',
    'footer_toc7' => 'Kapuluang Paracel – Kapuluang Spratly',
    'footer_copy_eyebrow' => 'Proyektong hindi para sa kita',
    'footer_copy_title' => 'Ang Kapuluang Paracel – Kapuluang Spratly ay bahagi ng Biyetnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Espesyal na pahina tungkol sa Linya ng Siyam na Guhit sa ekosistemang pang-soberanya ng Biyetnam.',
    'footer_copy_body' => 'Ipinaliliwanag ang pag-aangkin sa Linya ng Siyam na Guhit sa pamamagitan ng <strong>objektibong katotohanan</strong>, <strong>internasyonal na batas</strong>, pasyang PCA 2016, at mga historikal na dokumento — karagdagan sa mga masusing pahina tungkol sa soberanya ng dalawang kapuluan na Kapuluang Paracel at Kapuluang Spratly.',
    'footer_copy_ecosystem_aria' => 'Mga pahinang kabilang sa parehong proyekto',
    'footer_copy_ecosystem_label' => 'Parehong ekosistema',
    'footer_copy_disclaimer' => 'Ang nilalaman ay para sa edukasyon at pagpapataas ng kamalayan; hindi nito pinapalitan ang opisyal na pananaw ng Pamahalaan ng Biyetnam.',
    'footer_copy' => '<strong>© :year Linya ng Siyam na Guhit</strong> — Bahagi ng proyektong hindi para sa kita <strong>Ang Kapuluang Paracel – Kapuluang Spratly ay bahagi ng Biyetnam</strong> na kabilang sa sistemang: <a href="https://paracelislands.net/fil" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/fil" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/fil" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/fil" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/fil" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Pangako sa nilalaman ng pahina',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Pasyang PCA 2016',
    'footer_chip3' => 'Makasaysayang ebidensya',
    'footer_chip4' => 'Mga sinaunang mapa',
    'footer_chip5' => 'Objektibong katotohanan',
    'footer_chip6' => 'Kapayapaan sa Dagat Timog Tsina',
];
