<?php

return [
    'footer_index' => 'Aklatan',
    'footer_crest_eyebrow' => 'Pagtatapos ng aklatan ng katotohanan',
    'footer_crest_quote' => '“Ang kapayapaan sa Dagat Timog Tsina ay nakasalalay sa pundasyon ng <b>Pandaigdigang Batas</b>.”',
    'footer_crest_sub' => 'Walang poot · Katotohanan lamang',
    'footer_nav_aria' => 'Mga aksyon sa ibaba ng pahina',
    'footer_btn_top' => 'Bumalik sa itaas',
    'footer_btn_verdict' => 'Pasya ng PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Pag-aangkin sa Linya ng Siyam na Guhit',
    'footer_brand_eyebrow' => 'Espesyal na pahina · Soberanya ng Biyetnam',
    'footer_brand_body' => 'Paliwanag tungkol sa Linya ng Siyam na Guhit sa pamamagitan ng obhetibong katotohanan, pandaigdigang batas, pasya ng PCA 2016 at mga makasaysayang dokumento — dagdag sa mga masusing pahina tungkol sa soberanya ng dalawang kapuluan <strong>"Kapuluang Paracel at Kapuluang Spratly"</strong>. Pinapabulaanan ang walang batayang pag-aangkin ng Tsina gamit ang kasaysayan at ebidensya.',
    'footer_refs_title' => 'Mga sanggunian',
    'footer_ref1' => 'Pasya ng PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — buong teksto',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Mga makasaysayang dokumento at lumang mapa',
    'footer_toc_title' => 'Nilalaman ng pahina',
    'footer_toc1' => 'Ano ang Linya ng Siyam na Guhit',
    'footer_toc2' => 'Pinagmulan',
    'footer_toc3' => 'Bakit ito kontrobersyal',
    'footer_toc4' => 'Bakit ito tinututulan ng pandaigdigang komunidad',
    'footer_toc5' => 'Tahimik na mga saksi',
    'footer_toc6' => 'Pasya ng PCA 2016',
    'footer_toc7' => 'Kapuluang Paracel – Kapuluang Spratly',
    'footer_copy_eyebrow' => 'Proyektong walang tubo',
    'footer_copy_title' => 'Ang Kapuluang Paracel – Kapuluang Spratly ay sa Biyetnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Espesyal na pahina tungkol sa Linya ng Siyam na Guhit sa ekosistema ng soberanya ng Biyetnam.',
    'footer_copy_body' => 'Paliwanag sa pag-aangkin sa Linya ng Siyam na Guhit sa pamamagitan ng <strong>obhetibong katotohanan</strong>, <strong>pandaigdigang batas</strong>, pasya ng PCA 2016 at mga makasaysayang dokumento — dagdag sa mga masusing pahina tungkol sa soberanya ng dalawang kapuluan ng Kapuluang Paracel at Kapuluang Spratly.',
    'footer_copy_ecosystem_aria' => 'Mga pahina ng parehong proyekto',
    'footer_copy_ecosystem_label' => 'Kaparehong ekosistema',
    'footer_copy_disclaimer' => 'Ang nilalaman ay para sa edukasyon at pagpapataas ng kamalayan; hindi nito pinapalitan ang opisyal na pananaw ng Estado ng Biyetnam.',
    'footer_copy' => '<strong>© :year Linya ng Siyam na Guhit</strong> — Bahagi ng proyektong walang tubo <strong>Ang Kapuluang Paracel – Kapuluang Spratly ay sa Biyetnam</strong> na kabilang sa sistemang: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Pangako sa nilalaman ng pahina',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Pasya ng PCA 2016',
    'footer_chip3' => 'Makasaysayang ebidensya',
    'footer_chip4' => 'Lumang mapa',
    'footer_chip5' => 'Obhetibong katotohanan',
    'footer_chip6' => 'Kapayapaan sa Dagat Timog Tsina',
];
