<?php

return [
    'nav_logo_name' => 'Linya ng Siyam na Guhit',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linya ng Siyam na Guhit',
    'nav_rail_aria' => 'Pag-navigate ayon sa seksyon',
    'nav_rail_what' => 'Kahulugan',
    'nav_rail_origin' => 'Pinagmulan',
    'nav_rail_dispute' => 'Alitan',
    'nav_rail_opposition' => 'Pagtutol',
    'nav_rail_witnesses' => 'Mga Sinaunang Mapa',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Kapuluang Paracel – Kapuluang Spratly',
    'nav_sound_off' => 'I-on ang background music',
    'nav_sound_on' => 'I-off ang background music',
    'nav_share' => 'Ibahagi',
    'dialog_title' => 'Wikang ipinapakita',
    'language' => 'Wika',
    'display_hint' => ':count na wika',
    'search_placeholder' => 'Maghanap ng wika…',
    'cancel' => 'Kanselahin',
    'apply' => 'Ilapat',
    'sound_off' => 'I-on ang tunog sa background',
    'sound_on' => 'I-off ang tunog sa background',
    'lang_trigger' => 'Pumili ng wika',
    'close' => 'Isara',
    'no_results' => 'Walang nahanap na wika',
    'contribute' => 'Ibahagi',
];
