<?php

return [
    'opposition_index' => 'Pagtutol',
    'opposition_label' => 'Bakit tumututol ang pandaigdigang komunidad',
    'opposition_title' => 'Ang pagtutol ay nakabatay sa',
    'opposition_title_accent' => 'batas, hindi sa damdamin',
    'opposition_lead' => 'Kaagad matapos iharap ang Linya ng Siyam na Guhit sa United Nations noong 2009, maraming bansa at mga iskolar ang tumutol — gamit ang mga tiyak na argumentong legal.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayo',
    'opposition_voice1_title' => 'Biyetnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Isang araw lamang matapos isumite ng Tsina ang mapa ng Linya ng Siyam na Guhit sa Kalihim-Heneral ng United Nations (7/5/2009), sunud-sunod na nagsumite ang mga bansang ito ng mga diplomatikong nota ng pagtutol, na itinakwil ang pag-angkin.',
    'opposition_voice1_chip1' => 'Diplomatikong nota ng pagtutol',
    'opposition_voice1_chip2' => 'Hindi alinsunod sa UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Pilipinas',
    'opposition_voice2_body' => 'Nagpadala ng diplomatikong liham sa United Nations, na nagsasabing ang pag-angkin ng Tsina sa Dagat ng Timog Tsina ay “walang batayan sa ilalim ng internasyonal na batas” — na naging batayan ng kasunod na kaso sa Arbitrasyon.',
    'opposition_voice2_chip1' => 'Batayan ng kaso sa PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kagawaran ng Estado ng Estados Unidos — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Ipinakita ng pagsusuri na: hindi pare-pareho ang mga mapa sa iba’t ibang taon sa lokasyon ng linya; ang linya ay pumapasok sa lupain sa halip na gumamit ng gitnang linya; at maraming entidad ang hindi umaabot sa pamantayan ng “isla” upang magkaroon ng EEZ.',
    'opposition_voice3_chip1' => 'Hindi tumutugon sa mga legal na pamantayan',
    'opposition_voice3_chip2' => 'Opisyal na pagsusuri',
    'opposition_voice4_year' => 'Akademiko',
    'opposition_voice4_title' => 'Luma na ang “makasaysayang katubigan”',
    'opposition_voice4_body' => 'Ang konseptong ito ay nalalapat lamang sa mga look at malapit-sa-baybayin na mga kipot — hindi nito maaaring saklawin ang isang malawak na bahagi ng bukas na dagat. Noong 2003, maging ang Taiwan mismo ay tumanggi sa patakarang “makasaysayang katubigan” na minsang binanggit noong 1993.',
    'opposition_voice4_chip1' => 'Maging ang mga iskolar mula sa Tsina ay hindi nagkakaisa',
];
