<?php

return [
    'opposition_index' => 'Pagtutol',
    'opposition_label' => 'Bakit tumututol ang internasyonal na komunidad',
    'opposition_title' => 'Ang pagtutol ay nakabatay sa',
    'opposition_title_accent' => 'batas, hindi sa damdamin',
    'opposition_lead' => 'Di-naglaon matapos isumite ang Linya ng Siyam na Guhit sa United Nations noong 2009, maraming bansa at iskolar ang tumutol — gamit ang mga tiyak na argumentong legal.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayo',
    'opposition_voice1_title' => 'Biyetnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Isang araw lamang matapos isumite ng Tsina ang mapa ng Linya ng Siyam na Guhit sa Kalihim-Heneral ng United Nations (7/5/2009), sunud-sunod na nagsumite ng mga note verbale ng pagtutol ang mga bansang ito, at tinanggihan ang pag-aangkin.',
    'opposition_voice1_chip1' => 'Note verbale ng pagtutol',
    'opposition_voice1_chip2' => 'Hindi alinsunod sa UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Pilipinas',
    'opposition_voice2_body' => 'Nagsumite ng diplomatikong liham sa United Nations, at idineklara na ang pag-aangkin ng Tsina sa South China Sea ay “walang batayan sa ilalim ng pandaigdigang batas” — na naging paunang hakbang sa kasong isinampa sa Arbitration Tribunal kalaunan.',
    'opposition_voice2_chip1' => 'Paunang hakbang sa kaso sa PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kagawaran ng Estado ng U.S. — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Ipinakita ng pagsusuri: hindi magkakatugma ang mga mapa ng iba’t ibang taon sa lokasyon ng guhit; ang guhit ay pumapasok sa lupain sa halip na sundin ang median line; at maraming tampok ang hindi sapat ang pamantayan upang maituring na “isla” na may EEZ.',
    'opposition_voice3_chip1' => 'Hindi tumutupad sa mga legal na pamantayan',
    'opposition_voice3_chip2' => 'Opisyal na pagsusuri',
    'opposition_voice4_year' => 'Akademiko',
    'opposition_voice4_title' => 'Luma na ang “makasaysayang katubigan”',
    'opposition_voice4_body' => 'Ang konseptong ito ay naaangkop lamang sa mga look at mga bahaging-dagat na malapit sa pampang — hindi nito maaaring saklawin ang isang malawak na dagat na nasa malayo sa baybayin. Noong 2003, maging ang Taiwan ay tumanggi rin sa patakarang “makasaysayang katubigan” na inihayag noon pang 1993.',
    'opposition_voice4_chip1' => 'Kahit mga iskolar sa Tsina ay hindi nagkakaisa',
];
