<?php

return [
    'sovereignty_index' => 'Kapuluang Paracel - Kapuluang Spratly',
    'sovereignty_label' => 'Kongklusyong lohikal',
    'sovereignty_title' => 'Kapuluang Paracel - Kapuluang Spratly',
    'sovereignty_title_accent' => 'ay sa Biyetnam',
    'sovereignty_lead' => 'Ipinaliliwanag ng pahinang ito ang Linya ng Siyam na Guhit. Sumasagot ang bahaging pangwakas sa susunod na tanong: sino ang may soberanya sa dalawang kapuluang Kapuluang Paracel at Kapuluang Spratly? Batay sa kasaysayan ng pamamahala at sa pandaigdigang batas, iisa ang sagot: Biyetnam.',
    'sovereignty_thesis_label' => 'Pinagsamang argumento',
    'sovereignty_thesis_lock1' => 'Walang ligal na koordinado',
    'sovereignty_thesis_lock2' => 'Pinawalang-bisa ng PCA 2016',
    'sovereignty_thesis_lock3' => 'Hindi saklaw ng mga sinaunang mapa',
    'sovereignty_thesis_body' => 'Pagkaraan ng anim na seksyon sa itaas, malinaw na ang tatlong punto: ang Linya ng Siyam na Guhit ay iginuhit lamang sa kamay at walang ligal na koordinado; pinawalang-bisa ng Arbitral Tribunal noong 2016 ang pag-aangkin; at ang mga sinaunang mapa mismo ng Tsina ay hindi sumasaklaw sa Dagat Timog Tsina. Ang soberanya ng Biyetnam ay hindi nakabatay sa mga islogan kundi sa katotohanang ang pamahalaang Biyetnam — mula pa noong panahon ng mga Nguyễn chúa — ay mapayapa at tuluy-tuloy na namahala noong ang dalawang kapuluan ay lupang walang may-ari pa.',
    'sovereignty_spine_caption' => 'Tuloy-tuloy na mga palatandaan ng pamamahala',
    'sovereignty_spine_title' => 'Isang timeline, walang putol',
    'sovereignty_spine_range' => 'Ika-17 siglo → kasalukuyan',
    'sovereignty_chron1_year' => 'Ika-17 siglo',
    'sovereignty_chron1_title' => 'Pangkat ng Hoang Sa',
    'sovereignty_chron1_body' => 'Nagpadala ang mga Nguyễn chúa ng pangkat ng Hoang Sa upang magsiyasat, sukatin ang rutang pandagat, at mangisda at mangalap sa dagat — na nagsasakatuparan ng aktuwal na pamamahala.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Haring Gia Long',
    'sovereignty_chron2_body' => 'Itinaas ang bandila sa Kapuluang Paracel, na nagpapatibay sa soberanya ng Biyetnam sa harap ng mga bansang nasa panahong iyon.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Haring Minh Mạng',
    'sovereignty_chron3_body' => 'Sinukat, naglagay ng mga stela, at itinala ang mga kapuluan sa opisyal na mga mapa ng korte ng hari.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Patuloy na pagmamana',
    'sovereignty_chron4_body' => 'Kinilala at ipinagpatuloy ng Pransya ang pamamahala; isinama ang Hoang Sa sa lalawigan ng Thừa Thiên — na naging pundasyon ng kasalukuyang Estado ng Biyetnam.',
    'sovereignty_chron5_year' => 'Kasalukuyan',
    'sovereignty_chron5_title' => 'Batas at aktuwal na kalagayan',
    'sovereignty_chron5_body' => 'Pinamamahalaan ng Biyetnam ayon sa UNCLOS, diplomasya, at mga tala sa arkibo; hindi napapalitan ng pag-aangkin ng Linya ng Siyam na Guhit ang ebidensiyang ito.',
    'sovereignty_balance_label' => 'Balanse ng ebidensiya',
    'sovereignty_balance_medallion_title' => 'Paghahambing ng dalawang panig',
    'sovereignty_vn_tag' => 'Panig ng Biyetnam',
    'sovereignty_vn_title' => 'Ang soberanya ay itinatatag sa pamamagitan ng mga kilos',
    'sovereignty_vn_body' => 'Tunay na pag-aari noong ang lupain ay walang may-ari pa, kasunod ang hayag na pamamahala sa loob ng maraming siglo — may mga opisyal na dokumento, stela, mapa, at mga rekord pang-administratibo. Ang paraang ito ay umaayon sa UNCLOS at sa pandaigdigang nakagawiang batas.',
    'sovereignty_dash_tag' => 'Panig ng Linya ng Siyam na Guhit',
    'sovereignty_dash_title' => 'Hindi napapantayan ng pag-aangkin ang ebidensiya',
    'sovereignty_dash_body' => 'Isang linyang iginuhit noong 1948, walang koordinado, na pinawalang-bisa ng PCA 2016 at salungat sa UNCLOS — gaya ng inilatag sa mga seksyon 03 hanggang 06. Iyan ang dahilan kung bakit hindi maaaring ibatay sa Linya ng Siyam na Guhit ang kongklusyon hinggil sa soberanya ng dalawang kapuluan.',
    'sovereignty_seal_quote' => 'Nilulutas ng Biyetnam ang mga sigalot sa pamamagitan ng <strong>mapayapang paraan</strong>, batay sa pandaigdigang batas — lalo na sa UNCLOS 1982 — tungo sa isang Dagat Timog Tsina na mapayapa, kooperatibo, at umuunlad.',
    'sovereignty_seal_cite' => 'Pananaw ng Biyetnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Pangunahing proyekto sa parehong ekosistema',
    'sovereignty_next_title' => 'Basahin ang buong ebidensiya tungkol sa Hoang Sa – Trường Sa',
    'sovereignty_next_body' => 'Ang detalyadong talaan — mga dokumento, mapa, timeline, at mga batayang legal — ay nasa <strong>paracelislands.net</strong>, kung saan inilalahad nang buo ang paksa ng soberanya sa dalawang kapuluan. Ang pahinang binabasa mo ngayon ay nag-uugnay lamang ng lohika mula sa Linya ng Siyam na Guhit patungo sa kongklusyong iyon.',
    'sovereignty_next_cta' => 'Buksan ang paracelislands.net',
];
