<?php

return [
    'sovereignty_index' => 'Kapuluang Paracel - Kapuluang Spratly',
    'sovereignty_label' => 'Ang kinakailangang konklusyon',
    'sovereignty_title' => 'Kapuluang Paracel - Kapuluang Spratly',
    'sovereignty_title_accent' => 'ay sa Biyetnam',
    'sovereignty_lead' => 'Ipinaliliwanag ng pahinang ito ang Linya ng Siyam na Guhit. Ang bahaging konklusyon ay sumasagot sa susunod na tanong: sino ang may soberanya sa dalawang kapuluan ng Kapuluang Paracel at Kapuluang Spratly? Batay sa kasaysayan ng pangangasiwa at sa pandaigdigang batas, ang magkakaugnay na sagot ay Biyetnam.',
    'sovereignty_thesis_label' => 'Pinagsamang argumento',
    'sovereignty_thesis_lock1' => 'Walang legal na koordinado',
    'sovereignty_thesis_lock2' => 'Itinakwil ng PCA noong 2016',
    'sovereignty_thesis_lock3' => 'Hindi saklaw ng mga sinaunang mapa',
    'sovereignty_thesis_body' => 'Pagkatapos ng anim na naunang bahagi, malinaw na ang tatlong punto: ang Linya ng Siyam na Guhit ay iginuhit sa kamay at walang legal na koordinado; tinanggihan ng Arbitration Tribunal noong 2016 ang pag-aangkin; at ang mga sinaunang mapa ng mismong Tsina ay hindi saklaw ang Dagat Timog Tsina. Ang soberanya ng Biyetnam ay hindi nakabatay sa islogan kundi sa katotohanang ang estadong Biyetnames, mula pa noong panahon ng mga Nguyễn na pinuno, ay mapayapa at tuluy-tuloy na namahala noong ang dalawang kapuluan ay lupang walang may-ari pa.',
    'sovereignty_spine_caption' => 'Mga palatandaan ng tuloy-tuloy na pamamahala',
    'sovereignty_spine_title' => 'Isang timeline, walang putol',
    'sovereignty_spine_range' => 'Ika-17 siglo → kasalukuyan',
    'sovereignty_chron1_year' => 'Ika-17 siglo',
    'sovereignty_chron1_title' => 'Pangkat ng Hoàng Sa',
    'sovereignty_chron1_body' => 'Nagpadala ang mga Nguyễn na pinuno ng pangkat ng Hoàng Sa upang magsuri, sukatin ang mga rutang pandagat, at magsagawa ng gawaing pandagat — na siyang aktuwal na pagpapatupad ng pamamahala.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Haring Gia Long',
    'sovereignty_chron2_body' => 'Nagtaas ng watawat sa Kapuluang Paracel, na nagpatibay ng soberanya ng Biyetnam sa harap ng mundo noon.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Haring Minh Mạng',
    'sovereignty_chron3_body' => 'Sinukat, nagtayo ng mga bato/palatandaan, at isinama ang kapuluan sa opisyal na mga mapa ng korte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Tuloy-tuloy na paglipat',
    'sovereignty_chron4_body' => 'Kinilala at ipinagpatuloy ng Pransiya ang pamamahala; isinama ang Hoàng Sa sa lalawigan ng Thừa Thiên — isang batayan para sa kasalukuyang Estado ng Biyetnam.',
    'sovereignty_chron5_year' => 'Kasalukuyan',
    'sovereignty_chron5_title' => 'Batas at praktika',
    'sovereignty_chron5_body' => 'Pinangangasiwaan ng Biyetnam alinsunod sa UNCLOS, diplomasya, at mga archival record; hindi napapalitan ng pag-aangkin ng Linya ng Siyam na Guhit ang ebidensyang ito.',
    'sovereignty_balance_label' => 'Balanse ng ebidensya',
    'sovereignty_balance_medallion_title' => 'Paghahambing ng dalawang panig',
    'sovereignty_vn_tag' => 'Panig ng Biyetnam',
    'sovereignty_vn_title' => 'Ang soberanya ay naitatag sa pamamagitan ng mga kilos',
    'sovereignty_vn_body' => 'Aktuwal na pag-aari noong ang lupain ay walang may-ari pa, pagkatapos ay hayagang pinamahalaan sa loob ng maraming siglo — na may mga imperyal na rekord, mga bato/palatandaan, mapa, at mga administratibong tala. Ang paraang ito ay umaayon sa UNCLOS at sa internasyonal na nakagawiang batas.',
    'sovereignty_dash_tag' => 'Panig ng Linya ng Siyam na Guhit',
    'sovereignty_dash_title' => 'Hindi napupunan ng pag-aangkin ang kakulangan sa ebidensya',
    'sovereignty_dash_body' => 'Isang linyang iginuhit noong 1948, walang mga koordinado, na tinanggihan ng PCA noong 2016 at salungat sa UNCLOS — gaya ng ipinakita ng mga bahagi 03 hanggang 06. Iyan ang dahilan kung bakit hindi maaaring ibatay sa Linya ng Siyam na Guhit ang konklusyon tungkol sa soberanya ng dalawang kapuluan.',
    'sovereignty_seal_quote' => 'Nilulutas ng Biyetnam ang mga sigalot sa pamamagitan ng <strong>mapayapang paraan</strong>, batay sa pandaigdigang batas — lalo na sa UNCLOS 1982 — tungo sa isang mapayapa, kooperatibo, at umuunlad na Dagat Timog Tsina.',
    'sovereignty_seal_cite' => 'Paninindigan ng Biyetnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Pangunahing proyekto sa parehong ecosystem',
    'sovereignty_next_title' => 'Basahin ang buong ebidensya tungkol sa Kapuluang Paracel - Kapuluang Spratly',
    'sovereignty_next_body' => 'Ang detalyadong talaan — mga dokumento, mapa, timeline, at mga legal na batayan — ay nasa <strong>paracelislands.net</strong>, kung saan inilalahad nang buo ang paksa ng soberanya sa dalawang kapuluan. Ang pahinang binabasa mo ngayon ay nag-uugnay lamang nang lohikal mula sa Linya ng Siyam na Guhit patungo sa konklusyong iyon.',
    'sovereignty_next_cta' => 'Buksan ang paracelislands.net',
];
