<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Pandaigdigang Hatol',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tatlong “Hindi”',
    'verdict_lead' => 'Noong 12/7/2016, ang Permanent Court of Arbitration (PCA) sa The Hague — na itinayo sa ilalim ng Annex VII ng UNCLOS, sa kasong isinampa ng Pilipinas laban sa Tsina — ay naglabas ng hatol na tumanggi sa paghahabol ng Linya ng Siyam na Guhit. <em>I-click ang bawat kard upang mabasa ang buong teksto.</em>',
    'verdict_card1_khong' => 'HINDI',
    'verdict_card1_title' => 'makasaysayang karapatan',
    'verdict_card1_short' => 'Walang batayang legal para igiit ng Tsina ang makasaysayang karapatan sa mga yamang-biya sa dagat na nasa loob ng Linya ng Siyam na Guhit.',
    'verdict_card1_quote' => '“Walang batayang legal para igiit ng Tsina ang mga makasaysayang karapatan sa mga yamang-nasa-dagat sa loob ng Linya ng Siyam na Guhit.”',
    'verdict_card1_more' => '+ Basahin ang hatol',
    'verdict_card2_khong' => 'HINDI',
    'verdict_card2_title' => 'bagay na lumilikha ng EEZ',
    'verdict_card2_short' => 'Walang anumang katangian sa Kapuluang Spratly na sapat upang lumikha ng eksklusibong sonang ekonomiko para sa Tsina — kabilang ang Ba Bình.',
    'verdict_card2_quote' => '“Walang anumang bagay sa Kapuluang Spratly na may kakayahang lumikha ng eksklusibong sonang ekonomiko.”',
    'verdict_card2_more' => '+ Basahin ang hatol',
    'verdict_card3_khong' => 'HINDI',
    'verdict_card3_title' => 'legal na kilos',
    'verdict_card3_short' => 'Nilabag ng Tsina ang mga karapatang soberano ng Pilipinas, humadlang sa pangingisda, at sumira sa kapaligiran ng dagat.',
    'verdict_card3_quote' => '“Nilabag ng Tsina ang mga karapatang soberano ng Pilipinas, nanghimasok sa pangingisda sa Scarborough Shoal, at nagdulot ng malubhang pinsala sa kapaligiran ng bahurang korales.”',
    'verdict_card3_more' => '+ Basahin ang hatol',
    'verdict_extra1' => 'Ang Linya ng Siyam na Guhit na iginuhit ng Tsina ay <strong>hindi tumutugma</strong> sa UNCLOS 1982.',
    'verdict_extra2' => 'Nagdulot ang Tsina ng pinsala sa ekosistema ng Spratly sa pamamagitan ng labis na pagkuha at pagtatayo ng mga artipisyal na isla.',
    'verdict_extra3' => 'Ang mga aksyon ng Tsina ay nagpapataas ng panganib ng tunggalian sa Pilipinas.',
    'verdict_extra4' => 'Ang Ba Bình (na kontrolado ng Taiwan) ay hindi rin makalilikha ng EEZ.',
    'verdict_subtitle' => 'Bakit ito sumasalungat sa UNCLOS?',
    'verdict_subtitle_body' => 'Malinaw na tinutukoy ng UNCLOS 1982 ang mga sona ng dagat batay sa baseline ng baybaying estado. Ang paghahabol ng Linya ng Siyam na Guhit ay lumalampas sa balangkas na ito kaya hindi ito maipapatong nang katabi.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoryal na dagat (nautical miles)',
    'verdict_zone1_body' => 'Sonang-dagat ng estado na may soberanya, sinusukat mula sa baseline.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusibong sonang ekonomiko',
    'verdict_zone2_body' => 'EEZ — may karapatang soberano ang baybaying estado sa mga yamang nasa loob ng saklaw na ito.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinental na istante (pinakamarami, nautical miles)',
    'verdict_zone3_body' => 'Mga karapatan sa yamang nasa ilalim ng dagat, alinsunod sa itinakdang kondisyong heolohikal.',
    'verdict_foot' => 'Sa balangkas na ito, ang “makasaysayang karapatan” na sumasaklaw sa buong bukas na dagat — gaya ng ipinahihiwatig ng Linya ng Siyam na Guhit — <em>ay napalitan na</em> ng legal na rehimen ng UNCLOS na kinabibilangan din ng Tsina.',
];
