<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Pandaigdigang pasya',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tatlong "Hindi"',
    'verdict_lead' => 'Noong 12/7/2016, ang Permanent Court of Arbitration (PCA) sa The Hague — na itinatag sa ilalim ng Annex VII ng UNCLOS, sa kasong inihain ng Pilipinas laban sa Tsina — ay naglabas ng pasyang tumanggi sa pag-aangkin ng Linya ng Siyam na Guhit. <em>I-click ang bawat kard upang basahin ang buong teksto.</em>',
    'verdict_card1_khong' => 'HINDI',
    'verdict_card1_title' => 'historikal na karapatan',
    'verdict_card1_short' => 'Walang batayang legal para igiit ng Tsina ang mga historikal na karapatan sa mga yaman sa dagat na nasa loob ng Linya ng Siyam na Guhit.',
    'verdict_card1_quote' => '“Walang batayang legal para sa pag-aangkin ng Tsina ng mga historikal na karapatan sa mga yamang nasa mga karagatang nasa loob ng Linya ng Siyam na Guhit.”',
    'verdict_card1_more' => '+ Basahin ang pasya',
    'verdict_card2_khong' => 'HINDI',
    'verdict_card2_title' => 'bagay na lumilikha ng EEZ',
    'verdict_card2_short' => 'Walang anumang pormasyon sa Kapuluang Spratly ang kwalipikadong lumikha ng eksklusibong sonang ekonomiko para sa Tsina — kabilang ang Ba Bình.',
    'verdict_card2_quote' => '“Walang isang pormasyon sa Kapuluang Spratly na may kakayahang lumikha ng eksklusibong sonang ekonomiko.”',
    'verdict_card2_more' => '+ Basahin ang pasya',
    'verdict_card3_khong' => 'HINDI',
    'verdict_card3_title' => 'ligal na kilos',
    'verdict_card3_short' => 'Nilabag ng Tsina ang mga karapatang soberano ng Biyetnam, hinarang ang pangingisda, at sinira ang kapaligirang-dagat.',
    'verdict_card3_quote' => '“Nilabag ng Tsina ang mga karapatang soberano ng Pilipinas, nakialam sa mga gawain ng pangingisda sa Scarborough Shoal, at malubhang nakasira sa kapaligiran ng bahura.”',
    'verdict_card3_more' => '+ Basahin ang pasya',
    'verdict_extra1' => 'Ang Linya ng Siyam na Guhit na iginuhit mismo ng Tsina ay <strong>hindi tugma</strong> sa UNCLOS 1982.',
    'verdict_extra2' => 'Nagdulot ang Tsina ng pinsala sa ekosistemang-dagat ng Kapuluang Spratly sa pamamagitan ng labis na pagkuha at pagtatayo ng artipisyal na mga pulo.',
    'verdict_extra3' => 'Pinapataas ng mga kilos ng Tsina ang panganib ng sigalot sa Biyetnam.',
    'verdict_extra4' => 'Hindi rin makalilikha ng EEZ ang Ba Bình Island (na kontrolado ng Taiwan).',
    'verdict_subtitle' => 'Bakit ito sumasalungat sa UNCLOS?',
    'verdict_subtitle_body' => 'Malinaw na itinatakda ng UNCLOS 1982 ang mga sona ng dagat batay sa mga batayang guhit ng isang baybaying estado. Lumalampas sa balangkas na ito ang pag-aangkin ng Linya ng Siyam na Guhit kaya hindi ito maipapantay.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoryal na dagat (milya-dagat)',
    'verdict_zone1_body' => 'Soberanong katubigan ng estado, mula sa batayang guhit.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusibong sonang ekonomiko',
    'verdict_zone2_body' => 'EEZ — may karapatang soberano ang baybaying estado sa mga yaman sa loob ng saklaw na ito.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinental na kalupaan (pinakamataas, milya-dagat)',
    'verdict_zone3_body' => 'Mga karapatan sa mga yamang nasa ilalim ng dagat, batay sa natukoy na mga kondisyong heolohikal.',
    'verdict_foot' => 'Sa loob ng balangkas na ito, ang "historikal na karapatan" na sumasaklaw sa isang malawak na karagatang bahagi — gaya ng ipinahihiwatig ng Linya ng Siyam na Guhit — <em>ay napalitan na</em> ng kaayusang legal ng UNCLOS kung saan kasapi rin ang Tsina.',
];
