<?php

return [
    'witnesses_index' => 'Mga Sinaunang Mapa',
    'witnesses_label' => 'Mga Sinaunang Mapa ng Tsina',
    'witnesses_title' => 'Ang pinakatimog na hangganan ay umaabot lamang sa',
    'witnesses_title_accent' => 'Pulo ng Hainan',
    'witnesses_lead' => 'Ang mga sinaunang mapang iginuhit ng mga may-akdang Tsino — inayos ayon sa panahon — ay pawang nagpapakita na ang <em>Pulo ng Hainan ang pinakatimog na hangganan</em> ng Tsina, at walang Kapuluang Paracel o Kapuluang Spratly. Ang mga sanggunian ay pinagsama mula sa akdang <em>Pambansang Soberanya ng Biyetnam sa Kapuluang Paracel at Kapuluang Spratly</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Gamitin ang magnifying glass',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— pinakatimog na bahagi ng teritoryo —',
    'witnesses_map1_svg_era' => 'Dinastiyang Song · 1136',
    'witnesses_map1_title' => 'Mapa ng Dinastiyang Song, 1136',
    'witnesses_map1_body' => 'Ang teritoryo ng Tsina ay nagtatapos sa pulo ng Hainan — ang Kapuluang Paracel at ang Kapuluang Spratly ay nasa labas ng saklaw ng teritoryo.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'hangganan ng d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Mapa ni d\'Anville, 1735',
    'witnesses_map2_body' => 'Ginuhit ni J.-B. B. d\'Anville; ang kopyang ginawa noong 1740 ay minsang ibinigay ng Punong Ministro ng Alemanya sa isang pinuno ng Tsina. Ang teritoryo ng Dinastiyang Qing ay nagtatapos sa Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"pinakatimog ng Tsina"',
    'witnesses_map3_svg_era' => 'Imperyal na atlas ng mga lalawigan · 1904',
    'witnesses_map3_title' => 'Kumpletong atlas ng mga lalawigan ng imperyal na hukuman',
    'witnesses_map3_body' => 'Inilimbag ng Dinastiyang Qing — malinaw na itinatala na ang pinakatimog na bahagi ng teritoryo ng Tsina ay ang pulo ng Hainan.',
    'witnesses_quote' => 'Maging ang mga mapang inilathala mismo ng Tsina noon ay hindi isinama ang Kapuluang Paracel at Kapuluang Spratly sa kanilang teritoryo.',
    'witnesses_timeline_aria' => 'Timeline ng mga sinaunang mapa ng Tsina',
    'witnesses_year_aria' => 'Panahon',
    'lightbox_aria' => 'Tingnan ang pinalaking larawan',
    'lightbox_close' => 'Isara',
    'lightbox_prev' => 'Nakaraang larawan',
    'lightbox_next' => 'Susunod na larawan',
];
