<?php

return [
    'footer_index' => 'ग्रंथालय',
    'footer_crest_eyebrow' => 'ग्रंथालय सत्याचा शेवट',
    'footer_crest_quote' => '“दक्षिण चीन समुद्रातील शांतता <b>आंतरराष्ट्रीय कायद्याच्या</b> पायावर उभी आहे.”',
    'footer_crest_sub' => 'द्वेष नाही · फक्त सत्य',
    'footer_nav_aria' => 'पृष्ठाच्या शेवटचे कृती पर्याय',
    'footer_btn_top' => 'वरच्या भागात परत',
    'footer_btn_verdict' => 'PCA 2016 निर्णय',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'नाइन-डॅश रेषेवरील दावा',
    'footer_brand_eyebrow' => 'विशेष विषय · व्हिएतनामचे सार्वभौमत्व',
    'footer_brand_body' => 'नाइन-डॅश रेषेबद्दल वस्तुनिष्ठ सत्य, आंतरराष्ट्रीय कायदा, PCA 2016 निर्णय आणि ऐतिहासिक दस्तऐवजांच्या आधारे स्पष्टीकरण — <strong>"पॅरासेल द्वीपसमूह आणि स्प्रॅटली द्वीपसमूह"</strong> या दोन द्वीपसमूहांच्या सार्वभौमत्वावरील सखोल पानांना पूरक. चीनच्या अवाजवी दाव्यांचे इतिहास आणि पुराव्यांच्या आधारे खंडन.',
    'footer_refs_title' => 'संदर्भ स्रोत',
    'footer_ref1' => 'PCA निर्णय, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — पूर्ण मजकूर',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ऐतिहासिक दस्तऐवज व जुनी नकाशे',
    'footer_toc_title' => 'पान अनुक्रमणिका',
    'footer_toc1' => 'नाइन-डॅश रेषा म्हणजे काय',
    'footer_toc2' => 'उगम',
    'footer_toc3' => 'हे वादग्रस्त का आहे',
    'footer_toc4' => 'आंतरराष्ट्रीय स्तरावर विरोध का होतो',
    'footer_toc5' => 'मौन साक्षीदार',
    'footer_toc6' => 'PCA 2016 निर्णय',
    'footer_toc7' => 'पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह',
    'footer_copy_eyebrow' => 'नफा नसलेला प्रकल्प',
    'footer_copy_title' => 'पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह व्हिएतनामचे आहेत',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — व्हिएतनामच्या सार्वभौमत्व परिसंस्थेतील नाइन-डॅश रेषेवरील विशेष विषयाचे पान.',
    'footer_copy_body' => 'नाइन-डॅश रेषेच्या दाव्याचे स्पष्टीकरण <strong>वस्तुनिष्ठ सत्य</strong>, <strong>आंतरराष्ट्रीय कायदा</strong>, PCA 2016 निर्णय आणि ऐतिहासिक दस्तऐवजांच्या आधारे — पॅरासेल द्वीपसमूह आणि स्प्रॅटली द्वीपसमूह यांच्या सार्वभौमत्वावरील सखोल पानांना पूरक.',
    'footer_copy_ecosystem_aria' => 'त्याच प्रकल्पातील इतर पाने',
    'footer_copy_ecosystem_label' => 'समान परिसंस्था',
    'footer_copy_disclaimer' => 'ही सामग्री शिक्षण आणि जनजागृतीसाठी आहे; ती व्हिएतनाम सरकारच्या अधिकृत भूमिकेचा पर्याय नाही.',
    'footer_copy' => '<strong>© :year नाइन-डॅश रेषा</strong> — <strong>पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह व्हिएतनामचे आहेत</strong> या नफा नसलेल्या प्रकल्पाचा एक भाग, प्रणालीमध्ये समाविष्ट: <a href="https://paracelislands.net/mr" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/mr" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/mr" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/mr" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/mr" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'पृष्ठ सामग्रीची हमी',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 निर्णय',
    'footer_chip3' => 'ऐतिहासिक पुरावे',
    'footer_chip4' => 'जुने नकाशे',
    'footer_chip5' => 'वस्तुनिष्ठ सत्य',
    'footer_chip6' => 'दक्षिण चीन समुद्रातील शांतता',
];
