<?php

return [
    'footer_index' => 'ग्रंथालय',
    'footer_crest_eyebrow' => 'सत्याच्या ग्रंथालयाचा समारोप',
    'footer_crest_quote' => '“दक्षिण चीन समुद्रातील शांतता <b>आंतरराष्ट्रीय कायदा</b> या पायावर उभी आहे.”',
    'footer_crest_sub' => 'द्वेष नाही · फक्त सत्य',
    'footer_nav_aria' => 'तळटीप कृती',
    'footer_btn_top' => 'पृष्ठाच्या वर जा',
    'footer_btn_verdict' => 'PCA 2016 निर्णय',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'नाइन-डॅश रेषा',
    'footer_brand_body' => 'वस्तुनिष्ठ सत्य, आंतरराष्ट्रीय कायदा आणि ऐतिहासिक दस्तऐवजांवर आधारित एक स्पष्टीकरणात्मक पृष्ठ — घोषणांऐवजी पुराव्यांनी नाइन-डॅश रेषेचा दावा खोडून काढते.',
    'footer_refs_title' => 'संदर्भ',
    'footer_ref1' => 'PCA निर्णय, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — संपूर्ण मजकूर',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ऐतिहासिक साहित्य व प्राचीन नकाशे',
    'footer_toc_title' => 'पानाची अनुक्रमणिका',
    'footer_toc1' => 'नाइन-डॅश रेषा म्हणजे काय',
    'footer_toc2' => 'उत्पत्ती',
    'footer_toc3' => 'ती वादग्रस्त का आहे',
    'footer_toc4' => 'आंतरराष्ट्रीय विरोध का आहे',
    'footer_toc5' => 'मूक साक्षीदार',
    'footer_toc6' => 'PCA 2016 निर्णय',
    'footer_toc7' => 'पॅरासेल द्वीपसमूह - स्प्रॅटली द्वीपसमूह',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — दक्षिण चीन समुद्रावरील वस्तुनिष्ठ सत्य.<br>परिसंस्था: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'कोणतेही समन्वय नाही',
];
