<?php

return [
    'footer_index' => 'ग्रंथालय',
    'footer_crest_eyebrow' => 'सत्याच्या ग्रंथालयाचा शेवट',
    'footer_crest_quote' => '“दक्षिण चीन समुद्रातील शांतता <b>आंतरराष्ट्रीय कायद्याच्या</b> पायावर उभी आहे.”',
    'footer_crest_sub' => 'द्वेष नाही · फक्त सत्य',
    'footer_nav_aria' => 'तळटीप कृती',
    'footer_btn_top' => 'पृष्ठाच्या वर',
    'footer_btn_verdict' => 'PCA 2016 चा निर्णय',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'नाइन-डॅश रेषेवरील दावा',
    'footer_brand_eyebrow' => 'विशेष विषय · व्हिएतनामचे सार्वभौमत्व',
    'footer_brand_body' => 'नाइन-डॅश रेषेचे स्पष्टीकरण वस्तुनिष्ठ सत्य, आंतरराष्ट्रीय कायदा, PCA 2016 चा निर्णय आणि ऐतिहासिक साधनांच्या आधारे — <strong>"पॅरासेल द्वीपसमूह आणि स्प्रॅटली द्वीपसमूह"</strong>वरील सार्वभौमत्वावरील सखोल पानांना पूरक. चीनच्या अवाजवी दाव्यांचे इतिहास आणि पुराव्यांद्वारे खंडन.',
    'footer_refs_title' => 'संदर्भ स्रोत',
    'footer_ref1' => 'PCA चा निर्णय, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — पूर्ण मजकूर',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ऐतिहासिक साधने आणि प्राचीन नकाशे',
    'footer_toc_title' => 'पृष्ठ अनुक्रमणिका',
    'footer_toc1' => 'नाइन-डॅश रेषा म्हणजे काय',
    'footer_toc2' => 'उगम',
    'footer_toc3' => 'ती वादग्रस्त का आहे',
    'footer_toc4' => 'आंतरराष्ट्रीय विरोध का आहे',
    'footer_toc5' => 'मूक साक्षीदार',
    'footer_toc6' => 'PCA 2016 चा निर्णय',
    'footer_toc7' => 'पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह',
    'footer_copy_eyebrow' => 'ना-नफा प्रकल्प',
    'footer_copy_title' => 'पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह व्हिएतनामचे आहे',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — व्हिएतनामच्या सार्वभौमत्व परिसंस्थेत नाइन-डॅश रेषेवरील विशेष पृष्ठ.',
    'footer_copy_body' => 'नाइन-डॅश रेषेवरील दावे <strong>वस्तुनिष्ठ सत्य</strong>, <strong>आंतरराष्ट्रीय कायदा</strong>, PCA 2016 चा निर्णय आणि ऐतिहासिक साधनांच्या आधारे स्पष्ट केले आहेत — पॅरासेल द्वीपसमूह आणि स्प्रॅटली द्वीपसमूहावरील सार्वभौमत्वाच्या सखोल पानांना पूरक.',
    'footer_copy_ecosystem_aria' => 'एकाच प्रकल्पातील पृष्ठे',
    'footer_copy_ecosystem_label' => 'त्याच परिसंस्थेत',
    'footer_copy_disclaimer' => 'ही सामग्री शिक्षण आणि जनजागृतीसाठी आहे; व्हिएतनाम सरकारच्या अधिकृत भूमिकेची जागा घेत नाही.',
    'footer_copy' => '<strong>© :year नाइन-डॅश रेषा</strong> — हा ना-नफा प्रकल्प <strong>पॅरासेल द्वीपसमूह – स्प्रॅटली द्वीपसमूह व्हिएतनामचे आहे</strong> याचा एक भाग आहे, प्रणालीमध्ये: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'पृष्ठ सामग्रीची हमी',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 चा निर्णय',
    'footer_chip3' => 'ऐतिहासिक पुरावे',
    'footer_chip4' => 'प्राचीन नकाशे',
    'footer_chip5' => 'वस्तुनिष्ठ सत्य',
    'footer_chip6' => 'दक्षिण चीन समुद्रातील शांतता',
];
