<?php

return [
    'nav_logo_name' => 'नाइन-डॅश रेषा',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'नाइन-डॅश रेषा',
    'nav_rail_aria' => 'विभागानुसार नेव्हिगेशन',
    'nav_rail_what' => 'व्याख्या',
    'nav_rail_origin' => 'उत्पत्ती',
    'nav_rail_dispute' => 'वाद',
    'nav_rail_opposition' => 'विरोध',
    'nav_rail_witnesses' => 'प्राचीन नकाशे',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'पॅरासेल द्वीपसमूह - स्प्रॅटली द्वीपसमूह',
    'nav_sound_off' => 'पार्श्वसंगीत सुरू करा',
    'nav_sound_on' => 'पार्श्वसंगीत बंद करा',
    'nav_share' => 'सामायिक करा',
    'dialog_title' => 'प्रदर्शन भाषा',
    'language' => 'भाषा',
    'display_hint' => ':count भाषा',
    'search_placeholder' => 'भाषा शोधा…',
    'cancel' => 'रद्द करा',
    'apply' => 'लागू करा',
    'sound_off' => 'पार्श्वध्वनी सुरू करा',
    'sound_on' => 'पार्श्वध्वनी बंद करा',
    'lang_trigger' => 'भाषा निवडा',
    'close' => 'बंद करा',
    'no_results' => 'भाषा आढळली नाही',
    'contribute' => 'सामायिक करा',
];
