<?php

return [
    'footer_index' => 'ലൈബ്രറി',
    'footer_crest_eyebrow' => 'സത്യത്തിന്റെ ലൈബ്രറിയിലെ സമാപനം',
    'footer_crest_quote' => '“ദക്ഷിണ ചൈനാ കടലിലെ സമാധാനം <b>അന്താരാഷ്ട്ര നിയമത്തിന്റെ</b> അടിത്തറയിൽ പടുത്തുയർത്തപ്പെടുന്നു.”',
    'footer_crest_sub' => 'വെറുപ്പ് ഇല്ല · സത്യമാണ് മാത്രം',
    'footer_nav_aria' => 'പേജിന്റെ അടിഭാഗ പ്രവർത്തനങ്ങൾ',
    'footer_btn_top' => 'മുകളിൽ പോകുക',
    'footer_btn_verdict' => '2016 ലെ PCA വിധി',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ഒൻപത്-ഡാഷ് രേഖയുടെ അവകാശവാദം',
    'footer_brand_eyebrow' => 'വിഷയാധിഷ്ഠിത പേജ് · വിയറ്റ്നാമിന്റെ സ്വാധീനം',
    'footer_brand_body' => 'നിഷ്പക്ഷ സത്യം, അന്താരാഷ്ട്ര നിയമം, 2016 ലെ PCA വിധി, ചരിത്ര രേഖകൾ എന്നിവയുടെ അടിസ്ഥാനത്തിൽ ഒൻപത്-ഡാഷ് രേഖയെ വിശദീകരിക്കുന്നു — രണ്ട് ദ്വീപുസമൂഹങ്ങളുടെ സ്വാധീനത്തെക്കുറിച്ചുള്ള പ്രത്യേക പേജുകൾക്ക് പൂരകമായി <strong>"Hoàng Sa ഒപ്പം Trường Sa"</strong>. ചൈനയുടെ യുക്തിരഹിതമായ അവകാശവാദങ്ങളെ ചരിത്രവും തെളിവുകളും ഉപയോഗിച്ച് നിഷേധിക്കുന്നു.',
    'footer_refs_title' => 'റഫറൻസ് ഉറവിടങ്ങൾ',
    'footer_ref1' => 'PCA വിധി, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — പൂർണ്ണപാഠം',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ചരിത്ര രേഖകളും പുരാതന ഭൂപടങ്ങളും',
    'footer_toc_title' => 'പേജ് ഉള്ളടക്ക പട്ടിക',
    'footer_toc1' => 'ഒൻപത്-ഡാഷ് രേഖ എന്താണ്',
    'footer_toc2' => 'ഉത്ഭവം',
    'footer_toc3' => 'എന്തുകൊണ്ട് ഇത് വിവാദമാകുന്നു',
    'footer_toc4' => 'എന്തുകൊണ്ട് അന്താരാഷ്ട്ര സമൂഹം എതിർക്കുന്നു',
    'footer_toc5' => 'നിശ്ശബ്ദ സാക്ഷികൾ',
    'footer_toc6' => '2016 ലെ PCA വിധി',
    'footer_toc7' => 'Hoàng Sa – Trường Sa',
    'footer_copy_eyebrow' => 'ലാഭരഹിത പദ്ധതി',
    'footer_copy_title' => 'Hoàng Sa – Trường Sa വിയറ്റ്നാമിന്റേതാണ്',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — വിയറ്റ്നാമിന്റെ സ്വാധീന പരിസ്ഥിതിക്കുള്ളിലെ ഒൻപത്-ഡാഷ് രേഖയെക്കുറിച്ചുള്ള വിഷയാധിഷ്ഠിത പേജ്.',
    'footer_copy_body' => 'നിഷ്പക്ഷ സത്യം, <strong>അന്താരാഷ്ട്ര നിയമം</strong>, 2016 ലെ PCA വിധി, ചരിത്ര രേഖകൾ എന്നിവയുടെ അടിസ്ഥാനത്തിൽ ഒൻപത്-ഡാഷ് രേഖയുടെ അവകാശവാദം വിശദീകരിക്കുന്നു — Hoàng Sa, Trường Sa എന്നീ രണ്ട് ദ്വീപുസമൂഹങ്ങളുടെ സ്വാധീനത്തെക്കുറിച്ചുള്ള വിശദമായ പേജുകൾക്ക് പൂരകമായി.',
    'footer_copy_ecosystem_aria' => 'അതേ പദ്ധതിയിലെ പേജുകൾ',
    'footer_copy_ecosystem_label' => 'ഒരേ ഇക്കോസിസ്റ്റം',
    'footer_copy_disclaimer' => 'ഉള്ളടക്കം വിദ്യാഭ്യാസത്തിനും ബോധവൽക്കരണത്തിനുമാണ്; വിയറ്റ്നാം സർക്കാരിന്റെ ഔദ്യോഗിക നിലപാടിന് പകരമാകുന്നതല്ല.',
    'footer_copy' => '<strong>© :year ഒൻപത്-ഡാഷ് രേഖ</strong> — ലാഭരഹിത പദ്ധതിയായ <strong>Hoàng Sa – Trường Sa വിയറ്റ്നാമിന്റേതാണ്</strong> എന്നതിന്റെ ഒരു ഭാഗം, ഈ സിസ്റ്റത്തിൽ: <a href="https://paracelislands.net/ml" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ml" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ml" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ml" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ml" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'പേജ് ഉള്ളടക്ക പ്രതിബദ്ധത',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 ലെ PCA വിധി',
    'footer_chip3' => 'ചരിത്ര തെളിവുകൾ',
    'footer_chip4' => 'പുരാതന ഭൂപടങ്ങൾ',
    'footer_chip5' => 'നിഷ്പക്ഷ സത്യം',
    'footer_chip6' => 'ദക്ഷിണ ചൈനാ കടലിലെ സമാധാനം',
];
