<?php

return [
    'footer_index' => 'ലൈബ്രറി',
    'footer_crest_eyebrow' => 'സത്യത്തിന്റെ ലൈബ്രറി സമാപനം',
    'footer_crest_quote' => '“ദക്ഷിണ ചൈനാ കടലിലെ സമാധാനം <b>അന്താരാഷ്ട്ര നിയമം</b> എന്ന അടിസ്ഥാനത്തിലാണ് പടുത്തുയർത്തപ്പെടുന്നത്.”',
    'footer_crest_sub' => 'ദ്വേഷമില്ല · സത്യം മാത്രം',
    'footer_nav_aria' => 'ഫൂട്ടർ പ്രവർത്തനങ്ങൾ',
    'footer_btn_top' => 'മുകളിലേക്ക്',
    'footer_btn_verdict' => '2016 PCA വിധി',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ഒൻപത്-ഡാഷ് രേഖ',
    'footer_brand_body' => 'വസ്തുനിഷ്ഠമായ സത്യം, അന്താരാഷ്ട്ര നിയമം, ചരിത്ര രേഖകൾ എന്നിവയുടെ അടിസ്ഥാനത്തിലുള്ള ഒരു വിശദീകരണ പേജ് — മുദ്രാവാക്യങ്ങളിലൂടെ അല്ല, തെളിവുകളിലൂടെ ഒൻപത്-ഡാഷ് രേഖ സംബന്ധിച്ച അവകാശവാദങ്ങളെ നിഷേധിക്കുന്നു.',
    'footer_refs_title' => 'അവലംബങ്ങൾ',
    'footer_ref1' => 'PCA വിധി, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — പൂർണ്ണ പാഠം',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ചരിത്ര രേഖകളും പുരാതന ഭൂപടങ്ങളും',
    'footer_toc_title' => 'പേജ് ഉള്ളടക്ക പട്ടിക',
    'footer_toc1' => 'ഒൻപത്-ഡാഷ് രേഖ എന്താണ്',
    'footer_toc2' => 'ഉത്ഭവം',
    'footer_toc3' => 'എന്തുകൊണ്ട് വിവാദമാകുന്നു',
    'footer_toc4' => 'എന്തുകൊണ്ട് അന്താരാഷ്ട്ര സമൂഹം എതിർക്കുന്നു',
    'footer_toc5' => 'നിശബ്ദ സാക്ഷികൾ',
    'footer_toc6' => '2016 PCA വിധി',
    'footer_toc7' => 'പരാസെൽ ദ്വീപുകൾ – സ്പ്രാറ്റ്ലി ദ്വീപുകൾ',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — ദക്ഷിണ ചൈനാ കടലിനെക്കുറിച്ചുള്ള വസ്തുനിഷ്ഠ സത്യം.<br>പരിസ്ഥിതി: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'കോഓർഡിനേറ്റുകളില്ല',
];
