<?php

return [
    'footer_index' => 'ലൈബ്രറി',
    'footer_crest_eyebrow' => 'ലൈബ്രറി സത്യത്തിന്റെ സമാപനം',
    'footer_crest_quote' => '“ദക്ഷിണ ചൈനാ കടലിലെ സമാധാനം <b>അന്താരാഷ്ട്ര നിയമത്തിന്റെ</b> അടിസ്ഥാനത്തിലാണ് നിലനിൽക്കുന്നത്.”',
    'footer_crest_sub' => 'വൈരം ഇല്ല · സത്യം മാത്രം',
    'footer_nav_aria' => 'പേജ് അവസാനം പ്രവർത്തനങ്ങൾ',
    'footer_btn_top' => 'മുകളിലേക്ക് മടങ്ങുക',
    'footer_btn_verdict' => '2016ലെ PCA വിധി',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'ഒൻപത്-ഡാഷ് രേഖയുടെ അവകാശവാദം',
    'footer_brand_eyebrow' => 'വിശേഷ വിഷയം · വിയറ്റ്നാമിന്റെ പരമാധികാരം',
    'footer_brand_body' => 'ഒൻപത്-ഡാഷ് രേഖയെ വസ്തുനിഷ്ഠമായ സത്യങ്ങൾ, അന്താരാഷ്ട്ര നിയമം, 2016ലെ PCA വിധി, ചരിത്ര രേഖകൾ എന്നിവയുടെ അടിസ്ഥാനത്തിൽ വിശദീകരിക്കുന്നു — <strong>"പരാസെൽ ദ്വീപുകൾയും സ്പ്രാറ്റ്ലി ദ്വീപുകളും"</strong> എന്ന രണ്ടു ദ്വീപസമൂഹങ്ങളുടെ പരമാധികാരം സംബന്ധിച്ച ആഴത്തിലുള്ള പേജുകളെ പൂരിപ്പിക്കുന്നവിധത്തിൽ. ചൈനയുടെ യുക്തിരഹിത അവകാശവാദങ്ങളെ ചരിത്രത്തിലും തെളിവുകളിലും അടിസ്ഥാനപ്പെടുത്തി നിഷേധിക്കുന്നു.',
    'footer_refs_title' => 'റഫറൻസ് സ്രോതസുകൾ',
    'footer_ref1' => 'PCA വിധി, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — പൂർണ്ണ പാഠം',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ചരിത്ര രേഖകളും പുരാതന ഭൂപടങ്ങളും',
    'footer_toc_title' => 'പേജിലെ ഉള്ളടക്കക്രമം',
    'footer_toc1' => 'ഒൻപത്-ഡാഷ് രേഖ എന്താണ്',
    'footer_toc2' => 'ഉത്ഭവം',
    'footer_toc3' => 'എന്തുകൊണ്ട് വിവാദമാകുന്നു',
    'footer_toc4' => 'എന്തുകൊണ്ട് അന്താരാഷ്ട്ര സമൂഹം എതിർക്കുന്നു',
    'footer_toc5' => 'മൗന സാക്ഷികൾ',
    'footer_toc6' => '2016ലെ PCA വിധി',
    'footer_toc7' => 'പരാസെൽ ദ്വീപുകൾ – സ്പ്രാറ്റ്ലി ദ്വീപുകൾ',
    'footer_copy_eyebrow' => 'ലാഭരഹിത പദ്ധതി',
    'footer_copy_title' => 'പരാസെൽ ദ്വീപുകൾ – സ്പ്രാറ്റ്ലി ദ്വീപുകൾ വിയറ്റ്നാമിന്റേതാണ്',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — വിയറ്റ്നാമിന്റെ പരമാധികാര പരിസ്ഥിതിയിലെ ഒൻപത്-ഡാഷ് രേഖയെക്കുറിച്ചുള്ള പ്രത്യേക പേജ്.',
    'footer_copy_body' => 'ഒൻപത്-ഡാഷ് രേഖയുടെ അവകാശവാദത്തെ <strong>വസ്തുനിഷ്ഠമായ സത്യങ്ങൾ</strong>, <strong>അന്താരാഷ്ട്ര നിയമം</strong>, 2016ലെ PCA വിധി, ചരിത്ര രേഖകൾ എന്നിവയുടെ അടിസ്ഥാനത്തിൽ വിശദീകരിക്കുന്നു — പരാസെൽ ദ്വീപുകളും സ്പ്രാറ്റ്ലി ദ്വീപുകളും എന്ന രണ്ടു ദ്വീപസമൂഹങ്ങളുടെ പരമാധികാരം സംബന്ധിച്ച ആഴത്തിലുള്ള പേജുകളെ പൂരിപ്പിക്കുന്നു.',
    'footer_copy_ecosystem_aria' => 'അതേ പദ്ധതിയിലെ പേജുകൾ',
    'footer_copy_ecosystem_label' => 'ഒരേ പരിസ്ഥിതി',
    'footer_copy_disclaimer' => 'ഈ ഉള്ളടക്കം വിദ്യാഭ്യാസത്തിനും അവബോധ വർധനയ്ക്കുമായി മാത്രമാണ്; വിയറ്റ്നാം സർക്കാരിന്റെ ഔദ്യോഗിക നിലപാടിന് പകരമാകുന്നതല്ല.',
    'footer_copy' => '<strong>© :year ഒൻപത്-ഡാഷ് രേഖ</strong> — <strong>പരാസെൽ ദ്വീപുകൾ – സ്പ്രാറ്റ്ലി ദ്വീപുകൾ വിയറ്റ്നാമിന്റേതാണ്</strong> എന്ന ലാഭരഹിത പദ്ധതിയുടെ ഭാഗം; ഈ സംവിധാനത്തിൽ: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'പേജിന്റെ ഉള്ളടക്ക പ്രതിബദ്ധത',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016ലെ PCA വിധി',
    'footer_chip3' => 'ചരിത്ര തെളിവുകൾ',
    'footer_chip4' => 'പുരാതന ഭൂപടങ്ങൾ',
    'footer_chip5' => 'വസ്തുനിഷ്ഠ സത്യം',
    'footer_chip6' => 'ദക്ഷിണ ചൈനാ കടലിലെ സമാധാനം',
];
