<?php

return [
    'nav_logo_name' => 'ഒൻപത്-ഡാഷ് രേഖ',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'ഒൻപത്-ഡാഷ് രേഖ',
    'nav_rail_aria' => 'വിഭാഗങ്ങൾ പ്രകാരമുള്ള നാവിഗേഷൻ',
    'nav_rail_what' => 'നിർവചനം',
    'nav_rail_origin' => 'ഉത്ഭവം',
    'nav_rail_dispute' => 'വിവാദം',
    'nav_rail_opposition' => 'എതിർപ്പ്',
    'nav_rail_witnesses' => 'പുരാതന ഭൂപടങ്ങൾ',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'പരാസെൽ ദ്വീപുകൾ - സ്പ്രാറ്റ്ലി ദ്വീപുകൾ',
    'nav_sound_off' => 'പശ്ചാത്തല സംഗീതം ഓൺ ചെയ്യുക',
    'nav_sound_on' => 'പശ്ചാത്തല സംഗീതം ഓഫ് ചെയ്യുക',
    'nav_share' => 'പങ്കിടുക',
    'dialog_title' => 'പ്രദർശന ഭാഷ',
    'language' => 'ഭാഷ',
    'display_hint' => ':count ഭാഷകൾ',
    'search_placeholder' => 'ഭാഷ തിരയുക…',
    'cancel' => 'റദ്ദാക്കുക',
    'apply' => 'പ്രയോഗിക്കുക',
    'sound_off' => 'പശ്ചാത്തല ശബ്ദം ഓൺ ചെയ്യുക',
    'sound_on' => 'പശ്ചാത്തല ശബ്ദം ഓഫ് ചെയ്യുക',
    'lang_trigger' => 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'close' => 'അടയ്ക്കുക',
    'no_results' => 'ഭാഷ കണ്ടെത്തിയില്ല',
    'contribute' => 'പങ്കിടുക',
];
