<?php

return [
    'footer_index' => 'Knižnica',
    'footer_crest_eyebrow' => 'Záver knižnice pravdy',
    'footer_crest_quote' => '„Mier v Juhočínskom mori stojí na základoch <b>medzinárodného práva</b>.“',
    'footer_crest_sub' => 'Žiadna nenávisť · Iba pravda',
    'footer_nav_aria' => 'Akcie v pätičke',
    'footer_btn_top' => 'Na začiatok stránky',
    'footer_btn_verdict' => 'Rozsudok PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Čiara deviatich čiarok',
    'footer_brand_body' => 'Stránka vysvetľujúca na základe objektívnej pravdy, medzinárodného práva a historických dokumentov — vyvracia nároky Čiara deviatich čiarok dôkazmi, nie heslami.',
    'footer_refs_title' => 'Referenčné zdroje',
    'footer_ref1' => 'Rozsudok PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — úplné znenie',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historické materiály a staré mapy',
    'footer_toc_title' => 'Obsah stránky',
    'footer_toc1' => 'Čo je Čiara deviatich čiarok',
    'footer_toc2' => 'Pôvod',
    'footer_toc3' => 'Prečo je to sporné',
    'footer_toc4' => 'Prečo to medzinárodné spoločenstvo odmieta',
    'footer_toc5' => 'Tichí svedkovia',
    'footer_toc6' => 'Rozsudok PCA 2016',
    'footer_toc7' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektívna pravda o Juhočínskom mori.<br>Ekosystém: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Bez súradníc',
];
