<?php

return [
    'footer_index' => 'Knižnica',
    'footer_crest_eyebrow' => 'Záver knižnice pravdy',
    'footer_crest_quote' => '„Mier v Juhočínskom mori sa buduje na základe <b>medzinárodného práva</b>.“',
    'footer_crest_sub' => 'Bez nenávisti · Len pravda',
    'footer_nav_aria' => 'Akcie v pätičke',
    'footer_btn_top' => 'Späť na začiatok',
    'footer_btn_verdict' => 'Rozhodnutie PCA z roku 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Nárok na Čiara deviatich čiarok',
    'footer_brand_eyebrow' => 'Tematická stránka · Suverenita Vietnamu',
    'footer_brand_body' => 'Vysvetlenie Čiary deviatich čiarok prostredníctvom objektívnych faktov, medzinárodného práva, rozhodnutia PCA z roku 2016 a historických materiálov — doplnok k podrobným stránkam o suverenite dvoch súostroví <strong>"Paracelské ostrovy a Spratlyho ostrovy"</strong>. Vyvracia neopodstatnené nároky Číny pomocou dejín a dôkazov.',
    'footer_refs_title' => 'Referenčné zdroje',
    'footer_ref1' => 'Rozhodnutie PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — úplné znenie',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historické materiály a staré mapy',
    'footer_toc_title' => 'Obsah stránky',
    'footer_toc1' => 'Čo je Čiara deviatich čiarok',
    'footer_toc2' => 'Pôvod',
    'footer_toc3' => 'Prečo je sporná',
    'footer_toc4' => 'Prečo ju medzinárodné spoločenstvo odmieta',
    'footer_toc5' => 'Tichí svedkovia',
    'footer_toc6' => 'Rozhodnutie PCA z roku 2016',
    'footer_toc7' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'footer_copy_eyebrow' => 'Neziskový projekt',
    'footer_copy_title' => 'Paracelské ostrovy – Spratlyho ostrovy patria Vietnamu',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematická stránka o Čiare deviatich čiarok v rámci suverenitného ekosystému Vietnamu.',
    'footer_copy_body' => 'Vysvetlenie nároku na Čiaru deviatich čiarok prostredníctvom <strong>objektívnych faktov</strong>, <strong>medzinárodného práva</strong>, rozhodnutia PCA z roku 2016 a historických materiálov — doplnok k podrobným stránkam o suverenite dvoch súostroví Paracelské ostrovy a Spratlyho ostrovy.',
    'footer_copy_ecosystem_aria' => 'Stránky toho istého projektu',
    'footer_copy_ecosystem_label' => 'V tom istom ekosystéme',
    'footer_copy_disclaimer' => 'Obsah je určený na vzdelávanie a zvyšovanie povedomia; nenahrádza oficiálne stanovisko Vietnamského štátu.',
    'footer_copy' => '<strong>© :year Čiara deviatich čiarok</strong> — Súčasť neziskového projektu <strong>Paracelské ostrovy – Spratlyho ostrovy patria Vietnamu</strong> v rámci systému: <a href="https://paracelislands.net/sk" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/sk" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/sk" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/sk" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/sk" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Záväzok obsahu stránky',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Rozhodnutie PCA 2016',
    'footer_chip3' => 'Historické dôkazy',
    'footer_chip4' => 'Staré mapy',
    'footer_chip5' => 'Objektívna pravda',
    'footer_chip6' => 'Mier v Juhočínskom mori',
];
