<?php

return [
    'nav_logo_name' => 'Čiara deviatich čiarok',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Čiara deviatich čiarok',
    'nav_rail_aria' => 'Navigácia podľa sekcií',
    'nav_rail_what' => 'Definícia',
    'nav_rail_origin' => 'Pôvod',
    'nav_rail_dispute' => 'Spory',
    'nav_rail_opposition' => 'Odmietnutie',
    'nav_rail_witnesses' => 'Staré mapy',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'nav_sound_off' => 'Zapnúť hudbu na pozadí',
    'nav_sound_on' => 'Vypnúť hudbu na pozadí',
    'nav_share' => 'Zdieľať',
    'dialog_title' => 'Jazyk zobrazenia',
    'language' => 'Jazyk',
    'display_hint' => ':count jazykov',
    'search_placeholder' => 'Hľadať jazyk…',
    'cancel' => 'Zrušiť',
    'apply' => 'Použiť',
    'sound_off' => 'Zapnúť zvuk na pozadí',
    'sound_on' => 'Vypnúť zvuk na pozadí',
    'lang_trigger' => 'Vybrať jazyk',
    'close' => 'Zavrieť',
    'no_results' => 'Jazyk sa nenašiel',
    'contribute' => 'Zdieľať',
];
