<?php

return [
    'opposition_index' => 'Námietky',
    'opposition_label' => 'Prečo medzinárodné spoločenstvo namieta',
    'opposition_title' => 'Námietky založené na',
    'opposition_title_accent' => 'práve, nie na emóciách',
    'opposition_lead' => 'Krátko po tom, ako bola Čiara deviatich čiarok v roku 2009 predložená OSN, viaceré štáty a akademická obec proti nej namietali — konkrétnymi právnymi argumentmi.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Máj',
    'opposition_voice1_title' => 'Vietnam · Malajzia · Indonézia',
    'opposition_voice1_body' => 'Len jeden deň po tom, čo Čína predložila mapu Čiara deviatich čiarok generálnemu tajomníkovi OSN (7. 5. 2009), tieto krajiny postupne zaslali protestné nóty a odmietli daný nárok.',
    'opposition_voice1_chip1' => 'Protestná nóta',
    'opposition_voice1_chip2' => 'Nie je v súlade s UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipíny',
    'opposition_voice2_body' => 'Zaslala diplomatický list OSN a vyhlásila, že nárok Číny v Juhočínskom mori je „bez opory v medzinárodnom práve“ — čo sa neskôr stalo základom pre arbitrážny spor.',
    'opposition_voice2_chip1' => 'Predohra k prípadu PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministerstvo zahraničných vecí USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analýza ukázala: mapy z rôznych rokov sú nejednotné v umiestnení prerušovanej čiary; prerušovaná čiara zasahuje do pevniny namiesto vedenia po stredovej línii; mnohé útvary nespĺňajú kritériá „ostrova“ na vznik výlučnej ekonomickej zóny (EEZ).',
    'opposition_voice3_chip1' => 'Nespĺňa právne podmienky',
    'opposition_voice3_chip2' => 'Oficiálna analýza',
    'opposition_voice4_year' => 'Akademická obec',
    'opposition_voice4_title' => '„Historické vody“ sú už zastarané',
    'opposition_voice4_body' => 'Tento koncept sa vzťahuje len na zálivy a pobrežné vody pri brehu — nemôže pokrývať celé rozsiahle otvorené more. V roku 2003 aj samotný Taiwan odmietol politiku „historických vôd“, ktorú uviedol už v roku 1993.',
    'opposition_voice4_chip1' => 'Ani čínski akademici sa nezhodujú',
];
