<?php

return [
    'opposition_index' => 'Odpor',
    'opposition_label' => 'Prečo medzinárodne nesúhlasia',
    'opposition_title' => 'Odpor založený na',
    'opposition_title_accent' => 'zákone, nie na emóciách',
    'opposition_lead' => 'Hneď po tom, ako bola Čiara deviatich čiarok predložená Organizácii Spojených národov v roku 2009, mnohé krajiny a akademická obec ju odmietli — na základe konkrétnych právnych argumentov.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Máj',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonézia',
    'opposition_voice1_body' => 'Už deň po tom, čo Čína predložila mapu Čiary deviatich čiarok generálnemu tajomníkovi Organizácie Spojených národov (7. 5. 2009), tieto krajiny postupne zaslali protestné nóty a odmietli tento nárok.',
    'opposition_voice1_chip1' => 'Protestná nóta',
    'opposition_voice1_chip2' => 'V rozpore s UNCLOS z roku 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipíny',
    'opposition_voice2_body' => 'Poslali diplomatický list Organizácii Spojených národov a vyhlásili, že nárok Číny v Juhočínskom mori je „bez opory v medzinárodnom práve“ — čo sa stalo predpokladom neskoršej žaloby na rozhodcovský súd.',
    'opposition_voice2_chip1' => 'Predpoklad žaloby na PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministerstvo zahraničných vecí USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analýza ukázala: mapy z rôznych rokov boli nekonzistentné v umiestnení línie; línia zasahovala do pevniny namiesto vedenia v stredovej línii; mnohé útvary nespĺňajú kritériá „ostrova“ na priznanie EEZ.',
    'opposition_voice3_chip1' => 'Nespĺňa právne podmienky',
    'opposition_voice3_chip2' => 'Oficiálna analýza',
    'opposition_voice4_year' => 'Akademické',
    'opposition_voice4_title' => '„Historické vody“ sú zastarané',
    'opposition_voice4_body' => 'Tento pojem sa vzťahuje len na zátoky a pobrežné vody blízko brehu — nemožno ním pokryť celé rozsiahle otvorené more. V roku 2003 aj samotný Taiwan odmietol politiku „historických vôd“, ktorú uviedol v roku 1993.',
    'opposition_voice4_chip1' => 'Ani čínski vedci nie sú jednotní',
];
