<?php

return [
    'sovereignty_index' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_label' => 'Nevyhnutný záver',
    'sovereignty_title' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_title_accent' => 'patria Vietnamu',
    'sovereignty_lead' => 'Táto stránka vysvetľuje Čiara deviatich čiarok. Záver odpovedá na ďalšiu otázku: komu patrí suverenita nad oboma súostroviami, Paracelskými ostrovmi a Spratlyho ostrovmi? Podľa historickej správy a medzinárodného práva je konzistentná odpoveď Vietnam.',
    'sovereignty_thesis_label' => 'Súhrnná téza',
    'sovereignty_thesis_lock1' => 'Žiadne právne súradnice',
    'sovereignty_thesis_lock2' => 'PCA 2016 zamietol',
    'sovereignty_thesis_lock3' => 'Staré mapy ich nezahŕňajú',
    'sovereignty_thesis_body' => 'Po šiestich vyššie uvedených častiach sú tri veci jasné: Čiara deviatich čiarok je ručne nakreslená, bez právnych súradníc; Arbitrážny tribunál v roku 2016 nárok zamietol; a staré mapy samotnej Číny nezahŕňajú Juhočínske more. Suverenita Vietnamu nestojí na sloganoch, ale na tom, že vietnamský štát — od čias vládcov Nguyễnovcov — tieto ostrovy pokojne a nepretržite spravoval, keď ešte boli terra nullius.',
    'sovereignty_spine_caption' => 'Míľniky nepretržitej správy',
    'sovereignty_spine_title' => 'Jeden časový sled, bez prerušenia',
    'sovereignty_spine_range' => '17. storočie → dnes',
    'sovereignty_chron1_year' => '17. stor.',
    'sovereignty_chron1_title' => 'Oddiel Hoàng Sa',
    'sovereignty_chron1_body' => 'Vládci Nguyễnovci vysielali oddiel Hoàng Sa, aby skúmal, meral námorné trasy a vykonával zber na mori — čím uplatňovali faktickú správu.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kráľ Gia Long',
    'sovereignty_chron2_body' => 'Vztyčil zástavu na súostroví Paracelské ostrovy a potvrdil suverenitu Vietnamu pred vtedajším svetom.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kráľ Minh Mạng',
    'sovereignty_chron3_body' => 'Nechal súostrovie zmerať, postaviť stély a zaznamenať ho na oficiálnych mapách dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Neprerušená kontinuita',
    'sovereignty_chron4_body' => 'Francúzsko uznalo a ďalej spravovalo; Paracelské ostrovy boli pričlenené k provincii Thừa Thiên — čo položilo základ dnešnému Vietnamskému štátu.',
    'sovereignty_chron5_year' => 'Súčasnosť',
    'sovereignty_chron5_title' => 'Právo a prax',
    'sovereignty_chron5_body' => 'Vietnam spravuje podľa UNCLOS, diplomacie a archívnych záznamov; nárok Čiara deviatich čiarok tieto dôkazy nemôže nahradiť.',
    'sovereignty_balance_label' => 'Rovnováha dôkazov',
    'sovereignty_balance_medallion_title' => 'Porovnanie oboch strán',
    'sovereignty_vn_tag' => 'Strana Vietnamu',
    'sovereignty_vn_title' => 'Suverenita sa zakladá na činoch',
    'sovereignty_vn_body' => 'Skutočné obsadenie v čase, keď územie bolo ešte terra nullius, a následná verejná správa počas mnohých storočí — s cisárskymi nariadeniami, stélami, mapami a administratívnymi záznamami. Tento postup je v súlade s UNCLOS a medzinárodnou praxou.',
    'sovereignty_dash_tag' => 'Strana Čiary deviatich čiarok',
    'sovereignty_dash_title' => 'Nárok nemôže nahradiť dôkazy',
    'sovereignty_dash_body' => 'Jedna čiara nakreslená v roku 1948, bez súradníc, bola PCA 2016 zamietnutá a je v rozpore s UNCLOS — ako ukázali časti 03 až 06. Preto záver o suverenite oboch súostroví nemôže vychádzať z Čiary deviatich čiarok.',
    'sovereignty_seal_quote' => 'Vietnam rieši spory <strong>mierovými prostriedkami</strong> na základe medzinárodného práva — najmä UNCLOS 1982 — so zameraním na pokojné, spolupracujúce a rozvojové Juhočínske more.',
    'sovereignty_seal_cite' => 'Postoj Vietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hlavný projekt v tom istom ekosystéme',
    'sovereignty_next_title' => 'Prečítajte si úplné dôkazy o Paracelských ostrovoch – Spratlyho ostrovoch',
    'sovereignty_next_body' => 'Podrobný spis — dokumenty, mapy, časová os a právne argumenty — je na stránke <strong>paracelislands.net</strong>, kde je téma suverenity nad oboma súostroviami spracovaná komplexne. Stránka, ktorú práve čítate, iba logicky spája Čiaru deviatich čiarok s týmto záverom.',
    'sovereignty_next_cta' => 'Otvoriť paracelislands.net',
];
