<?php

return [
    'sovereignty_index' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_label' => 'Nevyhnutný záver',
    'sovereignty_title' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_title_accent' => 'patria Vietnamu',
    'sovereignty_lead' => 'Táto stránka vysvetľuje Čiaru deviatich čiarok. Záverečná časť odpovedá na ďalšiu otázku: komu patrí zvrchovanosť nad dvoma súostroviami, Paracelskými ostrovmi a Spratlyho ostrovmi? Podľa historickej správy a medzinárodného práva je odpoveď jednoznačná: Vietnamu.',
    'sovereignty_thesis_label' => 'Súhrnná téza',
    'sovereignty_thesis_lock1' => 'Žiadne právne súradnice',
    'sovereignty_thesis_lock2' => 'PCA 2016 zamietlo',
    'sovereignty_thesis_lock3' => 'Staré mapy nezahŕňajú',
    'sovereignty_thesis_body' => 'Po šiestich vyššie uvedených častiach sú jasné tri body: Čiara deviatich čiarok je ručne nakreslená a nemá právne súradnice; Arbitrážny tribunál v roku 2016 tento nárok zamietol; staré mapy samotnej Číny nepokrývajú Juhočínske more. Zvrchovanosť Vietnamu nestojí na heslách, ale na tom, že vietnamský štát — od čias panovníkov dynastie Nguyễn — tieto ostrovy mierovo a nepretržite spravoval, keď boli ešte terra nullius.',
    'sovereignty_spine_caption' => 'Míľniky nepretržitej správy',
    'sovereignty_spine_title' => 'Jeden časový sled, bez prerušenia',
    'sovereignty_spine_range' => '17. storočie → súčasnosť',
    'sovereignty_chron1_year' => '17. stor.',
    'sovereignty_chron1_title' => 'Oddiel Hoàng Sa',
    'sovereignty_chron1_body' => 'Panovníci dynastie Nguyễn vysielali oddiel Hoàng Sa na prieskum, meranie plavebných trás a námorné využívanie — vykonávali tak faktickú správu.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kráľ Gia Long',
    'sovereignty_chron2_body' => 'Zabodol na súostroví Paracelské ostrovy vlajku a potvrdil tak zvrchovanosť Vietnamu pred vtedajším svetom.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kráľ Minh Mạng',
    'sovereignty_chron3_body' => 'Nechal ostrovy zamerať, vztýčiť stély a zaznamenať ich na oficiálne mapy dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuita nástupníctva',
    'sovereignty_chron4_body' => 'Francúzsko toto postavenie uznalo a ďalej spravovalo; Paracelské ostrovy boli pričlenené k provincii Thừa Thiên — to tvorí základ dnešného vietnamského štátu.',
    'sovereignty_chron5_year' => 'Súčasnosť',
    'sovereignty_chron5_title' => 'Právo a prax',
    'sovereignty_chron5_body' => 'Vietnam spravuje územie podľa UNCLOS, diplomacie a archívnych záznamov; nárok Čiary deviatich čiarok tieto dôkazy nenahrádza.',
    'sovereignty_balance_label' => 'Vyváženie dôkazov',
    'sovereignty_balance_medallion_title' => 'Porovnanie dvoch strán',
    'sovereignty_vn_tag' => 'Vietnamská strana',
    'sovereignty_vn_title' => 'Zvrchovanosť potvrdená konaním',
    'sovereignty_vn_body' => 'Skutočné obsadenie v čase, keď územie bolo bez pána, a potom verejná správa po stáročia — s cisárskymi záznamami, stélami, mapami a administratívnymi spismi. Tento postup je v súlade s UNCLOS aj medzinárodnou praxou.',
    'sovereignty_dash_tag' => 'Strana Čiary deviatich čiarok',
    'sovereignty_dash_title' => 'Nárok nedokáže nahradiť dôkazy',
    'sovereignty_dash_body' => 'Jedna čiara nakreslená v roku 1948, bez súradníc, bola zamietnutá PCA v roku 2016 a je v rozpore s UNCLOS — ako bolo uvedené v bodoch 03 až 06. Preto záver o zvrchovanosti nad oboma súostroviami nemôže stáť na Čiare deviatich čiarok.',
    'sovereignty_seal_quote' => 'Vietnam rieši spory <strong>mierovými prostriedkami</strong>, na základe medzinárodného práva — najmä UNCLOS 1982 — s cieľom dosiahnuť Juhočínske more mieru, spolupráce a rozvoja.',
    'sovereignty_seal_cite' => 'Postoj Vietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hlavný projekt v tom istom ekosystéme',
    'sovereignty_next_title' => 'Prečítajte si úplné dôkazy o Paracelských ostrovoch – Spratlyho ostrovoch',
    'sovereignty_next_body' => 'Podrobný spis — dokumenty, mapy, časová os a právne argumenty — je na stránke <strong>paracelislands.net</strong>, kde je komplexne predstavená téma zvrchovanosti nad oboma súostroviami. Stránka, ktorú práve čítate, iba logicky spája Čiaru deviatich čiarok s týmto záverom.',
    'sovereignty_next_cta' => 'Otvoriť paracelislands.net',
];
