<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Medzinárodný rozsudok',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tri „Nie“',
    'verdict_lead' => 'Dňa 12. 7. 2016 Stály rozhodcovský súd (PCA) v Haagu — zriadený podľa Prílohy VII Dohovoru OSN o morskom práve (UNCLOS), v prípade Filipíny proti Číne — vydal rozsudok, ktorým zamietol nárok na Čiara deviatich čiarok. <em>Kliknite na každú kartu, aby ste si prečítali plné znenie.</em>',
    'verdict_card1_khong' => 'NIE',
    'verdict_card1_title' => 'historické právo',
    'verdict_card1_short' => 'Čína nemá právny základ na uplatňovanie historického práva k zdrojom v morských oblastiach v rámci Čiara deviatich čiarok.',
    'verdict_card1_quote' => '„Neexistuje právny základ na to, aby Čína uplatňovala historické práva k zdrojom nachádzajúcim sa v morských oblastiach v rámci Čiara deviatich čiarok.“',
    'verdict_card1_more' => '+ Prečítať rozsudok',
    'verdict_card2_khong' => 'NIE',
    'verdict_card2_title' => 'prvok vytvárajúci výlučnú ekonomickú zónu',
    'verdict_card2_short' => 'Žiadny prvok v súostroví Spratlyho ostrovy nespĺňa podmienky na vytvorenie výlučnej ekonomickej zóny pre Čínu — vrátane ostrova Ba Bình.',
    'verdict_card2_quote' => '„Žiadny prvok v súostroví Spratlyho ostrovy nie je schopný vytvoriť výlučnú ekonomickú zónu.“',
    'verdict_card2_more' => '+ Prečítať rozsudok',
    'verdict_card3_khong' => 'NIE',
    'verdict_card3_title' => 'zákonné konanie',
    'verdict_card3_short' => 'Čína porušila zvrchované práva Filipín, bránila rybolovu a poškodila morské prostredie.',
    'verdict_card3_quote' => '„Čína porušila zvrchované práva Filipín, zasahovala do rybolovu pri útese Scarborough a vážne poškodila prostredie koralového útesu.“',
    'verdict_card3_more' => '+ Prečítať rozsudok',
    'verdict_extra1' => 'Čiara deviatich čiarok, ktorú si Čína sama nakreslila, <strong>nie je v súlade</strong> s UNCLOS z roku 1982.',
    'verdict_extra2' => 'Čína poškodzuje ekosystém Spratlyho ostrovov nadmerným využívaním zdrojov a budovaním umelých ostrovov.',
    'verdict_extra3' => 'Kroky Číny zvyšujú riziko konfliktu s Filipínami.',
    'verdict_extra4' => 'Ostrov Ba Bình (pod kontrolou Taiwanu) tiež nemôže vytvoriť výlučnú ekonomickú zónu.',
    'verdict_subtitle' => 'Prečo je to v rozpore s UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS z roku 1982 jasne vymedzuje morské pásma na základe základnej línie pobrežného štátu. Nárok Čiara deviatich čiarok tento rámec prekračuje, a preto s ním nie je zlučiteľný.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Pobrežné more (míle)',
    'verdict_zone1_body' => 'Morské pásmo štátu so zvrchovanosťou, merané od základnej línie.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Výlučná ekonomická zóna',
    'verdict_zone2_body' => 'EEZ — pobrežný štát má v tomto pásme zvrchované práva k zdrojom.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentálny šelf (max., míle)',
    'verdict_zone3_body' => 'Práva k zdrojom morského dna podľa určených geologických podmienok.',
    'verdict_foot' => 'V tomto rámci je „historické právo“ na celé otvorené more — ako naznačuje Čiara deviatich čiarok — <em>nahradené</em> právnym režimom UNCLOS, ktorého je aj Čína zmluvnou stranou.',
];
