<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Medzinárodný rozsudok',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tri „nie“',
    'verdict_lead' => 'Dňa 12. 7. 2016 Stály rozhodcovský súd (PCA) v Haagu — zriadený podľa prílohy VII UNCLOS v spore Filipíny proti Číne — vydal rozsudok, ktorým zamietol nárok na Čiaru deviatich čiarok. <em>Kliknite na každú kartu, aby ste si prečítali celý text.</em>',
    'verdict_card1_khong' => 'NIE',
    'verdict_card1_title' => 'historické právo',
    'verdict_card1_short' => 'Čína nemá právny základ na uplatňovanie historického práva na zdroje v moriach vnútri Čiary deviatich čiarok.',
    'verdict_card1_quote' => '„Neexistuje žiadny právny základ, aby Čína uplatňovala historické právo na zdroje nachádzajúce sa v moriach vnútri Čiary deviatich čiarok.“',
    'verdict_card1_more' => '+ Prečítať rozsudok',
    'verdict_card2_khong' => 'NIE',
    'verdict_card2_title' => 'útvar vytvárajúci EEZ',
    'verdict_card2_short' => 'Žiadny útvar v Spratlyho ostrovoch nespĺňa podmienky na vytvorenie výlučnej ekonomickej zóny pre Čínu — vrátane ostrova Ba Bình.',
    'verdict_card2_quote' => '„Žiadny útvar v Spratlyho ostrovoch nemá schopnosť vytvoriť výlučnú ekonomickú zónu.“',
    'verdict_card2_more' => '+ Prečítať rozsudok',
    'verdict_card3_khong' => 'NIE',
    'verdict_card3_title' => 'zákonné konanie',
    'verdict_card3_short' => 'Čína porušila suverénne práva Filipín, bránila rybolovu a poškodila morské prostredie.',
    'verdict_card3_quote' => '„Čína porušila suverénne práva Filipín, zasahovala do rybolovu v oblasti Scarborough Shoal a spôsobila vážne škody koralovému životnému prostrediu.“',
    'verdict_card3_more' => '+ Prečítať rozsudok',
    'verdict_extra1' => 'Čiara deviatich čiarok, ktorú si Čína sama nakreslila, <strong>nie je v súlade</strong> s dohovorom UNCLOS z roku 1982.',
    'verdict_extra2' => 'Čína poškodila ekosystém v Spratlyho ostrovoch nadmerným využívaním zdrojov a budovaním umelých ostrovov.',
    'verdict_extra3' => 'Kroky Číny zvyšujú riziko konfliktu s Filipínami.',
    'verdict_extra4' => 'Ostrov Ba Bình (pod kontrolou Taiwanu) tiež nemôže vytvoriť EEZ.',
    'verdict_subtitle' => 'Prečo je to v rozpore s UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 presne vymedzuje morské zóny na základe základnej línie pobrežného štátu. Nárok na Čiaru deviatich čiarok tento rámec prekračuje, a preto ho nemožno zosúladiť.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoriálne more (míle)',
    'verdict_zone1_body' => 'Morská oblasť so štátnou zvrchovanosťou, meraná od základnej línie.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Výlučná ekonomická zóna',
    'verdict_zone2_body' => 'EEZ — pobrežný štát má v tomto rozsahu suverénne práva na zdroje.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentálny šelf (maximum, míle)',
    'verdict_zone3_body' => 'Práva k zdrojom morského dna podľa určených geologických podmienok.',
    'verdict_foot' => 'V tomto rámci „historické právo“, ktoré by zahŕňalo celé otvorené more — ako naznačuje Čiara deviatich čiarok — <em>bolo nahradené</em> právnym režimom UNCLOS, ktorého je Čína takisto členom.',
];
