<?php

return [
    'witnesses_index' => 'Staré mapy',
    'witnesses_label' => 'Staré mapy Číny',
    'witnesses_title' => 'Sahá len k najjužnejšiemu bodu',
    'witnesses_title_accent' => 'ostrov Chaj-nan',
    'witnesses_lead' => 'Staré mapy kreslené čínskymi autormi — usporiadané chronologicky — všetky ukazujú, že <em>ostrov Chaj-nan je najjužnejším bodom</em> Číny, bez Paracelských ostrovov či Spratlyho ostrovov. Súhrn materiálov podľa <em>Suverenita Vietnamu nad dvoma súostroviami Paracelské ostrovy a Spratlyho ostrovy</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Použiť lupu',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— najjužnejší bod územia —',
    'witnesses_map1_svg_era' => 'Dynastia Song · 1136',
    'witnesses_map1_title' => 'Mapa dynastie Song, 1136',
    'witnesses_map1_body' => 'Územie Číny sa končilo na ostrove Hainan — Paracelské ostrovy a Spratlyho ostrovy ležali mimo hraníc.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'hranica d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Mapa d\'Anville, 1735',
    'witnesses_map2_body' => 'Nakreslil ju J.-B. B. d\'Anville; kópia z roku 1740 bola kedysi darovaná nemeckým kancelárom čínskemu vedeniu. Územie dynastie Čching sa končilo pri Hainane.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"najjužnejšia Čína"',
    'witnesses_map3_svg_era' => 'Celková mapa zemepisu cisárskeho pravosprávneho systému · 1904',
    'witnesses_map3_title' => 'Celková mapa zemepisu cisárskeho pravosprávneho systému',
    'witnesses_map3_body' => 'Vydaná dynastiou Čching — jasne uvádza, že najjužnejším územím Číny je ostrov Hainan.',
    'witnesses_quote' => 'Práve samotné čínske mapy, ktoré boli kedysi zverejnené, nezobrazovali Paracelské ostrovy ani Spratlyho ostrovy ako súčasť ich územia.',
    'witnesses_timeline_aria' => 'Časová os starých čínskych máp',
    'witnesses_year_aria' => 'Datovanie',
    'lightbox_aria' => 'Zobraziť zväčšený obrázok',
    'lightbox_close' => 'Zavrieť',
    'lightbox_prev' => 'Predchádzajúci obrázok',
    'lightbox_next' => 'Nasledujúci obrázok',
];
