<?php

return [
    'footer_index' => '圖書館',
    'footer_crest_eyebrow' => '圖書館的真相結語',
    'footer_crest_quote' => '“南海的和平建立在 <b>國際法</b> 的基礎之上。”',
    'footer_crest_sub' => '不仇恨 · 只有事實',
    'footer_nav_aria' => '頁尾動作',
    'footer_btn_top' => '回到頁首',
    'footer_btn_verdict' => 'PCA 2016 裁決',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '十一段線',
    'footer_brand_body' => '一個基於客觀事實、國際法與歷史文獻的解說網站——以證據而非口號，駁斥十一段線主張。',
    'footer_refs_title' => '參考來源',
    'footer_ref1' => 'PCA 裁決，2016/7/12',
    'footer_ref2' => '1982 年 UNCLOS —— 全文',
    'footer_ref3' => 'Limits in the Seas №143（美國國務院）',
    'footer_ref4' => '歷史資料與古地圖',
    'footer_toc_title' => '頁面目錄',
    'footer_toc1' => '什麼是十一段線',
    'footer_toc2' => '起源',
    'footer_toc3' => '為何引發爭議',
    'footer_toc4' => '為何遭到國際反對',
    'footer_toc5' => '沉默的見證者',
    'footer_toc6' => 'PCA 2016 裁決',
    'footer_toc7' => '西沙群島 – 南沙群島',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — 南海的客觀事實。<br>生態系統：<a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => '1982 年 UNCLOS',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => '無座標',
];
