<?php

return [
    'footer_index' => '資料庫',
    'footer_crest_eyebrow' => '真相資料庫的結語',
    'footer_crest_quote' => '「南海的和平建立在 <b>國際法</b> 的基礎之上。」',
    'footer_crest_sub' => '不仇恨 · 只有真相',
    'footer_nav_aria' => '頁尾行動',
    'footer_btn_top' => '返回頁首',
    'footer_btn_verdict' => '2016 年 PCA 裁決',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => '十一段線主張',
    'footer_brand_eyebrow' => '專題頁 · 越南主權',
    'footer_brand_body' => '以客觀事實、國際法、2016 年 PCA 裁決與歷史資料解析十一段線——作為補充越南對兩個群島 <strong>"西沙群島和南沙群島"</strong> 主權的深入專頁。以歷史與證據駁斥中國的無理主張。',
    'footer_refs_title' => '參考資料',
    'footer_ref1' => 'PCA 裁決，2016/7/12',
    'footer_ref2' => '《1982 年 UNCLOS》— 全文',
    'footer_ref3' => 'Limits in the Seas №143（美國國務院）',
    'footer_ref4' => '歷史資料與古地圖',
    'footer_toc_title' => '頁面目錄',
    'footer_toc1' => '什麼是十一段線',
    'footer_toc2' => '起源',
    'footer_toc3' => '為何具爭議',
    'footer_toc4' => '為何遭國際反對',
    'footer_toc5' => '沉默的見證',
    'footer_toc6' => '2016 年 PCA 裁決',
    'footer_toc7' => '西沙群島 – 南沙群島',
    'footer_copy_eyebrow' => '非營利專案',
    'footer_copy_title' => '西沙群島 – 南沙群島屬於越南',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — 越南主權生態系統中的十一段線專題頁。',
    'footer_copy_body' => '以 <strong>客觀事實</strong>、<strong>國際法</strong>、2016 年 PCA 裁決與歷史資料解析十一段線主張——作為補充越南對西沙群島與南沙群島兩個群島主權的深入專頁。',
    'footer_copy_ecosystem_aria' => '同一專案的頁面',
    'footer_copy_ecosystem_label' => '同一生態系統',
    'footer_copy_disclaimer' => '內容旨在教育與提升認知；不取代越南國家正式立場。',
    'footer_copy' => '<strong>© :year 十一段線</strong> — 非營利專案 <strong>西沙群島 – 南沙群島屬於越南</strong> 的一部分，隸屬以下系統：<a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => '頁面內容承諾',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 年 PCA 裁決',
    'footer_chip3' => '歷史證據',
    'footer_chip4' => '古地圖',
    'footer_chip5' => '客觀事實',
    'footer_chip6' => '南海和平',
];
