<?php

return [
    'footer_index' => '圖書館',
    'footer_crest_eyebrow' => '真相圖書館的結語',
    'footer_crest_quote' => '「南海的和平建立在<strong>國際法</strong>的基礎之上。」',
    'footer_crest_sub' => '不仇恨 · 只有真相',
    'footer_nav_aria' => '頁尾操作',
    'footer_btn_top' => '回到頁首',
    'footer_btn_verdict' => '2016 年 PCA 裁決',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '十一段線主張',
    'footer_brand_eyebrow' => '專題網站 · 越南主權',
    'footer_brand_body' => '透過客觀真相、國際法、2016 年 PCA 裁決與歷史資料來闡釋十一段線，並補充關於兩個群島<strong>「西沙群島與南沙群島」</strong>主權的深度內容。以歷史與證據駁斥中國毫無根據的主張。',
    'footer_refs_title' => '參考來源',
    'footer_ref1' => 'PCA 裁決，2016/7/12',
    'footer_ref2' => '《1982 年聯合國海洋法公約》— 全文',
    'footer_ref3' => '《海域界限》第 143 號（美國國務院）',
    'footer_ref4' => '歷史資料與古地圖',
    'footer_toc_title' => '頁面目錄',
    'footer_toc1' => '什麼是十一段線',
    'footer_toc2' => '起源',
    'footer_toc3' => '為何引發爭議',
    'footer_toc4' => '為何遭到國際反對',
    'footer_toc5' => '沉默的見證者',
    'footer_toc6' => '2016 年 PCA 裁決',
    'footer_toc7' => '西沙群島 – 南沙群島',
    'footer_copy_eyebrow' => '非營利專案',
    'footer_copy_title' => '西沙群島 – 南沙群島屬於越南',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — 越南主權生態系中的十一段線專題網站。',
    'footer_copy_body' => '透過<strong>客觀事實</strong>、<strong>國際法</strong>、2016 年 PCA 裁決與歷史資料來闡釋十一段線主張 — 並補充關於西沙群島與南沙群島主權的深度內容。',
    'footer_copy_ecosystem_aria' => '同一專案的網站',
    'footer_copy_ecosystem_label' => '同一生態系',
    'footer_copy_disclaimer' => '本內容旨在教育與提升認知；不取代越南政府的正式立場。',
    'footer_copy' => '<strong>© :year 十一段線</strong> — 非營利專案<strong>西沙群島 – 南沙群島屬於越南</strong>的一部分，屬於以下系統：<a href="https://paracelislands.net/zh-tw" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/zh-tw" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/zh-tw" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/zh-tw" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/zh-tw" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => '頁面內容承諾',
    'footer_chip1' => '1982 年 UNCLOS',
    'footer_chip2' => '2016 年 PCA 裁決',
    'footer_chip3' => '歷史證據',
    'footer_chip4' => '古地圖',
    'footer_chip5' => '客觀事實',
    'footer_chip6' => '南海和平',
];
