<?php

return [
    'nav_logo_name' => '十一段線',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => '十一段線',
    'nav_rail_aria' => '依主題導覽',
    'nav_rail_what' => '定義',
    'nav_rail_origin' => '起源',
    'nav_rail_dispute' => '爭議',
    'nav_rail_opposition' => '反對',
    'nav_rail_witnesses' => '古地圖',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => '西沙群島 – 南沙群島',
    'nav_sound_off' => '開啟背景音樂',
    'nav_sound_on' => '關閉背景音樂',
    'nav_share' => '分享',
    'dialog_title' => '顯示語言',
    'language' => '語言',
    'display_hint' => ':count 種語言',
    'search_placeholder' => '搜尋語言…',
    'cancel' => '取消',
    'apply' => '套用',
    'sound_off' => '開啟背景音效',
    'sound_on' => '關閉背景音效',
    'lang_trigger' => '選擇語言',
    'close' => '關閉',
    'no_results' => '找不到語言',
    'contribute' => '分享',
];
