<?php

return [
    'opposition_index' => '反對',
    'opposition_label' => '為何國際反對',
    'opposition_title' => '反對基於',
    'opposition_title_accent' => '法律，而非情緒',
    'opposition_lead' => '自十一段線於2009年提交至聯合國後，許多國家與學者便提出反對——並以具體的法律論據為依據。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => '越南 · 馬來西亞 · 印尼',
    'opposition_voice1_body' => '就在中國將十一段線地圖提交給聯合國秘書長（2009/5/7）後僅一天，這些國家便陸續發出抗議照會，駁斥相關主張。',
    'opposition_voice1_chip1' => '抗議照會',
    'opposition_voice1_chip2' => '不符合1982年《聯合國海洋法公約》',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => '菲律賓',
    'opposition_voice2_body' => '向聯合國提交外交照會，聲明中國在南海的主張「沒有國際法依據」——這也成為之後提請常設仲裁法院仲裁的前提。',
    'opposition_voice2_chip1' => 'PCA訴訟前提',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '12/05',
    'opposition_voice3_title' => '美國國務院 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析指出：歷年地圖對界線位置前後不一；界線侵入內陸而非採取中線；多個海洋地物不足以符合「島嶼」標準，因而不能享有專屬經濟區。',
    'opposition_voice3_chip1' => '不符合法律條件',
    'opposition_voice3_chip2' => '官方分析',
    'opposition_voice4_year' => '學術',
    'opposition_voice4_title' => '「歷史性水域」已過時',
    'opposition_voice4_body' => '此概念只適用於海灣、近岸內凹海域——不能涵蓋整個廣闊海域。2003年，台灣本身也已否定1993年曾提出的「歷史性水域」政策。',
    'opposition_voice4_chip1' => '即使中國學者也未達成一致',
];
