<?php

return [
    'opposition_index' => '反對',
    'opposition_label' => '為何國際社會反對',
    'opposition_title' => '反對基於',
    'opposition_title_accent' => '法律，而非情緒',
    'opposition_lead' => '就在十一段線於2009年提交聯合國後，許多國家與學界便提出反對——並以具體的法律論據為依據。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => '越南 · 馬來西亞 · 印尼',
    'opposition_voice1_body' => '在中國將十一段線地圖提交聯合國秘書長（2009/5/7）僅一天後，這些國家便相繼致函抗議，駁斥其主張。',
    'opposition_voice1_chip1' => '抗議照會',
    'opposition_voice1_chip2' => '不符合1982年《聯合國海洋法公約》',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => '菲律賓',
    'opposition_voice2_body' => '致函聯合國外交照會，宣稱中國在南中國海的主張「沒有國際法依據」——這也成為其後向仲裁庭提起訴訟的前提。',
    'opposition_voice2_chip1' => 'PCA訴訟前提',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => '美國國務院 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析指出：歷年地圖對於界線位置並不一致；界線侵入大陸，而非以中線為基準；多個地物不具備成為「島嶼」並擁有EEZ的條件。',
    'opposition_voice3_chip1' => '不具備法律條件',
    'opposition_voice3_chip2' => '官方分析',
    'opposition_voice4_year' => '學術界',
    'opposition_voice4_title' => '「歷史性水域」已過時',
    'opposition_voice4_body' => '此概念僅適用於海灣、近岸內海——不可能涵蓋整個廣大外海。2003年，連臺灣也駁斥了其在1993年曾提出的「歷史性水域」政策。',
    'opposition_voice4_chip1' => '甚至中國學者也未達一致',
];
