<?php

return [
    'sovereignty_index' => '西沙群島 - 南沙群島',
    'sovereignty_label' => '必然結論',
    'sovereignty_title' => '西沙群島 - 南沙群島',
    'sovereignty_title_accent' => '屬於越南',
    'sovereignty_lead' => '本頁說明十一段線。結論部分回答下一個問題：誰對西沙群島和南沙群島擁有主權？依據歷史管理與國際法，答案一致是越南。',
    'sovereignty_thesis_label' => '綜合論點',
    'sovereignty_thesis_lock1' => '無法律座標',
    'sovereignty_thesis_lock2' => '2016 年仲裁裁決駁回',
    'sovereignty_thesis_lock3' => '古地圖未涵蓋',
    'sovereignty_thesis_body' => '在上面六個部分之後，三點已經明確：十一段線是手繪的，沒有法律座標；2016 年仲裁庭駁回了該主張；中國自己的古地圖也未涵蓋整個南海。越南的主權不依賴口號，而是建立在越南國家——自阮主時期起——在兩個群島仍屬無主地時，已經和平且持續地加以管理。',
    'sovereignty_spine_caption' => '持續管理的里程碑',
    'sovereignty_spine_title' => '一條不中斷的時間線',
    'sovereignty_spine_range' => '17 世紀 → 至今',
    'sovereignty_chron1_year' => '17 世紀',
    'sovereignty_chron1_title' => '黃沙隊',
    'sovereignty_chron1_body' => '阮主派遣黃沙隊進行勘查、測量航道並在海上開採——實際行使管理權。',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => '嘉隆皇帝',
    'sovereignty_chron2_body' => '在西沙群島插旗，向當時世界確認越南的主權。',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => '明命皇帝',
    'sovereignty_chron3_body' => '進行測量、立碑，並將群島記錄於朝廷的正式地圖中。',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => '持續繼承',
    'sovereignty_chron4_body' => '法國予以承認並延續管理；將西沙群島併入承天省——這成為今日越南國家的基礎。',
    'sovereignty_chron5_year' => '當今',
    'sovereignty_chron5_title' => '法律與實踐',
    'sovereignty_chron5_body' => '越南依據 UNCLOS、外交與檔案資料進行管理；十一段線主張無法取代這些證據。',
    'sovereignty_balance_label' => '證據平衡',
    'sovereignty_balance_medallion_title' => '雙方對照',
    'sovereignty_vn_tag' => '越南一方',
    'sovereignty_vn_title' => '以行為確立的主權',
    'sovereignty_vn_body' => '在土地仍屬無主時實際占有，隨後數百年公開管理——有詔書、碑記、地圖與行政檔案。這種做法符合 UNCLOS 與國際慣例。',
    'sovereignty_dash_tag' => '十一段線一方',
    'sovereignty_dash_title' => '主張無法補足證據',
    'sovereignty_dash_body' => '1948 年的一條線，沒有座標，已被 2016 年 PCA 駁回，且違反 UNCLOS——如第 03 至 06 部分所述。因此，關於兩個群島主權的結論不能建立在十一段線之上。',
    'sovereignty_seal_quote' => '越南依據<strong>和平手段</strong>，以國際法——特別是 1982 年 UNCLOS——處理爭端，致力於實現一個和平、合作與發展的南海。',
    'sovereignty_seal_cite' => '越南立場 · 1982 年 UNCLOS',
    'sovereignty_next_eyebrow' => '同一生態系中的核心專案',
    'sovereignty_next_title' => '完整閱讀西沙群島 - 南沙群島的證據',
    'sovereignty_next_body' => '詳細檔案——文件、地圖、時間線與法律論據——收錄於 <strong>paracelislands.net</strong>，該站全面呈現兩個群島主權主題。你目前閱讀的頁面，僅將邏輯從十一段線連結到該結論。',
    'sovereignty_next_cta' => '開啟 paracelislands.net',
];
