<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '國際裁決',
    'verdict_title' => 'PCA 2016：',
    'verdict_title_accent' => '三個「不」字',
    'verdict_lead' => '2016年7月12日，海牙常設仲裁法院（PCA）——依據《聯合國海洋法公約》（UNCLOS）附件七成立，於菲律賓訴中國一案中——作出裁決，駁回十一段線主張。<em>點擊每張卡片閱讀原文。</em>',
    'verdict_card1_khong' => '不',
    'verdict_card1_title' => '歷史性權利',
    'verdict_card1_short' => '中國對位於十一段線內海域資源主張歷史性權利，缺乏法律依據。',
    'verdict_card1_quote' => '「中國對位於十一段線內海域中的各項資源主張歷史性權利，沒有法律依據。」',
    'verdict_card1_more' => '+ 閱讀裁決',
    'verdict_card2_khong' => '不',
    'verdict_card2_title' => '構成EEZ的實體',
    'verdict_card2_short' => '南沙群島中沒有任何實體具備形成中國專屬經濟區的資格——包括太平島。',
    'verdict_card2_quote' => '「南沙群島中沒有任何實體有能力形成專屬經濟區。」',
    'verdict_card2_more' => '+ 閱讀裁決',
    'verdict_card3_khong' => '不',
    'verdict_card3_title' => '合法行為',
    'verdict_card3_short' => '中國侵犯了菲律賓的主權權利，阻礙漁業活動並損害海洋環境。',
    'verdict_card3_quote' => '「中國侵犯了菲律賓的主權權利，干預了在黃岩島的漁業活動，並對珊瑚礁環境造成嚴重損害。」',
    'verdict_card3_more' => '+ 閱讀裁決',
    'verdict_extra1' => '中國自行繪製的十一段線<strong>不符合</strong>1982年《聯合國海洋法公約》。',
    'verdict_extra2' => '中國透過過度開採與填海造島，對南沙群島生態系造成損害。',
    'verdict_extra3' => '中國的行動加劇了與菲律賓發生衝突的風險。',
    'verdict_extra4' => '太平島（由臺灣控制）也不能形成EEZ。',
    'verdict_subtitle' => '為什麼它與UNCLOS衝突？',
    'verdict_subtitle_body' => '1982年《聯合國海洋法公約》依據沿海國的基線，明確劃分各海域。十一段線主張超出此一框架，因此無法相容並列。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '領海（海里）',
    'verdict_zone1_body' => '國家享有主權的海域，自基線起算。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '專屬經濟區',
    'verdict_zone2_body' => 'EEZ——沿海國在此範圍內對資源享有主權權利。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陸棚（最長，海里）',
    'verdict_zone3_body' => '依地質條件認定，對海床資源享有權利。',
    'verdict_foot' => '在這一制度下，涵蓋整片公海海域的「歷史性權利」——如十一段線所暗示者——<em>已被</em>UNCLOS的法律制度所取代，而中國本身也是其締約成員。',
];
