<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '國際裁決',
    'verdict_title' => 'PCA 2016：',
    'verdict_title_accent' => '三個「不」字',
    'verdict_lead' => '2016年7月12日，海牙常設仲裁法院（PCA）——依據《聯合國海洋法公約》（UNCLOS）附件七設立，於菲律賓訴中國一案中——作出裁決，否定了十一段線主張。<em>點擊每一個卡片即可閱讀原文。</em>',
    'verdict_card1_khong' => '不',
    'verdict_card1_title' => '歷史性權利',
    'verdict_card1_short' => '中國就十一段線內海域的資源主張歷史性權利，沒有法律依據。',
    'verdict_card1_quote' => '「中國就十一段線內海域的資源主張歷史性權利，沒有法律依據。」',
    'verdict_card1_more' => '+ 閱讀裁決',
    'verdict_card2_khong' => '不',
    'verdict_card2_title' => '可產生EEZ的實體',
    'verdict_card2_short' => '南沙群島中沒有任何實體具備為中國產生專屬經濟區的條件——包括太平島。',
    'verdict_card2_quote' => '「南沙群島中沒有任何實體具備產生專屬經濟區的能力。」',
    'verdict_card2_more' => '+ 閱讀裁決',
    'verdict_card3_khong' => '不',
    'verdict_card3_title' => '合法行為',
    'verdict_card3_short' => '中國侵犯了菲律賓的主權權利，阻礙漁業活動，並損害海洋環境。',
    'verdict_card3_quote' => '「中國侵犯了菲律賓的主權權利，干預黃岩島附近的漁業活動，並對珊瑚礁環境造成嚴重損害。」',
    'verdict_card3_more' => '+ 閱讀裁決',
    'verdict_extra1' => '中國自行繪製的十一段線 <strong>不符合</strong> 1982年《聯合國海洋法公約》。',
    'verdict_extra2' => '中國透過過度開採與填海造島，對南沙群島生態系統造成損害。',
    'verdict_extra3' => '中國的行動加劇了與菲律賓發生衝突的風險。',
    'verdict_extra4' => '太平島（由台灣控制）也無法產生EEZ。',
    'verdict_subtitle' => '為何它與UNCLOS相衝突？',
    'verdict_subtitle_body' => '1982年《聯合國海洋法公約》根據沿海國家的基線，明確劃分各海域。十一段線的主張超出此一框架，因此不能並置。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '領海（海里）',
    'verdict_zone1_body' => '自基線起算，國家享有主權的海域。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '專屬經濟區',
    'verdict_zone2_body' => 'EEZ——沿海國在此範圍內對資源享有主權權利。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陸棚（最長，海里）',
    'verdict_zone3_body' => '依地質條件確定，享有海床資源權利。',
    'verdict_foot' => '在此框架下，涵蓋整片公海海域的「歷史性權利」——如十一段線所暗示的那樣——<em>已被取代</em>，而取而代之的是UNCLOS的法律制度；中國本身也是該公約的締約國。',
];
