<?php

return [
    'footer_index' => 'గ్రంథాలయం',
    'footer_crest_eyebrow' => 'గ్రంథాలయ సత్యాన్ని ముగింపు భాగం',
    'footer_crest_quote' => '“దక్షిణ చైనా సముద్రంలో శాంతి <b>అంతర్జాతీయ చట్టం</b> అనే పునాదిపై నిర్మితమవుతుంది.”',
    'footer_crest_sub' => 'ద్వేషం లేదు · కేవలం నిజం',
    'footer_nav_aria' => 'పేజీ చివరి చర్యలు',
    'footer_btn_top' => 'పైకి వెళ్ళండి',
    'footer_btn_verdict' => 'PCA 2016 తీర్పు',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'నైన్-డాష్ లైన్ వాదన',
    'footer_brand_eyebrow' => 'ప్రత్యేక అంశం · వియత్నాం సార్వభౌమత్వం',
    'footer_brand_body' => 'నైన్-డాష్ లైన్‌ను వాస్తవిక సత్యం, అంతర్జాతీయ చట్టం, PCA 2016 తీర్పు మరియు చారిత్రక పత్రాల ద్వారా వివరిస్తూ — <strong>"పారాసెల్ దీవులు మరియు స్ప్రాట్లీ దీవులు"</strong> పై సార్వభౌమత్వాన్ని లోతుగా పరిశీలించే పేజీలకు తోడ్పడుతుంది. చైనా యొక్క అన్యాయమైన వాదనలను చరిత్ర మరియు ఆధారాలతో ఖండిస్తుంది.',
    'footer_refs_title' => 'సూచనలు',
    'footer_ref1' => 'PCA తీర్పు, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — సంపూర్ణ పాఠ్యం',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'చారిత్రక పత్రాలు & పురాతన పటాలు',
    'footer_toc_title' => 'పేజీ విషయ సూచిక',
    'footer_toc1' => 'నైన్-డాష్ లైన్ అంటే ఏమిటి',
    'footer_toc2' => 'ఉద్భవం',
    'footer_toc3' => 'ఇది ఎందుకు వివాదాస్పదం',
    'footer_toc4' => 'అంతర్జాతీయంగా ఎందుకు వ్యతిరేకత ఉంది',
    'footer_toc5' => 'నిశ్శబ్ద సాక్షులు',
    'footer_toc6' => 'PCA 2016 తీర్పు',
    'footer_toc7' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు',
    'footer_copy_eyebrow' => 'లాభాపేక్షలేని ప్రాజెక్టు',
    'footer_copy_title' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు వియత్నాంకు చెందాయి',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — వియత్నాం సార్వభౌమత్వ పరితంత్రంలో నైన్-డాష్ లైన్‌పై ప్రత్యేక పేజీ.',
    'footer_copy_body' => 'నైన్-డాష్ లైన్ వాదనను <strong>వాస్తవిక సత్యం</strong>, <strong>అంతర్జాతీయ చట్టం</strong>, PCA 2016 తీర్పు మరియు చారిత్రక పత్రాల ద్వారా వివరిస్తూ — పారాసెల్ దీవులు మరియు స్ప్రాట్లీ దీవుల సార్వభౌమత్వంపై లోతైన పేజీలకు తోడ్పడుతుంది.',
    'footer_copy_ecosystem_aria' => 'అదే ప్రాజెక్ట్‌లోని పేజీలు',
    'footer_copy_ecosystem_label' => 'అదే పర్యావరణంలో',
    'footer_copy_disclaimer' => 'ఈ విషయాలు విద్యా మరియు అవగాహన పెంపు కోసం; ఇవి వియత్నాం ప్రభుత్వ అధికారిక వైఖరిని ప్రత్యామ్నాయంగా భర్తీ చేయవు.',
    'footer_copy' => '<strong>© :year నైన్-డాష్ లైన్</strong> — లాభాపేక్షలేని <strong>పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు వియత్నాంకు చెందాయి</strong> ప్రాజెక్టులో的一భాగం, ఈ వ్యవస్థలో: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'పేజీ కంటెంట్ ప్రతిజ్ఞ',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 తీర్పు',
    'footer_chip3' => 'చారిత్రక ఆధారాలు',
    'footer_chip4' => 'పురాతన పటాలు',
    'footer_chip5' => 'వాస్తవిక సత్యం',
    'footer_chip6' => 'దక్షిణ చైనా సముద్రంలో శాంతి',
];
