<?php

return [
    'footer_index' => 'గ్రంథాలయం',
    'footer_crest_eyebrow' => 'గ్రంథాలయ సత్య సమాహారం',
    'footer_crest_quote' => '“దక్షిణ చైనా సముద్రంలో శాంతి యొక్క ఆధారం <b>అంతర్జాతీయ చట్టం</b> మీదే నిర్మించబడింది.”',
    'footer_crest_sub' => 'ద్వేషం కాదు · సత్యమే',
    'footer_nav_aria' => 'పేజీ దిగువ చర్యలు',
    'footer_btn_top' => 'పేజీ పైభాగానికి',
    'footer_btn_verdict' => 'PCA 2016 తీర్పు',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'నైన్-డాష్ లైన్',
    'footer_brand_body' => 'వాస్తవాధారిత, అంతర్జాతీయ చట్టం మరియు చారిత్రక పత్రాలపై ఆధారపడిన వివరణాత్మక సైట్ — ఆధారాలతో నైన్-డాష్ లైన్ దావాను ఖండిస్తుంది, నినాదాలతో కాదు.',
    'footer_refs_title' => 'సూచన మూలాలు',
    'footer_ref1' => 'PCA తీర్పు, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — సంపూర్ణ పాఠ్యం',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'చారిత్రక పత్రాలు & పురాతన పటాలు',
    'footer_toc_title' => 'పేజీ విషయ సూచిక',
    'footer_toc1' => 'నైన్-డాష్ లైన్ అంటే ఏమిటి',
    'footer_toc2' => 'మూలం',
    'footer_toc3' => 'ఎందుకు వివాదాస్పదం',
    'footer_toc4' => 'అంతర్జాతీయంగా ఎందుకు వ్యతిరేకత ఉంది',
    'footer_toc5' => 'నిశ్శబ్ద సాక్షులు',
    'footer_toc6' => 'PCA 2016 తీర్పు',
    'footer_toc7' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — దక్షిణ చైనా సముద్రంపై వాస్తవాధారిత సత్యం.<br>పర్యావరణ వ్యవస్థ: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'స్థానాంకాలు లేవు',
];
