<?php

return [
    'footer_index' => 'గ్రంథాలయం',
    'footer_crest_eyebrow' => 'సత్య గ్రంథాలయానికి ముగింపు',
    'footer_crest_quote' => '“దక్షిణ చైనా సముద్రంలో శాంతి <b>అంతర్జాతీయ చట్టం</b> పునాదిపై నిర్మించబడుతుంది.”',
    'footer_crest_sub' => 'ద్వేషం లేదు · సత్యమే',
    'footer_nav_aria' => 'పేజీ చివరి చర్యలు',
    'footer_btn_top' => 'పేజీ పైకి',
    'footer_btn_verdict' => 'PCA 2016 తీర్పు',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'నైన్-డాష్ లైన్‌పై హక్కు దావా',
    'footer_brand_eyebrow' => 'ప్రత్యేక అంశ పేజీ · వియత్నాం సార్వభౌమాధికారం',
    'footer_brand_body' => 'నైన్-డాష్ లైన్‌ను వాస్తవాలు, అంతర్జాతీయ చట్టం, PCA 2016 తీర్పు మరియు చారిత్రక పత్రాల ద్వారా వివరిస్తుంది — <strong>"పారాసెల్ దీవులు మరియు స్ప్రాట్లీ దీవులు"</strong> పై సార్వభౌమాధికారాన్ని లోతుగా వివరించే పేజీలకు తోడ్పాటు. చైనా యొక్క అవివేకపూరిత హక్కుదావాను చరిత్ర మరియు ఆధారాలతో ఖండిస్తుంది.',
    'footer_refs_title' => 'సూచన మూలాలు',
    'footer_ref1' => 'PCA తీర్పు, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — పూర్తి పాఠ్యం',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'చారిత్రక పత్రాలు & పురాతన పటాలు',
    'footer_toc_title' => 'పేజీ విషయసూచిక',
    'footer_toc1' => 'నైన్-డాష్ లైన్ అంటే ఏమిటి',
    'footer_toc2' => 'మూలం',
    'footer_toc3' => 'ఎందుకు వివాదాస్పదం',
    'footer_toc4' => 'అంతర్జాతీయంగా ఎందుకు వ్యతిరేకత',
    'footer_toc5' => 'నిశ్శబ్ద సాక్షులు',
    'footer_toc6' => 'PCA 2016 తీర్పు',
    'footer_toc7' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు',
    'footer_copy_eyebrow' => 'లాభాపేక్ష లేని ప్రాజెక్ట్',
    'footer_copy_title' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు వియత్నాంకు చెందినవి',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — వియత్నాం సార్వభౌమాధికార పర్యావరణ వ్యవస్థలో నైన్-డాష్ లైన్‌పై ప్రత్యేక పేజీ.',
    'footer_copy_body' => 'నైన్-డాష్ లైన్ హక్కుదావాను <strong>వాస్తవాలు</strong>, <strong>అంతర్జాతీయ చట్టం</strong>, PCA 2016 తీర్పు మరియు చారిత్రక పత్రాల ద్వారా వివరిస్తుంది — పారాసెల్ దీవులు మరియు స్ప్రాట్లీ దీవుల సార్వభౌమాధికారంపై లోతైన పేజీలకు తోడ్పాటు.',
    'footer_copy_ecosystem_aria' => 'అదే ప్రాజెక్ట్‌లోని పేజీలు',
    'footer_copy_ecosystem_label' => 'అదే పర్యావరణ వ్యవస్థ',
    'footer_copy_disclaimer' => 'ఈ విషయం విద్యా పరమైన అవగాహన కోసం మాత్రమే; వియత్నాం ప్రభుత్వ అధికారిక అభిప్రాయానికి ప్రత్యామ్నాయం కాదు.',
    'footer_copy' => '<strong>© :year నైన్-డాష్ లైన్</strong> — లాభాపేక్ష లేని <strong>పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు వియత్నాంకు చెందినవి</strong> ప్రాజెక్ట్‌లో భాగం, ఈ వ్యవస్థలో: <a href="https://paracelislands.net/te" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/te" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/te" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/te" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/te" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'పేజీ కంటెంట్ హామీ',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 తీర్పు',
    'footer_chip3' => 'చారిత్రక ఆధారాలు',
    'footer_chip4' => 'పురాతన పటాలు',
    'footer_chip5' => 'వాస్తవిక సత్యం',
    'footer_chip6' => 'దక్షిణ చైనా సముద్ర శాంతి',
];
