<?php

return [
    'nav_logo_name' => 'నైన్-డాష్ లైన్',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'నైన్-డాష్ లైన్',
    'nav_rail_aria' => 'విభాగాల వారీగా నావిగేషన్',
    'nav_rail_what' => 'నిర్వచనం',
    'nav_rail_origin' => 'ఉద్భవం',
    'nav_rail_dispute' => 'వివాదం',
    'nav_rail_opposition' => 'వ్యతిరేకత',
    'nav_rail_witnesses' => 'పురాతన పటాలు',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'పారాసెల్ దీవులు – స్ప్రాట్లీ దీవులు',
    'nav_sound_off' => 'నేపథ్య సంగీతాన్ని ఆన్ చేయండి',
    'nav_sound_on' => 'నేపథ్య సంగీతాన్ని ఆఫ్ చేయండి',
    'nav_share' => 'పంచుకోండి',
    'dialog_title' => 'ప్రదర్శన భాష',
    'language' => 'భాష',
    'display_hint' => ':count భాషలు',
    'search_placeholder' => 'భాషను శోధించండి…',
    'cancel' => 'రద్దు',
    'apply' => 'వర్తించు',
    'sound_off' => 'నేపథ్య ధ్వనిని ఆన్ చేయండి',
    'sound_on' => 'నేపథ్య ధ్వనిని ఆఫ్ చేయండి',
    'lang_trigger' => 'భాషను ఎంచుకోండి',
    'close' => 'మూసివేయి',
    'no_results' => 'భాష కనుగొనబడలేదు',
    'contribute' => 'పంచుకోండి',
];
