<?php

return [
    'footer_index' => 'المكتبة',
    'footer_crest_eyebrow' => 'ختام مكتبة الحقيقة',
    'footer_crest_quote' => '“يُبنى السلام في بحر الصين الجنوبي على أساس <b>القانون الدولي</b>.”',
    'footer_crest_sub' => 'لا كراهية · الحقيقة فقط',
    'footer_nav_aria' => 'إجراءات أسفل الصفحة',
    'footer_btn_top' => 'العودة إلى أعلى الصفحة',
    'footer_btn_verdict' => 'حكم هيئة التحكيم الدائمة 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ادعاء خط الشرطات التسع',
    'footer_brand_eyebrow' => 'صفحة موضوعية · سيادة فيتنام',
    'footer_brand_body' => 'شرح خط الشرطات التسع عبر الحقيقة الموضوعية، والقانون الدولي، وحكم هيئة التحكيم الدائمة 2016، والوثائق التاريخية — استكمالًا للصفحات المتخصصة في سيادة أرخبيلَي <strong>"جزر باراسيل وجزر سبراتلي"</strong>. دحض الادعاء غير المنطقي للصين بالتاريخ والأدلة.',
    'footer_refs_title' => 'المراجع',
    'footer_ref1' => 'حكم هيئة التحكيم الدائمة، 12/7/2016',
    'footer_ref2' => 'اتفاقية الأمم المتحدة لقانون البحار 1982 — النص الكامل',
    'footer_ref3' => 'الحدود في البحار №143 (وزارة الخارجية الأمريكية)',
    'footer_ref4' => 'وثائق تاريخية وخرائط قديمة',
    'footer_toc_title' => 'فهرس الصفحة',
    'footer_toc1' => 'ما هو خط الشرطات التسع',
    'footer_toc2' => 'الأصل',
    'footer_toc3' => 'لماذا يثير الجدل',
    'footer_toc4' => 'لماذا يعارضه المجتمع الدولي',
    'footer_toc5' => 'الشهود الصامتون',
    'footer_toc6' => 'حكم هيئة التحكيم الدائمة 2016',
    'footer_toc7' => 'جزر باراسيل – جزر سبراتلي',
    'footer_copy_eyebrow' => 'مشروع غير ربحي',
    'footer_copy_title' => 'جزر باراسيل – جزر سبراتلي جزء من فيتنام',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — صفحة موضوعية عن خط الشرطات التسع ضمن منظومة السيادة الخاصة بفيتنام.',
    'footer_copy_body' => 'شرح ادعاء خط الشرطات التسع عبر <strong>الحقيقة الموضوعية</strong>، و<strong>القانون الدولي</strong>، وحكم هيئة التحكيم الدائمة 2016، والوثائق التاريخية — استكمالًا للصفحات المتخصصة في سيادة أرخبيلَي جزر باراسيل وجزر سبراتلي.',
    'footer_copy_ecosystem_aria' => 'الصفحات التابعة للمشروع نفسه',
    'footer_copy_ecosystem_label' => 'ضمن المنظومة نفسها',
    'footer_copy_disclaimer' => 'المحتوى مخصص للتثقيف ورفع الوعي؛ ولا يحل محل الموقف الرسمي لدولة فيتنام.',
    'footer_copy' => '<strong>© :year خط الشرطات التسع</strong> — جزء من مشروع غير ربحي <strong>جزر باراسيل – جزر سبراتلي جزء من فيتنام</strong> ضمن المنظومة: <a href="https://paracelislands.net/ar" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ar" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ar" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ar" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ar" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'التزام محتوى الصفحة',
    'footer_chip1' => 'اتفاقية الأمم المتحدة لقانون البحار 1982',
    'footer_chip2' => 'حكم هيئة التحكيم الدائمة 2016',
    'footer_chip3' => 'أدلة تاريخية',
    'footer_chip4' => 'خرائط قديمة',
    'footer_chip5' => 'الحقيقة الموضوعية',
    'footer_chip6' => 'سلام بحر الصين الجنوبي',
];
