<?php

return [
    'footer_index' => 'المكتبة',
    'footer_crest_eyebrow' => 'ختام مكتبة الحقيقة',
    'footer_crest_quote' => '“يُبنى السلام في بحر الصين الجنوبي على أساس <b>القانون الدولي</b>.”',
    'footer_crest_sub' => 'لا كراهية · الحقيقة فقط',
    'footer_nav_aria' => 'إجراءات أسفل الصفحة',
    'footer_btn_top' => 'العودة إلى أعلى الصفحة',
    'footer_btn_verdict' => 'حكم PCA لعام 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'خط الشرطات التسع',
    'footer_brand_body' => 'موقع يشرح بالاستناد إلى الحقيقة الموضوعية والقانون الدولي والوثائق التاريخية — يفنّد ادعاء خط الشرطات التسع بالأدلة، لا بالشعارات.',
    'footer_refs_title' => 'المراجع',
    'footer_ref1' => 'حكم PCA، 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — النص الكامل',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'مواد تاريخية وخرائط قديمة',
    'footer_toc_title' => 'فهرس الصفحة',
    'footer_toc1' => 'ما هو خط الشرطات التسع',
    'footer_toc2' => 'الأصل',
    'footer_toc3' => 'لماذا يثير الجدل',
    'footer_toc4' => 'لماذا يعارضه المجتمع الدولي',
    'footer_toc5' => 'الشهود الصامتون',
    'footer_toc6' => 'حكم PCA لعام 2016',
    'footer_toc7' => 'جزر باراسيل – جزر سبراتلي',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — الحقيقة الموضوعية بشأن بحر الصين الجنوبي.<br>النظام البيئي: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'لا إحداثيات',
];
