<?php

return [
    'footer_index' => 'المكتبة',
    'footer_crest_eyebrow' => 'خاتمة مكتبة الحقيقة',
    'footer_crest_quote' => '«يُبنى السلام في بحر الصين الجنوبي على أساس <b>القانون الدولي</b>.»',
    'footer_crest_sub' => 'لا للكراهية · الحقيقة فقط',
    'footer_nav_aria' => 'إجراءات أسفل الصفحة',
    'footer_btn_top' => 'إلى أعلى الصفحة',
    'footer_btn_verdict' => 'حكم محكمة التحكيم الدائمة 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'المطالبة بخط الشرطات التسع',
    'footer_brand_eyebrow' => 'صفحة متخصصة · سيادة فيتنام',
    'footer_brand_body' => 'شرح خط الشرطات التسع عبر الحقيقة الموضوعية، والقانون الدولي، وحكم محكمة التحكيم الدائمة 2016، والمواد التاريخية — مكمّلٌ للصفحات المتخصصة في سيادة الأرخبيلين <strong>"جزر باراسيل وجزر سبراتلي"</strong>. دحض المطالبات غير المنطقية للصين بالتاريخ والأدلة.',
    'footer_refs_title' => 'المراجع',
    'footer_ref1' => 'حكم محكمة التحكيم الدائمة، 12/7/2016',
    'footer_ref2' => 'اتفاقية الأمم المتحدة لقانون البحار 1982 — النص الكامل',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'مواد تاريخية وخرائط قديمة',
    'footer_toc_title' => 'فهرس الصفحة',
    'footer_toc1' => 'ما هو خط الشرطات التسع',
    'footer_toc2' => 'الأصل',
    'footer_toc3' => 'لماذا يثير الجدل',
    'footer_toc4' => 'لماذا يعارضه المجتمع الدولي',
    'footer_toc5' => 'شهود صامتون',
    'footer_toc6' => 'حكم محكمة التحكيم الدائمة 2016',
    'footer_toc7' => 'جزر باراسيل – جزر سبراتلي',
    'footer_copy_eyebrow' => 'مشروع غير ربحي',
    'footer_copy_title' => 'جزر باراسيل – جزر سبراتلي هي من فيتنام',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — صفحة متخصصة عن خط الشرطات التسع ضمن منظومة سيادة فيتنام.',
    'footer_copy_body' => 'شرح مطالبة خط الشرطات التسع عبر <strong>الحقيقة الموضوعية</strong>، <strong>القانون الدولي</strong>، وحكم محكمة التحكيم الدائمة 2016 والمواد التاريخية — مكمّلٌ للصفحات المتخصصة في سيادة أرخبيلَي جزر باراسيل وجزر سبراتلي.',
    'footer_copy_ecosystem_aria' => 'الصفحات ضمن المشروع نفسه',
    'footer_copy_ecosystem_label' => 'ضمن المنظومة ذاتها',
    'footer_copy_disclaimer' => 'المحتوى مخصص للتثقيف ورفع الوعي؛ ولا يحل محل الموقف الرسمي لدولة فيتنام.',
    'footer_copy' => '<strong>© :year خط الشرطات التسع</strong> — جزء من مشروع غير ربحي <strong>جزر باراسيل – جزر سبراتلي هي من فيتنام</strong> ضمن النظام: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'التزام محتوى الصفحة',
    'footer_chip1' => 'اتفاقية الأمم المتحدة لقانون البحار 1982',
    'footer_chip2' => 'حكم محكمة التحكيم الدائمة 2016',
    'footer_chip3' => 'أدلة تاريخية',
    'footer_chip4' => 'خرائط قديمة',
    'footer_chip5' => 'الحقيقة الموضوعية',
    'footer_chip6' => 'سلام بحر الصين الجنوبي',
];
