<?php

return [
    'nav_logo_name' => 'خط الشرطات التسع',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'خط الشرطات التسع',
    'nav_rail_aria' => 'التنقل حسب القسم',
    'nav_rail_what' => 'التعريف',
    'nav_rail_origin' => 'الأصل',
    'nav_rail_dispute' => 'الجدل',
    'nav_rail_opposition' => 'الاعتراض',
    'nav_rail_witnesses' => 'الخرائط القديمة',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'جزر باراسيل - جزر سبراتلي',
    'nav_sound_off' => 'تشغيل الموسيقى الخلفية',
    'nav_sound_on' => 'إيقاف الموسيقى الخلفية',
    'nav_share' => 'مشاركة',
    'dialog_title' => 'لغة العرض',
    'language' => 'اللغة',
    'display_hint' => ':count لغة',
    'search_placeholder' => 'ابحث عن لغة…',
    'cancel' => 'إلغاء',
    'apply' => 'تطبيق',
    'sound_off' => 'تشغيل الصوت الخلفي',
    'sound_on' => 'إيقاف الصوت الخلفي',
    'lang_trigger' => 'اختر اللغة',
    'close' => 'إغلاق',
    'no_results' => 'لم يتم العثور على لغة',
    'contribute' => 'مشاركة',
];
