<?php

return [
    'footer_index' => 'ห้องสมุด',
    'footer_crest_eyebrow' => 'ปิดท้ายห้องสมุดแห่งความจริง',
    'footer_crest_quote' => '“สันติภาพในทะเลจีนใต้ตั้งอยู่บนรากฐานของ <b>กฎหมายระหว่างประเทศ</b>.”',
    'footer_crest_sub' => 'ไม่มีความเกลียดชัง · มีเพียงความจริง',
    'footer_nav_aria' => 'การดำเนินการท้ายหน้า',
    'footer_btn_top' => 'กลับไปด้านบน',
    'footer_btn_verdict' => 'คำชี้ขาด PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ข้ออ้างเส้นประเก้าเส้น',
    'footer_brand_eyebrow' => 'หน้าหัวข้อพิเศษ · อธิปไตยของเวียดนาม',
    'footer_brand_body' => 'อธิบายเส้นประเก้าเส้นผ่านความจริงเชิงประจักษ์ กฎหมายระหว่างประเทศ คำชี้ขาด PCA 2016 และเอกสารประวัติศาสตร์ — เสริมให้กับหน้าที่เจาะลึกเรื่องอธิปไตยของสองหมู่เกาะ <strong>"หมู่เกาะพาราเซลและหมู่เกาะสแปรตลี"</strong> หักล้างข้ออ้างอันไร้เหตุผลของจีนด้วยประวัติศาสตร์และหลักฐาน',
    'footer_refs_title' => 'แหล่งอ้างอิง',
    'footer_ref1' => 'คำชี้ขาด PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — ฉบับเต็ม',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'เอกสารประวัติศาสตร์ & แผนที่โบราณ',
    'footer_toc_title' => 'สารบัญหน้า',
    'footer_toc1' => 'เส้นประเก้าเส้นคืออะไร',
    'footer_toc2' => 'ที่มา',
    'footer_toc3' => 'เหตุใดจึงเป็นข้อพิพาท',
    'footer_toc4' => 'เหตุใดนานาชาติจึงคัดค้าน',
    'footer_toc5' => 'พยานเงียบ',
    'footer_toc6' => 'คำชี้ขาด PCA 2016',
    'footer_toc7' => 'หมู่เกาะพาราเซล – หมู่เกาะสแปรตลี',
    'footer_copy_eyebrow' => 'โครงการไม่แสวงหากำไร',
    'footer_copy_title' => 'หมู่เกาะพาราเซล – หมู่เกาะสแปรตลีเป็นของเวียดนาม',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — หน้าหัวข้อพิเศษเกี่ยวกับเส้นประเก้าเส้นในระบบนิเวศด้านอธิปไตยของเวียดนาม.',
    'footer_copy_body' => 'อธิบายข้ออ้างเส้นประเก้าเส้นผ่าน <strong>ความจริงเชิงประจักษ์</strong>, <strong>กฎหมายระหว่างประเทศ</strong>, คำชี้ขาด PCA 2016 และเอกสารประวัติศาสตร์ — เสริมให้กับหน้าที่เจาะลึกเรื่องอธิปไตยของสองหมู่เกาะพาราเซลและสแปรตลี.',
    'footer_copy_ecosystem_aria' => 'หน้าเว็บในโครงการเดียวกัน',
    'footer_copy_ecosystem_label' => 'ในระบบนิเวศเดียวกัน',
    'footer_copy_disclaimer' => 'เนื้อหามีวัตถุประสงค์เพื่อการศึกษาและสร้างความตระหนักรู้; ไม่ได้ทดแทนจุดยืนอย่างเป็นทางการของรัฐเวียดนาม.',
    'footer_copy' => '<strong>© :year เส้นประเก้าเส้น</strong> — ส่วนหนึ่งของโครงการไม่แสวงหากำไร <strong>หมู่เกาะพาราเซล – หมู่เกาะสแปรตลีเป็นของเวียดนาม</strong> ภายใต้ระบบ: <a href="https://paracelislands.net/th" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/th" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/th" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/th" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/th" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'คำมั่นสัญญาด้านเนื้อหาของหน้า',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'คำชี้ขาด PCA 2016',
    'footer_chip3' => 'หลักฐานทางประวัติศาสตร์',
    'footer_chip4' => 'แผนที่โบราณ',
    'footer_chip5' => 'ความจริงเชิงประจักษ์',
    'footer_chip6' => 'สันติภาพในทะเลจีนใต้',
];
