<?php

return [
    'footer_index' => 'ห้องสมุด',
    'footer_crest_eyebrow' => 'ปิดท้ายด้วยห้องสมุดแห่งความจริง',
    'footer_crest_quote' => '“สันติภาพในทะเลจีนใต้ตั้งอยู่บนรากฐานของ <b>กฎหมายระหว่างประเทศ</b>.”',
    'footer_crest_sub' => 'ไม่มีความเกลียดชัง · มีแต่ความจริง',
    'footer_nav_aria' => 'การดำเนินการท้ายหน้า',
    'footer_btn_top' => 'กลับสู่ด้านบน',
    'footer_btn_verdict' => 'คำตัดสิน PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'เส้นประเก้าเส้น',
    'footer_brand_body' => 'หน้าเว็บอธิบายที่ยึดตามข้อเท็จจริงอย่างเป็นกลาง กฎหมายระหว่างประเทศ และเอกสารประวัติศาสตร์ — โต้แย้งข้ออ้างเกี่ยวกับเส้นประเก้าเส้นด้วยหลักฐาน ไม่ใช่ด้วยคำขวัญ',
    'footer_refs_title' => 'แหล่งอ้างอิง',
    'footer_ref1' => 'คำตัดสิน PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — ฉบับเต็ม',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'เอกสารประวัติศาสตร์และแผนที่โบราณ',
    'footer_toc_title' => 'สารบัญของหน้า',
    'footer_toc1' => 'เส้นประเก้าเส้นคืออะไร',
    'footer_toc2' => 'ที่มา',
    'footer_toc3' => 'เหตุใดจึงเป็นข้อพิพาท',
    'footer_toc4' => 'เหตุใดนานาชาติจึงคัดค้าน',
    'footer_toc5' => 'พยานเงียบ',
    'footer_toc6' => 'คำตัดสิน PCA 2016',
    'footer_toc7' => 'หมู่เกาะพาราเซล - หมู่เกาะสแปรตลี',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — ความจริงอย่างเป็นกลางเกี่ยวกับทะเลจีนใต้.<br>ระบบนิเวศ: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'ไม่มีพิกัด',
];
