<?php

return [
    'nav_logo_name' => 'เส้นประเก้าเส้น',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'เส้นประเก้าเส้น',
    'nav_rail_aria' => 'การนำทางตามหัวข้อ',
    'nav_rail_what' => 'คำนิยาม',
    'nav_rail_origin' => 'ที่มา',
    'nav_rail_dispute' => 'ข้อพิพาท',
    'nav_rail_opposition' => 'การคัดค้าน',
    'nav_rail_witnesses' => 'แผนที่โบราณ',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'หมู่เกาะพาราเซล - หมู่เกาะสแปรตลี',
    'nav_sound_off' => 'เปิดเพลงพื้นหลัง',
    'nav_sound_on' => 'ปิดเพลงพื้นหลัง',
    'nav_share' => 'แชร์',
    'dialog_title' => 'ภาษาที่แสดง',
    'language' => 'ภาษา',
    'display_hint' => ':count ภาษา',
    'search_placeholder' => 'ค้นหาภาษา…',
    'cancel' => 'ยกเลิก',
    'apply' => 'นำไปใช้',
    'sound_off' => 'เปิดเสียงพื้นหลัง',
    'sound_on' => 'ปิดเสียงพื้นหลัง',
    'lang_trigger' => 'เลือกภาษา',
    'close' => 'ปิด',
    'no_results' => 'ไม่พบภาษา',
    'contribute' => 'แบ่งปัน',
];
