<?php

return [
    'witnesses_index' => 'แผนที่โบราณ',
    'witnesses_label' => 'แผนที่โบราณของจีน',
    'witnesses_title' => 'จุดใต้สุดได้เพียง',
    'witnesses_title_accent' => 'เกาะไหหนำ',
    'witnesses_lead' => 'แผนที่โบราณที่ผู้เขียนชาวจีนวาดขึ้น — จัดเรียงตามลำดับเวลา — ล้วนแสดงให้เห็นว่า <em>เกาะไหหนำเป็นจุดใต้สุด</em>ของจีน โดยไม่มีหมู่เกาะพาราเซลหรือหมู่เกาะสแปรตลี ข้อมูลรวบรวมตาม <em>อธิปไตยของชาติเวียดนามต่อหมู่เกาะพาราเซลและหมู่เกาะสแปรตลี</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ ส่องด้วยแว่นขยาย',
    'witnesses_map1_svg_hainan' => 'ไห่หนาน 海南',
    'witnesses_map1_svg_south' => '— จุดใต้สุดของดินแดน —',
    'witnesses_map1_svg_era' => 'ราชวงศ์ซ่ง · 1136',
    'witnesses_map1_title' => 'แผนที่ราชวงศ์ซ่ง, 1136',
    'witnesses_map1_body' => 'ดินแดนจีนสิ้นสุดที่เกาะไห่หนาน — หมู่เกาะพาราเซลและหมู่เกาะสแปรตลีอยู่นอกอาณาเขต',
    'witnesses_map2_svg_hainan' => 'ไห่หนาน',
    'witnesses_map2_svg_south' => 'ขอบเขตของ d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'แผนที่ของ d\'Anville, 1735',
    'witnesses_map2_body' => 'จัดทำโดย J.-B. B. d\'Anville; สำเนาปี 1740 เคยมอบให้ผู้นำจีนโดยนายกรัฐมนตรีเยอรมนี ดินแดนราชวงศ์ชิงสิ้นสุดที่ไห่หนาน',
    'witnesses_map3_svg_hainan' => '海南 ไห่หนาน',
    'witnesses_map3_svg_south' => '"จุดใต้สุดของจีน"',
    'witnesses_map3_svg_era' => 'แผนที่บูรพาแห่งราชสำนัก · 1904',
    'witnesses_map3_title' => 'แผนที่ภูมิศาสตร์ครบถ้วนของมณฑลในราชสำนัก',
    'witnesses_map3_body' => 'พิมพ์โดยราชวงศ์ชิง — ระบุชัดว่าจุดใต้สุดของดินแดนจีนคือเกาะไห่หนาน',
    'witnesses_quote' => 'แม้แต่แผนที่จีนที่เคยเผยแพร่เองก็ไม่เคยวาดหมู่เกาะพาราเซล — หมู่เกาะสแปรตลีไว้ในดินแดนของตน',
    'witnesses_timeline_aria' => 'ลำดับเวลาแผนที่โบราณของจีน',
    'witnesses_year_aria' => '年代',
    'lightbox_aria' => 'ดูภาพขยาย',
    'lightbox_close' => 'ปิด',
    'lightbox_prev' => 'ภาพก่อนหน้า',
    'lightbox_next' => 'ภาพถัดไป',
];
