<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Afslutning på sandhedens bibliotek',
    'footer_crest_quote' => '“Fred i Det Sydkinesiske Hav er bygget på fundamentet af <b>folkeretten</b>.”',
    'footer_crest_sub' => 'Intet had · Kun sandhed',
    'footer_nav_aria' => 'Handlinger i sidefoden',
    'footer_btn_top' => 'Tilbage til toppen',
    'footer_btn_verdict' => 'PCA-afgørelsen 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Ni-streglinjen',
    'footer_brand_body' => 'Et forklarende site baseret på objektive fakta, folkeret og historiske kilder — som afviser Ni-streglinjens krav med beviser, ikke slagord.',
    'footer_refs_title' => 'Kilder',
    'footer_ref1' => 'PCA-afgørelsen, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — fuld tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiske kilder og gamle kort',
    'footer_toc_title' => 'Sidens indholdsfortegnelse',
    'footer_toc1' => 'Hvad er Ni-streglinjen',
    'footer_toc2' => 'Oprindelse',
    'footer_toc3' => 'Hvorfor det er kontroversielt',
    'footer_toc4' => 'Hvorfor det internationale samfund er imod',
    'footer_toc5' => 'Stumme vidner',
    'footer_toc6' => 'PCA-afgørelsen 2016',
    'footer_toc7' => 'Paraceløerne – Spratlyøerne',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektiv sandhed om Det Sydkinesiske Hav.<br>Økosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Ingen koordinater',
];
