<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Afslutning på sandhedens bibliotek',
    'footer_crest_quote' => '“Freden i Det Sydkinesiske Hav er bygget på fundamentet af <b>international ret</b>.”',
    'footer_crest_sub' => 'Intet had · Kun sandhed',
    'footer_nav_aria' => 'Handlinger i sidefoden',
    'footer_btn_top' => 'Til toppen',
    'footer_btn_verdict' => 'PCA-kendelse 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Krav på Ni-streglinjen',
    'footer_brand_eyebrow' => 'Tema-side · Vietnams suverænitet',
    'footer_brand_body' => 'En forklaring af Ni-streglinjen gennem objektive fakta, international ret, PCA-kendelsen fra 2016 og historiske kilder — som supplement til de dybdegående sider om suveræniteten over de to øgrupper <strong>"Paraceløerne og Spratlyøerne"</strong>. En afvisning af Kinas urimelige krav gennem historie og beviser.',
    'footer_refs_title' => 'Referencer',
    'footer_ref1' => 'PCA-kendelsen, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — fuld tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiske kilder og gamle kort',
    'footer_toc_title' => 'Sidens indholdsfortegnelse',
    'footer_toc1' => 'Hvad er Ni-streglinjen',
    'footer_toc2' => 'Oprindelse',
    'footer_toc3' => 'Hvorfor den er omstridt',
    'footer_toc4' => 'Hvorfor den internationale verden afviser den',
    'footer_toc5' => 'Stille vidner',
    'footer_toc6' => 'PCA-kendelsen 2016',
    'footer_toc7' => 'Paraceløerne – Spratlyøerne',
    'footer_copy_eyebrow' => 'Ikke-kommercielt projekt',
    'footer_copy_title' => 'Paraceløerne – Spratlyøerne tilhører Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — En temaside om Ni-streglinjen i Vietnams suverænitetsøkosystem.',
    'footer_copy_body' => 'En forklaring af kravet om Ni-streglinjen gennem <strong>objektive fakta</strong>, <strong>international ret</strong>, PCA-kendelsen fra 2016 og historiske kilder — som supplement til de dybdegående sider om suveræniteten over Paraceløerne og Spratlyøerne.',
    'footer_copy_ecosystem_aria' => 'Sider i samme projekt',
    'footer_copy_ecosystem_label' => 'Samme økosystem',
    'footer_copy_disclaimer' => 'Indholdet er til undervisning og oplysning; det erstatter ikke Den Socialistiske Republik Vietnams officielle موقف.',
    'footer_copy' => '<strong>© :year Ni-streglinjen</strong> — En del af det ikke-kommercielle projekt <strong>Paraceløerne – Spratlyøerne tilhører Vietnam</strong> i systemet: <a href="https://paracelislands.net/da" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/da" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/da" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/da" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/da" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sidens indholdsløfte',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-kendelsen 2016',
    'footer_chip3' => 'Historiske beviser',
    'footer_chip4' => 'Gamle kort',
    'footer_chip5' => 'Objektiv sandhed',
    'footer_chip6' => 'Fred i Det Sydkinesiske Hav',
];
