<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Afslutning af sandhedens bibliotek',
    'footer_crest_quote' => '“Freden i Det Sydkinesiske Hav er bygget på fundamentet af <b>international ret</b>.”',
    'footer_crest_sub' => 'Intet had · Kun sandheden',
    'footer_nav_aria' => 'Handlinger i sidefoden',
    'footer_btn_top' => 'Til toppen',
    'footer_btn_verdict' => 'PCA-kenkendelsen 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Krav om Ni-streglinjen',
    'footer_brand_eyebrow' => 'Temaside · Vietnams suverænitet',
    'footer_brand_body' => 'Forklaring af Ni-streglinjen gennem objektive fakta, international ret, PCA-kenkendelsen 2016 og historiske kilder — som supplement til de dybdegående sider om suveræniteten over de to øgrupper <strong>"Paraceløerne og Spratlyøerne"</strong>. Afviser Kinas urimelige krav med historie og beviser.',
    'footer_refs_title' => 'Kilder',
    'footer_ref1' => 'PCA-kenkendelsen, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — fuld tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiske kilder & gamle kort',
    'footer_toc_title' => 'Sidens indholdsfortegnelse',
    'footer_toc1' => 'Hvad er Ni-streglinjen',
    'footer_toc2' => 'Oprindelse',
    'footer_toc3' => 'Hvorfor er det kontroversielt',
    'footer_toc4' => 'Hvorfor det internationale samfund afviser det',
    'footer_toc5' => 'Tavse vidner',
    'footer_toc6' => 'PCA-kenkendelsen 2016',
    'footer_toc7' => 'Paraceløerne – Spratlyøerne',
    'footer_copy_eyebrow' => 'Ikke-kommercielt projekt',
    'footer_copy_title' => 'Paraceløerne – Spratlyøerne tilhører Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Temaside om Ni-streglinjen i Vietnams suverænitets-økosystem.',
    'footer_copy_body' => 'Forklaring af Ni-streglinjens krav gennem <strong>objektive fakta</strong>, <strong>international ret</strong>, PCA-kenkendelsen 2016 og historiske kilder — som supplement til de dybdegående sider om suveræniteten over øgrupperne Paraceløerne og Spratlyøerne.',
    'footer_copy_ecosystem_aria' => 'Andre sider i projektet',
    'footer_copy_ecosystem_label' => 'Samme økosystem',
    'footer_copy_disclaimer' => 'Indholdet er til undervisning og oplysning; det erstatter ikke Den Socialistiske Republik Vietnams officielle holdning.',
    'footer_copy' => '<strong>© :year Ni-streglinjen</strong> — En del af det ikke-kommercielle projekt <strong>Paraceløerne – Spratlyøerne tilhører Vietnam</strong> i systemet: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Forpligtelser for sidens indhold',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-kenkendelsen 2016',
    'footer_chip3' => 'Historiske beviser',
    'footer_chip4' => 'Gamle kort',
    'footer_chip5' => 'Objektive fakta',
    'footer_chip6' => 'Fred i Det Sydkinesiske Hav',
];
