<?php

return [
    'nav_logo_name' => 'Ni-streglinjen',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Ni-streglinjen',
    'nav_rail_aria' => 'Navigation efter sektion',
    'nav_rail_what' => 'Definition',
    'nav_rail_origin' => 'Oprindelse',
    'nav_rail_dispute' => 'Stridigheder',
    'nav_rail_opposition' => 'Modstand',
    'nav_rail_witnesses' => 'Gamle kort',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paraceløerne - Spratlyøerne',
    'nav_sound_off' => 'Slå baggrundsmusik til',
    'nav_sound_on' => 'Slå baggrundsmusik fra',
    'nav_share' => 'Del',
    'dialog_title' => 'Visningssprog',
    'language' => 'Sprog',
    'display_hint' => ':count sprog',
    'search_placeholder' => 'Søg efter sprog…',
    'cancel' => 'Annuller',
    'apply' => 'Anvend',
    'sound_off' => 'Slå baggrundslyd til',
    'sound_on' => 'Slå baggrundslyd fra',
    'lang_trigger' => 'Vælg sprog',
    'close' => 'Luk',
    'no_results' => 'Ingen sprog fundet',
    'contribute' => 'Del',
];
