<?php

return [
    'opposition_index' => 'Opposition',
    'opposition_label' => 'Hvorfor det internationale samfund gør modstand',
    'opposition_title' => 'Modstanden bygger på',
    'opposition_title_accent' => 'lov, ikke følelser',
    'opposition_lead' => 'Kort efter at Ni-streglinjen blev forelagt FN i 2009, protesterede mange lande og forskere — med konkrete juridiske argumenter.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maj',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesien',
    'opposition_voice1_body' => 'Allerede dagen efter, at Kina indgav kortet over Ni-streglinjen til FN’s generalsekretær (7/5/2009), sendte disse lande hver især diplomatiske noter med protest og afviste kravet.',
    'opposition_voice1_chip1' => 'Protestnote',
    'opposition_voice1_chip2' => 'Ikke i overensstemmelse med UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippinerne',
    'opposition_voice2_body' => 'Sendte et diplomatisk brev til FN og erklærede, at Kinas krav i Det Sydkinesiske Hav var “uden grundlag i folkeretten” — et forstadium til den senere voldgiftssag.',
    'opposition_voice2_chip1' => 'Grundlag for PCA-sagen',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'USA’s udenrigsministerium — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analysen påpegede: kort fra forskellige år viste uoverensstemmelser i linjens placering; linjen trængte ind over fastlandet i stedet for at følge midtlinjen; og flere havformationer opfyldte ikke kriterierne for en “ø” med EEZ.',
    'opposition_voice3_chip1' => 'Opfylder ikke de juridiske kriterier',
    'opposition_voice3_chip2' => 'Officiel analyse',
    'opposition_voice4_year' => 'Akademisk',
    'opposition_voice4_title' => '“Historiske farvande” er forældet',
    'opposition_voice4_body' => 'Dette begreb gælder kun for bugter og kystnære vandområder — det kan ikke omfatte et helt stort åbent havområde. I 2003 afviste Taiwan selv den politik om “historiske farvande”, som man havde fremsat i 1993.',
    'opposition_voice4_chip1' => 'Selv kinesiske forskere er ikke enige',
];
