<?php

return [
    'sovereignty_index' => 'Paraceløerne – Spratlyøerne',
    'sovereignty_label' => 'Den uundgåelige konklusion',
    'sovereignty_title' => 'Paraceløerne – Spratlyøerne',
    'sovereignty_title_accent' => 'tilhører Vietnam',
    'sovereignty_lead' => 'Denne side forklarer Ni-streglinjen. Afslutningen besvarer det næste spørgsmål: hvem har suverænitet over de to øgrupper Paraceløerne og Spratlyøerne? Ifølge historisk forvaltning og folkeretten er det konsekvent Vietnam.',
    'sovereignty_thesis_label' => 'Samlet argument',
    'sovereignty_thesis_lock1' => 'Ingen juridisk geografi',
    'sovereignty_thesis_lock2' => 'PCA 2016 afviste den',
    'sovereignty_thesis_lock3' => 'Gamle kort dækker ikke',
    'sovereignty_thesis_body' => 'Efter de seks punkter ovenfor står tre ting klart: Ni-streglinjen er tegnet i hånden og har ingen juridisk geografi; Voldgiftsretten i 2016 afviste kravet; og Kinas egne gamle kort dækker ikke Det Sydkinesiske Hav. Vietnams suverænitet bygger ikke på slogans, men på, at den vietnamesiske stat — fra Nguyễn-dynastiets tid — har forvaltet området fredeligt og kontinuerligt, mens de to øgrupper endnu var terra nullius.',
    'sovereignty_spine_caption' => 'Kontinuerlige forvaltningspunkter',
    'sovereignty_spine_title' => 'En tidslinje uden afbrydelser',
    'sovereignty_spine_range' => '17. århundrede → nu',
    'sovereignty_chron1_year' => '17. årh.',
    'sovereignty_chron1_title' => 'Hoàng Sa-holdet',
    'sovereignty_chron1_body' => 'Nguyễn-herskerne sendte Hoàng Sa-holdet ud for at undersøge, opmåle sejlruter og udnytte ressourcer til søs — udøvelse af faktisk forvaltning.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kejser Gia Long',
    'sovereignty_chron2_body' => 'Han hejste flaget på Paraceløerne og bekræftede Vietnams suverænitet over for samtiden.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kejser Minh Mạng',
    'sovereignty_chron3_body' => 'Området blev opmålt, der blev rejst steler, og øerne blev indført på hoffets officielle kort.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuerlig arv',
    'sovereignty_chron4_body' => 'Frankrig anerkendte og fortsatte forvaltningen; Paraceløerne blev indlemmet i Thừa Thiên-provinsen — et grundlag for den nuværende vietnamesiske stat.',
    'sovereignty_chron5_year' => 'I dag',
    'sovereignty_chron5_title' => 'Lov og praksis',
    'sovereignty_chron5_body' => 'Vietnam forvalter i overensstemmelse med UNCLOS, diplomati og arkivmateriale; kravet fra Ni-streglinjen kan ikke erstatte dette bevis.',
    'sovereignty_balance_label' => 'Bevisbalance',
    'sovereignty_balance_medallion_title' => 'Sammenligning af to sider',
    'sovereignty_vn_tag' => 'Den vietnamesiske side',
    'sovereignty_vn_title' => 'Suverænitet etableret gennem handling',
    'sovereignty_vn_body' => 'Effektiv besiddelse, da området endnu var terra nullius, efterfulgt af offentlig forvaltning gennem flere århundreder — med kejserlige dokumenter, steler, kort og administrative arkiver. Denne praksis er i overensstemmelse med UNCLOS og international sædvane.',
    'sovereignty_dash_tag' => 'Ni-streglinjens side',
    'sovereignty_dash_title' => 'Et krav kan ikke opveje bevis',
    'sovereignty_dash_body' => 'En linje tegnet i 1948 uden koordinater blev afvist af PCA i 2016 og er i strid med UNCLOS — som vist i afsnit 03 til 06. Derfor kan konklusionen om de to øgruppers suverænitet ikke bygge på Ni-streglinjen.',
    'sovereignty_seal_quote' => 'Vietnam løser tvister ved <strong>fredelige midler</strong> på grundlag af folkeretten — især UNCLOS 1982 — med henblik på et fredeligt, samarbejdende og udviklende Sydkinesisk Hav.',
    'sovereignty_seal_cite' => 'Vietnams holdning · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hovedprojektet i det samme økosystem',
    'sovereignty_next_title' => 'Læs det fulde bevismateriale om Paraceløerne – Spratlyøerne',
    'sovereignty_next_body' => 'Det detaljerede dossier — dokumenter, kort, tidslinjer og juridiske argumenter — findes på siden <strong>paracelislands.net</strong>, hvor emnet om de to øgruppers suverænitet gennemgås samlet. Den side, du læser nu, forbinder blot logikken fra Ni-streglinjen til denne konklusion.',
    'sovereignty_next_cta' => 'Åbn paracelislands.net',
];
