<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'International dom',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'de tre "Nej"',
    'verdict_lead' => 'Den 12. juli 2016 afsagde Den Faste Voldgiftsret (PCA) i Haag — nedsat i henhold til bilag VII til UNCLOS, i sagen mellem Filippinerne og Kina — en kendelse, der afviste kravene om Ni-streglinjen. <em>Klik på hvert kort for at læse den fulde tekst.</em>',
    'verdict_card1_khong' => 'NEJ',
    'verdict_card1_title' => 'historiske rettigheder',
    'verdict_card1_short' => 'Der er intet juridisk grundlag for, at Kina kan gøre historiske rettigheder gældende over ressourcerne i farvande inden for Ni-streglinjen.',
    'verdict_card1_quote' => '“Der er intet juridisk grundlag for, at Kina kan gøre historiske rettigheder gældende over ressourcerne i farvande inden for Ni-streglinjen.”',
    'verdict_card1_more' => '+ Læs kendelsen',
    'verdict_card2_khong' => 'NEJ',
    'verdict_card2_title' => 'dannelse af EEZ',
    'verdict_card2_short' => 'Ingen af øerne i Spratlyøerne opfylder betingelserne for at skabe en eksklusiv økonomisk zone for Kina — heller ikke Ba Bình-øen.',
    'verdict_card2_quote' => '“Ingen af øerne i Spratlyøerne er i stand til at skabe en eksklusiv økonomisk zone.”',
    'verdict_card2_more' => '+ Læs kendelsen',
    'verdict_card3_khong' => 'NEJ',
    'verdict_card3_title' => 'lovlig adfærd',
    'verdict_card3_short' => 'Kina krænkede Filippinernes suveræne rettigheder, forhindrede fiskeri og skadede havmiljøet.',
    'verdict_card3_quote' => '“Kina har krænket Filippinernes suveræne rettigheder, blandet sig i fiskeriaktiviteter ved Scarborough-revet og forårsaget alvorlig skade på koralrevsmiljøet.”',
    'verdict_card3_more' => '+ Læs kendelsen',
    'verdict_extra1' => 'Ni-streglinjen, som Kina selv har tegnet, er <strong>ikke i overensstemmelse</strong> med UNCLOS 1982.',
    'verdict_extra2' => 'Kina har forårsaget skade på Spratlyøernes økosystem gennem overudnyttelse og opbygning af kunstige øer.',
    'verdict_extra3' => 'Kinas handlinger har øget risikoen for konflikt med Filippinerne.',
    'verdict_extra4' => 'Ba Bình-øen (kontrolleret af Taiwan) kan heller ikke skabe en EEZ.',
    'verdict_subtitle' => 'Hvorfor er den i konflikt med UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 afgrænser klart havområderne ud fra kyststatens basislinje. Kravet om Ni-streglinjen ligger uden for denne ramme og kan derfor ikke forenes med den.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialfarvand (sømil)',
    'verdict_zone1_body' => 'Statens farvand med suverænitet, målt fra basislinjen.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusiv økonomisk zone',
    'verdict_zone2_body' => 'EEZ — kyststaten har suveræne rettigheder til ressourcer inden for dette område.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalsokkel (maks., sømil)',
    'verdict_zone3_body' => 'Rettigheder til havbundens ressourcer, fastlagt efter geologiske betingelser.',
    'verdict_foot' => 'I denne ramme er “historiske rettigheder” over et helt åbent havområde — som Ni-streglinjen antyder — <em>blevet erstattet</em> af UNCLOS’ retlige regime, som også Kina er part i.',
];
