<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'International afgørelse',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tre "Nej"',
    'verdict_lead' => 'Den 12. juli 2016 afsagde Den Permanente Voldgiftsret (PCA) i Haag — oprettet i henhold til bilag VII til UNCLOS, i sagen mellem Filippinerne og Kina — en kendelse, der afviste kravet om Ni-streglinjen. <em>Klik på hvert kort for at læse den fulde tekst.</em>',
    'verdict_card1_khong' => 'NEJ',
    'verdict_card1_title' => 'historisk ret',
    'verdict_card1_short' => 'Der er intet juridisk grundlag for, at Kina kan gøre krav på historiske rettigheder til ressourcer i havområdet inden for Ni-streglinjen.',
    'verdict_card1_quote' => '“Der er intet juridisk grundlag for, at Kina kan gøre krav på historiske rettigheder til ressourcerne i havområdet inden for Ni-streglinjen.”',
    'verdict_card1_more' => '+ Læs afgørelsen',
    'verdict_card2_khong' => 'NEJ',
    'verdict_card2_title' => 'enhed, der skaber EEZ',
    'verdict_card2_short' => 'Ingen af enhederne i Spratlyøerne opfylder betingelserne for at skabe en eksklusiv økonomisk zone for Kina — heller ikke Ba Bình-øen.',
    'verdict_card2_quote' => '“Ingen af enhederne i Spratlyøerne er i stand til at skabe en eksklusiv økonomisk zone.”',
    'verdict_card2_more' => '+ Læs afgørelsen',
    'verdict_card3_khong' => 'NEJ',
    'verdict_card3_title' => 'lovlig adfærd',
    'verdict_card3_short' => 'Kina krænkede Filippinernes suveræne rettigheder, forhindrede fiskeri og skadede havmiljøet.',
    'verdict_card3_quote' => '“Kina har krænket Filippinernes suveræne rettigheder, grebet ind i fiskeriaktiviteterne ved Scarborough-revet og forårsaget alvorlig skade på koralrevets miljø.”',
    'verdict_card3_more' => '+ Læs afgørelsen',
    'verdict_extra1' => 'Ni-streglinjen, som Kina selv har tegnet, er <strong>ikke forenelig</strong> med UNCLOS 1982.',
    'verdict_extra2' => 'Kina har skadet økosystemet i Spratlyøerne gennem overudnyttelse og opførelse af kunstige øer.',
    'verdict_extra3' => 'Kinas handlinger har øget risikoen for konflikt med Filippinerne.',
    'verdict_extra4' => 'Ba Bình-øen (under taiwansk kontrol) kan heller ikke skabe en EEZ.',
    'verdict_subtitle' => 'Hvorfor er den i konflikt med UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 afgrænser klart havzoner baseret på kyststatens basislinjer. Kravet om Ni-streglinjen ligger uden for denne ramme og kan derfor ikke forenes med den.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialfarvand (sømil)',
    'verdict_zone1_body' => 'Et lands suveræne havområde, målt fra basislinjen.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusiv økonomisk zone',
    'verdict_zone2_body' => 'EEZ — kyststaten har suveræne rettigheder til ressourcer inden for dette område.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalsokkel (maks., sømil)',
    'verdict_zone3_body' => 'Rettigheder til havbundens ressourcer, fastlagt efter geologiske kriterier.',
    'verdict_foot' => 'Inden for denne ramme er “historiske rettigheder” til at omfatte et helt åbent havområde — som Ni-streglinjen antyder — <em>blevet erstattet</em> af UNCLOS\' retlige regime, som Kina selv er part i.',
];
