<?php

return [
    'footer_index' => 'ბიბლიოთეკა',
    'footer_crest_eyebrow' => 'ბიბლიოთეკის დასკვნა სიმართლით',
    'footer_crest_quote' => '“სამხრეთ ჩინეთის ზღვაში მშვიდობა შენდება <b>საერთაშორისო სამართლის</b> საფუძველზე.”',
    'footer_crest_sub' => 'სიძულვილის გარეშე · მხოლოდ სიმართლე',
    'footer_nav_aria' => 'გვერდის ქვედა ნაწილის მოქმედებები',
    'footer_btn_top' => 'ზევით დაბრუნება',
    'footer_btn_verdict' => 'PCA-ის 2016 წლის გადაწყვეტილება',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ცხრა ტირეს ხაზი',
    'footer_brand_body' => 'ფაქტებზე, საერთაშორისო სამართალსა და ისტორიულ დოკუმენტებზე დაფუძნებული განმარტებითი გვერდი — რომელიც ცხრას ტირეს ხაზის პრეტენზიას მტკიცებულებებით უარყოფს და არა სლოგანებით.',
    'footer_refs_title' => 'წყაროები',
    'footer_ref1' => 'PCA-ის გადაწყვეტილება, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — სრული ტექსტი',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ისტორიული მასალები და ძველი რუკები',
    'footer_toc_title' => 'გვერდის სარჩევი',
    'footer_toc1' => 'რა არის ცხრა ტირეს ხაზი',
    'footer_toc2' => 'წარმოშობა',
    'footer_toc3' => 'რატომ იწვევს დავას',
    'footer_toc4' => 'რატომ ეწინააღმდეგება საერთაშორისო საზოგადოება',
    'footer_toc5' => 'ჩუმი მოწმეები',
    'footer_toc6' => 'PCA-ის 2016 წლის გადაწყვეტილება',
    'footer_toc7' => 'პარასელის კუნძულები – სპრატლის კუნძულები',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — ობიექტური სიმართლე სამხრეთ ჩინეთის ზღვაზე.<br>ეკოსისტემა: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'კოორდინატების გარეშე',
];
