<?php

return [
    'footer_index' => 'ბიბლიოთეკა',
    'footer_crest_eyebrow' => 'საბიბლიოთეკო ჭეშმარიტების დასასრული',
    'footer_crest_quote' => '„სამხრეთ ჩინეთის ზღვაში მშვიდობა აგებულია <b>საერთაშორისო სამართლის</b> საფუძველზე.“',
    'footer_crest_sub' => 'სიძულვილის გარეშე · მხოლოდ ჭეშმარიტება',
    'footer_nav_aria' => 'გვერდის ქვედა ნაწილის მოქმედებები',
    'footer_btn_top' => 'ზედა ნაწილზე დაბრუნება',
    'footer_btn_verdict' => 'PCA-ის 2016 წლის გადაწყვეტილება',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ცხრა ტირეს ხაზის პრეტენზია',
    'footer_brand_eyebrow' => 'თემატური გვერდი · ვიეტნამის სუვერენიტეტი',
    'footer_brand_body' => 'ცხრა ტირეს ხაზის შესახებ ახსნა ობიექტური ჭეშმარიტების, საერთაშორისო სამართლის, PCA-ის 2016 წლის გადაწყვეტილებისა და ისტორიული მასალების მეშვეობით — დამატება ორი არქიპელაგის <strong>"პარასელის კუნძულები და სპრატლის კუნძულები"</strong> სუვერენიტეტის შესახებ სპეციალიზებული გვერდებისთვის. ჩინეთის უსაფუძვლო პრეტენზიის უარყოფა ისტორიითა და მტკიცებულებებით.',
    'footer_refs_title' => 'საკონსულტაციო წყაროები',
    'footer_ref1' => 'PCA-ის გადაწყვეტილება, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — სრული ტექსტი',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ისტორიული მასალები და ძველი რუკები',
    'footer_toc_title' => 'გვერდის სარჩევი',
    'footer_toc1' => 'რა არის ცხრა ტირეს ხაზი',
    'footer_toc2' => 'წარმოშობა',
    'footer_toc3' => 'რატომ იწვევს დავას',
    'footer_toc4' => 'რატომ ეწინააღმდეგება საერთაშორისო საზოგადოება',
    'footer_toc5' => 'ჩუმი მოწმეები',
    'footer_toc6' => 'PCA-ის 2016 წლის გადაწყვეტილება',
    'footer_toc7' => 'პარასელის კუნძულები – სპრატლის კუნძულები',
    'footer_copy_eyebrow' => 'არაკომერციული პროექტი',
    'footer_copy_title' => 'პარასელის კუნძულები – სპრატლის კუნძულები ვიეტნამის საკუთრებაა',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — თემატური გვერდი ცხრა ტირეს ხაზის შესახებ ვიეტნამის სუვერენიტეტის ეკოსისტემაში.',
    'footer_copy_body' => 'ცხრა ტირეს ხაზის პრეტენზიის ახსნა <strong>ობიექტური ჭეშმარიტებით</strong>, <strong>საერთაშორისო სამართლით</strong>, PCA-ის 2016 წლის გადაწყვეტილებითა და ისტორიული მასალებით — დამატება პარასელის კუნძულები და სპრატლის კუნძულები სუვერენიტეტის შესახებ სპეციალიზებული გვერდებისთვის.',
    'footer_copy_ecosystem_aria' => 'ამ პროექტის სხვა გვერდები',
    'footer_copy_ecosystem_label' => 'ერთი ეკოსისტემა',
    'footer_copy_disclaimer' => 'შინაარსი განკუთვნილია განათლებისა და ცნობიერების ამაღლებისთვის; არ ცვლის ვიეტნამის სახელმწიფოს ოფიციალურ პოზიციას.',
    'footer_copy' => '<strong>© :year ცხრა ტირეს ხაზი</strong> — არაკომერციული პროექტის <strong>პარასელის კუნძულები – სპრატლის კუნძულები ვიეტნამის საკუთრებაა</strong> ნაწილი, სისტემაში: <a href="https://paracelislands.net/ka" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ka" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ka" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ka" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ka" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'გვერდის შინაარსობრივი ვალდებულებები',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-ის 2016 წლის გადაწყვეტილება',
    'footer_chip3' => 'ისტორიული მტკიცებულებები',
    'footer_chip4' => 'ძველი რუკები',
    'footer_chip5' => 'ობიექტური ჭეშმარიტება',
    'footer_chip6' => 'სამხრეთ ჩინეთის ზღვის მშვიდობა',
];
