<?php

return [
    'footer_index' => 'ბიბლიოთეკა',
    'footer_crest_eyebrow' => 'საბუთების ბიბლიოთეკის დასასრული',
    'footer_crest_quote' => '„სამხრეთ ჩინეთის ზღვაში მშვიდობა შენდება <b>საერთაშორისო სამართლის</b> საფუძველზე.“',
    'footer_crest_sub' => 'სიძულვილის გარეშე · მხოლოდ სიმართლე',
    'footer_nav_aria' => 'გვერდის ქვედა ნაწილის მოქმედებები',
    'footer_btn_top' => 'ზედა ნაწილზე დაბრუნება',
    'footer_btn_verdict' => 'PCA-ს 2016 წლის გადაწყვეტილება',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'ცხრა ტირეს ხაზის პრეტენზია',
    'footer_brand_eyebrow' => 'სათემატო გვერდი · ვიეტნამის სუვერენიტეტი',
    'footer_brand_body' => 'ცხრა ტირეს ხაზის შესახებ ახსნა ობიექტური სიმართლის, საერთაშორისო სამართლის, PCA-ს 2016 წლის გადაწყვეტილებისა და ისტორიული მასალების საფუძველზე — დამატებად ორ კუნძულოვან ჯგუფზე <strong>"პარასელის კუნძულები და სპრატლის კუნძულები"</strong> სუვერენიტეტის შესახებ სპეციალიზებული გვერდებისთვის. ჩინეთის უსაფუძვლო პრეტენზიის უარყოფა ისტორიითა და მტკიცებულებებით.',
    'footer_refs_title' => 'საკვლევი წყაროები',
    'footer_ref1' => 'PCA-ს გადაწყვეტილება, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — სრული ტექსტი',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ისტორიული მასალები და ძველი რუკები',
    'footer_toc_title' => 'გვერდის სარჩევი',
    'footer_toc1' => 'რა არის ცხრა ტირეს ხაზი',
    'footer_toc2' => 'წარმოშობა',
    'footer_toc3' => 'რატომ იწვევს დავას',
    'footer_toc4' => 'რატომ ეწინააღმდეგება ამას საერთაშორისო საზოგადოება',
    'footer_toc5' => 'ჩუმი მოწმეები',
    'footer_toc6' => 'PCA-ს 2016 წლის გადაწყვეტილება',
    'footer_toc7' => 'პარასელის კუნძულები – სპრატლის კუნძულები',
    'footer_copy_eyebrow' => 'არაკომერციული პროექტი',
    'footer_copy_title' => 'პარასელის კუნძულები – სპრატლის კუნძულები ეკუთვნის ვიეტნამს',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — თემატური გვერდი ცხრა ტირეს ხაზზე ვიეტნამის სუვერენიტეტის ეკოსისტემაში.',
    'footer_copy_body' => 'ცხრა ტირეს ხაზის პრეტენზიის განმარტება <strong>ობიექტური სიმართლის</strong>, <strong>საერთაშორისო სამართლის</strong>, PCA-ს 2016 წლის გადაწყვეტილებისა და ისტორიული მასალების საფუძველზე — დამატებად პარასელის კუნძულებისა და სპრატლის კუნძულების სუვერენიტეტის შესახებ სპეციალიზებული გვერდებისთვის.',
    'footer_copy_ecosystem_aria' => 'ერთიანი პროექტის გვერდები',
    'footer_copy_ecosystem_label' => 'იმავე ეკოსისტემაში',
    'footer_copy_disclaimer' => 'შინაარსი მიზნად ისახავს განათლებასა და ცნობიერების ამაღლებას; იგი არ ცვლის ვიეტნამის სახელმწიფოს ოფიციალურ პოზიციას.',
    'footer_copy' => '<strong>© :year ცხრა ტირეს ხაზი</strong> — არაკომერციული პროექტის <strong>პარასელის კუნძულები – სპრატლის კუნძულები ეკუთვნის ვიეტნამს</strong> ნაწილი, სისტემაში: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'გვერდის შინაარსობრივი ვალდებულება',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-ს 2016 წლის გადაწყვეტილება',
    'footer_chip3' => 'ისტორიული მტკიცებულებები',
    'footer_chip4' => 'ძველი რუკები',
    'footer_chip5' => 'ობიექტური სიმართლე',
    'footer_chip6' => 'სამხრეთ ჩინეთის ზღვის მშვიდობა',
];
