<?php

return [
    'nav_logo_name' => 'ცხრა ტირეს ხაზი',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'ცხრა ტირეს ხაზი',
    'nav_rail_aria' => 'სექციების მიხედვით ნავიგაცია',
    'nav_rail_what' => 'განმარტება',
    'nav_rail_origin' => 'წარმოშობა',
    'nav_rail_dispute' => 'დავა',
    'nav_rail_opposition' => 'საწინააღმდეგო პოზიცია',
    'nav_rail_witnesses' => 'ძველი რუკები',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'პარასელის კუნძულები – სპრატლის კუნძულები',
    'nav_sound_off' => 'ფონის მუსიკის ჩართვა',
    'nav_sound_on' => 'ფონის მუსიკის გამორთვა',
    'nav_share' => 'გაზიარება',
    'dialog_title' => 'ჩვენების ენა',
    'language' => 'ენა',
    'display_hint' => ':count ენა',
    'search_placeholder' => 'ენის ძებნა…',
    'cancel' => 'გაუქმება',
    'apply' => 'გამოყენება',
    'sound_off' => 'ფონის ხმის ჩართვა',
    'sound_on' => 'ფონის ხმის გამორთვა',
    'lang_trigger' => 'ენის არჩევა',
    'close' => 'დახურვა',
    'no_results' => 'ენა ვერ მოიძებნა',
    'contribute' => 'გაზიარება',
];
