<?php

return [
    'footer_index' => 'ライブラリ',
    'footer_crest_eyebrow' => '真実のライブラリを締めくくる',
    'footer_crest_quote' => '「南シナ海の平和は <b>国際法</b> を基盤として築かれる。」',
    'footer_crest_sub' => '憎しみは不要・真実のみ',
    'footer_nav_aria' => 'ページ下部の操作',
    'footer_btn_top' => 'ページ上部へ',
    'footer_btn_verdict' => '2016年PCA判決',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '九段線の主張',
    'footer_brand_eyebrow' => '特集ページ · ベトナムの主権',
    'footer_brand_body' => '九段線について、客観的事実、国際法、2016年PCA判決、歴史資料に基づいて解説します。これは、<strong>「西沙諸島と南沙諸島」</strong> の主権に関する専門ページを補完するものです。中国の理不尽な主張を、歴史と証拠によって否定します。',
    'footer_refs_title' => '参考資料',
    'footer_ref1' => 'PCA判決、2016年7月12日',
    'footer_ref2' => 'UNCLOS 1982 — 全文',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => '歴史資料 & 古地図',
    'footer_toc_title' => 'ページ目次',
    'footer_toc1' => '九段線とは何か',
    'footer_toc2' => '起源',
    'footer_toc3' => 'なぜ争点となるのか',
    'footer_toc4' => 'なぜ国際社会は反対するのか',
    'footer_toc5' => '静かな証人',
    'footer_toc6' => '2016年PCA判決',
    'footer_toc7' => '西沙諸島 – 南沙諸島',
    'footer_copy_eyebrow' => '非営利プロジェクト',
    'footer_copy_title' => '西沙諸島 – 南沙諸島はベトナムのもの',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — ベトナムの主権エコシステムにおける九段線に関する特集ページです。',
    'footer_copy_body' => '九段線の主張を、<strong>客観的事実</strong>、<strong>国際法</strong>、2016年PCA判決、歴史資料を通じて解説します。これは、西沙諸島と南沙諸島の主権に関する専門ページを補完するものです。',
    'footer_copy_ecosystem_aria' => '同一プロジェクトのページ',
    'footer_copy_ecosystem_label' => '同じエコシステム',
    'footer_copy_disclaimer' => '本内容は教育と理解促進を目的としたものであり、ベトナム国家の公式見解に代わるものではありません。',
    'footer_copy' => '<strong>© :year 九段線</strong> — 非営利プロジェクト <strong>西沙諸島 – 南沙諸島はベトナムのもの</strong> の一部。所属システム: <a href="https://paracelislands.net/ja" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ja" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ja" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ja" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ja" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'ページ内容のコミットメント',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016年PCA判決',
    'footer_chip3' => '歴史的証拠',
    'footer_chip4' => '古地図',
    'footer_chip5' => '客観的事実',
    'footer_chip6' => '南シナ海の平和',
];
