<?php

return [
    'footer_index' => 'ライブラリ',
    'footer_crest_eyebrow' => '真実のライブラリを締めくくる',
    'footer_crest_quote' => '「南シナ海の平和は、<b>国際法</b>という土台の上に築かれる。」',
    'footer_crest_sub' => '憎悪なし · あるのは真実だけ',
    'footer_nav_aria' => 'ページ下部のアクション',
    'footer_btn_top' => 'ページ上部へ',
    'footer_btn_verdict' => 'PCA 2016 年裁定',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '九段線',
    'footer_brand_body' => '客観的な事実、国際法、歴史資料に基づく解説サイトです。証拠によって九段線の主張を退け、スローガンではなく事実で示します。',
    'footer_refs_title' => '参考資料',
    'footer_ref1' => 'PCA 裁定、2016年7月12日',
    'footer_ref2' => '1982年 UNCLOS — 全文',
    'footer_ref3' => 'Limits in the Seas №143（米国国務省）',
    'footer_ref4' => '歴史資料と古地図',
    'footer_toc_title' => 'ページ目次',
    'footer_toc1' => '九段線とは何か',
    'footer_toc2' => '起源',
    'footer_toc3' => 'なぜ争点となるのか',
    'footer_toc4' => 'なぜ国際社会は反対するのか',
    'footer_toc5' => '静かな証人',
    'footer_toc6' => 'PCA 2016 年裁定',
    'footer_toc7' => '西沙諸島 – 南沙諸島',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — 南シナ海に関する客観的な真実。<br>エコシステム: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => '座標なし',
];
