<?php

return [
    'nav_logo_name' => '九段線',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => '九段線',
    'nav_rail_aria' => '項目別ナビゲーション',
    'nav_rail_what' => '定義',
    'nav_rail_origin' => '起源',
    'nav_rail_dispute' => '論争',
    'nav_rail_opposition' => '反対',
    'nav_rail_witnesses' => '古地図',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => '西沙諸島 – 南沙諸島',
    'nav_sound_off' => 'BGMをオンにする',
    'nav_sound_on' => 'BGMをオフにする',
    'nav_share' => '共有',
    'dialog_title' => '表示言語',
    'language' => '言語',
    'display_hint' => ':count言語',
    'search_placeholder' => '言語を検索…',
    'cancel' => 'キャンセル',
    'apply' => '適用',
    'sound_off' => '背景音をオンにする',
    'sound_on' => '背景音をオフにする',
    'lang_trigger' => '言語を選択',
    'close' => '閉じる',
    'no_results' => '言語が見つかりません',
    'contribute' => '共有',
];
