<?php

return [
    'opposition_index' => '反対',
    'opposition_label' => 'なぜ国際社会は反対するのか',
    'opposition_title' => '反対の根拠は',
    'opposition_title_accent' => '感情ではなく、法にある',
    'opposition_lead' => '九段線が2009年に国連へ提出されるや否や、多くの国と学界は、具体的な法的論拠をもって反対した。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => 'ベトナム · マレーシア · インドネシア',
    'opposition_voice1_body' => '中国が国連事務総長に九段線図を提出した翌日（2009年5月7日）、これらの国々は相次いで反対の公文を送り、主張を退けた。',
    'opposition_voice1_chip1' => '反対公文',
    'opposition_voice1_chip2' => '1982年UNCLOSに適合しない',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'フィリピン',
    'opposition_voice2_body' => '国連に外交書簡を送り、中国の南シナ海における主張は「国際法上の根拠を欠く」と表明した。これは、その後の仲裁裁判提起の前提となった。',
    'opposition_voice2_chip1' => 'PCA提訴の前提',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => '米国国務省 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析は、各年の地図で境界線の位置が一致していないこと、境界線が中間線ではなく大陸側へ食い込んでいること、多くの地物がEEZを持つ「島」の要件を満たしていないことを示した。',
    'opposition_voice3_chip1' => '法的要件を満たさない',
    'opposition_voice3_chip2' => '公式分析',
    'opposition_voice4_year' => '学術',
    'opposition_voice4_title' => '「歴史的水域」は時代遅れ',
    'opposition_voice4_body' => 'この概念は、湾や沿岸に近い内海にのみ適用されるもので、広大な外洋の海域全体を覆うことはできない。2003年には、台湾自身も1993年に掲げた「歴史的水域」政策を否定している。',
    'opposition_voice4_chip1' => '中国の学者の間ですら一致していない',
];
