<?php

return [
    'opposition_index' => '反対',
    'opposition_label' => 'なぜ国際社会は反対するのか',
    'opposition_title' => '反対の根拠は',
    'opposition_title_accent' => '感情ではなく、法',
    'opposition_lead' => '九段線が2009年に国連へ提出されると直ちに、多くの国や学界が、具体的な法的論拠に基づいて反対した。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => 'ベトナム · マレーシア · インドネシア',
    'opposition_voice1_body' => '中国が九段線の地図を国連事務総長に提出した（2009年5月7日）わずか1日後、これらの国々は相次いで反対の公文書を送り、主張を退けた。',
    'opposition_voice1_chip1' => '反対の公文書',
    'opposition_voice1_chip2' => '1982年UNCLOSに適合しない',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => 'フィリピン',
    'opposition_voice2_body' => '国連に外交文書を提出し、中国の南シナ海における主張は「国際法上の根拠がない」と表明した。これは、その後の仲裁裁判提起の前提となった。',
    'opposition_voice2_chip1' => 'PCA提訴の前提',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'アメリカ合衆国国務省 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析は、境界線の位置について各年の地図が一致していないこと、境界線が中線ではなく大陸側へ食い込んでいること、多くの海域地形がEEZを持つ「島」の法的要件を満たさないことを示した。',
    'opposition_voice3_chip1' => '法的要件を満たさない',
    'opposition_voice3_chip2' => '公式分析',
    'opposition_voice4_year' => '学術',
    'opposition_voice4_title' => '「歴史的水域」は時代遅れ',
    'opposition_voice4_body' => 'この概念は、湾や沿岸に近い入り江にのみ適用されるもので、広大な外洋全体を覆うことはできない。2003年には、台湾自身も1993年に示していた「歴史的水域」政策を否定している。',
    'opposition_voice4_chip1' => '中国の学者でさえ一致していない',
];
