<?php

return [
    'sovereignty_index' => '西沙諸島 - 南沙諸島',
    'sovereignty_label' => '必然的な結論',
    'sovereignty_title' => '西沙諸島 - 南沙諸島',
    'sovereignty_title_accent' => 'はベトナムのものです',
    'sovereignty_lead' => 'このページでは九段線を解説します。結論部分では、次の問いに答えます。すなわち、西沙諸島と南沙諸島という二つの群島に対する主権は誰にあるのか。歴史的な管理の経緯と国際法に照らせば、一貫した答えはベトナムです。',
    'sovereignty_thesis_label' => '総合的な論点',
    'sovereignty_thesis_lock1' => '法的座標がない',
    'sovereignty_thesis_lock2' => 'PCA 2016が否定',
    'sovereignty_thesis_lock3' => '古地図は包含せず',
    'sovereignty_thesis_body' => '上の6項目を経て、3点は明らかです。九段線は手描きであり、法的座標を持たず、2016年の仲裁裁判所はその主張を退けました。さらに、中国自身の古地図も南シナ海を包含していません。ベトナムの主権はスローガンに基づくのではなく、ベトナム国家が — 阮朝の時代から — 二つの群島が無主地であった時期に、平和的かつ継続的に管理してきた事実に基づいています。',
    'sovereignty_spine_caption' => '継続的管理の節目',
    'sovereignty_spine_title' => '途切れない一つの年表',
    'sovereignty_spine_range' => '17世紀 → 現在',
    'sovereignty_chron1_year' => '17世紀',
    'sovereignty_chron1_title' => '黄沙隊',
    'sovereignty_chron1_body' => '阮朝の諸王は黄沙隊を派遣し、測量、航路調査、海上での採取を行わせました — これは実効的な管理権の行使でした。',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'ザーロン帝',
    'sovereignty_chron2_body' => '西沙諸島に旗を立て、当時の世界に対してベトナムの主権を確認しました。',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'ミンマン帝',
    'sovereignty_chron3_body' => '測量を行い、碑を建立し、群島を朝廷の公式地図に記録しました。',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => '継続的継承',
    'sovereignty_chron4_body' => 'フランスはこれを承認し、その後も管理を継続し、西沙諸島をトゥアティエン省に編入しました — これは現在のベトナム国家の基盤となりました。',
    'sovereignty_chron5_year' => '現在',
    'sovereignty_chron5_title' => '法と実務',
    'sovereignty_chron5_body' => 'ベトナムはUNCLOS、外交、文書記録に基づいて管理しています。九段線の主張は、この証拠に取って代わることはできません。',
    'sovereignty_balance_label' => '証拠の均衡',
    'sovereignty_balance_medallion_title' => '双方を対比する',
    'sovereignty_vn_tag' => 'ベトナム側',
    'sovereignty_vn_title' => '行為によって確立された主権',
    'sovereignty_vn_body' => '土地が無主地であった時に実効的に占有し、その後、何世紀にもわたって公然と管理してきました — 詔書、碑文、地図、行政記録があります。この方法はUNCLOSおよび国際慣行に適合しています。',
    'sovereignty_dash_tag' => '九段線側',
    'sovereignty_dash_title' => '主張では証拠を補えない',
    'sovereignty_dash_body' => '1948年に引かれた一本の線は座標を持たず、PCA 2016によって退けられ、UNCLOSにも反します — これは03から06までの項目で示したとおりです。したがって、二つの群島の主権に関する結論を九段線に基づいて導くことはできません。',
    'sovereignty_seal_quote' => 'ベトナムは <strong>平和的手段</strong> により、国際法 — とりわけ1982年UNCLOS — に基づいて紛争を解決し、平和、協力、発展のある南シナ海を目指します。',
    'sovereignty_seal_cite' => 'ベトナムの立場 · UNCLOS 1982',
    'sovereignty_next_eyebrow' => '同じエコシステムの主要プロジェクト',
    'sovereignty_next_title' => '西沙諸島 - 南沙諸島に関する証拠をすべて読む',
    'sovereignty_next_body' => '詳細な資料 — 文書、地図、年表、法的論拠 — は <strong>paracelislands.net</strong> にあり、二つの群島の主権というテーマを包括的に提示しています。今ご覧のページは、九段線からその結論へ至る論理をつなぐものです。',
    'sovereignty_next_cta' => 'paracelislands.net を開く',
];
