<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '国際的な判決',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => '3つの「ノー」',
    'verdict_lead' => '2016年7月12日、ハーグの常設仲裁裁判所（PCA）は、UNCLOS附属書VIIに基づき、フィリピン対中国の事件において、九段線の主張を退ける判決を下した。<em>各カードをクリックして原文を読む。</em>',
    'verdict_card1_khong' => 'ノー',
    'verdict_card1_title' => '歴史的権利',
    'verdict_card1_short' => '中国が九段線内の海域の資源について歴史的権利を主張する法的根拠はない。',
    'verdict_card1_quote' => '「中国が九段線内の海域にある資源について歴史的権利を主張する法的根拠はない。」',
    'verdict_card1_more' => '+ 判決を読む',
    'verdict_card2_khong' => 'ノー',
    'verdict_card2_title' => 'EEZを生む地形',
    'verdict_card2_short' => '南沙諸島のいかなる地形も、中国の排他的経済水域を生み出す条件を満たさない。太平島も含まれる。',
    'verdict_card2_quote' => '「南沙諸島のいかなる地形も、排他的経済水域を生み出す能力を有しない。」',
    'verdict_card2_more' => '+ 判決を読む',
    'verdict_card3_khong' => 'ノー',
    'verdict_card3_title' => '合法的な行為',
    'verdict_card3_short' => '中国はフィリピンの主権的権利を侵害し、漁業を妨げ、海洋環境に損害を与えた。',
    'verdict_card3_quote' => '「中国はフィリピンの主権的権利を侵害し、スカボロー礁での漁業活動に干渉し、サンゴ礁環境に深刻な損害を与えた。」',
    'verdict_card3_more' => '+ 判決を読む',
    'verdict_extra1' => '中国が自ら描いた九段線は、1982年UNCLOSと<strong>整合しない</strong>。',
    'verdict_extra2' => '中国は過剰な採取と人工島造成を通じて南沙諸島の生態系に損害を与えている。',
    'verdict_extra3' => '中国の行動はフィリピンとの紛争リスクを高めている。',
    'verdict_extra4' => '太平島（台湾の実効支配下）もEEZを生み出すことはできない。',
    'verdict_subtitle' => 'なぜUNCLOSと矛盾するのか？',
    'verdict_subtitle_body' => '1982年UNCLOSは、沿岸国の基線に基づいて海域を明確に区分している。九段線の主張はこの枠組みを超えているため、両立しない。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '領海（海里）',
    'verdict_zone1_body' => '基線から測る、国家の主権が及ぶ海域。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '排他的経済水域',
    'verdict_zone2_body' => 'EEZ — 沿岸国は、この範囲内の資源について主権的権利を有する。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陸棚（最大、海里）',
    'verdict_zone3_body' => '地質学的条件により定められる、海底資源に対する権利。',
    'verdict_foot' => 'この枠組みにおいて、九段線が示唆するような海洋全体に及ぶ「歴史的権利」は、<em>すでに置き換えられている</em>。中国自身も当事国であるUNCLOSの法制度によって。',
];
