<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '国際裁定',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => '3つの「ない」',
    'verdict_lead' => '2016年7月12日、ハーグの常設仲裁裁判所（PCA）は、UNCLOS付属書VIIに基づき、フィリピン対中国事件において、九段線の主張を退ける判決を下しました。<em>各カードをクリックすると、原文を読むことができます。</em>',
    'verdict_card1_khong' => 'ない',
    'verdict_card1_title' => '歴史的権利',
    'verdict_card1_short' => '中国が九段線内の海域の資源について歴史的権利を主張する法的根拠はありません。',
    'verdict_card1_quote' => '「中国が九段線内の海域にある資源について歴史的権利を主張するための法的根拠はない。」',
    'verdict_card1_more' => '+ 判決を読む',
    'verdict_card2_khong' => 'ない',
    'verdict_card2_title' => 'EEZを生み出す地物',
    'verdict_card2_short' => '南沙諸島のいかなる地物も、中国の排他的経済水域を形成する条件を満たしておらず、太平島も同様です。',
    'verdict_card2_quote' => '「南沙諸島のいかなる地物も、排他的経済水域を形成する能力を有しない。」',
    'verdict_card2_more' => '+ 判決を読む',
    'verdict_card3_khong' => 'ない',
    'verdict_card3_title' => '合法な行為',
    'verdict_card3_short' => '中国はフィリピンの主権的権利を侵害し、漁業活動を妨げ、海洋環境に損害を与えました。',
    'verdict_card3_quote' => '「中国はフィリピンの主権的権利を侵害し、スカボロー礁での漁業活動に干渉し、サンゴ礁環境に深刻な損害を与えた。」',
    'verdict_card3_more' => '+ 判決を読む',
    'verdict_extra1' => '中国が自ら描いた九段線は、<strong>1982年のUNCLOSと整合しません</strong>。',
    'verdict_extra2' => '中国は過剰な開発と人工島造成を通じて南沙諸島の生態系に損害を与えています。',
    'verdict_extra3' => '中国の行動は、フィリピンとの紛争のリスクを高めています。',
    'verdict_extra4' => '太平島（台湾が管理）もEEZを形成することはできません。',
    'verdict_subtitle' => 'なぜUNCLOSと衝突するのか？',
    'verdict_subtitle_body' => '1982年のUNCLOSは、沿岸国の基線に基づいて海域を明確に区分しています。九段線の主張はこの枠組みを超えているため、両立しません。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '領海（海里）',
    'verdict_zone1_body' => '基線から測定される、国家の主権が及ぶ海域。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '排他的経済水域',
    'verdict_zone2_body' => 'EEZ — 沿岸国は、この範囲内の資源について主権的権利を有します。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陸棚（最大、海里）',
    'verdict_zone3_body' => '海底資源に対する権利。地質条件により定められます。',
    'verdict_foot' => 'この枠組みの下では、九段線が示唆するような公海全体に及ぶ「歴史的権利」は、<em>すでにUNCLOSの法制度に置き換えられており</em>、中国自身もその締約国です。',
];
