<?php

return [
    'ancient_maps_index' => 'Ancient Maps',
    'ancient_maps_label' => 'Ancient Maps of China',
    'ancient_maps_title' => 'The southernmost point reaches only',
    'ancient_maps_title_accent' => 'Hainan Island',
    'ancient_maps_lead' => 'Maps published by China and foreign presses — grouped by era — all show <em>Hainan Island as the southernmost point</em>, with no Paracel Islands or Spratly Islands. Compiled from <em>Vietnam’s national sovereignty over the two archipelagos of Paracel Islands and Spratly Islands</em> (Trương Minh Dục, 2015), thoidai.com.vn, and materials collected by M.A. Chử Đình Phúc (VietNamNet, 2012).',
    'ancient_maps_timeline_aria' => 'Chronological timeline of ancient Chinese maps',
    'ancient_maps_year_aria' => 'Date',
    'lightbox_aria' => 'View enlarged image',
    'lightbox_close' => 'Close',
    'lightbox_prev' => 'Previous image',
    'lightbox_next' => 'Next image',
    'ancient_maps_source' => 'Images: thoidai.com.vn · VietNamNet (Chử Đình Phúc) · compiled by Hải Vân',
    'ancient_maps_quote' => 'Maps published by China itself have never placed the Paracel Islands - Spratly Islands within its territory.',

    'ancient_map_jiuyu_title' => 'Nine Regions Inspection Order Map (1121)',
    'ancient_map_jiuyu_year' => '1121',
    'ancient_map_jiuyu_body' => '<p>The earliest surviving map showing the full territory of the Song dynasty, first appearing in <strong>1121</strong> (3rd year of Xuanhe). Carved in stone, discovered in 1960 in Rong County, Sichuan Province.</p><p>The southern boundary of the Song on this map reaches <strong>Qiongzhou (Hainan)</strong>. The outline of Hainan Island is drawn quite accurately, close to modern maps.</p>',

    'ancient_map_kangxi_guangdong_title' => 'Guangdong under Kangxi — southern limit at Hainan',
    'ancient_map_kangxi_guangdong_year' => '1685–1701',
    'ancient_map_kangxi_guangdong_body' => '<p>Late 17th–early 18th century: a series of Guangdong provincial administrative maps on silk and in provincial gazetteers under the <strong>Kangxi</strong> reign.</p><p><strong>General Map of Guangdong</strong> (around 1685): <strong>295×196 cm</strong>, painted in color on silk; the province ends at <strong>Qiongzhou Prefecture (Hainan)</strong>.</p><p><strong>Complete Map of Guangdong</strong> and Hainan detail (around 1700–1701): the southern boundary stops at Hainan — no Paracel Islands or Spratly Islands.</p>',
    'ancient_map_kangxi_guangdong_img1_caption' => 'General Map of Guangdong (around 1685)',
    'ancient_map_kangxi_guangdong_img2_caption' => 'Complete Map of Guangdong',
    'ancient_map_kangxi_guangdong_img3_caption' => 'Complete Map of Guangdong — Hainan detail',

    'ancient_map_qianlong_gazetteer_title' => 'Imperial territory map & Gazetteer of Guangdong',
    'ancient_map_qianlong_gazetteer_year' => '1728–1751',
    'ancient_map_qianlong_gazetteer_body' => '<p><strong>Yongzheng–Qianlong</strong> era: national maps and the <em>Gazetteer of Guangdong</em> alike place the southernmost administrative point at <strong>Qiongzhou Prefecture on Hainan Island</strong>.</p><p><strong>Imperial Territory Map of the Great Qing</strong> (1728–1729): <strong>57×57.3 cm</strong>; the southern boundary reaches only Qiongzhou.</p><p>In the provincial gazetteer: <em>Complete Provincial Map of Guangdong</em> (He Yulin) and <em>Complete Map of Qiongzhou Prefecture</em> (Nguyen Nguyen) — administrative scope does not extend beyond Hainan.</p>',
    'ancient_map_qianlong_gazetteer_img1_caption' => 'Imperial Territory Map (1728–1729)',
    'ancient_map_qianlong_gazetteer_img2_caption' => 'Complete Provincial Map of Guangdong',
    'ancient_map_qianlong_gazetteer_img3_caption' => 'Complete Map of Qiongzhou Prefecture',

    'ancient_map_jiaqing_atlas_1850_title' => 'Qing eighteen-province atlas (1850)',
    'ancient_map_jiaqing_atlas_1850_year' => '1850',
    'ancient_map_jiaqing_atlas_1850_body' => '<p>In <em>Complete Territorial Maps of the Eighteen Provinces of the Qing</em> by Dong Yue Wen Zuo Wei Men — Japanese Kaei 3 edition (<strong>1850</strong>).</p><p>Both the <em>General Map of the Eighteen Provinces</em> and the <em>Complete Map of Guangdong</em> in the same volume draw China’s southern limit at Hainan Island. Materials from Chinese digital libraries (Chử Đình Phúc / VietNamNet).</p>',
    'ancient_map_jiaqing_atlas_1850_img1_caption' => 'General Map of the Eighteen Provinces',
    'ancient_map_jiaqing_atlas_1850_img2_caption' => 'Complete Map of Guangdong',

    'ancient_map_guangxu_coastal_title' => 'Coastal & naval maps of Guangdong',
    'ancient_map_guangxu_coastal_year' => '1862–1866',
    'ancient_map_guangxu_coastal_body' => '<p><strong>Guangxu</strong> era — two map types confirming the same geography:</p><p><strong>Complete Ocean Map of the Seven Coastal Provinces</strong> (around 1862–1908): <strong>28×914.2 cm</strong>; South China Sea area does not extend beyond <strong>18° north latitude</strong>.</p><p><strong>Map of Guangdong Navy Garrison Troops</strong> (after 1866): military map <strong>32×560 cm</strong>; no island group corresponding to Xisha or Nansha (Chinese names for Vietnam’s Spratly and Paracel Islands).</p>',
    'ancient_map_guangxu_coastal_img1_caption' => 'Complete Ocean Map of the Seven Coastal Provinces',
    'ancient_map_guangxu_coastal_img2_caption' => 'Guangdong Navy Garrison Troops map',

    'ancient_map_daqing_yitong_title' => 'Complete Unified Map of the Great Qing',
    'ancient_map_daqing_yitong_year' => 'late 19th century',
    'ancient_map_daqing_yitong_body' => '<p>A complete map of the Great Qing. Offshore it marks only islands such as Fengma (south of Korea), Liuqiu (east of Zhejiang), Taiwan (east of Fujian), and <strong>Qiongzhou, Yazhou</strong> on Hainan Island — south of the Guangdong mainland.</p>',

    'ancient_map_late_qing_prints_title' => 'Late Qing printed atlases — 1904–1908',
    'ancient_map_late_qing_prints_year' => '1904–1908',
    'ancient_map_late_qing_prints_body' => '<p>Atlases published in China and abroad from <strong>1904</strong> to <strong>1908</strong> share one conclusion: China’s southernmost point is Hainan Island — <strong>excluding the Paracel Islands and Spratly Islands</strong>.</p><p>Notable works: <em>Complete Provincial Geographical Map of the Imperial Court</em> (1904, donated to the Vietnam History Museum); <em>Great Qing Empire Atlas</em> (1905); <em>Provincial Atlas of the Great Qing Empire</em> (1907, Tokyo); <em>Complete Atlas of the Great Qing Empire</em> (1908, Shanghai Commercial Press).</p>',
    'ancient_map_late_qing_prints_img1_caption' => 'Complete Provincial Geographical Map (1904)',
    'ancient_map_late_qing_prints_img2_caption' => 'Great Qing Empire — atlas volume (1905)',
    'ancient_map_late_qing_prints_img3_caption' => 'Complete map of the Great Qing Empire (1907)',
    'ancient_map_late_qing_prints_img4_caption' => 'Guangdong — provincial atlas (1907)',
    'ancient_map_late_qing_prints_img5_caption' => 'Complete Atlas of the Great Qing Empire (1908)',
    'ancient_map_late_qing_prints_img6_caption' => 'Guangdong — complete map (1908)',

    'ancient_map_xinhai_1912_title' => 'Great Qing territory map — 1911 Revolution (1912)',
    'ancient_map_xinhai_1912_year' => '1912',
    'ancient_map_xinhai_1912_body' => '<p><em>Great Qing Territory Map — 1911 Revolution uprising sites</em> — published in <strong>1912</strong> (Meiji 44) by Seihan Printing Cooperative, Osaka, Japan. Held at the University of California, Berkeley (USA).</p>',

    'ancient_map_roc_atlas_title' => 'Republic of China — geographical atlases 1933–1939',
    'ancient_map_roc_atlas_year' => '1933–1939',
    'ancient_map_roc_atlas_body' => '<p>Under the Republic of China, atlases printed in China and Tokyo still place the southern limit at Hainan Island:</p><p><em>Provincial Atlas of the Republic of China</em> (<strong>1933</strong>); <em>National Provincial Atlas, Year 24 of the Republic</em> (<strong>1935</strong>); <em>Atlas of China</em> by Matsuda Hisanami, Tokyo Shikai Bookstore (<strong>1939</strong>) — including mainland and Guangdong provincial maps.</p>',
    'ancient_map_roc_atlas_img1_caption' => 'Complete map of the Republic of China (1933)',
    'ancient_map_roc_atlas_img2_caption' => 'Complete map of the Republic of China (1935)',
    'ancient_map_roc_atlas_img3_caption' => 'Mainland terrain map (1939)',
    'ancient_map_roc_atlas_img4_caption' => 'Guangdong — Atlas of China (1939)',
];
