<?php

return [
    'footer_index' => 'Library',
    'footer_crest_eyebrow' => 'Truth library conclusion',
    'footer_crest_quote' => '“Peace in the South China Sea is built on the foundation of <b>international law</b>.”',
    'footer_crest_sub' => 'No hatred · Only truth',
    'footer_nav_aria' => 'Footer actions',
    'footer_btn_top' => 'Back to top',
    'footer_btn_verdict' => '2016 PCA Award',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Claims to the Nine-Dash Line',
    'footer_brand_eyebrow' => 'Special topic page · Vietnam\'s sovereignty',
    'footer_brand_body' => 'An explanation of the Nine-Dash Line based on objective facts, international law, the 2016 PCA ruling, and historical materials — complementing the in-depth pages on the sovereignty of the two archipelagos <strong>"Paracel Islands and Spratly Islands"</strong>. It refutes China\'s baseless claims with history and evidence.',
    'footer_refs_title' => 'References',
    'footer_ref1' => 'PCA Award, 12 July 2016',
    'footer_ref2' => 'UNCLOS 1982 — full text',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historical documents & old maps',
    'footer_toc_title' => 'Page contents',
    'footer_toc1' => 'What is the Nine-Dash Line',
    'footer_toc2' => 'Origins',
    'footer_toc3' => 'Why it is controversial',
    'footer_toc4' => 'Why the international community rejects it',
    'footer_toc5' => 'Silent witnesses',
    'footer_toc6' => '2016 PCA Award',
    'footer_toc7' => 'Paracel Islands – Spratly Islands',
    'footer_copy_eyebrow' => 'Nonprofit project',
    'footer_copy_title' => 'Paracel Islands – Spratly Islands belong to Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — A special page about the Nine-Dash Line within Vietnam\'s sovereignty ecosystem.',
    'footer_copy_body' => 'An explanation of the Nine-Dash Line claim through <strong>objective facts</strong>, <strong>international law</strong>, the 2016 PCA ruling, and historical materials — complementing the in-depth pages on the sovereignty of the Paracel Islands and Spratly Islands.',
    'footer_copy_ecosystem_aria' => 'Pages in the same project',
    'footer_copy_ecosystem_label' => 'Same ecosystem',
    'footer_copy_disclaimer' => 'This content is for education and awareness; it does not replace the official position of the State of Vietnam.',
    'footer_copy' => '<strong>© :year Nine-Dash Line</strong> — A part of the nonprofit project <strong>Paracel Islands – Spratly Islands belong to Vietnam</strong> within the system: <a href="https://paracelislands.net/en" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/en" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/en" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/en" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/en" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Site content commitments',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 PCA Award',
    'footer_chip3' => 'Historical evidence',
    'footer_chip4' => 'Old maps',
    'footer_chip5' => 'Objective facts',
    'footer_chip6' => 'South China Sea peace',
];
