<?php

return [
    'footer_index' => 'Library',
    'footer_crest_eyebrow' => 'Library of Truths',
    'footer_crest_quote' => '“Peace in the South China Sea is built on the foundation of <b>international law</b>.”',
    'footer_crest_sub' => 'No hatred · Only facts',
    'footer_nav_aria' => 'End-of-page actions',
    'footer_btn_top' => 'Back to Top',
    'footer_btn_verdict' => 'PCA 2016 Award',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Nine-Dash Line',
    'footer_brand_eyebrow' => 'Dedicated page · Sovereignty ecosystem',
    'footer_brand_body' => 'Explains the Nine-Dash Line claim through <strong>objective facts</strong>, <strong>international law</strong>, the 2016 PCA Award, and historical records — complementing in-depth pages on Paracel and Spratly sovereignty. Refuting the claim with evidence, not slogans.',
    'footer_refs_title' => 'References',
    'footer_ref1' => 'PCA Award, 12 July 2016',
    'footer_ref2' => 'UNCLOS 1982 — Full Text',
    'footer_ref3' => 'Limits in the Seas №143 (U.S. DoS)',
    'footer_ref4' => 'Historical Records & Ancient Maps',
    'footer_toc_title' => 'Page Contents',
    'footer_toc1' => 'What Is the Nine-Dash Line',
    'footer_toc2' => 'Origins',
    'footer_toc3' => 'Why It Is Controversial',
    'footer_toc4' => 'Why the International Community Opposes It',
    'footer_toc5' => 'Silent Witnesses',
    'footer_toc6' => 'PCA 2016 Award',
    'footer_toc7' => 'Paracel Islands – Spratly Islands',
    'footer_copy_eyebrow' => 'Non-profit initiative',
    'footer_copy_title' => 'Paracel &amp; Spratly Islands belong to Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — A Nine-Dash Line resource within the sovereignty education ecosystem.',
    'footer_copy_body' => 'Explains the Nine-Dash Line claim through <strong>objective facts</strong>, <strong>international law</strong>, the 2016 PCA Award, and historical records — complementing in-depth pages on Paracel and Spratly sovereignty.',
    'footer_copy_ecosystem_aria' => 'Related project sites',
    'footer_copy_ecosystem_label' => 'Ecosystem',
    'footer_copy_disclaimer' => 'For education and awareness only; not an official statement of the Vietnamese State.',
    'footer_copy' => '<strong>© :year ninedashline.net</strong> — Part of the non-profit <strong>Paracel &amp; Spratly Islands belong to Vietnam</strong> initiative. Ecosystem: <a href="https://paracelislands.net" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Page content commitments',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA Award 2016',
    'footer_chip3' => 'Claim has no legal coordinates',
    'footer_chip4' => 'Historical evidence',
    'footer_chip5' => 'Objective facts',
    'footer_chip6' => 'Non-profit project',
];
