<?php

return [
    'nav_logo_name' => 'Nine-Dash Line',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Nine-Dash Line',
    'nav_rail_aria' => 'Section navigation',
    'nav_rail_what' => 'Definition',
    'nav_rail_origin' => 'Origin',
    'nav_rail_dispute' => 'Controversy',
    'nav_rail_opposition' => 'Opposition',
    'nav_rail_witnesses' => 'Historical Maps',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracel Islands – Spratly Islands',
    'nav_sound_off' => 'Enable background music',
    'nav_sound_on' => 'Disable background music',
    'nav_share' => 'Share',
    'dialog_title' => 'Display Language',
    'language' => 'Language',
    'display_hint' => ':count languages',
    'search_placeholder' => 'Search languages…',
    'cancel' => 'Cancel',
    'apply' => 'Apply',
    'sound_off' => 'Enable background audio',
    'sound_on' => 'Disable background audio',
    'lang_trigger' => 'Select language',
    'close' => 'Close',
    'no_results' => 'No languages found',
    'contribute' => 'Share',
];
