<?php

return [
    'opposition_index' => 'Opposition',
    'opposition_label' => 'Why the international community opposes it',
    'opposition_title' => 'Opposition is based on',
    'opposition_title_accent' => 'law, not emotion',
    'opposition_lead' => 'Soon after the Nine-Dash Line was submitted to the United Nations in 2009, many countries and scholars objected — with specific legal arguments.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'May',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Just one day after China submitted the Nine-Dash Line map to the UN Secretary-General (7 May 2009), these countries successively sent diplomatic notes of protest, rejecting the claim.',
    'opposition_voice1_chip1' => 'Note of protest',
    'opposition_voice1_chip2' => 'Incompatible with UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippines',
    'opposition_voice2_body' => 'Sent a diplomatic letter to the United Nations, stating that China’s claim in the South China Sea was “without basis under international law” — laying the groundwork for the later arbitration case.',
    'opposition_voice2_chip1' => 'Basis for the PCA case',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'U.S. Department of State — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'The analysis showed: maps from different years were inconsistent in the position of the dashed line; the dashed line extended into the mainland rather than using a median line; many features did not qualify as “islands” to generate an EEZ.',
    'opposition_voice3_chip1' => 'Does not meet legal requirements',
    'opposition_voice3_chip2' => 'Official analysis',
    'opposition_voice4_year' => 'Academic',
    'opposition_voice4_title' => '“Historic waters” is outdated',
    'opposition_voice4_body' => 'This concept applies only to bays and waters close to the shore — it cannot cover an entire vast open sea area. In 2003, even Taiwan rejected the “historic waters” policy it had once stated in 1993.',
    'opposition_voice4_chip1' => 'Even Chinese scholars do not agree',
];
