<?php

return [
    'opposition_index' => 'Opposition',
    'opposition_label' => 'Why the International Community Opposes It',
    'opposition_title' => 'Opposition Based on',
    'opposition_title_accent' => 'Law, Not Emotion',
    'opposition_lead' => 'Immediately after the Nine-Dash Line was submitted to the United Nations in 2009, many countries and scholars raised objections — using specific legal arguments.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'May',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Just one day after China submitted the Nine-Dash Line map to the United Nations Secretary-General (7 May 2009), these countries successively sent diplomatic notes of protest rejecting the claim.',
    'opposition_voice1_chip1' => 'Diplomatic Notes of Protest',
    'opposition_voice1_chip2' => 'Inconsistent with UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippines',
    'opposition_voice2_body' => 'Submitted a diplomatic communication to the United Nations, declaring that China\'s claims in the South China Sea were “without basis under international law” — laying the groundwork for the later arbitration case.',
    'opposition_voice2_chip1' => 'Foundation for the PCA Case',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'U.S. Department of State — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'The analysis found that maps from different years were inconsistent in the placement of the line; the line extended toward coastlines rather than following median lines; and many features did not meet the criteria of an “island” capable of generating an EEZ.',
    'opposition_voice3_chip1' => 'Fails to Meet Legal Requirements',
    'opposition_voice3_chip2' => 'Official Analysis',
    'opposition_voice4_year' => 'Academic Scholarship',
    'opposition_voice4_title' => '“Historic Waters” Is an Outdated Concept',
    'opposition_voice4_body' => 'This concept applies only to bays and coastal inlets close to shore — it cannot encompass an entire vast expanse of open sea. In 2003, Taiwan itself also abandoned the “historic waters” policy it had previously articulated in 1993.',
    'opposition_voice4_chip1' => 'Even Chinese Scholars Do Not Agree',
];
