<?php

return [
    'sovereignty_index' => 'Paracel Islands – Spratly Islands',
    'sovereignty_label' => 'The Inevitable Conclusion',
    'sovereignty_title' => 'Paracel Islands – Spratly Islands',
    'sovereignty_title_accent' => 'belong to Vietnam',
    'sovereignty_lead' => 'This site explains the Nine-Dash Line. The concluding section answers the next question: who holds sovereignty over the Paracel Islands and Spratly Islands? Based on the history of administration and international law, the consistent answer is Vietnam.',
    'sovereignty_thesis_label' => 'Synthesis Thesis',
    'sovereignty_thesis_lock1' => 'No legal coordinates',
    'sovereignty_thesis_lock2' => 'Rejected by PCA 2016',
    'sovereignty_thesis_lock3' => 'Historic maps do not encompass it',
    'sovereignty_thesis_body' => 'After the six sections above, three points are clear: the Nine-Dash Line was hand-drawn and has no legal coordinates; the 2016 Arbitral Tribunal rejected the claim; and historic maps of China itself did not encompass the South China Sea. Vietnam’s sovereignty claim is not based on slogans but on the fact that the Vietnamese state — since the Nguyễn Lords period — exercised peaceful and continuous administration when the two archipelagos were still terra nullius.',
    'sovereignty_spine_caption' => 'Milestones of Continuous Administration',
    'sovereignty_spine_title' => 'One Timeline, Without Interruption',
    'sovereignty_spine_range' => '17th century → present',
    'sovereignty_chron1_year' => '17th c.',
    'sovereignty_chron1_title' => 'Hoàng Sa Flotilla',
    'sovereignty_chron1_body' => 'The Nguyễn Lords dispatched the Hoàng Sa Flotilla to survey, chart sea routes, and conduct maritime activities — exercising effective administration.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Emperor Gia Long',
    'sovereignty_chron2_body' => 'Raised the flag in the Paracel Islands, affirming Vietnam’s sovereignty before the contemporary world.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Emperor Minh Mạng',
    'sovereignty_chron3_body' => 'Conducted surveys, erected markers, and recorded the archipelagos on official imperial maps.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuous Succession',
    'sovereignty_chron4_body' => 'France recognized and continued administration; the Paracel Islands were incorporated into Thừa Thiên Province — forming part of the legal foundation of the modern Vietnamese state.',
    'sovereignty_chron5_year' => 'Present',
    'sovereignty_chron5_title' => 'Law and Practice',
    'sovereignty_chron5_body' => 'Vietnam administers its maritime rights through UNCLOS, diplomacy, and archival records; the Nine-Dash Line claim cannot override this evidence.',
    'sovereignty_balance_label' => 'Balance of Evidence',
    'sovereignty_balance_medallion_title' => 'Comparing Both Sides',
    'sovereignty_vn_tag' => 'Vietnam’s Position',
    'sovereignty_vn_title' => 'Sovereignty Established Through State Practice',
    'sovereignty_vn_body' => 'Effective occupation when the territory was terra nullius, followed by open administration over centuries — supported by imperial records, markers, maps, and administrative documents. This approach is consistent with UNCLOS and international practice.',
    'sovereignty_dash_tag' => 'The Nine-Dash Line Position',
    'sovereignty_dash_title' => 'A Claim Cannot Substitute for Evidence',
    'sovereignty_dash_body' => 'A line drawn in 1948, without coordinates, rejected by PCA 2016, and inconsistent with UNCLOS — as demonstrated in Sections 03 through 06. This is why conclusions regarding sovereignty over the two archipelagos cannot be based on the Nine-Dash Line.',
    'sovereignty_seal_quote' => 'Vietnam seeks to resolve disputes through <strong>peaceful means</strong>, on the basis of international law — particularly UNCLOS 1982 — with the goal of a South China Sea characterized by peace, cooperation, and development.',
    'sovereignty_seal_cite' => 'Vietnam’s Position · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Main Project Within the Same Ecosystem',
    'sovereignty_next_title' => 'Read the Full Evidence on the Paracel Islands – Spratly Islands',
    'sovereignty_next_body' => 'The detailed record — documents, maps, timelines, and legal arguments — is available at <strong>paracelislands.net</strong>, which presents a comprehensive examination of sovereignty over the two archipelagos. The page you are reading only connects the logic from the Nine-Dash Line to that conclusion.',
    'sovereignty_next_cta' => 'Open paracelislands.net',
];
