<?php

return [
    'sovereignty_index' => 'Paracel Islands - Spratly Islands',
    'sovereignty_label' => 'The inevitable conclusion',
    'sovereignty_title' => 'Paracel Islands - Spratly Islands',
    'sovereignty_title_accent' => 'belong to Vietnam',
    'sovereignty_lead' => 'This page explains the Nine-Dash Line. The conclusion answers the next question: who has sovereignty over the two archipelagos, the Paracel Islands and the Spratly Islands? Based on historical administration and international law, the consistent answer is Vietnam.',
    'sovereignty_thesis_label' => 'Overall thesis',
    'sovereignty_thesis_lock1' => 'No legal coordinates',
    'sovereignty_thesis_lock2' => 'Rejected by PCA 2016',
    'sovereignty_thesis_lock3' => 'Old maps do not cover it',
    'sovereignty_thesis_body' => 'After the six sections above, three points are clear: the Nine-Dash Line is hand-drawn and has no legal coordinates; the 2016 arbitral tribunal rejected the claim; and China’s own old maps do not cover the East Sea. Vietnam’s sovereignty is not based on slogans, but on the fact that the Vietnamese state — since the era of the Nguyễn lords — has administered the two archipelagos peacefully and continuously when they were still terra nullius.',
    'sovereignty_spine_caption' => 'Continuous administration milestones',
    'sovereignty_spine_title' => 'One timeline, uninterrupted',
    'sovereignty_spine_range' => '17th century → present',
    'sovereignty_chron1_year' => '17th century',
    'sovereignty_chron1_title' => 'The Hoàng Sa Team',
    'sovereignty_chron1_body' => 'The Nguyễn lords sent the Hoàng Sa Team to survey, measure sea routes, and conduct maritime exploitation — exercising actual administrative control.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'King Gia Long',
    'sovereignty_chron2_body' => 'He raised the flag on the Paracel Islands, affirming Vietnam’s sovereignty before the world of that time.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'King Minh Mạng',
    'sovereignty_chron3_body' => 'He ordered surveys, erected steles, and recorded the archipelagos on the court’s official maps.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuous succession',
    'sovereignty_chron4_body' => 'France recognized and continued administration; Paracel was incorporated into Thừa Thiên Province — the foundation for today’s Vietnamese state.',
    'sovereignty_chron5_year' => 'Present',
    'sovereignty_chron5_title' => 'Law and practice',
    'sovereignty_chron5_body' => 'Vietnam administers according to UNCLOS, diplomacy, and archival records; the Nine-Dash Line claim cannot replace this evidence.',
    'sovereignty_balance_label' => 'Balancing the evidence',
    'sovereignty_balance_medallion_title' => 'Comparing both sides',
    'sovereignty_vn_tag' => 'Vietnam’s side',
    'sovereignty_vn_title' => 'Sovereignty established through acts',
    'sovereignty_vn_body' => 'Actual occupation while the land was still terra nullius, followed by open administration over centuries — with royal edicts, steles, maps, and administrative records. This approach is consistent with UNCLOS and international practice.',
    'sovereignty_dash_tag' => 'Nine-Dash Line side',
    'sovereignty_dash_title' => 'A claim cannot outweigh evidence',
    'sovereignty_dash_body' => 'A line drawn in 1948, with no coordinates, was rejected by PCA 2016 and is contrary to UNCLOS — as Sections 03 to 06 have shown. That is why the conclusion on sovereignty over the two archipelagos cannot rely on the Nine-Dash Line.',
    'sovereignty_seal_quote' => 'Vietnam resolves disputes by <strong>peaceful means</strong>, on the basis of international law — especially UNCLOS 1982 — with the aim of a peaceful, cooperative, and developing East Sea.',
    'sovereignty_seal_cite' => 'Vietnam’s position · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Core project in the same ecosystem',
    'sovereignty_next_title' => 'Read the full evidence on the Paracel Islands - Spratly Islands',
    'sovereignty_next_body' => 'The detailed dossier — documents, maps, timeline, and legal arguments — is on <strong>paracelislands.net</strong>, where the sovereignty issue of the two archipelagos is presented comprehensively. The page you are reading only connects the logic from the Nine-Dash Line to that conclusion.',
    'sovereignty_next_cta' => 'Open paracelislands.net',
];
