<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'International Ruling',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'three “No’s”',
    'verdict_lead' => 'On 12 July 2016, the Permanent Court of Arbitration (PCA) in The Hague — constituted under Annex VII of UNCLOS in the case brought by the Philippines against China — issued a ruling rejecting the Nine-Dash Line claim. <em>Click each card to read the original wording.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'historic rights',
    'verdict_card1_short' => 'There is no legal basis for China to claim historic rights to resources within the waters enclosed by the Nine-Dash Line.',
    'verdict_card1_quote' => '“There was no legal basis for China to claim historic rights to resources within the sea areas falling within the Nine-Dash Line.”',
    'verdict_card1_more' => '+ Read the ruling',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'feature generating an EEZ',
    'verdict_card2_short' => 'No feature in the Spratly Islands is capable of generating an exclusive economic zone for China — including Itu Aba.',
    'verdict_card2_quote' => '“No feature in the Spratly Islands is capable of generating an exclusive economic zone.”',
    'verdict_card2_more' => '+ Read the ruling',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'lawful conduct',
    'verdict_card3_short' => 'China violated the Philippines’ sovereign rights, interfered with fishing activities, and caused harm to the marine environment.',
    'verdict_card3_quote' => '“China had violated the Philippines’ sovereign rights, interfered with fishing activities at Scarborough Shoal, and caused severe harm to the coral reef environment.”',
    'verdict_card3_more' => '+ Read the ruling',
    'verdict_extra1' => 'The Nine-Dash Line drawn unilaterally by China is <strong>inconsistent</strong> with UNCLOS 1982.',
    'verdict_extra2' => 'China caused damage to the Spratly Islands ecosystem through excessive exploitation and artificial island construction.',
    'verdict_extra3' => 'China’s actions increased the risk of conflict with the Philippines.',
    'verdict_extra4' => 'Itu Aba (controlled by Taiwan) is also incapable of generating an EEZ.',
    'verdict_subtitle' => 'Why does it conflict with UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 clearly defines maritime zones based on the baselines of coastal states. The Nine-Dash Line claim extends beyond this framework and therefore cannot be reconciled with it.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorial Sea (nautical miles)',
    'verdict_zone1_body' => 'A maritime zone under national sovereignty, measured from the baseline.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Exclusive Economic Zone',
    'verdict_zone2_body' => 'EEZ — within this zone, the coastal state has sovereign rights over natural resources.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Continental Shelf (maximum, nautical miles)',
    'verdict_zone3_body' => 'Rights over seabed resources, determined according to geological conditions.',
    'verdict_foot' => 'Within this framework, “historic rights” covering an entire expanse of open sea — as implied by the Nine-Dash Line — <em>have been superseded</em> by the legal regime of UNCLOS, of which China itself is a party.',
];
