<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'International ruling',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'three "Noes"',
    'verdict_lead' => 'On July 12, 2016, the Permanent Court of Arbitration (PCA) in The Hague — constituted under Annex VII of UNCLOS in the case brought by the Philippines against China — issued a ruling rejecting the Nine-Dash Line claim. <em>Click each card to read the full text.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'historical rights',
    'verdict_card1_short' => 'There is no legal basis for China to assert historical rights over resources in the waters within the Nine-Dash Line.',
    'verdict_card1_quote' => '"There is no legal basis for China to claim historical rights to resources within the waters encompassed by the Nine-Dash Line."',
    'verdict_card1_more' => '+ Read the ruling',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'features that create an EEZ',
    'verdict_card2_short' => 'No feature in the Spratly Islands is entitled to generate an exclusive economic zone for China — including Itu Aba.',
    'verdict_card2_quote' => '"No feature in the Spratly Islands is capable of generating an exclusive economic zone."',
    'verdict_card2_more' => '+ Read the ruling',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'lawful conduct',
    'verdict_card3_short' => 'China violated the Philippines\' sovereign rights, interfered with fishing, and harmed the marine environment.',
    'verdict_card3_quote' => '"China violated the Philippines\' sovereign rights, interfered with fishing at Scarborough Shoal, and caused severe harm to the coral reef environment."',
    'verdict_card3_more' => '+ Read the ruling',
    'verdict_extra1' => 'The Nine-Dash Line drawn unilaterally by China <strong>is not consistent</strong> with UNCLOS 1982.',
    'verdict_extra2' => 'China has damaged the Spratly Islands ecosystem through overexploitation and artificial island construction.',
    'verdict_extra3' => 'China\'s actions have increased the risk of conflict with the Philippines.',
    'verdict_extra4' => 'Itu Aba Island (controlled by Taiwan) also cannot generate an EEZ.',
    'verdict_subtitle' => 'Why does it conflict with UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 clearly defines maritime zones based on the baseline of the coastal state. The Nine-Dash Line claim goes beyond this framework, so the two cannot be reconciled.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorial sea (nautical miles)',
    'verdict_zone1_body' => 'A national sea area under sovereign control, measured from the baseline.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Exclusive economic zone',
    'verdict_zone2_body' => 'EEZ — within this area, the coastal state has sovereign rights over resources.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Continental shelf (maximum, nautical miles)',
    'verdict_zone3_body' => 'Rights over seabed resources, subject to established geological conditions.',
    'verdict_foot' => 'Within this framework, a "historical right" covering an entire open sea — as implied by the Nine-Dash Line — <em>has been replaced</em> by the legal regime of UNCLOS, to which China itself is also a party.',
];
