<?php

return [
    'witnesses_index' => 'Ancient Maps',
    'witnesses_label' => 'Ancient Maps of China',
    'witnesses_title' => 'The southernmost point reaches only',
    'witnesses_title_accent' => 'Hainan Island',
    'witnesses_lead' => 'Ancient maps drawn by Chinese authors — arranged chronologically — all show <em>Hainan Island as the southernmost point</em> of China, with no Paracel Islands or Spratly Islands. Materials compiled from <em>Vietnam’s national sovereignty over the two archipelagos of Paracel Islands and Spratly Islands</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Examine with Magnifier',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— southernmost territorial limit —',
    'witnesses_map1_svg_era' => 'Song Dynasty · 1136',
    'witnesses_map1_title' => 'Song Dynasty Map, 1136',
    'witnesses_map1_body' => 'China\'s territory ended at Hainan Island — the Paracel Islands and Spratly Islands lay beyond its borders.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anville boundary',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville Map, 1735',
    'witnesses_map2_body' => 'Drawn by J.-B. B. d\'Anville; a 1740 copy was later presented by a German Chancellor to Chinese leaders. The territory of the Qing Dynasty ended at Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"southernmost point of China"',
    'witnesses_map3_svg_era' => 'Imperial Provinces Atlas · 1904',
    'witnesses_map3_title' => 'Complete Geographic Map of the Imperial Provinces',
    'witnesses_map3_body' => 'Printed by the Qing Dynasty — clearly identifying Hainan Island as the southernmost point of Chinese territory.',
    'witnesses_quote' => 'Maps published by China itself have never placed the Paracel Islands - Spratly Islands within its territory.',
    'witnesses_timeline_aria' => 'Chronological timeline of ancient Chinese maps',
    'witnesses_year_aria' => 'Date',
    'lightbox_aria' => 'View enlarged image',
    'lightbox_close' => 'Close',
    'lightbox_prev' => 'Previous image',
    'lightbox_next' => 'Next image',
];
