<?php

return [
    'footer_index' => 'ספרייה',
    'footer_crest_eyebrow' => 'חותם ספריית האמת',
    'footer_crest_quote' => '“השלום בים סין הדרומי נבנה על יסוד <b>המשפט הבין־לאומי</b>.”',
    'footer_crest_sub' => 'ללא שנאה · רק אמת',
    'footer_nav_aria' => 'פעולות תחתית העמוד',
    'footer_btn_top' => 'חזרה לראש העמוד',
    'footer_btn_verdict' => 'פסק הדין של ה-PCA משנת 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'התביעה על קו תשע המקפים',
    'footer_brand_eyebrow' => 'עמוד נושא · ריבונות וייטנאם',
    'footer_brand_body' => 'הסבר על קו תשע המקפים באמצעות אמת אובייקטיבית, המשפט הבין־לאומי, פסק הדין של ה-PCA משנת 2016 ומקורות היסטוריים — כהשלמה לעמודים המעמיקים על הריבונות על שני הארכיפלגים <strong>"איי פארסל ואיי ספרטלי"</strong>. הפרכת התביעה הבלתי־מוצדקת של סין באמצעות היסטוריה וראיות.',
    'footer_refs_title' => 'מקורות עיון',
    'footer_ref1' => 'פסק הדין של ה-PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — הטקסט המלא',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'מקורות היסטוריים ומפות עתיקות',
    'footer_toc_title' => 'תוכן העניינים של העמוד',
    'footer_toc1' => 'מהו קו תשע המקפים',
    'footer_toc2' => 'מקור',
    'footer_toc3' => 'מדוע זה מעורר מחלוקת',
    'footer_toc4' => 'מדוע הקהילה הבין־לאומית מתנגדת',
    'footer_toc5' => 'עדים שקטים',
    'footer_toc6' => 'פסק הדין של ה-PCA 2016',
    'footer_toc7' => 'איי פארסל – איי ספרטלי',
    'footer_copy_eyebrow' => 'פרויקט ללא מטרות רווח',
    'footer_copy_title' => 'איי פארסל – איי ספרטלי שייכים לוייטנאם',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — עמוד נושא על קו תשע המקפים במערכת האקולוגית של ריבונות וייטנאם.',
    'footer_copy_body' => 'הסבר התביעה של קו תשע המקפים באמצעות <strong>אמת אובייקטיבית</strong>, <strong>המשפט הבין־לאומי</strong>, פסק הדין של ה-PCA משנת 2016 ומקורות היסטוריים — כהשלמה לעמודים המעמיקים על הריבונות על איי פארסל ואיי ספרטלי.',
    'footer_copy_ecosystem_aria' => 'העמודים של אותו הפרויקט',
    'footer_copy_ecosystem_label' => 'אותה מערכת אקולוגית',
    'footer_copy_disclaimer' => 'התוכן מיועד לחינוך ולהעלאת מודעות; אינו מחליף את העמדה הרשמית של מדינת וייטנאם.',
    'footer_copy' => '<strong>© :year קו תשע המקפים</strong> — חלק מפרויקט ללא מטרות רווח <strong>איי פארסל – איי ספרטלי שייכים לוייטנאם</strong> במערכת: <a href="https://paracelislands.net/he" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/he" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/he" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/he" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/he" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'התחייבות לתוכן העמוד',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'פסק הדין של ה-PCA 2016',
    'footer_chip3' => 'ראיות היסטוריות',
    'footer_chip4' => 'מפות עתיקות',
    'footer_chip5' => 'אמת אובייקטיבית',
    'footer_chip6' => 'שלום בים סין הדרומי',
];
