<?php

return [
    'footer_index' => 'ספרייה',
    'footer_crest_eyebrow' => 'חותמת הספרייה של האמת',
    'footer_crest_quote' => '“השלום בים סין הדרומי נבנה על יסוד <b>המשפט הבינלאומי</b>.”',
    'footer_crest_sub' => 'ללא שנאה · רק האמת',
    'footer_nav_aria' => 'פעולות בתחתית העמוד',
    'footer_btn_top' => 'חזרה לראש העמוד',
    'footer_btn_verdict' => 'פסק הדין של PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'קו תשע המקפים',
    'footer_brand_body' => 'אתר הסבר המבוסס על עובדות אובייקטיביות, המשפט הבינלאומי ומסמכים היסטוריים — דוחה את תביעת קו תשע המקפים באמצעות ראיות, לא באמצעות סיסמאות.',
    'footer_refs_title' => 'מקורות עיון',
    'footer_ref1' => 'פסק הדין של PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — הטקסט המלא',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'חומרים היסטוריים ומפות עתיקות',
    'footer_toc_title' => 'תוכן העניינים של האתר',
    'footer_toc1' => 'מהו קו תשע המקפים',
    'footer_toc2' => 'מקור',
    'footer_toc3' => 'מדוע הוא מעורר מחלוקת',
    'footer_toc4' => 'מדוע הקהילה הבינלאומית מתנגדת',
    'footer_toc5' => 'עדים שקטים',
    'footer_toc6' => 'פסק הדין של PCA 2016',
    'footer_toc7' => 'איי פארסל – איי ספרטלי',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — האמת האובייקטיבית על ים סין הדרומי.<br>מערכת אקולוגית: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'ללא קואורדינטות',
];
