<?php

return [
    'footer_index' => 'ספרייה',
    'footer_crest_eyebrow' => 'חותם ספריית האמת',
    'footer_crest_quote' => '“השלום בים סין הדרומי נבנה על יסודות <b>המשפט הבין־לאומי</b>.”',
    'footer_crest_sub' => 'ללא שנאה · רק אמת',
    'footer_nav_aria' => 'פעולות תחתונות',
    'footer_btn_top' => 'חזרה לראש העמוד',
    'footer_btn_verdict' => 'פסק הדין של PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'תביעת קו תשע המקפים',
    'footer_brand_eyebrow' => 'עמוד专题 · ריבונות וייטנאם',
    'footer_brand_body' => 'הסבר על קו תשע המקפים באמצעות אמת אובייקטיבית, המשפט הבין־לאומי, פסק הדין של PCA 2016 ומסמכים היסטוריים — כהשלמה לעמודי העומק על ריבונות שני הארכיפלגים <strong>"איי פארסל ואיי ספרטלי"</strong>. שלילת תביעותיה הבלתי־מוצדקות של סין באמצעות היסטוריה וראיות.',
    'footer_refs_title' => 'מקורות עיון',
    'footer_ref1' => 'פסק הדין של PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — הטקסט המלא',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'חומרים היסטוריים ומפות עתיקות',
    'footer_toc_title' => 'תוכן העמוד',
    'footer_toc1' => 'מהו קו תשע המקפים',
    'footer_toc2' => 'מקור',
    'footer_toc3' => 'מדוע הוא מעורר מחלוקת',
    'footer_toc4' => 'מדוע הקהילה הבין־לאומית מתנגדת',
    'footer_toc5' => 'עדות שקטה',
    'footer_toc6' => 'פסק הדין של PCA 2016',
    'footer_toc7' => 'איי פארסל – איי ספרטלי',
    'footer_copy_eyebrow' => 'פרויקט ללא מטרות רווח',
    'footer_copy_title' => 'איי פארסל – איי ספרטלי הם של וייטנאם',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — עמוד专题 על קו תשע המקפים במערכת הריבונות של וייטנאם.',
    'footer_copy_body' => 'הסבר על תביעת קו תשע המקפים באמצעות <strong>אמת אובייקטיבית</strong>, <strong>המשפט הבין־לאומי</strong>, פסק הדין של PCA 2016 ומסמכים היסטוריים — כהשלמה לעמודי העומק על ריבונות שני הארכיפלגים איי פארסל ואיי ספרטלי.',
    'footer_copy_ecosystem_aria' => 'העמודים שבאותו פרויקט',
    'footer_copy_ecosystem_label' => 'באותה מערכת אקולוגית',
    'footer_copy_disclaimer' => 'התוכן מיועד לחינוך ולהגברת המודעות; אינו מחליף את עמדתה הרשמית של מדינת וייטנאם.',
    'footer_copy' => '<strong>© :year קו תשע המקפים</strong> — חלק מפרויקט ללא מטרות רווח <strong>איי פארסל – איי ספרטלי הם של וייטנאם</strong> במערכת: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'התחייבות התוכן של העמוד',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'פסק הדין של PCA 2016',
    'footer_chip3' => 'ראיות היסטוריות',
    'footer_chip4' => 'מפות עתיקות',
    'footer_chip5' => 'אמת אובייקטיבית',
    'footer_chip6' => 'שלום בים סין הדרומי',
];
