<?php

return [
    'nav_logo_name' => 'קו תשע המקפים',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'קו תשע המקפים',
    'nav_rail_aria' => 'ניווט לפי נושא',
    'nav_rail_what' => 'הגדרה',
    'nav_rail_origin' => 'מקור',
    'nav_rail_dispute' => 'מחלוקת',
    'nav_rail_opposition' => 'התנגדות',
    'nav_rail_witnesses' => 'מפות עתיקות',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'איי פארסל - איי ספרטלי',
    'nav_sound_off' => 'הפעל מוזיקת רקע',
    'nav_sound_on' => 'כבה מוזיקת רקע',
    'nav_share' => 'שיתוף',
    'dialog_title' => 'שפת תצוגה',
    'language' => 'שפה',
    'display_hint' => ':count שפות',
    'search_placeholder' => 'חיפוש שפה…',
    'cancel' => 'ביטול',
    'apply' => 'החל',
    'sound_off' => 'הפעלת שמע רקע',
    'sound_on' => 'כיבוי שמע רקע',
    'lang_trigger' => 'בחר שפה',
    'close' => 'סגירה',
    'no_results' => 'לא נמצאו שפות',
    'contribute' => 'שיתוף',
];
