<?php

return [
    'opposition_index' => 'התנגדות',
    'opposition_label' => 'מדוע הקהילה הבינלאומית מתנגדת',
    'opposition_title' => 'ההתנגדות מבוססת על',
    'opposition_title_accent' => 'חוק, לא על רגשות',
    'opposition_lead' => 'מיד לאחר שהקו תשע המקפים הוגש לאו"ם בשנת 2009, מדינות רבות וחוקרים התנגדו לו — בטיעונים משפטיים קונקרטיים.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'מאי',
    'opposition_voice1_title' => 'וייטנאם · מלזיה · אינדונזיה',
    'opposition_voice1_body' => 'יום אחד בלבד לאחר שסין הגישה את מפת קו תשע המקפים למזכ"ל האו"ם (7/5/2009), מדינות אלו שלחו בזו אחר זו איגרות מחאה דיפלומטיות, ודחו את התביעה.',
    'opposition_voice1_chip1' => 'איגרת מחאה',
    'opposition_voice1_chip2' => 'אינו תואם את UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'הפיליפינים',
    'opposition_voice2_body' => 'נשלח מכתב דיפלומטי לאו"ם, שבו נקבע כי תביעתה של סין בים סין הדרומי היא "חסרת בסיס לפי המשפט הבינלאומי" — תשתית לתביעה לבית הדין לבוררות שבאה לאחר מכן.',
    'opposition_voice2_chip1' => 'תשתית לתביעת PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'משרד החוץ של ארצות הברית — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'הניתוח הראה: במפות משנים שונות יש חוסר עקביות במיקום קו הגבול; הקו חודר אל היבשה במקום להסתמך על קו האמצע; ישויות רבות אינן עומדות בתנאי הסף של "אי" לצורך קבלת EEZ.',
    'opposition_voice3_chip1' => 'אינו עומד בתנאים המשפטיים',
    'opposition_voice3_chip2' => 'ניתוח רשמי',
    'opposition_voice4_year' => 'אקדמי',
    'opposition_voice4_title' => '"מים היסטוריים" — תפיסה מיושנת',
    'opposition_voice4_body' => 'מושג זה חל רק על מפרצים, לשונות ים ומים צמודי-חוף — ואינו יכול לחול על אזור ים פתוח ורחב היקף. בשנת 2003, גם טייוואן עצמה דחתה את מדיניות "המים ההיסטוריים" שנזכרה ב-1993.',
    'opposition_voice4_chip1' => 'אפילו חוקרים סינים אינם תמימי דעים',
];
