<?php

return [
    'opposition_index' => 'התנגדות',
    'opposition_label' => 'מדוע הקהילה הבין־לאומית מתנגדת',
    'opposition_title' => 'ההתנגדות מבוססת על',
    'opposition_title_accent' => 'החוק, לא על רגשות',
    'opposition_lead' => 'מיד לאחר שקו תשע המקפים הוגש לאו"ם בשנת 2009, מדינות רבות וחוקרים רבים התנגדו — באמצעות נימוקים משפטיים קונקרטיים.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'מאי',
    'opposition_voice1_title' => 'וייטנאם · מלזיה · אינדונזיה',
    'opposition_voice1_body' => 'יום אחד בלבד לאחר שסין הגישה את מפת קו תשע המקפים למזכ"ל האו"ם (7/5/2009), מדינות אלה שלחו בזו אחר זו איגרות רשמיות של התנגדות, ודחו את התביעה.',
    'opposition_voice1_chip1' => 'איגרת מחאה רשמית',
    'opposition_voice1_chip2' => 'אינה תואמת את UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'הפיליפינים',
    'opposition_voice2_body' => 'נשלח מכתב דיפלומטי לאו"ם, שבו הוצהר כי תביעתה של סין בים סין הדרומי היא “ללא בסיס על פי המשפט הבין־לאומי” — תשתית לתביעה לבית הדין לבוררות שהוגשה לאחר מכן.',
    'opposition_voice2_chip1' => 'תשתית לתביעת PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'משרד החוץ של ארצות הברית — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'הניתוח הראה: מפות מן השנים השונות אינן עקביות לגבי מיקום הקו; הקו חודר אל היבשה במקום להישען על קו האמצע; ומספר ישויות אינן עומדות בתנאי הסף של “אי” כדי לזכות ב-EEZ.',
    'opposition_voice3_chip1' => 'אינו עומד בתנאים המשפטיים',
    'opposition_voice3_chip2' => 'ניתוח רשמי',
    'opposition_voice4_year' => 'אקדמי',
    'opposition_voice4_title' => '“מימי היסטוריים” הוא מושג מיושן',
    'opposition_voice4_body' => 'מושג זה חל רק על מפרצים ומפרצונים הסמוכים לחוף — ואינו יכול לכסות אזור ימי פתוח רחב היקף. בשנת 2003 גם טייוואן עצמה דחתה את מדיניות “המימים ההיסטוריים” שהועלתה בשנת 1993.',
    'opposition_voice4_chip1' => 'אפילו חוקרים מסין אינם תמימי דעים',
];
