<?php

return [
    'sovereignty_index' => 'איי פארסל - איי ספרטלי',
    'sovereignty_label' => 'המסקנה המתבקשת',
    'sovereignty_title' => 'איי פארסל - איי ספרטלי',
    'sovereignty_title_accent' => 'הם של וייטנאם',
    'sovereignty_lead' => 'עמוד זה מסביר את קו תשע המקפים. החלק המסכם עונה על השאלה הבאה: למי יש ריבונות על שני הארכיפלגים איי פארסל ואיי ספרטלי? לפי ההיסטוריה של הניהול והמשפט הבינלאומי, התשובה העקבית היא וייטנאם.',
    'sovereignty_thesis_label' => 'הטענה המסכמת',
    'sovereignty_thesis_lock1' => 'אין קואורדינטות משפטיות',
    'sovereignty_thesis_lock2' => 'פסק הבוררות PCA 2016 דחה',
    'sovereignty_thesis_lock3' => 'מפות עתיקות לא כיסו',
    'sovereignty_thesis_body' => 'לאחר ששת הסעיפים שלעיל, שלוש נקודות ברורות: קו תשע המקפים צויר ביד, ללא קואורדינטות משפטיות; פסק הבוררות של 2016 דחה את התביעה; והמפות העתיקות של סין עצמה לא כיסו את ים סין הדרומי. הריבונות של וייטנאם אינה נשענת על סיסמאות אלא על כך שמדינת וייטנאם — עוד מתקופת שליטי נגויין — ניהלה את האיים בשלום וברציפות כאשר שני הארכיפלגים היו עדיין טרה נוליוס.',
    'sovereignty_spine_caption' => 'ציוני דרך של ניהול מתמשך',
    'sovereignty_spine_title' => 'ציר זמן אחד, ללא הפרעה',
    'sovereignty_spine_range' => 'המאה ה־17 → היום',
    'sovereignty_chron1_year' => 'המאה ה־17',
    'sovereignty_chron1_title' => 'צוות Hoàng Sa',
    'sovereignty_chron1_body' => 'שליטי נגויין שלחו את צוות Hoàng Sa לסקר, למדוד מסלולי שיט ולנצל את הים — מימוש של סמכות ניהול בפועל.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'הקיסר גיה לונג',
    'sovereignty_chron2_body' => 'הניף דגל על איי פארסל, ובכך אישר את ריבונותה של וייטנאם בפני העולם בן התקופה.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'הקיסר מין מאנג',
    'sovereignty_chron3_body' => 'מדד, הקים מצבות ורשם את הארכיפלגים במפות הרשמיות של החצר.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'המשכיות של ירושה',
    'sovereignty_chron4_body' => 'צרפת הכירה והמשיכה בניהול; סיפחה את איי פארסל למחוז ת\'ואה תיין — יסוד למדינת וייטנאם של ימינו.',
    'sovereignty_chron5_year' => 'כיום',
    'sovereignty_chron5_title' => 'חוק ומציאות',
    'sovereignty_chron5_body' => 'וייטנאם מנהלת בהתאם ל-UNCLOS, לדיפלומטיה ולתיעוד הארכיוני; תביעת קו תשע המקפים אינה יכולה להחליף ראיות אלה.',
    'sovereignty_balance_label' => 'איזון הראיות',
    'sovereignty_balance_medallion_title' => 'השוואת שני הצדדים',
    'sovereignty_vn_tag' => 'הצד הווייטנאמי',
    'sovereignty_vn_title' => 'ריבונות שנקבעה באמצעות מעשה',
    'sovereignty_vn_body' => 'חזקה ממשית כאשר הארץ הייתה עדיין טרה נוליוס, ולאחר מכן ניהול גלוי לאורך מאות שנים — עם צווים קיסריים, מצבות, מפות ותיקי מינהל. דרך זו תואמת את UNCLOS ואת הנוהג הבינלאומי.',
    'sovereignty_dash_tag' => 'הצד של קו תשע המקפים',
    'sovereignty_dash_title' => 'תביעה שאינה משלימה ראיות',
    'sovereignty_dash_body' => 'קו שנשרטט ב-1948, ללא קואורדינטות, שנדחה בידי PCA 2016 וסותר את UNCLOS — כפי שהוצג בסעיפים 03 עד 06. לכן המסקנה לגבי ריבונותם של שני הארכיפלגים אינה יכולה להישען על קו תשע המקפים.',
    'sovereignty_seal_quote' => 'וייטנאם פותרת סכסוכים באמצעות <strong>אמצעים של שלום</strong>, על בסיס המשפט הבינלאומי — במיוחד UNCLOS 1982 — במטרה להוביל לים סין הדרומי של שלום, שיתוף פעולה ופיתוח.',
    'sovereignty_seal_cite' => 'עמדתה של וייטנאם · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'הפרויקט המרכזי באותה מערכת אקולוגית',
    'sovereignty_next_title' => 'קראו את הראיות המלאות על איי פארסל - איי ספרטלי',
    'sovereignty_next_body' => 'התיק המפורט — מסמכים, מפות, ציר זמן וטיונים משפטיים — נמצא באתר <strong>paracelislands.net</strong>, המציג באופן מקיף את נושא הריבונות על שני הארכיפלגים. הדף שאתם קוראים מחבר באופן לוגי מקו תשע המקפים אל המסקנה הזו.',
    'sovereignty_next_cta' => 'פתחו את paracelislands.net',
];
