<?php

return [
    'witnesses_index' => 'מפות עתיקות',
    'witnesses_label' => 'מפות עתיקות של סין',
    'witnesses_title' => 'הקצה הדרומי מגיע רק עד',
    'witnesses_title_accent' => 'אי היינאן',
    'witnesses_lead' => 'המפות העתיקות שנשרטטו בידי מחברים סינים — מסודרות לפי זמן — מציגות כולן את <em>אי היינאן כנקודה הדרומית ביותר</em> של סין, ללא איי פארסל או איי ספרטלי. החומר נערך לפי <em>ריבונותה של מדינת וייטנאם בשני הארכיפלגים איי פארסל ואיי ספרטלי</em> (טרונג מין דוק, 2015).',
    'witnesses_hint' => '⌖ בחינת זכוכית מגדלת',
    'witnesses_map1_svg_hainan' => 'היינאן 海南',
    'witnesses_map1_svg_south' => '— הקצה הדרומי של השטח —',
    'witnesses_map1_svg_era' => 'שושלת סונג · 1136',
    'witnesses_map1_title' => 'מפת שושלת סונג, 1136',
    'witnesses_map1_body' => 'שטחה של סין נעצר באי היינאן — איי פארסל ואיי ספרטלי נמצאים מחוץ לתחום הריבוני.',
    'witnesses_map2_svg_hainan' => 'היינאן',
    'witnesses_map2_svg_south' => 'גבול ד\'אןויל',
    'witnesses_map2_svg_era' => 'ד\'אןויל · 1735',
    'witnesses_map2_title' => 'מפת ד\'אןויל, 1735',
    'witnesses_map2_body' => 'צוירה בידי J.-B. B. d\'Anville; העתק מ-1740 הוענק פעם על ידי קנצלר גרמניה למנהיג סין. שטח שושלת צ\'ינג נעצר בהיינאן.',
    'witnesses_map3_svg_hainan' => '海南 היינאן',
    'witnesses_map3_svg_south' => '"הקצה הדרומי של סין"',
    'witnesses_map3_svg_era' => 'העידן הקיסרי · 1904',
    'witnesses_map3_title' => 'אטלס הגאוגרפיה של מחוזות קיסריים',
    'witnesses_map3_body' => 'הודפס בידי שושלת צ\'ינג — מציין בבירור כי הקצה הדרומי של שטח סין הוא אי היינאן.',
    'witnesses_quote' => 'המפות שפרסמה סין עצמה לא ציירו את איי פארסל - איי ספרטלי בתוך שטחה.',
    'witnesses_timeline_aria' => 'ציר הזמן של המפות העתיקות של סין',
    'witnesses_year_aria' => 'תיארוך',
    'lightbox_aria' => 'צפייה בתמונה מוגדלת',
    'lightbox_close' => 'סגירה',
    'lightbox_prev' => 'התמונה הקודמת',
    'lightbox_next' => 'התמונה הבאה',
];
