<?php

return [
    'footer_index' => 'Kutubxona',
    'footer_crest_eyebrow' => 'Kutubxonani faktlar bilan yakunlash',
    'footer_crest_quote' => '“Janubiy Xitoy dengizida tinchlikning asosi <b>xalqaro huquq</b>dir.”',
    'footer_crest_sub' => 'Nafrat yo‘q · Faqat haqiqat',
    'footer_nav_aria' => 'Sahifa pastidagi harakatlar',
    'footer_btn_top' => 'Yuqoriga qaytish',
    'footer_btn_verdict' => 'PCA 2016 qarori',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'To\'qqiz chiziqli chegara da\'vosi',
    'footer_brand_eyebrow' => 'Maxsus sahifa · Vyetnam suvereniteti',
    'footer_brand_body' => 'To\'qqiz chiziqli chegarani obyektiv haqiqat, xalqaro huquq, PCA 2016 qarori va tarixiy manbalar orqali izohlash — <strong>"Parasel orollari va Spratli orollari"</strong> ustidan suverenitetga bag‘ishlangan chuqur sahifalarga qo‘shimcha. Xitoyning asossiz da\'vosini tarix va dalillar bilan rad etadi.',
    'footer_refs_title' => 'Manbalar',
    'footer_ref1' => 'PCA qarori, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — to‘liq matn',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tarixiy materiallar va qadimiy xaritalar',
    'footer_toc_title' => 'Sahifa mundarijasi',
    'footer_toc1' => 'To\'qqiz chiziqli chegara nima',
    'footer_toc2' => 'Kelib chiqishi',
    'footer_toc3' => 'Nega bahsli',
    'footer_toc4' => 'Nega xalqaro hamjamiyat qarshi',
    'footer_toc5' => 'Jim guvohlar',
    'footer_toc6' => 'PCA 2016 qarori',
    'footer_toc7' => 'Parasel orollari – Spratli orollari',
    'footer_copy_eyebrow' => 'Nodavlat loyiha',
    'footer_copy_title' => 'Parasel orollari – Spratli orollari Vyetnamniki',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Vyetnam suvereniteti ekotizimidagi To\'qqiz chiziqli chegara haqidagi maxsus sahifa.',
    'footer_copy_body' => 'To\'qqiz chiziqli chegara da\'vosini <strong>obyektiv haqiqat</strong>, <strong>xalqaro huquq</strong>, PCA 2016 qarori va tarixiy manbalar orqali izohlash — Parasel orollari va Spratli orollari suverenitetiga bag‘ishlangan chuqur sahifalarga qo‘shimcha.',
    'footer_copy_ecosystem_aria' => 'Bir loyihadagi boshqa sahifalar',
    'footer_copy_ecosystem_label' => 'Bir xil ekotizim',
    'footer_copy_disclaimer' => 'Mazmun ta’lim va xabardorlikni oshirish uchun mo‘ljallangan; Vyetnam Davlatining rasmiy nuqtai nazarini almashtirmaydi.',
    'footer_copy' => '<strong>© :year To\'qqiz chiziqli chegara</strong> — Nodavlat loyiha <strong>Parasel orollari – Spratli orollari Vyetnamniki</strong>ning bir qismi, quyidagi tizimga kiradi: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sahifa mazmuni bo‘yicha majburiyat',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 qarori',
    'footer_chip3' => 'Tarixiy dalillar',
    'footer_chip4' => 'Qadimiy xaritalar',
    'footer_chip5' => 'Obyektiv haqiqat',
    'footer_chip6' => 'Janubiy Xitoy dengizida tinchlik',
];
