<?php

return [
    'footer_index' => 'Kutubxona',
    'footer_crest_eyebrow' => 'Haqiqat kutubxonasining yakuni',
    'footer_crest_quote' => '“Janubiy Xitoy dengizida tinchlik <b>Xalqaro huquq</b> poydevori ustiga quriladi.”',
    'footer_crest_sub' => 'Nafrat yo\'q · Faqat haqiqat',
    'footer_nav_aria' => 'Pastki qismdagi harakatlar',
    'footer_btn_top' => 'Boshiga qaytish',
    'footer_btn_verdict' => 'PCA 2016 qarori',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'To\'qqiz chiziqli chegara',
    'footer_brand_body' => 'Bu sahifa obyektiv faktlar, xalqaro huquq va tarixiy hujjatlarga asoslangan tushuntirishdir — To\'qqiz chiziqli chegara da\'vosini shiorlar bilan emas, dalillar bilan rad etadi.',
    'footer_refs_title' => 'Manbalar',
    'footer_ref1' => 'PCA qarori, 2016-yil 12-iyul',
    'footer_ref2' => '1982-yil UNCLOS — to\'liq matn',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tarixiy materiallar va qadimiy xaritalar',
    'footer_toc_title' => 'Sahifa mundarijasi',
    'footer_toc1' => 'To\'qqiz chiziqli chegara nima',
    'footer_toc2' => 'Kelib chiqishi',
    'footer_toc3' => 'Nega bahsli',
    'footer_toc4' => 'Nega xalqaro hamjamiyat qarshi',
    'footer_toc5' => 'Jim guvohlar',
    'footer_toc6' => 'PCA 2016 qarori',
    'footer_toc7' => 'Parasel orollari - Spratli orollari',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Janubiy Xitoy dengizi haqidagi obyektiv haqiqat.<br>Ekotizim: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Koordinatasiz',
];
