<?php

return [
    'footer_index' => 'Kutubxona',
    'footer_crest_eyebrow' => 'Haqiqat kutubxonasining yakuni',
    'footer_crest_quote' => '“Janubiy Xitoy dengizida tinchlik <b>Xalqaro huquq</b> asosida quriladi.”',
    'footer_crest_sub' => 'Nafrat yo‘q · Faqat haqiqat',
    'footer_nav_aria' => 'Sahifa oxiri harakatlari',
    'footer_btn_top' => 'Boshiga qaytish',
    'footer_btn_verdict' => '2016 yilgi PCA qarori',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'To\'qqiz chiziqli chegara da\'vosi',
    'footer_brand_eyebrow' => 'Maxsus sahifa · Vyetnam suvereniteti',
    'footer_brand_body' => 'To\'qqiz chiziqli chegarani xolis haqiqat, xalqaro huquq, 2016 yilgi PCA qarori va tarixiy manbalar orqali tushuntiradi — ikki arxipelag <strong>"Parasel orollari va Spratli orollari"</strong> suverenitetiga bag‘ishlangan batafsil sahifalarni to‘ldiradi. Xitoyning asossiz da’volarini tarix va dalillar bilan rad etadi.',
    'footer_refs_title' => 'Manbalar',
    'footer_ref1' => 'PCA qarori, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — to‘liq matn',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tarixiy materiallar va qadimiy xaritalar',
    'footer_toc_title' => 'Sahifa mundarijasi',
    'footer_toc1' => 'To\'qqiz chiziqli chegara nima',
    'footer_toc2' => 'Kelib chiqishi',
    'footer_toc3' => 'Nega bahsli',
    'footer_toc4' => 'Nega xalqaro hamjamiyat qarshi',
    'footer_toc5' => 'Jim guvohlar',
    'footer_toc6' => '2016 yilgi PCA qarori',
    'footer_toc7' => 'Parasel orollari – Spratli orollari',
    'footer_copy_eyebrow' => 'Notijorat loyiha',
    'footer_copy_title' => 'Parasel orollari – Spratli orollari Vyetnamga tegishli',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Vyetnam suvereniteti ekotizimidagi To\'qqiz chiziqli chegara haqidagi maxsus sahifa.',
    'footer_copy_body' => 'To\'qqiz chiziqli chegara da’vosini <strong>xolis haqiqat</strong>, <strong>xalqaro huquq</strong>, 2016 yilgi PCA qarori va tarixiy manbalar orqali tushuntiradi — Parasel orollari va Spratli orollari suverenitetiga bag‘ishlangan batafsil sahifalarni to‘ldiradi.',
    'footer_copy_ecosystem_aria' => 'Bir loyiha sahifalari',
    'footer_copy_ecosystem_label' => 'Bir ekotizim',
    'footer_copy_disclaimer' => 'Mazmun ta’lim va xabardorlikni oshirish uchun mo‘ljallangan; Vyetnam Davlatining rasmiy pozitsiyasini almashtirmaydi.',
    'footer_copy' => '<strong>© :year To\'qqiz chiziqli chegara</strong> — <strong>Parasel orollari – Spratli orollari Vyetnamga tegishli</strong> nomli notijorat loyihaning bir qismi, quyidagi tizimga kiradi: <a href="https://paracelislands.net/uz" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/uz" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/uz" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/uz" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/uz" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sahifa mazmuni kafolatlari',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 yilgi PCA qarori',
    'footer_chip3' => 'Tarixiy dalillar',
    'footer_chip4' => 'Qadimiy xaritalar',
    'footer_chip5' => 'Xolis haqiqat',
    'footer_chip6' => 'Janubiy Xitoy dengizida tinchlik',
];
