<?php

return [
    'nav_logo_name' => 'To\'qqiz chiziqli chegara',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'To\'qqiz chiziqli chegara',
    'nav_rail_aria' => 'Bo\'limlar bo\'yicha navigatsiya',
    'nav_rail_what' => 'Ta\'rif',
    'nav_rail_origin' => 'Kelib chiqishi',
    'nav_rail_dispute' => 'Bahs',
    'nav_rail_opposition' => 'E\'tirozlar',
    'nav_rail_witnesses' => 'Qadimiy xaritalar',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Parasel orollari - Spratli orollari',
    'nav_sound_off' => 'Fon musiqasini yoqish',
    'nav_sound_on' => 'Fon musiqasini o\'chirish',
    'nav_share' => 'Ulashish',
    'dialog_title' => 'Ko\'rsatiladigan til',
    'language' => 'Til',
    'display_hint' => ':count ta til',
    'search_placeholder' => 'Tilni qidirish…',
    'cancel' => 'Bekor qilish',
    'apply' => 'Qo\'llash',
    'sound_off' => 'Fon ovozini yoqish',
    'sound_on' => 'Fon ovozini o\'chirish',
    'lang_trigger' => 'Tilni tanlash',
    'close' => 'Yopish',
    'no_results' => 'Til topilmadi',
    'contribute' => 'Ulashish',
];
