<?php

return [
    'opposition_index' => 'Qarshilik',
    'opposition_label' => 'Nega xalqaro hamjamiyat qarshi chiqadi',
    'opposition_title' => 'Qarshilik asoslanadi',
    'opposition_title_accent' => 'qonunga, his-tuyg‘uga emas',
    'opposition_lead' => '2009 yilda To\'qqiz chiziqli chegara BMTga taqdim etilganidan so‘ng, ko‘plab davlatlar va olimlar aniq huquqiy dalillar bilan qarshi chiqishdi.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'May',
    'opposition_voice1_title' => 'Vyetnam · Malayziya · Indoneziya',
    'opposition_voice1_body' => 'Xitoy To\'qqiz chiziqli chegara xaritasini BMT Bosh kotibiga taqdim etganidan atigi bir kun o‘tib (7/5/2009), bu davlatlar ketma-ket norozilik notalarini yuborib, da’voni rad etdilar.',
    'opposition_voice1_chip1' => 'Norozilik notasi',
    'opposition_voice1_chip2' => '1982-yilgi UNCLOSga mos emas',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippinlar',
    'opposition_voice2_body' => 'BMTga diplomatik xat yuborib, Xitoyning Janubiy Xitoy dengizidagi da’volari xalqaro huquq bo‘yicha "asosga ega emas" ekanini bildirdi — bu keyinchalik Arbitraj sudiga berilgan ish uchun zamin yaratdi.',
    'opposition_voice2_chip1' => 'PCA ishining asoslari',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'AQSh Davlat departamenti — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Tahlil shuni ko‘rsatdi: xaritalarning yillari chiziqning joylashuvi bo‘yicha bir-biriga mos kelmaydi; chiziq o‘rta chiziq emas, balki materik hududiga kirib boradi; ko‘plab obyektlar EEZga ega bo‘lish uchun "orol" maqomiga yetarli emas.',
    'opposition_voice3_chip1' => 'Huquqiy mezonlarga javob bermaydi',
    'opposition_voice3_chip2' => 'Rasmiy tahlil',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '"Tarixiy suvlar" tushunchasi eskirgan',
    'opposition_voice4_body' => 'Bu tushuncha faqat qo‘ltiqlar va qirg‘oqqa yaqin suv hududlariga tatbiq etiladi — keng ochiq dengizning katta qismini qamrab ola olmaydi. 2003 yilda Tayvan ham 1993 yilda ilgari surilgan "tarixiy suvlar" siyosatini rad etgan edi.',
    'opposition_voice4_chip1' => 'Hatto XXR olimlari ham bir fikrda emas',
];
