<?php

return [
    'opposition_index' => 'Qarshilik',
    'opposition_label' => 'Nega xalqaro hamjamiyat qarshi chiqdi',
    'opposition_title' => 'Qarshilik asoslanadi',
    'opposition_title_accent' => 'qonunga, hissiyotga emas',
    'opposition_lead' => 'To\'qqiz chiziqli chegara 2009 yilda BMTga taqdim etilgach, ko\'plab davlatlar va olimlar unga qarshi chiqdi — aniq huquqiy dalillar bilan.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'May',
    'opposition_voice1_title' => 'Vyetnam · Malayziya · Indoneziya',
    'opposition_voice1_body' => 'Xitoy To\'qqiz chiziqli chegara xaritasini BMT Bosh kotibiga taqdim etganidan bor-yo\'g\'i bir kun o\'tib (7/5/2009), bu davlatlar ketma-ket qarshi notalar yuborib, da\'voni rad etdi.',
    'opposition_voice1_chip1' => 'Qarshi nota',
    'opposition_voice1_chip2' => '1982 yilgi UNCLOSga mos emas',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippin',
    'opposition_voice2_body' => 'BMTga diplomatik maktub yuborib, Xitoyning Janubiy Xitoy dengizidagi da\'volari "xalqaro huquqqa ko\'ra asossiz" ekanini bildirdi — bu keyinchalik Arbitraj sudiga murojaat qilish uchun zamin bo\'ldi.',
    'opposition_voice2_chip1' => 'PCA da\'vosi uchun zamin',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'AQSh Davlat departamenti — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Tahlil shuni ko\'rsatadi: yillarga oid xaritalarda chegara chizig\'ining joylashuvi bir-biriga mos emas; chegara chizig\'i o\'rta chiziqni emas, balki materik hududini kesib o\'tadi; ko\'plab obyektlar EEZga ega bo\'lish uchun "orol" maqomiga yetarli emas.',
    'opposition_voice3_chip1' => 'Huquqiy talablarga javob bermaydi',
    'opposition_voice3_chip2' => 'Rasmiy tahlil',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '"Tarixiy suvlar" tushunchasi eskirgan',
    'opposition_voice4_body' => 'Bu tushuncha faqat qo\'ltiqlar, qirg\'oqqa yaqin ko\'rfazlarga tatbiq etiladi — keng ochiq dengiz hududini qamrab ololmaydi. 2003 yilda hatto Tayvan ham 1993 yilda ilgari surilgan "tarixiy suvlar" siyosatini rad etgan.',
    'opposition_voice4_chip1' => 'Hatto Xitoy olimlari ham yakdil emas',
];
