<?php

return [
    'sovereignty_index' => 'Parasel orollari – Spratli orollari',
    'sovereignty_label' => 'Muqarrar xulosa',
    'sovereignty_title' => 'Parasel orollari – Spratli orollari',
    'sovereignty_title_accent' => 'Vyetnamga tegishli',
    'sovereignty_lead' => 'Bu sahifa To\'qqiz chiziqli chegarani tushuntiradi. Xulosa esa keyingi savolga javob beradi: Parasel orollari va Spratli orollari ustidan suverenitet kimga tegishli? Tarixiy boshqaruv va xalqaro huquqga ko‘ra, javob izchil ravishda Vyetnamdir.',
    'sovereignty_thesis_label' => 'Yig‘ma dalil',
    'sovereignty_thesis_lock1' => 'Huquqiy koordinatalar yo‘q',
    'sovereignty_thesis_lock2' => 'PCA 2016 rad etdi',
    'sovereignty_thesis_lock3' => 'Qadimiy xaritalar qamrab olmaydi',
    'sovereignty_thesis_body' => 'Yuqoridagi olti bo‘limdan so‘ng uch narsa ravshan bo‘ldi: To\'qqiz chiziqli chegara qo‘lda chizilgan, huquqiy koordinatalarga ega emas; 2016-yildagi Arbitraj sudi da’voni rad etdi; Xitoyning o‘z qadimiy xaritalari Janubiy Xitoy dengizini qamrab olmaydi. Vyetnam suvereniteti shiorlarga emas, balki — Nguyen hukmdorlari davridan boshlab — ikki orol guruhi hech kimniki bo‘lmagan yer bo‘lib turgan paytda Vyetnam davlati ularni tinch va uzluksiz boshqarganiga tayanadi.',
    'sovereignty_spine_caption' => 'Uzluksiz boshqaruv bosqichlari',
    'sovereignty_spine_title' => 'Uzilmagan yagona vaqt jadvali',
    'sovereignty_spine_range' => 'XVII asr → hozir',
    'sovereignty_chron1_year' => 'XVII asr',
    'sovereignty_chron1_title' => 'Hoàng Sa jamoasi',
    'sovereignty_chron1_body' => 'Nguyen hukmdorlari Hoàng Sa jamoasini dengiz yo‘llarini tekshirish, o‘lchash va dengizda faoliyat yuritish uchun yuborgan — bu amaldagi boshqaruvni ifodalagan.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Gia Long imperatori',
    'sovereignty_chron2_body' => 'Parasel orollarida bayroq o‘rnatib, o‘sha davr dunyosi oldida Vyetnam suverenitetini tasdiqlagan.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Minh Mạng imperatori',
    'sovereignty_chron3_body' => 'O‘lchov ishlari olib borilgan, tosh lavhalar qo‘yilgan va orollar saroyning rasmiy xaritalarida qayd etilgan.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Uzluksiz vorislik',
    'sovereignty_chron4_body' => 'Fransiya buni tan olib, boshqaruvni davom ettirdi; Parasel orollari Thừa Thiên provinsiyasiga qo‘shildi — bu bugungi Vyetnam davlati uchun poydevor bo‘ldi.',
    'sovereignty_chron5_year' => 'Hozir',
    'sovereignty_chron5_title' => 'Qonun va amaliyot',
    'sovereignty_chron5_body' => 'Vyetnam UNCLOS, diplomatiya va arxiv hujjatlari asosida boshqaradi; To\'qqiz chiziqli chegara da’vosi bu dalillarni almashtira olmaydi.',
    'sovereignty_balance_label' => 'Dalillar muvozanati',
    'sovereignty_balance_medallion_title' => 'Ikki tomonning taqqoslanishi',
    'sovereignty_vn_tag' => 'Vyetnam tomoni',
    'sovereignty_vn_title' => 'Suverenitet amallar orqali o‘rnatiladi',
    'sovereignty_vn_body' => 'Yer hech kimniki bo‘lmagan paytda haqiqiy egalik, so‘ngra asrlar davomida ochiq boshqaruv — châu bảnlar, tosh lavhalar, xaritalar va ma’muriy hujjatlar bilan tasdiqlangan. Bu usul UNCLOS va xalqaro amaliyotga mos keladi.',
    'sovereignty_dash_tag' => 'To\'qqiz chiziqli chegara tomoni',
    'sovereignty_dash_title' => 'Da’vo dalillarni qoplay olmaydi',
    'sovereignty_dash_body' => '1948-yilda chizilgan, koordinatasiz chiziq 2016-yilda PCA tomonidan rad etilgan va UNCLOSga zid — buni 03 dan 06 gacha bo‘lgan bo‘limlar allaqachon ko‘rsatib bergan. Shu sababli ikki orol guruhi ustidan suverenitet haqidagi xulosa To\'qqiz chiziqli chegaraga tayanolmaydi.',
    'sovereignty_seal_quote' => 'Vyetnam nizolarni <strong>tinch vositalar</strong> bilan, xalqaro huquq asosida — ayniqsa 1982-yilgi UNCLOSga tayangan holda — Janubiy Xitoy dengizida tinchlik, hamkorlik va taraqqiyot sari hal qiladi.',
    'sovereignty_seal_cite' => 'Vyetnamning pozitsiyasi · 1982-yilgi UNCLOS',
    'sovereignty_next_eyebrow' => 'Xuddi shu ekotizimdagi asosiy loyiha',
    'sovereignty_next_title' => 'Parasel orollari – Spratli orollari haqidagi dalillarni to‘liq o‘qing',
    'sovereignty_next_body' => 'Batafsil materiallar — hujjatlar, xaritalar, vaqt jadvali va huquqiy asoslar — <strong>paracelislands.net</strong> sahifasida jamlangan bo‘lib, u ikki orol guruhi suvereniteti mavzusini to‘liq yoritadi. Siz o‘qiyotgan sahifa esa To\'qqiz chiziqli chegaradan shu xulosaga mantiqiy bog‘lanishni ta’minlaydi.',
    'sovereignty_next_cta' => 'paracelislands.net ni ochish',
];
