<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Xalqaro qaror',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'uchta “Yo‘q”',
    'verdict_lead' => '2016-yil 12-iyulda, Gagada joylashgan Doimiy Arbitraj sudi (PCA) — UNCLOSning VII ilovasi asosida tuzilgan, Filippinlarning Xitoyga qarshi ishida — To\'qqiz chiziqli chegara da’vosini rad etuvchi qaror chiqardi. <em>To‘liq matnni o‘qish uchun har bir kartani bosing.</em>',
    'verdict_card1_khong' => 'YO‘Q',
    'verdict_card1_title' => 'tarixiy huquq',
    'verdict_card1_short' => 'Xitoyning To\'qqiz chiziqli chegara ichida joylashgan dengiz hududidagi resurslarga nisbatan tarixiy huquq da’vo qilishiga huquqiy asos yo‘q.',
    'verdict_card1_quote' => '“Xitoyning To\'qqiz chiziqli chegara ichidagi dengiz hududida joylashgan resurslarga nisbatan tarixiy huquq da’vo qilishiga huquqiy asos yo‘q.”',
    'verdict_card1_more' => '+ Qarorni o‘qish',
    'verdict_card2_khong' => 'YO‘Q',
    'verdict_card2_title' => 'EEZni hosil qiluvchi ob’ekt',
    'verdict_card2_short' => 'Spratli orollari tarkibidagi hech bir ob’ekt Xitoy uchun alohida iqtisodiy zona yaratish huquqiga ega emas — jumladan Ba Binh oroli ham.',
    'verdict_card2_quote' => '“Spratli orollari tarkibidagi hech bir ob’ekt alohida iqtisodiy zona yaratishga qodir emas.”',
    'verdict_card2_more' => '+ Qarorni o‘qish',
    'verdict_card3_khong' => 'YO‘Q',
    'verdict_card3_title' => 'qonuniy harakat',
    'verdict_card3_short' => 'Xitoy Filipinning suveren huquqlarini buzdi, baliq ovlashga to‘sqinlik qildi va dengiz muhitiga zarar yetkazdi.',
    'verdict_card3_quote' => '“Xitoy Filipinning suveren huquqlarini buzdi, Scarborough sayozligida baliq ovlash faoliyatiga aralashdi va marjon riflari muhitiga jiddiy zarar yetkazdi.”',
    'verdict_card3_more' => '+ Qarorni o‘qish',
    'verdict_extra1' => 'Xitoy tomonidan chizilgan To\'qqiz chiziqli chegara <strong>UNCLOS 1982 ga mos emas</strong>.',
    'verdict_extra2' => 'Xitoy haddan tashqari ekspluatatsiya va sun’iy orollar qurish orqali Spratli orollari ekotizimiga zarar yetkazdi.',
    'verdict_extra3' => 'Xitoyning harakatlari Filippin bilan mojaro xavfini kuchaytirdi.',
    'verdict_extra4' => 'Ba Binh oroli (Tayvan nazoratida) ham EEZ hosil qila olmaydi.',
    'verdict_subtitle' => 'Nega u UNCLOS bilan zid?',
    'verdict_subtitle_body' => 'UNCLOS 1982 qirg‘oqbo‘yi davlatning tayanch chizig‘iga asoslanib dengiz zonalarini aniq belgilaydi. To\'qqiz chiziqli chegara da’vosi bu doiradan tashqariga chiqadi, shuning uchun uni moslashtirib bo‘lmaydi.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Hududiy dengiz (dengiz mili)',
    'verdict_zone1_body' => 'Tayanch chizig‘idan boshlab hisoblanadigan, davlat suverenitetidagi dengiz hududi.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Alohida iqtisodiy zona',
    'verdict_zone2_body' => 'EEZ — qirg‘oqbo‘yi davlat ushbu hudud ichida resurslarga nisbatan suveren huquqlarga ega.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinental shelf (maksimal, dengiz mili)',
    'verdict_zone3_body' => 'Dengiz tubi resurslariga bo‘lgan huquq, geologik shartlarga ko‘ra belgilanadi.',
    'verdict_foot' => 'Ushbu doirada, “tarixiy huquq” ochiq dengizning butun bir hududini — To\'qqiz chiziqli chegara nazarda tutganidek — qamrab olishi <em>UNCLOSning huquqiy rejimi bilan almashtirilgan</em>, va Xitoy ham uning a’zosidir.',
];
