<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Xalqaro hukm',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'uchta “Yo‘q”',
    'verdict_lead' => '2016-yil 12-iyul kuni The Hague shahridagi Doimiy Arbitraj Sudi (PCA) — UNCLOSning VII-ilovasi asosida, Filippin Xitoyga qarshi qo‘zg‘atgan ishda — To\'qqiz chiziqli chegara da’vosini rad etuvchi hukm chiqardi. <em>To‘liq matnni o‘qish uchun har bir kartaga bosing.</em>',
    'verdict_card1_khong' => 'YO‘Q',
    'verdict_card1_title' => 'tarixiy huquq',
    'verdict_card1_short' => 'To\'qqiz chiziqli chegara ichidagi dengiz hududidagi resurslarga nisbatan Xitoy tarixiy huquqni da’vo qilish uchun huquqiy asosga ega emas.',
    'verdict_card1_quote' => '“To\'qqiz chiziqli chegara ichidagi dengiz hududidagi resurslarga nisbatan Xitoyning tarixiy huquq da’vo qilishiga huquqiy asos yo‘q.”',
    'verdict_card1_more' => '+ Hukmni o‘qish',
    'verdict_card2_khong' => 'YO‘Q',
    'verdict_card2_title' => 'EEZ yaratadigan obyekt',
    'verdict_card2_short' => 'Spratli orollari tarkibidagi hech bir obyekt Xitoy uchun eksklyuziv iqtisodiy zonani yaratish mezonlariga javob bermaydi — Babi oroli ham shu jumladan.',
    'verdict_card2_quote' => '“Spratli orollari tarkibidagi biror-bir obyekt eksklyuziv iqtisodiy zonani yaratish qobiliyatiga ega emas.”',
    'verdict_card2_more' => '+ Hukmni o‘qish',
    'verdict_card3_khong' => 'YO‘Q',
    'verdict_card3_title' => 'qonuniy harakat',
    'verdict_card3_short' => 'Xitoy Filippinning suveren huquqlarini buzdi, baliq ovlashga to‘sqinlik qildi va dengiz muhitiga zarar yetkazdi.',
    'verdict_card3_quote' => '“Xitoy Filippinning suveren huquqlarini buzdi, Scarborough qirg‘oqlarida baliq ovlash faoliyatiga aralashdi va marjon riflari muhitiga jiddiy zarar yetkazdi.”',
    'verdict_card3_more' => '+ Hukmni o‘qish',
    'verdict_extra1' => 'Xitoy tomonidan chizilgan To\'qqiz chiziqli chegara <strong>UNCLOS 1982ga mos kelmaydi</strong>.',
    'verdict_extra2' => 'Xitoy haddan tashqari ekspluatatsiya va sun’iy orollar qurish orqali Spratli orollari ekotizimiga zarar yetkazdi.',
    'verdict_extra3' => 'Xitoyning harakatlari Filippin bilan mojaro xavfini oshirdi.',
    'verdict_extra4' => 'Babi oroli (Tayvan nazoratida) ham EEZ yaratolmaydi.',
    'verdict_subtitle' => 'Nega u UNCLOS bilan ziddiyatda?',
    'verdict_subtitle_body' => 'UNCLOS 1982 qirg‘oqbo‘yi davlatlarning boshlang‘ich chizig‘iga asoslanib dengiz hududlarini aniq belgilaydi. To\'qqiz chiziqli chegara da’vosi bu doiradan tashqariga chiqadi, shuning uchun u bilan yonma-yon qo‘yib bo‘lmaydi.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Hududiy dengiz (dengiz mili)',
    'verdict_zone1_body' => 'Boshlang‘ich chiziqdan boshlab hisoblanadigan, davlat suverenitetiga ega dengiz hududi.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklyuziv iqtisodiy zona',
    'verdict_zone2_body' => 'EEZ — qirg‘oqbo‘yi davlat ushbu hududdagi resurslarga nisbatan suveren huquqlarga ega bo‘ladi.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinental shelf (maksimal, dengiz mili)',
    'verdict_zone3_body' => 'Geologik shartlarga ko‘ra belgilangan dengiz tubi resurslariga bo‘lgan huquqlar.',
    'verdict_foot' => 'Ushbu doirada, “tarixiy huquq” butun bir ochiq dengiz hududini qamrab olishi — To\'qqiz chiziqli chegara nazarda tutganidek — <em>UNSLOSning huquqiy rejimi bilan almashtirilgan</em>, va Xitoyning o‘zi ham uning a’zosidir.',
];
