<?php

return [
    'witnesses_index' => 'Qadimiy xaritalar',
    'witnesses_label' => 'Xitoyning qadimiy xaritalari',
    'witnesses_title' => 'Eng janubiy chegara faqat',
    'witnesses_title_accent' => 'Xaynan oroligacha',
    'witnesses_lead' => 'Xitoy mualliflari chizgan qadimiy xaritalar — xronologik tartibda joylashtirilgan — barchasi <em>Xaynan oroli Xitoyning eng janubiy nuqtasi</em> ekanini ko‘rsatadi, Parasel orollari yoki Spratli orollari yo‘q. Materiallar <em>Vyetnamning Parasel orollari va Spratli orollaridagi milliy suvereniteti</em> (Truong Minh Duk, 2015) asariga tayangan holda jamlangan.',
    'witnesses_hint' => '⌖ Lupani tekshiring',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— hududning eng janubiy nuqtasi —',
    'witnesses_map1_svg_era' => 'Sung sulolasi · 1136',
    'witnesses_map1_title' => 'Sung sulolasi xaritasi, 1136',
    'witnesses_map1_body' => 'Xitoy hududi Hainan orolida tugaydi — Parasel orollari va Spratli orollari uning hududidan tashqarida.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anville chegarasi',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville xaritasi, 1735',
    'witnesses_map2_body' => 'J.-B. B. d\'Anville tomonidan chizilgan; 1740 yilgi nusxasi bir vaqtlar Germaniya bosh vaziri tomonidan Xitoy rahbariga sovg‘a qilingan. Sin sulolasi hududi Hainan bilan yakunlanadi.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"Xitoyning eng janubiy nuqtasi"',
    'witnesses_map3_svg_era' => 'Imperatorlik saroyi provinsiyalari geodezik to‘liq xaritasi · 1904',
    'witnesses_map3_title' => 'Imperatorlik saroyi provinsiyalari geodezik to‘liq xaritasi',
    'witnesses_map3_body' => 'Sin sulolasi tomonidan chop etilgan — Xitoy hududining eng janubiy nuqtasi aniq Hainan oroli ekani ko‘rsatilgan.',
    'witnesses_quote' => 'Xitoy tomonidan e’lon qilingan xaritalarning o‘zida ham Parasel orollari - Spratli orollari ularning hududi sifatida chizilmagan.',
    'witnesses_timeline_aria' => 'Xitoyning qadimiy xaritalari vaqt jadvali',
    'witnesses_year_aria' => 'Sana',
    'lightbox_aria' => 'Kattalashtirilgan rasmni ko‘rish',
    'lightbox_close' => 'Yopish',
    'lightbox_prev' => 'Oldingi rasm',
    'lightbox_next' => 'Keyingi rasm',
];
