<?php

return [
    'footer_index' => 'Kirjasto',
    'footer_crest_eyebrow' => 'Tosiasioiden kirjasto päätökseen',
    'footer_crest_quote' => '“Rauha Etelä-Kiinan merellä rakentuu <b>kansainvälisen oikeuden</b> varaan.”',
    'footer_crest_sub' => 'Ei vihaa · Vain totuus',
    'footer_nav_aria' => 'Toiminnot alatunnisteessa',
    'footer_btn_top' => 'Takaisin ylös',
    'footer_btn_verdict' => 'PCA:n ratkaisu 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Yhdeksän viivan linjan vaateet',
    'footer_brand_eyebrow' => 'Teemasivu · Vietnamin suvereniteetti',
    'footer_brand_body' => 'Selittää Yhdeksän viivan linjaa objektiivisten tosiasioiden, kansainvälisen oikeuden, PCA:n vuoden 2016 ratkaisun ja historiallisten lähteiden avulla — täydentäen syventäviä sivuja kahden saariston <strong>"Paracelsaaret ja Spratlysaaret"</strong> suvereniteetista. Kiinan perusteettomien vaatimusten kumoaminen historian ja todisteiden avulla.',
    'footer_refs_title' => 'Lähteet',
    'footer_ref1' => 'PCA:n ratkaisu, 12.7.2016',
    'footer_ref2' => 'UNCLOS 1982 — koko teksti',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historialliset lähteet ja vanhat kartat',
    'footer_toc_title' => 'Sivun sisällysluettelo',
    'footer_toc1' => 'Mikä on Yhdeksän viivan linja',
    'footer_toc2' => 'Alkuperä',
    'footer_toc3' => 'Miksi se on kiistanalainen',
    'footer_toc4' => 'Miksi kansainvälinen yhteisö vastustaa',
    'footer_toc5' => 'Hiljaiset todistajat',
    'footer_toc6' => 'PCA:n ratkaisu 2016',
    'footer_toc7' => 'Paracelsaaret – Spratlysaaret',
    'footer_copy_eyebrow' => 'Voittoa tavoittelematon hanke',
    'footer_copy_title' => 'Paracelsaaret – Spratlysaaret kuuluvat Vietnamille',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Teemasivu Yhdeksän viivan linjasta osana Vietnamin suvereniteettiekosysteemiä.',
    'footer_copy_body' => 'Yhdeksän viivan linjan vaateen selittäminen <strong>objektiivisten tosiasioiden</strong>, <strong>kansainvälisen oikeuden</strong>, PCA:n vuoden 2016 ratkaisun ja historiallisten lähteiden avulla — täydentäen syventäviä sivuja Paracelsaarten ja Spratlysaarten suvereniteetista.',
    'footer_copy_ecosystem_aria' => 'Saman projektin sivut',
    'footer_copy_ecosystem_label' => 'Sama ekosysteemi',
    'footer_copy_disclaimer' => 'Sisältö on tarkoitettu koulutukseen ja tietoisuuden lisäämiseen; se ei korvaa Vietnamin valtion virallista kantaa.',
    'footer_copy' => '<strong>© :year Yhdeksän viivan linja</strong> — Osa voittoa tavoittelematonta hanketta <strong>Paracelsaaret – Spratlysaaret kuuluvat Vietnamille</strong>, joka kuuluu järjestelmään: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sivun sisältösitoumukset',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA:n ratkaisu 2016',
    'footer_chip3' => 'Historialliset todisteet',
    'footer_chip4' => 'Vanhat kartat',
    'footer_chip5' => 'Objektiiviset tosiasiat',
    'footer_chip6' => 'Etelä-Kiinan meren rauha',
];
