<?php

return [
    'footer_index' => 'Kirjasto',
    'footer_crest_eyebrow' => 'Faktojen kirjaston loppu',
    'footer_crest_quote' => '“Rauha Etelä-Kiinan merellä rakentuu <b>kansainvälisen oikeuden</b> perustalle.”',
    'footer_crest_sub' => 'Ei vihaa · Vain totuus',
    'footer_nav_aria' => 'Alatunnisteen toiminnot',
    'footer_btn_top' => 'Takaisin ylös',
    'footer_btn_verdict' => 'PCA:n vuoden 2016 ratkaisu',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Yhdeksän viivan linja',
    'footer_brand_body' => 'Totuuteen, kansainväliseen oikeuteen ja historiallisten lähteiden objektiiviseen tarkasteluun perustuva selittävä sivusto — kumoaa Yhdeksän viivan linjan vaatimukset todisteilla, ei iskulauseilla.',
    'footer_refs_title' => 'Lähteet',
    'footer_ref1' => 'PCA:n ratkaisu, 12.7.2016',
    'footer_ref2' => 'UNCLOS 1982 — koko teksti',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historialliset aineistot ja vanhat kartat',
    'footer_toc_title' => 'Sivun sisällysluettelo',
    'footer_toc1' => 'Mikä on Yhdeksän viivan linja',
    'footer_toc2' => 'Alkuperä',
    'footer_toc3' => 'Miksi se on kiistanalainen',
    'footer_toc4' => 'Miksi kansainvälinen yhteisö vastustaa sitä',
    'footer_toc5' => 'Hiljaiset todistajat',
    'footer_toc6' => 'PCA:n vuoden 2016 ratkaisu',
    'footer_toc7' => 'Paracelsaaret – Spratlysaaret',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektiivista totuutta Etelä-Kiinan merestä.<br>Ekosysteemi: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Ei koordinaatteja',
];
