<?php

return [
    'nav_logo_name' => 'Yhdeksän viivan linja',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Yhdeksän viivan linja',
    'nav_rail_aria' => 'Navigointi osioittain',
    'nav_rail_what' => 'Määritelmä',
    'nav_rail_origin' => 'Alkuperä',
    'nav_rail_dispute' => 'Kiista',
    'nav_rail_opposition' => 'Vastustus',
    'nav_rail_witnesses' => 'Vanhat kartat',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelsaaret – Spratlysaaret',
    'nav_sound_off' => 'Kytke taustamusiikki päälle',
    'nav_sound_on' => 'Kytke taustamusiikki pois päältä',
    'nav_share' => 'Jaa',
    'dialog_title' => 'Näyttökieli',
    'language' => 'Kieli',
    'display_hint' => ':count kieltä',
    'search_placeholder' => 'Etsi kieltä…',
    'cancel' => 'Peruuta',
    'apply' => 'Ota käyttöön',
    'sound_off' => 'Kytke taustaääni päälle',
    'sound_on' => 'Kytke taustaääni pois päältä',
    'lang_trigger' => 'Valitse kieli',
    'close' => 'Sulje',
    'no_results' => 'Kieliä ei löytynyt',
    'contribute' => 'Jaa',
];
