<?php

return [
    'opposition_index' => 'Vastustus',
    'opposition_label' => 'Miksi kansainvälinen yhteisö vastustaa',
    'opposition_title' => 'Vastustus perustuu',
    'opposition_title_accent' => 'lakiin, ei tunteisiin',
    'opposition_lead' => 'Heti sen jälkeen kun Yhdeksän viivan linja esitettiin Yhdistyneille kansakunnille vuonna 2009, monet valtiot ja tutkijat vastustivat sitä — täsmällisin oikeudellisin perustein.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Toukokuu',
    'opposition_voice1_title' => 'Vietnam · Malesia · Indonesia',
    'opposition_voice1_body' => 'Vain päivä sen jälkeen kun Kiina toimitti Yhdeksän viivan linjan kartan YK:n pääsihteerille (7.5.2009), nämä maat lähettivät vuorollaan vastalausekirjelmät ja torjuivat vaatimukset.',
    'opposition_voice1_chip1' => 'Vastalausekirjelmä',
    'opposition_voice1_chip2' => 'Ei vastaa UNCLOS 1982 -yleissopimusta',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippiinit',
    'opposition_voice2_body' => 'Lähetti diplomaattisen kirjeen Yhdistyneille kansakunnille ja ilmoitti, että Kiinan vaatimukset Etelä-Kiinan merellä olivat “vailla perustaa kansainvälisen oikeuden mukaan” — mikä loi pohjan myöhemmälle välimiesmenettelylle.',
    'opposition_voice2_chip1' => 'PCA-kanteen lähtökohta',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Yhdysvaltain ulkoministeriö — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analyysi osoitti: eri vuosien kartat olivat ristiriitaisia viivan sijainnin osalta; viiva tunkeutui mantereelle keskiviivan sijasta; monet muodostelmat eivät täytä “saaren” kriteerejä talousvyöhykkeen saamiseksi.',
    'opposition_voice3_chip1' => 'Ei täytä oikeudellisia edellytyksiä',
    'opposition_voice3_chip2' => 'Virallinen analyysi',
    'opposition_voice4_year' => 'Akateeminen',
    'opposition_voice4_title' => '“Historiallisten vesien” käsite on vanhentunut',
    'opposition_voice4_body' => 'Tämä käsite koskee vain lahtia ja rannikon läheisiä vesialueita — sitä ei voi ulottaa laajaan avomeren alueeseen. Vuonna 2003 myös Taiwan itse hylkäsi vuonna 1993 esitetyn “historiallisten vesien” politiikan.',
    'opposition_voice4_chip1' => 'Jopa kiinalaiset tutkijat eivät ole yksimielisiä',
];
