<?php

return [
    'sovereignty_index' => 'Paracelsaaret – Spratlysaaret',
    'sovereignty_label' => 'Välttämätön johtopäätös',
    'sovereignty_title' => 'Paracelsaaret – Spratlysaaret',
    'sovereignty_title_accent' => 'ovat Vietnamin',
    'sovereignty_lead' => 'Tämä sivu selittää Yhdeksän viivan linjan. Päätösluku vastaa seuraavaan kysymykseen: kenellä on suvereniteetti Paracelsaaret- ja Spratlysaaret-saaristoihin? Hallinnollisen historian ja kansainvälisen oikeuden perusteella johdonmukainen vastaus on Vietnam.',
    'sovereignty_thesis_label' => 'Kokonaisargumentti',
    'sovereignty_thesis_lock1' => 'Ei oikeudellisia koordinaatteja',
    'sovereignty_thesis_lock2' => 'PCA 2016 torjui',
    'sovereignty_thesis_lock3' => 'Vanhat kartat eivät kata aluetta',
    'sovereignty_thesis_body' => 'Edellisten kuuden osion jälkeen kolme asiaa on selvä: Yhdeksän viivan linja on käsin piirretty eikä sillä ole oikeudellisia koordinaatteja; vuoden 2016 välimiesoikeus torjui vaatimuksen; Kiinan omat vanhat kartat eivät kata Etelä-Kiinan merta. Vietnamin suvereniteetti ei perustu iskulauseisiin, vaan siihen, että Vietnamin valtio — Nguyễn-dynastian ajoista lähtien — on hallinnoinut aluetta rauhanomaisesti ja keskeytyksettä silloin, kun molemmat saaristot olivat vielä terra nullius.',
    'sovereignty_spine_caption' => 'Jatkuvan hallinnan merkkipaalut',
    'sovereignty_spine_title' => 'Yksi aikajana, ilman katkosta',
    'sovereignty_spine_range' => '17. vuosisata → nykypäivä',
    'sovereignty_chron1_year' => '17. vuosisata',
    'sovereignty_chron1_title' => 'Hoàng Sa -joukko',
    'sovereignty_chron1_body' => 'Nguyễn-hallitsijat lähettivät Hoàng Sa -joukon kartoittamaan, mittaamaan merireittejä ja hyödyntämään merta — tosiasiallisen hallinnan harjoittamista.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kuningas Gia Long',
    'sovereignty_chron2_body' => 'Liput nostettiin Paracelsaaret-saaristossa, mikä vahvisti Vietnamin suvereniteetin aikansa maailman silmien edessä.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kuningas Minh Mạng',
    'sovereignty_chron3_body' => 'Saaristo mitattiin, sinne pystytettiin muistomerkkejä, ja se kirjattiin hovin virallisiin karttoihin.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Jatkuvuuden perintö',
    'sovereignty_chron4_body' => 'Ranska tunnusti alueen ja jatkoi hallintoa; Paracelsaaret liitettiin Thừa Thiênin maakuntaan — tämä loi perustan nykyiselle Vietnamin valtiolle.',
    'sovereignty_chron5_year' => 'Nyt',
    'sovereignty_chron5_title' => 'Laki ja käytäntö',
    'sovereignty_chron5_body' => 'Vietnam hallinnoi aluetta UNCLOSin, diplomatian ja arkistojen perusteella; Yhdeksän viivan linjan vaatimus ei korvaa tätä näyttöä.',
    'sovereignty_balance_label' => 'Todisteiden tasapaino',
    'sovereignty_balance_medallion_title' => 'Kahden puolen vertailu',
    'sovereignty_vn_tag' => 'Vietnamin puoli',
    'sovereignty_vn_title' => 'Suvereniteetti vahvistettu teoilla',
    'sovereignty_vn_body' => 'Todellinen hallinta tapahtui, kun alue oli vielä terra nullius, minkä jälkeen sitä hallinnoitiin julkisesti vuosisatojen ajan — hallitsijoiden asiakirjojen, muistomerkkien, karttojen ja hallinnollisten aineistojen avulla. Tämä menettely on UNCLOSin ja kansainvälisen käytännön mukainen.',
    'sovereignty_dash_tag' => 'Yhdeksän viivan linjan puoli',
    'sovereignty_dash_title' => 'Vaatimus ei korvaa näyttöä',
    'sovereignty_dash_body' => 'Vuonna 1948 piirretty viiva ilman koordinaatteja on PCA:n vuonna 2016 torjuma ja UNCLOSin vastainen — kuten osioissa 03–06 on osoitettu. Siksi johtopäätös kahden saariston suvereniteetista ei voi perustua Yhdeksän viivan linjaan.',
    'sovereignty_seal_quote' => 'Vietnam ratkaisee kiistat <strong>rauhanomaisin keinoin</strong> kansainvälisen oikeuden — erityisesti vuoden 1982 UNCLOSin — pohjalta ja tavoittelee Etelä-Kiinan merestä rauhan, yhteistyön ja kehityksen merta.',
    'sovereignty_seal_cite' => 'Vietnamin kanta · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Saman ekosysteemin päätuote',
    'sovereignty_next_title' => 'Lue täydet todisteet Paracelsaaret- ja Spratlysaaret-saarista',
    'sovereignty_next_body' => 'Yksityiskohtainen aineisto — asiakirjat, kartat, aikajana ja oikeudelliset perustelut — löytyy sivustolta <strong>paracelislands.net</strong>, jossa kahden saariston suvereniteettikysymys esitetään kokonaisuutena. Tämä sivu yhdistää Yhdeksän viivan linjan loogisesti tähän johtopäätökseen.',
    'sovereignty_next_cta' => 'Avaa paracelislands.net',
];
