<?php

return [
    'sovereignty_index' => 'Paracelsaaret – Spratlysaaret',
    'sovereignty_label' => 'Välttämätön johtopäätös',
    'sovereignty_title' => 'Paracelsaaret – Spratlysaaret',
    'sovereignty_title_accent' => 'ovat Vietnamin alueita',
    'sovereignty_lead' => 'Tämä sivu selittää Yhdeksän viivan linjaa. Päätösosio vastaa seuraavaan kysymykseen: kenellä on suvereniteetti kahdesta saaristosta, Paracelsaarista ja Spratlysaarista? Hallinnon historian ja kansainvälisen oikeuden mukaan johdonmukainen vastaus on Vietnam.',
    'sovereignty_thesis_label' => 'Koottu väite',
    'sovereignty_thesis_lock1' => 'Ei oikeudellisia koordinaatteja',
    'sovereignty_thesis_lock2' => 'PCA 2016 hylkäsi väitteen',
    'sovereignty_thesis_lock3' => 'Muinaiset kartat eivät kata aluetta',
    'sovereignty_thesis_body' => 'Kuuden edellä olevan osion jälkeen kolme asiaa ovat selviä: Yhdeksän viivan linja on käsin piirretty eikä sillä ole oikeudellisia koordinaatteja; vuoden 2016 välimiesoikeus hylkäsi vaatimuksen; Kiinan omat vanhat kartat eivät kata Etelä-Kiinan merta. Vietnamin suvereniteetti ei perustu iskulauseisiin vaan siihen, että Vietnamin valtio — jo Nguyễn-hallitsijoiden ajasta lähtien — on hallinnoinut aluetta rauhanomaisesti ja jatkuvasti, kun nämä kaksi saaristoa olivat vielä omistajattomia.',
    'sovereignty_spine_caption' => 'Jatkuvan hallinnan virstanpylväät',
    'sovereignty_spine_title' => 'Yksi aikajana, ilman katkoa',
    'sovereignty_spine_range' => '17. vuosisata → nykypäivä',
    'sovereignty_chron1_year' => '17. vuosis.',
    'sovereignty_chron1_title' => 'Hoàng Sa -ryhmä',
    'sovereignty_chron1_body' => 'Nguyễn-hallitsijat lähettivät Hoàng Sa -ryhmän tutkimaan, mittaamaan merireittejä ja hyödyntämään merta — käytännössä valvomaan aluetta.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kuningas Gia Long',
    'sovereignty_chron2_body' => 'Lippu nostettiin Paracelsaarilla, mikä vahvisti Vietnamin suvereniteetin tuon ajan maailmalle.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kuningas Minh Mạng',
    'sovereignty_chron3_body' => 'Alue mitattiin, sinne pystytettiin stelaa ja saaristo merkittiin hovin virallisiin karttoihin.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Jatkuva perintö',
    'sovereignty_chron4_body' => 'Ranska tunnusti ja jatkoi hallintoa; Paracelsaaret liitettiin Thừa Thiênin maakuntaan — tämä loi perustan nykyiselle Vietnamin valtiolle.',
    'sovereignty_chron5_year' => 'Nyt',
    'sovereignty_chron5_title' => 'Laki ja käytäntö',
    'sovereignty_chron5_body' => 'Vietnam hallinnoi aluetta UNCLOSin, diplomatian ja arkistojen perusteella; Yhdeksän viivan linjan vaatimus ei voi syrjäyttää tätä näyttöä.',
    'sovereignty_balance_label' => 'Näytön tasapaino',
    'sovereignty_balance_medallion_title' => 'Kahden puolen vertailu',
    'sovereignty_vn_tag' => 'Vietnamin puoli',
    'sovereignty_vn_title' => 'Suvereniteetti vahvistettu teoilla',
    'sovereignty_vn_body' => 'Todellinen hallinta otettiin alueen ollessa vielä omistajaton, minkä jälkeen sitä hallinnoitiin avoimesti vuosisatojen ajan — keisarillisten asiakirjojen, steelojen, karttojen ja hallinnollisten tietojen avulla. Tämä menettely on sopusoinnussa UNCLOSin ja kansainvälisen käytännön kanssa.',
    'sovereignty_dash_tag' => 'Yhdeksän viivan linjan puoli',
    'sovereignty_dash_title' => 'Vaatimus ei korvaa näyttöä',
    'sovereignty_dash_body' => 'Vuonna 1948 piirretty viiva ilman koordinaatteja on PCA:n vuonna 2016 hylkäämä ja UNCLOSin vastainen — kuten osiot 03–06 osoittavat. Siksi johtopäätöstä kahden saariston suvereniteetista ei voida perustaa Yhdeksän viivan linjaan.',
    'sovereignty_seal_quote' => 'Vietnam ratkaisee kiistat <strong>rauhanomaisin keinoin</strong>, kansainvälisen oikeuden — erityisesti vuoden 1982 UNCLOSin — pohjalta, tavoitteena rauhallinen, yhteistyöhön perustuva ja kehittyvä Etelä-Kiinan meri.',
    'sovereignty_seal_cite' => 'Vietnamin kanta · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Saman ekosysteemin pääprojekti',
    'sovereignty_next_title' => 'Lue täydet todisteet Paracelsaarista – Spratlysaarista',
    'sovereignty_next_body' => 'Yksityiskohtainen aineisto — asiakirjat, kartat, aikajana ja oikeudelliset perustelut — löytyy sivustolta <strong>paracelislands.net</strong>, joka esittelee kahden saariston suvereniteettikysymyksen kokonaisuudessaan. Tämä sivu yhdistää loogisesti Yhdeksän viivan linjan siihen johtopäätökseen.',
    'sovereignty_next_cta' => 'Avaa paracelislands.net',
];
