<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Kansainvälinen tuomio',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'kolme "ei"-vastauksia',
    'verdict_lead' => '12.7.2016, Pysyvä välitystuomioistuin (PCA) Haagissa — UNCLOSin liitteen VII mukaisesti perustettu, Filippiinien Kiinaa vastaan nostamassa asiassa — antoi tuomion, joka hylkäsi Yhdeksän viivan linjan vaatimuksen. <em>Napsauta kutakin korttia lukeaksesi alkuperäisen tekstin.</em>',
    'verdict_card1_khong' => 'EI',
    'verdict_card1_title' => 'historiallista oikeutta',
    'verdict_card1_short' => 'Kiinalla ei ole oikeudellista perustaa vedota historiallisten oikeuksien vuoksi Yhdeksän viivan linjan sisällä olevien merialueiden luonnonvaroihin.',
    'verdict_card1_quote' => '“Kiinalla ei ole oikeudellista perustaa vedota historiallisten oikeuksien vuoksi Yhdeksän viivan linjan sisällä olevien merialueiden luonnonvaroihin.”',
    'verdict_card1_more' => '+ Lue tuomio',
    'verdict_card2_khong' => 'EI',
    'verdict_card2_title' => 'aluetta, joka muodostaa EEZ:n',
    'verdict_card2_short' => 'Mikään Spratlysaarten saari ei täytä edellytyksiä luoda Kiinalle yksinomaista talousvyöhykettä — ei edes Ba Binhin saari.',
    'verdict_card2_quote' => '“Mikään Spratlysaarten alueen muodostelma ei kykene luomaan yksinomaista talousvyöhykettä.”',
    'verdict_card2_more' => '+ Lue tuomio',
    'verdict_card3_khong' => 'EI',
    'verdict_card3_title' => 'laillista toimintaa',
    'verdict_card3_short' => 'Kiina loukkasi Filippiinien suvereeneja oikeuksia, esti kalastusta ja vahingoitti meriympäristöä.',
    'verdict_card3_quote' => '“Kiina loukkasi Filippiinien suvereeneja oikeuksia, puuttui kalastustoimintaan Scarboroughin matalikolla ja aiheutti vakavaa vahinkoa koralliriutta-ympäristölle.”',
    'verdict_card3_more' => '+ Lue tuomio',
    'verdict_extra1' => 'Kiinan itse piirtämä Yhdeksän viivan linja <strong>ei ole yhteensopiva</strong> vuoden 1982 UNCLOSin kanssa.',
    'verdict_extra2' => 'Kiina on aiheuttanut vahinkoa Spratlysaarten ekosysteemille liikakalastuksen ja keinosaarten rakentamisen kautta.',
    'verdict_extra3' => 'Kiinan toimet lisäävät konfliktin riskiä Filippiinien kanssa.',
    'verdict_extra4' => 'Myöskään Ba Binhin saari (Taiwanin hallinnassa) ei voi muodostaa EEZ:tä.',
    'verdict_subtitle' => 'Miksi se on ristiriidassa UNCLOSin kanssa?',
    'verdict_subtitle_body' => 'Vuoden 1982 UNCLOS määrittelee selkeästi merialueet rannikkovaltion perusviivojen perusteella. Yhdeksän viivan linjan vaatimus ylittää tämän kehyksen, joten niitä ei voida sovittaa yhteen.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Aluevesi (meripeninkulmaa)',
    'verdict_zone1_body' => 'Valtion suvereeni merialue, joka mitataan perusviivasta.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Yksinomainen talousvyöhyke',
    'verdict_zone2_body' => 'EEZ — rannikkovaltiolla on tällä alueella suvereeneja oikeuksia luonnonvaroihin.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Mannerrinne (enintään, meripeninkulmaa)',
    'verdict_zone3_body' => 'Oikeudet merenpohjan luonnonvaroihin, määräytyvät geologisten edellytysten mukaan.',
    'verdict_foot' => 'Tässä kehyksessä “historialliset oikeudet”, jotka kattavat kokonaisen avomerialueen — kuten Yhdeksän viivan linja antaa ymmärtää — <em>on korvattu</em> UNCLOSin oikeudellisella järjestelmällä, jonka jäsen myös Kiina on.',
];
