<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Kansainvälinen tuomio',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'kolme "ei":tä',
    'verdict_lead' => '12.7.2016 Haagissa toimiva pysyvä välitystuomioistuin (PCA) — joka oli perustettu UNCLOSin liitteen VII mukaisesti Filippiinien Kiinaa vastaan nostamassa asiassa — antoi ratkaisun, jossa Yhdeksän viivan linja hylättiin. <em>Napauta kutakin korttia lukeaksesi koko tekstin.</em>',
    'verdict_card1_khong' => 'EI',
    'verdict_card1_title' => 'historiallista oikeutta',
    'verdict_card1_short' => 'Kiinalla ei ole oikeudellista perustaa vedota historialliseen oikeuteen Yhdeksän viivan linjan sisällä sijaitsevien merialueiden luonnonvaroihin.',
    'verdict_card1_quote' => '“Kiinalla ei ole oikeudellista perustaa vedota historiallisiin oikeuksiin Yhdeksän viivan linjan sisällä olevien merialueiden luonnonvaroihin.”',
    'verdict_card1_more' => '+ Lue ratkaisu',
    'verdict_card2_khong' => 'EI',
    'verdict_card2_title' => 'EEZ:n muodostavaa kohdetta',
    'verdict_card2_short' => 'Mikään Spratlysaarten alueen muodostuma ei täytä edellytyksiä muodostaa Kiinalle talousvyöhykettä — ei edes Ba Binhin saari.',
    'verdict_card2_quote' => '“Yksikään Spratlysaarten alueen muodostuma ei kykene muodostamaan talousvyöhykettä.”',
    'verdict_card2_more' => '+ Lue ratkaisu',
    'verdict_card3_khong' => 'EI',
    'verdict_card3_title' => 'laillista menettelyä',
    'verdict_card3_short' => 'Kiina loukkasi Filippiinien suvereeneja oikeuksia, esti kalastusta ja vahingoitti meriympäristöä.',
    'verdict_card3_quote' => '“Kiina on loukannut Filippiinien suvereeneja oikeuksia, puuttunut kalastustoimintaan Scarborough\'n matalikolla ja aiheuttanut vakavaa vahinkoa koralliriuttaekosysteemille.”',
    'verdict_card3_more' => '+ Lue ratkaisu',
    'verdict_extra1' => 'Kiinan itse piirtämä Yhdeksän viivan linja <strong>ei ole yhdenmukainen</strong> vuoden 1982 UNCLOSin kanssa.',
    'verdict_extra2' => 'Kiina on vahingoittanut Spratlysaarten ekosysteemiä liikakalastuksella ja keinosaarten rakentamisella.',
    'verdict_extra3' => 'Kiinan toimet lisäävät konfliktin riskiä Filippiinien kanssa.',
    'verdict_extra4' => 'Ba Binhin saari (Taiwanin hallinnassa) ei myöskään voi muodostaa talousvyöhykettä.',
    'verdict_subtitle' => 'Miksi se on ristiriidassa UNCLOSin kanssa?',
    'verdict_subtitle_body' => 'Vuoden 1982 UNCLOS määrittelee selkeästi merivyöhykkeet rannikkovaltion perusviivojen perusteella. Yhdeksän viivan linjaa koskeva vaatimus ylittää tämän kehyksen, eikä sitä siksi voida sovittaa siihen.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Aluevesi (mpk)',
    'verdict_zone1_body' => 'Valtion suvereeni merialue, joka mitataan perusviivasta.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Talousvyöhyke',
    'verdict_zone2_body' => 'EEZ — rannikkovaltiolla on tällä alueella suvereenit oikeudet luonnonvaroihin.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Mannerrinne (enintään, mpk)',
    'verdict_zone3_body' => 'Oikeudet merenpohjan luonnonvaroihin, määritettyjen geologisten ehtojen perusteella.',
    'verdict_foot' => 'Tässä kehyksessä “historiallinen oikeus”, joka kattaisi laajan avomerialueen — kuten Yhdeksän viivan linja antaa ymmärtää — <em>on syrjäytetty</em> UNCLOSin oikeusjärjestyksellä, jonka jäsen myös Kiina on.',
];
