<?php

return [
    'footer_index' => 'গ্রন্থাগার',
    'footer_crest_eyebrow' => 'সত্যের গ্রন্থাগারের সমাপ্তি',
    'footer_crest_quote' => '“দক্ষিণ চীন সাগরে শান্তি <b>আন্তর্জাতিক আইনের</b> ভিত্তির উপর নির্মিত।”',
    'footer_crest_sub' => 'ঘৃণা নয় · শুধু সত্য',
    'footer_nav_aria' => 'ফুটারের শেষের ক্রিয়াকলাপ',
    'footer_btn_top' => 'শীর্ষে ফিরে যান',
    'footer_btn_verdict' => 'PCA 2016-এর রায়',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'নাইন-ড্যাশ লাইনের দাবি',
    'footer_brand_eyebrow' => 'বিশেষ বিষয় · ভিয়েতনামের সার্বভৌমত্ব',
    'footer_brand_body' => 'নাইন-ড্যাশ লাইন সম্পর্কে বস্তুনিষ্ঠ সত্য, আন্তর্জাতিক আইন, PCA 2016-এর রায় এবং ঐতিহাসিক উপকরণের মাধ্যমে ব্যাখ্যা — <strong>"হোàng Sa এবং Trường Sa"</strong> দ্বীপপুঞ্জের সার্বভৌমত্ব নিয়ে গভীরতর পাতাগুলোর পরিপূরক। ইতিহাস ও প্রমাণের মাধ্যমে চীনের অযৌক্তিক দাবির খণ্ডন।',
    'footer_refs_title' => 'তথ্যসূত্র',
    'footer_ref1' => 'PCA-এর রায়, ১২/৭/২০১৬',
    'footer_ref2' => 'UNCLOS 1982 — পূর্ণ পাঠ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ঐতিহাসিক উপকরণ ও প্রাচীন মানচিত্র',
    'footer_toc_title' => 'পাতার সূচিপত্র',
    'footer_toc1' => 'নাইন-ড্যাশ লাইন কী',
    'footer_toc2' => 'উৎপত্তি',
    'footer_toc3' => 'কেন বিতর্কিত',
    'footer_toc4' => 'কেন আন্তর্জাতিকভাবে বিরোধিতা করা হয়',
    'footer_toc5' => 'নীরব সাক্ষী',
    'footer_toc6' => 'PCA 2016-এর রায়',
    'footer_toc7' => 'প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ',
    'footer_copy_eyebrow' => 'অলাভজনক প্রকল্প',
    'footer_copy_title' => 'প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ ভিয়েতনামের',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — ভিয়েতনামের সার্বভৌমত্ব-ইকোসিস্টেমে নাইন-ড্যাশ লাইন বিষয়ক বিশেষ পাতা।',
    'footer_copy_body' => 'নাইন-ড্যাশ লাইনের দাবি ব্যাখ্যা করা হয়েছে <strong>বস্তুনিষ্ঠ সত্য</strong>, <strong>আন্তর্জাতিক আইন</strong>, PCA 2016-এর রায় এবং ঐতিহাসিক উপকরণের মাধ্যমে — যা প্যারাসেল দ্বীপপুঞ্জ এবং স্প্র্যাটলি দ্বীপপুঞ্জের সার্বভৌমত্ব নিয়ে গভীরতর পাতাগুলোর পরিপূরক।',
    'footer_copy_ecosystem_aria' => 'একই প্রকল্পের অন্যান্য পাতা',
    'footer_copy_ecosystem_label' => 'একই ইকোসিস্টেমে',
    'footer_copy_disclaimer' => 'এই বিষয়বস্তু শিক্ষা ও সচেতনতা বৃদ্ধির উদ্দেশ্যে; এটি ভিয়েতনাম সরকারের আনুষ্ঠানিক অবস্থানের বিকল্প নয়।',
    'footer_copy' => '<strong>© :year নাইন-ড্যাশ লাইন</strong> — অলাভজনক প্রকল্পের একটি অংশ <strong>প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ ভিয়েতনামের</strong> এর অধীনে এই নেটওয়ার্ক: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'পাতার বিষয়বস্তুর অঙ্গীকার',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016-এর রায়',
    'footer_chip3' => 'ঐতিহাসিক প্রমাণ',
    'footer_chip4' => 'প্রাচীন মানচিত্র',
    'footer_chip5' => 'বস্তুনিষ্ঠ সত্য',
    'footer_chip6' => 'দক্ষিণ চীন সাগরে শান্তি',
];
