<?php

return [
    'footer_index' => 'গ্রন্থাগার',
    'footer_crest_eyebrow' => 'সত্যের গ্রন্থাগারের সমাপ্তি',
    'footer_crest_quote' => '“দক্ষিণ চীন সাগরে শান্তি গড়ে ওঠে <b>আন্তর্জাতিক আইনের</b> ভিত্তির ওপর।”',
    'footer_crest_sub' => 'ঘৃণা নয় · কেবল সত্য',
    'footer_nav_aria' => 'পাদলেখের কার্যক্রম',
    'footer_btn_top' => 'পাতার শীর্ষে ফিরে যান',
    'footer_btn_verdict' => 'PCA 2016 রায়',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'নাইন-ড্যাশ লাইন',
    'footer_brand_body' => 'বাস্তব তথ্য, আন্তর্জাতিক আইন এবং ঐতিহাসিক নথির ওপর ভিত্তি করে একটি ব্যাখ্যামূলক সাইট — প্রমাণ দিয়ে নাইন-ড্যাশ লাইনের দাবি খণ্ডন করে, স্লোগান দিয়ে নয়।',
    'footer_refs_title' => 'তথ্যসূত্র',
    'footer_ref1' => 'PCA রায়, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — পূর্ণ পাঠ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ঐতিহাসিক উপকরণ ও প্রাচীন মানচিত্র',
    'footer_toc_title' => 'পাতার সূচিপত্র',
    'footer_toc1' => 'নাইন-ড্যাশ লাইন কী',
    'footer_toc2' => 'উৎপত্তি',
    'footer_toc3' => 'কেন বিতর্কিত',
    'footer_toc4' => 'কেন আন্তর্জাতিকভাবে বিরোধিতা করা হয়',
    'footer_toc5' => 'নীরব সাক্ষী',
    'footer_toc6' => 'PCA 2016 রায়',
    'footer_toc7' => 'প্যারাসেল দ্বীপপুঞ্জ - স্প্র্যাটলি দ্বীপপুঞ্জ',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — দক্ষিণ চীন সাগর সম্পর্কে নিরপেক্ষ সত্য।<br>ইকোসিস্টেম: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'কোনো স্থানাঙ্ক নেই',
];
