<?php

return [
    'footer_index' => 'গ্রন্থাগার',
    'footer_crest_eyebrow' => 'সত্যের গ্রন্থাগারসমাপ্তি',
    'footer_crest_quote' => '“দক্ষিণ চীন সাগরে শান্তি প্রতিষ্ঠিত হয় <b>আন্তর্জাতিক আইন</b>-এর ভিত্তির ওপর।”',
    'footer_crest_sub' => 'বিদ্বেষ নয় · কেবল সত্য',
    'footer_nav_aria' => 'পৃষ্ঠার নিচের কার্যক্রম',
    'footer_btn_top' => 'পৃষ্ঠার শীর্ষে',
    'footer_btn_verdict' => '২০১৬ সালের PCA রায়',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'নাইন-ড্যাশ লাইনের দাবি',
    'footer_brand_eyebrow' => 'বিশেষ বিষয় · ভিয়েতনামের সার্বভৌমত্ব',
    'footer_brand_body' => 'নাইন-ড্যাশ লাইনকে নিরপেক্ষ সত্য, আন্তর্জাতিক আইন, ২০১৬ সালের PCA রায় এবং ঐতিহাসিক উপাত্তের মাধ্যমে ব্যাখ্যা করা হয়েছে — এটি দুই দ্বীপপুঞ্জ <strong>"প্যারাসেল দ্বীপপুঞ্জ এবং স্প্র্যাটলি দ্বীপপুঞ্জ"</strong>-এর সার্বভৌমত্ব নিয়ে গভীরতর পাতাগুলোর পরিপূরক। চীনের ভিত্তিহীন দাবিকে ইতিহাস ও প্রমাণের মাধ্যমে খণ্ডন করা হয়েছে।',
    'footer_refs_title' => 'তথ্যসূত্র',
    'footer_ref1' => 'PCA রায়, ১২/৭/২০১৬',
    'footer_ref2' => 'UNCLOS 1982 — পূর্ণ পাঠ',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'ঐতিহাসিক নথি ও প্রাচীন মানচিত্র',
    'footer_toc_title' => 'পৃষ্ঠার বিষয়সূচি',
    'footer_toc1' => 'নাইন-ড্যাশ লাইন কী',
    'footer_toc2' => 'উৎপত্তি',
    'footer_toc3' => 'কেন বিতর্কের সৃষ্টি',
    'footer_toc4' => 'কেন আন্তর্জাতিকভাবে বিরোধিতা করা হয়',
    'footer_toc5' => 'নীরব সাক্ষীরা',
    'footer_toc6' => '২০১৬ সালের PCA রায়',
    'footer_toc7' => 'প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ',
    'footer_copy_eyebrow' => 'অলাভজনক প্রকল্প',
    'footer_copy_title' => 'প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ ভিয়েতনামের অংশ',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — ভিয়েতনামের সার্বভৌমত্ব-পরিবেশের মধ্যে নাইন-ড্যাশ লাইন বিষয়ক বিশেষ পৃষ্ঠা।',
    'footer_copy_body' => 'নাইন-ড্যাশ লাইনের দাবিকে <strong>নিরপেক্ষ সত্য</strong>, <strong>আন্তর্জাতিক আইন</strong>, ২০১৬ সালের PCA রায় এবং ঐতিহাসিক উপাত্তের মাধ্যমে ব্যাখ্যা করা হয়েছে — যা প্যারাসেল দ্বীপপুঞ্জ ও স্প্র্যাটলি দ্বীপপুঞ্জের সার্বভৌমত্ব নিয়ে গভীরতর পাতাগুলোর পরিপূরক।',
    'footer_copy_ecosystem_aria' => 'একই প্রকল্পের অন্যান্য পৃষ্ঠা',
    'footer_copy_ecosystem_label' => 'একই ইকোসিস্টেম',
    'footer_copy_disclaimer' => 'এই বিষয়বস্তু শিক্ষা ও সচেতনতা বৃদ্ধির উদ্দেশ্যে; এটি ভিয়েতনাম রাষ্ট্রের আনুষ্ঠানিক অবস্থানের বিকল্প নয়।',
    'footer_copy' => '<strong>© :year নাইন-ড্যাশ লাইন</strong> — অলাভজনক প্রকল্প <strong>প্যারাসেল দ্বীপপুঞ্জ – স্প্র্যাটলি দ্বীপপুঞ্জ ভিয়েতনামের অংশ</strong>-এর একটি অংশ, নীচের সিস্টেমের অন্তর্গত: <a href="https://paracelislands.net/bn" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/bn" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/bn" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/bn" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/bn" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'পৃষ্ঠার বিষয়বস্তুর প্রতিশ্রুতি',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '২০১৬ সালের PCA রায়',
    'footer_chip3' => 'ঐতিহাসিক প্রমাণ',
    'footer_chip4' => 'প্রাচীন মানচিত্র',
    'footer_chip5' => 'নিরপেক্ষ সত্য',
    'footer_chip6' => 'দক্ষিণ চীন সাগরে শান্তি',
];
