<?php

return [
    'nav_logo_name' => 'নাইন-ড্যাশ লাইন',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'নাইন-ড্যাশ লাইন',
    'nav_rail_aria' => 'বিভাগভিত্তিক নেভিগেশন',
    'nav_rail_what' => 'সংজ্ঞা',
    'nav_rail_origin' => 'উৎপত্তি',
    'nav_rail_dispute' => 'বিতর্ক',
    'nav_rail_opposition' => 'বিরোধিতা',
    'nav_rail_witnesses' => 'প্রাচীন মানচিত্র',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'প্যারাসেল দ্বীপপুঞ্জ - স্প্র্যাটলি দ্বীপপুঞ্জ',
    'nav_sound_off' => 'পটভূমির সঙ্গীত চালু করুন',
    'nav_sound_on' => 'পটভূমির সঙ্গীত বন্ধ করুন',
    'nav_share' => 'শেয়ার',
    'dialog_title' => 'প্রদর্শনের ভাষা',
    'language' => 'ভাষা',
    'display_hint' => ':count ভাষা',
    'search_placeholder' => 'ভাষা খুঁজুন…',
    'cancel' => 'বাতিল',
    'apply' => 'প্রয়োগ',
    'sound_off' => 'পটভূমির শব্দ চালু করুন',
    'sound_on' => 'পটভূমির শব্দ বন্ধ করুন',
    'lang_trigger' => 'ভাষা নির্বাচন করুন',
    'close' => 'বন্ধ',
    'no_results' => 'কোনো ভাষা পাওয়া যায়নি',
    'contribute' => 'শেয়ার করুন',
];
