<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Avslutter sannhetens bibliotek',
    'footer_crest_quote' => '“Fred i Sør-Kinahavet bygges på grunnlaget av <b>folkeretten</b>.”',
    'footer_crest_sub' => 'Ingen hat · Bare sannhet',
    'footer_nav_aria' => 'Handlinger nederst på siden',
    'footer_btn_top' => 'Tilbake til toppen',
    'footer_btn_verdict' => 'PCA-kjennelsen 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Ni-streklinjen',
    'footer_brand_body' => 'En forklaringsside basert på objektive fakta, folkeretten og historiske kilder — som avviser kravene knyttet til Ni-streklinjen med bevis, ikke slagord.',
    'footer_refs_title' => 'Kilder',
    'footer_ref1' => 'PCA-kjennelsen, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — full tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiske kilder og gamle kart',
    'footer_toc_title' => 'Sidens innhold',
    'footer_toc1' => 'Hva er Ni-streklinjen',
    'footer_toc2' => 'Opprinnelse',
    'footer_toc3' => 'Hvorfor det er kontroversielt',
    'footer_toc4' => 'Hvorfor det internasjonale samfunnet avviser det',
    'footer_toc5' => 'Tause vitner',
    'footer_toc6' => 'PCA-kjennelsen 2016',
    'footer_toc7' => 'Paraceløyene – Spratlyøyene',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektiv sannhet om Sør-Kinahavet.<br>Økosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Ingen koordinater',
];
