<?php

return [
    'footer_index' => 'Bibliotek',
    'footer_crest_eyebrow' => 'Avslutningen på sannhetsbiblioteket',
    'footer_crest_quote' => '“Freden i Sør-Kinahavet er bygget på grunnlaget av <b>folkeretten</b>.”',
    'footer_crest_sub' => 'Ingen hat · Bare sannhet',
    'footer_nav_aria' => 'Handlinger nederst på siden',
    'footer_btn_top' => 'Til toppen',
    'footer_btn_verdict' => 'PCA-avgjørelsen 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Kravet om Ni-streklinjen',
    'footer_brand_eyebrow' => 'Temaside · Vietnams suverenitet',
    'footer_brand_body' => 'En forklaring av Ni-streklinjen gjennom objektive fakta, folkeretten, PCA-avgjørelsen fra 2016 og historiske kilder — som et tillegg til de fordypende sidene om suvereniteten over de to øygruppene <strong>"Paraceløyene og Spratlyøyene"</strong>. Den avviser Kinas urimelige krav med historie og bevis.',
    'footer_refs_title' => 'Referanser',
    'footer_ref1' => 'PCA-avgjørelsen, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — full tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historiske kilder og gamle kart',
    'footer_toc_title' => 'Sideinnhold',
    'footer_toc1' => 'Hva Ni-streklinjen er',
    'footer_toc2' => 'Opprinnelse',
    'footer_toc3' => 'Hvorfor den er omstridt',
    'footer_toc4' => 'Hvorfor verden avviser den',
    'footer_toc5' => 'Tause vitner',
    'footer_toc6' => 'PCA-avgjørelsen 2016',
    'footer_toc7' => 'Paraceløyene – Spratlyøyene',
    'footer_copy_eyebrow' => 'Ideelt, ikke-kommersielt prosjekt',
    'footer_copy_title' => 'Paraceløyene – Spratlyøyene tilhører Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Temaside om Ni-streklinjen i Vietnams suverenitetsøkosystem.',
    'footer_copy_body' => 'En forklaring av Ni-streklinjen gjennom <strong>objektive fakta</strong>, <strong>folkeretten</strong>, PCA-avgjørelsen fra 2016 og historiske kilder — som et tillegg til de fordypende sidene om suvereniteten over øygruppene Paraceløyene og Spratlyøyene.',
    'footer_copy_ecosystem_aria' => 'Prosjektsider med felles profil',
    'footer_copy_ecosystem_label' => 'Samme økosystem',
    'footer_copy_disclaimer' => 'Innholdet er ment for opplæring og bevisstgjøring; det erstatter ikke Den sosialistiske republikken Vietnams offisielle standpunkt.',
    'footer_copy' => '<strong>© :year Ni-streklinjen</strong> — En del av det ideelle prosjektet <strong>Paraceløyene – Spratlyøyene tilhører Vietnam</strong> i systemet: <a href="https://paracelislands.net/no" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/no" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/no" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/no" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/no" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Løfter for sidens innhold',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-avgjørelsen 2016',
    'footer_chip3' => 'Historiske bevis',
    'footer_chip4' => 'Gamle kart',
    'footer_chip5' => 'Objektive fakta',
    'footer_chip6' => 'Fred i Sør-Kinahavet',
];
