<?php

return [
    'nav_logo_name' => 'Ni-streklinjen',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Ni-streklinjen',
    'nav_rail_aria' => 'Navigasjon etter tema',
    'nav_rail_what' => 'Definisjon',
    'nav_rail_origin' => 'Opprinnelse',
    'nav_rail_dispute' => 'Strid',
    'nav_rail_opposition' => 'Motstand',
    'nav_rail_witnesses' => 'Gamle kart',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paraceløyene – Spratlyøyene',
    'nav_sound_off' => 'Slå på bakgrunnsmusikk',
    'nav_sound_on' => 'Slå av bakgrunnsmusikk',
    'nav_share' => 'Del',
    'dialog_title' => 'Visningsspråk',
    'language' => 'Språk',
    'display_hint' => ':count språk',
    'search_placeholder' => 'Søk etter språk…',
    'cancel' => 'Avbryt',
    'apply' => 'Bruk',
    'sound_off' => 'Slå på bakgrunnslyd',
    'sound_on' => 'Slå av bakgrunnslyd',
    'lang_trigger' => 'Velg språk',
    'close' => 'Lukk',
    'no_results' => 'Fant ikke noe språk',
    'contribute' => 'Del',
];
