<?php

return [
    'opposition_index' => 'Motstand',
    'opposition_label' => 'Hvorfor det internasjonale samfunnet protesterer',
    'opposition_title' => 'Motstanden bygger på',
    'opposition_title_accent' => 'lov, ikke følelser',
    'opposition_lead' => 'Kort tid etter at Ni-streklinjen ble lagt fram for FN i 2009, protesterte mange stater og akademikere — med konkrete juridiske argumenter.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Bare én dag etter at Kina la kartet over Ni-streklinjen fram for FNs generalsekretær (7.5.2009), sendte disse landene protestnotater i tur og orden og avviste kravet.',
    'opposition_voice1_chip1' => 'Protestnote',
    'opposition_voice1_chip2' => 'Ikke i samsvar med UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippinene',
    'opposition_voice2_body' => 'Sendte et diplomatisk brev til FN og erklærte at Kinas krav i Sør-Kinahavet var "uten grunnlag i folkeretten" — et utgangspunkt for den senere voldgiftsaken.',
    'opposition_voice2_chip1' => 'Grunnlag for PCA-saken',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'USAs utenriksdepartement — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analysen viste: kart fra ulike år var inkonsistente når det gjaldt linjens plassering; linjen trengte inn på fastlandet i stedet for å følge midtlinjen; mange enheter oppfylte ikke kriteriene for å være en "øy" og kunne derfor ikke ha EEZ.',
    'opposition_voice3_chip1' => 'Oppfyller ikke de juridiske vilkårene',
    'opposition_voice3_chip2' => 'Offisiell analyse',
    'opposition_voice4_year' => 'Akademisk',
    'opposition_voice4_title' => '"Historiske farvann" er foreldet',
    'opposition_voice4_body' => 'Dette konseptet gjelder bare for bukter og kystnære vannområder — det kan ikke omfatte et helt vidstrakt havområde. I 2003 avviste også Taiwan selv politikken om "historiske farvann" som var blitt nevnt i 1993.',
    'opposition_voice4_chip1' => 'Selv kinesiske forskere er ikke enige',
];
