<?php

return [
    'sovereignty_index' => 'Paraceløyene – Spratlyøyene',
    'sovereignty_label' => 'Den uunngåelige konklusjonen',
    'sovereignty_title' => 'Paraceløyene – Spratlyøyene',
    'sovereignty_title_accent' => 'tilhører Vietnam',
    'sovereignty_lead' => 'Denne siden forklarer Ni-streklinjen. Avslutningen svarer på det neste spørsmålet: hvem har suverenitet over de to øygruppene Paraceløyene og Spratlyøyene? I lys av historisk forvaltning og folkerett er det konsekvente svaret Vietnam.',
    'sovereignty_thesis_label' => 'Samlet hovedpoeng',
    'sovereignty_thesis_lock1' => 'Ingen rettslig koordinat',
    'sovereignty_thesis_lock2' => 'PCA 2016 avviste det',
    'sovereignty_thesis_lock3' => 'Gamle kart omfatter ikke',
    'sovereignty_thesis_body' => 'Etter de seks delene ovenfor er tre ting klare: Ni-streklinjen er tegnet for hånd og har ingen rettslig koordinat; voldgiftsdomstolen i 2016 avviste kravet; og gamle kart fra Kina selv omfatter ikke Sør-Kinahavet. Vietnams suverenitet bygger ikke på slagord, men på at den vietnamesiske staten — fra Nguyễn-herskernes tid — fredelig og kontinuerlig har forvaltet området da de to øygruppene fortsatt var terra nullius.',
    'sovereignty_spine_caption' => 'Milepæler for kontinuerlig forvaltning',
    'sovereignty_spine_title' => 'Én ubrutt tidslinje',
    'sovereignty_spine_range' => '17. århundre → i dag',
    'sovereignty_chron1_year' => '17. årh.',
    'sovereignty_chron1_title' => 'Hoàng Sa-gruppen',
    'sovereignty_chron1_body' => 'Nguyễn-herskerne sendte Hoàng Sa-gruppen for å kartlegge, måle sjøveier og utnytte havet — en faktisk utøvelse av forvaltning.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kong Gia Long',
    'sovereignty_chron2_body' => 'Hisset flagget på Paraceløyene og bekreftet Vietnams suverenitet overfor datidens verden.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kong Minh Mạng',
    'sovereignty_chron3_body' => 'Oppmålte, reiste steinmarkører og registrerte øygruppene på hoffets offisielle kart.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuerlig arvtakelse',
    'sovereignty_chron4_body' => 'Frankrike anerkjente og fortsatte forvaltningen; Paraceløyene ble innlemmet i Thừa Thiên-provinsen — et grunnlag for dagens vietnamesiske stat.',
    'sovereignty_chron5_year' => 'I dag',
    'sovereignty_chron5_title' => 'Lov og praksis',
    'sovereignty_chron5_body' => 'Vietnam forvalter i tråd med UNCLOS, diplomati og arkivmateriale; kravene fra Ni-streklinjen kan ikke erstatte disse bevisene.',
    'sovereignty_balance_label' => 'Balanse i bevisene',
    'sovereignty_balance_medallion_title' => 'Sammenligning av begge sider',
    'sovereignty_vn_tag' => 'Den vietnamesiske siden',
    'sovereignty_vn_title' => 'Suverenitet fastslått gjennom handling',
    'sovereignty_vn_body' => 'Reell okkupasjon da området var terra nullius, deretter åpen og kontinuerlig forvaltning gjennom århundrer — med kongelige forordninger, steinmarkører, kart og administrative arkiver. Denne fremgangsmåten er i samsvar med UNCLOS og internasjonal praksis.',
    'sovereignty_dash_tag' => 'Ni-streklinjen-siden',
    'sovereignty_dash_title' => 'Et krav kan ikke oppveie bevis',
    'sovereignty_dash_body' => 'En linje tegnet i 1948, uten koordinater, ble avvist av PCA i 2016 og strider mot UNCLOS — slik del 03 til 06 har vist. Derfor kan konklusjonen om suverenitet over de to øygruppene ikke bygge på Ni-streklinjen.',
    'sovereignty_seal_quote' => 'Vietnam løser tvister med <strong>fredelige midler</strong>, på grunnlag av folkeretten — særlig UNCLOS 1982 — med mål om et Sør-Kinahavet som er fredelig, samarbeidspreget og utviklingsorientert.',
    'sovereignty_seal_cite' => 'Vietnams standpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hovedprosjektet i samme økosystem',
    'sovereignty_next_title' => 'Les hele dokumentasjonen om Paraceløyene – Spratlyøyene',
    'sovereignty_next_body' => 'Den detaljerte dokumentasjonen — kilder, kart, tidslinjer og juridiske argumenter — finnes på <strong>paracelislands.net</strong>, hvor temaet om suverenitet over de to øygruppene presenteres helhetlig. Siden du leser nå, knytter bare logikken fra Ni-streklinjen til denne konklusjonen.',
    'sovereignty_next_cta' => 'Åpne paracelislands.net',
];
