<?php

return [
    'sovereignty_index' => 'Paraceløyene – Spratlyøyene',
    'sovereignty_label' => 'Den uunngåelige konklusjonen',
    'sovereignty_title' => 'Paraceløyene – Spratlyøyene',
    'sovereignty_title_accent' => 'tilhører Vietnam',
    'sovereignty_lead' => 'Denne siden forklarer Ni-streklinjen. Konklusjonen svarer på det neste spørsmålet: hvem har suverenitet over de to øygruppene Paraceløyene og Spratlyøyene? Ut fra historisk forvaltning og folkeretten er det konsekvente svaret Vietnam.',
    'sovereignty_thesis_label' => 'Sammenfattet hovedpoeng',
    'sovereignty_thesis_lock1' => 'Ingen juridiske koordinater',
    'sovereignty_thesis_lock2' => 'PCA 2016 avviser',
    'sovereignty_thesis_lock3' => 'Gamle kart omfatter ikke',
    'sovereignty_thesis_body' => 'Etter de seks punktene ovenfor står tre ting klart: Ni-streklinjen er tegnet for hånd og har ingen juridiske koordinater; voldgiftsdomstolen i 2016 avviste kravet; og de gamle kartene fra selve Kina omfatter ikke Sør-Kinahavet. Vietnams suverenitet bygger ikke på slagord, men på at den vietnamesiske staten — fra Nguyễn-herskernes tid — forvaltet området fredelig og kontinuerlig da de to øygruppene fortsatt var terra nullius.',
    'sovereignty_spine_caption' => 'Kontinuerlige forvaltningspunkter',
    'sovereignty_spine_title' => 'Én tidslinje, uten avbrudd',
    'sovereignty_spine_range' => '17. århundre → i dag',
    'sovereignty_chron1_year' => '17. årh.',
    'sovereignty_chron1_title' => 'Hoàng Sa-ekspedisjonen',
    'sovereignty_chron1_body' => 'Nguyễn-herskerne sendte Hoàng Sa-ekspedisjonen for å undersøke, måle sjøruter og drive virksomhet til havs — og utøvde dermed faktisk forvaltning.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kong Gia Long',
    'sovereignty_chron2_body' => 'Heiste flagget på Paraceløyene og bekreftet Vietnams suverenitet overfor datidens omverden.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kong Minh Mạng',
    'sovereignty_chron3_body' => 'Kartla, reiste steinmarkører og førte øygruppen inn på hoffets offisielle kart.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuerlig videreføring',
    'sovereignty_chron4_body' => 'Frankrike anerkjente og fortsatte forvaltningen; Paraceløyene ble innlemmet i Thừa Thiên-provinsen — et grunnlag for dagens vietnamesiske stat.',
    'sovereignty_chron5_year' => 'I dag',
    'sovereignty_chron5_title' => 'Lov og praksis',
    'sovereignty_chron5_body' => 'Vietnam forvalter i tråd med UNCLOS, diplomati og arkivmateriale; kravet om Ni-streklinjen kan ikke erstatte disse bevisene.',
    'sovereignty_balance_label' => 'Balanse i bevisene',
    'sovereignty_balance_medallion_title' => 'Sammenligning av de to sidene',
    'sovereignty_vn_tag' => 'Den vietnamesiske siden',
    'sovereignty_vn_title' => 'Suverenitet fastslått gjennom handling',
    'sovereignty_vn_body' => 'Reell besittelse da området var terra nullius, deretter åpen forvaltning gjennom flere hundre år — med keiserlige dokumenter, steinmarkører, kart og administrative arkiver. Denne fremgangsmåten er i samsvar med UNCLOS og internasjonal praksis.',
    'sovereignty_dash_tag' => 'Ni-streklinjen-siden',
    'sovereignty_dash_title' => 'Et krav kan ikke oppveie bevis',
    'sovereignty_dash_body' => 'En linje tegnet i 1948, uten koordinater, ble avvist av PCA i 2016 og strider mot UNCLOS — slik punktene 03 til 06 allerede har vist. Derfor kan konklusjonen om suverenitet over de to øygruppene ikke bygge på Ni-streklinjen.',
    'sovereignty_seal_quote' => 'Vietnam løser tvister med <strong>fredelige midler</strong>, på grunnlag av folkeretten — særlig UNCLOS 1982 — med mål om et fredelig, samarbeidsorientert og utviklende Sør-Kinahav.',
    'sovereignty_seal_cite' => 'Vietnams standpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hovedprosjektet i samme økosystem',
    'sovereignty_next_title' => 'Les hele bevisgrunnlaget om Paraceløyene – Spratlyøyene',
    'sovereignty_next_body' => 'Den detaljerte dokumentasjonen — kilder, kart, tidslinjer og juridiske argumenter — finnes på siden <strong>paracelislands.net</strong>, hvor temaet om suvereniteten over de to øygruppene er presentert i sin helhet. Siden du leser nå, kobler bare logisk Ni-streklinjen til denne konklusjonen.',
    'sovereignty_next_cta' => 'Åpne paracelislands.net',
];
