<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internasjonal dom',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tre «nei»',
    'verdict_lead' => 'Den 12.7.2016 avsa Den faste voldgiftsdomstolen (PCA) i Haag — opprettet etter vedlegg VII til UNCLOS, i saken Filipinene mot Kina — en dom som avviste kravet om Ni-streklinjen. <em>Klikk på hvert kort for å lese ordlyden.</em>',
    'verdict_card1_khong' => 'NEI',
    'verdict_card1_title' => 'historiske rettigheter',
    'verdict_card1_short' => 'Det finnes ikke noe rettslig grunnlag for at Kina kan hevde historiske rettigheter til ressurser i havområdene innenfor Ni-streklinjen.',
    'verdict_card1_quote' => '“Det finnes ikke noe rettslig grunnlag for at Kina kan hevde historiske rettigheter til ressurser i havområdene innenfor Ni-streklinjen.”',
    'verdict_card1_more' => '+ Les dommen',
    'verdict_card2_khong' => 'NEI',
    'verdict_card2_title' => 'enheter som kan skape EEZ',
    'verdict_card2_short' => 'Ingen enhet i Spratlyøyene oppfyller vilkårene for å skape en økonomisk sone for Kina — heller ikke Itu Aba.',
    'verdict_card2_quote' => '“Ingen enhet i Spratlyøyene har kapasitet til å skape en økonomisk sone.”',
    'verdict_card2_more' => '+ Les dommen',
    'verdict_card3_khong' => 'NEI',
    'verdict_card3_title' => 'lovlig opptreden',
    'verdict_card3_short' => 'Kina krenket Filippinenes suverene rettigheter, hindret fiske og skadet det marine miljøet.',
    'verdict_card3_quote' => '“Kina har krenket Filippinenes suverene rettigheter, blandet seg inn i fiskevirksomhet ved Scarborough-revet og påført alvorlig skade på korallrevets miljø.”',
    'verdict_card3_more' => '+ Les dommen',
    'verdict_extra1' => 'Ni-streklinjen, slik Kina selv har tegnet den, er <strong>ikke i samsvar med</strong> UNCLOS 1982.',
    'verdict_extra2' => 'Kina har skadet økosystemet i Spratlyøyene gjennom overutnyttelse og bygging av kunstige øyer.',
    'verdict_extra3' => 'Kinas handlinger øker risikoen for konflikt med Filippinene.',
    'verdict_extra4' => 'Itu Aba, som kontrolleres av Taiwan, kan heller ikke skape en EEZ.',
    'verdict_subtitle' => 'Hvorfor er den i strid med UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 avgrenser klart havområder på grunnlag av kyststatens basislinjer. Kravet om Ni-streklinjen går utover dette rammeverket og kan derfor ikke settes side om side.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialfarvann (nautiske mil)',
    'verdict_zone1_body' => 'Statens havområde med suverenitet, målt fra basislinjen.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusiv økonomisk sone',
    'verdict_zone2_body' => 'EEZ — kyststaten har suverene rettigheter til ressurser innenfor dette området.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalsokkel (maks., nautiske mil)',
    'verdict_zone3_body' => 'Rettigheter til ressurser på havbunnen, fastsatt etter geologiske vilkår.',
    'verdict_foot' => 'Innenfor dette rammeverket er «historiske rettigheter» som omfattet et helt åpent havområde — slik Ni-streklinjen impliserer — <em>erstattet</em> av det rettslige regimet i UNCLOS, som også Kina er part i.',
];
