<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internasjonal kjennelse',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tre «nei»',
    'verdict_lead' => '12. juli 2016 avsa Den faste voldgiftsdomstolen (PCA) i Haag — opprettet i henhold til vedlegg VII til UNCLOS, i saken Philippines mot Kina — en kjennelse som avviste kravet til Ni-streklinjen. <em>Klikk på hvert kort for å lese ordlyden.</em>',
    'verdict_card1_khong' => 'NEI',
    'verdict_card1_title' => 'historiske rettigheter',
    'verdict_card1_short' => 'Det finnes ikke noe rettslig grunnlag for at Kina kan påberope seg historiske rettigheter til ressurser i havområdene innenfor Ni-streklinjen.',
    'verdict_card1_quote' => '“Det finnes ikke noe rettslig grunnlag for at Kina kan påberope seg historiske rettigheter til ressurser i havområdene innenfor Ni-streklinjen.”',
    'verdict_card1_more' => '+ Les kjennelsen',
    'verdict_card2_khong' => 'NEI',
    'verdict_card2_title' => 'enhet som skaper EEZ',
    'verdict_card2_short' => 'Ingen enheter i Spratlyøyene oppfyller vilkårene for å skape en økonomisk sone for Kina — heller ikke Itu Aba.',
    'verdict_card2_quote' => '“Ingen enheter i Spratlyøyene er i stand til å skape en økonomisk sone.”',
    'verdict_card2_more' => '+ Les kjennelsen',
    'verdict_card3_khong' => 'NEI',
    'verdict_card3_title' => 'lovlig opptreden',
    'verdict_card3_short' => 'Kina krenket Philippinenes suverene rettigheter, hindret fiskeri og påførte skade på havmiljøet.',
    'verdict_card3_quote' => '“Kina har krenket Philippinenes suverene rettigheter, blandet seg inn i fiskeriaktiviteter ved Scarborough-revet og påført alvorlig skade på korallrevets miljø.”',
    'verdict_card3_more' => '+ Les kjennelsen',
    'verdict_extra1' => 'Ni-streklinjen, som Kina selv har tegnet, er <strong>ikke i samsvar med</strong> UNCLOS 1982.',
    'verdict_extra2' => 'Kina har forårsaket skade på økosystemet i Spratlyøyene gjennom overutnyttelse og bygging av kunstige øyer.',
    'verdict_extra3' => 'Kinas handlinger øker risikoen for konflikt med Philippines.',
    'verdict_extra4' => 'Itu Aba (kontrollert av Taiwan) kan heller ikke skape en EEZ.',
    'verdict_subtitle' => 'Hvorfor er det i konflikt med UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 avgrenser klart sjøområder på grunnlag av kyststatens grunnlinjer. Kravet til Ni-streklinjen går utover dette rammeverket og kan derfor ikke forenes med det.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialfarvann (nautiske mil)',
    'verdict_zone1_body' => 'Et havområde under statens suverenitet, målt fra grunnlinjen.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Eksklusiv økonomisk sone',
    'verdict_zone2_body' => 'EEZ — kyststaten har suverene rettigheter til ressursene innenfor dette området.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalsokkel (maks., nautiske mil)',
    'verdict_zone3_body' => 'Rettigheter til havbunnsressurser, i henhold til fastsatte geologiske vilkår.',
    'verdict_foot' => 'Innenfor denne rammen er «historiske rettigheter» som omfattet et helt åpent havområde — slik Ni-streklinjen antyder — <em>erstattet</em> av det rettslige regimet i UNCLOS, som også Kina selv er part i.',
];
