<?php

return [
    'witnesses_index' => 'Gamle kart',
    'witnesses_label' => 'Gamle kinesiske kart',
    'witnesses_title' => 'Den sørligste grensen når bare til',
    'witnesses_title_accent' => 'Hainanøya',
    'witnesses_lead' => 'De gamle kartene tegnet av kinesiske forfattere — ordnet kronologisk — viser alle at <em>Hainanøya er Kinas sørligste punkt</em>, uten Paraceløyene eller Spratlyøyene. Materialet er samlet fra <em>Vietnams nasjonale suverenitet over Paraceløyene og Spratlyøyene</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Se med lupe',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— territoriets sørligste punkt —',
    'witnesses_map1_svg_era' => 'Song-dynastiet · 1136',
    'witnesses_map1_title' => 'Kart fra Song-dynastiet, 1136',
    'witnesses_map1_body' => 'Kinas territorium stopper ved øya Hainan — Paraceløyene og Spratlyøyene ligger utenfor riket.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anvilles grense',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville-kartet, 1735',
    'witnesses_map2_body' => 'Tegnet av J.-B. B. d\'Anville; en kopi fra 1740 ble senere gitt som gave fra Tysklands statsminister til Kinas leder. Qing-dynastiets territorium ender ved Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"Kinas sørligste punkt"',
    'witnesses_map3_svg_era' => 'Keiserlig prefekturkart · 1904',
    'witnesses_map3_title' => 'Keiserlig prefekturkart over rikets geografi',
    'witnesses_map3_body' => 'Trykt av Qing-dynastiet — viser tydelig at Kinas sørligste territorium er øya Hainan.',
    'witnesses_quote' => 'Selv kart som Kina tidligere publiserte, tegnet ikke inn Paraceløyene eller Spratlyøyene som en del av deres territorium.',
    'witnesses_timeline_aria' => 'Tidslinje for gamle kinesiske kart',
    'witnesses_year_aria' => 'Datering',
    'lightbox_aria' => 'Vis forstørret bilde',
    'lightbox_close' => 'Lukk',
    'lightbox_prev' => 'Forrige bilde',
    'lightbox_next' => 'Neste bilde',
];
