<?php

return [
    'footer_index' => 'Kütüphane',
    'footer_crest_eyebrow' => 'Kütüphane gerçeğinin özeti',
    'footer_crest_quote' => '“Güney Çin Denizi’ndeki barış, <b>uluslararası hukuk</b> temeli üzerine inşa edilir.”',
    'footer_crest_sub' => 'Nefret yok · Sadece gerçek',
    'footer_nav_aria' => 'Alt bölüm eylemleri',
    'footer_btn_top' => 'Başa dön',
    'footer_btn_verdict' => 'PCA 2016 Kararı',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Dokuz Çizgi Hattı',
    'footer_brand_body' => 'Nesnel gerçekler, uluslararası hukuk ve tarihî belgeler temeline dayanan açıklayıcı bir site — Dokuz Çizgi Hattı iddiasını sloganlarla değil, kanıtlarla çürütür.',
    'footer_refs_title' => 'Kaynaklar',
    'footer_ref1' => 'PCA Kararı, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — tam metin',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tarihî belgeler ve eski haritalar',
    'footer_toc_title' => 'Sayfa içindekiler',
    'footer_toc1' => 'Dokuz Çizgi Hattı nedir',
    'footer_toc2' => 'Kökeni',
    'footer_toc3' => 'Neden tartışmalı',
    'footer_toc4' => 'Neden uluslararası toplum karşı çıkıyor',
    'footer_toc5' => 'Sessiz tanıklar',
    'footer_toc6' => 'PCA 2016 Kararı',
    'footer_toc7' => 'Paracel Adaları - Spratly Adaları',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Güney Çin Denizi hakkında nesnel gerçekler.<br>Ekosistem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Koordinat yok',
];
