<?php

return [
    'footer_index' => 'Kütüphane',
    'footer_crest_eyebrow' => 'Kütüphanenin son sözü',
    'footer_crest_quote' => '“Güney Çin Denizi’nde barış, <b>uluslararası hukuk</b> temeli üzerine inşa edilir.”',
    'footer_crest_sub' => 'Nefret yok · Yalnızca gerçek',
    'footer_nav_aria' => 'Sayfa altı eylemleri',
    'footer_btn_top' => 'Başa dön',
    'footer_btn_verdict' => '2016 PCA kararı',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Dokuz Çizgi Hattı Talebi',
    'footer_brand_eyebrow' => 'Özel sayfa · Vietnam egemenliği',
    'footer_brand_body' => 'Dokuz Çizgi Hattı’nı nesnel gerçekler, uluslararası hukuk, 2016 PCA kararı ve tarihî belgeler üzerinden açıklıyor — <strong>"Paracel Adaları ve Spratly Adaları"</strong> üzerindeki egemenliğe dair derinlemesine sayfaları tamamlar. Çin’in dayanaksız iddialarını tarih ve kanıtlarla çürütür.',
    'footer_refs_title' => 'Kaynaklar',
    'footer_ref1' => 'PCA kararı, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — tam metin',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tarihî belgeler ve eski haritalar',
    'footer_toc_title' => 'Sayfa içindekiler',
    'footer_toc1' => 'Dokuz Çizgi Hattı nedir',
    'footer_toc2' => 'Kökeni',
    'footer_toc3' => 'Neden tartışmalı',
    'footer_toc4' => 'Neden uluslararası toplum karşı çıkıyor',
    'footer_toc5' => 'Sessiz tanıklar',
    'footer_toc6' => '2016 PCA kararı',
    'footer_toc7' => 'Paracel Adaları – Spratly Adaları',
    'footer_copy_eyebrow' => 'Kâr amacı gütmeyen proje',
    'footer_copy_title' => 'Paracel Adaları – Spratly Adaları Vietnam’a aittir',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Vietnam’ın egemenlik ekosistemi içinde Dokuz Çizgi Hattı’na adanmış özel sayfa.',
    'footer_copy_body' => 'Dokuz Çizgi Hattı iddiasını <strong>nesnel gerçekler</strong>, <strong>uluslararası hukuk</strong>, 2016 PCA kararı ve tarihî belgeler üzerinden açıklar — Paracel Adaları ve Spratly Adaları’nın egemenliğine dair derinlemesine sayfaları tamamlar.',
    'footer_copy_ecosystem_aria' => 'Aynı projedeki sayfalar',
    'footer_copy_ecosystem_label' => 'Aynı ekosistem',
    'footer_copy_disclaimer' => 'İçerik eğitim ve farkındalık amaçlıdır; Vietnam Devleti’nin resmî görüşünün yerine geçmez.',
    'footer_copy' => '<strong>© :year Dokuz Çizgi Hattı</strong> — <strong>Paracel Adaları – Spratly Adaları Vietnam’a aittir</strong> adlı kâr amacı gütmeyen projenin bir parçası; sistem içi siteler: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sayfa içeriği taahhüdü',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 PCA kararı',
    'footer_chip3' => 'Tarihî kanıtlar',
    'footer_chip4' => 'Eski haritalar',
    'footer_chip5' => 'Nesnel gerçekler',
    'footer_chip6' => 'Güney Çin Denizi’nde barış',
];
