<?php

return [
    'footer_index' => 'Kütüphane',
    'footer_crest_eyebrow' => 'Kütüphane gerçeğin kapanışı',
    'footer_crest_quote' => '“Güney Çin Denizi’nde barış, <b>uluslararası hukuk</b> temeli üzerine inşa edilir.”',
    'footer_crest_sub' => 'Nefret yok · Yalnızca gerçek',
    'footer_nav_aria' => 'Alt sayfa eylemleri',
    'footer_btn_top' => 'Başa dön',
    'footer_btn_verdict' => '2016 PCA kararı',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Dokuz Çizgi Hattı İddiası',
    'footer_brand_eyebrow' => 'Özel sayfa · Vietnam egemenliği',
    'footer_brand_body' => 'Dokuz Çizgi Hattı’nı nesnel gerçekler, uluslararası hukuk, 2016 PCA kararı ve tarihsel belgeler üzerinden açıklayan bu içerik — <strong>"Paracel Adaları ve Spratly Adaları"</strong> üzerindeki egemenliğe odaklanan ayrıntılı sayfaları destekler. Çin’in temelsiz iddialarını tarih ve kanıtlarla çürütür.',
    'footer_refs_title' => 'Kaynaklar',
    'footer_ref1' => 'PCA kararı, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — tam metin',
    'footer_ref3' => 'Denizlerdeki Sınırlar No.143 (ABD Dışişleri Bakanlığı)',
    'footer_ref4' => 'Tarihî belgeler ve eski haritalar',
    'footer_toc_title' => 'Sayfa içeriği',
    'footer_toc1' => 'Dokuz Çizgi Hattı nedir',
    'footer_toc2' => 'Kökeni',
    'footer_toc3' => 'Neden tartışmalıdır',
    'footer_toc4' => 'Neden uluslararası alanda reddedilir',
    'footer_toc5' => 'Sessiz tanıklar',
    'footer_toc6' => '2016 PCA kararı',
    'footer_toc7' => 'Paracel Adaları – Spratly Adaları',
    'footer_copy_eyebrow' => 'Kâr amacı gütmeyen proje',
    'footer_copy_title' => 'Paracel Adaları – Spratly Adaları Vietnam’a aittir',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Vietnam’ın egemenlik ekosisteminde Dokuz Çizgi Hattı üzerine özel sayfa.',
    'footer_copy_body' => 'Dokuz Çizgi Hattı iddiasının açıklaması <strong>nesnel gerçekler</strong>, <strong>uluslararası hukuk</strong>, 2016 PCA kararı ve tarihsel belgeler üzerinden yapılır — Paracel Adaları ve Spratly Adaları üzerindeki egemenliğe adanmış ayrıntılı sayfaları destekler.',
    'footer_copy_ecosystem_aria' => 'Aynı proje içindeki sayfalar',
    'footer_copy_ecosystem_label' => 'Aynı ekosistem',
    'footer_copy_disclaimer' => 'İçerik eğitim ve farkındalık amacı taşır; Vietnam devletinin resmî görüşünün yerini almaz.',
    'footer_copy' => '<strong>© :year Dokuz Çizgi Hattı</strong> — Kâr amacı gütmeyen <strong>Paracel Adaları – Spratly Adaları Vietnam’a aittir</strong> projesinin bir parçası; şu sistem içindedir: <a href="https://paracelislands.net/tr" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/tr" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/tr" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/tr" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/tr" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Sayfa içerik taahhüdü',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 PCA kararı',
    'footer_chip3' => 'Tarihî kanıtlar',
    'footer_chip4' => 'Eski haritalar',
    'footer_chip5' => 'Nesnel gerçekler',
    'footer_chip6' => 'Güney Çin Denizi’nde barış',
];
