<?php

return [
    'nav_logo_name' => 'Dokuz Çizgi Hattı',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Dokuz Çizgi Hattı',
    'nav_rail_aria' => 'Bölümlere göre gezinme',
    'nav_rail_what' => 'Tanım',
    'nav_rail_origin' => 'Köken',
    'nav_rail_dispute' => 'Tartışma',
    'nav_rail_opposition' => 'İtiraz',
    'nav_rail_witnesses' => 'Eski haritalar',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracel Adaları – Spratly Adaları',
    'nav_sound_off' => 'Arka plan müziğini aç',
    'nav_sound_on' => 'Arka plan müziğini kapat',
    'nav_share' => 'Paylaş',
    'dialog_title' => 'Gösterim dili',
    'language' => 'Dil',
    'display_hint' => ':count dil',
    'search_placeholder' => 'Dil ara…',
    'cancel' => 'İptal',
    'apply' => 'Uygula',
    'sound_off' => 'Arka plan sesini aç',
    'sound_on' => 'Arka plan sesini kapat',
    'lang_trigger' => 'Dil seç',
    'close' => 'Kapat',
    'no_results' => 'Dil bulunamadı',
    'contribute' => 'Paylaş',
];
