<?php

return [
    'opposition_index' => 'İtiraz',
    'opposition_label' => 'Uluslararası toplum neden karşı çıkıyor',
    'opposition_title' => 'İtirazın dayanağı',
    'opposition_title_accent' => 'duygular değil, hukuk',
    'opposition_lead' => 'Dokuz Çizgi Hattı 2009 yılında Birleşmiş Milletler’e sunulduktan hemen sonra, birçok ülke ve akademisyen somut hukukî gerekçelerle buna itiraz etti.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayıs',
    'opposition_voice1_title' => 'Vietnam · Malezya · Endonezya',
    'opposition_voice1_body' => 'Çin, Dokuz Çizgi Hattı haritasını Birleşmiş Milletler Genel Sekreteri’ne sunduktan yalnızca bir gün sonra (7/5/2009), bu ülkeler sırayla itiraz notaları göndererek iddiayı reddetti.',
    'opposition_voice1_chip1' => 'İtiraz notası',
    'opposition_voice1_chip2' => '1982 UNCLOS ile uyumlu değil',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinler',
    'opposition_voice2_body' => 'Birleşmiş Milletler’e diplomatik mektup göndererek, Çin’in Güney Çin Denizi’ndeki iddialarının "uluslararası hukuka göre dayanağı yok" olduğunu belirtti — bu, ardından Tahkim Mahkemesi’ne açılacak davanın temelini oluşturdu.',
    'opposition_voice2_chip1' => 'PCA davasının zemini',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'ABD Dışişleri Bakanlığı — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiz şu noktaları ortaya koydu: yıllara göre haritalarda çizgi konumu tutarsızdı; çizgi, orta hattı esas almak yerine kara içine taşmaktaydı; birçok unsur, EEZ’ye sahip olabilecek bir "ada" niteliğini taşımıyordu.',
    'opposition_voice3_chip1' => 'Hukukî koşulları karşılamıyor',
    'opposition_voice3_chip2' => 'Resmî analiz',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '"Tarihî sular" kavramı artık geçerli değil',
    'opposition_voice4_body' => 'Bu kavram yalnızca körfezler ve kıyıya yakın iç sular için geçerlidir — geniş bir açık deniz alanını kapsayamaz. 2003 yılında, bizzat Tayvan da 1993’te öne sürülen "tarihî sular" politikasını reddetmiştir.',
    'opposition_voice4_chip1' => 'Çinli akademisyenler arasında bile görüş birliği yok',
];
