<?php

return [
    'opposition_index' => 'Karşı çıkış',
    'opposition_label' => 'Uluslararası toplum neden karşı çıkıyor',
    'opposition_title' => 'Karşı çıkışın dayanağı',
    'opposition_title_accent' => 'duygularda değil, hukukta',
    'opposition_lead' => 'Dokuz Çizgi Hattı 2009\'da Birleşmiş Milletler\'e sunulduktan hemen sonra, birçok ülke ve akademisyen somut hukuki gerekçelerle buna karşı çıktı.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayıs',
    'opposition_voice1_title' => 'Vietnam · Malezya · Endonezya',
    'opposition_voice1_body' => 'Çin, Dokuz Çizgi Hattı haritasını Birleşmiş Milletler Genel Sekreteri\'ne sunduktan sadece bir gün sonra (7/5/2009), bu ülkeler ardı ardına itiraz notaları göndererek bu iddiayı reddetti.',
    'opposition_voice1_chip1' => 'İtiraz notası',
    'opposition_voice1_chip2' => '1982 BMDHS ile uyumlu değil',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinler',
    'opposition_voice2_body' => 'Birleşmiş Milletler\'e diplomatik mektup göndererek, Çin\'in Güney Çin Denizi\'ndeki iddialarının "uluslararası hukuka göre dayanağı olmadığını" belirtti — bu, daha sonra Daimi Tahkim Mahkemesi\'ne açılan davanın öncülü oldu.',
    'opposition_voice2_chip1' => 'PCA davasının öncülü',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'ABD Dışişleri Bakanlığı — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiz şunu ortaya koydu: haritalardaki çizgi konumu yıllara göre tutarsızdır; çizgi, orta hattı esas almak yerine kara içine taşmaktadır; birçok oluşum, EEZ\'ye sahip olmak için "ada" sayılacak yeterlilikte değildir.',
    'opposition_voice3_chip1' => 'Hukuki şartları karşılamıyor',
    'opposition_voice3_chip2' => 'Resmî analiz',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '"Tarihî sular" kavramı artık geçerli değil',
    'opposition_voice4_body' => 'Bu kavram yalnızca körfezler ve kıyıya yakın iç sular için geçerlidir — geniş bir açık deniz alanını kapsayamaz. 2003\'te Tayvan da, 1993\'te ortaya koyduğu "tarihî sular" politikasını reddetmiştir.',
    'opposition_voice4_chip1' => 'Çinli akademisyenler bile fikir birliğinde değil',
];
