<?php

return [
    'sovereignty_index' => 'Paracel Adaları - Spratly Adaları',
    'sovereignty_label' => 'Kaçınılmaz sonuç',
    'sovereignty_title' => 'Paracel Adaları - Spratly Adaları',
    'sovereignty_title_accent' => 'Vietnam\'a aittir',
    'sovereignty_lead' => 'Bu sayfa Dokuz Çizgi Hattı\'nı açıklar. Sonuç bölümü bir sonraki soruyu yanıtlar: Paracel Adaları ve Spratly Adaları üzerinde egemenlik kimdedir? Yönetim tarihi ve uluslararası hukuka göre tutarlı yanıt Vietnam\'dır.',
    'sovereignty_thesis_label' => 'Bütüncül tez',
    'sovereignty_thesis_lock1' => 'Hukuki koordinat yok',
    'sovereignty_thesis_lock2' => 'PCA 2016 reddetti',
    'sovereignty_thesis_lock3' => 'Eski haritalar kapsamıyor',
    'sovereignty_thesis_body' => 'Yukarıdaki altı bölümden sonra üç nokta nettir: Dokuz Çizgi Hattı elle çizilmiştir, hukuki koordinatları yoktur; 2016 Tahkim Mahkemesi iddiayı reddetmiştir; Çin\'in kendi eski haritaları Güney Çin Denizi\'ni kapsamamaktadır. Vietnam\'ın egemenliği slogana değil, Vietnam devletinin — Nguyễn lordları döneminden itibaren — iki takımada henüz sahipsiz araziyken onları barışçıl ve kesintisiz biçimde yönetmiş olmasına dayanır.',
    'sovereignty_spine_caption' => 'Kesintisiz yönetim dönüm noktaları',
    'sovereignty_spine_title' => 'Kesintisiz bir zaman çizgisi',
    'sovereignty_spine_range' => '17. yüzyıl → günümüz',
    'sovereignty_chron1_year' => '17. yy.',
    'sovereignty_chron1_title' => 'Hoàng Sa Birliği',
    'sovereignty_chron1_body' => 'Nguyễn lordları, Hoàng Sa Birliği\'ni denetim, seyir ölçümü ve denizcilik amaçlı faaliyetler için gönderdi — fiilî yönetim yetkisini kullandılar.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'İmparator Gia Long',
    'sovereignty_chron2_body' => 'Hoàng Sa Adaları\'na bayrak dikerek, Vietnam\'ın egemenliğini dönemin dünyasına karşı teyit etti.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'İmparator Minh Mạng',
    'sovereignty_chron3_body' => 'Resmî ölçümler yapıldı, steller dikildi ve takımadalar sarayın resmî haritalarına kaydedildi.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kesintisiz miras',
    'sovereignty_chron4_body' => 'Fransa bunu tanıdı ve yönetimi sürdürdü; Hoàng Sa, Thừa Thiên eyaletine bağlandı — bu da bugünkü Vietnam Devleti için temel oluşturdu.',
    'sovereignty_chron5_year' => 'Günümüz',
    'sovereignty_chron5_title' => 'Hukuk ve fiilî durum',
    'sovereignty_chron5_body' => 'Vietnam, UNCLOS, diplomasi ve arşiv kayıtlarına göre yönetmektedir; Dokuz Çizgi Hattı iddiası bu kanıtların yerini alamaz.',
    'sovereignty_balance_label' => 'Kanıt dengesi',
    'sovereignty_balance_medallion_title' => 'İki tarafın karşılaştırması',
    'sovereignty_vn_tag' => 'Vietnam tarafı',
    'sovereignty_vn_title' => 'Egemenlik fiillerle tesis edilmiştir',
    'sovereignty_vn_body' => 'Arazi sahipsizken fiilî zilyetlik, ardından yüzyıllar boyunca açık yönetim — fermanlar, steller, haritalar ve idarî kayıtlarla. Bu yöntem UNCLOS ve uluslararası teamülle uyumludur.',
    'sovereignty_dash_tag' => 'Dokuz Çizgi Hattı tarafı',
    'sovereignty_dash_title' => 'İddia kanıtın yerini tutamaz',
    'sovereignty_dash_body' => '1948\'de çizilmiş, koordinat içermeyen bir hat, PCA 2016 tarafından reddedilmiş ve UNCLOS\'a aykırıdır — 03 ile 06 arasındaki bölümlerin gösterdiği gibi. Bu yüzden iki takımadanın egemenliğine ilişkin sonuç Dokuz Çizgi Hattı\'na dayanamaz.',
    'sovereignty_seal_quote' => 'Vietnam, anlaşmazlıkları <strong>barışçıl yollarla</strong>, özellikle UNCLOS 1982 olmak üzere uluslararası hukuk temelinde ve Güney Çin Denizi\'nde barış, işbirliği ve kalkınma hedefiyle çözmektedir.',
    'sovereignty_seal_cite' => 'Vietnam\'ın tutumu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Aynı ekosistemdeki ana proje',
    'sovereignty_next_title' => 'Paracel Adaları - Spratly Adaları hakkında tam kanıtları okuyun',
    'sovereignty_next_body' => 'Ayrıntılı dosya — belgeler, haritalar, zaman çizelgesi ve hukukî gerekçeler — <strong>paracelislands.net</strong> sitesinde yer alır; bu site iki takımadanın egemenliği konusunu kapsamlı biçimde sunar. Şu anda okuduğunuz sayfa yalnızca Dokuz Çizgi Hattı\'ndan o sonuca giden mantıksal bağı kurar.',
    'sovereignty_next_cta' => 'paracelislands.net\'i aç',
];
