<?php

return [
    'sovereignty_index' => 'Paracel Adaları - Spratly Adaları',
    'sovereignty_label' => 'Kaçınılmaz Sonuç',
    'sovereignty_title' => 'Paracel Adaları - Spratly Adaları',
    'sovereignty_title_accent' => 'Vietnam\'a aittir',
    'sovereignty_lead' => 'Bu sayfa Dokuz Çizgi Hattı\'nı açıklar. Sonuç bölümü bir sonraki soruya yanıt verir: Paracel Adaları ve Spratly Adaları üzerinde egemenlik kime aittir? Tarihsel yönetim ve uluslararası hukuka göre, yanıt tutarlıdır: Vietnam.',
    'sovereignty_thesis_label' => 'Bütüncül Tez',
    'sovereignty_thesis_lock1' => 'Hukuki koordinat yok',
    'sovereignty_thesis_lock2' => '2016 PCA tarafından reddedildi',
    'sovereignty_thesis_lock3' => 'Eski haritalar kapsamıyor',
    'sovereignty_thesis_body' => 'Yukarıdaki altı bölümden sonra üç nokta nettir: Dokuz Çizgi Hattı elle çizilmiştir, hukuki koordinatlara sahip değildir; 2016 Tahkim Mahkemesi bu iddiayı reddetmiştir; Çin\'in kendi eski haritaları Güney Çin Denizi\'ni kapsamamaktadır. Vietnam\'ın egemenliği sloganlara değil, Vietnam devletinin — Nguyễn beyleri döneminden itibaren — iki takımada henüz sahipsiz topraklarken onları barışçıl ve kesintisiz biçimde yönetmiş olmasına dayanır.',
    'sovereignty_spine_caption' => 'Kesintisiz yönetim dönüm noktaları',
    'sovereignty_spine_title' => 'Kesintisiz bir zaman çizelgesi',
    'sovereignty_spine_range' => '17. yüzyıl → günümüz',
    'sovereignty_chron1_year' => '17. yy',
    'sovereignty_chron1_title' => 'Hoàng Sa Birliği',
    'sovereignty_chron1_body' => 'Nguyễn beyleri, Hoàng Sa Birliği\'ni denizde keşif yapmak, deniz yollarını ölçmek ve kaynak toplamak için görevlendirdi — fiilî yönetim yetkisinin kullanımı.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Gia Long İmparatoru',
    'sovereignty_chron2_body' => 'Hoàng Sa Adaları üzerinde bayrak dikerek, Vietnam\'ın egemenliğini dönemin dünyasına karşı teyit etti.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Minh Mạng İmparatoru',
    'sovereignty_chron3_body' => 'Ölçümler yapıldı, dikilitaşlar dikildi ve takımada saray yönetiminin resmî haritalarına kaydedildi.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kesintisiz ardıllık',
    'sovereignty_chron4_body' => 'Fransa bunu tanıdı ve yönetimi sürdürdü; Hoàng Sa\'yı Thừa Thiên eyaletine kattı — bu, bugünkü Vietnam Devleti için temel oluşturdu.',
    'sovereignty_chron5_year' => 'Günümüz',
    'sovereignty_chron5_title' => 'Hukuk ve uygulama',
    'sovereignty_chron5_body' => 'Vietnam, UNCLOS, diplomasi ve arşiv kayıtları temelinde yönetmektedir; Dokuz Çizgi Hattı iddiası bu kanıtların yerine geçemez.',
    'sovereignty_balance_label' => 'Kanıt dengesi',
    'sovereignty_balance_medallion_title' => 'İki tarafı karşılaştırma',
    'sovereignty_vn_tag' => 'Vietnam tarafı',
    'sovereignty_vn_title' => 'Egemenlik eylemlerle tesis edilmiştir',
    'sovereignty_vn_body' => 'Toprak henüz sahipsizken fiilî zilyetlik, ardından yüzyıllar boyunca açık yönetim — resmî belgeler, dikilitaşlar, haritalar ve idarî kayıtlarla. Bu yöntem UNCLOS ve uluslararası teamül ile uyumludur.',
    'sovereignty_dash_tag' => 'Dokuz Çizgi Hattı tarafı',
    'sovereignty_dash_title' => 'İddia kanıtın yerini tutamaz',
    'sovereignty_dash_body' => '1948\'de çizilmiş, koordinat içermeyen bir hat; 2016 PCA tarafından reddedilmiş ve UNCLOS\'a aykırıdır — 03 ila 06. bölümlerde açıklandığı gibi. Bu nedenle iki takımada üzerindeki egemenlik sonucu Dokuz Çizgi Hattı\'na dayanamaz.',
    'sovereignty_seal_quote' => 'Vietnam anlaşmazlıkları <strong>barışçıl yöntemlerle</strong>, özellikle 1982 UNCLOS başta olmak üzere uluslararası hukuk temelinde çözer; hedefi Güney Çin Denizi\'nde barış, işbirliği ve kalkınmadır.',
    'sovereignty_seal_cite' => 'Vietnam\'ın tutumu · 1982 UNCLOS',
    'sovereignty_next_eyebrow' => 'Aynı ekosistemdeki ana proje',
    'sovereignty_next_title' => 'Paracel Adaları - Spratly Adaları hakkındaki kanıtları tam olarak okuyun',
    'sovereignty_next_body' => 'Ayrıntılı dosya — belgeler, haritalar, zaman çizelgesi ve hukukî argümanlar — <strong>paracelislands.net</strong> sitesinde yer alır; bu site iki takımadanın egemenliği konusunu kapsamlı biçimde sunar. Şu anda okuduğunuz sayfa, Dokuz Çizgi Hattı\'ndan bu sonuca mantıksal bağlantı kurar.',
    'sovereignty_next_cta' => 'paracelislands.net\'i aç',
];
