<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Uluslararası karar',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'üç "Hayır"',
    'verdict_lead' => '12/7/2016 tarihinde, Lahey\'deki Daimi Tahkim Mahkemesi (PCA) — UNCLOS Ek VII uyarınca oluşturulmuş, Filipinler\'in Çin\'e karşı açtığı davada — Dokuz Çizgi Hattı iddiasını reddeden kararını vermiştir. <em>Tam metni okumak için her karta tıklayın.</em>',
    'verdict_card1_khong' => 'HAYIR',
    'verdict_card1_title' => 'tarihsel hak',
    'verdict_card1_short' => 'Çin\'in, Dokuz Çizgi Hattı içindeki deniz alanında bulunan kaynaklar üzerinde tarihsel hak iddia etmesi için hukuki bir dayanak yoktur.',
    'verdict_card1_quote' => '“Çin\'in, Dokuz Çizgi Hattı içindeki deniz alanında bulunan kaynaklar üzerinde tarihsel hak iddia etmesi için hukuki bir dayanak yoktur.”',
    'verdict_card1_more' => '+ Kararı oku',
    'verdict_card2_khong' => 'HAYIR',
    'verdict_card2_title' => 'EEZ oluşturan unsur',
    'verdict_card2_short' => 'Spratly Adaları\'ndaki hiçbir unsur, Taiping Adası da dahil olmak üzere, Çin için münhasır ekonomik bölge oluşturma niteliğine sahip değildir.',
    'verdict_card2_quote' => '“Spratly Adaları\'ndaki hiçbir unsurun münhasır ekonomik bölge oluşturma kapasitesi yoktur.”',
    'verdict_card2_more' => '+ Kararı oku',
    'verdict_card3_khong' => 'HAYIR',
    'verdict_card3_title' => 'hukuka uygun davranış',
    'verdict_card3_short' => 'Çin, Vietnam\'ın egemen haklarını ihlal etmiş, balıkçılığı engellemiş ve deniz çevresine zarar vermiştir.',
    'verdict_card3_quote' => '“Çin, Vietnam\'ın egemen haklarını ihlal etmiş, Scarborough sığlığındaki balıkçılık faaliyetlerine müdahale etmiş ve mercan resifi çevresine ciddi zarar vermiştir.”',
    'verdict_card3_more' => '+ Kararı oku',
    'verdict_extra1' => 'Çin\'in kendi çizdiği Dokuz Çizgi Hattı, 1982 UNCLOS ile <strong>uyumlu değildir</strong>.',
    'verdict_extra2' => 'Çin, aşırı çıkarım ve yapay ada inşası yoluyla Spratly Adaları ekosistemine zarar vermiştir.',
    'verdict_extra3' => 'Çin\'in eylemleri, Vietnam ile çatışma riskini artırmaktadır.',
    'verdict_extra4' => 'Taiping Adası (Tayvan\'ın kontrolünde) da EEZ oluşturamaz.',
    'verdict_subtitle' => 'Neden UNCLOS ile çatışıyor?',
    'verdict_subtitle_body' => '1982 UNCLOS, kıyı devletinin esas hatlarına dayanarak deniz alanlarını açık biçimde belirler. Dokuz Çizgi Hattı iddiası bu çerçevenin dışına çıktığı için onunla bağdaştırılamaz.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Karasuları (deniz mili)',
    'verdict_zone1_body' => 'Esas hatta göre ölçülen, devletin egemenliğindeki deniz alanı.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Münhasır ekonomik bölge',
    'verdict_zone2_body' => 'EEZ — kıyı devleti bu alan içinde kaynaklar üzerinde egemen haklara sahiptir.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kıta sahanlığı (azami, deniz mili)',
    'verdict_zone3_body' => 'Belirlenen jeolojik koşullara göre, deniz tabanı kaynakları üzerindeki haklar.',
    'verdict_foot' => 'Bu çerçevede, Dokuz Çizgi Hattı\'nın ima ettiği gibi, tüm bir açık deniz alanını kapsayan “tarihsel hak” <em>yerini</em> UNCLOS\'un hukukî rejimine bırakmıştır; Çin de bu sözleşmenin tarafıdır.',
];
