<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Uluslararası karar',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'üç kez “Hayır”',
    'verdict_lead' => '12/7/2016 tarihinde, UNCLOS Ek VII uyarınca oluşturulan Lahey\'deki Daimi Tahkim Mahkemesi (PCA), Filipinler\'in Çin\'e karşı açtığı davada Dokuz Çizgi Hattı iddiasını reddeden bir karar verdi. <em>Tam metni okumak için her karta tıklayın.</em>',
    'verdict_card1_khong' => 'HAYIR',
    'verdict_card1_title' => 'tarihi hak',
    'verdict_card1_short' => 'Çin\'in, Dokuz Çizgi Hattı içindeki denizlerde bulunan kaynaklar üzerinde tarihi hak iddia etmesi için hukuki bir dayanak yoktur.',
    'verdict_card1_quote' => '“Çin\'in, Dokuz Çizgi Hattı içindeki denizlerde bulunan kaynaklar üzerinde tarihi hak iddia etmesi için hukuki bir dayanak yoktur.”',
    'verdict_card1_more' => '+ Kararı oku',
    'verdict_card2_khong' => 'HAYIR',
    'verdict_card2_title' => 'EEZ oluşturan varlık',
    'verdict_card2_short' => 'Spratly Adaları\'ndaki hiçbir varlık, Ba Bình Adası da dahil olmak üzere, Çin için münhasır ekonomik bölge oluşturma niteliğine sahip değildir.',
    'verdict_card2_quote' => '“Spratly Adaları\'ndaki hiçbir varlığın münhasır ekonomik bölge oluşturma kapasitesi yoktur.”',
    'verdict_card2_more' => '+ Kararı oku',
    'verdict_card3_khong' => 'HAYIR',
    'verdict_card3_title' => 'meşru eylem',
    'verdict_card3_short' => 'Çin, Filipinler\'in egemen haklarını ihlal etmiş, balıkçılığı engellemiş ve deniz çevresine zarar vermiştir.',
    'verdict_card3_quote' => '“Çin, Filipinler\'in egemen haklarını ihlal etmiş, Scarborough Sığlığı\'ndaki balıkçılık faaliyetlerine müdahale etmiş ve mercan resifi çevresine ciddi zarar vermiştir.”',
    'verdict_card3_more' => '+ Kararı oku',
    'verdict_extra1' => 'Çin\'in kendi çizdiği Dokuz Çizgi Hattı <strong>1982 UNCLOS ile uyumlu değildir</strong>.',
    'verdict_extra2' => 'Çin, aşırı kullanım ve yapay ada inşası yoluyla Spratly Adaları ekosistemine zarar vermiştir.',
    'verdict_extra3' => 'Çin\'in eylemleri Filipinler ile çatışma riskini artırmaktadır.',
    'verdict_extra4' => 'Ba Bình Adası (Tayvan\'ın kontrolünde) da bir EEZ oluşturamaz.',
    'verdict_subtitle' => 'Neden UNCLOS ile çelişiyor?',
    'verdict_subtitle_body' => '1982 UNCLOS, kıyı devletinin esas hatlarına dayalı olarak deniz alanlarını açık biçimde tanımlar. Dokuz Çizgi Hattı iddiası bu çerçevenin dışına taşmaktadır; bu nedenle yan yana konulamaz.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Karasuları (deniz mili)',
    'verdict_zone1_body' => 'Esas hatlardan ölçülen, devletin egemen olduğu deniz alanı.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Münhasır ekonomik bölge',
    'verdict_zone2_body' => 'EEZ — kıyı devleti, bu alan içindeki kaynaklar üzerinde egemen haklara sahiptir.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kıta sahanlığı (en fazla, deniz mili)',
    'verdict_zone3_body' => 'Belirlenen jeolojik koşullara göre deniz tabanı kaynakları üzerindeki haklar.',
    'verdict_foot' => 'Bu çerçevede, Dokuz Çizgi Hattı\'nın ima ettiği gibi tüm bir açık deniz alanını kapsayan “tarihi hak” <em>yerini</em>, Çin\'in de taraf olduğu UNCLOS\'un hukuki rejimine bırakmıştır.',
];
