<?php

return [
    'footer_index' => 'Бібліотека',
    'footer_crest_eyebrow' => 'Завершення бібліотеки фактів',
    'footer_crest_quote' => '«Мир у Південно-Китайському морі будується на основі <b>міжнародного права</b>.»',
    'footer_crest_sub' => 'Без ненависті · Лише правда',
    'footer_nav_aria' => 'Дії в нижній частині сторінки',
    'footer_btn_top' => 'На початок сторінки',
    'footer_btn_verdict' => 'Рішення PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Претензії Лінії дев\'яті пунктирів',
    'footer_brand_eyebrow' => 'Тематична сторінка · Суверенітет Вʼєтнаму',
    'footer_brand_body' => 'Пояснення щодо Лінії дев\'яті пунктирів через об\'єктивні факти, міжнародне право, рішення PCA 2016 та історичні матеріали — на додаток до поглиблених сторінок про суверенітет над двома архіпелагами <strong>"Парасельські острови та Острови Спратлі"</strong>. Спростування безпідставних претензій Китаю за допомогою історії та доказів.',
    'footer_refs_title' => 'Джерела',
    'footer_ref1' => 'Рішення PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — повний текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Історичні матеріали та старовинні карти',
    'footer_toc_title' => 'Зміст сторінки',
    'footer_toc1' => 'Що таке Лінія дев\'яті пунктирів',
    'footer_toc2' => 'Походження',
    'footer_toc3' => 'Чому це викликає суперечки',
    'footer_toc4' => 'Чому міжнародна спільнота заперечує',
    'footer_toc5' => 'Мовчазні свідки',
    'footer_toc6' => 'Рішення PCA 2016',
    'footer_toc7' => 'Парасельські острови – Острови Спратлі',
    'footer_copy_eyebrow' => 'Неприбутковий проєкт',
    'footer_copy_title' => 'Парасельські острови – Острови Спратлі належать Вʼєтнаму',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — тематична сторінка про Лінію дев\'яті пунктирів в екосистемі суверенітету Вʼєтнаму.',
    'footer_copy_body' => 'Пояснення претензій Лінії дев\'яті пунктирів через <strong>об\'єктивні факти</strong>, <strong>міжнародне право</strong>, рішення PCA 2016 та історичні матеріали — на додаток до поглиблених сторінок про суверенітет над архіпелагами Парасельські острови та Острови Спратлі.',
    'footer_copy_ecosystem_aria' => 'Сторінки того самого проєкту',
    'footer_copy_ecosystem_label' => 'Той самий екосистемний простір',
    'footer_copy_disclaimer' => 'Матеріал призначений для освіти та підвищення обізнаності; він не замінює офіційної позиції Держави Вʼєтнам.',
    'footer_copy' => '<strong>© :year Лінія дев\'яті пунктирів</strong> — частина неприбуткового проєкту <strong>Парасельські острови – Острови Спратлі належать Вʼєтнаму</strong> у складі системи: <a href="https://paracelislands.net/uk" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/uk" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/uk" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/uk" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/uk" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Зобов\'язання щодо змісту сторінки',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Рішення PCA 2016',
    'footer_chip3' => 'Історичні докази',
    'footer_chip4' => 'Старовинні карти',
    'footer_chip5' => 'Об\'єктивна правда',
    'footer_chip6' => 'Мир у Південно-Китайському морі',
];
