<?php

return [
    'footer_index' => 'Бібліотека',
    'footer_crest_eyebrow' => 'Завершення бібліотеки фактів',
    'footer_crest_quote' => '“Мир у Південно-Китайському морі будується на основі <b>міжнародного права</b>.”',
    'footer_crest_sub' => 'Без ненависті · Лише правда',
    'footer_nav_aria' => 'Дії внизу сторінки',
    'footer_btn_top' => 'На початок сторінки',
    'footer_btn_verdict' => 'Рішення PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Лінія дев\'яті пунктирів',
    'footer_brand_body' => 'Сторінка, що пояснює на основі об’єктивних фактів, міжнародного права та історичних матеріалів — спростовує претензії щодо Лінії дев\'яті пунктирів доказами, а не гаслами.',
    'footer_refs_title' => 'Джерела',
    'footer_ref1' => 'Рішення PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — повний текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Історичні матеріали та старовинні карти',
    'footer_toc_title' => 'Зміст сторінки',
    'footer_toc1' => 'Що таке Лінія дев\'яті пунктирів',
    'footer_toc2' => 'Походження',
    'footer_toc3' => 'Чому це викликає суперечки',
    'footer_toc4' => 'Чому міжнародна спільнота заперечує',
    'footer_toc5' => 'Мовчазні свідки',
    'footer_toc6' => 'Рішення PCA 2016',
    'footer_toc7' => 'Парасельські острови – Острови Спратлі',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Об’єктивна правда про Південно-Китайське море.<br>Екосистема: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Без координат',
];
