<?php

return [
    'nav_logo_name' => 'Лінія дев\'яті пунктирів',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Лінія дев\'яті пунктирів',
    'nav_rail_aria' => 'Навігація за розділами',
    'nav_rail_what' => 'Визначення',
    'nav_rail_origin' => 'Походження',
    'nav_rail_dispute' => 'Суперечка',
    'nav_rail_opposition' => 'Заперечення',
    'nav_rail_witnesses' => 'Стародавні мапи',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Парасельські острови - Острови Спратлі',
    'nav_sound_off' => 'Увімкнути фонову музику',
    'nav_sound_on' => 'Вимкнути фонову музику',
    'nav_share' => 'Поділитися',
    'dialog_title' => 'Мова відображення',
    'language' => 'Мова',
    'display_hint' => ':count мов',
    'search_placeholder' => 'Пошук мови…',
    'cancel' => 'Скасувати',
    'apply' => 'Застосувати',
    'sound_off' => 'Увімкнути фоновий звук',
    'sound_on' => 'Вимкнути фоновий звук',
    'lang_trigger' => 'Обрати мову',
    'close' => 'Закрити',
    'no_results' => 'Мову не знайдено',
    'contribute' => 'Поділитися',
];
