<?php

return [
    'footer_index' => '라이브러리',
    'footer_crest_eyebrow' => '사실의 장서를 엮다',
    'footer_crest_quote' => '“남중국해의 평화는 <b>국제법</b> 위에 세워져야 한다.”',
    'footer_crest_sub' => '증오 없음 · 오직 진실만',
    'footer_nav_aria' => '하단 작업',
    'footer_btn_top' => '맨 위로',
    'footer_btn_verdict' => '2016년 PCA 판결',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => '남중국해 9단선의 주장',
    'footer_brand_eyebrow' => '주제 페이지 · 베트남의 주권',
    'footer_brand_body' => '남중국해 9단선에 대한 설명을 객관적 사실, 국제법, 2016년 PCA 판결, 역사 자료를 통해 제시하며 — 두 군도 <strong>"파라셀 제도와 스프래틀리 제도"</strong>의 주권에 관한 심화 페이지를 보완합니다. 역사와 증거로 중국의 무리한 주장을 반박합니다.',
    'footer_refs_title' => '참고 자료',
    'footer_ref1' => 'PCA 판결, 2016/7/12',
    'footer_ref2' => 'UNCLOS 1982 — 전문',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => '역사 자료 및 고지도',
    'footer_toc_title' => '페이지 목차',
    'footer_toc1' => '남중국해 9단선이란',
    'footer_toc2' => '기원',
    'footer_toc3' => '왜 논쟁이 되는가',
    'footer_toc4' => '왜 국제사회가 반대하는가',
    'footer_toc5' => '침묵의 증언',
    'footer_toc6' => '2016년 PCA 판결',
    'footer_toc7' => '파라셀 제도 – 스프래틀리 제도',
    'footer_copy_eyebrow' => '비영리 프로젝트',
    'footer_copy_title' => '파라셀 제도 – 스프래틀리 제도는 베트남의 것이다',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — 베트남의 주권 생태계 안에서 남중국해 9단선에 대한 주제 페이지.',
    'footer_copy_body' => '남중국해 9단선의 주장을 <strong>객관적 사실</strong>, <strong>국제법</strong>, 2016년 PCA 판결, 역사 자료를 통해 설명하며 — 파라셀 제도와 스프래틀리 제도의 주권에 관한 심화 페이지를 보완합니다.',
    'footer_copy_ecosystem_aria' => '프로젝트의 다른 페이지',
    'footer_copy_ecosystem_label' => '같은 생태계',
    'footer_copy_disclaimer' => '이 내용은 교육과 인식 제고를 위한 것이며, 베트남 국가의 공식 입장을 대체하지 않습니다.',
    'footer_copy' => '<strong>© :year 남중국해 9단선</strong> — 비영리 프로젝트 <strong>파라셀 제도 – 스프래틀리 제도는 베트남의 것이다</strong>의 일부이며 다음 시스템에 속합니다: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => '페이지 콘텐츠 약속',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016년 PCA 판결',
    'footer_chip3' => '역사적 증거',
    'footer_chip4' => '고지도',
    'footer_chip5' => '객관적 사실',
    'footer_chip6' => '남중국해의 평화',
];
