<?php

return [
    'footer_index' => '라이브러리',
    'footer_crest_eyebrow' => '사실의 라이브러리를 닫으며',
    'footer_crest_quote' => '“남중국해의 평화는 <b>국제법</b>을 기반으로 세워진다.”',
    'footer_crest_sub' => '증오 없음 · 오직 사실만',
    'footer_nav_aria' => '페이지 하단 작업',
    'footer_btn_top' => '맨 위로',
    'footer_btn_verdict' => '2016 PCA 판정',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '남중국해 9단선',
    'footer_brand_body' => '객관적 사실, 국제법, 역사 자료에 기반한 해설 페이지 — 구호가 아니라 증거로 남중국해 9단선 주장을 반박합니다.',
    'footer_refs_title' => '참고 자료',
    'footer_ref1' => 'PCA 판정, 2016.7.12',
    'footer_ref2' => 'UNCLOS 1982 — 전문',
    'footer_ref3' => 'Limits in the Seas №143 (미 국무부)',
    'footer_ref4' => '역사 자료 및 고지도',
    'footer_toc_title' => '페이지 목차',
    'footer_toc1' => '남중국해 9단선이란',
    'footer_toc2' => '기원',
    'footer_toc3' => '왜 논란이 되는가',
    'footer_toc4' => '왜 국제사회가 반대하는가',
    'footer_toc5' => '침묵의 증인',
    'footer_toc6' => '2016 PCA 판정',
    'footer_toc7' => '파라셀 제도 - 스프래틀리 제도',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — 남중국해에 대한 객관적 사실.<br>생태계: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => '좌표 없음',
];
