<?php

return [
    'nav_logo_name' => '남중국해 9단선',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => '남중국해 9단선',
    'nav_rail_aria' => '항목별 탐색',
    'nav_rail_what' => '정의',
    'nav_rail_origin' => '기원',
    'nav_rail_dispute' => '논쟁',
    'nav_rail_opposition' => '반대',
    'nav_rail_witnesses' => '고지도',
    'nav_rail_verdict' => '2016년 PCA',
    'nav_rail_sovereignty' => '파라셀 제도 - 스프래틀리 제도',
    'nav_sound_off' => '배경음 켜기',
    'nav_sound_on' => '배경음 끄기',
    'nav_share' => '공유',
    'dialog_title' => '표시 언어',
    'language' => '언어',
    'display_hint' => ':count개 언어',
    'search_placeholder' => '언어 검색…',
    'cancel' => '취소',
    'apply' => '적용',
    'sound_off' => '배경음 켜기',
    'sound_on' => '배경음 끄기',
    'lang_trigger' => '언어 선택',
    'close' => '닫기',
    'no_results' => '언어를 찾을 수 없음',
    'contribute' => '공유',
];
