<?php

return [
    'opposition_index' => '반대',
    'opposition_label' => '국제사회가 반대하는 이유',
    'opposition_title' => '반대는',
    'opposition_title_accent' => '감정이 아니라 법에 근거한다',
    'opposition_lead' => '2009년 남중국해 9단선이 유엔에 제출된 직후, 여러 국가와 학계는 구체적인 법적 근거를 들어 이에 반대했다.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5월',
    'opposition_voice1_title' => '베트남 · 말레이시아 · 인도네시아',
    'opposition_voice1_body' => '중국이 남중국해 9단선 지도를 유엔 사무총장에게 제출한 지 단 하루 뒤(2009년 5월 7일), 이들 국가는 잇따라 반대 공한을 보내며 해당 주장를 부인했다.',
    'opposition_voice1_chip1' => '반대 공한',
    'opposition_voice1_chip2' => '1982년 UNCLOS와 부합하지 않음',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => '필리핀',
    'opposition_voice2_body' => '유엔에 외교 서한을 보내 중국의 남중국해 주장가 "국제법상 근거가 없다"고 밝히며, 이후 중재재판소 제소의 전제가 되었다.',
    'opposition_voice2_chip1' => 'PCA 제소의 전제',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => '미국 국무부 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '분석은 다음을 지적했다: 지도마다 선의 위치가 일관되지 않음; 선이 중간선을 기준으로 하지 않고 육지를 침범함; 많은 지형물이 EEZ를 가질 수 있는 “섬”의 요건을 충족하지 못함.',
    'opposition_voice3_chip1' => '법적 요건 미충족',
    'opposition_voice3_chip2' => '공식 분석',
    'opposition_voice4_year' => '학계',
    'opposition_voice4_title' => '“역사적 수역” 개념은 시대에 뒤떨어졌다',
    'opposition_voice4_body' => '이 개념은 만이나 해안 가까운 연안 수역에만 적용되며 — 광대한 공해 전체를 포괄할 수는 없다. 2003년에는 대만조차 1993년에 제기했던 “역사적 수역” 정책을 부인했다.',
    'opposition_voice4_chip1' => '중국 학자들조차도 의견이 일치하지 않음',
];
