<?php

return [
    'sovereignty_index' => '파라셀 제도 - 스프래틀리 제도',
    'sovereignty_label' => '필연적 결론',
    'sovereignty_title' => '파라셀 제도 - 스프래틀리 제도',
    'sovereignty_title_accent' => '는 베트남의 것이다',
    'sovereignty_lead' => '이 페이지는 남중국해 9단선을 설명합니다. 결론 부분은 다음 질문에 답합니다: 파라셀 제도와 스프래틀리 제도 두 군도에 대한 주권은 누구에게 있는가? 역사적 관리와 국제법에 따르면, 일관된 답은 베트남입니다.',
    'sovereignty_thesis_label' => '종합 논점',
    'sovereignty_thesis_lock1' => '법적 좌표 없음',
    'sovereignty_thesis_lock2' => '2016년 PCA 기각',
    'sovereignty_thesis_lock3' => '고지도는 포괄하지 않음',
    'sovereignty_thesis_body' => '앞선 여섯 항목을 통해 세 가지가 분명해졌습니다: 남중국해 9단선은 손으로 그은 선일 뿐 법적 좌표가 없으며, 2016년 중재재판소는 그 주장을 기각했고, 중국 자체의 고지도는 남중국해를 포괄하지 않았습니다. 베트남의 주권은 구호가 아니라, 특히 응우옌 군주 시대부터 베트남 국가가 두 군도가 무주지였던 시기에 평화롭고 지속적으로 관리해 왔다는 사실에 근거합니다.',
    'sovereignty_spine_caption' => '지속적 관리의 이정표',
    'sovereignty_spine_title' => '끊기지 않은 하나의 시간선',
    'sovereignty_spine_range' => '17세기 → 현재',
    'sovereignty_chron1_year' => '17세기',
    'sovereignty_chron1_title' => '황사대',
    'sovereignty_chron1_body' => '응우옌 군주들은 황사대를 파견해 해역을 조사하고, 항로를 측량하며, 해상에서 자원을 채취하게 했습니다 — 이는 사실상의 관리권 행사였습니다.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => '자롱 황제',
    'sovereignty_chron2_body' => '파라셀 제도에 국기를 게양하여 당시 세계에 베트남의 주권을 확인했습니다.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => '민망 황제',
    'sovereignty_chron3_body' => '측량하고 비석을 세우며, 군도에 대한 기록을 조정의 공식 지도에 남겼습니다.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => '연속적 계승',
    'sovereignty_chron4_body' => '프랑스가 이를 인정하고 계속 관리했으며, 파라셀 제도를 투아티엔 성에 편입했습니다 — 이는 오늘날 베트남 국가의 기초가 되었습니다.',
    'sovereignty_chron5_year' => '현재',
    'sovereignty_chron5_title' => '법과 실천',
    'sovereignty_chron5_body' => '베트남은 UNCLOS, 외교, 보존 문서를 바탕으로 관리하고 있으며, 남중국해 9단선의 주장으로는 이 증거를 대체할 수 없습니다.',
    'sovereignty_balance_label' => '증거의 균형',
    'sovereignty_balance_medallion_title' => '양측 비교',
    'sovereignty_vn_tag' => '베트남 측',
    'sovereignty_vn_title' => '주권은 행위로 확립됨',
    'sovereignty_vn_body' => '무주지였던 시기에 실제로 점유한 뒤, 수세기에 걸쳐 공개적으로 관리했습니다 — 황제의 문서, 비석, 지도, 행정 기록이 남아 있습니다. 이러한 방식은 UNCLOS와 국제 관행에 부합합니다.',
    'sovereignty_dash_tag' => '남중국해 9단선 측',
    'sovereignty_dash_title' => '주장은 증거를 대신할 수 없음',
    'sovereignty_dash_body' => '1948년에 그어진 선은 좌표가 없고, 2016년 PCA에 의해 기각되었으며 UNCLOS에도 위배됩니다 — 이는 03항부터 06항까지에서 설명한 바와 같습니다. 그러므로 두 군도의 주권에 대한 결론은 남중국해 9단선에 의존할 수 없습니다.',
    'sovereignty_seal_quote' => '베트남은 <strong>평화적 수단</strong>으로, 특히 1982년 UNCLOS를 비롯한 국제법에 근거하여 분쟁을 해결하며, 남중국해가 평화롭고 협력적이며 발전하는 해역이 되기를 지향합니다.',
    'sovereignty_seal_cite' => '베트남의 입장 · 1982년 UNCLOS',
    'sovereignty_next_eyebrow' => '같은 생태계의 핵심 프로젝트',
    'sovereignty_next_title' => '파라셀 제도 - 스프래틀리 제도에 대한 증거를 모두 읽어보세요',
    'sovereignty_next_body' => '세부 기록 — 문서, 지도, 연표, 법적 논거 — 는 <strong>paracelislands.net</strong>에 있으며, 이곳에서 두 군도의 주권 주제를 종합적으로 제시합니다. 지금 보고 있는 이 페이지는 남중국해 9단선에서 그 결론으로 이어지는 논리를 연결합니다.',
    'sovereignty_next_cta' => 'paracelislands.net 열기',
];
