<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '국제 판정',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => '세 가지 "아니오"',
    'verdict_lead' => '2016년 7월 12일, 헤이그의 상설중재재판소(PCA)는 UNCLOS 부속서 VII에 따라, 필리핀이 중국을 상대로 제기한 사건에서 남중국해 9단선 주장을 기각하는 판정을 내렸다. <em>각 카드를 클릭해 원문을 읽어보세요.</em>',
    'verdict_card1_khong' => '아니오',
    'verdict_card1_title' => '역사적 권리',
    'verdict_card1_short' => '남중국해 9단선 안에 있는 해역의 자원에 대해 중국이 역사적 권리를 주장할 법적 근거는 없다.',
    'verdict_card1_quote' => '“중국이 남중국해 9단선 안의 해역에 있는 자원에 대해 역사적 권리를 주장할 법적 근거는 없다.”',
    'verdict_card1_more' => '+ 판정 읽기',
    'verdict_card2_khong' => '아니오',
    'verdict_card2_title' => 'EEZ를 형성하는 실체',
    'verdict_card2_short' => '스프래틀리 제도의 어느 실체도 중국을 위한 배타적 경제수역을 형성할 자격이 없으며, 바빙섬도 예외가 아니다.',
    'verdict_card2_quote' => '“스프래틀리 제도의 어떤 실체도 배타적 경제수역을 형성할 능력이 없다.”',
    'verdict_card2_more' => '+ 판정 읽기',
    'verdict_card3_khong' => '아니오',
    'verdict_card3_title' => '합법적 행위',
    'verdict_card3_short' => '중국은 필리핀의 주권적 권리를 침해하고, 어로를 방해하며, 해양 환경에 피해를 주었다.',
    'verdict_card3_quote' => '“중국은 필리핀의 주권적 권리를 침해하고, 스카버러 암초에서의 어업 활동에 개입했으며, 산호초 환경에 심각한 피해를 주었다.”',
    'verdict_card3_more' => '+ 판정 읽기',
    'verdict_extra1' => '중국이 자의적으로 그은 남중국해 9단선은 1982년 UNCLOS와 <strong>양립하지 않는다</strong>.',
    'verdict_extra2' => '중국은 과도한 채굴과 인공섬 건설을 통해 스프래틀리 제도의 생태계를 훼손했다.',
    'verdict_extra3' => '중국의 행동은 필리핀과의 충돌 위험을 높였다.',
    'verdict_extra4' => '바빙섬(대만이 통제)은 역시 EEZ를 형성할 수 없다.',
    'verdict_subtitle' => '왜 이것이 UNCLOS와 충돌하는가?',
    'verdict_subtitle_body' => '1982년 UNCLOS는 연안국의 기선을 기준으로 해역을 명확히 구분한다. 남중국해 9단선 주장은 이 틀을 벗어나므로 양립할 수 없다.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '영해 (해리)',
    'verdict_zone1_body' => '기선으로부터 측정되는 국가의 주권 해역.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '배타적 경제수역',
    'verdict_zone2_body' => 'EEZ — 연안국은 이 범위 내 자원에 대해 주권적 권리를 가진다.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '대륙붕 (최대, 해리)',
    'verdict_zone3_body' => '해저 자원에 대한 권리로, 확정된 지질학적 조건에 따른다.',
    'verdict_foot' => '이러한 틀에서, “역사적 권리”가 공해 전체를 포괄한다는 주장 — 남중국해 9단선이 암시하듯 — 는 <em>이미 UNCLOS의 법적 체계로 대체되었으며</em>, 중국 자신도 그 당사국이다.',
];
