<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '국제 판정',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => '세 개의 “아니오”',
    'verdict_lead' => '2016년 7월 12일, 헤이그의 상설중재재판소(PCA)는 — UNCLOS 부속서 VII에 따라 구성되어, 필리핀이 중국을 상대로 제기한 사건에서 — 남중국해 9단선 주장을 기각하는 판정을 내렸다. <em>각 카드에 클릭하면 원문을 읽을 수 있습니다.</em>',
    'verdict_card1_khong' => '아니오',
    'verdict_card1_title' => '역사적 권리',
    'verdict_card1_short' => '중국이 남중국해 9단선 안의 해역 자원에 대해 역사적 권리를 주장할 법적 근거는 없다.',
    'verdict_card1_quote' => '“중국이 남중국해 9단선 안의 해역에 있는 자원에 대해 역사적 권리를 주장할 법적 근거는 없다.”',
    'verdict_card1_more' => '+ 판정 읽기',
    'verdict_card2_khong' => '아니오',
    'verdict_card2_title' => 'EEZ를 형성하는 지형',
    'verdict_card2_short' => '스프래틀리 제도 내 어떤 지형도 중국을 위한 배타적경제수역을 형성할 자격이 없으며, 바빙 섬도 예외가 아니다.',
    'verdict_card2_quote' => '“스프래틀리 제도 내 어떤 지형도 배타적경제수역을 형성할 수 없다.”',
    'verdict_card2_more' => '+ 판정 읽기',
    'verdict_card3_khong' => '아니오',
    'verdict_card3_title' => '합법적 행위',
    'verdict_card3_short' => '중국은 필리핀의 주권적 권리를 침해하고, 어업을 방해하며, 해양 환경에 피해를 주었다.',
    'verdict_card3_quote' => '“중국은 필리핀의 주권적 권리를 침해하고, 스카버러 암초에서의 어업 활동에 간섭했으며, 산호초 환경에 중대한 피해를 주었다.”',
    'verdict_card3_more' => '+ 판정 읽기',
    'verdict_extra1' => '중국이 자의적으로 그린 남중국해 9단선은 1982년 UNCLOS와 <strong>부합하지 않는다</strong>.',
    'verdict_extra2' => '중국은 과도한 개발과 인공섬 건설을 통해 스프래틀리 제도의 생태계를 훼손했다.',
    'verdict_extra3' => '중국의 행위는 필리핀과의 충돌 위험을 높였다.',
    'verdict_extra4' => '바빙 섬(대만이 통제)은 또한 EEZ를 형성할 수 없다.',
    'verdict_subtitle' => '왜 이것이 UNCLOS와 충돌하는가?',
    'verdict_subtitle_body' => '1982년 UNCLOS는 연안국의 기선에 따라 해양 구역을 명확히 구분한다. 남중국해 9단선 주장은 이 틀을 벗어나므로, 양립할 수 없다.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '영해(해리)',
    'verdict_zone1_body' => '기선부터 측정되는 국가의 주권 해역.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '배타적경제수역',
    'verdict_zone2_body' => 'EEZ — 연안국은 이 범위 내 자원에 대해 주권적 권리를 가진다.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '대륙붕(최대, 해리)',
    'verdict_zone3_body' => '해저 자원에 대한 권리로, 지질학적 조건에 따라 정해진다.',
    'verdict_foot' => '이 틀 안에서, “역사적 권리”가 — 남중국해 9단선이 암시하듯 — 광대한 공해를 포괄한다는 주장은 <em>대체되었다</em>. 바로 UNCLOS의 법적 체제에 의해, 그리고 중국 역시 그 당사국이다.',
];
