<?php

return [
    'witnesses_index' => '고지도',
    'witnesses_label' => '중국 고지도',
    'witnesses_title' => '극남은 오직',
    'witnesses_title_accent' => '하이난섬까지',
    'witnesses_lead' => '중국인이 그린 고지도들은 시간순으로 살펴보면 모두 <em>하이난섬이 중국의 극남</em>임을 보여 주며, 파라셀 제도나 스프래틀리 제도는 포함되어 있지 않습니다. 자료는 <em>두 군도 파라셀 제도와 스프래틀리 제도에서의 베트남 국가 주권</em>(Trương Minh Dục, 2015)을 종합한 것입니다.',
    'witnesses_hint' => '⌖ 확대경으로 보기',
    'witnesses_map1_svg_hainan' => '하이난 海南',
    'witnesses_map1_svg_south' => '— 영토의 최남단 —',
    'witnesses_map1_svg_era' => '송나라 · 1136',
    'witnesses_map1_title' => '송나라 지도, 1136년',
    'witnesses_map1_body' => '중국의 영토는 하이난섬에서 끝나며 — 파라셀 제도와 스프래틀리 제도는 영토 밖에 있었습니다.',
    'witnesses_map2_svg_hainan' => '하이난',
    'witnesses_map2_svg_south' => 'd\'Anville의 경계',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville 지도, 1735년',
    'witnesses_map2_body' => 'J.-B. B. d\'Anville이 제작했으며, 1740년 사본은 독일 총리가 중국 지도자에게 증정한 바 있습니다. 청나라의 영토는 하이난에서 끝났습니다.',
    'witnesses_map3_svg_hainan' => '海南 하이난',
    'witnesses_map3_svg_south' => '"중국의 최남단"',
    'witnesses_map3_svg_era' => '황조직성도 · 1904',
    'witnesses_map3_title' => '황조직성도지리전도',
    'witnesses_map3_body' => '청나라가 인쇄한 지도 — 중국 영토의 최남단이 하이난섬임을 분명히 표시하고 있습니다.',
    'witnesses_quote' => '중국이 직접 공표한 지도에도 파라셀 제도 — 스프래틀리 제도는 자국 영토로 표시되어 있지 않았습니다.',
    'witnesses_timeline_aria' => '중국 고지도 연대표',
    'witnesses_year_aria' => '연대',
    'lightbox_aria' => '확대 이미지 보기',
    'lightbox_close' => '닫기',
    'lightbox_prev' => '이전 이미지',
    'lightbox_next' => '다음 이미지',
];
