<?php

return [
    'footer_index' => 'Könyvtár',
    'footer_crest_eyebrow' => 'A könyvtár igazságának zárása',
    'footer_crest_quote' => '„A Dél-kínai-tengeri béke a <b>nemzetközi jog</b> alapjaira épül.”',
    'footer_crest_sub' => 'Nincs gyűlölet · Csak az igazság',
    'footer_nav_aria' => 'Lábléc műveletei',
    'footer_btn_top' => 'Vissza a tetejére',
    'footer_btn_verdict' => 'A PCA 2016-os ítélete',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'A Kilenc vonásos vonal igényei',
    'footer_brand_eyebrow' => 'Tematikus oldal · Vietnam szuverenitása',
    'footer_brand_body' => 'A Kilenc vonásos vonal magyarázata objektív tények, a nemzetközi jog, a PCA 2016-os ítélete és történelmi források alapján — kiegészítve a két szigetcsoport, a <strong>"Hoàng Sa és Trường Sa"</strong> szuverenitásáról szóló részletes oldalakat. Kína alaptalan igényeinek cáfolata történelemmel és bizonyítékokkal.',
    'footer_refs_title' => 'Források',
    'footer_ref1' => 'A PCA ítélete, 2016.07.12.',
    'footer_ref2' => 'UNCLOS 1982 — teljes szöveg',
    'footer_ref3' => 'A tengerek határai №143 (US DoS)',
    'footer_ref4' => 'Történelmi források és régi térképek',
    'footer_toc_title' => 'Oldal tartalomjegyzéke',
    'footer_toc1' => 'Mi a Kilenc vonásos vonal',
    'footer_toc2' => 'Eredet',
    'footer_toc3' => 'Miért vitatott',
    'footer_toc4' => 'Miért ellenzi a nemzetközi közösség',
    'footer_toc5' => 'Csendes tanúk',
    'footer_toc6' => 'A PCA 2016-os ítélete',
    'footer_toc7' => 'Paracel-szigetek – Spratly-szigetek',
    'footer_copy_eyebrow' => 'Nonprofit projekt',
    'footer_copy_title' => 'Paracel-szigetek – Spratly-szigetek Vietnamé',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematikus oldal a Kilenc vonásos vonalról Vietnam szuverenitási ökoszisztémájában.',
    'footer_copy_body' => 'A Kilenc vonásos vonal igényének magyarázata <strong>objektív tények</strong>, <strong>nemzetközi jog</strong>, a PCA 2016-os ítélete és történelmi források alapján — kiegészítve a Paracel-szigetek és a Spratly-szigetek szuverenitásáról szóló részletes oldalakat.',
    'footer_copy_ecosystem_aria' => 'A projekt további oldalai',
    'footer_copy_ecosystem_label' => 'Ugyanazon ökoszisztéma',
    'footer_copy_disclaimer' => 'A tartalom oktatási és szemléletformáló célokat szolgál; nem helyettesíti Vietnam állam hivatalos álláspontját.',
    'footer_copy' => '<strong>© :year Kilenc vonásos vonal</strong> — A <strong>Paracel-szigetek – Spratly-szigetek Vietnamé</strong> nonprofit projekt része, az alábbi rendszeren belül: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Oldal tartalmi kötelezettségvállalásai',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'A PCA 2016-os ítélete',
    'footer_chip3' => 'Történelmi bizonyítékok',
    'footer_chip4' => 'Régi térképek',
    'footer_chip5' => 'Objektív tények',
    'footer_chip6' => 'Dél-kínai-tengeri béke',
];
