<?php

return [
    'footer_index' => 'Könyvtár',
    'footer_crest_eyebrow' => 'Az igazság könyvtárának záróakkordja',
    'footer_crest_quote' => '„A Dél-kínai-tengeren a béke a <b>nemzetközi jog</b> alapjain nyugszik.”',
    'footer_crest_sub' => 'Nincs gyűlölet · Csak igazság',
    'footer_nav_aria' => 'Lábléc műveletek',
    'footer_btn_top' => 'Vissza az oldal tetejére',
    'footer_btn_verdict' => 'A PCA 2016-os döntése',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'A Kilenc vonásos vonal igénye',
    'footer_brand_eyebrow' => 'Tematikus oldal · Vietnam szuverenitása',
    'footer_brand_body' => 'A Kilenc vonásos vonal magyarázata tárgyilagos tények, a nemzetközi jog, a PCA 2016-os döntése és történelmi források alapján — kiegészítve a két szigetcsoportról, a <strong>"Paracel-szigetek és Spratly-szigetek"</strong>-ről szóló mélyebb oldalakat. Kína alaptalan követeléseinek cáfolata történelemmel és bizonyítékokkal.',
    'footer_refs_title' => 'Hivatkozási források',
    'footer_ref1' => 'A PCA döntése, 2016.07.12.',
    'footer_ref2' => 'UNCLOS 1982 — teljes szöveg',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Történelmi források és régi térképek',
    'footer_toc_title' => 'Oldal tartalomjegyzéke',
    'footer_toc1' => 'Mi a Kilenc vonásos vonal',
    'footer_toc2' => 'Eredet',
    'footer_toc3' => 'Miért vitatott',
    'footer_toc4' => 'Miért ellenzi a nemzetközi közösség',
    'footer_toc5' => 'Néma tanúk',
    'footer_toc6' => 'A PCA 2016-os döntése',
    'footer_toc7' => 'Paracel-szigetek – Spratly-szigetek',
    'footer_copy_eyebrow' => 'Nonprofit projekt',
    'footer_copy_title' => 'A Paracel-szigetek – Spratly-szigetek Vietnamhoz tartoznak',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematikus oldal a Kilenc vonásos vonalról Vietnam szuverenitási ökoszisztémájában.',
    'footer_copy_body' => 'A Kilenc vonásos vonal igényének magyarázata <strong>tárgyilagos tények</strong>, <strong>a nemzetközi jog</strong>, a PCA 2016-os döntése és történelmi források alapján — kiegészítve a Paracel-szigetek és a Spratly-szigetek szuverenitásáról szóló mélyebb oldalakat.',
    'footer_copy_ecosystem_aria' => 'Azonos projekt oldalai',
    'footer_copy_ecosystem_label' => 'Ugyanabban az ökoszisztémában',
    'footer_copy_disclaimer' => 'A tartalom oktatási és szemléletformáló célú; nem helyettesíti Vietnam állami hivatalos álláspontját.',
    'footer_copy' => '<strong>© :year Kilenc vonásos vonal</strong> — A <strong>Paracel-szigetek – Spratly-szigetek Vietnamhoz tartoznak</strong> nonprofit projekt része, az alábbi rendszerben: <a href="https://paracelislands.net/hu" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/hu" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/hu" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/hu" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/hu" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Az oldal tartalmi kötelezettségvállalásai',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'A PCA 2016-os döntése',
    'footer_chip3' => 'Történelmi bizonyítékok',
    'footer_chip4' => 'Régi térképek',
    'footer_chip5' => 'Tárgyilagos tények',
    'footer_chip6' => 'A Dél-kínai-tenger békéje',
];
