<?php

return [
    'footer_index' => 'Könyvtár',
    'footer_crest_eyebrow' => 'A könyvtár igazságának összefogása',
    'footer_crest_quote' => '„A Dél-kínai-tengeren a béke az <b>nemzetközi jog</b> alapjára épül.”',
    'footer_crest_sub' => 'Nincs gyűlölet · Csak az igazság',
    'footer_nav_aria' => 'Alsó menüsor műveletei',
    'footer_btn_top' => 'Vissza az oldal tetejére',
    'footer_btn_verdict' => 'A PCA 2016-os ítélete',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Kilenc vonásos vonal',
    'footer_brand_body' => 'Tényeken, a nemzetközi jogon és történelmi dokumentumokon alapuló magyarázó oldal — a Kilenc vonásos vonal igényét bizonyítékokkal, nem szlogenekkel utasítja el.',
    'footer_refs_title' => 'Hivatkozások',
    'footer_ref1' => 'PCA-ítélet, 2016.07.12.',
    'footer_ref2' => 'UNCLOS 1982 — teljes szöveg',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Történelmi anyagok és régi térképek',
    'footer_toc_title' => 'Oldal tartalomjegyzéke',
    'footer_toc1' => 'Mi a Kilenc vonásos vonal',
    'footer_toc2' => 'Eredete',
    'footer_toc3' => 'Miért vitatott',
    'footer_toc4' => 'Miért ellenzi a nemzetközi közösség',
    'footer_toc5' => 'A néma tanúk',
    'footer_toc6' => 'A PCA 2016-os ítélete',
    'footer_toc7' => 'Paracel-szigetek – Spratly-szigetek',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Tényeken alapuló objektivitás a Dél-kínai-tengerről.<br>Ökoszisztéma: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Nincs koordináta',
];
