<?php

return [
    'nav_logo_name' => 'Kilenc vonásos vonal',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Kilenc vonásos vonal',
    'nav_rail_aria' => 'Szakaszok szerinti navigáció',
    'nav_rail_what' => 'Meghatározás',
    'nav_rail_origin' => 'Eredet',
    'nav_rail_dispute' => 'Vita',
    'nav_rail_opposition' => 'Ellenzés',
    'nav_rail_witnesses' => 'Ősi térképek',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracel-szigetek – Spratly-szigetek',
    'nav_sound_off' => 'Háttérzene bekapcsolása',
    'nav_sound_on' => 'Háttérzene kikapcsolása',
    'nav_share' => 'Megosztás',
    'dialog_title' => 'Megjelenített nyelv',
    'language' => 'Nyelv',
    'display_hint' => ':count nyelv',
    'search_placeholder' => 'Nyelv keresése…',
    'cancel' => 'Mégse',
    'apply' => 'Alkalmaz',
    'sound_off' => 'Háttérhang bekapcsolása',
    'sound_on' => 'Háttérhang kikapcsolása',
    'lang_trigger' => 'Nyelv kiválasztása',
    'close' => 'Bezárás',
    'no_results' => 'Nem található nyelv',
    'contribute' => 'Megosztás',
];
