<?php

return [
    'opposition_index' => 'Ellenzék',
    'opposition_label' => 'Miért ellenzi a nemzetközi közösség',
    'opposition_title' => 'Az ellenzés alapja',
    'opposition_title_accent' => 'a jog, nem az érzelmek',
    'opposition_lead' => 'Közvetlenül azután, hogy a Kilenc vonásos vonalat 2009-ben benyújtották az Egyesült Nemzetekhez, számos ország és tudós ellenezte azt — konkrét jogi érvekre hivatkozva.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Május',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonézia',
    'opposition_voice1_body' => 'Mindössze egy nappal azután, hogy Kína benyújtotta a Kilenc vonásos vonal térképét az ENSZ főtitkárának (2009. 05. 07.), ezek az országok sorra tiltakozó jegyzékeket küldtek, elutasítva az igényt.',
    'opposition_voice1_chip1' => 'Tiltakozó jegyzék',
    'opposition_voice1_chip2' => 'Nem felel meg az 1982-es UNCLOS-nak',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Fülöp-szigetek',
    'opposition_voice2_body' => 'Diplomáciai levelet küldött az Egyesült Nemzeteknek, kijelentve, hogy Kína dél-kínai-tengeri igénye „nem rendelkezik a nemzetközi jog szerinti alappal” — ez később a választottbírósági eljárás előzményévé vált.',
    'opposition_voice2_chip1' => 'A PCA-eljárás előzménye',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Az Egyesült Államok Külügyminisztériuma — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Az elemzés rámutatott: a különböző évek térképei következetlenek a vonal helyzetét illetően; a vonal a szárazföldre nyúlik be ahelyett, hogy középvonalat követne; számos képződmény nem felel meg az „sziget” jogi feltételének ahhoz, hogy EEZ-t kapjon.',
    'opposition_voice3_chip1' => 'Nem teljesíti a jogi feltételeket',
    'opposition_voice3_chip2' => 'Hivatalos elemzés',
    'opposition_voice4_year' => 'Akadémiai',
    'opposition_voice4_title' => 'A „történelmi vizek” fogalma elavult',
    'opposition_voice4_body' => 'Ez a fogalom csak öblökre, partközeli öblöcskékre alkalmazható — nem terjedhet ki egy egész, hatalmas nyílt tengeri térségre. 2003-ban maga Tajvan is elutasította az 1993-ban említett „történelmi vizek” politikáját.',
    'opposition_voice4_chip1' => 'Még a kínai tudósok sem egységesek',
];
