<?php

return [
    'opposition_index' => 'Ellenzék',
    'opposition_label' => 'Miért ellenzik nemzetközileg',
    'opposition_title' => 'Az ellenzés alapja',
    'opposition_title_accent' => 'a jog, nem az érzelmek',
    'opposition_lead' => 'Röviddel azután, hogy a Kilenc vonásos vonalat 2009-ben benyújtották az ENSZ-hez, számos állam és tudós tiltakozott — konkrét jogi érvek alapján.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Május',
    'opposition_voice1_title' => 'Vietnam · Malajzia · Indonézia',
    'opposition_voice1_body' => 'Mindössze egy nappal azután, hogy Kína benyújtotta a Kilenc vonásos vonal térképét az ENSZ főtitkárának (2009. 5. 7.), ezek az országok sorra tiltakozó jegyzékeket küldtek, és elutasították az igényt.',
    'opposition_voice1_chip1' => 'Tiltakozó jegyzék',
    'opposition_voice1_chip2' => 'Nem felel meg az 1982-es UNCLOS-nak',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => 'Fülöp-szigetek',
    'opposition_voice2_body' => 'Diplomáciai levelet küldött az ENSZ-nek, és kijelentette, hogy Kína dél-kínai-tengeri igényei „nem rendelkeznek a nemzetközi jog szerinti alappal” — ez később a választottbírósági eljárás előzménye lett.',
    'opposition_voice2_chip1' => 'A PCA-eljárás előzménye',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '12/05',
    'opposition_voice3_title' => 'Az Egyesült Államok Külügyminisztériuma — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Az elemzés kimutatta: a különböző évek térképei ellentmondanak egymásnak a vonal helyzetét illetően; a vonal a szárazföld belsejébe nyúlik ahelyett, hogy a középvonalat követné; számos képződmény nem felel meg az „sziget” jogi feltételeinek ahhoz, hogy EEZ-t biztosítson.',
    'opposition_voice3_chip1' => 'Nem felel meg a jogi feltételeknek',
    'opposition_voice3_chip2' => 'Hivatalos elemzés',
    'opposition_voice4_year' => 'Akadémiai',
    'opposition_voice4_title' => 'A „történelmi vizek” fogalma elavult',
    'opposition_voice4_body' => 'Ez a fogalom csak öblökre és a part menti belső vizekre alkalmazható — nem terjedhet ki egy egész, nyílt tengeri térségre. 2003-ban Tajvan maga is elutasította az 1993-ban megfogalmazott „történelmi vizek” politikáját.',
    'opposition_voice4_chip1' => 'Még a kínai tudósok sem értenek egyet',
];
