<?php

return [
    'sovereignty_index' => 'Paracel-szigetek – Spratly-szigetek',
    'sovereignty_label' => 'Következtetés szükségszerűsége',
    'sovereignty_title' => 'Paracel-szigetek – Spratly-szigetek',
    'sovereignty_title_accent' => 'Vietnamhoz tartozik',
    'sovereignty_lead' => 'Ez az oldal a Kilenc vonásos vonalról ad magyarázatot. A záró rész a következő kérdésre válaszol: kié a Paracel-szigetek és a Spratly-szigetek feletti szuverenitás? A történelmi igazgatás és a nemzetközi jog alapján a következetes válasz Vietnam.',
    'sovereignty_thesis_label' => 'Összegzett állítás',
    'sovereignty_thesis_lock1' => 'Nincs jogi koordináta',
    'sovereignty_thesis_lock2' => 'A PCA 2016 elutasította',
    'sovereignty_thesis_lock3' => 'A régi térképek nem fedik le',
    'sovereignty_thesis_body' => 'Az előző hat pont után három dolog világos: a Kilenc vonásos vonal kézzel rajzolt, nincs jogi koordinátája; a 2016-os választottbíróság elutasította az igényt; Kína saját régi térképei sem fedik le a Dél-kínai-tengert. Vietnam szuverenitása nem jelszavakon alapul, hanem azon, hogy a vietnami állam — a Nguyễn-uralkodók ideje óta — békésen és folyamatosan igazgatta ezeket a területeket, amikor a két szigetcsoport még gazdátlan föld volt.',
    'sovereignty_spine_caption' => 'A folyamatos igazgatás mérföldkövei',
    'sovereignty_spine_title' => 'Egy megszakítás nélküli idővonal',
    'sovereignty_spine_range' => '17. század → napjainkig',
    'sovereignty_chron1_year' => '17. sz.',
    'sovereignty_chron1_title' => 'Hoàng Sa-csapat',
    'sovereignty_chron1_body' => 'A Nguyễn-uralkodók kiküldték a Hoàng Sa-csapatot a tengeri felmérésekre, útvonalak mérésére és a tengeri erőforrások kiaknázására — a tényleges igazgatás gyakorlására.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Gia Long király',
    'sovereignty_chron2_body' => 'Zászlót tűzött ki a Paracel-szigetekre, ezzel korának világa előtt megerősítve Vietnam szuverenitását.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Minh Mạng király',
    'sovereignty_chron3_body' => 'Felmérték, sztéléket állítottak, és a szigeteket a udvar hivatalos térképein is rögzítették.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Folytonos öröklődés',
    'sovereignty_chron4_body' => 'Franciaország elismerte és folytatta az igazgatást; a Paracel-szigeteket Thừa Thiên tartományhoz csatolta — ez lett a mai vietnami állam alapja.',
    'sovereignty_chron5_year' => 'Napjainkban',
    'sovereignty_chron5_title' => 'Jog és gyakorlat',
    'sovereignty_chron5_body' => 'Vietnam az UNCLOS, a diplomácia és a levéltári dokumentumok alapján igazgat; a Kilenc vonásos vonalra hivatkozó igény ezt a bizonyítékot nem írhatja felül.',
    'sovereignty_balance_label' => 'A bizonyítékok egyensúlya',
    'sovereignty_balance_medallion_title' => 'A két oldal összevetése',
    'sovereignty_vn_tag' => 'A vietnami oldal',
    'sovereignty_vn_title' => 'A szuverenitás cselekvéssel jött létre',
    'sovereignty_vn_body' => 'Valós birtokbavétel akkor, amikor a terület még gazdátlan volt, majd évszázadokon át nyilvános igazgatás — császári rendeletek, sztélék, térképek és közigazgatási iratok formájában. Ez a gyakorlat összhangban van az UNCLOS-szal és a nemzetközi gyakorlattal.',
    'sovereignty_dash_tag' => 'A Kilenc vonásos vonal oldala',
    'sovereignty_dash_title' => 'Az igény nem pótolja a bizonyítékot',
    'sovereignty_dash_body' => 'Egy 1948-ban rajzolt vonal, koordináták nélkül, amelyet a PCA 2016 elutasított, és amely ellentétes az UNCLOS-szal — ahogy a 03–06. részek bemutatták. Ezért a két szigetcsoport szuverenitásáról szóló következtetés nem alapozható a Kilenc vonásos vonalra.',
    'sovereignty_seal_quote' => 'Vietnam a vitákat <strong>békés eszközökkel</strong>, a nemzetközi jog — különösen az 1982-es UNCLOS — alapján kezeli, a Dél-kínai-tenger békéjét, együttműködését és fejlődését célozva.',
    'sovereignty_seal_cite' => 'Vietnam álláspontja · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Fő projekt ugyanabban az ökoszisztémában',
    'sovereignty_next_title' => 'Olvasd el teljes egészében a Paracel-szigetek – Spratly-szigetek bizonyítékait',
    'sovereignty_next_body' => 'A részletes dosszié — dokumentumok, térképek, idővonal és jogi érvek — a <strong>paracelislands.net</strong> oldalon található, amely átfogóan mutatja be a két szigetcsoport szuverenitásának témáját. Az általad olvasott oldal csak logikailag kapcsolja össze a Kilenc vonásos vonalat ezzel a következtetéssel.',
    'sovereignty_next_cta' => 'Nyisd meg a paracelislands.net-et',
];
