<?php

return [
    'sovereignty_index' => 'Paracel-szigetek – Spratly-szigetek',
    'sovereignty_label' => 'Elkerülhetetlen következtetés',
    'sovereignty_title' => 'Paracel-szigetek – Spratly-szigetek',
    'sovereignty_title_accent' => 'Vietnamhoz tartozik',
    'sovereignty_lead' => 'Ez az oldal a Kilenc vonásos vonalat magyarázza. A záró rész a következő kérdésre válaszol: ki rendelkezik szuverenitással a Paracel-szigetek és a Spratly-szigetek felett? A történeti igazgatás és a nemzetközi jog alapján a következetes válasz Vietnam.',
    'sovereignty_thesis_label' => 'Összegző tétel',
    'sovereignty_thesis_lock1' => 'Nincs jogi koordinátája',
    'sovereignty_thesis_lock2' => 'A PCA 2016 elutasította',
    'sovereignty_thesis_lock3' => 'Az ősi térképek nem fedik le',
    'sovereignty_thesis_body' => 'A fenti hat pont után három dolog világos: a Kilenc vonásos vonal kézzel rajzolt, nincs jogi koordinátája; a 2016-os választottbíróság elutasította az igényt; Kína saját régi térképei sem fedik le a Dél-kínai-tengert. Vietnam szuverenitása nem jelszavakon alapul, hanem azon, hogy a vietnami állam — a Nguyễn-uralkodók korától kezdve — békésen és folyamatosan igazgatta e két szigetcsopor t, amikor azok még senki földjei voltak.',
    'sovereignty_spine_caption' => 'Folyamatos igazgatási mérföldkövek',
    'sovereignty_spine_title' => 'Egy megszakítás nélküli idővonal',
    'sovereignty_spine_range' => '17. század → napjainkig',
    'sovereignty_chron1_year' => '17. sz.',
    'sovereignty_chron1_title' => 'Hoàng Sa egység',
    'sovereignty_chron1_body' => 'A Nguyễn-uralkodók a Hoàng Sa egységet küldték felmérésre, hajózási útvonalak mérésére és tengeri hasznosításra — a tényleges állami igazgatás gyakorlására.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Gia Long király',
    'sovereignty_chron2_body' => 'Zászlót tűzött ki a Paracel-szigetekre, és ezzel kora világával szemben megerősítette Vietnam szuverenitását.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Minh Mạng király',
    'sovereignty_chron3_body' => 'Felmérések, emlékkövek felállítása és a szigetek hivatalos udvari térképeken való rögzítése.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Folytonos jogutódlás',
    'sovereignty_chron4_body' => 'Franciaország elismerte és folytatta az igazgatást; Hoàng Sa-t beolvasztotta Thừa Thiên tartományba — ez lett a mai vietnami állam alapja.',
    'sovereignty_chron5_year' => 'Napjainkban',
    'sovereignty_chron5_title' => 'Jog és gyakorlat',
    'sovereignty_chron5_body' => 'Vietnam az UNCLOS, a diplomácia és az irattári bizonyítékok alapján igazgat; a Kilenc vonásos vonal igényei ezt nem helyettesíthetik.',
    'sovereignty_balance_label' => 'Bizonyítékok egyensúlya',
    'sovereignty_balance_medallion_title' => 'A két oldal összevetése',
    'sovereignty_vn_tag' => 'Vietnam oldala',
    'sovereignty_vn_title' => 'A szuverenitás cselekedetekkel jött létre',
    'sovereignty_vn_body' => 'Valódi birtokbavétel akkor, amikor a föld még senkié volt, majd évszázadokon át tartó nyilvános igazgatás — császári iratokkal, sztélékkel, térképekkel és közigazgatási dokumentumokkal. Ez összhangban van az UNCLOS-szal és a nemzetközi gyakorlattal.',
    'sovereignty_dash_tag' => 'A Kilenc vonásos vonal oldala',
    'sovereignty_dash_title' => 'Az igény nem pótolja a bizonyítékot',
    'sovereignty_dash_body' => 'Egy 1948-ban rajzolt vonal, koordináták nélkül, amelyet a PCA 2016 elutasított, és amely ellentétes az UNCLOS-szal — ahogyan a 03–06. pontok bemutatták. Ezért a két szigetcsoportra vonatkozó szuverenitási következtetés nem alapulhat a Kilenc vonásos vonalon.',
    'sovereignty_seal_quote' => 'Vietnam a vitákat <strong>békés eszközökkel</strong>, a nemzetközi jog — különösen az 1982-es UNCLOS — alapján rendezi, a Dél-kínai-tenger békéje, együttműködése és fejlődése érdekében.',
    'sovereignty_seal_cite' => 'Vietnam álláspontja · 1982-es UNCLOS',
    'sovereignty_next_eyebrow' => 'A közös ökoszisztéma fő projektje',
    'sovereignty_next_title' => 'Olvasd el a teljes bizonyítékanyagot a Paracel-szigetek – Spratly-szigetek ügyében',
    'sovereignty_next_body' => 'A részletes dosszié — dokumentumok, térképek, idővonal és jogi érvek — a <strong>paracelislands.net</strong> oldalon található, amely átfogóan mutatja be e két szigetcsoportra vonatkozó szuverenitási kérdést. Az általad olvasott oldal csak logikai kapcsolatot teremt a Kilenc vonásos vonaltól ehhez a következtetéshez.',
    'sovereignty_next_cta' => 'A paracelislands.net megnyitása',
];
