<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Nemzetközi ítélet',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'a három „Nem”',
    'verdict_lead' => '2016. 7. 12-én a hágai Állandó Választottbíróság (PCA) — az UNCLOS VII. melléklete alapján létrehozva, a Fülöp-szigetek Kína elleni ügyében — meghozta ítéletét, amely elutasította a Kilenc vonásos vonalra vonatkozó igényt. <em>Kattintson az egyes kártyákra az eredeti szöveg elolvasásához.</em>',
    'verdict_card1_khong' => 'NEM',
    'verdict_card1_title' => 'történeti jog',
    'verdict_card1_short' => 'Nincs jogalap arra, hogy Kína történeti jogot állítson a Kilenc vonásos vonalon belüli tengeri térség erőforrásaira.',
    'verdict_card1_quote' => '„Nincs jogalap arra, hogy Kína történeti jogot állítson a Kilenc vonásos vonalon belüli tengeri térség erőforrásaira.”',
    'verdict_card1_more' => '+ Az ítélet olvasása',
    'verdict_card2_khong' => 'NEM',
    'verdict_card2_title' => 'EEZ-t létrehozó képződmény',
    'verdict_card2_short' => 'A Spratly-szigetek egyik képződménye sem alkalmas arra, hogy Kína számára kizárólagos gazdasági övezetet hozzon létre — beleértve Ba Binh-szigetet is.',
    'verdict_card2_quote' => '„A Spratly-szigetek egyik képződménye sem képes kizárólagos gazdasági övezetet létrehozni.”',
    'verdict_card2_more' => '+ Az ítélet olvasása',
    'verdict_card3_khong' => 'NEM',
    'verdict_card3_title' => 'jogszerű magatartás',
    'verdict_card3_short' => 'Kína megsértette a Fülöp-szigetek szuverén jogait, akadályozta a halászatot, és károsította a tengeri környezetet.',
    'verdict_card3_quote' => '„Kína megsértette a Fülöp-szigetek szuverén jogait, beavatkozott a Scarborough-zátonynál folyó halászati tevékenységbe, és súlyos kárt okozott a korallzátonyok környezetében.”',
    'verdict_card3_more' => '+ Az ítélet olvasása',
    'verdict_extra1' => 'A Kína által saját maga által meghúzott Kilenc vonásos vonal <strong>nem felel meg</strong> az 1982-es UNCLOS-nak.',
    'verdict_extra2' => 'Kína túlzott kitermeléssel és mesterséges szigetek építésével kárt okoz a Spratly-szigetek ökoszisztémájában.',
    'verdict_extra3' => 'Kína lépései növelik a Fülöp-szigetekkel való konfliktus kockázatát.',
    'verdict_extra4' => 'Ba Bình-sziget (amelyet Tajvan ellenőriz) szintén nem képes EEZ-t létrehozni.',
    'verdict_subtitle' => 'Miért ütközik ez az UNCLOS-szal?',
    'verdict_subtitle_body' => 'Az 1982-es UNCLOS egyértelműen a parti állam alapvonalai alapján határozza meg a tengeri övezeteket. A Kilenc vonásos vonalra vonatkozó igény túllép ezen a kereten, ezért nem egyeztethető össze vele.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Területi tenger (mérföld)',
    'verdict_zone1_body' => 'Az állam szuverenitása alá tartozó tengeri övezet, az alapvonaltól mérve.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Kizárólagos gazdasági övezet',
    'verdict_zone2_body' => 'EEZ — a parti államnak ebben a zónában szuverén joga van az erőforrásokhoz.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentális talapzat (legfeljebb, mérföld)',
    'verdict_zone3_body' => 'Jogok a tengerfenék erőforrásaihoz, meghatározott geológiai feltételek szerint.',
    'verdict_foot' => 'Ebben a keretben a „történeti jog” egy teljes nyílt tengeri térségre terjedne ki — ahogyan azt a Kilenc vonásos vonal sugallja — <em>ezt azonban felváltotta</em> az UNCLOS jogi rezsimje, amelynek Kína maga is részes állama.',
];
