<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Nemzetközi ítélet',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'három „nem”',
    'verdict_lead' => '2016. 7. 12-én a Hágában működő Állandó Választottbíróság (PCA) — az UNCLOS VII. melléklete alapján létrehozva, a Fülöp-szigetek Kína elleni ügyében — olyan ítéletet hozott, amely elutasította a Kilenc vonásos vonalra vonatkozó igényt. <em>Kattintson minden kártyára az eredeti szöveg elolvasásához.</em>',
    'verdict_card1_khong' => 'NEM',
    'verdict_card1_title' => 'történelmi jog',
    'verdict_card1_short' => 'Nincs jogalapja annak, hogy Kína történelmi jogot állítson a Kilenc vonásos vonalon belüli vizek erőforrásaira.',
    'verdict_card1_quote' => '„Nincs jogalapja annak, hogy Kína történelmi jogot állítson a Kilenc vonásos vonalon belüli vizekben található erőforrásokra.”',
    'verdict_card1_more' => '+ Az ítélet elolvasása',
    'verdict_card2_khong' => 'NEM',
    'verdict_card2_title' => 'EEZ-t létrehozó képződmény',
    'verdict_card2_short' => 'A Spratly-szigetek egyik képződménye sem felel meg a feltételeknek ahhoz, hogy Kína számára kizárólagos gazdasági övezetet hozzon létre — még Ba Bình szigete sem.',
    'verdict_card2_quote' => '„A Spratly-szigetek egyetlen képződménye sem képes kizárólagos gazdasági övezetet létrehozni.”',
    'verdict_card2_more' => '+ Az ítélet elolvasása',
    'verdict_card3_khong' => 'NEM',
    'verdict_card3_title' => 'jogszerű magatartás',
    'verdict_card3_short' => 'Kína megsértette a Fülöp-szigetek szuverén jogait, akadályozta a halászatot és károsította a tengeri környezetet.',
    'verdict_card3_quote' => '„Kína megsértette a Fülöp-szigetek szuverén jogait, beavatkozott a Scarborough-zátonynál folyó halászati tevékenységbe, és súlyos kárt okozott a korallzátonyok környezetében.”',
    'verdict_card3_more' => '+ Az ítélet elolvasása',
    'verdict_extra1' => 'A Kína által egyoldalúan megrajzolt Kilenc vonásos vonal <strong>nem egyeztethető össze</strong> az 1982-es UNCLOS-szal.',
    'verdict_extra2' => 'Kína a túlhorgászással és mesterséges szigetek építésével károsította a Spratly-szigetek ökoszisztémáját.',
    'verdict_extra3' => 'Kína lépései növelik a Fülöp-szigetekkel fennálló konfliktus kockázatát.',
    'verdict_extra4' => 'Ba Bình szigete (amelyet Tajvan ellenőriz) sem képes EEZ-t létrehozni.',
    'verdict_subtitle' => 'Miért ütközik ez az UNCLOS-szal?',
    'verdict_subtitle_body' => 'Az 1982-es UNCLOS egyértelműen meghatározza a tengeri övezeteket a parti állam alapvonalai alapján. A Kilenc vonásos vonalra vonatkozó igény túlnyúlik ezen a kereten, ezért nem egyeztethető össze vele.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Területi tenger (tengeri mérföld)',
    'verdict_zone1_body' => 'A partvonaltól számított, az állam szuverenitása alá tartozó tengeri övezet.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Kizárólagos gazdasági övezet',
    'verdict_zone2_body' => 'EEZ — a parti államnak ebben a sávban szuverén joga van az erőforrásokhoz.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentális talapzat (legfeljebb, tengeri mérföld)',
    'verdict_zone3_body' => 'A tengerfenék erőforrásaihoz fűződő jogok, a meghatározott földtani feltételek szerint.',
    'verdict_foot' => 'Ebben a keretben a „történelmi jog”, amely egy teljes nyílt tengeri térségre terjedne ki — ahogyan azt a Kilenc vonásos vonal sugallja — <em>felváltásra került</em> az UNCLOS jogi rendszerével, amelynek Kína maga is részes állama.',
];
