<?php

return [
    'witnesses_index' => 'Ősi térképek',
    'witnesses_label' => 'Kínai ősi térképek',
    'witnesses_title' => 'A legdélibb pont csak eddig ér',
    'witnesses_title_accent' => 'Hainan-sziget',
    'witnesses_lead' => 'A kínai szerzők által készített, időrendbe rendezett ősi térképek mind azt mutatják, hogy <em>Hainan-sziget volt Kína legdélibb pontja</em>, Hoàng Sa vagy Trường Sa nélkül. Az anyag összefoglalása a <em>Vietnam állami szuverenitása a Hoàng Sa- és Trường Sa-szigetcsoportok felett</em> című mű alapján készült (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Nagyítóval vizsgálni',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— a terület legdélibb pontja —',
    'witnesses_map1_svg_era' => 'Song-dinasztia · 1136',
    'witnesses_map1_title' => 'A Song-dinasztia térképe, 1136',
    'witnesses_map1_body' => 'Kína területe Hainan szigeténél véget ér — a Paracel-szigetek és a Spratly-szigetek a határain kívül vannak.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anville határa',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville térképe, 1735',
    'witnesses_map2_body' => 'J.-B. B. d\'Anville készítette; egy 1740-es másolatot a német kancellár ajándékozott a kínai vezetésnek. A Csing-dinasztia területe Hainannál ért véget.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"Kína legdélibb pontja"',
    'witnesses_map3_svg_era' => 'Konghvang cseng-tu csih-tuj · 1904',
    'witnesses_map3_title' => 'A Konghvang cseng-tu csih-tuj teljes földrajzi térképe',
    'witnesses_map3_body' => 'A Csing-dinasztia adta ki — világosan jelzi, hogy Kína területének legdélibb pontja Hainan szigete.',
    'witnesses_quote' => 'Maguk a korábban Kína által közzétett térképek sem ábrázolták a Hoàng Sa — Trường Sa-szigeteket az ő területükként.',
    'witnesses_timeline_aria' => 'A kínai ősi térképek idővonala',
    'witnesses_year_aria' => 'Keltezés',
    'lightbox_aria' => 'Nagyított kép megtekintése',
    'lightbox_close' => 'Bezárás',
    'lightbox_prev' => 'Előző kép',
    'lightbox_next' => 'Következő kép',
];
