<?php

return [
    'footer_index' => 'Thư viện',
    'footer_crest_eyebrow' => 'Kết thư viện sự thật',
    'footer_crest_quote' => '“Hòa bình ở Biển Đông được xây trên nền tảng của <b>Luật pháp quốc tế</b>.”',
    'footer_crest_sub' => 'Không thù ghét · Chỉ có sự thật',
    'footer_nav_aria' => 'Hành động cuối trang',
    'footer_btn_top' => 'Về đầu trang',
    'footer_btn_verdict' => 'Phán quyết PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Yêu Sách Đường Lưỡi Bò',
    'footer_brand_eyebrow' => 'Trang chuyên đề · Chủ quyền Việt Nam',
    'footer_brand_body' => 'Giải thích về Đường Lưỡi Bò qua sự thật khách quan, luật pháp quốc tế, phán quyết PCA 2016 và tư liệu lịch sử — bổ sung cho các trang chuyên sâu về chủ quyền hai quần đảo <strong>"Hoàng Sa và Trường Sa"</strong>. Phủ định yêu sách vô lí của Trung Quốc bằng lịch sử và bằng chứng.',
    'footer_refs_title' => 'Nguồn tham khảo',
    'footer_ref1' => 'Phán quyết PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — toàn văn',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tư liệu lịch sử & bản đồ cổ',
    'footer_toc_title' => 'Mục lục trang',
    'footer_toc1' => 'Đường Lưỡi Bò là gì',
    'footer_toc2' => 'Nguồn gốc',
    'footer_toc3' => 'Vì sao gây tranh cãi',
    'footer_toc4' => 'Vì sao quốc tế phản đối',
    'footer_toc5' => 'Nhân chứng thầm lặng',
    'footer_toc6' => 'Phán quyết PCA 2016',
    'footer_toc7' => 'Hoàng Sa – Trường Sa',
    'footer_copy_eyebrow' => 'Dự án phi lợi nhuận',
    'footer_copy_title' => 'Hoàng Sa – Trường Sa là của Việt Nam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Trang chuyên đề về Đường Lưỡi Bò trong hệ sinh thái chủ quyền của Việt Nam.',
    'footer_copy_body' => 'Giải thích yêu sách Đường Lưỡi Bò qua <strong>sự thật khách quan</strong>, <strong>luật pháp quốc tế</strong>, phán quyết PCA 2016 và tư liệu lịch sử — bổ sung cho các trang chuyên sâu về chủ quyền hai quần đảo Hoàng Sa và Trường Sa.',
    'footer_copy_ecosystem_aria' => 'Các trang cùng dự án',
    'footer_copy_ecosystem_label' => 'Cùng hệ sinh thái',
    'footer_copy_disclaimer' => 'Nội dung nhằm giáo dục và nâng cao nhận thức; không thay thế quan điểm chính thức của Nhà nước Việt Nam.',
    'footer_copy' => '<strong>© :year Đường Lưỡi Bò</strong> — Một phần dự án phi lợi nhuận <strong>Hoàng Sa – Trường Sa là của Việt Nam</strong> thuộc hệ thống: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Cam kết nội dung trang',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Phán quyết PCA 2016',
    'footer_chip3' => 'Bằng chứng lịch sử',
    'footer_chip4' => 'Bản đồ cổ',
    'footer_chip5' => 'Sự thật khách quan',
    'footer_chip6' => 'Hòa bình Biển Đông',
];
