<?php

return [
    'footer_index' => 'Thư viện',
    'footer_crest_eyebrow' => 'Kết thư viện sự thật',
    'footer_crest_quote' => '“Hòa bình ở Biển Đông được xây trên nền tảng của <b>Luật pháp quốc tế</b>.”',
    'footer_crest_sub' => 'Không thù ghét · Chỉ có sự thật',
    'footer_nav_aria' => 'Hành động cuối trang',
    'footer_btn_top' => 'Về đầu trang',
    'footer_btn_verdict' => 'Phán quyết PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Đường Lưỡi Bò',
    'footer_brand_body' => 'Một trang giải thích dựa trên sự thật khách quan, luật pháp quốc tế và tài liệu lịch sử — phủ định yêu sách Đường Lưỡi Bò bằng bằng chứng, không bằng khẩu hiệu.',
    'footer_refs_title' => 'Nguồn tham khảo',
    'footer_ref1' => 'Phán quyết PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — toàn văn',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Tư liệu lịch sử & bản đồ cổ',
    'footer_toc_title' => 'Mục lục trang',
    'footer_toc1' => 'Đường Lưỡi Bò là gì',
    'footer_toc2' => 'Nguồn gốc',
    'footer_toc3' => 'Vì sao gây tranh cãi',
    'footer_toc4' => 'Vì sao quốc tế phản đối',
    'footer_toc5' => 'Nhân chứng thầm lặng',
    'footer_toc6' => 'Phán quyết PCA 2016',
    'footer_toc7' => 'Hoàng Sa – Trường Sa',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Sự thật khách quan về Biển Đông.<br>Hệ sinh thái: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Không tọa độ',
];
