<?php

return [
    'nav_logo_name' => 'Đường Lưỡi Bò',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Đường Lưỡi Bò',
    'nav_rail_aria' => 'Điều hướng theo mục',
    'nav_rail_what' => 'Định nghĩa',
    'nav_rail_origin' => 'Nguồn gốc',
    'nav_rail_dispute' => 'Tranh cãi',
    'nav_rail_opposition' => 'Phản đối',
    'nav_rail_witnesses' => 'Bản đồ cổ',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Hoàng Sa – Trường Sa',
    'nav_sound_off' => 'Bật nhạc nền',
    'nav_sound_on' => 'Tắt nhạc nền',
    'nav_share' => 'Chia sẻ',
    'dialog_title' => 'Ngôn ngữ hiển thị',
    'language' => 'Ngôn ngữ',
    'display_hint' => ':count ngôn ngữ',
    'search_placeholder' => 'Tìm ngôn ngữ…',
    'cancel' => 'Hủy',
    'apply' => 'Áp dụng',
    'sound_off' => 'Bật âm thanh nền',
    'sound_on' => 'Tắt âm thanh nền',
    'lang_trigger' => 'Chọn ngôn ngữ',
    'close' => 'Đóng',
    'no_results' => 'Không tìm thấy ngôn ngữ',
    'contribute' => 'Chia sẻ',
];
