<?php

return [
    'opposition_index' => 'Phản đối',
    'opposition_label' => 'Vì sao quốc tế phản đối',
    'opposition_title' => 'Phản đối dựa trên',
    'opposition_title_accent' => 'luật, không phải cảm xúc',
    'opposition_lead' => 'Ngay sau khi Đường Lưỡi Bò được trình lên Liên Hợp Quốc năm 2009, nhiều quốc gia và giới học giả đã phản đối — bằng các lập luận pháp lý cụ thể.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Tháng 5',
    'opposition_voice1_title' => 'Việt Nam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Chỉ một ngày sau khi Trung Quốc trình bản đồ Đường Lưỡi Bò lên Tổng Thư ký Liên Hợp Quốc (7/5/2009), các nước này lần lượt gửi công hàm phản đối, bác bỏ yêu sách.',
    'opposition_voice1_chip1' => 'Công hàm phản đối',
    'opposition_voice1_chip2' => 'Không phù hợp UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippines',
    'opposition_voice2_body' => 'Gửi thư ngoại giao lên Liên Hợp Quốc, tuyên bố yêu sách của Trung Quốc ở Biển Đông là “không có căn cứ theo luật quốc tế” — tiền đề cho vụ kiện ra Tòa Trọng tài sau đó.',
    'opposition_voice2_chip1' => 'Tiền đề vụ kiện PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Bộ Ngoại giao Hoa Kỳ — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Phân tích chỉ ra: bản đồ các năm bất nhất về vị trí lằn ranh; lằn ranh lấn vào đất liền thay vì lấy trung tuyến; nhiều thực thể không đủ tiêu chuẩn “đảo” để có EEZ.',
    'opposition_voice3_chip1' => 'Không hội đủ điều kiện pháp lý',
    'opposition_voice3_chip2' => 'Phân tích chính thức',
    'opposition_voice4_year' => 'Học thuật',
    'opposition_voice4_title' => '“Vùng nước lịch sử” đã lỗi thời',
    'opposition_voice4_body' => 'Khái niệm này chỉ áp dụng cho vịnh, vụng nước sát bờ — không thể bao phủ cả một vùng biển khơi rộng lớn. Năm 2003, chính Đài Loan cũng đã bác bỏ chính sách “vùng nước lịch sử” từng nêu năm 1993.',
    'opposition_voice4_chip1' => 'Ngay cả học giả TQ cũng không thống nhất',
];
