<?php

return [
    'sovereignty_index' => 'Hoàng Sa – Trường Sa',
    'sovereignty_label' => 'Kết luận tất yếu',
    'sovereignty_title' => 'Hoàng Sa – Trường Sa',
    'sovereignty_title_accent' => 'là của Việt Nam',
    'sovereignty_lead' => 'Trang này giải thích Đường Lưỡi Bò. Phần kết luận trả lời câu hỏi tiếp theo: ai có chủ quyền với hai quần đảo Hoàng Sa và Trường Sa? Theo lịch sử quản lý và luật pháp quốc tế, câu trả lời nhất quán là Việt Nam.',
    'sovereignty_thesis_label' => 'Luận điểm tổng hợp',
    'sovereignty_thesis_lock1' => 'Không tọa độ pháp lý',
    'sovereignty_thesis_lock2' => 'PCA 2016 bác bỏ',
    'sovereignty_thesis_lock3' => 'Bản đồ cổ không bao trùm',
    'sovereignty_thesis_body' => 'Sau sáu mục phía trên, ba điểm đã rõ: Đường Lưỡi Bò vẽ tay, không có tọa độ pháp lý; Tòa Trọng tài năm 2016 bác bỏ yêu sách; bản đồ cổ của chính Trung Quốc không bao trùm Biển Đông. Chủ quyền Việt Nam không dựa vào khẩu hiệu mà dựa vào việc nhà nước Việt Nam — từ thời các chúa Nguyễn — đã quản lý hòa bình và liên tục khi hai quần đảo còn là đất vô chủ.',
    'sovereignty_spine_caption' => 'Mốc quản lý liên tục',
    'sovereignty_spine_title' => 'Một dòng thời gian, không gián đoạn',
    'sovereignty_spine_range' => 'Thế kỷ XVII → nay',
    'sovereignty_chron1_year' => 'TK XVII',
    'sovereignty_chron1_title' => 'Đội Hoàng Sa',
    'sovereignty_chron1_body' => 'Các chúa Nguyễn cử đội Hoàng Sa khảo sát, đo thủy trình và khai thác trên biển — thực thi quyền quản lý thực tế.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Vua Gia Long',
    'sovereignty_chron2_body' => 'Cắm cờ trên quần đảo Hoàng Sa, khẳng định chủ quyền của Việt Nam trước thế giới đương thời.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Vua Minh Mạng',
    'sovereignty_chron3_body' => 'Đo đạc, dựng bia, ghi nhận quần đảo trên bản đồ chính thức của triều đình.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kế thừa liên tục',
    'sovereignty_chron4_body' => 'Pháp công nhận và tiếp tục quản lý; sáp nhập Hoàng Sa vào tỉnh Thừa Thiên — nền tảng cho Nhà nước Việt Nam hiện nay.',
    'sovereignty_chron5_year' => 'Hiện nay',
    'sovereignty_chron5_title' => 'Luật và thực tiễn',
    'sovereignty_chron5_body' => 'Việt Nam quản lý theo UNCLOS, ngoại giao và hồ sơ lưu trữ; yêu sách Đường Lưỡi Bò không thay thế được bằng chứng này.',
    'sovereignty_balance_label' => 'Cân bằng bằng chứng',
    'sovereignty_balance_medallion_title' => 'Đối chiếu hai phía',
    'sovereignty_vn_tag' => 'Phía Việt Nam',
    'sovereignty_vn_title' => 'Chủ quyền được xác lập bằng hành vi',
    'sovereignty_vn_body' => 'Chiếm hữu thực sự khi đất còn vô chủ, sau đó quản lý công khai qua nhiều thế kỷ — có châu bản, bia, bản đồ và hồ sơ hành chính. Cách làm này phù hợp UNCLOS và thông lệ quốc tế.',
    'sovereignty_dash_tag' => 'Phía Đường Lưỡi Bò',
    'sovereignty_dash_title' => 'Yêu sách không bù được bằng chứng',
    'sovereignty_dash_body' => 'Một đường vẽ năm 1948, không tọa độ, đã bị PCA 2016 bác bỏ và trái UNCLOS — như các mục 03 đến 06 đã trình bày. Đó là lý do kết luận về chủ quyền hai quần đảo không thể dựa vào Đường Lưỡi Bò.',
    'sovereignty_seal_quote' => 'Việt Nam giải quyết tranh chấp bằng <strong>biện pháp hòa bình</strong>, trên cơ sở luật pháp quốc tế — đặc biệt UNCLOS 1982 — hướng tới Biển Đông hòa bình, hợp tác và phát triển.',
    'sovereignty_seal_cite' => 'Lập trường của Việt Nam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Dự án chính trong cùng hệ sinh thái',
    'sovereignty_next_title' => 'Đọc đầy đủ bằng chứng về Hoàng Sa – Trường Sa',
    'sovereignty_next_body' => 'Hồ sơ chi tiết — tài liệu, bản đồ, dòng thời gian và luận cứ pháp lý — nằm trên trang <strong>paracelislands.net</strong>, nơi trình bày toàn diện chủ đề chủ quyền hai quần đảo. Trang bạn đang đọc chỉ kết nối logic từ Đường Lưỡi Bò tới kết luận đó.',
    'sovereignty_next_cta' => 'Mở paracelislands.net',
];
