<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Phán quyết quốc tế',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'ba chữ “Không”',
    'verdict_lead' => 'Ngày 12/7/2016, Tòa Trọng tài Thường trực (PCA) tại The Hague — lập theo Phụ lục VII của UNCLOS, trong vụ Philippines kiện Trung Quốc — đã ra phán quyết bác bỏ yêu sách Đường Lưỡi Bò. <em>Bấm vào mỗi thẻ để đọc nguyên văn.</em>',
    'verdict_card1_khong' => 'KHÔNG',
    'verdict_card1_title' => 'quyền lịch sử',
    'verdict_card1_short' => 'Không có cơ sở pháp lý để Trung Quốc nêu quyền lịch sử với tài nguyên trong vùng biển nằm trong Đường Lưỡi Bò.',
    'verdict_card1_quote' => '“Không có căn cứ pháp lý cho việc Trung Quốc nêu quyền lịch sử với các tài nguyên nằm trong vùng biển trong Đường Lưỡi Bò.”',
    'verdict_card1_more' => '+ Đọc phán quyết',
    'verdict_card2_khong' => 'KHÔNG',
    'verdict_card2_title' => 'thực thể tạo EEZ',
    'verdict_card2_short' => 'Không thực thể nào ở quần đảo Trường Sa đủ điều kiện tạo ra vùng đặc quyền kinh tế cho Trung Quốc — kể cả đảo Ba Bình.',
    'verdict_card2_quote' => '“Không một thực thể nào ở quần đảo Trường Sa có khả năng tạo ra vùng đặc quyền kinh tế.”',
    'verdict_card2_more' => '+ Đọc phán quyết',
    'verdict_card3_khong' => 'KHÔNG',
    'verdict_card3_title' => 'hành vi hợp pháp',
    'verdict_card3_short' => 'Trung Quốc vi phạm quyền chủ quyền của Philippines, cản trở đánh bắt cá và gây hại môi trường biển.',
    'verdict_card3_quote' => '“Trung Quốc đã vi phạm quyền chủ quyền của Philippines, can thiệp vào hoạt động đánh bắt cá tại bãi Scarborough và gây hại nghiêm trọng cho môi trường rạn san hô.”',
    'verdict_card3_more' => '+ Đọc phán quyết',
    'verdict_extra1' => 'Đường Lưỡi Bò do Trung Quốc tự vẽ <strong>không phù hợp</strong> với UNCLOS 1982.',
    'verdict_extra2' => 'Trung Quốc gây thiệt hại hệ sinh thái Trường Sa qua khai thác quá mức và xây đảo nhân tạo.',
    'verdict_extra3' => 'Các hành động của Trung Quốc làm gia tăng nguy cơ xung đột với Philippines.',
    'verdict_extra4' => 'Đảo Ba Bình (do Đài Loan kiểm soát) cũng không thể tạo ra EEZ.',
    'verdict_subtitle' => 'Vì sao nó xung đột với UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 phân định rõ ràng các vùng biển dựa trên đường cơ sở của quốc gia ven biển. Yêu sách Đường Lưỡi Bò vượt ra ngoài khuôn khổ này nên không thể đặt cạnh nhau.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Lãnh hải (hải lý)',
    'verdict_zone1_body' => 'Vùng biển quốc gia có chủ quyền, tính từ đường cơ sở.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Vùng đặc quyền kinh tế',
    'verdict_zone2_body' => 'EEZ — quốc gia ven biển có quyền chủ quyền về tài nguyên trong phạm vi này.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Thềm lục địa (tối đa, hải lý)',
    'verdict_zone3_body' => 'Quyền với tài nguyên đáy biển, theo điều kiện địa chất xác định.',
    'verdict_foot' => 'Trong khuôn khổ này, “quyền lịch sử” bao trùm cả một vùng biển khơi — như Đường Lưỡi Bò ngụ ý — <em>đã bị thay thế</em> bởi chế độ pháp lý của UNCLOS mà chính Trung Quốc cũng là thành viên.',
];
