<?php

return [
    'footer_index' => 'Knjižnica',
    'footer_crest_eyebrow' => 'Zaključek knjižnice resnice',
    'footer_crest_quote' => '"Mir v Južnokitajskem morju je zgrajen na temelju <b>mednarodnega prava</b>."',
    'footer_crest_sub' => 'Brez sovraštva · Le resnica',
    'footer_nav_aria' => 'Dejanja v nogi strani',
    'footer_btn_top' => 'Nazaj na vrh',
    'footer_btn_verdict' => 'Razsodba PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Zahtevki Linije devetih črt',
    'footer_brand_eyebrow' => 'Tematska stran · Suverenost Vietnam',
    'footer_brand_body' => 'Pojasnilo Linije devetih črt skozi objektivna dejstva, mednarodno pravo, razsodbo PCA 2016 in zgodovinske vire — kot dopolnilo specializiranim stranem o suverenosti obeh arhipelagov <strong>"Paracelski otoki in Spratlyjevi otoki"</strong>. Zgodovino in dokaze uporabljamo za zavračanje neutemeljenih zahtev Kitajska.',
    'footer_refs_title' => 'Viri za referenco',
    'footer_ref1' => 'Razsodba PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — celotno besedilo',
    'footer_ref3' => 'Limits in the Seas št. 143 (US DoS)',
    'footer_ref4' => 'Zgodovinski viri in stari zemljevidi',
    'footer_toc_title' => 'Kazalo strani',
    'footer_toc1' => 'Kaj je Linija devetih črt',
    'footer_toc2' => 'Izvor',
    'footer_toc3' => 'Zakaj je sporna',
    'footer_toc4' => 'Zakaj ji mednarodna skupnost nasprotuje',
    'footer_toc5' => 'Tiha priča',
    'footer_toc6' => 'Razsodba PCA 2016',
    'footer_toc7' => 'Paracelski otoki – Spratlyjevi otoki',
    'footer_copy_eyebrow' => 'Neprofitni projekt',
    'footer_copy_title' => 'Paracelski otoki – Spratlyjevi otoki so del Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematska stran o Liniji devetih črt v okviru vietnamovega ekosistema suverenosti.',
    'footer_copy_body' => 'Pojasnilo zahtevka Linije devetih črt skozi <strong>objektivna dejstva</strong>, <strong>mednarodno pravo</strong>, razsodbo PCA 2016 in zgodovinske vire — kot dopolnilo specializiranim stranem o suverenosti obeh arhipelagov Paracelski otoki in Spratlyjevi otoki.',
    'footer_copy_ecosystem_aria' => 'Sorodne strani projekta',
    'footer_copy_ecosystem_label' => 'Isti ekosistem',
    'footer_copy_disclaimer' => 'Vsebina je namenjena izobraževanju in ozaveščanju; ne nadomešča uradnega stališča države Vietnam.',
    'footer_copy' => '<strong>© :year Linija devetih črt</strong> — Del neprofitnega projekta <strong>Paracelski otoki – Spratlyjevi otoki so del Vietnam</strong> v sistemu: <a href="https://paracelislands.net/sl" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/sl" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/sl" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/sl" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/sl" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Zaveze vsebine strani',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Razsodba PCA 2016',
    'footer_chip3' => 'Zgodovinski dokazi',
    'footer_chip4' => 'Stari zemljevidi',
    'footer_chip5' => 'Objektivna resnica',
    'footer_chip6' => 'Mir v Južnokitajskem morju',
];
