<?php

return [
    'footer_index' => 'Knjižnica',
    'footer_crest_eyebrow' => 'Konec knjižnice resnice',
    'footer_crest_quote' => '“Mir na Južnokitajskem morju je zgrajen na temelju <b>mednarodnega prava</b>.”',
    'footer_crest_sub' => 'Brez sovraštva · Samo resnica',
    'footer_nav_aria' => 'Dejanja v nogi strani',
    'footer_btn_top' => 'Na vrh strani',
    'footer_btn_verdict' => 'Razsodba PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Yêu Sách Đường Lưỡi Bò',
    'footer_brand_eyebrow' => 'Tematska stran · Suverenost Vietnam',
    'footer_brand_body' => 'Pojasnjuje Linija devetih črt skozi objektivna dejstva, mednarodno pravo, razsodbo PCA 2016 in zgodovinske vire — kot dopolnilo poglobljenim stranem o suverenosti nad obema arhipelagoma <strong>"Paracelski otoki in Spratlyjevi otoki"</strong>. Ovrže neutemeljene zahtevke Kitajska z zgodovino in dokazi.',
    'footer_refs_title' => 'Viri',
    'footer_ref1' => 'Razsodba PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — celotno besedilo',
    'footer_ref3' => 'Limits in the Seas št. 143 (US DoS)',
    'footer_ref4' => 'Zgodovinski viri in stare karte',
    'footer_toc_title' => 'Kazalo strani',
    'footer_toc1' => 'Kaj je Linija devetih črt',
    'footer_toc2' => 'Izvor',
    'footer_toc3' => 'Zakaj je sporna',
    'footer_toc4' => 'Zakaj ji mednarodna skupnost nasprotuje',
    'footer_toc5' => 'Nemi pričevalci',
    'footer_toc6' => 'Razsodba PCA 2016',
    'footer_toc7' => 'Paracelski otoki – Spratlyjevi otoki',
    'footer_copy_eyebrow' => 'Neprofitni projekt',
    'footer_copy_title' => 'Paracelski otoki – Spratlyjevi otoki so del Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematska stran o Linija devetih črt v okviru suverenostnega ekosistema Vietnam.',
    'footer_copy_body' => 'Razlaga zahtevkov Linija devetih črt skozi <strong>objektivna dejstva</strong>, <strong>mednarodno pravo</strong>, razsodbo PCA 2016 in zgodovinske vire — kot dopolnilo poglobljenim stranem o suverenosti nad arhipelagoma Paracelski otoki in Spratlyjevi otoki.',
    'footer_copy_ecosystem_aria' => 'Sorodne strani projekta',
    'footer_copy_ecosystem_label' => 'V istem ekosistemu',
    'footer_copy_disclaimer' => 'Vsebina je namenjena izobraževanju in ozaveščanju; ne nadomešča uradnega stališča države Vietnam.',
    'footer_copy' => '<strong>© :year Đường Lưỡi Bò</strong> — Del neprofitnega projekta <strong>Paracelski otoki – Spratlyjevi otoki so del Vietnam</strong> v okviru sistema: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Zaveza vsebine strani',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Razsodba PCA 2016',
    'footer_chip3' => 'Zgodovinski dokazi',
    'footer_chip4' => 'Stare karte',
    'footer_chip5' => 'Objektivna resnica',
    'footer_chip6' => 'Mir na Južnokitajskem morju',
];
