<?php

return [
    'footer_index' => 'Knjižnica',
    'footer_crest_eyebrow' => 'Sklepanje knjižnice resnice',
    'footer_crest_quote' => '“Mir na Južnokitajskem morju temelji na <b>mednarodnem pravu</b>.”',
    'footer_crest_sub' => 'Brez sovraštva · Le resnica',
    'footer_nav_aria' => 'Dejanja v nogi strani',
    'footer_btn_top' => 'Nazaj na vrh',
    'footer_btn_verdict' => 'Razsodba PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linija devetih črt',
    'footer_brand_body' => 'Spletna stran, ki pojasnjuje dejstva na podlagi objektivne resnice, mednarodnega prava in zgodovinskih virov — zahteve Linije devetih črt zavrača z dokazi, ne s slogani.',
    'footer_refs_title' => 'Viri',
    'footer_ref1' => 'Razsodba PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — celotno besedilo',
    'footer_ref3' => 'Limits in the Seas št. 143 (US DoS)',
    'footer_ref4' => 'Zgodovinski viri in stare karte',
    'footer_toc_title' => 'Kazalo strani',
    'footer_toc1' => 'Kaj je Linija devetih črt',
    'footer_toc2' => 'Izvor',
    'footer_toc3' => 'Zakaj je sporno',
    'footer_toc4' => 'Zakaj mu mednarodna skupnost nasprotuje',
    'footer_toc5' => 'Tihi pričevalci',
    'footer_toc6' => 'Razsodba PCA 2016',
    'footer_toc7' => 'Paracelski otoki – Spratlyjevi otoki',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektivna resnica o Južnokitajskem morju.<br>Ekoistem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Brez koordinat',
];
