<?php

return [
    'nav_logo_name' => 'Linija devetih črt',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linija devetih črt',
    'nav_rail_aria' => 'Krmarjenje po razdelkih',
    'nav_rail_what' => 'Opredelitev',
    'nav_rail_origin' => 'Izvor',
    'nav_rail_dispute' => 'Spor',
    'nav_rail_opposition' => 'Nasprotovanje',
    'nav_rail_witnesses' => 'Stari zemljevidi',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelski otoki – Spratlyjevi otoki',
    'nav_sound_off' => 'Vklopi ozadno glasbo',
    'nav_sound_on' => 'Izklopi ozadno glasbo',
    'nav_share' => 'Deli',
    'dialog_title' => 'Jezik prikaza',
    'language' => 'Jezik',
    'display_hint' => ':count jezikov',
    'search_placeholder' => 'Išči jezik…',
    'cancel' => 'Prekliči',
    'apply' => 'Uporabi',
    'sound_off' => 'Vklopi ozadni zvok',
    'sound_on' => 'Izklopi ozadni zvok',
    'lang_trigger' => 'Izberi jezik',
    'close' => 'Zapri',
    'no_results' => 'Jezik ni najden',
    'contribute' => 'Deli',
];
