<?php

return [
    'opposition_index' => 'Nasprotovanje',
    'opposition_label' => 'Zakaj mednarodna skupnost nasprotuje',
    'opposition_title' => 'Nasprotovanje temelji na',
    'opposition_title_accent' => 'pravu, ne na čustvih',
    'opposition_lead' => 'Takoj po tem, ko je bila Linija devetih črt leta 2009 predložena Združenim narodom, so številne države in akademiki nasprotovali — s konkretnimi pravnimi argumenti.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'maj',
    'opposition_voice1_title' => 'Vietnam · Malezija · Indonezija',
    'opposition_voice1_body' => 'Že en dan po tem, ko je Kitajska zemljevid Linije devetih črt predložila generalnemu sekretarju Združenih narodov (7. 5. 2009), so te države zaporedoma poslale diplomatske note protesta in zavrnile ta zahtevek.',
    'opposition_voice1_chip1' => 'Diplomatska nota protesta',
    'opposition_voice1_chip2' => 'Ni skladno z UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipini',
    'opposition_voice2_body' => 'Združenim narodom so poslali diplomatsko pismo in izjavili, da je zahtevek Kitajske v Južnokitajskem morju "brez podlage v mednarodnem pravu" — kar je postavilo temelje za poznejšo tožbo pred arbitražnim sodiščem.',
    'opposition_voice2_chip1' => 'Temelj za zadevo PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ameriško zunanje ministrstvo — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiza je pokazala: zemljevidi iz različnih let so bili nedosledni glede položaja črt; črte so segale v kopno namesto da bi upoštevale sredinsko črto; številni objekti ne izpolnjujejo pogojev za "otok" in zato ne morejo imeti EEZ.',
    'opposition_voice3_chip1' => 'Ne izpolnjuje pravnih pogojev',
    'opposition_voice3_chip2' => 'Uradna analiza',
    'opposition_voice4_year' => 'Akademsko',
    'opposition_voice4_title' => '"Zgodovinske vode" so zastarel koncept',
    'opposition_voice4_body' => 'Ta koncept velja le za zalive in obalne zateke — ne more zajeti celotnega prostranega odprtega morja. Leta 2003 je tudi Tajvan zavrnil politiko "zgodovinskih voda", ki jo je omenil leta 1993.',
    'opposition_voice4_chip1' => 'Tudi kitajski akademiki se ne strinjajo',
];
