<?php

return [
    'sovereignty_index' => 'Paracelski otoki – Spratlyjevi otoki',
    'sovereignty_label' => 'Nujen sklep',
    'sovereignty_title' => 'Paracelski otoki – Spratlyjevi otoki',
    'sovereignty_title_accent' => 'sta del Vietnam',
    'sovereignty_lead' => 'Ta stran pojasnjuje Linija devetih črt. Sklepni del odgovarja na naslednje vprašanje: kdo ima suverenost nad obema arhipelagoma, Paracelskimi otoki in Spratlyjevimi otoki? Glede na zgodovinsko upravljanje in mednarodno pravo je dosleden odgovor Vietnam.',
    'sovereignty_thesis_label' => 'Združeni argument',
    'sovereignty_thesis_lock1' => 'Brez pravnih koordinat',
    'sovereignty_thesis_lock2' => 'PCA 2016 zavrnila',
    'sovereignty_thesis_lock3' => 'Starih zemljevidov ne pokriva',
    'sovereignty_thesis_body' => 'Po šestih zgornjih delih so tri stvari jasne: Linija devetih črt je narisana ročno in nima pravnih koordinat; arbitražno sodišče leta 2016 je zahtevek zavrnilo; stare kitajske karte ne pokrivajo Južnokitajskega morja. Suverenost Vietnama ne temelji na sloganu, temveč na tem, da je vietnamska država — od časa dinastije Nguyễn — mirno in neprekinjeno upravljala, ko sta bila oba arhipelaga še nikogaršnja zemlja.',
    'sovereignty_spine_caption' => 'Mejniki neprekinjenega upravljanja',
    'sovereignty_spine_title' => 'Enoten, neprekinjen časovni trak',
    'sovereignty_spine_range' => '17. stoletje → danes',
    'sovereignty_chron1_year' => '17. stol.',
    'sovereignty_chron1_title' => 'Enota Hoàng Sa',
    'sovereignty_chron1_body' => 'Vladarji Nguyễn so pošiljali enoto Hoàng Sa za raziskovanje, merjenje plovnih poti in izkoriščanje na morju — izvajanje dejanske oblasti.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kralj Gia Long',
    'sovereignty_chron2_body' => 'Na Paracelskih otokih je izobesil zastavo in tako svetu tistega časa potrdil suverenost Vietnama.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kralj Minh Mạng',
    'sovereignty_chron3_body' => 'Izvedel je merjenja, postavil stele in arhipelag zapisal na uradne zemljevide dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Neprekinjeno nasledstvo',
    'sovereignty_chron4_body' => 'Francija je priznala in nadaljevala upravljanje; Paracelske otoke je priključila provinci Thừa Thiên — kar je postavilo temelje za današnjo državo Vietnam.',
    'sovereignty_chron5_year' => 'Danes',
    'sovereignty_chron5_title' => 'Pravo in praksa',
    'sovereignty_chron5_body' => 'Vietnam upravlja v skladu z UNCLOS, diplomacijo in arhivskimi zapisi; zahtevek Linija devetih črt teh dokazov ne more nadomestiti.',
    'sovereignty_balance_label' => 'Uravnoteženje dokazov',
    'sovereignty_balance_medallion_title' => 'Primerjava obeh strani',
    'sovereignty_vn_tag' => 'Vietnamska stran',
    'sovereignty_vn_title' => 'Suverenost je vzpostavljena z dejanji',
    'sovereignty_vn_body' => 'Dejanska zasedba, ko je bila zemlja še nikogaršnja, nato pa javno upravljanje skozi stoletja — z imperialnimi zapisi, stebri, zemljevidi in administrativnimi dokumenti. Takšen pristop je v skladu z UNCLOS in mednarodno prakso.',
    'sovereignty_dash_tag' => 'Stran Linija devetih črt',
    'sovereignty_dash_title' => 'Zahtevek ne more nadomestiti dokazov',
    'sovereignty_dash_body' => 'Leta 1948 narisana črta brez koordinat je bila z odločbo PCA 2016 zavrnjena in je v nasprotju z UNCLOS — kot je bilo predstavljeno v delih od 03 do 06. Zato sklepa o suverenosti nad obema arhipelagoma ni mogoče utemeljiti na Linija devetih črt.',
    'sovereignty_seal_quote' => 'Vietnam spore rešuje z <strong>miroljubnimi sredstvi</strong>, na podlagi mednarodnega prava — zlasti UNCLOS 1982 — in si prizadeva za Južnokitajsko morje, ki je mirno, sodelovalno in razvojno usmerjeno.',
    'sovereignty_seal_cite' => 'Stališče Vietnama · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Glavni projekt v istem ekosistemu',
    'sovereignty_next_title' => 'V celoti preberite dokaze o Paracelskih otokih – Spratlyjevih otokih',
    'sovereignty_next_body' => 'Podrobna dokumentacija — gradiva, zemljevidi, časovni trakovi in pravni argumenti — je na strani <strong>paracelislands.net</strong>, kjer je tema suverenosti nad obema arhipelagoma predstavljena celovito. Stran, ki jo pravkar berete, le logično povezuje Linija devetih črt s tem sklepom.',
    'sovereignty_next_cta' => 'Odpri paracelislands.net',
];
