<?php

return [
    'sovereignty_index' => 'Paracelski otoki – Spratlyjevi otoki',
    'sovereignty_label' => 'Nujni sklep',
    'sovereignty_title' => 'Paracelski otoki – Spratlyjevi otoki',
    'sovereignty_title_accent' => 'so Vietnam',
    'sovereignty_lead' => 'Ta stran pojasnjuje Linija devetih črt. Sklepni del odgovarja na naslednje vprašanje: kdo ima suverenost nad dvema arhipelagoma, Paracelski otoki in Spratlyjevi otoki? Glede na zgodovinsko upravljanje in mednarodno pravo je dosleden odgovor Vietnam.',
    'sovereignty_thesis_label' => 'Združeni argument',
    'sovereignty_thesis_lock1' => 'Brez pravnih koordinat',
    'sovereignty_thesis_lock2' => 'PCA 2016 zavrača',
    'sovereignty_thesis_lock3' => 'Stare karte tega ne pokrivajo',
    'sovereignty_thesis_body' => 'Po šestih zgornjih poglavjih so tri točke jasne: Linija devetih črt je narisana ročno, brez pravnih koordinat; arbitražno sodišče leta 2016 je zavrnilo zahtevek; stare karte same Kitajske ne zajemajo Južnokitajskega morja. Suverenost Vietnama ne temelji na sloganu, temveč na tem, da je vietnamska država — od časa Nguyễnovih vladarjev — mirno in neprekinjeno upravljala, ko sta bila oba arhipelaga še nikogaršnja zemlja.',
    'sovereignty_spine_caption' => 'Mejnik neprekinjenega upravljanja',
    'sovereignty_spine_title' => 'En sam časovni trak, brez prekinitve',
    'sovereignty_spine_range' => '17. stoletje → danes',
    'sovereignty_chron1_year' => '17. stol.',
    'sovereignty_chron1_title' => 'Enota Hoàng Sa',
    'sovereignty_chron1_body' => 'Nguyễnovi vladarji so pošiljali enoto Hoàng Sa, da je pregledovala območje, merila plovne poti in izkoriščala morje — s tem je izvajala dejansko upravljanje.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Kralj Gia Long',
    'sovereignty_chron2_body' => 'Zastavo je dvignil na arhipelagu Paracelski otoki in s tem pred tedanjim svetom potrdil suverenost Vietnama.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Kralj Minh Mạng',
    'sovereignty_chron3_body' => 'Izvedel je meritve, postavil stele in arhipelag vpisal na uradne zemljevide dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Neprekinjeno nasledstvo',
    'sovereignty_chron4_body' => 'Francija je to priznala in nadaljevala upravljanje; Paracelski otoki so bili priključeni provinci Thừa Thiên — kar je postavilo temelje za današnjo vietnamsko državo.',
    'sovereignty_chron5_year' => 'Danes',
    'sovereignty_chron5_title' => 'Pravo in praksa',
    'sovereignty_chron5_body' => 'Vietnam upravlja v skladu z UNCLOS, diplomacijo in arhivskimi zapisi; zahtevek po Linija devetih črt teh dokazov ne more nadomestiti.',
    'sovereignty_balance_label' => 'Ravnotežje dokazov',
    'sovereignty_balance_medallion_title' => 'Primerjava obeh strani',
    'sovereignty_vn_tag' => 'Vietnamska stran',
    'sovereignty_vn_title' => 'Suverenost, uveljavljena z dejanji',
    'sovereignty_vn_body' => 'Dejanska zasedba, ko je bilo območje še nikogaršnje, nato pa javno upravljanje skozi stoletja — z imperialnimi zapisi, stélami, zemljevidi in upravnimi dokumenti. Tak pristop je skladen z UNCLOS in mednarodno prakso.',
    'sovereignty_dash_tag' => 'Stran Linija devetih črt',
    'sovereignty_dash_title' => 'Zahtevek ne more nadomestiti dokazov',
    'sovereignty_dash_body' => 'Leta 1948 narisana črta brez koordinat je bila zavrnjena s strani PCA leta 2016 in je v nasprotju z UNCLOS — kot je bilo predstavljeno v točkah 03 do 06. Zato sklepa o suverenosti nad obema arhipelagoma ni mogoče opreti na Linija devetih črt.',
    'sovereignty_seal_quote' => 'Vietnam spore rešuje z <strong>miroljubnimi sredstvi</strong>, na podlagi mednarodnega prava — zlasti UNCLOS 1982 — ter si prizadeva za mirno, sodelovalno in razvojno Južnokitajsko morje.',
    'sovereignty_seal_cite' => 'Stališče Vietnama · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Glavni projekt v istem ekosistemu',
    'sovereignty_next_title' => 'Preberite celotne dokaze o Paracelski otoki – Spratlyjevi otoki',
    'sovereignty_next_body' => 'Podrobna dokumentacija — gradiva, zemljevidi, časovni trakovi in pravni argumenti — je na strani <strong>paracelislands.net</strong>, kjer je tema suverenosti nad obema arhipelagoma predstavljena celovito. Stran, ki jo trenutno berete, le logično povezuje Linija devetih črt z omenjenim sklepom.',
    'sovereignty_next_cta' => 'Odpri paracelislands.net',
];
