<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Mednarodna razsodba',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tri »ne«',
    'verdict_lead' => 'Dne 12. 7. 2016 je Stalno arbitražno sodišče (PCA) v Haagu — ustanovljeno po Prilogi VII UNCLOS v zadevi, ki jo je Filipini sprožili proti Kitajski — izdalo razsodbo, s katero je zavrnilo zahtevek glede Linija devetih črt. <em>Kliknite vsako kartico za branje celotnega besedila.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'zgodovinska pravica',
    'verdict_card1_short' => 'Ni pravne podlage, da bi Kitajska uveljavljala zgodovinsko pravico do virov v morskem območju znotraj Linija devetih črt.',
    'verdict_card1_quote' => '“Ni pravne podlage, da bi Kitajska uveljavljala zgodovinske pravice do virov v morskih območjih znotraj Linija devetih črt.”',
    'verdict_card1_more' => '+ Preberi razsodbo',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'entiteta, ki ustvarja EEZ',
    'verdict_card2_short' => 'Nobena entiteta na otokih Spratlyjevi otoki ne izpolnjuje pogojev za ustvarjanje izključne ekonomske cone za Kitajsko — niti otok Ba Bình.',
    'verdict_card2_quote' => '“Nobena entiteta na otokih Spratlyjevi otoki nima sposobnosti ustvariti izključne ekonomske cone.”',
    'verdict_card2_more' => '+ Preberi razsodbo',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'zakonito ravnanje',
    'verdict_card3_short' => 'Kitajska je kršila suverene pravice Filipinov, ovirala ribolov in škodovala morskemu okolju.',
    'verdict_card3_quote' => '“Kitajska je kršila suverene pravice Filipinov, posegala v ribolovne dejavnosti na grebenu Scarborough in povzročila hudo škodo koralnemu okolju.”',
    'verdict_card3_more' => '+ Preberi razsodbo',
    'verdict_extra1' => 'Linija devetih črt, ki jo je Kitajska sama narisala, <strong>ni skladna</strong> z UNCLOS iz leta 1982.',
    'verdict_extra2' => 'Kitajska je z izčrpavanjem virov in gradnjo umetnih otokov povzročila škodo ekosistemu na otokih Spratlyjevi otoki.',
    'verdict_extra3' => 'Dejanja Kitajske povečujejo tveganje za spor s Filipini.',
    'verdict_extra4' => 'Tudi otok Ba Bình (pod nadzorom Tajvana) ne more ustvariti EEZ.',
    'verdict_subtitle' => 'Zakaj je to v nasprotju z UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS iz leta 1982 jasno določa morske pasove na podlagi izhodiščne črte obalne države. Zahtevek glede Linija devetih črt presega ta okvir, zato ju ni mogoče uskladiti.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritorialno morje (navtične milje)',
    'verdict_zone1_body' => 'Morsko območje pod suverenostjo države, merjeno od izhodiščne črte.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Izključna ekonomska cona',
    'verdict_zone2_body' => 'EEZ — obalna država ima suverene pravice do virov v tem območju.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Celinska polica (največ, navtične milje)',
    'verdict_zone3_body' => 'Pravice do morskega dna in njegovih virov, pod pogoji, določenimi z geološkimi merili.',
    'verdict_foot' => 'V tem okviru je bila »zgodovinska pravica«, ki naj bi obsegala celotno odprto morje — kot to nakazuje Linija devetih črt — <em>nadomeščena</em> s pravnim režimom UNCLOS, katerega članica je tudi Kitajska.',
];
