<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Mednarodna razsodba',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tri »ne«',
    'verdict_lead' => 'Dne 12. 7. 2016 je Stalno arbitražno sodišče (PCA) v Haagu — ustanovljeno po Prilogi VII UNCLOS v zadevi, ki jo je Filipini vložilo proti Kitajski — izdalo razsodbo, s katero je zavrnilo zahtevek Linija devetih črt. <em>Za branje celotnega besedila kliknite na vsako kartico.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'zgodovinske pravice',
    'verdict_card1_short' => 'Ni pravne podlage, da bi Kitajska uveljavljala zgodovinske pravice do virov v morskih območjih znotraj Linije devetih črt.',
    'verdict_card1_quote' => '“Ni pravne podlage za to, da bi Kitajska uveljavljala zgodovinske pravice do virov v morskih območjih znotraj Linije devetih črt.”',
    'verdict_card1_more' => '+ Preberi razsodbo',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'element, ki ustvarja EEZ',
    'verdict_card2_short' => 'Noben element na otokih Spratlyjevi otoki ne izpolnjuje pogojev za ustvarjanje izključne ekonomske cone za Kitajsko — niti otok Ba Binh.',
    'verdict_card2_quote' => '“Noben element na otokih Spratlyjevi otoki ni sposoben ustvariti izključne ekonomske cone.”',
    'verdict_card2_more' => '+ Preberi razsodbo',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'zakonito ravnanje',
    'verdict_card3_short' => 'Kitajska je kršila suverene pravice Filipinov, ovirala ribolov in škodovala morskemu okolju.',
    'verdict_card3_quote' => '“Kitajska je kršila suverene pravice Filipinov, posegala v ribolovne dejavnosti pri grebenu Scarborough in povzročila resno škodo koralnemu okolju.”',
    'verdict_card3_more' => '+ Preberi razsodbo',
    'verdict_extra1' => 'Linija devetih črt, ki jo je Kitajska sama začrtala, <strong>ni skladna</strong> z UNCLOS iz leta 1982.',
    'verdict_extra2' => 'Kitajska je z prekomernim izkoriščanjem in gradnjo umetnih otokov škodovala ekosistemu Spratlyjevih otokov.',
    'verdict_extra3' => 'Dejanja Kitajske so povečala tveganje za konflikt s Filipini.',
    'verdict_extra4' => 'Otok Ba Binh (pod nadzorom Tajvana) prav tako ne more ustvariti EEZ.',
    'verdict_subtitle' => 'Zakaj je to v nasprotju z UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 jasno določa morske pasove na podlagi izhodiščnih linij obalne države. Zahtevek Linija devetih črt presega ta okvir, zato ju ni mogoče primerjati kot enakovredna.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritorialno morje (navtične milje)',
    'verdict_zone1_body' => 'Morsko območje pod suverenostjo države, merjeno od izhodiščne črte.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Izključna ekonomska cona',
    'verdict_zone2_body' => 'EEZ — obalna država ima v tem območju suverene pravice do virov.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Celinska polica (največ, navtične milje)',
    'verdict_zone3_body' => 'Pravice do virov morskega dna, glede na določene geološke pogoje.',
    'verdict_foot' => 'V tem okviru je »zgodovinska pravica«, ki naj bi zajemala celotno odprto morsko območje — kot namiguje Linija devetih črt — <em>nadomeščena</em> z pravnim režimom UNCLOS, katerega članica je tudi Kitajska.',
];
