<?php

return [
    'witnesses_index' => 'Stare zemljevidi',
    'witnesses_label' => 'Neme priče',
    'witnesses_title' => 'Stari zemljevidi',
    'witnesses_title_accent' => 'sami po sebi',
    'witnesses_lead' => 'Več stoletij so uradni zemljevidi Kitajske navajali <em>otok Hainan kot najjužnejšo točko</em> njenega ozemlja — brez črte v obliki črke U, ki bi obsegala celotno Južnokitajsko morje. Vzemimo povečevalno steklo in poglejmo južno mejo pobliže.',
    'witnesses_hint' => '⌖ Povečevalno steklo',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— najjužnejša točka ozemlja —',
    'witnesses_map1_svg_era' => 'Dinastija Song · 1136',
    'witnesses_map1_title' => 'Zemljevid dinastije Song, 1136',
    'witnesses_map1_body' => 'Ozemlje Kitajske se je končalo pri otoku Hainan — Paracelski otoki in Spratlyjevi otoki so ležali zunaj njegovih meja.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anvillova meja',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Zemljevid d\'Anvilla, 1735',
    'witnesses_map2_body' => 'Narisal ga je J.-B. B. d\'Anville; kopija iz leta 1740 je bila nekoč podarjena voditelju Kitajske s strani nemškega kanclerja. Ozemlje dinastije Qing se je končalo pri Hainanu.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"najjužnejša točka Kitajske"',
    'witnesses_map3_svg_era' => 'Qingovska cesarska provinca · 1904',
    'witnesses_map3_title' => 'Popolni zemljevid geografije cesarske province',
    'witnesses_map3_body' => 'Tiskano v času dinastije Qing — izrecno navaja, da je najjužnejša točka ozemlja Kitajske otok Hainan.',
    'witnesses_quote' => 'Že dokumenti njihovih prednikov niso narisali Linije devetih črt.',
];
