<?php

return [
    'witnesses_index' => 'Stari zemljevidi',
    'witnesses_label' => 'Stari kitajski zemljevidi',
    'witnesses_title' => 'Najjužnejša meja sega le do',
    'witnesses_title_accent' => 'otoka Hainan',
    'witnesses_lead' => 'Stari zemljevidi, ki so jih narisali kitajski avtorji in so razvrščeni kronološko, vsi prikazujejo, da je <em>otok Hainan najjužnejša točka</em> Kitajske, brez Paracelskih otokov ali Spratlyjevih otokov. Gradivo je povzeto po delu <em>Državna suverenost Vietnama nad otoškima skupinama Paracelski otoki in Spratlyjevi otoki</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Povečevalno steklo',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— najjužnejša točka ozemlja —',
    'witnesses_map1_svg_era' => 'Dinastija Song · 1136',
    'witnesses_map1_title' => 'Zemljevid dinastije Song, 1136',
    'witnesses_map1_body' => 'Ozemlje Kitajske se je končalo pri otoku Hainan — Paracelski otoki in Spratlyjevi otoki so ležali zunaj njegovih meja.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anvillova meja',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Zemljevid d\'Anvilla, 1735',
    'witnesses_map2_body' => 'Narisal ga je J.-B. B. d\'Anville; kopija iz leta 1740 je bila nekoč podarjena voditelju Kitajske s strani nemškega kanclerja. Ozemlje dinastije Qing se je končalo pri Hainanu.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"najjužnejša točka Kitajske"',
    'witnesses_map3_svg_era' => 'Qingovska cesarska provinca · 1904',
    'witnesses_map3_title' => 'Popolni zemljevid geografije cesarske province',
    'witnesses_map3_body' => 'Tiskano v času dinastije Qing — izrecno navaja, da je najjužnejša točka ozemlja Kitajske otok Hainan.',
    'witnesses_quote' => 'Tudi zemljevidi, ki jih je Kitajska sama objavila, niso prikazovali Paracelskih otokov in Spratlyjevih otokov kot del svojega ozemlja.',
    'witnesses_timeline_aria' => 'Časovnica starih kitajskih zemljevidov',
    'witnesses_year_aria' => 'Obdobje',
    'lightbox_aria' => 'Ogled povečane slike',
    'lightbox_close' => 'Zapri',
    'lightbox_prev' => 'Prejšnja slika',
    'lightbox_next' => 'Naslednja slika',
];
