<?php

return [
    'footer_index' => 'Biblioteca',
    'footer_crest_eyebrow' => 'Cierre de la biblioteca de la verdad',
    'footer_crest_quote' => '“La paz en el Mar del Este se construye sobre la base del <b>Derecho internacional</b>.”',
    'footer_crest_sub' => 'Sin odio · Solo la verdad',
    'footer_nav_aria' => 'Acciones del final de página',
    'footer_btn_top' => 'Volver arriba',
    'footer_btn_verdict' => 'Laudo PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Reivindicación de la Línea de nueve guiones',
    'footer_brand_eyebrow' => 'Página temática · Soberanía de Vietnam',
    'footer_brand_body' => 'Explicación de la Línea de nueve guiones mediante hechos objetivos, el derecho internacional, el laudo PCA de 2016 y documentación histórica — complemento de las páginas especializadas sobre la soberanía de los dos archipiélagos <strong>"Islas Paracel y Islas Spratly"</strong>. Refuta la reivindicación infundada de China con historia y pruebas.',
    'footer_refs_title' => 'Fuentes de referencia',
    'footer_ref1' => 'Laudo PCA, 12/07/2016',
    'footer_ref2' => 'CONVEMAR 1982 — texto completo',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documentación histórica y mapas antiguos',
    'footer_toc_title' => 'Índice de la página',
    'footer_toc1' => 'Qué es la Línea de nueve guiones',
    'footer_toc2' => 'Origen',
    'footer_toc3' => 'Por qué es controvertida',
    'footer_toc4' => 'Por qué la comunidad internacional la rechaza',
    'footer_toc5' => 'Testigos silenciosos',
    'footer_toc6' => 'Laudo PCA 2016',
    'footer_toc7' => 'Islas Paracel – Islas Spratly',
    'footer_copy_eyebrow' => 'Proyecto sin fines de lucro',
    'footer_copy_title' => 'Islas Paracel – Islas Spratly pertenecen a Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Página temática sobre la Línea de nueve guiones dentro del ecosistema de soberanía de Vietnam.',
    'footer_copy_body' => 'Explicación de la reivindicación de la Línea de nueve guiones mediante <strong>hechos objetivos</strong>, <strong>derecho internacional</strong>, el laudo PCA de 2016 y documentación histórica — complemento de las páginas especializadas sobre la soberanía de los archipiélagos Paracel y Spratly.',
    'footer_copy_ecosystem_aria' => 'Páginas del mismo proyecto',
    'footer_copy_ecosystem_label' => 'Mismo ecosistema',
    'footer_copy_disclaimer' => 'El contenido tiene fines educativos y de sensibilización; no sustituye la posición oficial del Estado de Vietnam.',
    'footer_copy' => '<strong>© :year Línea de nueve guiones</strong> — Parte del proyecto sin fines de lucro <strong>Islas Paracel – Islas Spratly pertenecen a Vietnam</strong> dentro del sistema: <a href="https://paracelislands.net/es" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/es" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/es" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/es" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/es" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Compromisos del contenido del sitio',
    'footer_chip1' => 'CONVEMAR 1982',
    'footer_chip2' => 'Laudo PCA 2016',
    'footer_chip3' => 'Pruebas históricas',
    'footer_chip4' => 'Mapas antiguos',
    'footer_chip5' => 'Hechos objetivos',
    'footer_chip6' => 'Paz en el Mar del Este',
];
