<?php

return [
    'footer_index' => 'Biblioteca',
    'footer_crest_eyebrow' => 'Epílogo de la biblioteca de la verdad',
    'footer_crest_quote' => '“La paz en el Mar del Este se construye sobre la base del <b>Derecho internacional</b>.”',
    'footer_crest_sub' => 'Sin odio · Solo la verdad',
    'footer_nav_aria' => 'Acciones al final de la página',
    'footer_btn_top' => 'Volver al inicio',
    'footer_btn_verdict' => 'Laudo PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Línea de nueve guiones',
    'footer_brand_body' => 'Una página explicativa basada en hechos objetivos, el Derecho internacional y documentos históricos: refuta la reclamación de la Línea de nueve guiones con pruebas, no con consignas.',
    'footer_refs_title' => 'Fuentes de referencia',
    'footer_ref1' => 'Laudo de la PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — texto completo',
    'footer_ref3' => 'Limits in the Seas №143 (Departamento de Estado de EE. UU.)',
    'footer_ref4' => 'Documentos históricos y mapas antiguos',
    'footer_toc_title' => 'Índice del sitio',
    'footer_toc1' => 'Qué es la Línea de nueve guiones',
    'footer_toc2' => 'Origen',
    'footer_toc3' => 'Por qué es controvertida',
    'footer_toc4' => 'Por qué la comunidad internacional se opone',
    'footer_toc5' => 'Testigos silenciosos',
    'footer_toc6' => 'Laudo PCA 2016',
    'footer_toc7' => 'Islas Paracel – Islas Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — La verdad objetiva sobre el Mar del Este.<br>Red de proyectos: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Sin coordenadas',
];
