<?php

return [
    'nav_logo_name' => 'Línea de nueve guiones',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Línea de nueve guiones',
    'nav_rail_aria' => 'Navegación por secciones',
    'nav_rail_what' => 'Definición',
    'nav_rail_origin' => 'Origen',
    'nav_rail_dispute' => 'Controversia',
    'nav_rail_opposition' => 'Oposición',
    'nav_rail_witnesses' => 'Mapas antiguos',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Islas Paracel – Islas Spratly',
    'nav_sound_off' => 'Activar música de fondo',
    'nav_sound_on' => 'Desactivar música de fondo',
    'nav_share' => 'Compartir',
    'dialog_title' => 'Idioma de visualización',
    'language' => 'Idioma',
    'display_hint' => ':count idiomas',
    'search_placeholder' => 'Buscar idioma…',
    'cancel' => 'Cancelar',
    'apply' => 'Aplicar',
    'sound_off' => 'Activar sonido de fondo',
    'sound_on' => 'Desactivar sonido de fondo',
    'lang_trigger' => 'Seleccionar idioma',
    'close' => 'Cerrar',
    'no_results' => 'No se encontraron idiomas',
    'contribute' => 'Compartir',
];
