<?php

return [
    'opposition_index' => 'Oposición',
    'opposition_label' => 'Por qué la comunidad internacional se opone',
    'opposition_title' => 'La oposición se basa en',
    'opposition_title_accent' => 'la ley, no en las emociones',
    'opposition_lead' => 'Poco después de que la Línea de nueve guiones fuera presentada ante las Naciones Unidas en 2009, muchos países y académicos la rechazaron — con argumentos jurídicos concretos.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayo',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Tan solo un día después de que China presentara el mapa de la Línea de nueve guiones al Secretario General de las Naciones Unidas (7/5/2009), estos países enviaron sucesivamente notas diplomáticas de protesta, rechazando la reclamación.',
    'opposition_voice1_chip1' => 'Nota diplomática de protesta',
    'opposition_voice1_chip2' => 'No conforme con la CONVEMAR de 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinas',
    'opposition_voice2_body' => 'Envió una nota diplomática a las Naciones Unidas, declarando que la reclamación de China en el Mar del Este de Vietnam no tenía "ninguna base conforme al derecho internacional" — antecedente del caso presentado después ante el Tribunal de Arbitraje.',
    'opposition_voice2_chip1' => 'Antecedente del caso ante el PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departamento de Estado de los Estados Unidos — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'El análisis señala: los mapas de distintos años son inconsistentes en la ubicación de la línea; la línea se adentra en tierra firme en lugar de seguir la línea media; y muchos elementos no cumplen los criterios de una "isla" para generar una ZEE.',
    'opposition_voice3_chip1' => 'No reúne los requisitos jurídicos',
    'opposition_voice3_chip2' => 'Análisis oficial',
    'opposition_voice4_year' => 'Académico',
    'opposition_voice4_title' => 'La "zona de aguas históricas" está obsoleta',
    'opposition_voice4_body' => 'Este concepto solo se aplica a bahías y ensenadas cercanas a la costa — no puede abarcar una vasta zona de mar abierto. En 2003, la propia Taiwán también rechazó la política de "zona de aguas históricas" propuesta en 1993.',
    'opposition_voice4_chip1' => 'Incluso los académicos chinos no están de acuerdo',
];
