<?php

return [
    'opposition_index' => 'Oposición',
    'opposition_label' => 'Por qué la comunidad internacional se opone',
    'opposition_title' => 'La oposición se basa en',
    'opposition_title_accent' => 'el derecho, no en las emociones',
    'opposition_lead' => 'Inmediatamente después de que la Línea de nueve guiones fuera presentada ante las Naciones Unidas en 2009, numerosos países y académicos expresaron su oposición mediante argumentos jurídicos concretos.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mayo',
    'opposition_voice1_title' => 'Vietnam · Malasia · Indonesia',
    'opposition_voice1_body' => 'Tan solo un día después de que China presentara el mapa de la Línea de nueve guiones al Secretario General de las Naciones Unidas (7/5/2009), estos países enviaron sucesivamente notas diplomáticas de protesta, rechazando la reclamación.',
    'opposition_voice1_chip1' => 'Nota diplomática de protesta',
    'opposition_voice1_chip2' => 'Incompatible con la UNCLOS de 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinas',
    'opposition_voice2_body' => 'Envió una comunicación diplomática a las Naciones Unidas declarando que las reclamaciones de China en el Mar de China Meridional carecían de fundamento en el derecho internacional, lo que sentó las bases para el posterior caso ante el tribunal arbitral.',
    'opposition_voice2_chip1' => 'Precedente del caso PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departamento de Estado de los Estados Unidos — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'El análisis señaló que los mapas de distintos años eran inconsistentes en la ubicación de la línea; que la línea avanzaba hacia tierra firme en lugar de seguir una línea media; y que numerosas entidades no cumplían los requisitos para ser consideradas “islas” capaces de generar una ZEE.',
    'opposition_voice3_chip1' => 'No cumple los requisitos jurídicos',
    'opposition_voice3_chip2' => 'Análisis oficial',
    'opposition_voice4_year' => 'Ámbito académico',
    'opposition_voice4_title' => 'Las “aguas históricas” son un concepto obsoleto',
    'opposition_voice4_body' => 'Este concepto solo se aplica a bahías y ensenadas cercanas a la costa, y no puede abarcar una vasta extensión de mar abierto. En 2003, la propia Taiwán también rechazó la política de “aguas históricas” que había planteado en 1993.',
    'opposition_voice4_chip1' => 'Incluso los académicos chinos no coinciden',
];
