<?php

return [
    'sovereignty_index' => 'Islas Paracel - Islas Spratly',
    'sovereignty_label' => 'Conclusión inevitable',
    'sovereignty_title' => 'Islas Paracel - Islas Spratly',
    'sovereignty_title_accent' => 'pertenecen a Vietnam',
    'sovereignty_lead' => 'Esta página explica la Línea de nueve guiones. La conclusión responde a la pregunta siguiente: ¿quién tiene la soberanía sobre las dos archipiélagos de Islas Paracel e Islas Spratly? Según la gestión histórica y el derecho internacional, la respuesta constante es Vietnam.',
    'sovereignty_thesis_label' => 'Tesis resumida',
    'sovereignty_thesis_lock1' => 'Sin coordenadas jurídicas',
    'sovereignty_thesis_lock2' => 'Laudo PCA 2016 rechazó',
    'sovereignty_thesis_lock3' => 'Los mapas antiguos no las abarcan',
    'sovereignty_thesis_body' => 'Después de las seis secciones anteriores, tres puntos quedan claros: la Línea de nueve guiones fue trazada a mano, sin coordenadas jurídicas; el Tribunal de Arbitraje de 2016 rechazó la reclamación; y los mapas antiguos de China no abarcan el Mar del Este. La soberanía de Vietnam no se basa en consignas, sino en el hecho de que el Estado vietnamita —desde la época de los señores Nguyễn— administró de manera pacífica y continua cuando ambos archipiélagos aún eran terra nullius.',
    'sovereignty_spine_caption' => 'Hitos de administración continua',
    'sovereignty_spine_title' => 'Una línea de tiempo, sin interrupción',
    'sovereignty_spine_range' => 'Siglo XVII → presente',
    'sovereignty_chron1_year' => 'S. XVII',
    'sovereignty_chron1_title' => 'Equipo Hoàng Sa',
    'sovereignty_chron1_body' => 'Los señores Nguyễn enviaron al equipo Hoàng Sa para explorar, medir rutas marítimas y aprovechar el mar, ejerciendo una gestión efectiva.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Rey Gia Long',
    'sovereignty_chron2_body' => 'Izó la bandera en el archipiélago de Islas Paracel, afirmando la soberanía de Vietnam ante el mundo de la época.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Rey Minh Mạng',
    'sovereignty_chron3_body' => 'Se realizaron mediciones, se erigieron estelas y el archipiélago fue registrado en los mapas oficiales de la corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuidad heredada',
    'sovereignty_chron4_body' => 'Francia la reconoció y continuó administrándola; incorporó Hoàng Sa a la provincia de Thừa Thiên, base para el Estado vietnamita actual.',
    'sovereignty_chron5_year' => 'Presente',
    'sovereignty_chron5_title' => 'Derecho y práctica',
    'sovereignty_chron5_body' => 'Vietnam lo administra conforme a la UNCLOS, mediante la diplomacia y los archivos; la reclamación de la Línea de nueve guiones no puede sustituir esta prueba.',
    'sovereignty_balance_label' => 'Equilibrio de pruebas',
    'sovereignty_balance_medallion_title' => 'Comparación de ambos lados',
    'sovereignty_vn_tag' => 'Lado de Vietnam',
    'sovereignty_vn_title' => 'La soberanía se establece mediante actos',
    'sovereignty_vn_body' => 'La ocupación efectiva cuando la tierra aún era terra nullius, seguida de una administración pública durante siglos —con documentos imperiales, estelas, mapas y expedientes administrativos—. Este enfoque se ajusta a la UNCLOS y a la práctica internacional.',
    'sovereignty_dash_tag' => 'Lado de la Línea de nueve guiones',
    'sovereignty_dash_title' => 'Una reclamación no compensa la evidencia',
    'sovereignty_dash_body' => 'Una línea dibujada en 1948, sin coordenadas, fue rechazada por el PCA en 2016 y contraria a la UNCLOS, como se expuso en las secciones 03 a 06. Por eso, la conclusión sobre la soberanía de los dos archipiélagos no puede basarse en la Línea de nueve guiones.',
    'sovereignty_seal_quote' => 'Vietnam resuelve las disputas por <strong>medios pacíficos</strong>, sobre la base del derecho internacional —especialmente la UNCLOS de 1982—, con el objetivo de un Mar del Este de paz, cooperación y desarrollo.',
    'sovereignty_seal_cite' => 'Posición de Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyecto principal en el mismo ecosistema',
    'sovereignty_next_title' => 'Leer todas las pruebas sobre Islas Paracel - Islas Spratly',
    'sovereignty_next_body' => 'El dossier detallado —documentos, mapas, cronología y argumentos jurídicos— está en <strong>paracelislands.net</strong>, donde se presenta de forma integral el tema de la soberanía de los dos archipiélagos. La página que estás leyendo solo conecta lógicamente la Línea de nueve guiones con esa conclusión.',
    'sovereignty_next_cta' => 'Abrir paracelislands.net',
];
