<?php

return [
    'sovereignty_index' => 'Islas Paracel – Islas Spratly',
    'sovereignty_label' => 'Conclusión inevitable',
    'sovereignty_title' => 'Islas Paracel – Islas Spratly',
    'sovereignty_title_accent' => 'pertenecen a Vietnam',
    'sovereignty_lead' => 'Esta página explica la Línea de nueve guiones. La conclusión responde a la siguiente pregunta: ¿quién tiene soberanía sobre los archipiélagos de las Islas Paracel y las Islas Spratly? Según la historia de administración y el derecho internacional, la respuesta constante es Vietnam.',
    'sovereignty_thesis_label' => 'Tesis integradora',
    'sovereignty_thesis_lock1' => 'Sin coordenadas jurídicas',
    'sovereignty_thesis_lock2' => 'Rechazada por la PCA en 2016',
    'sovereignty_thesis_lock3' => 'Los mapas antiguos no la abarcan',
    'sovereignty_thesis_body' => 'Después de las seis secciones anteriores, tres puntos quedan claros: la Línea de nueve guiones fue trazada a mano y carece de coordenadas jurídicas; el Tribunal Arbitral de 2016 rechazó la reclamación; y los mapas antiguos de la propia China no abarcan el Mar de China Meridional. La soberanía de Vietnam no se basa en consignas, sino en el hecho de que el Estado vietnamita —desde la época de los señores Nguyen— ejerció una administración pacífica y continua cuando ambos archipiélagos aún eran territorios sin dueño.',
    'sovereignty_spine_caption' => 'Hitos de administración continua',
    'sovereignty_spine_title' => 'Una línea temporal ininterrumpida',
    'sovereignty_spine_range' => 'Siglo XVII → actualidad',
    'sovereignty_chron1_year' => 'Siglo XVII',
    'sovereignty_chron1_title' => 'Flotilla Hoang Sa',
    'sovereignty_chron1_body' => 'Los señores Nguyen enviaron la flotilla Hoang Sa para realizar reconocimientos, medir rutas marítimas y explotar recursos en el mar, ejerciendo una administración efectiva.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Emperador Gia Long',
    'sovereignty_chron2_body' => 'Izó la bandera en el archipiélago de las Islas Paracel, afirmando la soberanía de Vietnam ante el mundo de la época.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Emperador Minh Mang',
    'sovereignty_chron3_body' => 'Realizó levantamientos, erigió estelas y registró los archipiélagos en los mapas oficiales de la corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuidad sucesoria',
    'sovereignty_chron4_body' => 'Francia reconoció y continuó la administración; incorporó las Islas Paracel a la provincia de Thua Thien, sentando la base del actual Estado vietnamita.',
    'sovereignty_chron5_year' => 'Actualidad',
    'sovereignty_chron5_title' => 'Derecho y práctica',
    'sovereignty_chron5_body' => 'Vietnam ejerce su administración conforme a la UNCLOS, la diplomacia y los archivos históricos; la reclamación de la Línea de nueve guiones no puede sustituir estas pruebas.',
    'sovereignty_balance_label' => 'Balance de evidencias',
    'sovereignty_balance_medallion_title' => 'Comparación de ambas posiciones',
    'sovereignty_vn_tag' => 'Posición de Vietnam',
    'sovereignty_vn_title' => 'La soberanía se establece mediante actos efectivos',
    'sovereignty_vn_body' => 'Ocupación efectiva cuando los territorios carecían de dueño, seguida de una administración pública durante siglos, respaldada por documentos imperiales, estelas, mapas y registros administrativos. Este enfoque es coherente con la UNCLOS y la práctica internacional.',
    'sovereignty_dash_tag' => 'Posición de la Línea de nueve guiones',
    'sovereignty_dash_title' => 'Una reclamación no puede sustituir la evidencia',
    'sovereignty_dash_body' => 'Una línea trazada en 1948, sin coordenadas, rechazada por la PCA en 2016 y contraria a la UNCLOS, como se ha expuesto en las secciones 03 a 06. Por ello, la conclusión sobre la soberanía de los dos archipiélagos no puede basarse en la Línea de nueve guiones.',
    'sovereignty_seal_quote' => 'Vietnam resuelve las disputas mediante <strong>medios pacíficos</strong>, sobre la base del derecho internacional —especialmente la UNCLOS de 1982— con el objetivo de lograr un Mar de China Meridional pacífico, cooperativo y próspero.',
    'sovereignty_seal_cite' => 'Posición de Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyecto principal dentro del mismo ecosistema',
    'sovereignty_next_title' => 'Consulte la evidencia completa sobre las Islas Paracel – Islas Spratly',
    'sovereignty_next_body' => 'La documentación detallada —fuentes, mapas, cronologías y argumentos jurídicos— se encuentra en <strong>paracelislands.net</strong>, donde se presenta de manera integral la cuestión de la soberanía sobre ambos archipiélagos. La página que está leyendo únicamente conecta la lógica entre la Línea de nueve guiones y esa conclusión.',
    'sovereignty_next_cta' => 'Abrir paracelislands.net',
];
