<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Laudo internacional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'los tres “No”',
    'verdict_lead' => 'El 12/7/2016, la Corte Permanente de Arbitraje (PCA) en La Haya — establecida conforme al Anexo VII de la UNCLOS, en el caso Filipinas contra China — emitió un laudo que rechazó la reclamación de la Línea de nueve guiones. <em>Haz clic en cada tarjeta para leer el texto íntegro.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'derechos históricos',
    'verdict_card1_short' => 'No existe base jurídica para que China alegue derechos históricos sobre los recursos en las aguas situadas dentro de la Línea de nueve guiones.',
    'verdict_card1_quote' => '“No existe fundamento jurídico para que China alegue derechos históricos sobre los recursos situados en las aguas dentro de la Línea de nueve guiones.”',
    'verdict_card1_more' => '+ Leer el laudo',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'entidad que genere ZEE',
    'verdict_card2_short' => 'Ninguna entidad en el archipiélago de Islas Spratly reúne los requisitos para generar una zona económica exclusiva para China, incluida la isla de Ba Bình.',
    'verdict_card2_quote' => '“Ninguna entidad en el archipiélago de Islas Spratly tiene la capacidad de generar una zona económica exclusiva.”',
    'verdict_card2_more' => '+ Leer el laudo',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'conducta lícita',
    'verdict_card3_short' => 'China vulneró los derechos soberanos de Vietnam, obstaculizó la pesca y perjudicó el medio marino.',
    'verdict_card3_quote' => '“China violó los derechos soberanos de Filipinas, intervino en las actividades de pesca en el banco de Scarborough y causó daños graves al entorno de arrecifes de coral.”',
    'verdict_card3_more' => '+ Leer el laudo',
    'verdict_extra1' => 'La Línea de nueve guiones trazada unilateralmente por China <strong>no es compatible</strong> con la UNCLOS de 1982.',
    'verdict_extra2' => 'China ha causado daños al ecosistema de las Islas Spratly mediante la sobreexplotación y la construcción de islas artificiales.',
    'verdict_extra3' => 'Las acciones de China aumentan el riesgo de conflicto con Vietnam.',
    'verdict_extra4' => 'La isla de Ba Bình (controlada por Taiwán) tampoco puede generar una ZEE.',
    'verdict_subtitle' => '¿Por qué entra en conflicto con la UNCLOS?',
    'verdict_subtitle_body' => 'La UNCLOS de 1982 delimita claramente las zonas marítimas sobre la base de las líneas de base del Estado ribereño. La reclamación de la Línea de nueve guiones va más allá de este marco, por lo que no puede superponerse a él.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mar territorial (millas náuticas)',
    'verdict_zone1_body' => 'Zona marítima bajo soberanía del Estado, medida desde la línea de base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona económica exclusiva',
    'verdict_zone2_body' => 'ZEE — el Estado ribereño tiene derechos soberanos sobre los recursos dentro de esta zona.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Plataforma continental (máximo, millas náuticas)',
    'verdict_zone3_body' => 'Derechos sobre los recursos del lecho marino, según las condiciones geológicas determinadas.',
    'verdict_foot' => 'Dentro de este marco, los “derechos históricos” que abarcarían toda una zona de alta mar — como sugiere la Línea de nueve guiones — <em>han sido sustituidos</em> por el régimen jurídico de la UNCLOS, de la que China también es parte.',
];
