<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Laudo internacional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tres “No”',
    'verdict_lead' => 'El 12 de julio de 2016, la Corte Permanente de Arbitraje (PCA) en La Haya — constituida conforme al Anexo VII de la UNCLOS, en el caso presentado por Filipinas contra China — emitió un laudo que rechazó la reclamación de la Línea de nueve guiones. <em>Haga clic en cada tarjeta para leer el texto original.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'derechos históricos',
    'verdict_card1_short' => 'No existe base jurídica para que China invoque derechos históricos sobre los recursos dentro de las aguas comprendidas por la Línea de nueve guiones.',
    'verdict_card1_quote' => '“No existe fundamento jurídico para que China invoque derechos históricos sobre los recursos situados en las aguas dentro de la Línea de nueve guiones.”',
    'verdict_card1_more' => '+ Leer el laudo',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'entidades que generen ZEE',
    'verdict_card2_short' => 'Ninguna entidad de las Islas Spratly reúne las condiciones para generar una zona económica exclusiva para China, incluida la isla Taiping.',
    'verdict_card2_quote' => '“Ninguna entidad de las Islas Spratly tiene la capacidad de generar una zona económica exclusiva.”',
    'verdict_card2_more' => '+ Leer el laudo',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'conducta legal',
    'verdict_card3_short' => 'China violó los derechos soberanos de Filipinas, obstaculizó la pesca y causó daños al medio marino.',
    'verdict_card3_quote' => '“China violó los derechos soberanos de Filipinas, interfirió en las actividades pesqueras en el banco de Scarborough y causó graves daños al medio ambiente de los arrecifes de coral.”',
    'verdict_card3_more' => '+ Leer el laudo',
    'verdict_extra1' => 'La Línea de nueve guiones trazada unilateralmente por China <strong>no es compatible</strong> con la UNCLOS de 1982.',
    'verdict_extra2' => 'China causó daños al ecosistema de las Islas Spratly mediante la explotación excesiva y la construcción de islas artificiales.',
    'verdict_extra3' => 'Las acciones de China aumentaron el riesgo de conflicto con Filipinas.',
    'verdict_extra4' => 'La isla Taiping (controlada por Taiwán) tampoco puede generar una ZEE.',
    'verdict_subtitle' => '¿Por qué entra en conflicto con la UNCLOS?',
    'verdict_subtitle_body' => 'La UNCLOS de 1982 delimita claramente las zonas marítimas basándose en las líneas de base de los Estados costeros. La reclamación de la Línea de nueve guiones excede este marco, por lo que no pueden coexistir jurídicamente.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mar territorial (millas náuticas)',
    'verdict_zone1_body' => 'Zona marítima bajo soberanía estatal, medida desde la línea de base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona económica exclusiva',
    'verdict_zone2_body' => 'ZEE: el Estado costero posee derechos soberanos sobre los recursos dentro de esta zona.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Plataforma continental (máximo, millas náuticas)',
    'verdict_zone3_body' => 'Derechos sobre los recursos del lecho marino, determinados según criterios geológicos.',
    'verdict_foot' => 'Dentro de este marco, los “derechos históricos” que abarcan una vasta zona de alta mar —como implica la Línea de nueve guiones— <em>han sido sustituidos</em> por el régimen jurídico de la UNCLOS, de la cual China también es Estado parte.',
];
