<?php

return [
    'footer_index' => 'Bibliothèque',
    'footer_crest_eyebrow' => 'Clôture de la bibliothèque de la vérité',
    'footer_crest_quote' => '« La paix en mer de Chine méridionale repose sur les fondements du <b>droit international</b>. »',
    'footer_crest_sub' => 'Pas de haine · Seulement la vérité',
    'footer_nav_aria' => 'Actions de fin de page',
    'footer_btn_top' => 'Retour en haut',
    'footer_btn_verdict' => 'Sentence du TPA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Ligne en neuf traits',
    'footer_brand_body' => 'Une page explicative fondée sur des faits objectifs, le droit international et des documents historiques — qui réfute la revendication de la Ligne en neuf traits par des preuves, et non par des slogans.',
    'footer_refs_title' => 'Sources de référence',
    'footer_ref1' => 'Sentence du TPA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — texte intégral',
    'footer_ref3' => 'Limits in the Seas n°143 (US DoS)',
    'footer_ref4' => 'Documents historiques et cartes anciennes',
    'footer_toc_title' => 'Table des matières',
    'footer_toc1' => 'Qu’est-ce que la Ligne en neuf traits',
    'footer_toc2' => 'Origine',
    'footer_toc3' => 'Pourquoi cela suscite la controverse',
    'footer_toc4' => 'Pourquoi la communauté internationale s’y oppose',
    'footer_toc5' => 'Témoin silencieux',
    'footer_toc6' => 'Sentence du TPA 2016',
    'footer_toc7' => 'Îles Paracels – Îles Spratleys',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — La vérité objective sur la mer de Chine méridionale.<br>Écosystème : <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'TPA 2016',
    'footer_chip3' => 'Sans coordonnées',
];
