<?php

return [
    'footer_index' => 'Bibliothèque',
    'footer_crest_eyebrow' => 'Clôture de la bibliothèque des faits',
    'footer_crest_quote' => '« La paix en Mer de Chine méridionale repose sur les fondements du <b>droit international</b>. »',
    'footer_crest_sub' => 'Pas de haine · Seulement la vérité',
    'footer_nav_aria' => 'Actions en bas de page',
    'footer_btn_top' => 'Haut de page',
    'footer_btn_verdict' => 'Sentence de la CPA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Revendication de la Ligne en neuf traits',
    'footer_brand_eyebrow' => 'Page thématique · Souveraineté du Viêt Nam',
    'footer_brand_body' => 'Expliquer la Ligne en neuf traits à travers des faits objectifs, le droit international, la sentence de la CPA 2016 et des documents historiques — en complément des pages approfondies sur la souveraineté des deux archipels <strong>"Îles Paracels et Îles Spratleys"</strong>. Réfuter la revendication irrationnelle de la Chine par l’histoire et les preuves.',
    'footer_refs_title' => 'Sources de référence',
    'footer_ref1' => 'Sentence de la CPA, 12/07/2016',
    'footer_ref2' => 'CNUDM 1982 — texte intégral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documents historiques et cartes anciennes',
    'footer_toc_title' => 'Table des matières',
    'footer_toc1' => 'Qu’est-ce que la Ligne en neuf traits',
    'footer_toc2' => 'Origine',
    'footer_toc3' => 'Pourquoi elle suscite la controverse',
    'footer_toc4' => 'Pourquoi la communauté internationale la rejette',
    'footer_toc5' => 'Témoins silencieux',
    'footer_toc6' => 'Sentence de la CPA 2016',
    'footer_toc7' => 'Îles Paracels – Îles Spratleys',
    'footer_copy_eyebrow' => 'Projet à but non lucratif',
    'footer_copy_title' => 'Les Îles Paracels – Îles Spratleys appartiennent au Viêt Nam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Page thématique sur la Ligne en neuf traits dans l’écosystème de souveraineté du Viêt Nam.',
    'footer_copy_body' => 'Expliquer la revendication de la Ligne en neuf traits à travers <strong>des faits objectifs</strong>, <strong>le droit international</strong>, la sentence de la CPA 2016 et des documents historiques — en complément des pages approfondies sur la souveraineté des deux archipels Îles Paracels et Îles Spratleys.',
    'footer_copy_ecosystem_aria' => 'Pages du même projet',
    'footer_copy_ecosystem_label' => 'Même écosystème',
    'footer_copy_disclaimer' => 'Ce contenu a une vocation éducative et de sensibilisation ; il ne remplace pas la position officielle de l’État du Viêt Nam.',
    'footer_copy' => '<strong>© :year Ligne en neuf traits</strong> — Une partie du projet à but non lucratif <strong>Les Îles Paracels – Îles Spratleys appartiennent au Viêt Nam</strong> au sein du réseau : <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Engagements de contenu du site',
    'footer_chip1' => 'CNUDM 1982',
    'footer_chip2' => 'Sentence de la CPA 2016',
    'footer_chip3' => 'Preuves historiques',
    'footer_chip4' => 'Cartes anciennes',
    'footer_chip5' => 'Faits objectifs',
    'footer_chip6' => 'Paix en Mer de Chine méridionale',
];
