<?php

return [
    'footer_index' => 'Bibliothèque',
    'footer_crest_eyebrow' => 'Clôture de la bibliothèque de la vérité',
    'footer_crest_quote' => '« La paix en mer de Chine méridionale repose sur les fondements du <b>droit international</b>. »',
    'footer_crest_sub' => 'Pas de haine · Seulement la vérité',
    'footer_nav_aria' => 'Actions en bas de page',
    'footer_btn_top' => 'Haut de page',
    'footer_btn_verdict' => 'Sentence de la CPA de 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Revendiquer la Ligne en neuf traits',
    'footer_brand_eyebrow' => 'Page thématique · Souveraineté du Viêt Nam',
    'footer_brand_body' => 'Explication de la Ligne en neuf traits à travers des faits objectifs, le droit international, la sentence de la CPA de 2016 et des documents historiques — en complément des pages approfondies sur la souveraineté des deux archipels <strong>"Îles Paracels et Îles Spratleys"</strong>. Réfutation des revendications déraisonnables de la Chine par l’histoire et les preuves.',
    'footer_refs_title' => 'Sources de référence',
    'footer_ref1' => 'Sentence de la CPA, 12/07/2016',
    'footer_ref2' => 'CNUDM 1982 — texte intégral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documents historiques et cartes anciennes',
    'footer_toc_title' => 'Table des matières',
    'footer_toc1' => 'Qu’est-ce que la Ligne en neuf traits',
    'footer_toc2' => 'Origine',
    'footer_toc3' => 'Pourquoi est-ce विवादé',
    'footer_toc4' => 'Pourquoi la communauté internationale s’y oppose',
    'footer_toc5' => 'Témoins silencieux',
    'footer_toc6' => 'Sentence de la CPA de 2016',
    'footer_toc7' => 'Îles Paracels – Îles Spratleys',
    'footer_copy_eyebrow' => 'Projet à but non lucratif',
    'footer_copy_title' => 'Les Îles Paracels – Îles Spratleys appartiennent au Viêt Nam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Page thématique sur la Ligne en neuf traits au sein de l’écosystème de souveraineté du Viêt Nam.',
    'footer_copy_body' => 'Explication des revendications de la Ligne en neuf traits à travers <strong>des faits objectifs</strong>, <strong>le droit international</strong>, la sentence de la CPA de 2016 et des documents historiques — en complément des pages approfondies sur la souveraineté des deux archipels Paracels et Spratleys.',
    'footer_copy_ecosystem_aria' => 'Pages du même projet',
    'footer_copy_ecosystem_label' => 'Même écosystème',
    'footer_copy_disclaimer' => 'Le contenu a une vocation éducative et de sensibilisation ; il ne remplace pas la position officielle de l’État du Viêt Nam.',
    'footer_copy' => '<strong>© :year Ligne en neuf traits</strong> — Une partie du projet à but non lucratif <strong>Les Îles Paracels – Îles Spratleys appartiennent au Viêt Nam</strong> au sein du système : <a href="https://paracelislands.net/fr" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/fr" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/fr" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/fr" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/fr" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Engagements du site',
    'footer_chip1' => 'CNUDM 1982',
    'footer_chip2' => 'Sentence de la CPA de 2016',
    'footer_chip3' => 'Preuves historiques',
    'footer_chip4' => 'Cartes anciennes',
    'footer_chip5' => 'Faits objectifs',
    'footer_chip6' => 'Paix en mer de Chine méridionale',
];
