<?php

return [
    'nav_logo_name' => 'Ligne en neuf traits',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Ligne en neuf traits',
    'nav_rail_aria' => 'Navigation par section',
    'nav_rail_what' => 'Définition',
    'nav_rail_origin' => 'Origine',
    'nav_rail_dispute' => 'Controverse',
    'nav_rail_opposition' => 'Opposition',
    'nav_rail_witnesses' => 'Cartes anciennes',
    'nav_rail_verdict' => 'CPA 2016',
    'nav_rail_sovereignty' => 'Îles Paracels - Îles Spratleys',
    'nav_sound_off' => 'Activer la musique de fond',
    'nav_sound_on' => 'Désactiver la musique de fond',
    'nav_share' => 'Partager',
    'dialog_title' => 'Langue d’affichage',
    'language' => 'Langue',
    'display_hint' => ':count langues',
    'search_placeholder' => 'Rechercher une langue…',
    'cancel' => 'Annuler',
    'apply' => 'Appliquer',
    'sound_off' => 'Activer le son de fond',
    'sound_on' => 'Désactiver le son de fond',
    'lang_trigger' => 'Choisir une langue',
    'close' => 'Fermer',
    'no_results' => 'Aucune langue trouvée',
    'contribute' => 'Partager',
];
