<?php

return [
    'opposition_index' => 'Opposition',
    'opposition_label' => 'Pourquoi la communauté internationale s’y oppose',
    'opposition_title' => 'Une opposition fondée sur',
    'opposition_title_accent' => 'le droit, et non sur l’émotion',
    'opposition_lead' => 'Dès que la Ligne en neuf traits a été soumise aux Nations Unies en 2009, de nombreux États et universitaires s’y sont opposés — en avançant des arguments juridiques précis.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Viêt Nam · Malaisie · Indonésie',
    'opposition_voice1_body' => 'Un jour seulement après que la Chine a présenté sa carte de la Ligne en neuf traits au Secrétaire général de l’ONU (07/05/2009), ces pays ont successivement envoyé des notes diplomatiques de protestation, rejetant cette revendication.',
    'opposition_voice1_chip1' => 'Note diplomatique de protestation',
    'opposition_voice1_chip2' => 'Incompatible avec la CNUDM de 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippines',
    'opposition_voice2_body' => 'A adressé une lettre diplomatique aux Nations Unies, déclarant que la revendication de la Chine en mer de Chine méridionale était « sans fondement au regard du droit international » — prélude à l’affaire portée ensuite devant le Tribunal arbitral.',
    'opposition_voice2_chip1' => 'Prélude à l’affaire devant le TPA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Département d’État des États-Unis — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'L’analyse montre : les cartes de différentes années sont incohérentes quant à la position de la ligne ; la ligne empiète sur le continent au lieu de suivre la ligne médiane ; de nombreux éléments ne remplissent pas les critères de « rocher » pour avoir une ZEE.',
    'opposition_voice3_chip1' => 'Ne remplit pas les conditions juridiques',
    'opposition_voice3_chip2' => 'Analyse officielle',
    'opposition_voice4_year' => 'Académique',
    'opposition_voice4_title' => 'Le concept de « eaux historiques » est dépassé',
    'opposition_voice4_body' => 'Ce concept ne s’applique qu’aux baies et aux anses côtières — il ne peut pas couvrir une vaste zone de haute mer. En 2003, Taïwan lui-même a également rejeté la politique des « eaux historiques » qu’il avait évoquée en 1993.',
    'opposition_voice4_chip1' => 'Même parmi les universitaires chinois, il n’y a pas de consensus',
];
