<?php

return [
    'sovereignty_index' => 'Îles Paracels – Îles Spratleys',
    'sovereignty_label' => 'Conclusion inévitable',
    'sovereignty_title' => 'Îles Paracels – Îles Spratleys',
    'sovereignty_title_accent' => 'appartiennent au Viêt Nam',
    'sovereignty_lead' => 'Cette page explique la Ligne en neuf traits. La conclusion répond à la question suivante : qui détient la souveraineté sur les deux archipels, les Îles Paracels et les Îles Spratleys ? Au regard de l’histoire de l’administration et du droit international, la réponse cohérente est le Viêt Nam.',
    'sovereignty_thesis_label' => 'Thèse synthétique',
    'sovereignty_thesis_lock1' => 'Aucune coordonnée juridique',
    'sovereignty_thesis_lock2' => 'Le TPIA de 2016 a rejeté',
    'sovereignty_thesis_lock3' => 'Les cartes anciennes ne couvrent pas',
    'sovereignty_thesis_body' => 'Après les six sections ci-dessus, trois points sont clairs : la Ligne en neuf traits est tracée à main levée, sans coordonnées juridiques ; le tribunal arbitral de 2016 a rejeté la revendication ; les cartes anciennes de la Chine elle-même ne couvrent pas la mer de Chine méridionale. La souveraineté du Viêt Nam ne repose pas sur des slogans, mais sur le fait que l’État vietnamien — dès l’époque des seigneurs Nguyễn — a administré de manière pacifique et continue ces deux archipels lorsqu’ils étaient encore terra nullius.',
    'sovereignty_spine_caption' => 'Repères d’une administration continue',
    'sovereignty_spine_title' => 'Une chronologie, sans interruption',
    'sovereignty_spine_range' => 'XVIIe siècle → aujourd’hui',
    'sovereignty_chron1_year' => 'XVIIe s.',
    'sovereignty_chron1_title' => 'L’équipe Hoàng Sa',
    'sovereignty_chron1_body' => 'Les seigneurs Nguyễn envoyaient l’équipe Hoàng Sa pour l’exploration, la mesure des routes maritimes et l’exploitation en mer — exercice concret de l’autorité administrative.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Roi Gia Long',
    'sovereignty_chron2_body' => 'Il fit hisser le drapeau sur les Îles Paracels, affirmant la souveraineté du Viêt Nam aux yeux du monde de son époque.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Roi Minh Mạng',
    'sovereignty_chron3_body' => 'Les îles furent mesurées, des stèles furent érigées, et elles furent inscrites sur les cartes officielles de la cour.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuité de la succession',
    'sovereignty_chron4_body' => 'La France en a reconnu et poursuivi l’administration ; les Îles Paracels furent rattachées à la province de Thừa Thiên — base de l’État vietnamien actuel.',
    'sovereignty_chron5_year' => 'Aujourd’hui',
    'sovereignty_chron5_title' => 'Droit et pratique',
    'sovereignty_chron5_body' => 'Le Viêt Nam administre selon la CNUDM, la diplomatie et les archives ; la revendication de la Ligne en neuf traits ne peut remplacer ces preuves.',
    'sovereignty_balance_label' => 'Équilibre des preuves',
    'sovereignty_balance_medallion_title' => 'Comparaison des deux côtés',
    'sovereignty_vn_tag' => 'Côté Viêt Nam',
    'sovereignty_vn_title' => 'Une souveraineté établie par des actes',
    'sovereignty_vn_body' => 'Une occupation effective lorsque les terres étaient encore vacantes, puis une administration publique sur plusieurs siècles — avec édits royaux, stèles, cartes et dossiers administratifs. Cette approche est conforme à la CNUDM et à la pratique internationale.',
    'sovereignty_dash_tag' => 'Côté Ligne en neuf traits',
    'sovereignty_dash_title' => 'Une revendication ne compense pas l’absence de preuves',
    'sovereignty_dash_body' => 'Une ligne dessinée en 1948, sans coordonnées, a été rejetée par le TPIA de 2016 et est contraire à la CNUDM — comme l’ont montré les sections 03 à 06. C’est pourquoi la conclusion sur la souveraineté des deux archipels ne peut pas reposer sur la Ligne en neuf traits.',
    'sovereignty_seal_quote' => 'Le Viêt Nam règle les différends par des <strong>moyens pacifiques</strong>, sur la base du droit international — en particulier la CNUDM de 1982 — en vue d’une mer de Chine méridionale pacifique, coopérative et propice au développement.',
    'sovereignty_seal_cite' => 'Position du Viêt Nam · CNUDM 1982',
    'sovereignty_next_eyebrow' => 'Projet principal au sein du même écosystème',
    'sovereignty_next_title' => 'Lire l’ensemble des preuves sur les Îles Paracels – Îles Spratleys',
    'sovereignty_next_body' => 'Le dossier détaillé — documents, cartes, chronologie et arguments juridiques — se trouve sur <strong>paracelislands.net</strong>, où le sujet de la souveraineté sur les deux archipels est présenté de manière complète. La page que vous lisez ne fait que relier logiquement la Ligne en neuf traits à cette conclusion.',
    'sovereignty_next_cta' => 'Ouvrir paracelislands.net',
];
