<?php

return [
    'sovereignty_index' => 'Îles Paracels - Îles Spratleys',
    'sovereignty_label' => 'Conclusion inévitable',
    'sovereignty_title' => 'Îles Paracels - Îles Spratleys',
    'sovereignty_title_accent' => 'sont à Viêt Nam',
    'sovereignty_lead' => 'Cette page explique la Ligne en neuf traits. La conclusion répond à la question suivante : qui détient la souveraineté sur les deux archipels des Îles Paracels et des Îles Spratleys ? Au regard de l’histoire de l’administration et du droit international, la réponse constante est Viêt Nam.',
    'sovereignty_thesis_label' => 'Thèse synthétique',
    'sovereignty_thesis_lock1' => 'Aucune base juridique géographique',
    'sovereignty_thesis_lock2' => 'PCA 2016 rejeté',
    'sovereignty_thesis_lock3' => 'Les cartes anciennes ne les couvrent pas',
    'sovereignty_thesis_body' => 'Après les six sections ci-dessus, trois points sont clairs : la Ligne en neuf traits est dessinée à main levée, sans coordonnées juridiques ; la sentence arbitrale de 2016 l’a rejetée ; les cartes anciennes de la Chine elle-même ne couvrent pas la mer de Chine méridionale. La souveraineté du Viêt Nam ne repose pas sur des slogans, mais sur le fait que l’État vietnamien — depuis l’époque des seigneurs Nguyễn — a administré pacifiquement et de manière continue ces deux archipels lorsqu’ils étaient encore terra nullius.',
    'sovereignty_spine_caption' => 'Repères d’une administration continue',
    'sovereignty_spine_title' => 'Une chronologie, sans interruption',
    'sovereignty_spine_range' => 'XVIIe siècle → aujourd’hui',
    'sovereignty_chron1_year' => 'XVIIe s.',
    'sovereignty_chron1_title' => 'L’équipe Hoàng Sa',
    'sovereignty_chron1_body' => 'Les seigneurs Nguyễn ont envoyé l’équipe Hoàng Sa pour prospecter, mesurer les routes maritimes et exploiter en mer — exerçant ainsi une administration effective.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Roi Gia Long',
    'sovereignty_chron2_body' => 'Il a planté le drapeau sur l’archipel des Îles Paracels, affirmant la souveraineté du Viêt Nam aux yeux du monde de l’époque.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Roi Minh Mạng',
    'sovereignty_chron3_body' => 'Il a fait des relevés, érigé des stèles et consigné l’archipel sur les cartes officielles de la cour.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Transmission continue',
    'sovereignty_chron4_body' => 'La France l’a reconnu et l’a administré ensuite ; les Îles Paracels ont été rattachées à la province de Thừa Thiên — une base pour l’État vietnamien actuel.',
    'sovereignty_chron5_year' => 'Aujourd’hui',
    'sovereignty_chron5_title' => 'Droit et pratique',
    'sovereignty_chron5_body' => 'Le Viêt Nam administre selon la CNUDM, par la diplomatie et les archives ; la revendication de la Ligne en neuf traits ne peut pas remplacer ces preuves.',
    'sovereignty_balance_label' => 'Équilibre des preuves',
    'sovereignty_balance_medallion_title' => 'Comparer les deux parties',
    'sovereignty_vn_tag' => 'Côté vietnamien',
    'sovereignty_vn_title' => 'La souveraineté établie par les actes',
    'sovereignty_vn_body' => 'Prise de possession effective lorsque ces terres étaient terra nullius, puis administration publique pendant des siècles — avec édits impériaux, stèles, cartes et dossiers administratifs. Cette méthode est conforme à la CNUDM et à la pratique internationale.',
    'sovereignty_dash_tag' => 'Côté Ligne en neuf traits',
    'sovereignty_dash_title' => 'Une revendication ne comble pas l’absence de preuves',
    'sovereignty_dash_body' => 'Une ligne tracée en 1948, sans coordonnées, rejetée par la PCA en 2016 et contraire à la CNUDM — comme l’ont montré les sections 03 à 06. C’est pourquoi la conclusion sur la souveraineté des deux archipels ne peut pas reposer sur la Ligne en neuf traits.',
    'sovereignty_seal_quote' => 'Le Viêt Nam règle les différends par des <strong>moyens pacifiques</strong>, sur la base du droit international — en particulier la CNUDM de 1982 — afin de construire une mer de Chine méridionale pacifique, coopérative et propice au développement.',
    'sovereignty_seal_cite' => 'Position du Viêt Nam · CNUDM 1982',
    'sovereignty_next_eyebrow' => 'Projet principal dans le même écosystème',
    'sovereignty_next_title' => 'Lire l’ensemble des preuves sur les Îles Paracels - Îles Spratleys',
    'sovereignty_next_body' => 'Le dossier détaillé — documents, cartes, chronologie et arguments juridiques — se trouve sur <strong>paracelislands.net</strong>, où le sujet de la souveraineté des deux archipels est présenté de manière exhaustive. La page que vous lisez ne fait que relier logiquement la Ligne en neuf traits à cette conclusion.',
    'sovereignty_next_cta' => 'Ouvrir paracelislands.net',
];
