<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Sentence internationale',
    'verdict_title' => 'PCA 2016 :',
    'verdict_title_accent' => 'trois « Non »',
    'verdict_lead' => 'Le 12/07/2016, la Cour permanente d\'arbitrage (PCA) à La Haye — instituée en vertu de l\'Annexe VII de la CNUDM, dans l\'affaire opposant les Philippines à la Chine — a rendu une sentence rejetant la revendication de la Ligne en neuf traits. <em>Cliquez sur chaque carte pour lire le texte intégral.</em>',
    'verdict_card1_khong' => 'NON',
    'verdict_card1_title' => 'de droits historiques',
    'verdict_card1_short' => 'Il n’existe aucune base juridique permettant à la Chine d’invoquer des droits historiques sur les ressources situées dans les eaux à l’intérieur de la Ligne en neuf traits.',
    'verdict_card1_quote' => '« Il n’existe aucune base juridique pour que la Chine invoque des droits historiques sur les ressources situées dans les eaux à l’intérieur de la Ligne en neuf traits. »',
    'verdict_card1_more' => '+ Lire la sentence',
    'verdict_card2_khong' => 'NON',
    'verdict_card2_title' => 'd\'entité créant une ZEE',
    'verdict_card2_short' => 'Aucune entité des Îles Spratleys ne remplit les conditions pour créer une zone économique exclusive pour la Chine — y compris l’île Ba Bình.',
    'verdict_card2_quote' => '« Aucune entité des Îles Spratleys n’est en mesure de créer une zone économique exclusive. »',
    'verdict_card2_more' => '+ Lire la sentence',
    'verdict_card3_khong' => 'NON',
    'verdict_card3_title' => 'de conduite légale',
    'verdict_card3_short' => 'La Chine a violé les droits souverains des Philippines, entravé la pêche et porté atteinte au milieu marin.',
    'verdict_card3_quote' => '« La Chine a violé les droits souverains des Philippines, interféré avec les activités de pêche au récif de Scarborough et causé de graves dommages à l’environnement récifal. »',
    'verdict_card3_more' => '+ Lire la sentence',
    'verdict_extra1' => 'La Ligne en neuf traits tracée unilatéralement par la Chine <strong>n’est pas conforme</strong> à la CNUDM de 1982.',
    'verdict_extra2' => 'La Chine a causé des dommages à l’écosystème des Îles Spratleys par la surexploitation et la construction d’îles artificielles.',
    'verdict_extra3' => 'Les actions de la Chine ont accru le risque de conflit avec les Philippines.',
    'verdict_extra4' => 'L’île Ba Bình (contrôlée par Taïwan) ne peut pas non plus créer une ZEE.',
    'verdict_subtitle' => 'Pourquoi cela entre-t-il en conflit avec la CNUDM ?',
    'verdict_subtitle_body' => 'La CNUDM de 1982 délimite clairement les zones maritimes sur la base des lignes de base de l’État côtier. La revendication de la Ligne en neuf traits dépasse ce cadre et ne peut donc pas être conciliée avec celui-ci.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mer territoriale (milles marins)',
    'verdict_zone1_body' => 'Zone maritime relevant de la souveraineté de l’État, mesurée à partir de la ligne de base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zone économique exclusive',
    'verdict_zone2_body' => 'ZEE — dans cette zone, l’État côtier détient des droits souverains sur les ressources.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Plateau continental (maximum, milles marins)',
    'verdict_zone3_body' => 'Droits sur les ressources du fond marin, selon les conditions géologiques déterminées.',
    'verdict_foot' => 'Dans ce cadre, les « droits historiques » englobant une vaste zone de haute mer — comme l’implique la Ligne en neuf traits — <em>ont été remplacés</em> par le régime juridique de la CNUDM, dont la Chine est elle-même partie.',
];
