<?php

return [
    'witnesses_index' => 'Cartes anciennes',
    'witnesses_label' => 'Cartes anciennes de Chine',
    'witnesses_title' => 'Ne s’étend qu’au sud jusqu’à',
    'witnesses_title_accent' => 'l’île de Hainan',
    'witnesses_lead' => 'Les cartes anciennes dessinées par des auteurs chinois — classées chronologiquement — montrent toutes <em>l’île de Hainan comme l’extrême sud</em> de la Chine, sans les Îles Paracels ni les Îles Spratleys. Documentation synthétisée d’après <em>La souveraineté nationale du Viêt Nam sur les deux archipels des Îles Paracels et des Îles Spratleys</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Examiner à la loupe',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— extrémité sud du territoire —',
    'witnesses_map1_svg_era' => 'Dynastie Song · 1136',
    'witnesses_map1_title' => 'Carte de la dynastie Song, 1136',
    'witnesses_map1_body' => 'Le territoire de la Chine s’arrêtait à l’île de Hainan — les Îles Paracels et les Îles Spratleys se trouvaient hors de ses limites.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'limite d’Anville',
    'witnesses_map2_svg_era' => 'd’Anville · 1735',
    'witnesses_map2_title' => 'Carte de d’Anville, 1735',
    'witnesses_map2_body' => 'Dressée par J.-B. B. d’Anville ; une copie de 1740 fut offerte au dirigeant chinois par le chancelier allemand. Le territoire des Qing s’arrêtait à Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"extrémité sud de la Chine"',
    'witnesses_map3_svg_era' => 'Atlas géographique complet des provinces sous la dynastie impériale · 1904',
    'witnesses_map3_title' => 'Atlas géographique complet des provinces sous la dynastie impériale',
    'witnesses_map3_body' => 'Imprimé sous les Qing — il indique clairement que l’extrémité sud du territoire de la Chine est l’île de Hainan.',
    'witnesses_quote' => 'Les propres cartes publiées par la Chine n’ont jamais placé les Îles Paracels — Îles Spratleys dans leur territoire.',
    'witnesses_timeline_aria' => 'Chronologie des cartes anciennes chinoises',
    'witnesses_year_aria' => 'Date',
    'lightbox_aria' => 'Voir l’image en grand',
    'lightbox_close' => 'Fermer',
    'lightbox_prev' => 'Image précédente',
    'lightbox_next' => 'Image suivante',
];
