<?php

return [
    'footer_index' => 'Knihovna',
    'footer_crest_eyebrow' => 'Závěr knihovny pravdy',
    'footer_crest_quote' => '„Mír v Jihočínském moři je vybudován na základech <b>mezinárodního práva</b>."',
    'footer_crest_sub' => 'Žádná nenávist · Jen pravda',
    'footer_nav_aria' => 'Akce v patičce',
    'footer_btn_top' => 'Na začátek stránky',
    'footer_btn_verdict' => 'Rozhodnutí PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Čára devíti čárek',
    'footer_brand_body' => 'Stránka vysvětlující na základě objektivní pravdy, mezinárodního práva a historických materiálů — vyvrací nároky Čáry devíti čárek důkazy, nikoli slogany.',
    'footer_refs_title' => 'Referenční zdroje',
    'footer_ref1' => 'Rozhodnutí PCA, 12. 7. 2016',
    'footer_ref2' => 'Úmluva OSN o mořském právu z roku 1982 — úplné znění',
    'footer_ref3' => 'Limits in the Seas č. 143 (US DoS)',
    'footer_ref4' => 'Historické materiály a staré mapy',
    'footer_toc_title' => 'Obsah stránky',
    'footer_toc1' => 'Co je Čára devíti čárek',
    'footer_toc2' => 'Původ',
    'footer_toc3' => 'Proč je to sporné',
    'footer_toc4' => 'Proč je mezinárodně odmítána',
    'footer_toc5' => 'Tichí svědci',
    'footer_toc6' => 'Rozhodnutí PCA 2016',
    'footer_toc7' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektivní pravda o Jihočínském moři.<br>Ekosystém: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Bez souřadnic',
];
