<?php

return [
    'footer_index' => 'Knihovna',
    'footer_crest_eyebrow' => 'Závěr knihovny faktů',
    'footer_crest_quote' => '„Mír v Jihočínském moři je vybudován na základě <b>mezinárodního práva</b>."',
    'footer_crest_sub' => 'Žádná nenávist · Jen pravda',
    'footer_nav_aria' => 'Akce v patičce',
    'footer_btn_top' => 'Zpět nahoru',
    'footer_btn_verdict' => 'Rozhodnutí PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Nárok na Čáru devíti čárek',
    'footer_brand_eyebrow' => 'Tematická stránka · Suverenita Vietnamu',
    'footer_brand_body' => 'Vysvětlení Čáry devíti čárek prostřednictvím objektivních faktů, mezinárodního práva, rozhodnutí PCA z roku 2016 a historických materiálů — doplnění podrobných stránek o suverenitě obou souostroví <strong>"Paracelské ostrovy a Spratlyho ostrovy"</strong>. Vyvrací neopodstatněný nárok Číny pomocí historie a důkazů.',
    'footer_refs_title' => 'Reference',
    'footer_ref1' => 'Rozhodnutí PCA, 12. 7. 2016',
    'footer_ref2' => 'UNCLOS 1982 — úplné znění',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historické materiály a staré mapy',
    'footer_toc_title' => 'Obsah stránky',
    'footer_toc1' => 'Co je Čára devíti čárek',
    'footer_toc2' => 'Původ',
    'footer_toc3' => 'Proč je sporná',
    'footer_toc4' => 'Proč ji mezinárodní společenství odmítá',
    'footer_toc5' => 'Tichí svědkové',
    'footer_toc6' => 'Rozhodnutí PCA 2016',
    'footer_toc7' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'footer_copy_eyebrow' => 'Neziskový projekt',
    'footer_copy_title' => 'Paracelské ostrovy – Spratlyho ostrovy patří Vietnamu',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Tematická stránka o Čáře devíti čárek v rámci vietnamského ekosystému suverenity.',
    'footer_copy_body' => 'Vysvětlení nároku na Čáru devíti čárek prostřednictvím <strong>objektivních faktů</strong>, <strong>mezinárodního práva</strong>, rozhodnutí PCA z roku 2016 a historických materiálů — doplnění podrobných stránek o suverenitě souostroví Paracelské ostrovy a Spratlyho ostrovy.',
    'footer_copy_ecosystem_aria' => 'Stránky stejného projektu',
    'footer_copy_ecosystem_label' => 'Stejný ekosystém',
    'footer_copy_disclaimer' => 'Obsah slouží k vzdělávání a zvýšení povědomí; nenahrazuje oficiální stanovisko vietnamského státu.',
    'footer_copy' => '<strong>© :year Čára devíti čárek</strong> — Součást neziskového projektu <strong>Paracelské ostrovy – Spratlyho ostrovy patří Vietnamu</strong> v rámci systému: <a href="https://paracelislands.net/cs" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/cs" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/cs" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/cs" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/cs" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Závazky obsahu stránky',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Rozhodnutí PCA 2016',
    'footer_chip3' => 'Historické důkazy',
    'footer_chip4' => 'Staré mapy',
    'footer_chip5' => 'Objektivní fakta',
    'footer_chip6' => 'Mír v Jihočínském moři',
];
