<?php

return [
    'nav_logo_name' => 'Čára devíti čárek',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Čára devíti čárek',
    'nav_rail_aria' => 'Navigace podle sekcí',
    'nav_rail_what' => 'Definice',
    'nav_rail_origin' => 'Původ',
    'nav_rail_dispute' => 'Spory',
    'nav_rail_opposition' => 'Opozice',
    'nav_rail_witnesses' => 'Staré mapy',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'nav_sound_off' => 'Zapnout hudbu na pozadí',
    'nav_sound_on' => 'Vypnout hudbu na pozadí',
    'nav_share' => 'Sdílet',
    'dialog_title' => 'Jazyk zobrazení',
    'language' => 'Jazyk',
    'display_hint' => ':count jazyků',
    'search_placeholder' => 'Hledat jazyk…',
    'cancel' => 'Zrušit',
    'apply' => 'Použít',
    'sound_off' => 'Zapnout zvuk na pozadí',
    'sound_on' => 'Vypnout zvuk na pozadí',
    'lang_trigger' => 'Vybrat jazyk',
    'close' => 'Zavřít',
    'no_results' => 'Jazyk nenalezen',
    'contribute' => 'Sdílet',
];
