<?php

return [
    'opposition_index' => 'Protest',
    'opposition_label' => 'Proč mezinárodní společenství protestuje',
    'opposition_title' => 'Opozice založená na',
    'opposition_title_accent' => 'právu, ne na emocích',
    'opposition_lead' => 'Krátce poté, co byla Čára devíti čárek předložena OSN v roce 2009, mnoho států a akademiků se proti ní postavilo — s konkrétními právními argumenty.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Květen',
    'opposition_voice1_title' => 'Vietnam · Malajsie · Indonésie',
    'opposition_voice1_body' => 'Již den poté, co Čína předložila mapu Čáry devíti čárek generálnímu tajemníkovi OSN (7. 5. 2009), tyto země postupně zaslaly protestní diplomatické nóty a odmítly tento nárok.',
    'opposition_voice1_chip1' => 'Protestní nóta',
    'opposition_voice1_chip2' => 'V rozporu s UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipíny',
    'opposition_voice2_body' => 'Zaslaly diplomatický dopis OSN a prohlásily, že nárok Číny v Jihočínském moři je „bez opory v mezinárodním právu“ — což se stalo předpokladem pro následný případ u arbitrážního tribunálu.',
    'opposition_voice2_chip1' => 'Předpoklad případu u PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministerstvo zahraničí USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analýza ukázala: mapy z různých let jsou nekonzistentní v poloze linie; linie zasahuje do pevniny namísto vedení střední linií; mnoho útvarů nesplňuje kritéria pro „ostrov“ a nemůže mít EEZ.',
    'opposition_voice3_chip1' => 'Nesplňuje právní podmínky',
    'opposition_voice3_chip2' => 'Oficiální analýza',
    'opposition_voice4_year' => 'Akademické',
    'opposition_voice4_title' => '„Historické vody“ jsou zastaralé',
    'opposition_voice4_body' => 'Tento koncept se vztahuje jen na zálivy a pobřežní vody těsně u břehu — nemůže pokrývat celé rozlehlé volné moře. V roce 2003 i samotný Tchaj-wan odmítl politiku „historických vod“, kterou dříve uvedl v roce 1993.',
    'opposition_voice4_chip1' => 'Ani čínští akademici se neshodují',
];
