<?php

return [
    'opposition_index' => 'Opozice',
    'opposition_label' => 'Proč mezinárodní společenství odporuje',
    'opposition_title' => 'Opozice založená na',
    'opposition_title_accent' => 'právu, ne na emocích',
    'opposition_lead' => 'Bezprostředně poté, co byla Čára devíti čárek předložena Organizaci spojených národů v roce 2009, mnoho států a akademiků vzneslo námitky — s konkrétními právními argumenty.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'květen',
    'opposition_voice1_title' => 'Vietnam · Malajsie · Indonésie',
    'opposition_voice1_body' => 'Již jeden den poté, co Čína předložila mapu Čáry devíti čárek generálnímu tajemníkovi OSN (7. 5. 2009), tyto země postupně zaslaly protestní nóty a odmítly tento nárok.',
    'opposition_voice1_chip1' => 'Protestní nóta',
    'opposition_voice1_chip2' => 'Není v souladu s Úmluvou UNCLOS z roku 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipíny',
    'opposition_voice2_body' => 'Zaslala diplomatický dopis OSN a prohlásila, že nárok Číny v Jihočínském moři je „bez opory v mezinárodním právu“ — což se stalo předpokladem pro následnou arbitrážní žalobu.',
    'opposition_voice2_chip1' => 'Předpoklad pro řízení před PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministerstvo zahraničí USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analýza ukázala: mapy z různých let se neshodují v poloze linií; linie zasahuje do pevniny místo toho, aby vycházela z prostřední linie; mnoho útvarů nesplňuje kritéria „ostrova“ pro vznik EEZ.',
    'opposition_voice3_chip1' => 'Nesplňuje právní podmínky',
    'opposition_voice3_chip2' => 'Oficiální analýza',
    'opposition_voice4_year' => 'Akademická sféra',
    'opposition_voice4_title' => '„Historické vody“ jsou zastaralé',
    'opposition_voice4_body' => 'Tento koncept se vztahuje pouze na zálivy a příbřežní vody — nelze jím pokrýt celé rozsáhlé otevřené moře. V roce 2003 Tchaj-wan sám odmítl politiku „historických vod“, kterou uvedl v roce 1993.',
    'opposition_voice4_chip1' => 'Ani čínští akademici se neshodují',
];
