<?php

return [
    'sovereignty_index' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_label' => 'Nezbytný závěr',
    'sovereignty_title' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_title_accent' => 'patří Vietnamu',
    'sovereignty_lead' => 'Tato stránka vysvětluje Čáru devíti čárek. Závěr odpovídá na další otázku: kdo má svrchovanost nad dvěma souostrovími, Paracelskými ostrovy a Spratlyho ostrovy? Podle historické správy a mezinárodního práva je konzistentní odpověď Vietnam.',
    'sovereignty_thesis_label' => 'Souhrnný argument',
    'sovereignty_thesis_lock1' => 'Žádné právní souřadnice',
    'sovereignty_thesis_lock2' => 'PCA 2016 odmítl',
    'sovereignty_thesis_lock3' => 'Staré mapy je nepokrývají',
    'sovereignty_thesis_body' => 'Po šesti výše uvedených částech jsou jasné tři body: Čára devíti čárek byla nakreslena ručně, nemá právní souřadnice; rozhodčí tribunál v roce 2016 nárok odmítl; staré mapy samotné Číny Jihočínské moře nepokrývají. Svrchovanost Vietnamu nestojí na sloganech, ale na tom, že vietnamský stát — od doby panovníků z rodu Nguyễn — obě souostroví pokojně a nepřetržitě spravoval v době, kdy byla ještě zemí nikoho.',
    'sovereignty_spine_caption' => 'Milník nepřetržité správy',
    'sovereignty_spine_title' => 'Jedna časová osa, bez přerušení',
    'sovereignty_spine_range' => '17. století → současnost',
    'sovereignty_chron1_year' => '17. stol.',
    'sovereignty_chron1_title' => 'Jednotka Hoàng Sa',
    'sovereignty_chron1_body' => 'Panovníci z rodu Nguyễn vysílali jednotku Hoàng Sa k průzkumu, měření plavebních tras a využívání moře — čímž vykonávali faktickou správu.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Král Gia Long',
    'sovereignty_chron2_body' => 'Vztyčil vlajku na Paracelských ostrovech a potvrdil svrchovanost Vietnamu před tehdejším světem.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Král Minh Mạng',
    'sovereignty_chron3_body' => 'Nechal ostrovy zaměřit, vztyčit stély a zaznamenat je na oficiálních mapách dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Nepřetržité dědictví',
    'sovereignty_chron4_body' => 'Francie uznala a pokračovala ve správě; Paracelské ostrovy byly začleněny do provincie Thừa Thiên — což tvoří základ dnešního vietnamského státu.',
    'sovereignty_chron5_year' => 'Dnes',
    'sovereignty_chron5_title' => 'Právo a praxe',
    'sovereignty_chron5_body' => 'Vietnam spravuje věc v souladu s UNCLOS, diplomacií a archivními dokumenty; nárok Čáry devíti čárek tyto důkazy nemůže nahradit.',
    'sovereignty_balance_label' => 'Vyvážení důkazů',
    'sovereignty_balance_medallion_title' => 'Srovnání obou stran',
    'sovereignty_vn_tag' => 'Strana Vietnamu',
    'sovereignty_vn_title' => 'Svrchovanost je založena na činech',
    'sovereignty_vn_body' => 'Skutečné obsazení v době, kdy byla země nikoho, a poté veřejná správa po staletí — s císařskými dokumenty, stélami, mapami a správními záznamy. Tento postup je v souladu s UNCLOS i mezinárodní praxí.',
    'sovereignty_dash_tag' => 'Strana Čáry devíti čárek',
    'sovereignty_dash_title' => 'Nárok nemůže nahradit důkazy',
    'sovereignty_dash_body' => 'Jedna linie nakreslená v roce 1948, bez souřadnic, byla v roce 2016 PCA odmítnuta a je v rozporu s UNCLOS — jak bylo uvedeno v částech 03 až 06. Proto závěr o svrchovanosti nad oběma souostrovími nemůže stát na Čáře devíti čárek.',
    'sovereignty_seal_quote' => 'Vietnam řeší spory <strong>mírovými prostředky</strong>, na základě mezinárodního práva — zejména UNCLOS 1982 — s cílem dosáhnout Jihočínského moře míru, spolupráce a rozvoje.',
    'sovereignty_seal_cite' => 'Postoj Vietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hlavní projekt v rámci stejného ekosystému',
    'sovereignty_next_title' => 'Přečtěte si úplné důkazy o Paracelských ostrovech – Spratlyho ostrovech',
    'sovereignty_next_body' => 'Podrobné materiály — dokumenty, mapy, časová osa a právní argumenty — jsou na stránce <strong>paracelislands.net</strong>, která komplexně představuje téma svrchovanosti nad oběma souostrovími. Stránka, kterou právě čtete, pouze propojuje logiku od Čáry devíti čárek k tomuto závěru.',
    'sovereignty_next_cta' => 'Otevřít paracelislands.net',
];
