<?php

return [
    'sovereignty_index' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_label' => 'Nezbytný závěr',
    'sovereignty_title' => 'Paracelské ostrovy – Spratlyho ostrovy',
    'sovereignty_title_accent' => 'patří Vietnamu',
    'sovereignty_lead' => 'Tato stránka vysvětluje Čáru devíti čárek. Závěrečná část odpovídá na další otázku: kdo má svrchovanost nad dvěma souostrovími, Paracelskými ostrovy a Spratlyho ostrovy? Podle historické správy a mezinárodního práva je konzistentní odpověď Vietnam.',
    'sovereignty_thesis_label' => 'Shrnutý argument',
    'sovereignty_thesis_lock1' => 'Žádná právní koordinace',
    'sovereignty_thesis_lock2' => 'PCA 2016 zamítl',
    'sovereignty_thesis_lock3' => 'Staré mapy nezahrnují',
    'sovereignty_thesis_body' => 'Po šesti výše uvedených částech jsou tři věci jasné: Čára devíti čárek je nakreslená rukou, nemá právní souřadnice; Rozhodčí soud v roce 2016 nároky zamítl; staré mapy samotné Číny nezahrnují Jihočínské moře. Vietnamská suverenita nestojí na sloganech, ale na tom, že vietnamský stát — od doby vlád Nguyenů — tato dvě souostroví pokojně a nepřetržitě spravoval, když šlo ještě o terra nullius.',
    'sovereignty_spine_caption' => 'Milníky nepřetržité správy',
    'sovereignty_spine_title' => 'Jedna časová osa, bez přerušení',
    'sovereignty_spine_range' => '17. století → současnost',
    'sovereignty_chron1_year' => '17. stol.',
    'sovereignty_chron1_title' => 'Tým Hoang Sa',
    'sovereignty_chron1_body' => 'Vládci Nguyenové vysílali tým Hoang Sa k průzkumu, měření plavebních tras a využívání moře — šlo o výkon faktické správy.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Císař Gia Long',
    'sovereignty_chron2_body' => 'Vztyčil vlajku na Paracelských ostrovech a potvrdil svrchovanost Vietnamu před tehdejším světem.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Císař Minh Mang',
    'sovereignty_chron3_body' => 'Nechal ostrovy zaměřit, postavit stély a zaznamenat je na oficiálních mapách dvora.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuita nástupnictví',
    'sovereignty_chron4_body' => 'Francie je uznala a pokračovala ve správě; začlenila Paracelské ostrovy do provincie Thừa Thiên — to vytvořilo základ pro dnešní vietnamský stát.',
    'sovereignty_chron5_year' => 'Současnost',
    'sovereignty_chron5_title' => 'Právo a praxe',
    'sovereignty_chron5_body' => 'Vietnam spravuje v souladu s UNCLOS, diplomacií a archivními záznamy; nárok Čáry devíti čárek tyto důkazy nemůže nahradit.',
    'sovereignty_balance_label' => 'Vyvážení důkazů',
    'sovereignty_balance_medallion_title' => 'Srovnání obou stran',
    'sovereignty_vn_tag' => 'Vietnamská strana',
    'sovereignty_vn_title' => 'Svrchovanost prokázaná jednáním',
    'sovereignty_vn_body' => 'Skutečné obsazení v době, kdy šlo o neobsazené území, a poté po staletí veřejná správa — s císařskými dokumenty, stélami, mapami a správními záznamy. Tento postup je v souladu s UNCLOS i mezinárodní praxí.',
    'sovereignty_dash_tag' => 'Strana Čáry devíti čárek',
    'sovereignty_dash_title' => 'Nárok nemůže nahradit důkaz',
    'sovereignty_dash_body' => 'Jedna čára nakreslená v roce 1948, bez souřadnic, byla zamítnuta PCA v roce 2016 a je v rozporu s UNCLOS — jak ukázaly části 03 až 06. Proto závěr o svrchovanosti nad oběma souostrovími nemůže vycházet z Čáry devíti čárek.',
    'sovereignty_seal_quote' => 'Vietnam řeší spory <strong>mírovými prostředky</strong>, na základě mezinárodního práva — zejména Úmluvy UNCLOS z roku 1982 — s cílem dosáhnout Jihočínského moře mírového, spolupracujícího a rozvíjejícího se.',
    'sovereignty_seal_cite' => 'Postoj Vietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hlavní projekt ve stejném ekosystému',
    'sovereignty_next_title' => 'Přečtěte si úplné důkazy o Paracelských a Spratlyho ostrovech',
    'sovereignty_next_body' => 'Podrobné materiály — dokumenty, mapy, časová osa a právní argumentace — jsou na stránce <strong>paracelislands.net</strong>, která komplexně představuje téma svrchovanosti nad oběma souostrovími. Stránka, kterou právě čtete, pouze logicky propojuje Čáru devíti čárek s tímto závěrem.',
    'sovereignty_next_cta' => 'Otevřít paracelislands.net',
];
