<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Mezinárodní rozhodnutí',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tři „ne“',
    'verdict_lead' => 'Dne 12. 7. 2016 vydal Stálý rozhodčí soud (PCA) v Haagu — zřízený podle přílohy VII Úmluvy OSN o mořském právu (UNCLOS) ve věci Filipíny proti Číně — rozhodnutí, jímž odmítl nárok na Čáru devíti čárek. <em>Klikněte na každou kartu pro přečtení úplného znění.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'historické právo',
    'verdict_card1_short' => 'Neexistuje právní základ, aby Čína uplatňovala historické právo k zdrojům ve vodách ležících uvnitř Čáry devíti čárek.',
    'verdict_card1_quote' => '„Neexistuje žádný právní základ pro to, aby Čína uplatňovala historická práva k přírodním zdrojům ve vodách uvnitř Čáry devíti čárek.“',
    'verdict_card1_more' => '+ Přečíst rozhodnutí',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'prvek vytvářející EEZ',
    'verdict_card2_short' => 'Žádný prvek na Spratlyho ostrovech nesplňuje podmínky pro vytvoření výlučné ekonomické zóny pro Čínu — včetně ostrova Ba Bình.',
    'verdict_card2_quote' => '„Žádný prvek na Spratlyho ostrovech nemá schopnost vytvořit výlučnou ekonomickou zónu.“',
    'verdict_card2_more' => '+ Přečíst rozhodnutí',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'zákonné jednání',
    'verdict_card3_short' => 'Čína porušila svrchovaná práva Vietnamu, bránila rybolovu a poškodila mořské prostředí.',
    'verdict_card3_quote' => '„Čína porušila svrchovaná práva Vietnamu, zasahovala do rybolovných činností u Scarboroughského útesu a závažně poškodila prostředí korálových útesů.“',
    'verdict_card3_more' => '+ Přečíst rozhodnutí',
    'verdict_extra1' => 'Čára devíti čárek, jak ji sama nakreslila Čína, <strong>není v souladu</strong> s UNCLOS z roku 1982.',
    'verdict_extra2' => 'Čína poškozuje ekosystém Spratlyho ostrovů nadměrným využíváním a budováním umělých ostrovů.',
    'verdict_extra3' => 'Jednání Číny zvyšuje riziko konfliktu s Vietnamem.',
    'verdict_extra4' => 'Ostrov Ba Bình (pod kontrolou Tchaj-wanu) rovněž nemůže vytvořit EEZ.',
    'verdict_subtitle' => 'Proč je to v rozporu s UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS z roku 1982 jasně vymezuje mořské zóny podle základní linie pobřežního státu. Nárok na Čáru devíti čárek tento rámec přesahuje, a proto je nelze klást vedle sebe.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoriální moře (míle)',
    'verdict_zone1_body' => 'Mořské pásmo státu pod jeho svrchovaností, měřené od základní linie.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Výlučná ekonomická zóna',
    'verdict_zone2_body' => 'EEZ — pobřežní stát má v tomto pásmu svrchovaná práva k přírodním zdrojům.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentální šelf (max., míle)',
    'verdict_zone3_body' => 'Práva k zdrojům mořského dna podle stanovených geologických podmínek.',
    'verdict_foot' => 'V tomto rámci „historické právo“ pokrývající celé volné moře — jak implikuje Čára devíti čárek — <em>bylo nahrazeno</em> právním režimem UNCLOS, jehož je Čína sama smluvní stranou.',
];
