<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Mezinárodní rozsudek',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tři „ne“',
    'verdict_lead' => 'Dne 12. 7. 2016 vydal Stálý rozhodčí soud (PCA) v Haagu — zřízený podle Přílohy VII Úmluvy UNCLOS, ve věci Filipíny proti Číně — rozsudek, který zamítl nárok Čáry devíti čárek. <em>Klepněte na každou kartu pro přečtení plného znění.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'historické právo',
    'verdict_card1_short' => 'Neexistuje právní základ, aby Čína uplatňovala historická práva k přírodním zdrojům v mořské oblasti uvnitř Čáry devíti čárek.',
    'verdict_card1_quote' => '„Neexistuje žádný právní základ pro to, aby Čína uplatňovala historická práva k přírodním zdrojům v mořské oblasti uvnitř Čáry devíti čárek.“',
    'verdict_card1_more' => '+ Přečíst rozsudek',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'entita vytvářející EEZ',
    'verdict_card2_short' => 'Žádný útvar na Spratlyho ostrovech nesplňuje podmínky pro vytvoření výlučné ekonomické zóny pro Čínu — včetně ostrova Pching-tchej.',
    'verdict_card2_quote' => '„Žádný útvar na Spratlyho ostrovech není schopen vytvořit výlučnou ekonomickou zónu.“',
    'verdict_card2_more' => '+ Přečíst rozsudek',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'zákonné jednání',
    'verdict_card3_short' => 'Čína porušila svrchovaná práva Filipín, bránila rybolovu a poškodila mořské prostředí.',
    'verdict_card3_quote' => '„Čína porušila svrchovaná práva Filipín, zasahovala do rybolovu u Scarboroughského útesu a způsobila vážné škody korálovému mořskému prostředí.“',
    'verdict_card3_more' => '+ Přečíst rozsudek',
    'verdict_extra1' => 'Čára devíti čárek, kterou si Čína sama nakreslila, <strong>není v souladu</strong> s UNCLOS z roku 1982.',
    'verdict_extra2' => 'Čína poškozuje ekosystém Spratlyho ostrovů nadměrnou těžbou a umělým rozšiřováním ostrovů.',
    'verdict_extra3' => 'Jednání Číny zvyšuje riziko konfliktu s Filipínami.',
    'verdict_extra4' => 'Ostrov Pching-tchej (pod kontrolou Tchaj-wanu) rovněž nemůže vytvořit EEZ.',
    'verdict_subtitle' => 'Proč je to v rozporu s UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 jasně vymezuje jednotlivé mořské zóny na základě základní linie pobřežního státu. Nárok Čáry devíti čárek tento rámec přesahuje, a proto jej nelze uvést do souladu.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritoriální moře (námořní míle)',
    'verdict_zone1_body' => 'Mořská oblast pod svrchovaností státu, měřená od základní linie.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Výlučná ekonomická zóna',
    'verdict_zone2_body' => 'EEZ — pobřežní stát má v tomto prostoru svrchovaná práva k přírodním zdrojům.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentální šelf (max., námořní míle)',
    'verdict_zone3_body' => 'Práva k zdrojům mořského dna podle stanovených geologických podmínek.',
    'verdict_foot' => 'V tomto rámci bylo „historické právo“, které by zahrnovalo rozsáhlou otevřenou mořskou oblast — jak naznačuje Čára devíti čárek — <em>nahrazeno</em> právním režimem UNCLOS, jehož je Čína sama smluvní stranou.',
];
