<?php

return [
    'witnesses_index' => 'Starověké mapy',
    'witnesses_label' => 'Starověké mapy Číny',
    'witnesses_title' => 'Nejjižněji až k',
    'witnesses_title_accent' => 'ostrovu Chaj-nan',
    'witnesses_lead' => 'Starověké mapy vytvořené čínskými autory — seřazené chronologicky — všechny ukazují <em>ostrov Chaj-nan jako nejjižnější</em> část Číny, bez Paracelských ostrovů ani Spratlyho ostrovů. Podklady jsou zpracovány podle díla <em>Státní svrchovanost Vietnamu nad dvěma souostrovími Hoàng Sa a Trường Sa</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Přiblížit lupou',
    'witnesses_map1_svg_hainan' => 'Chaj-nan 海南',
    'witnesses_map1_svg_south' => '— nejjižnější bod území —',
    'witnesses_map1_svg_era' => 'Dynastie Sung · 1136',
    'witnesses_map1_title' => 'Mapa z období dynastie Sung, 1136',
    'witnesses_map1_body' => 'Území Číny končilo na ostrově Chaj-nan — Paracelské ostrovy a Spratlyho ostrovy ležely mimo jeho hranice.',
    'witnesses_map2_svg_hainan' => 'Chaj-nan',
    'witnesses_map2_svg_south' => 'd\'Anvilleovo vymezení',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Mapa d\'Anville, 1735',
    'witnesses_map2_body' => 'Nakreslil ji J.-B. B. d\'Anville; kopii z roku 1740 kdysi daroval německý kancléř čínskému vůdci. Území dynastie Čching končilo na Chaj-nanu.',
    'witnesses_map3_svg_hainan' => '海南 Chaj-nan',
    'witnesses_map3_svg_south' => '"nejjižnější bod Číny"',
    'witnesses_map3_svg_era' => 'Císařská geografická mapa provincií · 1904',
    'witnesses_map3_title' => 'Kompletní geografická mapa provincií císařské dynastie Čching',
    'witnesses_map3_body' => 'Tištěno dynastií Čching — výslovně uvádí, že nejjižnějším bodem území Číny je ostrov Chaj-nan.',
    'witnesses_quote' => 'Právě čínské mapy zveřejněné samotnou Čínou nikdy nezobrazovaly Paracelské ostrovy ani Spratlyho ostrovy jako součást jejího území.',
    'witnesses_timeline_aria' => 'Časová osa starověkých map Číny',
    'witnesses_year_aria' => 'Datace',
    'lightbox_aria' => 'Zobrazit zvětšený obrázek',
    'lightbox_close' => 'Zavřít',
    'lightbox_prev' => 'Předchozí obrázek',
    'lightbox_next' => 'Další obrázek',
];
