<?php

return [
    'footer_index' => 'لائبریری',
    'footer_crest_eyebrow' => 'حقائق کی لائبریری کا اختتام',
    'footer_crest_quote' => '“بحیرۂ جنوبی چین میں امن کی بنیاد <b>بین الاقوامی قانون</b> پر ہے۔”',
    'footer_crest_sub' => 'نفرت نہیں · صرف حقیقت',
    'footer_nav_aria' => 'صفحے کے نچلے حصے کے اقدامات',
    'footer_btn_top' => 'اوپر جائیں',
    'footer_btn_verdict' => 'PCA 2016 فیصلہ',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'نو خطوط والی لکیر',
    'footer_brand_body' => 'ایک توضیحی صفحہ جو معروضی حقیقت، بین الاقوامی قانون اور تاریخی دستاویزات پر مبنی ہے — نو خطوط والی لکیر کے دعوے کو نعروں سے نہیں بلکہ شواہد سے رد کرتا ہے۔',
    'footer_refs_title' => 'حوالہ جات',
    'footer_ref1' => 'PCA فیصلہ، 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — مکمل متن',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'تاریخی مواد اور قدیم نقشے',
    'footer_toc_title' => 'صفحے کی فہرست',
    'footer_toc1' => 'نو خطوط والی لکیر کیا ہے',
    'footer_toc2' => 'اصل',
    'footer_toc3' => 'یہ متنازع کیوں ہے',
    'footer_toc4' => 'بین الاقوامی مخالفت کیوں ہے',
    'footer_toc5' => 'خاموش گواہ',
    'footer_toc6' => 'PCA 2016 فیصلہ',
    'footer_toc7' => 'پیراسل جزائر - اسپراٹلی جزائر',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — بحیرۂ جنوبی چین کے بارے میں معروضی حقیقت۔<br>ماحولیاتی نظام: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'بلا координات',
];
