<?php

return [
    'footer_index' => 'لائبریری',
    'footer_crest_eyebrow' => 'حقیقت کی لائبریری کا اختتام',
    'footer_crest_quote' => '“بحیرۂ جنوبی چین میں امن کی بنیاد <b>بین الاقوامی قانون</b> پر ہے۔”',
    'footer_crest_sub' => 'نفرت نہیں · صرف حقیقت',
    'footer_nav_aria' => 'صفحے کے آخر کے اقدامات',
    'footer_btn_top' => 'اوپر جائیں',
    'footer_btn_verdict' => 'PCA 2016 کا فیصلہ',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'نو خطوط والی لکیر کا دعویٰ',
    'footer_brand_eyebrow' => 'خصوصی صفحہ · ویتنام کی خودمختاری',
    'footer_brand_body' => 'نو خطوط والی لکیر کی وضاحت معروضی حقیقت، بین الاقوامی قانون، PCA 2016 کے فیصلے اور تاریخی دستاویزات کے ذریعے — دو جزائر <strong>"پیراسل جزائر اور اسپراٹلی جزائر"</strong> کی خودمختاری پر گہرے صفحات کی تکمیل کے طور پر۔ چین کے بے بنیاد دعوے کو تاریخ اور شواہد سے رد کرتا ہے۔',
    'footer_refs_title' => 'حوالہ جات',
    'footer_ref1' => 'PCA کا فیصلہ، 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — مکمل متن',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'تاریخی دستاویزات اور قدیم نقشے',
    'footer_toc_title' => 'صفحہ فہرست',
    'footer_toc1' => 'نو خطوط والی لکیر کیا ہے',
    'footer_toc2' => 'اصل',
    'footer_toc3' => 'یہ متنازع کیوں ہے',
    'footer_toc4' => 'بین الاقوامی مخالفت کیوں ہے',
    'footer_toc5' => 'خاموش گواہ',
    'footer_toc6' => 'PCA 2016 کا فیصلہ',
    'footer_toc7' => 'پیراسل جزائر – اسپراٹلی جزائر',
    'footer_copy_eyebrow' => 'غیر منافع بخش منصوبہ',
    'footer_copy_title' => 'پیراسل جزائر – اسپراٹلی جزائر ویتنام کے ہیں',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — نو خطوط والی لکیر پر خصوصی صفحہ، ویتنام کے خودمختاریاتی ماحولیاتی نظام کا حصہ۔',
    'footer_copy_body' => 'نو خطوط والی لکیر کے دعوے کی وضاحت <strong>معروضی حقیقت</strong>، <strong>بین الاقوامی قانون</strong>، PCA 2016 کے فیصلے اور تاریخی دستاویزات کے ذریعے — پیراسل جزائر اور اسپراٹلی جزائر کی خودمختاری پر گہرے صفحات کی تکمیل کے طور پر۔',
    'footer_copy_ecosystem_aria' => 'اسی منصوبے کے صفحات',
    'footer_copy_ecosystem_label' => 'اسی ماحولیاتی نظام میں',
    'footer_copy_disclaimer' => 'یہ مواد تعلیم اور آگاہی کے لیے ہے؛ ویتنامی ریاست کے سرکاری مؤقف کا متبادل نہیں۔',
    'footer_copy' => '<strong>© :year نو خطوط والی لکیر</strong> — غیر منافع بخش منصوبے <strong>پیراسل جزائر – اسپراٹلی جزائر ویتنام کے ہیں</strong> کا حصہ، نظام میں شامل: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'صفحے کے مواد کا عہد',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 کا فیصلہ',
    'footer_chip3' => 'تاریخی شواہد',
    'footer_chip4' => 'قدیم نقشے',
    'footer_chip5' => 'معروضی حقیقت',
    'footer_chip6' => 'بحیرۂ جنوبی چین میں امن',
];
