<?php

return [
    'nav_logo_name' => 'نو خطوط والی لکیر',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'نو خطوط والی لکیر',
    'nav_rail_aria' => 'حصوں کے مطابق نیویگیشن',
    'nav_rail_what' => 'تعریف',
    'nav_rail_origin' => 'اصل',
    'nav_rail_dispute' => 'تنازع',
    'nav_rail_opposition' => 'مخالفت',
    'nav_rail_witnesses' => 'قدیم نقشے',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'پیراسل جزائر – اسپراٹلی جزائر',
    'nav_sound_off' => 'پس منظر موسیقی آن کریں',
    'nav_sound_on' => 'پس منظر موسیقی آف کریں',
    'nav_share' => 'شیئر کریں',
    'dialog_title' => 'دکھائی جانے والی زبان',
    'language' => 'زبان',
    'display_hint' => ':count زبانیں',
    'search_placeholder' => 'زبان تلاش کریں…',
    'cancel' => 'منسوخ',
    'apply' => 'لاگو کریں',
    'sound_off' => 'پس منظر آڈیو آن کریں',
    'sound_on' => 'پس منظر آڈیو آف کریں',
    'lang_trigger' => 'زبان منتخب کریں',
    'close' => 'بند کریں',
    'no_results' => 'کوئی زبان نہیں ملی',
    'contribute' => 'شیئر کریں',
];
