<?php

/**
 * ISO 3166-1 alpha-2 cho flagcdn.com/w40/{cc}.png
 * Bổ sung khi thêm locale mới trong config/language.php
 */
return [
    'vi' => 'vn',
    'en' => 'gb',
    'zh-cn' => 'cn',
    'zh-tw' => 'tw',
    'es' => 'es',
    'fr' => 'fr',
    'de' => 'de',
    'ru' => 'ru',
    'ja' => 'jp',
    'ko' => 'kr',
    'hi' => 'in',
    'bn' => 'bd',
    'mr' => 'in',
    'ta' => 'in',
    'te' => 'in',
    'ur' => 'pk',
    'gu' => 'in',
    'jv' => 'id',
    'id' => 'id',
    'ms' => 'my',
    'th' => 'th',
    'ar' => 'sa',
    'fa' => 'ir',
    'tr' => 'tr',
    'it' => 'it',
    'pl' => 'pl',
    'uk' => 'ua',
    'nl' => 'nl',
    'el' => 'gr',
    'hu' => 'hu',
    'cs' => 'cz',
    'ro' => 'ro',
    'sk' => 'sk',
    'ka' => 'ge',
    'he' => 'il',
    'uz' => 'uz',
    'pt' => 'pt',
    'fil' => 'ph',
    'sv' => 'se',
    'no' => 'no',
    'fi' => 'fi',
    'da' => 'dk',
    'ml' => 'in',
    'bg' => 'bg',
    'ky' => 'kg',
    'sr' => 'rs',
    'lv' => 'lv',
    'lt' => 'lt',
    'sl' => 'si',
    'mn' => 'mn',
];
