<?php

/**
 * Danh sách ngôn ngữ — đồng bộ từ wallsora.dev (+ zh-cn, zh-tw).
 * Cập nhật: php scripts/build-language-config.php
 */
return array (
  'default_code' => 'en',
  'fallback_code' => 'vi',
  'source' => 'wallsora.dev/config/language.php',
  'list' => 
  array (
    'en' => 
    array (
      'code' => 'en',
      'name_native' => 'English',
      'name_english' => 'English',
      'name_vi' => 'Tiếng Anh',
      'flag_cc' => 'gb',
      'dir' => 'ltr',
      'sort' => 0,
      'is_active' => true,
      'is_default' => true,
    ),
    'es' => 
    array (
      'code' => 'es',
      'name_native' => 'Español',
      'name_english' => 'Español',
      'name_vi' => 'Tiếng Tây Ban Nha',
      'flag_cc' => 'es',
      'dir' => 'ltr',
      'sort' => 3,
      'is_active' => true,
      'is_default' => false,
    ),
    'fr' => 
    array (
      'code' => 'fr',
      'name_native' => 'Français',
      'name_english' => 'Français',
      'name_vi' => 'Tiếng Pháp',
      'flag_cc' => 'fr',
      'dir' => 'ltr',
      'sort' => 4,
      'is_active' => true,
      'is_default' => false,
    ),
    'vi' => 
    array (
      'code' => 'vi',
      'name_native' => 'Tiếng Việt',
      'name_english' => 'Tiếng Việt',
      'name_vi' => 'Tiếng Việt',
      'flag_cc' => 'vn',
      'dir' => 'ltr',
      'sort' => 2,
      'is_active' => true,
      'is_default' => false,
    ),
    'hi' => 
    array (
      'code' => 'hi',
      'name_native' => 'हिंदी (Hindī)',
      'name_english' => 'Hindī',
      'name_vi' => 'Tiếng Hindi',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 6,
      'is_active' => true,
      'is_default' => false,
    ),
    'bn' => 
    array (
      'code' => 'bn',
      'name_native' => 'বাংলা (Bānlā)',
      'name_english' => 'Bānlā',
      'name_vi' => 'Tiếng Bengali',
      'flag_cc' => 'bd',
      'dir' => 'ltr',
      'sort' => 7,
      'is_active' => true,
      'is_default' => false,
    ),
    'mr' => 
    array (
      'code' => 'mr',
      'name_native' => 'मराठी (Marāṭhī)',
      'name_english' => 'Marāṭhī',
      'name_vi' => 'Tiếng Marathi',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 8,
      'is_active' => true,
      'is_default' => false,
    ),
    'ta' => 
    array (
      'code' => 'ta',
      'name_native' => 'தமிழ் (Tamiḻ)',
      'name_english' => 'Tamiḻ',
      'name_vi' => 'Tiếng Tamil',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 9,
      'is_active' => true,
      'is_default' => false,
    ),
    'te' => 
    array (
      'code' => 'te',
      'name_native' => 'తెలుగు (Telugu)',
      'name_english' => 'Telugu',
      'name_vi' => 'Tiếng Telugu',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 10,
      'is_active' => true,
      'is_default' => false,
    ),
    'ur' => 
    array (
      'code' => 'ur',
      'name_native' => 'اردو (Urdu)',
      'name_english' => 'Urdu',
      'name_vi' => 'Tiếng Urdu',
      'flag_cc' => 'pk',
      'dir' => 'rtl',
      'sort' => 11,
      'is_active' => true,
      'is_default' => false,
    ),
    'gu' => 
    array (
      'code' => 'gu',
      'name_native' => 'ગુજરાતી (Gujarati)',
      'name_english' => 'Gujarati',
      'name_vi' => 'Tiếng Gujarati',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 12,
      'is_active' => true,
      'is_default' => false,
    ),
    'ja' => 
    array (
      'code' => 'ja',
      'name_native' => '日本語 (Nihongo)',
      'name_english' => 'Nihongo',
      'name_vi' => 'Tiếng Nhật',
      'flag_cc' => 'jp',
      'dir' => 'ltr',
      'sort' => 13,
      'is_active' => true,
      'is_default' => false,
    ),
    'ko' => 
    array (
      'code' => 'ko',
      'name_native' => '한국어 (Hangug-eo)',
      'name_english' => 'Hangug-eo',
      'name_vi' => 'Tiếng Hàn',
      'flag_cc' => 'kr',
      'dir' => 'ltr',
      'sort' => 14,
      'is_active' => true,
      'is_default' => false,
    ),
    'jv' => 
    array (
      'code' => 'jv',
      'name_native' => 'ꦧꦱꦗꦮ (Basa Jawa)',
      'name_english' => 'Basa Jawa',
      'name_vi' => 'Tiếng Javanese',
      'flag_cc' => 'id',
      'dir' => 'ltr',
      'sort' => 15,
      'is_active' => true,
      'is_default' => false,
    ),
    'id' => 
    array (
      'code' => 'id',
      'name_native' => 'Bahasa Indonesia',
      'name_english' => 'Bahasa Indonesia',
      'name_vi' => 'Tiếng Indonesia',
      'flag_cc' => 'id',
      'dir' => 'ltr',
      'sort' => 16,
      'is_active' => true,
      'is_default' => false,
    ),
    'ms' => 
    array (
      'code' => 'ms',
      'name_native' => 'Bahasa Melayu',
      'name_english' => 'Bahasa Melayu',
      'name_vi' => 'Tiếng Malay',
      'flag_cc' => 'my',
      'dir' => 'ltr',
      'sort' => 17,
      'is_active' => true,
      'is_default' => false,
    ),
    'th' => 
    array (
      'code' => 'th',
      'name_native' => 'ไทย (Thai)',
      'name_english' => 'Thai',
      'name_vi' => 'Tiếng Thái',
      'flag_cc' => 'th',
      'dir' => 'ltr',
      'sort' => 18,
      'is_active' => true,
      'is_default' => false,
    ),
    'ar' => 
    array (
      'code' => 'ar',
      'name_native' => 'العربية (Al-‘Arabīyah)',
      'name_english' => 'Al-‘Arabīyah',
      'name_vi' => 'Tiếng Ả Rập',
      'flag_cc' => 'sa',
      'dir' => 'rtl',
      'sort' => 19,
      'is_active' => true,
      'is_default' => false,
    ),
    'fa' => 
    array (
      'code' => 'fa',
      'name_native' => 'فارسی (Fārsi)',
      'name_english' => 'Fārsi',
      'name_vi' => 'Tiếng Ba Tư',
      'flag_cc' => 'ir',
      'dir' => 'rtl',
      'sort' => 20,
      'is_active' => true,
      'is_default' => false,
    ),
    'ru' => 
    array (
      'code' => 'ru',
      'name_native' => 'Русский (Russkiy)',
      'name_english' => 'Russkiy',
      'name_vi' => 'Tiếng Nga',
      'flag_cc' => 'ru',
      'dir' => 'ltr',
      'sort' => 21,
      'is_active' => true,
      'is_default' => false,
    ),
    'de' => 
    array (
      'code' => 'de',
      'name_native' => 'Deutsch',
      'name_english' => 'Deutsch',
      'name_vi' => 'Tiếng Đức',
      'flag_cc' => 'de',
      'dir' => 'ltr',
      'sort' => 22,
      'is_active' => true,
      'is_default' => false,
    ),
    'tr' => 
    array (
      'code' => 'tr',
      'name_native' => 'Türkçe',
      'name_english' => 'Türkçe',
      'name_vi' => 'Tiếng Thổ Nhĩ Kỳ',
      'flag_cc' => 'tr',
      'dir' => 'ltr',
      'sort' => 23,
      'is_active' => true,
      'is_default' => false,
    ),
    'it' => 
    array (
      'code' => 'it',
      'name_native' => 'Italiano',
      'name_english' => 'Italiano',
      'name_vi' => 'Tiếng Ý',
      'flag_cc' => 'it',
      'dir' => 'ltr',
      'sort' => 24,
      'is_active' => true,
      'is_default' => false,
    ),
    'pl' => 
    array (
      'code' => 'pl',
      'name_native' => 'Polski',
      'name_english' => 'Polski',
      'name_vi' => 'Tiếng Ba Lan',
      'flag_cc' => 'pl',
      'dir' => 'ltr',
      'sort' => 25,
      'is_active' => true,
      'is_default' => false,
    ),
    'uk' => 
    array (
      'code' => 'uk',
      'name_native' => 'Українська (Ukrains\'ka)',
      'name_english' => 'Ukrains\'ka',
      'name_vi' => 'Tiếng Ukraina',
      'flag_cc' => 'ua',
      'dir' => 'ltr',
      'sort' => 26,
      'is_active' => true,
      'is_default' => false,
    ),
    'nl' => 
    array (
      'code' => 'nl',
      'name_native' => 'Nederlands',
      'name_english' => 'Nederlands',
      'name_vi' => 'Tiếng Hà Lan',
      'flag_cc' => 'nl',
      'dir' => 'ltr',
      'sort' => 27,
      'is_active' => true,
      'is_default' => false,
    ),
    'el' => 
    array (
      'code' => 'el',
      'name_native' => 'Ελληνικά (Elliniká)',
      'name_english' => 'Elliniká',
      'name_vi' => 'Tiếng Hy Lạp',
      'flag_cc' => 'gr',
      'dir' => 'ltr',
      'sort' => 28,
      'is_active' => true,
      'is_default' => false,
    ),
    'hu' => 
    array (
      'code' => 'hu',
      'name_native' => 'Magyar',
      'name_english' => 'Magyar',
      'name_vi' => 'Tiếng Hungary',
      'flag_cc' => 'hu',
      'dir' => 'ltr',
      'sort' => 29,
      'is_active' => true,
      'is_default' => false,
    ),
    'cs' => 
    array (
      'code' => 'cs',
      'name_native' => 'Čeština',
      'name_english' => 'Čeština',
      'name_vi' => 'Tiếng Czech',
      'flag_cc' => 'cz',
      'dir' => 'ltr',
      'sort' => 30,
      'is_active' => true,
      'is_default' => false,
    ),
    'ro' => 
    array (
      'code' => 'ro',
      'name_native' => 'Română',
      'name_english' => 'Română',
      'name_vi' => 'Tiếng Romani',
      'flag_cc' => 'ro',
      'dir' => 'ltr',
      'sort' => 31,
      'is_active' => true,
      'is_default' => false,
    ),
    'sk' => 
    array (
      'code' => 'sk',
      'name_native' => 'Slovenčina',
      'name_english' => 'Slovenčina',
      'name_vi' => 'Tiếng Slovak',
      'flag_cc' => 'sk',
      'dir' => 'ltr',
      'sort' => 32,
      'is_active' => true,
      'is_default' => false,
    ),
    'ka' => 
    array (
      'code' => 'ka',
      'name_native' => 'ქართული (Kartuli)',
      'name_english' => 'Kartuli',
      'name_vi' => 'Tiếng Georgia',
      'flag_cc' => 'ge',
      'dir' => 'ltr',
      'sort' => 33,
      'is_active' => true,
      'is_default' => false,
    ),
    'he' => 
    array (
      'code' => 'he',
      'name_native' => 'עברית (Ivrit)',
      'name_english' => 'Ivrit',
      'name_vi' => 'Tiếng Hebrew',
      'flag_cc' => 'il',
      'dir' => 'rtl',
      'sort' => 34,
      'is_active' => true,
      'is_default' => false,
    ),
    'uz' => 
    array (
      'code' => 'uz',
      'name_native' => 'O‘zbekcha',
      'name_english' => 'O‘zbekcha',
      'name_vi' => 'Tiếng Uzbek',
      'flag_cc' => 'uz',
      'dir' => 'ltr',
      'sort' => 35,
      'is_active' => true,
      'is_default' => false,
    ),
    'pt' => 
    array (
      'code' => 'pt',
      'name_native' => 'Português',
      'name_english' => 'Português',
      'name_vi' => 'Tiếng Bồ Đào Nha',
      'flag_cc' => 'pt',
      'dir' => 'ltr',
      'sort' => 36,
      'is_active' => true,
      'is_default' => false,
    ),
    'fil' => 
    array (
      'code' => 'fil',
      'name_native' => 'Filipino',
      'name_english' => 'Filipino',
      'name_vi' => 'Philippines',
      'flag_cc' => 'ph',
      'dir' => 'ltr',
      'sort' => 37,
      'is_active' => true,
      'is_default' => false,
    ),
    'sv' => 
    array (
      'code' => 'sv',
      'name_native' => 'Svenska',
      'name_english' => 'Svenska',
      'name_vi' => 'Thụy Diển',
      'flag_cc' => 'se',
      'dir' => 'ltr',
      'sort' => 38,
      'is_active' => true,
      'is_default' => false,
    ),
    'no' => 
    array (
      'code' => 'no',
      'name_native' => 'Norsk',
      'name_english' => 'Norsk',
      'name_vi' => 'Norsk',
      'flag_cc' => 'no',
      'dir' => 'ltr',
      'sort' => 39,
      'is_active' => true,
      'is_default' => false,
    ),
    'fi' => 
    array (
      'code' => 'fi',
      'name_native' => 'Suomi',
      'name_english' => 'Suomi',
      'name_vi' => 'Phần Lan',
      'flag_cc' => 'fi',
      'dir' => 'ltr',
      'sort' => 40,
      'is_active' => true,
      'is_default' => false,
    ),
    'da' => 
    array (
      'code' => 'da',
      'name_native' => 'Dansk',
      'name_english' => 'Dansk',
      'name_vi' => 'Đan Mạch',
      'flag_cc' => 'dk',
      'dir' => 'ltr',
      'sort' => 41,
      'is_active' => true,
      'is_default' => false,
    ),
    'ml' => 
    array (
      'code' => 'ml',
      'name_native' => 'മലയാളം',
      'name_english' => 'മലയാളം',
      'name_vi' => 'Malayalam',
      'flag_cc' => 'in',
      'dir' => 'ltr',
      'sort' => 42,
      'is_active' => true,
      'is_default' => false,
    ),
    'bg' => 
    array (
      'code' => 'bg',
      'name_native' => 'Български',
      'name_english' => 'Български',
      'name_vi' => 'Bulgarian',
      'flag_cc' => 'bg',
      'dir' => 'ltr',
      'sort' => 43,
      'is_active' => true,
      'is_default' => false,
    ),
    'ky' => 
    array (
      'code' => 'ky',
      'name_native' => 'Кыргызча',
      'name_english' => 'Кыргызча',
      'name_vi' => 'Kyrgyz',
      'flag_cc' => 'kg',
      'dir' => 'ltr',
      'sort' => 44,
      'is_active' => true,
      'is_default' => false,
    ),
    'sr' => 
    array (
      'code' => 'sr',
      'name_native' => 'Српски',
      'name_english' => 'Српски',
      'name_vi' => 'Serbian (Cyrillic Script)',
      'flag_cc' => 'rs',
      'dir' => 'ltr',
      'sort' => 45,
      'is_active' => true,
      'is_default' => false,
    ),
    'lv' => 
    array (
      'code' => 'lv',
      'name_native' => 'Latviešu',
      'name_english' => 'Latviešu',
      'name_vi' => 'Latviešu valoda',
      'flag_cc' => 'lv',
      'dir' => 'ltr',
      'sort' => 46,
      'is_active' => true,
      'is_default' => false,
    ),
    'lt' => 
    array (
      'code' => 'lt',
      'name_native' => 'Lietuvių',
      'name_english' => 'Lietuvių',
      'name_vi' => 'Lietuvių kalba',
      'flag_cc' => 'lt',
      'dir' => 'ltr',
      'sort' => 47,
      'is_active' => true,
      'is_default' => false,
    ),
    'sl' => 
    array (
      'code' => 'sl',
      'name_native' => 'Slovenščina',
      'name_english' => 'Slovenščina',
      'name_vi' => 'Slovenski jezik',
      'flag_cc' => 'si',
      'dir' => 'ltr',
      'sort' => 48,
      'is_active' => true,
      'is_default' => false,
    ),
    'mn' => 
    array (
      'code' => 'mn',
      'name_native' => 'Монгол',
      'name_english' => 'Монгол',
      'name_vi' => 'Монгол хэл',
      'flag_cc' => 'mn',
      'dir' => 'ltr',
      'sort' => 49,
      'is_active' => true,
      'is_default' => false,
    ),
    'zh-cn' => 
    array (
      'code' => 'zh-cn',
      'name_native' => '简体中文',
      'name_english' => 'Chinese (Simplified)',
      'name_vi' => 'Tiếng Trung (Giản thể)',
      'flag_cc' => 'cn',
      'dir' => 'ltr',
      'sort' => 3,
      'is_active' => true,
      'is_default' => false,
    ),
    'zh-tw' => 
    array (
      'code' => 'zh-tw',
      'name_native' => '繁體中文',
      'name_english' => 'Chinese (Traditional)',
      'name_vi' => 'Tiếng Trung (Phồn thể)',
      'flag_cc' => 'tw',
      'dir' => 'ltr',
      'sort' => 4,
      'is_active' => true,
      'is_default' => false,
    ),
  ),
  'nav_ui' => 
  array (
    'vi' => 
    array (
      'dialog_title' => 'Ngôn ngữ hiển thị',
      'language' => 'Ngôn ngữ',
      'display_hint' => '50 ngôn ngữ',
      'search_placeholder' => 'Tìm ngôn ngữ…',
      'cancel' => 'Hủy',
      'apply' => 'Áp dụng',
      'sound_off' => 'Bật âm thanh sóng biển',
      'sound_on' => 'Tắt âm thanh sóng biển',
      'sound_label_off' => 'Âm thanh',
      'sound_label_on' => 'Đang phát',
      'contribute' => 'Đóng góp',
      'lang_trigger' => 'Chọn ngôn ngữ',
      'close' => 'Đóng',
      'no_results' => 'Không tìm thấy ngôn ngữ',
    ),
    'en' => 
    array (
      'dialog_title' => 'Display language',
      'language' => 'Language',
      'display_hint' => '50 languages',
      'search_placeholder' => 'Search languages…',
      'cancel' => 'Cancel',
      'apply' => 'Apply',
      'sound_off' => 'Turn on ocean ambience',
      'sound_on' => 'Turn off ocean ambience',
      'sound_label_off' => 'Sound',
      'sound_label_on' => 'Playing',
      'contribute' => 'Contribute',
      'lang_trigger' => 'Choose language',
      'close' => 'Close',
      'no_results' => 'No languages found',
    ),
  ),
);
