<?php

return [
    'footer_index' => 'Biblioteka',
    'footer_crest_eyebrow' => 'Faktų bibliotekos užbaiga',
    'footer_crest_quote' => '„Taika Pietų Kinijos jūroje yra grindžiama <b>tarptautine teise</b>.“',
    'footer_crest_sub' => 'Be neapykantos · Tik tiesa',
    'footer_nav_aria' => 'Apatinės dalies veiksmai',
    'footer_btn_top' => 'Į puslapio viršų',
    'footer_btn_verdict' => 'PCA 2016 sprendimas',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Devynių brūkšnių linijos pretenzija',
    'footer_brand_eyebrow' => 'Teminis puslapis · Vietnamo suverenitetas',
    'footer_brand_body' => 'Paaiškina Devynių brūkšnių liniją per objektyvius faktus, tarptautinę teisę, PCA 2016 sprendimą ir istorinius šaltinius — kaip papildymą išsamiems puslapiams apie dviejų salynų <strong>"Paracelio salos ir Spratlio salos"</strong> suverenitetą. Istorija ir įrodymais paneigiamos nepagrįstos Kinijos pretenzijos.',
    'footer_refs_title' => 'Nuorodos',
    'footer_ref1' => 'PCA sprendimas, 2016-07-12',
    'footer_ref2' => 'UNCLOS 1982 — visas tekstas',
    'footer_ref3' => 'Limits in the Seas №143 (JAV Valstybės departamentas)',
    'footer_ref4' => 'Istoriniai šaltiniai ir seni žemėlapiai',
    'footer_toc_title' => 'Puslapio turinys',
    'footer_toc1' => 'Kas yra Devynių brūkšnių linija',
    'footer_toc2' => 'Kilmė',
    'footer_toc3' => 'Kodėl ji kelia ginčų',
    'footer_toc4' => 'Kodėl tarptautinė bendruomenė tam prieštarauja',
    'footer_toc5' => 'Tylūs liudytojai',
    'footer_toc6' => 'PCA 2016 sprendimas',
    'footer_toc7' => 'Paracelio salos – Spratlio salos',
    'footer_copy_eyebrow' => 'Pelno nesiekiantis projektas',
    'footer_copy_title' => 'Paracelio salos – Spratlio salos priklauso Vietnamui',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Teminis puslapis apie Devynių brūkšnių liniją Vietnamo suvereniteto ekosistemoje.',
    'footer_copy_body' => 'Devynių brūkšnių linijos pretenzijos aiškinamos per <strong>objektyvius faktus</strong>, <strong>tarptautinę teisę</strong>, PCA 2016 sprendimą ir istorinius šaltinius — kaip papildymas išsamiems puslapiams apie Paracelio salų ir Spratlio salų suverenitetą.',
    'footer_copy_ecosystem_aria' => 'Susiję šio projekto puslapiai',
    'footer_copy_ecosystem_label' => 'Toje pačioje ekosistemoje',
    'footer_copy_disclaimer' => 'Turinys skirtas švietimui ir sąmoningumo didinimui; jis nepakeičia oficialios Vietnamo valstybės pozicijos.',
    'footer_copy' => '<strong>© :year Devynių brūkšnių linija</strong> — Pelno nesiekiančio projekto <strong>Paracelio salos – Spratlio salos priklauso Vietnamui</strong> dalis, priklausanti sistemai: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Puslapio turinio įsipareigojimai',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 sprendimas',
    'footer_chip3' => 'Istoriniai įrodymai',
    'footer_chip4' => 'Seni žemėlapiai',
    'footer_chip5' => 'Objektyvi tiesa',
    'footer_chip6' => 'Pietų Kinijos jūros taika',
];
