<?php

return [
    'footer_index' => 'Biblioteka',
    'footer_crest_eyebrow' => 'Tiesos biblioteka užbaigta',
    'footer_crest_quote' => '„Taika Pietų Kinijos jūroje grindžiama <b>tarptautine teise</b>.“',
    'footer_crest_sub' => 'Be neapykantos · Tik tiesa',
    'footer_nav_aria' => 'Veiksmai puslapio apačioje',
    'footer_btn_top' => 'Į puslapio viršų',
    'footer_btn_verdict' => '2016 m. PCA sprendimas',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Devynių brūkšnių linija',
    'footer_brand_body' => 'Tinklalapis, aiškinantis remiantis objektyvia tiesa, tarptautine teise ir istoriniais šaltiniais — Devynių brūkšnių linijos pretenzijas paneigiantis įrodymais, o ne šūkiais.',
    'footer_refs_title' => 'Nuorodos',
    'footer_ref1' => 'PCA sprendimas, 2016-07-12',
    'footer_ref2' => 'UNCLOS 1982 — visas tekstas',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Istorinė medžiaga ir seni žemėlapiai',
    'footer_toc_title' => 'Puslapio turinys',
    'footer_toc1' => 'Kas yra Devynių brūkšnių linija',
    'footer_toc2' => 'Kilmė',
    'footer_toc3' => 'Kodėl ji kelia ginčus',
    'footer_toc4' => 'Kodėl tarptautinė bendruomenė jai prieštarauja',
    'footer_toc5' => 'Tyliieji liudytojai',
    'footer_toc6' => '2016 m. PCA sprendimas',
    'footer_toc7' => 'Paracelio salos – Spratlio salos',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektyvi tiesa apie Pietų Kinijos jūrą.<br>Ekosistema: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Be koordinačių',
];
