<?php

return [
    'nav_logo_name' => 'Devynių brūkšnių linija',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Devynių brūkšnių linija',
    'nav_rail_aria' => 'Navigacija pagal skyrius',
    'nav_rail_what' => 'Apibrėžimas',
    'nav_rail_origin' => 'Kilmė',
    'nav_rail_dispute' => 'Ginčas',
    'nav_rail_opposition' => 'Pasipriešinimas',
    'nav_rail_witnesses' => 'Senoviniai žemėlapiai',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracelio salos – Spratlio salos',
    'nav_sound_off' => 'Įjungti foninę muziką',
    'nav_sound_on' => 'Išjungti foninę muziką',
    'nav_share' => 'Bendrinti',
    'dialog_title' => 'Rodoma kalba',
    'language' => 'Kalba',
    'display_hint' => ':count kalbų',
    'search_placeholder' => 'Ieškoti kalbos…',
    'cancel' => 'Atšaukti',
    'apply' => 'Taikyti',
    'sound_off' => 'Įjungti foninį garsą',
    'sound_on' => 'Išjungti foninį garsą',
    'lang_trigger' => 'Pasirinkti kalbą',
    'close' => 'Uždaryti',
    'no_results' => 'Kalbų nerasta',
    'contribute' => 'Bendrinti',
];
