<?php

return [
    'opposition_index' => 'Prieštaravimas',
    'opposition_label' => 'Kodėl tarptautinė bendruomenė prieštarauja',
    'opposition_title' => 'Prieštaravimas grindžiamas',
    'opposition_title_accent' => 'įstatymu, o ne emocijomis',
    'opposition_lead' => 'Vos tik Devynių brūkšnių linija buvo pateikta Jungtinėms Tautoms 2009 m., daugelis valstybių ir akademikų jai prieštaravo — remdamiesi konkrečiais teisiniais argumentais.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Gegužė',
    'opposition_voice1_title' => 'Vietnamas · Malaizija · Indonezija',
    'opposition_voice1_body' => 'Vos vieną dieną po to, kai Kinija pateikė Devynių brūkšnių linijos žemėlapį Jungtinių Tautų Generaliniam Sekretoriui (2009-05-07), šios šalys paeiliui išsiuntė protesto notą, atmesdamos šį pretenziją.',
    'opposition_voice1_chip1' => 'Protesto nota',
    'opposition_voice1_chip2' => 'Neatitinka 1982 m. UNCLOS',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinai',
    'opposition_voice2_body' => 'Pateikė diplomatinį laišką Jungtinėms Tautoms, kuriame pareiškė, kad Kinijos pretenzijos Pietų Kinijos jūroje yra „neturinčios pagrindo pagal tarptautinę teisę“ — tai tapo pagrindu vėlesniam arbitražo ieškiniui.',
    'opposition_voice2_chip1' => 'PCA bylos prielaida',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'JAV Valstybės departamentas — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analizė parodė: skirtingų metų žemėlapiuose brūkšninė linija buvo nubrėžta nevienodai; ji įsiterpia į žemyninę teritoriją, o ne remiasi vidurine linija; daugelis objektų neatitinka „salos“ kriterijų, kad galėtų turėti EEZ.',
    'opposition_voice3_chip1' => 'Neatitinka teisinių reikalavimų',
    'opposition_voice3_chip2' => 'Oficiali analizė',
    'opposition_voice4_year' => 'Akademinė',
    'opposition_voice4_title' => '„Istorinių vandenų“ sąvoka pasenusi',
    'opposition_voice4_body' => 'Ši sąvoka taikoma tik įlankoms ir priekrantės įloms — ji negali apimti visos plačios atviros jūros teritorijos. 2003 m. pats Taivanas taip pat atmetė 1993 m. kadaise nurodytą „istorinių vandenų“ politiką.',
    'opposition_voice4_chip1' => 'Net ir Kinijos mokslininkai nesutaria',
];
