<?php

return [
    'opposition_index' => 'Prieštaravimas',
    'opposition_label' => 'Kodėl tarptautinė bendruomenė prieštarauja',
    'opposition_title' => 'Prieštaravimai grindžiami',
    'opposition_title_accent' => 'įstatymu, ne emocijomis',
    'opposition_lead' => 'Netrukus po to, kai Devynių brūkšnių linija 2009 m. buvo pateikta Jungtinėms Tautoms, daugelis valstybių ir mokslininkų jai prieštaravo — remdamiesi konkrečiais teisiniais argumentais.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Gegužė',
    'opposition_voice1_title' => 'Vietnamas · Malaizija · Indonezija',
    'opposition_voice1_body' => 'Vos praėjus vienai dienai po to, kai Kinija 2009-05-07 pateikė Devynių brūkšnių linijos žemėlapį Jungtinių Tautų Generaliniam Sekretoriui, šios šalys paeiliui išsiuntė protesto notas ir atmetė šį pretenzijų pagrindą.',
    'opposition_voice1_chip1' => 'Protesto nota',
    'opposition_voice1_chip2' => 'Nesuderinama su 1982 m. UNCLOS',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinai',
    'opposition_voice2_body' => 'Jungtinėms Tautoms buvo nusiųstas diplomatinis laiškas, kuriame teigiama, kad Kinijos pretenzijos Pietų Kinijos jūroje yra „neturinčios pagrindo pagal tarptautinę teisę“ — tai tapo pagrindu vėlesniam kreipimuisi į Arbitražo teismą.',
    'opposition_voice2_chip1' => 'PCA bylos prielaida',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'JAV Valstybės departamentas — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analizė parodė: skirtingų metų žemėlapiuose linijos padėtis nesutampa; linija įsiterpia į žemyninę teritoriją, užuot ėjusi vidurine linija; daugelis objektų neatitinka „salos“ statuso, kad galėtų turėti EEZ.',
    'opposition_voice3_chip1' => 'Neatitinka teisinės kvalifikacijos',
    'opposition_voice3_chip2' => 'Oficiali analizė',
    'opposition_voice4_year' => 'Akademinė sritis',
    'opposition_voice4_title' => '„Istorinių vandenų“ samprata yra pasenusi',
    'opposition_voice4_body' => 'Ši sąvoka taikoma tik įlankoms ir priekrantės užutėkiams — ji negali apimti visos plačios atviros jūros teritorijos. 2003 m. pati Taivano valdžia taip pat atmetė 1993 m. minėtą „istorinių vandenų“ politiką.',
    'opposition_voice4_chip1' => 'Net ir Kinijos mokslininkai nėra vieningi',
];
