<?php

return [
    'sovereignty_index' => 'Paracelio salos - Spratlio salos',
    'sovereignty_label' => 'Būtina išvada',
    'sovereignty_title' => 'Paracelio salos - Spratlio salos',
    'sovereignty_title_accent' => 'yra Vietnamo',
    'sovereignty_lead' => 'Šis puslapis paaiškina Devynių brūkšnių linija. Išvados dalis atsako į kitą klausimą: kam priklauso suverenitetas dėl dviejų Paracelio salos ir Spratlio salos? Pagal valdymo istoriją ir tarptautinę teisę nuoseklus atsakymas yra Vietnamas.',
    'sovereignty_thesis_label' => 'Apibendrinta tezė',
    'sovereignty_thesis_lock1' => 'Nėra teisinės geografijos',
    'sovereignty_thesis_lock2' => '2016 m. PCA atmetė',
    'sovereignty_thesis_lock3' => 'Senieji žemėlapiai neapima',
    'sovereignty_thesis_body' => 'Po šešių aukščiau pateiktų dalių aišku trys dalykai: Devynių brūkšnių linija nubrėžta ranka, be teisinių koordinačių; 2016 m. Arbitražo teismas atmetė šį reikalavimą; paties Kinija seni žemėlapiai neapima Pietų Kinijos jūros. Vietnamo suverenitetas remiasi ne šūkiais, o tuo, kad Vietnamo valstybė — nuo Nguyễn valdovų laikų — taikiai ir nuosekliai administravo šias salas tada, kai abi salynų grupės dar buvo niekieno žemė.',
    'sovereignty_spine_caption' => 'Nuoseklaus valdymo gairės',
    'sovereignty_spine_title' => 'Nesibaigianti laiko juosta',
    'sovereignty_spine_range' => 'XVII a. → dabar',
    'sovereignty_chron1_year' => 'XVII a.',
    'sovereignty_chron1_title' => 'Hoàng Sa būrys',
    'sovereignty_chron1_body' => 'Nguyễn valdovai siuntė Hoàng Sa būrį tirti, matuoti jūrų maršrutus ir vykdyti veiklą jūroje — taip buvo įgyvendinama faktinė valdžia.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Imperatorius Gia Long',
    'sovereignty_chron2_body' => 'Ant Paracelio salos buvo iškelta vėliava, taip pasauliui to meto akivaizdoje patvirtinant Vietnamo suverenitetą.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Imperatorius Minh Mạng',
    'sovereignty_chron3_body' => 'Salynai buvo išmatuoti, pastatytos stelos ir įrašyti į oficialius rūmų žemėlapius.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Tęstinis paveldėjimas',
    'sovereignty_chron4_body' => 'Prancūzija pripažino ir toliau administravo; Paracelio salos buvo prijungtos prie Thừa Thiên provincijos — tai sudarė pagrindą dabartinei Vietnamo valstybei.',
    'sovereignty_chron5_year' => 'Dabar',
    'sovereignty_chron5_title' => 'Teisė ir praktika',
    'sovereignty_chron5_body' => 'Vietnamas tvarko pagal UNCLOS, diplomatiją ir archyvinius dokumentus; Devynių brūkšnių linija pretenzija negali pakeisti šių įrodymų.',
    'sovereignty_balance_label' => 'Įrodymų pusiausvyra',
    'sovereignty_balance_medallion_title' => 'Abiejų pusių palyginimas',
    'sovereignty_vn_tag' => 'Vietnamo pusė',
    'sovereignty_vn_title' => 'Suverenitetas nustatomas veiksmais',
    'sovereignty_vn_body' => 'Tikras užėmimas, kai žemė dar buvo niekieno, po to per amžius vykdytas viešas administravimas — su imperiniais dokumentais, stelos akmenimis, žemėlapiais ir administraciniais archyvais. Šis būdas atitinka UNCLOS ir tarptautinę praktiką.',
    'sovereignty_dash_tag' => 'Devynių brūkšnių linijos pusė',
    'sovereignty_dash_title' => 'Pretenzija negali pakeisti įrodymų',
    'sovereignty_dash_body' => '1948 m. nubrėžta linija, be koordinačių, buvo 2016 m. PCA atmesta ir prieštarauja UNCLOS — kaip parodyta 03–06 dalyse. Todėl išvada dėl dviejų salynų suvereniteto negali būti grindžiama Devynių brūkšnių linija.',
    'sovereignty_seal_quote' => 'Vietnamas sprendžia ginčus <strong>taikiomis priemonėmis</strong>, remdamasis tarptautine teise — ypač 1982 m. UNCLOS — siekdamas taikios, bendradarbiaujančios ir klestinčios Pietų Kinijos jūros.',
    'sovereignty_seal_cite' => 'Vietnamo pozicija · 1982 m. UNCLOS',
    'sovereignty_next_eyebrow' => 'Pagrindinis projektas toje pačioje ekosistemoje',
    'sovereignty_next_title' => 'Skaitykite visus įrodymus apie Paracelio salas - Spratlio salas',
    'sovereignty_next_body' => 'Išsami medžiaga — dokumentai, žemėlapiai, laiko juosta ir teisiniai argumentai — pateikta svetainėje <strong>paracelislands.net</strong>, kur visapusiškai pristatoma dviejų salynų suvereniteto tema. Šis puslapis, kurį dabar skaitote, tik logiškai sujungia Devynių brūkšnių linija su šia išvada.',
    'sovereignty_next_cta' => 'Atidaryti paracelislands.net',
];
