<?php

return [
    'sovereignty_index' => 'Paracelio salos - Spratlio salos',
    'sovereignty_label' => 'Būtina išvada',
    'sovereignty_title' => 'Paracelio salos - Spratlio salos',
    'sovereignty_title_accent' => 'yra Vietnamo',
    'sovereignty_lead' => 'Šis puslapis paaiškina Devynių brūkšnių liniją. Išvada atsako į kitą klausimą: kam priklauso suverenitetas dviem Paracelio salų ir Spratlio salų salynams? Pagal valdymo istoriją ir tarptautinę teisę nuoseklus atsakymas yra Vietnamas.',
    'sovereignty_thesis_label' => 'Apibendrinta tezė',
    'sovereignty_thesis_lock1' => 'Nėra teisinės koordinačių sistemos',
    'sovereignty_thesis_lock2' => '2016 m. PCA ją atmetė',
    'sovereignty_thesis_lock3' => 'Senieji žemėlapiai jos neapima',
    'sovereignty_thesis_body' => 'Po šešių aukščiau pateiktų skyrių trys dalykai aiškūs: Devynių brūkšnių linija nubrėžta ranka, be teisinių koordinačių; 2016 m. Arbitražo teismas atmetė šį reikalavimą; o patys Kinijos seni žemėlapiai neapima Pietų Kinijos jūros. Vietnamo suverenitetas remiasi ne šūkiais, o tuo, kad Vietnamo valstybė — nuo Nguyễn valdovų laikų — taikiai ir nuosekliai vykdė administravimą tuo metu, kai abu salynai dar buvo niekieno žemė.',
    'sovereignty_spine_caption' => 'Nuoseklaus valdymo orientyrai',
    'sovereignty_spine_title' => 'Viena laiko juosta, be pertraukų',
    'sovereignty_spine_range' => 'XVII a. → dabar',
    'sovereignty_chron1_year' => 'XVII a.',
    'sovereignty_chron1_title' => 'Hoàng Sa būrys',
    'sovereignty_chron1_body' => 'Nguyễn valdovai siuntė Hoàng Sa būrį tyrinėti, matuoti jūrų maršrutus ir vykdyti veiklą jūroje — tai buvo faktinis valdymo įgyvendinimas.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Imperatorius Gia Long',
    'sovereignty_chron2_body' => 'Buvo iškelta vėliava Paracelio salose, taip patvirtinant Vietnamo suverenitetą to meto pasauliui.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Imperatorius Minh Mạng',
    'sovereignty_chron3_body' => 'Salynai buvo išmatuoti, pastatyti stulpai ir jie buvo įrašyti į oficialius rūmų žemėlapius.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Tęstinis perėmimas',
    'sovereignty_chron4_body' => 'Prancūzija tai pripažino ir toliau administravo; Hoàng Sa buvo prijungtos prie Thừa Thiên provincijos — tai tapo dabartinės Vietnamo valstybės pagrindu.',
    'sovereignty_chron5_year' => 'Dabar',
    'sovereignty_chron5_title' => 'Teisė ir praktika',
    'sovereignty_chron5_body' => 'Vietnamas valdo pagal UNCLOS, diplomatiją ir archyvinius įrašus; Devynių brūkšnių linijos pretenzija negali pakeisti šių įrodymų.',
    'sovereignty_balance_label' => 'Įrodymų pusiausvyra',
    'sovereignty_balance_medallion_title' => 'Abiejų pusių palyginimas',
    'sovereignty_vn_tag' => 'Vietnamo pusė',
    'sovereignty_vn_title' => 'Suverenitetas nustatomas veiksmais',
    'sovereignty_vn_body' => 'Tikras užėmimas, kai žemė dar buvo niekieno, o vėliau šimtmečius viešai vykdytas valdymas — su imperiniais dokumentais, stulpais, žemėlapiais ir administraciniais įrašais. Toks būdas atitinka UNCLOS ir tarptautinę praktiką.',
    'sovereignty_dash_tag' => 'Devynių brūkšnių linijos pusė',
    'sovereignty_dash_title' => 'Pretenzija negali pakeisti įrodymų',
    'sovereignty_dash_body' => '1948 m. nubrėžta linija be koordinačių buvo 2016 m. PCA atmesta ir prieštarauja UNCLOS — kaip jau parodyta 03–06 skyriuose. Dėl to išvada dėl abiejų salynų suvereniteto negali būti grindžiama Devynių brūkšnių linija.',
    'sovereignty_seal_quote' => 'Vietnamas sprendžia ginčus <strong>taikiomis priemonėmis</strong>, remdamasis tarptautine teise — ypač 1982 m. UNCLOS — siekdamas taikios, bendradarbiaujančios ir klestinčios Pietų Kinijos jūros.',
    'sovereignty_seal_cite' => 'Vietnamo pozicija · 1982 m. UNCLOS',
    'sovereignty_next_eyebrow' => 'Pagrindinis projektas toje pačioje ekosistemoje',
    'sovereignty_next_title' => 'Perskaitykite visus įrodymus apie Paracelio ir Spratlio salas',
    'sovereignty_next_body' => 'Išsami byla — dokumentai, žemėlapiai, laiko juosta ir teisiniai argumentai — pateikta svetainėje <strong>paracelislands.net</strong>, kur išsamiai pristatoma abiejų salynų suvereniteto tema. Šiuo puslapiu tik logiškai sujungiama Devynių brūkšnių linija su ta išvada.',
    'sovereignty_next_cta' => 'Atidaryti paracelislands.net',
];
