<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Tarptautinis sprendimas',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trys „Ne“',
    'verdict_lead' => '2016 m. liepos 12 d. Nuolatinis arbitražo teismas (PCA) Hagoje — sudarytas pagal UNCLOS VII priedą, byloje Filipinai prieš Kiniją — priėmė sprendimą, kuriuo atmetė Devynių brūkšnių linijos pretenzijas. <em>Paspauskite ant kiekvienos kortelės, kad perskaitytumėte visą tekstą.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'istorinėms teisėms',
    'verdict_card1_short' => 'Kinija neturi teisinio pagrindo remtis istorinėmis teisėmis į išteklius jūrinėje teritorijoje, esančioje Devynių brūkšnių linijoje.',
    'verdict_card1_quote' => '„Nėra teisinio pagrindo Kinijai remtis istorinėmis teisėmis į išteklius, esančius jūrinėje teritorijoje Devynių brūkšnių linijoje.“',
    'verdict_card1_more' => '+ Skaityti sprendimą',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'subjektams, kurianties EEZ',
    'verdict_card2_short' => 'Nė vienas objektas Spratlio salose neatitinka sąlygų sukurti Kinijai išskirtinę ekonominę zoną — įskaitant Ba Binh salą.',
    'verdict_card2_quote' => '„Nė vienas objektas Spratlio salose negali sukurti išskirtinės ekonominės zonos.“',
    'verdict_card2_more' => '+ Skaityti sprendimą',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'teisėtiems veiksmams',
    'verdict_card3_short' => 'Kinija pažeidė Filipinų suverenias teises, trukdė žvejybai ir padarė žalos jūrų aplinkai.',
    'verdict_card3_quote' => '„Kinija pažeidė Filipinų suverenias teises, kišosi į žvejybos veiklą Scarborough seklumoje ir padarė didelę žalą koralinių rifų aplinkai.“',
    'verdict_card3_more' => '+ Skaityti sprendimą',
    'verdict_extra1' => 'Kinijos pačios nubrėžta Devynių brūkšnių linija <strong>neatitinka</strong> 1982 m. UNCLOS.',
    'verdict_extra2' => 'Kinija, vykdydama perteklinį išteklių naudojimą ir statydama dirbtines salas, padarė žalą Spratlio salų ekosistemai.',
    'verdict_extra3' => 'Kinijos veiksmai didina konflikto su Filipinais riziką.',
    'verdict_extra4' => 'Ba Binh sala (kontroliuojama Taivano) taip pat negali sukurti EEZ.',
    'verdict_subtitle' => 'Kodėl tai prieštarauja UNCLOS?',
    'verdict_subtitle_body' => '1982 m. UNCLOS aiškiai nustato jūrines zonas, remdamasi pakrantės valstybės bazinėmis linijomis. Devynių brūkšnių linijos pretenzija peržengia šią sistemą, todėl jos negalima suderinti su ja.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritorinė jūra (jūrmylės)',
    'verdict_zone1_body' => 'Valstybės suvereniteto jūros zona, skaičiuojama nuo bazinės linijos.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Išskirtinė ekonominė zona',
    'verdict_zone2_body' => 'EEZ — pakrantės valstybė šioje zonoje turi suvereniąsias teises į išteklius.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentinis šelfas (daugiausia, jūrmylės)',
    'verdict_zone3_body' => 'Teisės į jūros dugno išteklius pagal nustatytas geologines sąlygas.',
    'verdict_foot' => 'Šiame teisiniame pagrinde „istorinės teisės“, apimančios visą atvirą jūrą — kaip leidžia suprasti Devynių brūkšnių linija — <em>buvo pakeistos</em> UNCLOS teisiniu režimu, kurio šalis yra ir pati Kinija.',
];
