<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Tarptautinis arbitražo sprendimas',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trys „Ne“',
    'verdict_lead' => '2016 m. liepos 12 d. Nuolatinis arbitražo teismas (PCA) Hagoje — sudarytas pagal UNCLOS VII priedą ir nagrinėjęs Filipinų bylą prieš Kiniją — paskelbė sprendimą, kuriuo atmetė Devynių brūkšnių linijos pretenzijas. <em>Spustelėkite kiekvieną kortelę, kad perskaitytumėte visą tekstą.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'istorinės teisės',
    'verdict_card1_short' => 'Kinija neturi teisinio pagrindo remtis istorinėmis teisėmis į išteklius jūroje, patenkančioje į Devynių brūkšnių liniją.',
    'verdict_card1_quote' => '„Nėra teisinio pagrindo Kinijai remtis istorinėmis teisėmis į išteklius jūroje, esančioje Devynių brūkšnių linijoje.“',
    'verdict_card1_more' => '+ Skaityti sprendimą',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'objektas, kuris sukuria EEZ',
    'verdict_card2_short' => 'Nė vienas objektas Spratlio salose neatitinka sąlygų sukurti išskirtinę ekonominę zoną Kinijai — net ir Taipingo sala.',
    'verdict_card2_quote' => '„Nė vienas objektas Spratlio salose negali sukurti išskirtinės ekonominės zonos.“',
    'verdict_card2_more' => '+ Skaityti sprendimą',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'teisėti veiksmai',
    'verdict_card3_short' => 'Kinija pažeidė Filipinų suverenias teises, trukdė žvejybai ir pakenkė jūros aplinkai.',
    'verdict_card3_quote' => '„Kinija pažeidė Filipinų suverenias teises, kišosi į žvejybą Scarborough seklumoje ir padarė rimtą žalą koralinių rifų aplinkai.“',
    'verdict_card3_more' => '+ Skaityti sprendimą',
    'verdict_extra1' => 'Kinijos pačios nubrėžta Devynių brūkšnių linija <strong>neatitinka</strong> 1982 m. UNCLOS.',
    'verdict_extra2' => 'Kinija padarė žalą Spratlio salų ekosistemai dėl pernelyg intensyvios gavybos ir dirbtinių salų statybos.',
    'verdict_extra3' => 'Kinijos veiksmai didino konflikto su Filipinais riziką.',
    'verdict_extra4' => 'Taipingo sala (kontroliuojama Taivano) taip pat negali sukurti EEZ.',
    'verdict_subtitle' => 'Kodėl tai prieštarauja UNCLOS?',
    'verdict_subtitle_body' => '1982 m. UNCLOS aiškiai nustato jūrų zonas pagal pakrantės valstybės bazines linijas. Devynių brūkšnių linijos pretenzija peržengia šią sistemą, todėl jų negalima sutapatinti.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritorinė jūra (jūrmylės)',
    'verdict_zone1_body' => 'Valstybės suverenitetą turinti jūros zona, skaičiuojama nuo bazinės linijos.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Išskirtinė ekonominė zona',
    'verdict_zone2_body' => 'EEZ — pakrantės valstybė šioje zonoje turi suverenią teisę į išteklius.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentinis šelfas (maks., jūrmylės)',
    'verdict_zone3_body' => 'Teisės į jūros dugno išteklius, nustatomos pagal geologines sąlygas.',
    'verdict_foot' => 'Šiame kontekste „istorinės teisės“, apimančios visą atvirą jūrą — kaip numano Devynių brūkšnių linija — <em>buvo pakeistos</em> UNCLOS teisiniu režimu, kurio šalis yra ir Kinija.',
];
