<?php

return [
    'witnesses_index' => 'Senoviniai žemėlapiai',
    'witnesses_label' => 'Senoviniai Kinijos žemėlapiai',
    'witnesses_title' => 'Pietinė riba siekia tik',
    'witnesses_title_accent' => 'Hainano salą',
    'witnesses_lead' => 'Senoviniai žemėlapiai, kuriuos sudarė Kinijos autoriai ir kurie išdėstyti chronologine tvarka, visi rodo, kad <em>Hainano sala yra piečiausias Kinijos taškas</em>, o Paracelio salos ir Spratlio salos juose nevaizduojamos. Medžiaga parengta pagal leidinį <em>Vietnamo valstybės suverenitetas Paracelio salos ir Spratlio salos salynuose</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Naudoti didinamąjį stiklą',
    'witnesses_map1_svg_hainan' => 'Hainanas 海南',
    'witnesses_map1_svg_south' => '— piečiausias teritorijos taškas —',
    'witnesses_map1_svg_era' => 'Songų dinastija · 1136',
    'witnesses_map1_title' => 'Songų dinastijos žemėlapis, 1136',
    'witnesses_map1_body' => 'Kinijos teritorija baigiasi prie Hainano salos — Paracelio ir Spratlio salos yra už valstybės ribų.',
    'witnesses_map2_svg_hainan' => 'Hainanas',
    'witnesses_map2_svg_south' => 'd\'Anville riba',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville žemėlapis, 1735',
    'witnesses_map2_body' => 'Nubraižė J.-B. B. d\'Anville; 1740 m. kopiją Vokietijos kancleris padovanojo Kinijos vadovybei. Čingų dinastijos teritorija baigėsi ties Hainanu.',
    'witnesses_map3_svg_hainan' => '海南 Hainanas',
    'witnesses_map3_svg_south' => '„piečiausias Kinijos taškas“',
    'witnesses_map3_svg_era' => 'Imperatoriškosios dinastijos provincijų atlasas · 1904',
    'witnesses_map3_title' => 'Imperatoriškosios dinastijos provincijų geografijos išsamus atlasas',
    'witnesses_map3_body' => 'Išleistas Čingų dinastijos — aiškiai nurodo, kad piečiausias Kinijos teritorijos taškas yra Hainano sala.',
    'witnesses_quote' => 'Net pačios Kinijos paskelbtuose žemėlapiuose Paracelio salos ir Spratlio salos nebuvo pavaizduotos kaip jos teritorijos dalis.',
    'witnesses_timeline_aria' => 'Senovinių Kinijos žemėlapių laiko juosta',
    'witnesses_year_aria' => 'Laikotarpis',
    'lightbox_aria' => 'Peržiūrėti padidintą vaizdą',
    'lightbox_close' => 'Uždaryti',
    'lightbox_prev' => 'Ankstesnis vaizdas',
    'lightbox_next' => 'Kitas vaizdas',
];
