<?php

return [
    'footer_index' => 'Bibliothek',
    'footer_crest_eyebrow' => 'Schluss mit der Bibliothek der Wahrheit',
    'footer_crest_quote' => '„Der Frieden im Südchinesischen Meer beruht auf den Grundlagen des <b>Völkerrechts</b>.“',
    'footer_crest_sub' => 'Kein Hass · Nur die Wahrheit',
    'footer_nav_aria' => 'Aktionen im Footer',
    'footer_btn_top' => 'Zurück nach oben',
    'footer_btn_verdict' => 'PCA-Urteil 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Neun-Striche-Linie',
    'footer_brand_body' => 'Eine Erklärseite, die auf objektiver Wahrheit, internationalem Recht und historischen Dokumenten basiert — und die Ansprüche der Neun-Striche-Linie mit Beweisen widerlegt, nicht mit Schlagworten.',
    'footer_refs_title' => 'Quellen',
    'footer_ref1' => 'PCA-Urteil, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — Volltext',
    'footer_ref3' => 'Limits in the Seas Nr. 143 (US DoS)',
    'footer_ref4' => 'Historische Dokumente & alte Karten',
    'footer_toc_title' => 'Inhaltsverzeichnis',
    'footer_toc1' => 'Was die Neun-Striche-Linie ist',
    'footer_toc2' => 'Ursprung',
    'footer_toc3' => 'Warum sie umstritten ist',
    'footer_toc4' => 'Warum sie international abgelehnt wird',
    'footer_toc5' => 'Stumme Zeugen',
    'footer_toc6' => 'PCA-Urteil 2016',
    'footer_toc7' => 'Paracel-Inseln – Spratly-Inseln',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Objektive Wahrheit über das Südchinesische Meer.<br>Ökosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Keine Koordinaten',
];
