<?php

return [
    'footer_index' => 'Bibliothek',
    'footer_crest_eyebrow' => 'Bibliothek der Wahrheiten abschließen',
    'footer_crest_quote' => '„Der Frieden im Südchinesischen Meer gründet sich auf <b>internationalem Recht</b>."',
    'footer_crest_sub' => 'Kein Hass · Nur die Wahrheit',
    'footer_nav_aria' => 'Footer-Aktionen',
    'footer_btn_top' => 'Zum Seitenanfang',
    'footer_btn_verdict' => 'PCA-Schiedsspruch 2016',
    'footer_btn_paracel' => 'paracelislands.net/de',
    'footer_brand_gold' => 'Anspruch auf die Neun-Striche-Linie',
    'footer_brand_eyebrow' => 'Themenseite · Souveränität Vietnams',
    'footer_brand_body' => 'Erklärt die Neun-Striche-Linie anhand objektiver Fakten, des internationalen Rechts, des PCA-Schiedsspruchs von 2016 und historischer Quellen — als Ergänzung zu den vertieften Seiten zur Souveränität über die beiden Inselgruppen <strong>"Paracel-Inseln und Spratly-Inseln"</strong>. Widerlegt die unvernünftigen Ansprüche Chinas mit Geschichte und Belegen.',
    'footer_refs_title' => 'Quellen',
    'footer_ref1' => 'PCA-Schiedsspruch, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — Volltext',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Historische Quellen & alte Karten',
    'footer_toc_title' => 'Seiteninhalt',
    'footer_toc1' => 'Was ist die Neun-Striche-Linie',
    'footer_toc2' => 'Ursprung',
    'footer_toc3' => 'Warum sie umstritten ist',
    'footer_toc4' => 'Warum die internationale Gemeinschaft sie ablehnt',
    'footer_toc5' => 'Stumme Zeugen',
    'footer_toc6' => 'PCA-Schiedsspruch 2016',
    'footer_toc7' => 'Paracel-Inseln – Spratly-Inseln',
    'footer_copy_eyebrow' => 'Gemeinnütziges Projekt',
    'footer_copy_title' => 'Paracel-Inseln – Spratly-Inseln gehören zu Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Themenseite über die Neun-Striche-Linie im Souveränitäts-Ökosystem Vietnams.',
    'footer_copy_body' => 'Erklärt die Ansprüche der Neun-Striche-Linie durch <strong>objektive Fakten</strong>, <strong>internationales Recht</strong>, den PCA-Schiedsspruch von 2016 und historische Quellen — als Ergänzung zu den vertieften Seiten zur Souveränität über die Paracel-Inseln und die Spratly-Inseln.',
    'footer_copy_ecosystem_aria' => 'Weitere Seiten dieses Projekts',
    'footer_copy_ecosystem_label' => 'Dasselbe Ökosystem',
    'footer_copy_disclaimer' => 'Die Inhalte dienen der Bildung und Sensibilisierung; sie ersetzen nicht die offizielle Position des Staates Vietnam.',
    'footer_copy' => '<strong>© :year Neun-Striche-Linie</strong> — Teil des gemeinnützigen Projekts <strong>Paracel-Inseln – Spratly-Inseln gehören zu Vietnam</strong> im Netzwerk: <a href="https://paracelislands.net/de" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/de" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/de" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/de" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/de" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Verpflichtungen zum Seiteninhalt',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA-Schiedsspruch 2016',
    'footer_chip3' => 'Historische Belege',
    'footer_chip4' => 'Alte Karten',
    'footer_chip5' => 'Objektive Fakten',
    'footer_chip6' => 'Frieden im Südchinesischen Meer',
];
