<?php

return [
    'nav_logo_name' => 'Neun-Striche-Linie',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Neun-Striche-Linie',
    'nav_rail_aria' => 'Navigation nach Themen',
    'nav_rail_what' => 'Definition',
    'nav_rail_origin' => 'Ursprung',
    'nav_rail_dispute' => 'Streit',
    'nav_rail_opposition' => 'Widerspruch',
    'nav_rail_witnesses' => 'Historische Karten',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Paracel-Inseln – Spratly-Inseln',
    'nav_sound_off' => 'Hintergrundmusik einschalten',
    'nav_sound_on' => 'Hintergrundmusik ausschalten',
    'nav_share' => 'Teilen',
    'dialog_title' => 'Anzeigesprache',
    'language' => 'Sprache',
    'display_hint' => ':count Sprachen',
    'search_placeholder' => 'Sprache suchen…',
    'cancel' => 'Abbrechen',
    'apply' => 'Anwenden',
    'sound_off' => 'Hintergrundmusik einschalten',
    'sound_on' => 'Hintergrundmusik ausschalten',
    'lang_trigger' => 'Sprache wählen',
    'close' => 'Schließen',
    'no_results' => 'Keine Sprache gefunden',
    'contribute' => 'Teilen',
];
