<?php

return [
    'opposition_index' => 'Einwände',
    'opposition_label' => 'Warum die internationale Gemeinschaft widerspricht',
    'opposition_title' => 'Widerspruch basiert auf',
    'opposition_title_accent' => 'Recht, nicht auf Gefühlen',
    'opposition_lead' => 'Unmittelbar nachdem die Neun-Striche-Linie 2009 bei den Vereinten Nationen vorgelegt worden war, erhoben zahlreiche Staaten und Wissenschaftler Einspruch — mit konkreten rechtlichen Argumenten.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesien',
    'opposition_voice1_body' => 'Nur einen Tag nachdem China die Karte der Neun-Striche-Linie dem Generalsekretär der Vereinten Nationen vorgelegt hatte (7.5.2009), sandten diese Staaten nacheinander diplomatische Noten des Protests und wiesen die Ansprüche zurück.',
    'opposition_voice1_chip1' => 'Protestnote',
    'opposition_voice1_chip2' => 'Unvereinbar mit UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippinen',
    'opposition_voice2_body' => 'Es wurde ein diplomatisches Schreiben an die Vereinten Nationen gesandt, in dem erklärt wurde, Chinas Anspruch im Südchinesischen Meer sei „völkerrechtlich unbegründet“ — eine Grundlage für die spätere Klage vor dem Schiedsgericht.',
    'opposition_voice2_chip1' => 'Grundlage der PCA-Klage',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Außenministerium der Vereinigten Staaten — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Die Analyse zeigt: Karten aus verschiedenen Jahren weichen hinsichtlich der Lage der Grenzlinie voneinander ab; die Linie greift ins Festland ein, statt eine Mittellinie zu bilden; viele Objekte erfüllen nicht die Kriterien einer „Insel“, um eine EEZ zu begründen.',
    'opposition_voice3_chip1' => 'Erfüllt die rechtlichen Voraussetzungen nicht',
    'opposition_voice3_chip2' => 'Offizielle Analyse',
    'opposition_voice4_year' => 'Akademisch',
    'opposition_voice4_title' => '„Historische Gewässer“ sind überholt',
    'opposition_voice4_body' => 'Dieses Konzept gilt nur für Buchten und küstennahe Gewässer — es kann nicht ein ganzes ausgedehntes offenes Seegebiet abdecken. Im Jahr 2003 wies auch Taiwan selbst die 1993 formulierte Politik der „historischen Gewässer“ zurück.',
    'opposition_voice4_chip1' => 'Nicht einmal chinesische Wissenschaftler sind sich einig',
];
