<?php

return [
    'opposition_index' => 'Opposition',
    'opposition_label' => 'Warum die internationale Gemeinschaft widerspricht',
    'opposition_title' => 'Widerspruch basiert auf',
    'opposition_title_accent' => 'dem Recht, nicht auf Gefühlen',
    'opposition_lead' => 'Unmittelbar nachdem die Neun-Striche-Linie 2009 bei den Vereinten Nationen vorgelegt wurde, widersprachen zahlreiche Staaten und Wissenschaftler — mit konkreten rechtlichen Argumenten.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesien',
    'opposition_voice1_body' => 'Bereits einen Tag nachdem China die Karte der Neun-Striche-Linie beim Generalsekretär der Vereinten Nationen eingereicht hatte (7.5.2009), sandten diese Länder nacheinander Protestnoten und wiesen den Anspruch zurück.',
    'opposition_voice1_chip1' => 'Protestnote',
    'opposition_voice1_chip2' => 'Unvereinbar mit UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Philippinen',
    'opposition_voice2_body' => 'Übermittelte ein diplomatisches Schreiben an die Vereinten Nationen und erklärte, Chinas Anspruch im Südchinesischen Meer sei „völkerrechtlich unbegründet“ — die Grundlage für die spätere Klage vor dem Schiedsgericht.',
    'opposition_voice2_chip1' => 'Grundlage der PCA-Klage',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'US-Außenministerium — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Die Analyse zeigt: Karten aus verschiedenen Jahren sind hinsichtlich der Lage der Grenzlinie inkonsistent; die Grenzlinie greift ins Festland ein statt einer Mittellinie zu folgen; viele Merkmale erfüllen nicht die Kriterien für eine „Insel“, um eine EEZ zu begründen.',
    'opposition_voice3_chip1' => 'Rechtlich nicht erfüllt',
    'opposition_voice3_chip2' => 'Offizielle Analyse',
    'opposition_voice4_year' => 'Akademisch',
    'opposition_voice4_title' => '„Historische Gewässer“ sind veraltet',
    'opposition_voice4_body' => 'Dieses Konzept gilt nur für Buchten und küstennahe Gewässer — es kann nicht ein ganzes ausgedehntes offenes Seegebiet umfassen. Im Jahr 2003 wies auch Taiwan selbst die 1993 formulierte Politik der „historischen Gewässer“ zurück.',
    'opposition_voice4_chip1' => 'Selbst chinesische Wissenschaftler sind sich nicht einig',
];
