<?php

return [
    'sovereignty_index' => 'Paracel-Inseln – Spratly-Inseln',
    'sovereignty_label' => 'Die zwingende Schlussfolgerung',
    'sovereignty_title' => 'Paracel-Inseln – Spratly-Inseln',
    'sovereignty_title_accent' => 'gehören zu Vietnam',
    'sovereignty_lead' => 'Diese Seite erläutert die Neun-Striche-Linie. Der Schlussabschnitt beantwortet die nächste Frage: Wer hat die Souveränität über die beiden Archipele Paracel-Inseln und Spratly-Inseln? Nach historischer Verwaltung und Völkerrecht lautet die konsistente Antwort: Vietnam.',
    'sovereignty_thesis_label' => 'Zusammengeführtes Argument',
    'sovereignty_thesis_lock1' => 'Keine rechtliche Verortung',
    'sovereignty_thesis_lock2' => 'PCA 2016 verworfen',
    'sovereignty_thesis_lock3' => 'Alte Karten decken es nicht ab',
    'sovereignty_thesis_body' => 'Nach den sechs Abschnitten oben sind drei Punkte klar: Die Neun-Striche-Linie ist handgezeichnet und ohne rechtliche Koordinaten; der Schiedshof von 2016 hat den Anspruch verworfen; alte Karten Chinas selbst decken das Südchinesische Meer nicht ab. Vietnams Souveränität beruht nicht auf Parolen, sondern darauf, dass der vietnamesische Staat — seit der Zeit der Nguyễn-Herrscher — die Inselgruppen friedlich und kontinuierlich verwaltet hat, als sie noch Niemandsland waren.',
    'sovereignty_spine_caption' => 'Stationen kontinuierlicher Verwaltung',
    'sovereignty_spine_title' => 'Eine durchgehende, ununterbrochene Zeitleiste',
    'sovereignty_spine_range' => '17. Jahrhundert → heute',
    'sovereignty_chron1_year' => '17. Jh.',
    'sovereignty_chron1_title' => 'Die Hoang-Sa-Truppe',
    'sovereignty_chron1_body' => 'Die Nguyễn-Herrscher entsandten die Hoang-Sa-Truppe zur Erkundung, Vermessung der Schifffahrtswege und Nutzung auf See — die Ausübung tatsächlicher Verwaltung.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'König Gia Long',
    'sovereignty_chron2_body' => 'Er hisste auf den Paracel-Inseln die Flagge und bekräftigte Vietnams Souveränität vor der damaligen Welt.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'König Minh Mạng',
    'sovereignty_chron3_body' => 'Vermessung, Errichtung von Markierungen und Aufnahme der Inseln in die offiziellen Karten des Hofes.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuität der Nachfolge',
    'sovereignty_chron4_body' => 'Frankreich erkannte dies an und setzte die Verwaltung fort; die Paracel-Inseln wurden in die Provinz Thừa Thiên eingegliedert — die Grundlage für den heutigen Staat Vietnam.',
    'sovereignty_chron5_year' => 'Heute',
    'sovereignty_chron5_title' => 'Recht und Praxis',
    'sovereignty_chron5_body' => 'Vietnam verwaltet gemäß UNCLOS, Diplomatie und Archivunterlagen; der Anspruch der Neun-Striche-Linie kann diese Beweise nicht ersetzen.',
    'sovereignty_balance_label' => 'Abgleich der Beweise',
    'sovereignty_balance_medallion_title' => 'Die beiden Seiten gegenübergestellt',
    'sovereignty_vn_tag' => 'Die Seite Vietnams',
    'sovereignty_vn_title' => 'Souveränität durch Handlungen begründet',
    'sovereignty_vn_body' => 'Tatsächliche Inbesitznahme, als das Land noch Niemandsland war, danach über Jahrhunderte offene Verwaltung — mit Kaiserlichen Erlassen, Steinen, Karten und Verwaltungsakten. Diese Vorgehensweise entspricht UNCLOS und der internationalen Praxis.',
    'sovereignty_dash_tag' => 'Die Seite der Neun-Striche-Linie',
    'sovereignty_dash_title' => 'Ein Anspruch ersetzt keine Beweise',
    'sovereignty_dash_body' => 'Eine im Jahr 1948 gezeichnete Linie ohne Koordinaten wurde 2016 vom PCA verworfen und steht im Widerspruch zu UNCLOS — wie in den Abschnitten 03 bis 06 dargestellt. Deshalb kann die Schlussfolgerung zur Souveränität über die beiden Archipele nicht auf der Neun-Striche-Linie beruhen.',
    'sovereignty_seal_quote' => 'Vietnam löst Streitigkeiten mit <strong>friedlichen Mitteln</strong> auf der Grundlage des Völkerrechts — insbesondere von UNCLOS 1982 — mit dem Ziel eines friedlichen, kooperativen und entwicklungsorientierten Südchinesischen Meeres.',
    'sovereignty_seal_cite' => 'Vietnams Standpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hauptprojekt im selben Ökosystem',
    'sovereignty_next_title' => 'Die vollständigen Belege zu den Paracel-Inseln – Spratly-Inseln lesen',
    'sovereignty_next_body' => 'Das detaillierte Dossier — Dokumente, Karten, Zeitleisten und rechtliche Argumente — befindet sich auf <strong>paracelislands.net</strong>, wo das Thema der Souveränität über die beiden Archipele umfassend dargestellt wird. Die Seite, die Sie gerade lesen, verbindet nur logisch die Neun-Striche-Linie mit dieser Schlussfolgerung.',
    'sovereignty_next_cta' => 'paracelislands.net öffnen',
];
