<?php

return [
    'sovereignty_index' => 'Paracel-Inseln – Spratly-Inseln',
    'sovereignty_label' => 'Unausweichliche Schlussfolgerung',
    'sovereignty_title' => 'Paracel-Inseln – Spratly-Inseln',
    'sovereignty_title_accent' => 'gehören zu Vietnam',
    'sovereignty_lead' => 'Diese Seite erklärt die Neun-Striche-Linie. Der abschließende Teil beantwortet die nächste Frage: Wem gehören die beiden Inselgruppen Paracel-Inseln und Spratly-Inseln? Nach historischer Verwaltung und internationalem Recht lautet die konsistente Antwort: Vietnam.',
    'sovereignty_thesis_label' => 'Zusammengeführte These',
    'sovereignty_thesis_lock1' => 'Keine rechtliche Verortung',
    'sovereignty_thesis_lock2' => 'PCA 2016 verworfen',
    'sovereignty_thesis_lock3' => 'Antike Karten decken es nicht ab',
    'sovereignty_thesis_body' => 'Nach den sechs Abschnitten oben sind drei Punkte klar: Die Neun-Striche-Linie ist handgezeichnet und hat keine rechtlichen Koordinaten; das Schiedsgericht 2016 hat den Anspruch verworfen; und die alten Karten Chinas selbst decken das Südchinesische Meer nicht ab. Vietnams Souveränität beruht nicht auf Parolen, sondern darauf, dass der vietnamesische Staat — seit der Zeit der Nguyễn-Herrscher — die beiden Inselgruppen friedlich und kontinuierlich verwaltet hat, als sie noch herrenloses Land waren.',
    'sovereignty_spine_caption' => 'Meilensteine kontinuierlicher Verwaltung',
    'sovereignty_spine_title' => 'Eine ununterbrochene Zeitlinie',
    'sovereignty_spine_range' => '17. Jahrhundert → heute',
    'sovereignty_chron1_year' => '17. Jh.',
    'sovereignty_chron1_title' => 'Die Hoang-Sa-Teams',
    'sovereignty_chron1_body' => 'Die Nguyễn-Herrscher entsandten die Hoang-Sa-Teams zur Erkundung, Vermessung von Seewegen und Nutzung auf See — als Ausübung tatsächlicher Verwaltungshoheit.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'König Gia Long',
    'sovereignty_chron2_body' => 'Er hisste die Flagge auf den Paracel-Inseln und bestätigte Vietnams Souveränität vor der damaligen Welt.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'König Minh Mạng',
    'sovereignty_chron3_body' => 'Vermessen, Gedenksteine errichtet und die Inselgruppen auf den offiziellen Karten des Hofes verzeichnet.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Kontinuität der Nachfolge',
    'sovereignty_chron4_body' => 'Frankreich erkannte dies an und führte die Verwaltung fort; die Eingliederung der Paracel-Inseln in die Provinz Thừa Thiên — eine Grundlage für den heutigen vietnamesischen Staat.',
    'sovereignty_chron5_year' => 'Heute',
    'sovereignty_chron5_title' => 'Recht und Praxis',
    'sovereignty_chron5_body' => 'Vietnam verwaltet im Einklang mit UNCLOS, Diplomatie und Archivunterlagen; der Anspruch der Neun-Striche-Linie kann diese Beweise nicht ersetzen.',
    'sovereignty_balance_label' => 'Beweisgleichgewicht',
    'sovereignty_balance_medallion_title' => 'Zwei Seiten gegenübergestellt',
    'sovereignty_vn_tag' => 'Vietnamesische Seite',
    'sovereignty_vn_title' => 'Souveränität durch Handlungen begründet',
    'sovereignty_vn_body' => 'Tatsächliche Besitzergreifung, als das Land noch herrenlos war, danach über Jahrhunderte öffentliche Verwaltung — mit kaiserlichen Dokumenten, Steinen, Karten und Verwaltungsakten. Dieses Vorgehen steht im Einklang mit UNCLOS und internationaler Praxis.',
    'sovereignty_dash_tag' => 'Seite der Neun-Striche-Linie',
    'sovereignty_dash_title' => 'Ein Anspruch ersetzt keine Beweise',
    'sovereignty_dash_body' => 'Eine 1948 gezeichnete Linie ohne Koordinaten wurde von der PCA 2016 verworfen und steht im Widerspruch zu UNCLOS — wie in den Abschnitten 03 bis 06 dargestellt. Deshalb kann die Schlussfolgerung zur Souveränität über die beiden Inselgruppen nicht auf der Neun-Striche-Linie beruhen.',
    'sovereignty_seal_quote' => 'Vietnam löst Streitigkeiten mit <strong>friedlichen Mitteln</strong> auf der Grundlage des internationalen Rechts — insbesondere UNCLOS 1982 — mit dem Ziel eines friedlichen, kooperativen und entwicklungsorientierten Südchinesischen Meeres.',
    'sovereignty_seal_cite' => 'Vietnams Standpunkt · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Hauptprojekt im selben Ökosystem',
    'sovereignty_next_title' => 'Lesen Sie die vollständigen Belege zu den Paracel-Inseln – Spratly-Inseln',
    'sovereignty_next_body' => 'Die ausführliche Dokumentation — Quellen, Karten, Zeitleiste und rechtliche Argumente — finden Sie auf <strong>paracelislands.net</strong>, wo das Thema der Souveränität über die beiden Inselgruppen umfassend dargestellt wird. Die Seite, die Sie gerade lesen, verbindet die Logik von der Neun-Striche-Linie bis zu dieser Schlussfolgerung.',
    'sovereignty_next_cta' => 'paracelislands.net öffnen',
];
