<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internationales Urteil',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'die drei „Nein“',
    'verdict_lead' => 'Am 12. Juli 2016 erließ der Ständige Schiedshof (PCA) in Den Haag — eingesetzt nach Anhang VII des UNCLOS, im Verfahren der Philippinen gegen China — ein Urteil, das die Ansprüche der Neun-Striche-Linie zurückwies. <em>Klicken Sie auf jede Karte, um den vollständigen Wortlaut zu lesen.</em>',
    'verdict_card1_khong' => 'KEIN',
    'verdict_card1_title' => 'historisches Recht',
    'verdict_card1_short' => 'Es gibt keine rechtliche Grundlage dafür, dass China historische Rechte an den Ressourcen in den Gewässern innerhalb der Neun-Striche-Linie geltend macht.',
    'verdict_card1_quote' => '„Es gibt keine rechtliche Grundlage dafür, dass China historische Rechte an den Ressourcen in den Gewässern innerhalb der Neun-Striche-Linie geltend macht.“',
    'verdict_card1_more' => '+ Urteil lesen',
    'verdict_card2_khong' => 'KEIN',
    'verdict_card2_title' => 'Objekt zur Schaffung einer AWZ',
    'verdict_card2_short' => 'Kein Merkmal der Spratly-Inseln erfüllt die Voraussetzungen, um für China eine ausschließliche Wirtschaftszone zu begründen — auch nicht die Insel Ba Bình.',
    'verdict_card2_quote' => '„Kein Merkmal der Spratly-Inseln ist in der Lage, eine ausschließliche Wirtschaftszone zu schaffen.“',
    'verdict_card2_more' => '+ Urteil lesen',
    'verdict_card3_khong' => 'KEIN',
    'verdict_card3_title' => 'rechtmäßiges Verhalten',
    'verdict_card3_short' => 'China verletzte die souveränen Rechte der Philippinen, behinderte die Fischerei und schädigte die Meeresumwelt.',
    'verdict_card3_quote' => '„China hat die souveränen Rechte der Philippinen verletzt, in die Fischerei am Scarborough-Riff eingegriffen und das Korallenriff-Ökosystem erheblich geschädigt.“',
    'verdict_card3_more' => '+ Urteil lesen',
    'verdict_extra1' => 'Die von China selbst gezogene Neun-Striche-Linie ist <strong>nicht vereinbar</strong> mit dem UNCLOS von 1982.',
    'verdict_extra2' => 'China verursacht durch Übernutzung und den Bau künstlicher Inseln Schäden am Ökosystem der Spratly-Inseln.',
    'verdict_extra3' => 'Chinas Handlungen erhöhen das Konfliktrisiko mit den Philippinen.',
    'verdict_extra4' => 'Auch die Insel Ba Bình (unter Kontrolle Taiwans) kann keine AWZ begründen.',
    'verdict_subtitle' => 'Warum steht es im Widerspruch zum UNCLOS?',
    'verdict_subtitle_body' => 'Das UNCLOS von 1982 legt die Meereszonen klar auf der Grundlage der Basislinien des Küstenstaats fest. Der Anspruch der Neun-Striche-Linie geht über diesen Rahmen hinaus und kann daher nicht daneben bestehen.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Hoheitsgewässer (Seemeilen)',
    'verdict_zone1_body' => 'Das unter staatlicher Souveränität stehende Küstenmeer, gemessen ab der Basislinie.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Ausschließliche Wirtschaftszone',
    'verdict_zone2_body' => 'AWZ — der Küstenstaat hat innerhalb dieses Bereichs souveräne Rechte an den Ressourcen.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Festlandsockel (max., Seemeilen)',
    'verdict_zone3_body' => 'Rechte an den Meeresbodenressourcen, je nach den festgelegten geologischen Bedingungen.',
    'verdict_foot' => 'In diesem Rahmen wurde das Konzept der „historischen Rechte“, das eine ganze offene Meeresfläche — wie sie die Neun-Striche-Linie nahelegt — umfasst, <em>durch die Rechtsordnung des UNCLOS ersetzt</em>, dem auch China selbst beigetreten ist.',
];
