<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Internationale Entscheidung',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'drei „Nein“',
    'verdict_lead' => 'Am 12.07.2016 erließ das Ständige Schiedsgericht (PCA) in Den Haag — eingesetzt nach Anhang VII des UNCLOS, im Verfahren Philippinen gegen China — ein Urteil, das den Anspruch der Neun-Striche-Linie zurückwies. <em>Klicken Sie auf jede Kachel, um den vollständigen Wortlaut zu lesen.</em>',
    'verdict_card1_khong' => 'NEIN',
    'verdict_card1_title' => 'historische Rechte',
    'verdict_card1_short' => 'Es gibt keine rechtliche Grundlage dafür, dass China historische Rechte an Ressourcen in den innerhalb der Neun-Striche-Linie liegenden Gewässern geltend macht.',
    'verdict_card1_quote' => '„Es gibt keine rechtliche Grundlage dafür, dass China historische Rechte an den Ressourcen in den Gewässern innerhalb der Neun-Striche-Linie geltend macht.“',
    'verdict_card1_more' => '+ Urteil lesen',
    'verdict_card2_khong' => 'NEIN',
    'verdict_card2_title' => 'ein EEZ-bildendes Merkmal',
    'verdict_card2_short' => 'Kein Merkmal der Spratly-Inseln erfüllt die Voraussetzungen, um für China eine ausschließliche Wirtschaftszone zu begründen — auch nicht die Insel Ba Bình.',
    'verdict_card2_quote' => '„Kein Merkmal der Spratly-Inseln ist in der Lage, eine ausschließliche Wirtschaftszone zu begründen.“',
    'verdict_card2_more' => '+ Urteil lesen',
    'verdict_card3_khong' => 'NEIN',
    'verdict_card3_title' => 'rechtmäßiges Verhalten',
    'verdict_card3_short' => 'China verletzte die souveränen Rechte von Vietnam, behinderte die Fischerei und schädigte die Meeresumwelt.',
    'verdict_card3_quote' => '„China hat die souveränen Rechte Vietnams verletzt, in die Fischereitätigkeit an der Scarborough-Bank eingegriffen und das Korallenriff-Ökosystem schwer geschädigt.“',
    'verdict_card3_more' => '+ Urteil lesen',
    'verdict_extra1' => 'Die von China selbst gezeichnete Neun-Striche-Linie <strong>steht nicht im Einklang</strong> mit dem UNCLOS von 1982.',
    'verdict_extra2' => 'China verursachte Schäden am Ökosystem der Spratly-Inseln durch Übernutzung und den Bau künstlicher Inseln.',
    'verdict_extra3' => 'Die Handlungen Chinas erhöhen das Risiko eines Konflikts mit den Philippinen.',
    'verdict_extra4' => 'Auch die Insel Ba Bình (von Taiwan kontrolliert) kann keine EEZ begründen.',
    'verdict_subtitle' => 'Warum kollidiert sie mit dem UNCLOS?',
    'verdict_subtitle_body' => 'Das UNCLOS von 1982 legt die Meereszonen klar auf Grundlage der Basislinie des Küstenstaates fest. Der Anspruch der Neun-Striche-Linie geht über diesen Rahmen hinaus und lässt sich daher nicht damit vereinbaren.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Territorialgewässer (Seemeilen)',
    'verdict_zone1_body' => 'Ein Küstenmeer unter staatlicher Souveränität, gemessen von der Basislinie aus.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Ausschließliche Wirtschaftszone',
    'verdict_zone2_body' => 'EEZ — der Küstenstaat hat in diesem Bereich souveräne Rechte an den Ressourcen.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Festlandsockel (max., Seemeilen)',
    'verdict_zone3_body' => 'Rechte an den Ressourcen des Meeresbodens, vorbehaltlich geologisch bestimmter Voraussetzungen.',
    'verdict_foot' => 'In diesem Rahmen wurde das Konzept der „historischen Rechte“, das einen ganzen offenen Meeresraum — wie von der Neun-Striche-Linie angedeutet — umfassen würde, <em>durch das Rechtsregime des UNCLOS ersetzt</em>, dem auch China selbst beigetreten ist.',
];
