<?php

return [
    'witnesses_index' => 'Historische Karten',
    'witnesses_label' => 'Historische Karten Chinas',
    'witnesses_title' => 'Bis zum äußersten Süden reicht nur',
    'witnesses_title_accent' => 'die Insel Hainan',
    'witnesses_lead' => 'Die von chinesischen Autoren gezeichneten historischen Karten — chronologisch geordnet — zeigen alle <em>die Insel Hainan als den südlichsten Punkt</em> Chinas; weder die Paracel-Inseln noch die Spratly-Inseln sind enthalten. Die Zusammenstellung basiert auf <em>Nationalsovereänität Vietnams über die beiden Inselgruppen Paracel und Spratly</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Lupe einsetzen',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— südlichster Punkt des Staatsgebiets —',
    'witnesses_map1_svg_era' => 'Song-Dynastie · 1136',
    'witnesses_map1_title' => 'Karte der Song-Dynastie, 1136',
    'witnesses_map1_body' => 'Das Staatsgebiet Chinas endete auf der Insel Hainan — die Paracel-Inseln und die Spratly-Inseln lagen außerhalb des Herrschaftsgebiets.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'd\'Anvilles Grenze',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Karte von d\'Anville, 1735',
    'witnesses_map2_body' => 'Von J.-B. B. d\'Anville gezeichnet; eine Kopie von 1740 wurde einst vom deutschen Bundeskanzler an den chinesischen Staatschef verschenkt. Das Territorium der Qing-Dynastie endete in Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"südlichster Punkt Chinas"',
    'witnesses_map3_svg_era' => 'Großes Qing-Atlas · 1904',
    'witnesses_map3_title' => 'Geographischer Gesamtatlas der Großen Qing-Dynastie',
    'witnesses_map3_body' => 'Von der Qing-Dynastie gedruckt — er vermerkt ausdrücklich die Insel Hainan als südlichsten Punkt des Staatsgebiets Chinas.',
    'witnesses_quote' => 'Gerade die von China selbst veröffentlichten Karten haben die Paracel-Inseln und Spratly-Inseln nie in ihr Hoheitsgebiet eingezeichnet.',
    'witnesses_timeline_aria' => 'Zeitachse historischer chinesischer Karten',
    'witnesses_year_aria' => 'Datierung',
    'lightbox_aria' => 'Vergrößertes Bild ansehen',
    'lightbox_close' => 'Schließen',
    'lightbox_prev' => 'Vorheriges Bild',
    'lightbox_next' => 'Nächstes Bild',
];
