<?php

return [
    'footer_index' => 'Biblioteka',
    'footer_crest_eyebrow' => 'Finał biblioteki prawdy',
    'footer_crest_quote' => '„Pokój na Morzu Południowochińskim opiera się na <b>prawie międzynarodowym</b>.”',
    'footer_crest_sub' => 'Bez nienawiści · Tylko prawda',
    'footer_nav_aria' => 'Działania w stopce',
    'footer_btn_top' => 'Na górę strony',
    'footer_btn_verdict' => 'Wyrok PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Roszczenia do Linia dziewięciu kresek',
    'footer_brand_eyebrow' => 'Strona tematyczna · Suwerenność Wietnamu',
    'footer_brand_body' => 'Wyjaśnienie Linii dziewięciu kresek poprzez obiektywną prawdę, prawo międzynarodowe, wyrok PCA z 2016 roku i materiały historyczne — uzupełnienie dla stron pogłębionych poświęconych suwerenności nad dwoma archipelagami <strong>"Wyspy Paracelskie i Wyspy Spratly"</strong>. Odrzuca bezpodstawne roszczenia Chin poprzez historię i dowody.',
    'footer_refs_title' => 'Źródła',
    'footer_ref1' => 'Wyrok PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — pełny tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Materiały historyczne i stare mapy',
    'footer_toc_title' => 'Spis treści strony',
    'footer_toc1' => 'Czym jest Linia dziewięciu kresek',
    'footer_toc2' => 'Pochodzenie',
    'footer_toc3' => 'Dlaczego budzi spory',
    'footer_toc4' => 'Dlaczego społeczność międzynarodowa się sprzeciwia',
    'footer_toc5' => 'Milczący świadkowie',
    'footer_toc6' => 'Wyrok PCA 2016',
    'footer_toc7' => 'Wyspy Paracelskie – Wyspy Spratly',
    'footer_copy_eyebrow' => 'Projekt non-profit',
    'footer_copy_title' => 'Wyspy Paracelskie – Wyspy Spratly należą do Wietnamu',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Strona tematyczna poświęcona Linii dziewięciu kresek w ekosystemie suwerenności Wietnamu.',
    'footer_copy_body' => 'Wyjaśnienie roszczeń Linii dziewięciu kresek poprzez <strong>obiektywną prawdę</strong>, <strong>prawo międzynarodowe</strong>, wyrok PCA z 2016 roku i materiały historyczne — uzupełnienie dla stron pogłębionych poświęconych suwerenności nad archipelagami Wyspy Paracelskie i Wyspy Spratly.',
    'footer_copy_ecosystem_aria' => 'Strony tego samego projektu',
    'footer_copy_ecosystem_label' => 'W tym samym ekosystemie',
    'footer_copy_disclaimer' => 'Treść ma charakter edukacyjny i służy zwiększaniu świadomości; nie zastępuje oficjalnego stanowiska państwa Wietnam.',
    'footer_copy' => '<strong>© :year Linia dziewięciu kresek</strong> — Część projektu non-profit <strong>Wyspy Paracelskie – Wyspy Spratly należą do Wietnamu</strong> w ramach systemu: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Zobowiązanie do treści strony',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Wyrok PCA 2016',
    'footer_chip3' => 'Dowody historyczne',
    'footer_chip4' => 'Stare mapy',
    'footer_chip5' => 'Obiektywna prawda',
    'footer_chip6' => 'Pokój na Morzu Południowochińskim',
];
