<?php

return [
    'footer_index' => 'Biblioteka',
    'footer_crest_eyebrow' => 'Zamykając bibliotekę prawdy',
    'footer_crest_quote' => '„Pokój na Morzu Południowochińskim opiera się na fundamentach <b>prawa międzynarodowego</b>.”',
    'footer_crest_sub' => 'Bez nienawiści · Tylko prawda',
    'footer_nav_aria' => 'Akcje w stopce',
    'footer_btn_top' => 'Na górę strony',
    'footer_btn_verdict' => 'Wyrok PCA z 2016 r.',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linia dziewięciu kresek',
    'footer_brand_body' => 'Strona wyjaśniająca, oparta na obiektywnej prawdzie, prawie międzynarodowym i materiałach historycznych — obala roszczenia dotyczące Linii dziewięciu kresek dowodami, a nie hasłami.',
    'footer_refs_title' => 'Źródła odniesienia',
    'footer_ref1' => 'Wyrok PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — pełny tekst',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Materiały historyczne i dawne mapy',
    'footer_toc_title' => 'Spis treści strony',
    'footer_toc1' => 'Czym jest Linia dziewięciu kresek',
    'footer_toc2' => 'Pochodzenie',
    'footer_toc3' => 'Dlaczego budzi spory',
    'footer_toc4' => 'Dlaczego społeczność międzynarodowa się sprzeciwia',
    'footer_toc5' => 'Milczący świadkowie',
    'footer_toc6' => 'Wyrok PCA 2016',
    'footer_toc7' => 'Wyspy Paracelskie – Wyspy Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Obiektywna prawda o Morzu Południowochińskim.<br>Ekosystem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Bez współrzędnych',
];
