<?php

return [
    'nav_logo_name' => 'Linia dziewięciu kresek',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linia dziewięciu kresek',
    'nav_rail_aria' => 'Nawigacja według sekcji',
    'nav_rail_what' => 'Definicja',
    'nav_rail_origin' => 'Pochodzenie',
    'nav_rail_dispute' => 'Spór',
    'nav_rail_opposition' => 'Sprzeciw',
    'nav_rail_witnesses' => 'Mapy historyczne',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Wyspy Paracelskie – Wyspy Spratly',
    'nav_sound_off' => 'Włącz muzykę w tle',
    'nav_sound_on' => 'Wyłącz muzykę w tle',
    'nav_share' => 'Udostępnij',
    'dialog_title' => 'Język wyświetlania',
    'language' => 'Język',
    'display_hint' => ':count języków',
    'search_placeholder' => 'Szukaj języka…',
    'cancel' => 'Anuluj',
    'apply' => 'Zastosuj',
    'sound_off' => 'Włącz dźwięk w tle',
    'sound_on' => 'Wyłącz dźwięk w tle',
    'lang_trigger' => 'Wybierz język',
    'close' => 'Zamknij',
    'no_results' => 'Nie znaleziono języka',
    'contribute' => 'Udostępnij',
];
