<?php

return [
    'opposition_index' => 'Sprzeciw',
    'opposition_label' => 'Dlaczego społeczność międzynarodowa się sprzeciwia',
    'opposition_title' => 'Sprzeciw opiera się na',
    'opposition_title_accent' => 'prawie, nie na emocjach',
    'opposition_lead' => 'Już po przedstawieniu Linia dziewięciu kresek w Organizacji Narodów Zjednoczonych w 2009 roku wiele państw i środowisk akademickich zgłosiło sprzeciw — oparty na konkretnych argumentach prawnych.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maj',
    'opposition_voice1_title' => 'Wietnam · Malezja · Indonezja',
    'opposition_voice1_body' => 'Zaledwie dzień po tym, jak Chiny przedstawiły mapę Linii dziewięciu kresek Sekretarzowi Generalnemu Organizacji Narodów Zjednoczonych (7/5/2009), państwa te kolejno przesłały noty protestacyjne, odrzucając to roszczenie.',
    'opposition_voice1_chip1' => 'Nota protestacyjna',
    'opposition_voice1_chip2' => 'Niezgodne z UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipiny',
    'opposition_voice2_body' => 'Przesłano pismo dyplomatyczne do Organizacji Narodów Zjednoczonych, stwierdzając, że chińskie roszczenia na Morzu Południowochińskim są „bez podstaw w prawie międzynarodowym” — co stało się podstawą późniejszego postępowania przed trybunałem arbitrażowym.',
    'opposition_voice2_chip1' => 'Podstawa sprawy PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departament Stanu USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiza wykazała: mapy z różnych lat są niespójne co do położenia linii granicznej; linia wkracza na ląd zamiast przebiegać wzdłuż linii środkowej; wiele obiektów nie spełnia kryteriów „wyspy”, aby mieć EEZ.',
    'opposition_voice3_chip1' => 'Nie spełnia warunków prawnych',
    'opposition_voice3_chip2' => 'Oficjalna analiza',
    'opposition_voice4_year' => 'Akademickie',
    'opposition_voice4_title' => '„Wody historyczne” są przestarzałe',
    'opposition_voice4_body' => 'Koncepcja ta ma zastosowanie jedynie do zatok i akwenów przybrzeżnych — nie może obejmować całego rozległego morza otwartego. W 2003 roku nawet Tajwan odrzucił politykę „wód historycznych” ogłoszoną wcześniej w 1993 roku.',
    'opposition_voice4_chip1' => 'Nawet chińscy badacze nie są zgodni',
];
