<?php

return [
    'opposition_index' => 'Sprzeciw',
    'opposition_label' => 'Dlaczego społeczność międzynarodowa się sprzeciwia',
    'opposition_title' => 'Sprzeciw opiera się na',
    'opposition_title_accent' => 'prawie, nie na emocjach',
    'opposition_lead' => 'Zaraz po tym, jak Linia dziewięciu kresek została przedstawiona Organizacji Narodów Zjednoczonych w 2009 roku, wiele państw i środowisk naukowych wyraziło sprzeciw — przedstawiając konkretne argumenty prawne.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maj',
    'opposition_voice1_title' => 'Wietnam · Malezja · Indonezja',
    'opposition_voice1_body' => 'Już dzień po tym, jak Chiny przedstawiły mapę Linii dziewięciu kresek Sekretarzowi Generalnemu ONZ (7.05.2009), kraje te kolejno przesłały noty protestacyjne, odrzucając roszczenia.',
    'opposition_voice1_chip1' => 'Nota protestacyjna',
    'opposition_voice1_chip2' => 'Niezgodne z UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipiny',
    'opposition_voice2_body' => 'Przesłały notę dyplomatyczną do ONZ, stwierdzając, że roszczenia Chin na Morzu Południowochińskim są „pozbawione podstaw w prawie międzynarodowym” — co stało się podstawą późniejszej sprawy przed Trybunałem Arbitrażowym.',
    'opposition_voice2_chip1' => 'Podstawa sprawy przed PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departament Stanu USA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiza wykazała: mapy z różnych lat nie były spójne co do położenia linii granicznej; linia wkraczała w głąb lądu zamiast przebiegać wzdłuż linii środkowej; wiele formacji nie spełniało kryteriów „wyspy”, by posiadać EEZ.',
    'opposition_voice3_chip1' => 'Nie spełnia warunków prawnych',
    'opposition_voice3_chip2' => 'Oficjalna analiza',
    'opposition_voice4_year' => 'Nauka',
    'opposition_voice4_title' => '„Wody historyczne” są anachroniczne',
    'opposition_voice4_body' => 'To pojęcie ma zastosowanie jedynie do zatok i akwenów przybrzeżnych — nie może obejmować całego rozległego morza otwartego. W 2003 roku również Tajwan odrzucił politykę „wód historycznych” ogłoszoną wcześniej w 1993 roku.',
    'opposition_voice4_chip1' => 'Nawet chińscy badacze nie są zgodni',
];
