<?php

return [
    'sovereignty_index' => 'Wyspy Paracelskie - Wyspy Spratly',
    'sovereignty_label' => 'Wniosek nieuchronny',
    'sovereignty_title' => 'Wyspy Paracelskie - Wyspy Spratly',
    'sovereignty_title_accent' => 'należą do Wietnamu',
    'sovereignty_lead' => 'Ta strona wyjaśnia Linię dziewięciu kresek. Część końcowa odpowiada na kolejne pytanie: kto ma suwerenność nad dwoma archipelagami, Wyspami Paracelskimi i Wyspami Spratly? Zgodnie z historią administracji i prawem międzynarodowym, odpowiedź jest spójna: Wietnam.',
    'sovereignty_thesis_label' => 'Teza zbiorcza',
    'sovereignty_thesis_lock1' => 'Brak współrzędnych prawnych',
    'sovereignty_thesis_lock2' => 'PCA 2016 odrzucił',
    'sovereignty_thesis_lock3' => 'Stare mapy nie obejmują',
    'sovereignty_thesis_body' => 'Po sześciu powyższych częściach trzy rzeczy są jasne: Linia dziewięciu kresek została narysowana odręcznie i nie ma współrzędnych prawnych; Trybunał Arbitrażowy w 2016 roku odrzucił to roszczenie; stare mapy samej strony chińskiej nie obejmują Morza Południowochińskiego. Suwerenność Wietnamu nie opiera się na haśle, lecz na tym, że państwo wietnamskie — od czasów dynastii Nguyễn — sprawowało pokojową i ciągłą administrację, gdy oba archipelagi były jeszcze terra nullius.',
    'sovereignty_spine_caption' => 'Punkt ciągłej administracji',
    'sovereignty_spine_title' => 'Jedna oś czasu, bez przerwy',
    'sovereignty_spine_range' => 'XVII wiek → dziś',
    'sovereignty_chron1_year' => 'XVII w.',
    'sovereignty_chron1_title' => 'Flota Hoàng Sa',
    'sovereignty_chron1_body' => 'Lordowie Nguyễn wysyłali flotę Hoàng Sa do badań, pomiarów tras morskich i eksploatacji na morzu — wykonywając faktyczne uprawnienia administracyjne.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Król Gia Long',
    'sovereignty_chron2_body' => 'Podniósł flagę na archipelagu Wysp Paracelskich, potwierdzając suwerenność Wietnamu wobec ówczesnego świata.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Król Minh Mạng',
    'sovereignty_chron3_body' => 'Dokonywano pomiarów, wznoszono stele i odnotowywano archipelag na oficjalnych mapach dworu.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Ciągłość następstwa',
    'sovereignty_chron4_body' => 'Francja uznała i kontynuowała administrację; przyłączono Wyspy Paracelskie do prowincji Thừa Thiên — co stało się podstawą dla dzisiejszego Państwa Wietnam.',
    'sovereignty_chron5_year' => 'Dziś',
    'sovereignty_chron5_title' => 'Prawo i praktyka',
    'sovereignty_chron5_body' => 'Wietnam sprawuje administrację zgodnie z UNCLOS, dyplomacją i archiwami; roszczenie Linii dziewięciu kresek nie może zastąpić tych dowodów.',
    'sovereignty_balance_label' => 'Równowaga dowodów',
    'sovereignty_balance_medallion_title' => 'Zestawienie obu stron',
    'sovereignty_vn_tag' => 'Strona wietnamska',
    'sovereignty_vn_title' => 'Suwerenność ustanowiona przez akty',
    'sovereignty_vn_body' => 'Rzeczywiste zajęcie, gdy ziemia była jeszcze niczyja, a następnie jawna administracja przez wiele stuleci — z cesarskimi dekretami, stelami, mapami i dokumentami administracyjnymi. Takie działanie jest zgodne z UNCLOS i praktyką międzynarodową.',
    'sovereignty_dash_tag' => 'Strona Linii dziewięciu kresek',
    'sovereignty_dash_title' => 'Roszczenie nie zastępuje dowodów',
    'sovereignty_dash_body' => 'Jedna linia narysowana w 1948 roku, bez współrzędnych, została odrzucona przez PCA w 2016 roku i jest sprzeczna z UNCLOS — jak wykazały części 03 do 06. Dlatego wniosek o suwerenności nad dwoma archipelagami nie może opierać się na Linii dziewięciu kresek.',
    'sovereignty_seal_quote' => 'Wietnam rozstrzyga spory za pomocą <strong>środków pokojowych</strong>, na podstawie prawa międzynarodowego — zwłaszcza UNCLOS 1982 — dążąc do Morza Południowochińskiego jako obszaru pokoju, współpracy i rozwoju.',
    'sovereignty_seal_cite' => 'Stanowisko Wietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Główny projekt w tym samym ekosystemie',
    'sovereignty_next_title' => 'Przeczytaj pełne dowody dotyczące Wysp Paracelskich - Wysp Spratly',
    'sovereignty_next_body' => 'Szczegółowe dossier — dokumenty, mapy, oś czasu i argumenty prawne — znajduje się na stronie <strong>paracelislands.net</strong>, gdzie kompleksowo przedstawiono temat suwerenności nad dwoma archipelagami. Strona, którą właśnie czytasz, łączy logicznie Linię dziewięciu kresek z tym wnioskiem.',
    'sovereignty_next_cta' => 'Otwórz paracelislands.net',
];
