<?php

return [
    'sovereignty_index' => 'Wyspy Paracelskie – Wyspy Spratly',
    'sovereignty_label' => 'Wniosek konieczny',
    'sovereignty_title' => 'Wyspy Paracelskie – Wyspy Spratly',
    'sovereignty_title_accent' => 'należą do Wietnamu',
    'sovereignty_lead' => 'Ta strona wyjaśnia Linię dziewięciu kresek. Część końcowa odpowiada na kolejne pytanie: kto ma suwerenność nad dwoma archipelagami, Wyspami Paracelskimi i Wyspami Spratly? Z perspektywy historii administracji i prawa międzynarodowego odpowiedź jest spójna: Wietnam.',
    'sovereignty_thesis_label' => 'Teza zbiorcza',
    'sovereignty_thesis_lock1' => 'Brak współrzędnych prawnych',
    'sovereignty_thesis_lock2' => 'PCA 2016 odrzucił',
    'sovereignty_thesis_lock3' => 'Stare mapy nie obejmują',
    'sovereignty_thesis_body' => 'Po sześciu powyższych częściach trzy kwestie stają się jasne: Linia dziewięciu kresek została narysowana odręcznie i nie ma współrzędnych prawnych; Trybunał Arbitrażowy w 2016 roku odrzucił to roszczenie; a stare mapy samego Chin nie obejmują Morza Południowochińskiego. Suwerenność Wietnamu nie opiera się na sloganach, lecz na fakcie, że państwo wietnamskie — od czasów władców z dynastii Nguyễn — zarządzało tym obszarem pokojowo i w sposób ciągły, gdy oba archipelagi były jeszcze ziemią niczyją.',
    'sovereignty_spine_caption' => 'Kamienie milowe ciągłego zarządzania',
    'sovereignty_spine_title' => 'Jedna, nieprzerwana oś czasu',
    'sovereignty_spine_range' => 'XVII wiek → dziś',
    'sovereignty_chron1_year' => 'XVII w.',
    'sovereignty_chron1_title' => 'Oddział Hoàng Sa',
    'sovereignty_chron1_body' => 'Władcy z dynastii Nguyễn wysyłali oddział Hoàng Sa do badań, pomiarów szlaków morskich i działalności na morzu — wykonując faktyczne uprawnienia administracyjne.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Król Gia Long',
    'sovereignty_chron2_body' => 'Wbił flagę na archipelagu Wysp Paracelskich, potwierdzając suwerenność Wietnamu wobec ówczesnego świata.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Król Minh Mạng',
    'sovereignty_chron3_body' => 'Przeprowadzono pomiary, wzniesiono stele i odnotowano archipelag na oficjalnych mapach dworu.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Ciągłość sukcesji',
    'sovereignty_chron4_body' => 'Francja uznała i kontynuowała administrację; włączono Wyspy Paracelskie do prowincji Thừa Thiên — to podstawa dla dzisiejszego Państwa Wietnam.',
    'sovereignty_chron5_year' => 'Obecnie',
    'sovereignty_chron5_title' => 'Prawo i praktyka',
    'sovereignty_chron5_body' => 'Wietnam zarządza zgodnie z UNCLOS, dyplomacją i archiwami; roszczenie oparte na Linii dziewięciu kresek nie może zastąpić tych dowodów.',
    'sovereignty_balance_label' => 'Równowaga dowodów',
    'sovereignty_balance_medallion_title' => 'Porównanie obu stron',
    'sovereignty_vn_tag' => 'Strona Wietnamu',
    'sovereignty_vn_title' => 'Suwerenność ustanowiona czynem',
    'sovereignty_vn_body' => 'Rzeczywiste zawłaszczenie, gdy ziemia była jeszcze niczyja, a następnie jawne zarządzanie przez kolejne stulecia — z cesarskimi dokumentami, stelami, mapami i aktami administracyjnymi. Takie działanie jest zgodne z UNCLOS i praktyką międzynarodową.',
    'sovereignty_dash_tag' => 'Strona Linii dziewięciu kresek',
    'sovereignty_dash_title' => 'Roszczenie nie zastępuje dowodów',
    'sovereignty_dash_body' => 'Linia narysowana w 1948 roku, bez współrzędnych, została odrzucona przez PCA w 2016 roku i jest sprzeczna z UNCLOS — jak pokazano w częściach 03–06. Dlatego wniosku o suwerenności nad dwoma archipelagami nie można opierać na Linii dziewięciu kresek.',
    'sovereignty_seal_quote' => 'Wietnam rozwiązuje spory za pomocą <strong>środków pokojowych</strong>, na podstawie prawa międzynarodowego — zwłaszcza UNCLOS 1982 — dążąc do Morza Południowochińskiego pokojowego, współpracy i rozwoju.',
    'sovereignty_seal_cite' => 'Stanowisko Wietnamu · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Główny projekt w tym samym ekosystemie',
    'sovereignty_next_title' => 'Przeczytaj pełny materiał dowodowy o Wyspach Paracelskich – Wyspach Spratly',
    'sovereignty_next_body' => 'Szczegółowe dossier — dokumenty, mapy, oś czasu i argumentacja prawna — znajduje się na stronie <strong>paracelislands.net</strong>, gdzie kompleksowo przedstawiono temat suwerenności nad dwoma archipelagami. Strona, którą właśnie czytasz, łączy logicznie Linię dziewięciu kresek z tym wnioskiem.',
    'sovereignty_next_cta' => 'Otwórz paracelislands.net',
];
