<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Orzeczenie międzynarodowe',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trzy „nie”',
    'verdict_lead' => '12 lipca 2016 r. Stały Trybunał Arbitrażowy (PCA) w Hadze — powołany na podstawie załącznika VII do UNCLOS, w sprawie Filipiny przeciwko Chinom — wydał orzeczenie odrzucające roszczenia związane z Linią dziewięciu kresek. <em>Kliknij każdą kartę, aby przeczytać pełny tekst.</em>',
    'verdict_card1_khong' => 'NIE',
    'verdict_card1_title' => 'praw historycznych',
    'verdict_card1_short' => 'Nie ma podstaw prawnych, by Chiny powoływały się na prawa historyczne do zasobów wód znajdujących się wewnątrz Linii dziewięciu kresek.',
    'verdict_card1_quote' => '“Nie ma podstaw prawnych, by Chiny powoływały się na prawa historyczne do zasobów znajdujących się w wodach wewnątrz Linii dziewięciu kresek.”',
    'verdict_card1_more' => '+ Przeczytaj orzeczenie',
    'verdict_card2_khong' => 'NIE',
    'verdict_card2_title' => 'obiektów tworzących EEZ',
    'verdict_card2_short' => 'Żaden obiekt na Wyspach Spratly nie spełnia warunków, by tworzyć wyłączną strefę ekonomiczną dla Chin — w tym Skała / wyspa Ba Bình.',
    'verdict_card2_quote' => '“Żaden obiekt na Wyspach Spratly nie ma zdolności do tworzenia wyłącznej strefy ekonomicznej.”',
    'verdict_card2_more' => '+ Przeczytaj orzeczenie',
    'verdict_card3_khong' => 'NIE',
    'verdict_card3_title' => 'legalnych działań',
    'verdict_card3_short' => 'Chiny naruszyły suwerenne prawa Filipin, utrudniały połowy i szkodziły środowisku morskiemu.',
    'verdict_card3_quote' => '“Chiny naruszyły suwerenne prawa Filipin, ingerowały w działalność połowową na ławicy Scarborough i poważnie szkodziły środowisku raf koralowych.”',
    'verdict_card3_more' => '+ Przeczytaj orzeczenie',
    'verdict_extra1' => 'Linia dziewięciu kresek wyrysowana przez Chiny <strong>nie jest zgodna</strong> z UNCLOS z 1982 r.',
    'verdict_extra2' => 'Chiny wyrządziły szkody ekosystemom Wysp Spratly poprzez nadmierną eksploatację i budowę sztucznych wysp.',
    'verdict_extra3' => 'Działania Chin zwiększają ryzyko konfliktu z Filipinami.',
    'verdict_extra4' => 'Wyspa Ba Bình (kontrolowana przez Tajwan) również nie może tworzyć EEZ.',
    'verdict_subtitle' => 'Dlaczego to stoi w sprzeczności z UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS z 1982 r. jasno wyznacza strefy morskie na podstawie linii bazowych państwa nadbrzeżnego. Roszczenia związane z Linią dziewięciu kresek wykraczają poza te ramy, dlatego nie dają się z nimi pogodzić.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Morze terytorialne (mile morskie)',
    'verdict_zone1_body' => 'Strefa morza państwowego objęta suwerennością, liczona od linii bazowej.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Wyłączna strefa ekonomiczna',
    'verdict_zone2_body' => 'EEZ — państwo nadbrzeżne ma w tej strefie suwerenne prawa do zasobów.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Szelf kontynentalny (maks., mile morskie)',
    'verdict_zone3_body' => 'Prawa do zasobów dna morskiego, zgodnie z określonymi warunkami geologicznymi.',
    'verdict_foot' => 'W tym systemie „prawa historyczne” obejmujące całe morze otwarte — tak jak sugeruje to Linia dziewięciu kresek — <em>zostały zastąpione</em> przez reżim prawny UNCLOS, którego Chiny są również stroną.',
];
