<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Wyrok międzynarodowy',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trzy „Nie”',
    'verdict_lead' => '12 lipca 2016 r. Stały Trybunał Arbitrażowy (PCA) w Hadze — ustanowiony zgodnie z załącznikiem VII do UNCLOS, w sprawie Filipiny przeciwko Chinom — wydał orzeczenie odrzucające roszczenia Linia dziewięciu kresek. <em>Kliknij każdą kartę, aby przeczytać pełny tekst.</em>',
    'verdict_card1_khong' => 'NIE',
    'verdict_card1_title' => 'praw historycznych',
    'verdict_card1_short' => 'Nie ma podstaw prawnych, aby Chiny powoływały się na prawa historyczne do zasobów wód leżących w obrębie Linii dziewięciu kresek.',
    'verdict_card1_quote' => '„Nie ma podstaw prawnych dla tego, by Chiny powoływały się na prawa historyczne do zasobów znajdujących się w wodach wewnątrz Linii dziewięciu kresek.”',
    'verdict_card1_more' => '+ Przeczytaj orzeczenie',
    'verdict_card2_khong' => 'NIE',
    'verdict_card2_title' => 'obiektów tworzących WSE',
    'verdict_card2_short' => 'Żaden obiekt na Wyspach Spratly nie spełnia warunków tworzenia wyłącznej strefy ekonomicznej dla Chin — w tym także wyspa Ba Bình.',
    'verdict_card2_quote' => '„Żaden obiekt na Wyspach Spratly nie ma zdolności do tworzenia wyłącznej strefy ekonomicznej.”',
    'verdict_card2_more' => '+ Przeczytaj orzeczenie',
    'verdict_card3_khong' => 'NIE',
    'verdict_card3_title' => 'legalnych działań',
    'verdict_card3_short' => 'Chiny naruszyły prawa suwerenne Filipin, utrudniały połowy ryb i szkodziły środowisku morskiemu.',
    'verdict_card3_quote' => '„Chiny naruszyły prawa suwerenne Filipin, ingerowały w połowy ryb na ławicy Scarborough i poważnie szkodziły środowisku raf koralowych.”',
    'verdict_card3_more' => '+ Przeczytaj orzeczenie',
    'verdict_extra1' => 'Linia dziewięciu kresek narysowana jednostronnie przez Chiny <strong>nie jest zgodna</strong> z UNCLOS 1982.',
    'verdict_extra2' => 'Chiny wyrządziły szkody ekosystemowi Wysp Spratly poprzez nadmierną eksploatację i budowę sztucznych wysp.',
    'verdict_extra3' => 'Działania Chin zwiększają ryzyko konfliktu z Filipinami.',
    'verdict_extra4' => 'Wyspa Ba Bình (kontrolowana przez Tajwan) również nie może tworzyć WSE.',
    'verdict_subtitle' => 'Dlaczego jest to sprzeczne z UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 wyraźnie wyznacza strefy morskie na podstawie linii podstawowych państwa nadbrzeżnego. Roszczenie Linii dziewięciu kresek wykracza poza te ramy, więc nie można go z nimi pogodzić.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Morze terytorialne (mil morskich)',
    'verdict_zone1_body' => 'Wody państwowe pod suwerennością, liczone od linii podstawowych.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Wyłączna strefa ekonomiczna',
    'verdict_zone2_body' => 'WSE — państwo nadbrzeżne ma w tym obszarze suwerenne prawa do zasobów.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Szelf kontynentalny (maks., mil morskich)',
    'verdict_zone3_body' => 'Prawa do zasobów dna morskiego, zgodnie z określonymi warunkami geologicznymi.',
    'verdict_foot' => 'W tym systemie „prawa historyczne” obejmujące całe otwarte morze — jak sugeruje Linia dziewięciu kresek — <em>zostały zastąpione</em> przez reżim prawny UNCLOS, którego Chiny również są stroną.',
];
