<?php

return [
    'footer_index' => 'کتابخانه',
    'footer_crest_eyebrow' => 'جمع‌بندی کتابخانه حقیقت',
    'footer_crest_quote' => '«صلح در دریای چین جنوبی بر پایهٔ <b>حقوق بین‌الملل</b> بنا می‌شود.»',
    'footer_crest_sub' => 'نه نفرت · فقط حقیقت',
    'footer_nav_aria' => 'اقدامات پایین صفحه',
    'footer_btn_top' => 'بازگشت به بالا',
    'footer_btn_verdict' => 'رأی PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'ادعای خط نه‌خطی',
    'footer_brand_eyebrow' => 'صفحهٔ تخصصی · حاکمیت ویتنام',
    'footer_brand_body' => 'توضیح خط نه‌خطی از طریق حقیقت عینی، حقوق بین‌الملل، رأی PCA 2016 و اسناد تاریخی — به‌عنوان مکملی برای صفحات تخصصی دربارهٔ حاکمیت دو مجمع‌الجزایر <strong>"جزایر پاراسل و جزایر اسپراتلی"</strong>. ردّ ادعای بی‌پایهٔ چین با تاریخ و شواهد.',
    'footer_refs_title' => 'منابع',
    'footer_ref1' => 'رأی PCA، 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — متن کامل',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'اسناد تاریخی و نقشه‌های قدیمی',
    'footer_toc_title' => 'فهرست مطالب صفحه',
    'footer_toc1' => 'خط نه‌خطی چیست',
    'footer_toc2' => 'خاستگاه',
    'footer_toc3' => 'چرا محل مناقشه است',
    'footer_toc4' => 'چرا جامعهٔ بین‌المللی مخالفت می‌کند',
    'footer_toc5' => 'شاهدان خاموش',
    'footer_toc6' => 'رأی PCA 2016',
    'footer_toc7' => 'جزایر پاراسل – جزایر اسپراتلی',
    'footer_copy_eyebrow' => 'پروژهٔ غیرانتفاعی',
    'footer_copy_title' => 'جزایر پاراسل – جزایر اسپراتلی متعلق به ویتنام است',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — صفحهٔ تخصصی دربارهٔ خط نه‌خطی در اکوسیستم حاکمیت ویتنام.',
    'footer_copy_body' => 'ادعای خط نه‌خطی از طریق <strong>حقیقت عینی</strong>، <strong>حقوق بین‌الملل</strong>، رأی PCA 2016 و اسناد تاریخی توضیح داده می‌شود — به‌عنوان مکملی برای صفحات تخصصی دربارهٔ حاکمیت دو مجمع‌الجزایر پاراسل و اسپراتلی.',
    'footer_copy_ecosystem_aria' => 'صفحات هم‌پروژه',
    'footer_copy_ecosystem_label' => 'در همان اکوسیستم',
    'footer_copy_disclaimer' => 'محتوا با هدف آموزش و افزایش آگاهی ارائه شده است؛ جایگزین موضع رسمی دولت ویتنام نیست.',
    'footer_copy' => '<strong>© :year خط نه‌خطی</strong> — بخشی از پروژهٔ غیرانتفاعی <strong>جزایر پاراسل – جزایر اسپراتلی متعلق به ویتنام است</strong> در مجموعهٔ: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'تعهد محتوای صفحه',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'رأی PCA 2016',
    'footer_chip3' => 'شواهد تاریخی',
    'footer_chip4' => 'نقشه‌های قدیمی',
    'footer_chip5' => 'حقیقت عینی',
    'footer_chip6' => 'صلح در دریای چین جنوبی',
];
