<?php

return [
    'footer_index' => 'کتابخانه',
    'footer_crest_eyebrow' => 'نقطهٔ پایانیِ کتابخانهٔ حقیقت',
    'footer_crest_quote' => '«صلح در دریای چین جنوبی بر پایهٔ <b>حقوق بین‌الملل</b> بنا می‌شود.»',
    'footer_crest_sub' => 'نه نفرت · فقط حقیقت',
    'footer_nav_aria' => 'اقدامات پایین صفحه',
    'footer_btn_top' => 'بازگشت به بالای صفحه',
    'footer_btn_verdict' => 'رأی PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'خط نه‌خطی',
    'footer_brand_body' => 'یک صفحهٔ توضیحی مبتنی بر حقیقتِ عینی، حقوق بین‌الملل و اسناد تاریخی — که ادعای خط نه‌خطی را نه با شعار، بلکه با شواهد رد می‌کند.',
    'footer_refs_title' => 'منابع مرجع',
    'footer_ref1' => 'رأی PCA، ۱۲/۷/۲۰۱۶',
    'footer_ref2' => 'UNCLOS 1982 — متن کامل',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'اسناد تاریخی و نقشه‌های کهن',
    'footer_toc_title' => 'فهرست صفحه',
    'footer_toc1' => 'خط نه‌خطی چیست',
    'footer_toc2' => 'خاستگاه',
    'footer_toc3' => 'چرا بحث‌برانگیز است',
    'footer_toc4' => 'چرا جامعهٔ بین‌المللی مخالفت می‌کند',
    'footer_toc5' => 'شاهدان خاموش',
    'footer_toc6' => 'رأی PCA 2016',
    'footer_toc7' => 'جزایر پاراسل - جزایر اسپراتلی',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — حقیقت عینی دربارهٔ دریای چین جنوبی.<br>اکوسیستم: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'بدون مختصات',
];
