<?php

return [
    'nav_logo_name' => 'خط نه‌خطی',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'خط نه‌خطی',
    'nav_rail_aria' => 'ناوبری بر اساس بخش',
    'nav_rail_what' => 'تعریف',
    'nav_rail_origin' => 'خاستگاه',
    'nav_rail_dispute' => 'مجادله',
    'nav_rail_opposition' => 'مخالفت',
    'nav_rail_witnesses' => 'نقشه‌های قدیمی',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'جزایر پاراسل - جزایر اسپراتلی',
    'nav_sound_off' => 'موسیقی پس‌زمینه را روشن کنید',
    'nav_sound_on' => 'موسیقی پس‌زمینه را خاموش کنید',
    'nav_share' => 'اشتراک‌گذاری',
    'dialog_title' => 'زبان نمایش',
    'language' => 'زبان',
    'display_hint' => ':count زبان',
    'search_placeholder' => 'جستجوی زبان…',
    'cancel' => 'لغو',
    'apply' => 'اعمال',
    'sound_off' => 'صدای پس‌زمینه را روشن کنید',
    'sound_on' => 'صدای پس‌زمینه را خاموش کنید',
    'lang_trigger' => 'انتخاب زبان',
    'close' => 'بستن',
    'no_results' => 'زبانی یافت نشد',
    'contribute' => 'اشتراک‌گذاری',
];
