<?php

return [
    'witnesses_index' => 'نقشه‌های قدیمی',
    'witnesses_label' => 'شاهدان خاموش',
    'witnesses_title' => 'نقشه‌های قدیمیِ',
    'witnesses_title_accent' => 'خودشان',
    'witnesses_lead' => 'در طول قرن‌ها، نقشه‌های رسمی چین همواره <em>جزیره هاینان را جنوبی‌ترین نقطه</em> قلمرو خود ثبت کرده‌اند — و هیچ خط U شکلی که دریای چین جنوبی را در بر بگیرد وجود نداشته است. با ذره‌بین، به مرز جنوبی دقیق‌تر نگاه کنید.',
    'witnesses_hint' => '⌖ ذره‌بین را بررسی کنید',
    'witnesses_map1_svg_hainan' => 'هاینان 海南',
    'witnesses_map1_svg_south' => '— جنوبی‌ترین نقطه قلمرو —',
    'witnesses_map1_svg_era' => 'سلسله سونگ · 1136',
    'witnesses_map1_title' => 'نقشه سلسله سونگ، 1136',
    'witnesses_map1_body' => 'قلمرو چین تا جزیره هاینان پایان می‌یافت — جزایر پاراسل و جزایر اسپراتلی خارج از قلمرو بودند.',
    'witnesses_map2_svg_hainan' => 'هاینان',
    'witnesses_map2_svg_south' => 'مرز d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'نقشه d\'Anville، 1735',
    'witnesses_map2_body' => 'به‌دست J.-B. B. d\'Anville ترسیم شد؛ نسخهٔ 1740 آن زمانی توسط صدراعظم آلمان به رهبر چین اهدا شد. قلمرو دودمان چینگ تا هاینان امتداد داشت.',
    'witnesses_map3_svg_hainan' => '海南 هاینان',
    'witnesses_map3_svg_south' => '"جنوبی‌ترین نقطه چین"',
    'witnesses_map3_svg_era' => 'اطلس جغرافیایی استان‌های تحت اداره مستقیم امپراتوری · 1904',
    'witnesses_map3_title' => 'اطلس جغرافیایی استان‌های تحت اداره مستقیم امپراتوری',
    'witnesses_map3_body' => 'به‌دست دودمان چینگ چاپ شد — و به‌روشنی نشان می‌دهد که جنوبی‌ترین نقطه قلمرو چین، جزیره هاینان است.',
    'witnesses_quote' => 'خودِ اسناد نیاکانشان هیچ‌گاه خط نه‌خطی را ترسیم نکرده‌اند.',
];
