<?php

return [
    'footer_index' => 'Βιβλιοθήκη',
    'footer_crest_eyebrow' => 'Ολοκλήρωση της βιβλιοθήκης αλήθειας',
    'footer_crest_quote' => '«Η ειρήνη στη Θάλασσα της Νότιας Κίνας οικοδομείται πάνω στη βάση του <b>διεθνούς δικαίου</b>.»',
    'footer_crest_sub' => 'Χωρίς μίσος · Μόνο αλήθεια',
    'footer_nav_aria' => 'Τελικές ενέργειες υποσέλιδου',
    'footer_btn_top' => 'Στην κορυφή',
    'footer_btn_verdict' => 'Απόφαση PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Διεκδίκηση της Γραμμής Εννέα Παύλων',
    'footer_brand_eyebrow' => 'Θεματική σελίδα · Κυριαρχία του Βιετνάμ',
    'footer_brand_body' => 'Επεξήγηση της Γραμμής Εννέα Παύλων μέσω αντικειμενικών γεγονότων, του διεθνούς δικαίου, της απόφασης του PCA το 2016 και ιστορικών τεκμηρίων — ως συμπλήρωμα προς τις εξειδικευμένες σελίδες για την κυριαρχία των δύο νησιωτικών συμπλεγμάτων <strong>"Νησιά Παρασέλ και Νησιά Σπράτλι"</strong>. Απορρίπτει τις παράλογες διεκδικήσεις της Κίνας με ιστορία και αποδείξεις.',
    'footer_refs_title' => 'Πηγές αναφοράς',
    'footer_ref1' => 'Απόφαση PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — πλήρες κείμενο',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Ιστορικά τεκμήρια & παλιοί χάρτες',
    'footer_toc_title' => 'Πίνακας περιεχομένων',
    'footer_toc1' => 'Τι είναι η Γραμμή Εννέα Παύλων',
    'footer_toc2' => 'Προέλευση',
    'footer_toc3' => 'Γιατί προκαλεί αντιπαράθεση',
    'footer_toc4' => 'Γιατί η διεθνής κοινότητα αντιδρά',
    'footer_toc5' => 'Σιωπηλοί μάρτυρες',
    'footer_toc6' => 'Απόφαση PCA 2016',
    'footer_toc7' => 'Νησιά Παρασέλ – Νησιά Σπράτλι',
    'footer_copy_eyebrow' => 'Μη κερδοσκοπικό έργο',
    'footer_copy_title' => 'Τα Νησιά Παρασέλ – Νησιά Σπράτλι ανήκουν στο Βιετνάμ',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Θεματική σελίδα για τη Γραμμή Εννέα Παύλων στο οικοσύστημα κυριαρχίας του Βιετνάμ.',
    'footer_copy_body' => 'Επεξήγηση της διεκδίκησης της Γραμμής Εννέα Παύλων μέσω <strong>αντικειμενικών γεγονότων</strong>, <strong>διεθνούς δικαίου</strong>, της απόφασης του PCA το 2016 και ιστορικών τεκμηρίων — ως συμπλήρωμα προς τις εξειδικευμένες σελίδες για την κυριαρχία των νησιωτικών συμπλεγμάτων Παρασέλ και Σπράτλι.',
    'footer_copy_ecosystem_aria' => 'Σελίδες του ίδιου έργου',
    'footer_copy_ecosystem_label' => 'Ίδιο οικοσύστημα',
    'footer_copy_disclaimer' => 'Το περιεχόμενο προορίζεται για εκπαίδευση και ευαισθητοποίηση· δεν αντικαθιστά την επίσημη θέση του Κράτους του Βιετνάμ.',
    'footer_copy' => '<strong>© :year Γραμμή Εννέα Παύλων</strong> — Μέρος του μη κερδοσκοπικού έργου <strong>Τα Νησιά Παρασέλ – Νησιά Σπράτλι ανήκουν στο Βιετνάμ</strong> στο σύστημα: <a href="https://paracelislands.net/el" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/el" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/el" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/el" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/el" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Δέσμευση περιεχομένου της σελίδας',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Απόφαση PCA 2016',
    'footer_chip3' => 'Ιστορικά τεκμήρια',
    'footer_chip4' => 'Παλιοί χάρτες',
    'footer_chip5' => 'Αντικειμενική αλήθεια',
    'footer_chip6' => 'Ειρήνη στη Θάλασσα της Νότιας Κίνας',
];
