<?php

return [
    'footer_index' => 'Βιβλιοθήκη',
    'footer_crest_eyebrow' => 'Ολοκλήρωση της βιβλιοθήκης της αλήθειας',
    'footer_crest_quote' => '«Η ειρήνη στη Θάλασσα της Νότιας Κίνας οικοδομείται πάνω στα θεμέλια του <b>διεθνούς δικαίου</b>.»',
    'footer_crest_sub' => 'Χωρίς μίσος · Μόνο η αλήθεια',
    'footer_nav_aria' => 'Ενέργειες υποσέλιδου',
    'footer_btn_top' => 'Πάνω στην αρχή',
    'footer_btn_verdict' => 'Απόφαση PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Γραμμή Εννέα Παύλων',
    'footer_brand_body' => 'Ένας ιστότοπος που εξηγεί με βάση την αντικειμενική αλήθεια, το διεθνές δίκαιο και ιστορικά έγγραφα — αντικρούοντας τον ισχυρισμό της Γραμμής Εννέα Παύλων με αποδείξεις, όχι με συνθήματα.',
    'footer_refs_title' => 'Πηγές αναφοράς',
    'footer_ref1' => 'Απόφαση του PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — πλήρες κείμενο',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Ιστορικά τεκμήρια & παλιοί χάρτες',
    'footer_toc_title' => 'Πίνακας περιεχομένων της σελίδας',
    'footer_toc1' => 'Τι είναι η Γραμμή Εννέα Παύλων',
    'footer_toc2' => 'Προέλευση',
    'footer_toc3' => 'Γιατί προκαλεί αντιπαραθέσεις',
    'footer_toc4' => 'Γιατί το διεθνές κοινό την απορρίπτει',
    'footer_toc5' => 'Σιωπηλοί μάρτυρες',
    'footer_toc6' => 'Απόφαση PCA 2016',
    'footer_toc7' => 'Νησιά Παρασέλ – Νησιά Σπράτλι',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Αντικειμενική αλήθεια για τη Θάλασσα της Νότιας Κίνας.<br>Οικοσύστημα: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Χωρίς συντεταγμένες',
];
