<?php

return [
    'footer_index' => 'Βιβλιοθήκη',
    'footer_crest_eyebrow' => 'Κλείσιμο της βιβλιοθήκης της αλήθειας',
    'footer_crest_quote' => '«Η ειρήνη στη Νότια Σινική Θάλασσα χτίζεται πάνω στα θεμέλια του <b>διεθνούς δικαίου</b>.»',
    'footer_crest_sub' => 'Χωρίς μίσος · Μόνο η αλήθεια',
    'footer_nav_aria' => 'Ενέργειες υποσέλιδου',
    'footer_btn_top' => 'Επιστροφή στην κορυφή',
    'footer_btn_verdict' => 'Απόφαση PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Διεκδίκηση της Γραμμής Εννέα Παύλων',
    'footer_brand_eyebrow' => 'Θεματική σελίδα · Κυριαρχία του Βιετνάμ',
    'footer_brand_body' => 'Εξηγεί τη Γραμμή Εννέα Παύλων μέσω της αντικειμενικής αλήθειας, του διεθνούς δικαίου, της απόφασης PCA 2016 και ιστορικών τεκμηρίων — ως συμπλήρωμα στις εξειδικευμένες σελίδες για την κυριαρχία στα δύο αρχιπελάγη <strong>"Νησιά Παρασέλ και Νησιά Σπράτλι"</strong>. Απορρίπτει τις παράλογες αξιώσεις της Κίνας με ιστορία και αποδείξεις.',
    'footer_refs_title' => 'Πηγές αναφοράς',
    'footer_ref1' => 'Απόφαση PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — πλήρες κείμενο',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Ιστορικά τεκμήρια & παλιοί χάρτες',
    'footer_toc_title' => 'Πίνακας περιεχομένων',
    'footer_toc1' => 'Τι είναι η Γραμμή Εννέα Παύλων',
    'footer_toc2' => 'Προέλευση',
    'footer_toc3' => 'Γιατί προκαλεί αντιπαράθεση',
    'footer_toc4' => 'Γιατί η διεθνής κοινότητα αντιδρά',
    'footer_toc5' => 'Σιωπηλοί μάρτυρες',
    'footer_toc6' => 'Απόφαση PCA 2016',
    'footer_toc7' => 'Νησιά Παρασέλ – Νησιά Σπράτλι',
    'footer_copy_eyebrow' => 'Μη κερδοσκοπικό έργο',
    'footer_copy_title' => 'Τα Νησιά Παρασέλ – Νησιά Σπράτλι ανήκουν στο Βιετνάμ',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Θεματική σελίδα για τη Γραμμή Εννέα Παύλων στο οικοσύστημα κυριαρχίας του Βιετνάμ.',
    'footer_copy_body' => 'Εξηγεί τις αξιώσεις της Γραμμής Εννέα Παύλων μέσω <strong>αντικειμενικής αλήθειας</strong>, <strong>διεθνούς δικαίου</strong>, της απόφασης PCA 2016 και ιστορικών τεκμηρίων — ως συμπλήρωμα στις εξειδικευμένες σελίδες για την κυριαρχία στα δύο αρχιπελάγη Νησιά Παρασέλ και Νησιά Σπράτλι.',
    'footer_copy_ecosystem_aria' => 'Σελίδες του ίδιου έργου',
    'footer_copy_ecosystem_label' => 'Στο ίδιο οικοσύστημα',
    'footer_copy_disclaimer' => 'Το περιεχόμενο αποσκοπεί στην εκπαίδευση και την ευαισθητοποίηση· δεν αντικαθιστά την επίσημη θέση του Κράτους του Βιετνάμ.',
    'footer_copy' => '<strong>© :year Γραμμή Εννέα Παύλων</strong> — Μέρος του μη κερδοσκοπικού έργου <strong>Τα Νησιά Παρασέλ – Νησιά Σπράτλι ανήκουν στο Βιετνάμ</strong> στο σύστημα: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Δέσμευση περιεχομένου της σελίδας',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Απόφαση PCA 2016',
    'footer_chip3' => 'Ιστορικά τεκμήρια',
    'footer_chip4' => 'Παλιοί χάρτες',
    'footer_chip5' => 'Αντικειμενική αλήθεια',
    'footer_chip6' => 'Ειρήνη στη Νότια Σινική Θάλασσα',
];
