<?php

return [
    'nav_logo_name' => 'Γραμμή Εννέα Παύλων',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Γραμμή Εννέα Παύλων',
    'nav_rail_aria' => 'Πλοήγηση ανά ενότητα',
    'nav_rail_what' => 'Ορισμός',
    'nav_rail_origin' => 'Προέλευση',
    'nav_rail_dispute' => 'Διαμάχη',
    'nav_rail_opposition' => 'Αντιδράσεις',
    'nav_rail_witnesses' => 'Αρχαίοι χάρτες',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Νησιά Παρασέλ - Νησιά Σπράτλι',
    'nav_sound_off' => 'Ενεργοποίηση μουσικής υπόκρουσης',
    'nav_sound_on' => 'Απενεργοποίηση μουσικής υπόκρουσης',
    'nav_share' => 'Κοινοποίηση',
    'dialog_title' => 'Γλώσσα προβολής',
    'language' => 'Γλώσσα',
    'display_hint' => ':count γλώσσες',
    'search_placeholder' => 'Αναζήτηση γλώσσας…',
    'cancel' => 'Ακύρωση',
    'apply' => 'Εφαρμογή',
    'sound_off' => 'Ενεργοποίηση ήχου υπόκρουσης',
    'sound_on' => 'Απενεργοποίηση ήχου υπόκρουσης',
    'lang_trigger' => 'Επιλογή γλώσσας',
    'close' => 'Κλείσιμο',
    'no_results' => 'Δεν βρέθηκε γλώσσα',
    'contribute' => 'Κοινοποίηση',
];
