<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Финал на библиотеката с истината',
    'footer_crest_quote' => '„Мирът в Южнокитайско море се гради върху основата на <b>международното право</b>.“',
    'footer_crest_sub' => 'Без омраза · Само истината',
    'footer_nav_aria' => 'Действия в долната част на страницата',
    'footer_btn_top' => 'Към началото на страницата',
    'footer_btn_verdict' => 'Решението на PCA от 2016 г.',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Линията на деветте тирета',
    'footer_brand_body' => 'Обяснителен сайт, основан на обективната истина, международното право и исторически документи — опровергава претенциите по Линията на деветте тирета с доказателства, а не със лозунги.',
    'footer_refs_title' => 'Източници за справка',
    'footer_ref1' => 'Решението на PCA, 12.07.2016 г.',
    'footer_ref2' => 'UNCLOS 1982 — пълен текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Исторически материали и стари карти',
    'footer_toc_title' => 'Съдържание на страницата',
    'footer_toc1' => 'Какво е Линията на деветте тирета',
    'footer_toc2' => 'Произход',
    'footer_toc3' => 'Защо е спорна',
    'footer_toc4' => 'Защо международната общност я отхвърля',
    'footer_toc5' => 'Мълчаливи свидетели',
    'footer_toc6' => 'Решението на PCA от 2016 г.',
    'footer_toc7' => 'Параселски острови – Острови Спратли',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Обективната истина за Южнокитайско море.<br>Екосистема: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Без координати',
];
