<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Събиране на библиотеката с истина',
    'footer_crest_quote' => '„Мирът в Южнокитайско море се гради върху основата на <b>международното право</b>.“',
    'footer_crest_sub' => 'Без омраза · Само истина',
    'footer_nav_aria' => 'Действия в долната част на страницата',
    'footer_btn_top' => 'Към началото на страницата',
    'footer_btn_verdict' => 'Решение на PCA от 2016 г.',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Претенцията за Линията на деветте тирета',
    'footer_brand_eyebrow' => 'Специализирана страница · Суверенитет на Виетнам',
    'footer_brand_body' => 'Обяснение на Линията на деветте тирета чрез обективната истина, международното право, решението на PCA от 2016 г. и исторически материали — в допълнение към подробните страници за суверенитета над двата архипелага <strong>"Параселски острови и Острови Спратли"</strong>. Опровержение на неоснователните претенции на Китай чрез история и доказателства.',
    'footer_refs_title' => 'Източници',
    'footer_ref1' => 'Решение на PCA, 12.07.2016 г.',
    'footer_ref2' => 'UNCLOS 1982 — пълен текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Исторически материали и стари карти',
    'footer_toc_title' => 'Съдържание на страницата',
    'footer_toc1' => 'Какво е Линията на деветте тирета',
    'footer_toc2' => 'Произход',
    'footer_toc3' => 'Защо е спорна',
    'footer_toc4' => 'Защо международната общност се противопоставя',
    'footer_toc5' => 'Тихите свидетели',
    'footer_toc6' => 'Решение на PCA от 2016 г.',
    'footer_toc7' => 'Параселски острови – Острови Спратли',
    'footer_copy_eyebrow' => 'Нестопански проект',
    'footer_copy_title' => 'Параселски острови – Острови Спратли са на Виетнам',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Специализирана страница за Линията на деветте тирета в екосистемата на суверенитета на Виетнам.',
    'footer_copy_body' => 'Обяснение на претенцията за Линията на деветте тирета чрез <strong>обективната истина</strong>, <strong>международното право</strong>, решението на PCA от 2016 г. и исторически материали — в допълнение към подробните страници за суверенитета над архипелагите Параселски острови и Острови Спратли.',
    'footer_copy_ecosystem_aria' => 'Страници от същия проект',
    'footer_copy_ecosystem_label' => 'В същата екосистема',
    'footer_copy_disclaimer' => 'Съдържанието е предназначено за образование и повишаване на осведомеността; не замества официалната позиция на държавата Виетнам.',
    'footer_copy' => '<strong>© :year Линията на деветте тирета</strong> — Част от нестопанския проект <strong>Параселски острови – Острови Спратли са на Виетнам</strong> в рамките на системата: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Ангажимент за съдържанието на страницата',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Решение на PCA от 2016 г.',
    'footer_chip3' => 'Исторически доказателства',
    'footer_chip4' => 'Стари карти',
    'footer_chip5' => 'Обективна истина',
    'footer_chip6' => 'Мир в Южнокитайско море',
];
