<?php

return [
    'nav_logo_name' => 'Линията на деветте тирета',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Линията на деветте тирета',
    'nav_rail_aria' => 'Навигация по раздели',
    'nav_rail_what' => 'Определение',
    'nav_rail_origin' => 'Произход',
    'nav_rail_dispute' => 'Спор',
    'nav_rail_opposition' => 'Противопоставяне',
    'nav_rail_witnesses' => 'Старинни карти',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Параселски острови – Острови Спратли',
    'nav_sound_off' => 'Включи фоновата музика',
    'nav_sound_on' => 'Изключи фоновата музика',
    'nav_share' => 'Споделяне',
    'dialog_title' => 'Показван език',
    'language' => 'Език',
    'display_hint' => ':count езика',
    'search_placeholder' => 'Търсене на език…',
    'cancel' => 'Отказ',
    'apply' => 'Приложи',
    'sound_off' => 'Включи звука на фона',
    'sound_on' => 'Изключи звука на фона',
    'lang_trigger' => 'Избери език',
    'close' => 'Затвори',
    'no_results' => 'Не е намерен език',
    'contribute' => 'Споделяне',
];
