<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Завершаем библиотеку фактов',
    'footer_crest_quote' => '“Мир в Южно-Китайском море строится на основе <b>международного права</b>.”',
    'footer_crest_sub' => 'Без ненависти · Только факты',
    'footer_nav_aria' => 'Действия в нижнем колонтитуле',
    'footer_btn_top' => 'В начало страницы',
    'footer_btn_verdict' => 'Решение PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Линия девяти пунктиров',
    'footer_brand_body' => 'Пояснительный сайт, основанный на объективных фактах, международном праве и исторических материалах — опровергает притязания Линии девяти пунктиров доказательствами, а не лозунгами.',
    'footer_refs_title' => 'Источники',
    'footer_ref1' => 'Решение PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — полный текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Исторические материалы и старые карты',
    'footer_toc_title' => 'Оглавление страницы',
    'footer_toc1' => 'Что такое Линия девяти пунктиров',
    'footer_toc2' => 'Происхождение',
    'footer_toc3' => 'Почему это вызывает споры',
    'footer_toc4' => 'Почему международное сообщество возражает',
    'footer_toc5' => 'Молчаливые свидетели',
    'footer_toc6' => 'Решение PCA 2016',
    'footer_toc7' => 'Парасельские острова – Острова Спратли',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Объективная правда о Южно-Китайском море.<br>Экосистема: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Без координат',
];
