<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Завершение библиотеки фактов',
    'footer_crest_quote' => '«Мир в Южно-Китайском море строится на основе <b>международного права</b>.»',
    'footer_crest_sub' => 'Без ненависти · Только факты',
    'footer_nav_aria' => 'Действия в нижней части страницы',
    'footer_btn_top' => 'Наверх',
    'footer_btn_verdict' => 'Решение PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Претензия на Линию девяти пунктиров',
    'footer_brand_eyebrow' => 'Тематическая страница · Суверенитет Вьетнама',
    'footer_brand_body' => 'Объяснение Линии девяти пунктиров через объективные факты, международное право, решение PCA 2016 и исторические материалы — в дополнение к подробным страницам о суверенитете над двумя архипелагами <strong>"Парасельские острова и Острова Спратли"</strong>. Опровержение необоснованных претензий Китая на основе истории и доказательств.',
    'footer_refs_title' => 'Источники',
    'footer_ref1' => 'Решение PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — полный текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Исторические материалы и старые карты',
    'footer_toc_title' => 'Оглавление страницы',
    'footer_toc1' => 'Что такое Линия девяти пунктиров',
    'footer_toc2' => 'Происхождение',
    'footer_toc3' => 'Почему это вызывает споры',
    'footer_toc4' => 'Почему международное сообщество возражает',
    'footer_toc5' => 'Молчаливые свидетели',
    'footer_toc6' => 'Решение PCA 2016',
    'footer_toc7' => 'Парасельские острова – Острова Спратли',
    'footer_copy_eyebrow' => 'Некоммерческий проект',
    'footer_copy_title' => 'Парасельские острова – Острова Спратли принадлежат Вьетнаму',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — тематическая страница о Линии девяти пунктиров в экосистеме суверенитета Вьетнама.',
    'footer_copy_body' => 'Объяснение претензий Линии девяти пунктиров через <strong>объективные факты</strong>, <strong>международное право</strong>, решение PCA 2016 и исторические материалы — в дополнение к подробным страницам о суверенитете над архипелагами Парасельские острова и Острова Спратли.',
    'footer_copy_ecosystem_aria' => 'Страницы того же проекта',
    'footer_copy_ecosystem_label' => 'В одной экосистеме',
    'footer_copy_disclaimer' => 'Содержание предназначено для образования и повышения осведомленности; оно не заменяет официальную позицию государства Вьетнам.',
    'footer_copy' => '<strong>© :year Линия девяти пунктиров</strong> — часть некоммерческого проекта <strong>Парасельские острова – Острова Спратли принадлежат Вьетнаму</strong> в составе сети: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Обязательства по содержанию страницы',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Решение PCA 2016',
    'footer_chip3' => 'Исторические доказательства',
    'footer_chip4' => 'Старые карты',
    'footer_chip5' => 'Объективные факты',
    'footer_chip6' => 'Мир в Южно-Китайском море',
];
