<?php

return [
    'nav_logo_name' => 'Линия девяти пунктиров',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Линия девяти пунктиров',
    'nav_rail_aria' => 'Навигация по разделам',
    'nav_rail_what' => 'Определение',
    'nav_rail_origin' => 'Происхождение',
    'nav_rail_dispute' => 'Спор',
    'nav_rail_opposition' => 'Возражения',
    'nav_rail_witnesses' => 'Старинные карты',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Парасельские острова - Острова Спратли',
    'nav_sound_off' => 'Включить фоновую музыку',
    'nav_sound_on' => 'Выключить фоновую музыку',
    'nav_share' => 'Поделиться',
    'dialog_title' => 'Язык отображения',
    'language' => 'Язык',
    'display_hint' => ':count языков',
    'search_placeholder' => 'Поиск языка…',
    'cancel' => 'Отмена',
    'apply' => 'Применить',
    'sound_off' => 'Включить звук фона',
    'sound_on' => 'Выключить звук фона',
    'lang_trigger' => 'Выбрать язык',
    'close' => 'Закрыть',
    'no_results' => 'Язык не найден',
    'contribute' => 'Поделиться',
];
