<?php

return [
    'footer_index' => 'நூலகம்',
    'footer_crest_eyebrow' => 'உண்மை நூலகத்தின் நிறைவு',
    'footer_crest_quote' => '“தென் சீனக் கடலில் அமைதி <b>சர்வதேசச் சட்டத்தின்</b> அடித்தளத்தில் கட்டப்படுகிறது.”',
    'footer_crest_sub' => 'வெறுப்பு இல்லை · உண்மை மட்டும்',
    'footer_nav_aria' => 'பக்கத்தின் கீழ்ப்பகுதி நடவடிக்கைகள்',
    'footer_btn_top' => 'மேலே செல்ல',
    'footer_btn_verdict' => '2016 PCA தீர்ப்பு',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'ஒன்பது-கோடு கோடு உரிமைக் கோரல்',
    'footer_brand_eyebrow' => 'சிறப்பு பக்கம் · வியட்நாம் இறைமை',
    'footer_brand_body' => 'ஒன்பது-கோடு கோடு பற்றிய விளக்கத்தை நடுநிலையான உண்மை, சர்வதேசச் சட்டம், 2016 PCA தீர்ப்பு மற்றும் வரலாற்றுத் தரவுகள் மூலம் வழங்குகிறது — <strong>"பராசல் தீவுகள் மற்றும் ஸ்ப்ராட்லி தீவுகள்"</strong> என்ற இரண்டு தீவுக்கூட்டங்களின் இறைமை குறித்து விரிவாகக் கூறும் பக்கங்களுக்கு துணையாக. சீனாவின் நியாயமற்ற உரிமைக் கோரலை வரலாறும் சான்றுகளும் கொண்டு மறுக்கிறது.',
    'footer_refs_title' => 'ஆதாரங்கள்',
    'footer_ref1' => 'PCA தீர்ப்பு, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — முழு உரை',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'வரலாற்றுத் தரவுகள் & பழைய வரைபடங்கள்',
    'footer_toc_title' => 'பக்க அட்டவணை',
    'footer_toc1' => 'ஒன்பது-கோடு கோடு என்றால் என்ன',
    'footer_toc2' => 'தோற்றம்',
    'footer_toc3' => 'ஏன் இது சர்ச்சையை ஏற்படுத்துகிறது',
    'footer_toc4' => 'சர்வதேசம் ஏன் எதிர்க்கிறது',
    'footer_toc5' => 'அமைதியான சாட்சிகள்',
    'footer_toc6' => '2016 PCA தீர்ப்பு',
    'footer_toc7' => 'பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள்',
    'footer_copy_eyebrow' => 'இலாப நோக்கமற்ற திட்டம்',
    'footer_copy_title' => 'பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள் வியட்நாமின் பகுதிகள்',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — வியட்நாம் இறைமை சூழலியல் அமைப்பில் உள்ள ஒன்பது-கோடு கோடு பற்றிய சிறப்பு பக்கம்.',
    'footer_copy_body' => 'ஒன்பது-கோடு கோடு உரிமைக் கோரலை <strong>நடுநிலையான உண்மை</strong>, <strong>சர்வதேசச் சட்டம்</strong>, 2016 PCA தீர்ப்பு மற்றும் வரலாற்றுத் தரவுகள் மூலம் விளக்குகிறது — பராசல் தீவுகள் மற்றும் ஸ்ப்ராட்லி தீவுகள் ஆகிய இரு தீவுக்கூட்டங்களின் இறைமை குறித்து விரிவாகக் கூறும் பக்கங்களுக்கு துணையாக.',
    'footer_copy_ecosystem_aria' => 'அதே திட்டத்தின் பிற பக்கங்கள்',
    'footer_copy_ecosystem_label' => 'அதே சூழலமைப்பு',
    'footer_copy_disclaimer' => 'உள்ளடக்கம் கல்வி மற்றும் விழிப்புணர்வு நோக்கத்திற்காக; இது வியட்நாம் அரசின் அதிகாரப்பூர்வ நிலைப்பாட்டை மாற்றாது.',
    'footer_copy' => '<strong>© :year ஒன்பது-கோடு கோடு</strong> — இலாப நோக்கமற்ற <strong>பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள் வியட்நாமின் பகுதிகள்</strong> திட்டத்தின் ஒரு பகுதி, அமைப்பு: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'பக்க உள்ளடக்க உறுதிமொழி',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 PCA தீர்ப்பு',
    'footer_chip3' => 'வரலாற்றுச் சான்றுகள்',
    'footer_chip4' => 'பழைய வரைபடங்கள்',
    'footer_chip5' => 'நடுநிலையான உண்மை',
    'footer_chip6' => 'தென் சீனக் கடல் அமைதி',
];
