<?php

return [
    'footer_index' => 'நூலகம்',
    'footer_crest_eyebrow' => 'நூலக உண்மைகளின் நிறைவு',
    'footer_crest_quote' => '“தென்சீனக் கடலில் அமைதி <b>சர்வதேசச் சட்டத்தின்</b> அடித்தளத்தில் கட்டப்படுகிறது.”',
    'footer_crest_sub' => 'வெறுப்பு இல்லை · உண்மை மட்டுமே',
    'footer_nav_aria' => 'பக்கத்தின் கீழ்ப்பகுதி நடவடிக்கைகள்',
    'footer_btn_top' => 'பக்கத்தின் மேல் பகுதிக்கு',
    'footer_btn_verdict' => 'PCA 2016 தீர்ப்பு',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ஒன்பது-கோடு கோடு உரிமை கோரல்',
    'footer_brand_eyebrow' => 'சிறப்புப் பகுதி · வியட்நாம் இறையாண்மை',
    'footer_brand_body' => 'ஒன்பது-கோடு கோடு பற்றிய விளக்கத்தை பொருளாதாரமான உண்மை, சர்வதேசச் சட்டம், PCA 2016 தீர்ப்பு மற்றும் வரலாற்று ஆவணங்கள் மூலம் வழங்குகிறது — <strong>"பராசல் தீவுகள் மற்றும் ஸ்ப்ராட்லி தீவுகள்"</strong> என்ற இரு தீவுக்கூட்டங்களின் இறையாண்மை குறித்த ஆழமான பக்கங்களுக்கு துணையாகும். சீனாவின் தவறான உரிமை கோரலை வரலாறும் ஆதாரங்களும் கொண்டு மறுக்கிறது.',
    'footer_refs_title' => 'மேற்கோள் ஆதாரங்கள்',
    'footer_ref1' => 'PCA தீர்ப்பு, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — முழு உரை',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'வரலாற்று ஆவணங்கள் & பழைய வரைபடங்கள்',
    'footer_toc_title' => 'பக்க உள்ளடக்க அட்டவணை',
    'footer_toc1' => 'ஒன்பது-கோடு கோடு என்றால் என்ன',
    'footer_toc2' => 'தோற்றம்',
    'footer_toc3' => 'ஏன் இது சர்ச்சைக்குரியது',
    'footer_toc4' => 'சர்வதேசம் ஏன் எதிர்க்கிறது',
    'footer_toc5' => 'அமைதியான சாட்சிகள்',
    'footer_toc6' => 'PCA 2016 தீர்ப்பு',
    'footer_toc7' => 'பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள்',
    'footer_copy_eyebrow' => 'இலாபநோக்கற்ற திட்டம்',
    'footer_copy_title' => 'பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள் வியட்நாமின் பகுதியாகும்',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — வியட்நாமின் இறையாண்மை சூழலமைப்பில் உள்ள ஒன்பது-கோடு கோடு பற்றிய சிறப்புப் பக்கம்.',
    'footer_copy_body' => 'ஒன்பது-கோடு கோடு உரிமை கோரலை <strong>பொருளாதாரமான உண்மை</strong>, <strong>சர்வதேசச் சட்டம்</strong>, PCA 2016 தீர்ப்பு மற்றும் வரலாற்று ஆவணங்கள் மூலம் விளக்குகிறது — பராசல் தீவுகள் மற்றும் ஸ்ப்ராட்லி தீவுகள் ஆகிய இரு தீவுக்கூட்டங்களின் இறையாண்மை குறித்த ஆழமான பக்கங்களுக்கு துணையாகும்.',
    'footer_copy_ecosystem_aria' => 'அதே திட்டத்தின் பிற பக்கங்கள்',
    'footer_copy_ecosystem_label' => 'அதே சூழலமைப்பு',
    'footer_copy_disclaimer' => 'இந்த உள்ளடக்கம் கல்வி மற்றும் விழிப்புணர்வுக்காக மட்டுமே; இது வியட்நாம் அரசின் அதிகாரப்பூர்வ நிலைப்பாட்டை மாற்றாது.',
    'footer_copy' => '<strong>© :year ஒன்பது-கோடு கோடு</strong> — <strong>பராசல் தீவுகள் – ஸ்ப்ராட்லி தீவுகள் வியட்நாமின் பகுதியாகும்</strong> என்ற இலாபநோக்கற்ற திட்டத்தின் ஒரு பகுதி; அமைப்பு: <a href="https://paracelislands.net/ta" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ta" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ta" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ta" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ta" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'பக்க உள்ளடக்க உறுதிமொழி',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 தீர்ப்பு',
    'footer_chip3' => 'வரலாற்று ஆதாரங்கள்',
    'footer_chip4' => 'பழைய வரைபடங்கள்',
    'footer_chip5' => 'பொருளாதாரமான உண்மை',
    'footer_chip6' => 'தென்சீனக் கடல் அமைதி',
];
