<?php

return [
    'footer_index' => 'நூலகம்',
    'footer_crest_eyebrow' => 'நூலக உண்மையின் நிறைவு',
    'footer_crest_quote' => '“தென் சீனக் கடலில் அமைதி <b>சர்வதேசச் சட்டத்தின்</b> அடித்தளத்தின் மீது கட்டமைக்கப்படுகிறது.”',
    'footer_crest_sub' => 'வெறுப்பில்லை · உண்மை மட்டுமே',
    'footer_nav_aria' => 'பக்கத்தின் இறுதிச் செயற்பாடுகள்',
    'footer_btn_top' => 'பக்கத்தின் மேலே',
    'footer_btn_verdict' => 'PCA 2016 தீர்ப்பு',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'ஒன்பது-கோடு கோடு',
    'footer_brand_body' => 'நியாயமான உண்மை, சர்வதேசச் சட்டம், மற்றும் வரலாற்று ஆவணங்களை அடிப்படையாகக் கொண்ட ஒரு விளக்கப் பக்கம் — ஒன்பது-கோடு கோடு என்ற கோரிக்கையை ஆதாரங்களால் மறுப்பது, முழக்கங்களால் அல்ல.',
    'footer_refs_title' => 'மேற்கோள் ஆதாரங்கள்',
    'footer_ref1' => 'PCA தீர்ப்பு, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — முழு உரை',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'வரலாற்றுச் சான்றுகள் & பழைய வரைபடங்கள்',
    'footer_toc_title' => 'பக்கத்தின் உள்ளடக்க அட்டவணை',
    'footer_toc1' => 'ஒன்பது-கோடு கோடு என்றால் என்ன',
    'footer_toc2' => 'தோற்றம்',
    'footer_toc3' => 'ஏன் இது சர்ச்சையை ஏற்படுத்துகிறது',
    'footer_toc4' => 'ஏன் உலகம் இதை எதிர்க்கிறது',
    'footer_toc5' => 'அமைதியான சாட்சிகள்',
    'footer_toc6' => 'PCA 2016 தீர்ப்பு',
    'footer_toc7' => 'பராசல் தீவுகள் - ஸ்ப்ராட்லி தீவுகள்',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — தென் சீனக் கடல் குறித்த நியாயமான உண்மை.<br>மண்டல அமைப்பு: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'கோஆர்டினேட்கள் இல்லை',
];
