<?php

return [
    'nav_logo_name' => 'ஒன்பது-கோடு கோடு',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'ஒன்பது-கோடு கோடு',
    'nav_rail_aria' => 'பிரிவுகளின்படி வழிசெலுத்தல்',
    'nav_rail_what' => 'வரையறை',
    'nav_rail_origin' => 'தோற்றம்',
    'nav_rail_dispute' => 'சர்ச்சை',
    'nav_rail_opposition' => 'எதிர்ப்பு',
    'nav_rail_witnesses' => 'பண்டைய வரைபடங்கள்',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'பராசல் தீவுகள் - ஸ்ப்ராட்லி தீவுகள்',
    'nav_sound_off' => 'பின்னணி இசையை இயக்கு',
    'nav_sound_on' => 'பின்னணி இசையை நிறுத்து',
    'nav_share' => 'பகிர்',
    'dialog_title' => 'காண்பிக்கும் மொழி',
    'language' => 'மொழி',
    'display_hint' => ':count மொழிகள்',
    'search_placeholder' => 'மொழியைத் தேடு…',
    'cancel' => 'ரத்து',
    'apply' => 'பயன்படுத்து',
    'sound_off' => 'பின்னணி ஒலியை இயக்கு',
    'sound_on' => 'பின்னணி ஒலியை நிறுத்து',
    'lang_trigger' => 'மொழியைத் தேர்ந்தெடு',
    'close' => 'மூடு',
    'no_results' => 'மொழி எதுவும் கிடைக்கவில்லை',
    'contribute' => 'பகிர்',
];
