<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Penutup perpustakaan kebenaran',
    'footer_crest_quote' => '“Keamanan di Laut China Selatan dibina di atas asas <b>undang-undang antarabangsa</b>.”',
    'footer_crest_sub' => 'Tiada kebencian · Hanya kebenaran',
    'footer_nav_aria' => 'Tindakan kaki halaman',
    'footer_btn_top' => 'Ke atas halaman',
    'footer_btn_verdict' => 'Keputusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Tuntutan Garisan Sembilan Titik',
    'footer_brand_eyebrow' => 'Laman khusus · Kedaulatan Vietnam',
    'footer_brand_body' => 'Menjelaskan Garisan Sembilan Titik melalui kebenaran objektif, undang-undang antarabangsa, keputusan PCA 2016 dan bahan sejarah — sebagai pelengkap kepada laman mendalam tentang kedaulatan dua kepulauan <strong>"Kepulauan Paracel dan Kepulauan Spratly"</strong>. Menafikan tuntutan tidak berasas China dengan sejarah dan bukti.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Keputusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks penuh',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta lama',
    'footer_toc_title' => 'Isi kandungan halaman',
    'footer_toc1' => 'Apakah Garisan Sembilan Titik',
    'footer_toc2' => 'Asal usul',
    'footer_toc3' => 'Mengapa ia dipertikaikan',
    'footer_toc4' => 'Mengapa masyarakat antarabangsa menolak',
    'footer_toc5' => 'Saksi senyap',
    'footer_toc6' => 'Keputusan PCA 2016',
    'footer_toc7' => 'Kepulauan Paracel – Kepulauan Spratly',
    'footer_copy_eyebrow' => 'Projek bukan untung',
    'footer_copy_title' => 'Kepulauan Paracel – Kepulauan Spratly milik Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Laman khusus tentang Garisan Sembilan Titik dalam ekosistem kedaulatan Vietnam.',
    'footer_copy_body' => 'Menjelaskan tuntutan Garisan Sembilan Titik melalui <strong>kebenaran objektif</strong>, <strong>undang-undang antarabangsa</strong>, keputusan PCA 2016 dan bahan sejarah — sebagai pelengkap kepada laman mendalam tentang kedaulatan dua kepulauan Paracel dan Spratly.',
    'footer_copy_ecosystem_aria' => 'Laman-laman dalam projek yang sama',
    'footer_copy_ecosystem_label' => 'Dalam ekosistem yang sama',
    'footer_copy_disclaimer' => 'Kandungan ini bertujuan untuk pendidikan dan meningkatkan kesedaran; ia tidak menggantikan pendirian rasmi Kerajaan Vietnam.',
    'footer_copy' => '<strong>© :year Garisan Sembilan Titik</strong> — Sebahagian daripada projek bukan untung <strong>Kepulauan Paracel – Kepulauan Spratly milik Vietnam</strong> dalam rangkaian: <a href="https://paracelislands.net/ms" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ms" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ms" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ms" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ms" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Komitmen kandungan laman',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Keputusan PCA 2016',
    'footer_chip3' => 'Bukti sejarah',
    'footer_chip4' => 'Peta lama',
    'footer_chip5' => 'Kebenaran objektif',
    'footer_chip6' => 'Keamanan Laut China Selatan',
];
