<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Penutup perpustakaan kebenaran',
    'footer_crest_quote' => '“Keamanan di Laut China Selatan dibina di atas asas <b>Undang-undang antarabangsa</b>.”',
    'footer_crest_sub' => 'Tanpa kebencian · Hanya kebenaran',
    'footer_nav_aria' => 'Tindakan bahagian bawah halaman',
    'footer_btn_top' => 'Kembali ke atas',
    'footer_btn_verdict' => 'Keputusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Tuntutan Garisan Sembilan Titik',
    'footer_brand_eyebrow' => 'Halaman khas · Kedaulatan Vietnam',
    'footer_brand_body' => 'Menjelaskan Garisan Sembilan Titik melalui fakta objektif, undang-undang antarabangsa, keputusan PCA 2016 dan bahan sejarah — sebagai pelengkap kepada halaman terperinci tentang kedaulatan dua kepulauan <strong>"Kepulauan Paracel dan Kepulauan Spratly"</strong>. Menolak tuntutan tidak berasas China dengan sejarah dan bukti.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Keputusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks penuh',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta lama',
    'footer_toc_title' => 'Isi kandungan halaman',
    'footer_toc1' => 'Apa itu Garisan Sembilan Titik',
    'footer_toc2' => 'Asal usul',
    'footer_toc3' => 'Mengapa ia menjadi pertikaian',
    'footer_toc4' => 'Mengapa ditolak oleh masyarakat antarabangsa',
    'footer_toc5' => 'Saksi yang diam',
    'footer_toc6' => 'Keputusan PCA 2016',
    'footer_toc7' => 'Kepulauan Paracel – Kepulauan Spratly',
    'footer_copy_eyebrow' => 'Projek bukan keuntungan',
    'footer_copy_title' => 'Kepulauan Paracel – Kepulauan Spratly adalah milik Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Halaman khas tentang Garisan Sembilan Titik dalam ekosistem kedaulatan Vietnam.',
    'footer_copy_body' => 'Menjelaskan tuntutan Garisan Sembilan Titik melalui <strong>fakta objektif</strong>, <strong>undang-undang antarabangsa</strong>, keputusan PCA 2016 dan bahan sejarah — sebagai pelengkap kepada halaman terperinci tentang kedaulatan dua kepulauan Kepulauan Paracel dan Kepulauan Spratly.',
    'footer_copy_ecosystem_aria' => 'Laman-laman dalam projek yang sama',
    'footer_copy_ecosystem_label' => 'Dalam ekosistem yang sama',
    'footer_copy_disclaimer' => 'Kandungan ini bertujuan pendidikan dan meningkatkan kesedaran; ia tidak menggantikan pendirian rasmi Kerajaan Vietnam.',
    'footer_copy' => '<strong>© :year Garisan Sembilan Titik</strong> — Sebahagian daripada projek bukan keuntungan <strong>Kepulauan Paracel – Kepulauan Spratly adalah milik Vietnam</strong> dalam rangkaian: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Komitmen kandungan halaman',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Keputusan PCA 2016',
    'footer_chip3' => 'Bukti sejarah',
    'footer_chip4' => 'Peta lama',
    'footer_chip5' => 'Fakta objektif',
    'footer_chip6' => 'Keamanan Laut China Selatan',
];
