<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Menutup perpustakaan kebenaran',
    'footer_crest_quote' => '“Keamanan di Laut China Selatan dibina atas asas <b>undang-undang antarabangsa</b>.”',
    'footer_crest_sub' => 'Tiada kebencian · Hanya kebenaran',
    'footer_nav_aria' => 'Tindakan penghujung halaman',
    'footer_btn_top' => 'Kembali ke atas',
    'footer_btn_verdict' => 'Keputusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Garisan Sembilan Titik',
    'footer_brand_body' => 'Sebuah laman penjelasan yang berasaskan kebenaran objektif, undang-undang antarabangsa dan dokumen sejarah — menafikan tuntutan Garisan Sembilan Titik dengan bukti, bukan slogan.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Keputusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks penuh',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Bahan sejarah & peta lama',
    'footer_toc_title' => 'Isi kandungan laman',
    'footer_toc1' => 'Apakah Garisan Sembilan Titik',
    'footer_toc2' => 'Asal usul',
    'footer_toc3' => 'Mengapa ia menjadi kontroversi',
    'footer_toc4' => 'Mengapa masyarakat antarabangsa menolak',
    'footer_toc5' => 'Saksi yang senyap',
    'footer_toc6' => 'Keputusan PCA 2016',
    'footer_toc7' => 'Kepulauan Paracel – Kepulauan Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Kebenaran objektif tentang Laut China Selatan.<br>Ekosistem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Tanpa koordinat',
];
