<?php

return [
    'nav_logo_name' => 'Garisan Sembilan Titik',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Garisan Sembilan Titik',
    'nav_rail_aria' => 'Navigasi mengikut bahagian',
    'nav_rail_what' => 'Definisi',
    'nav_rail_origin' => 'Asal usul',
    'nav_rail_dispute' => 'Kontroversi',
    'nav_rail_opposition' => 'Penolakan',
    'nav_rail_witnesses' => 'Peta lama',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Kepulauan Paracel - Kepulauan Spratly',
    'nav_sound_off' => 'Hidupkan muzik latar',
    'nav_sound_on' => 'Matikan muzik latar',
    'nav_share' => 'Kongsi',
    'dialog_title' => 'Bahasa paparan',
    'language' => 'Bahasa',
    'display_hint' => ':count bahasa',
    'search_placeholder' => 'Cari bahasa…',
    'cancel' => 'Batal',
    'apply' => 'Guna',
    'sound_off' => 'Hidupkan audio latar',
    'sound_on' => 'Matikan audio latar',
    'lang_trigger' => 'Pilih bahasa',
    'close' => 'Tutup',
    'no_results' => 'Tiada bahasa ditemui',
    'contribute' => 'Kongsi',
];
