<?php

return [
    'opposition_index' => 'Penentangan',
    'opposition_label' => 'Mengapa dunia antarabangsa menentang',
    'opposition_title' => 'Penentangan berdasarkan',
    'opposition_title_accent' => 'undang-undang, bukan emosi',
    'opposition_lead' => 'Sejurus selepas Garisan Sembilan Titik dikemukakan kepada Pertubuhan Bangsa-Bangsa Bersatu pada tahun 2009, banyak negara dan kalangan sarjana telah membantah — dengan hujah undang-undang yang khusus.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mei',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Hanya sehari selepas China mengemukakan peta Garisan Sembilan Titik kepada Setiausaha Agung Pertubuhan Bangsa-Bangsa Bersatu (7/5/2009), negara-negara ini secara bergilir-gilir menghantar nota bantahan, menolak tuntutan tersebut.',
    'opposition_voice1_chip1' => 'Nota bantahan',
    'opposition_voice1_chip2' => 'Tidak selaras dengan UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipina',
    'opposition_voice2_body' => 'Menghantar surat diplomatik kepada Pertubuhan Bangsa-Bangsa Bersatu, menyatakan bahawa tuntutan China di Laut China Selatan adalah “tidak berasas menurut undang-undang antarabangsa” — menjadi asas kepada kes yang kemudian dibawa ke Mahkamah Timbang Tara.',
    'opposition_voice2_chip1' => 'Asas bagi kes PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kementerian Luar Amerika Syarikat — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analisis menunjukkan: peta-peta pada tahun yang berbeza tidak konsisten dari segi kedudukan garis; garis tersebut menceroboh daratan dan bukannya menggunakan garis tengah; banyak entiti tidak memenuhi syarat sebagai “pulau” untuk memiliki EEZ.',
    'opposition_voice3_chip1' => 'Tidak memenuhi syarat undang-undang',
    'opposition_voice3_chip2' => 'Analisis rasmi',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '“Perairan sejarah” telah lapuk',
    'opposition_voice4_body' => 'Konsep ini hanya terpakai pada teluk, lekukan air yang dekat dengan pantai — tidak boleh meliputi seluruh kawasan laut lepas yang luas. Pada tahun 2003, Taiwan sendiri juga menolak dasar “perairan sejarah” yang pernah dinyatakan pada tahun 1993.',
    'opposition_voice4_chip1' => 'Malah sarjana China juga tidak sependapat',
];
