<?php

return [
    'sovereignty_index' => 'Kepulauan Paracel - Kepulauan Spratly',
    'sovereignty_label' => 'Kesimpulan yang logik',
    'sovereignty_title' => 'Kepulauan Paracel - Kepulauan Spratly',
    'sovereignty_title_accent' => 'milik Vietnam',
    'sovereignty_lead' => 'Halaman ini menerangkan Garisan Sembilan Titik. Bahagian kesimpulan menjawab soalan seterusnya: siapa yang mempunyai kedaulatan ke atas dua kepulauan Kepulauan Paracel dan Kepulauan Spratly? Berdasarkan sejarah pentadbiran dan undang-undang antarabangsa, jawapannya secara konsisten ialah Vietnam.',
    'sovereignty_thesis_label' => 'Hujah gabungan',
    'sovereignty_thesis_lock1' => 'Tiada koordinat undang-undang',
    'sovereignty_thesis_lock2' => 'PCA 2016 menolak',
    'sovereignty_thesis_lock3' => 'Peta lama tidak meliputi',
    'sovereignty_thesis_body' => 'Selepas enam bahagian di atas, tiga perkara telah jelas: Garisan Sembilan Titik dilukis tangan dan tidak mempunyai koordinat undang-undang; Mahkamah Timbang Tara pada tahun 2016 menolak tuntutan itu; peta lama milik China sendiri tidak meliputi Laut China Selatan. Kedaulatan Vietnam tidak bergantung pada slogan, tetapi pada hakikat bahawa negara Vietnam — sejak zaman para raja Nguyễn — telah mentadbir secara aman dan berterusan ketika dua kepulauan itu masih merupakan tanah tidak bertuan.',
    'sovereignty_spine_caption' => 'Titik pentadbiran berterusan',
    'sovereignty_spine_title' => 'Satu garis masa, tanpa gangguan',
    'sovereignty_spine_range' => 'Abad ke-17 → kini',
    'sovereignty_chron1_year' => 'Abad ke-17',
    'sovereignty_chron1_title' => 'Pasukan Hoàng Sa',
    'sovereignty_chron1_body' => 'Para raja Nguyễn menghantar Pasukan Hoàng Sa untuk menjalankan tinjauan, mengukur laluan laut dan memanfaatkan sumber di laut — melaksanakan kuasa pentadbiran secara nyata.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Raja Gia Long',
    'sovereignty_chron2_body' => 'Mengibarkan bendera di Kepulauan Paracel, menegaskan kedaulatan Vietnam di mata dunia ketika itu.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Raja Minh Mạng',
    'sovereignty_chron3_body' => 'Melakukan pengukuran, mendirikan batu tugu, dan mencatat kepulauan itu pada peta rasmi istana.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Pewarisan berterusan',
    'sovereignty_chron4_body' => 'Perancis mengiktiraf dan meneruskan pentadbiran; Kepulauan Paracel digabungkan ke dalam wilayah Thừa Thiên — asas bagi Negara Vietnam hari ini.',
    'sovereignty_chron5_year' => 'Kini',
    'sovereignty_chron5_title' => 'Undang-undang dan amalan',
    'sovereignty_chron5_body' => 'Vietnam mentadbir mengikut UNCLOS, diplomasi dan rekod arkib; tuntutan Garisan Sembilan Titik tidak dapat menggantikan bukti ini.',
    'sovereignty_balance_label' => 'Keseimbangan bukti',
    'sovereignty_balance_medallion_title' => 'Perbandingan dua pihak',
    'sovereignty_vn_tag' => 'Pihak Vietnam',
    'sovereignty_vn_title' => 'Kedaulatan ditetapkan melalui tindakan',
    'sovereignty_vn_body' => 'Penguasaan sebenar ketika tanah masih tidak bertuan, kemudian ditadbir secara terbuka selama berabad-abad — dengan dokumen diraja, batu peringatan, peta dan rekod pentadbiran. Cara ini selaras dengan UNCLOS dan amalan antarabangsa.',
    'sovereignty_dash_tag' => 'Pihak Garisan Sembilan Titik',
    'sovereignty_dash_title' => 'Tuntutan tidak dapat menampung bukti',
    'sovereignty_dash_body' => 'Satu garisan yang dilukis pada tahun 1948, tanpa koordinat, telah ditolak oleh PCA 2016 dan bercanggah dengan UNCLOS — seperti yang dihuraikan dalam bahagian 03 hingga 06. Itulah sebabnya kesimpulan tentang kedaulatan dua kepulauan ini tidak boleh bergantung pada Garisan Sembilan Titik.',
    'sovereignty_seal_quote' => 'Vietnam menyelesaikan pertikaian melalui <strong>kaedah aman</strong>, berasaskan undang-undang antarabangsa — khususnya UNCLOS 1982 — demi Laut China Selatan yang aman, bekerjasama dan maju.',
    'sovereignty_seal_cite' => 'Pendirian Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Projek utama dalam ekosistem yang sama',
    'sovereignty_next_title' => 'Baca sepenuhnya bukti tentang Kepulauan Paracel - Kepulauan Spratly',
    'sovereignty_next_body' => 'Fail terperinci — dokumen, peta, garis masa dan hujah undang-undang — terdapat di laman <strong>paracelislands.net</strong>, yang membentangkan secara menyeluruh tema kedaulatan dua kepulauan ini. Halaman yang anda baca ini hanya menghubungkan logik daripada Garisan Sembilan Titik kepada kesimpulan tersebut.',
    'sovereignty_next_cta' => 'Buka paracelislands.net',
];
