<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Keputusan Antarabangsa',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tiga perkataan “Tidak”',
    'verdict_lead' => 'Pada 12/7/2016, Mahkamah Timbang Tara Tetap (PCA) di The Hague — ditubuhkan di bawah Lampiran VII UNCLOS, dalam kes Filipina menentang China — telah mengeluarkan keputusan yang menolak tuntutan Garisan Sembilan Titik. <em>Klik pada setiap kad untuk membaca teks asal.</em>',
    'verdict_card1_khong' => 'TIDAK',
    'verdict_card1_title' => 'hak sejarah',
    'verdict_card1_short' => 'Tiada asas undang-undang untuk China menegaskan hak sejarah ke atas sumber di perairan yang terletak dalam Garisan Sembilan Titik.',
    'verdict_card1_quote' => '“Tiada asas undang-undang bagi China menegaskan hak sejarah ke atas sumber-sumber yang terletak di perairan dalam Garisan Sembilan Titik.”',
    'verdict_card1_more' => '+ Baca keputusan',
    'verdict_card2_khong' => 'TIDAK',
    'verdict_card2_title' => 'entiti pembentuk EEZ',
    'verdict_card2_short' => 'Tiada satu pun entiti di Kepulauan Spratly yang layak membentuk zon ekonomi eksklusif untuk China — termasuk Pulau Taiping.',
    'verdict_card2_quote' => '“Tiada satu pun entiti di Kepulauan Spratly yang mampu membentuk zon ekonomi eksklusif.”',
    'verdict_card2_more' => '+ Baca keputusan',
    'verdict_card3_khong' => 'TIDAK',
    'verdict_card3_title' => 'tindakan yang sah',
    'verdict_card3_short' => 'China melanggar hak kedaulatan Filipina, menghalang aktiviti menangkap ikan dan merosakkan alam sekitar laut.',
    'verdict_card3_quote' => '“China telah melanggar hak kedaulatan Filipina, mengganggu aktiviti menangkap ikan di beting Scarborough dan menyebabkan kerosakan serius kepada persekitaran terumbu karang.”',
    'verdict_card3_more' => '+ Baca keputusan',
    'verdict_extra1' => 'Garisan Sembilan Titik yang dilakar sendiri oleh China <strong>tidak selaras</strong> dengan UNCLOS 1982.',
    'verdict_extra2' => 'China menyebabkan kerosakan kepada ekosistem Kepulauan Spratly melalui eksploitasi berlebihan dan pembinaan pulau buatan.',
    'verdict_extra3' => 'Tindakan China meningkatkan risiko konflik dengan Filipina.',
    'verdict_extra4' => 'Pulau Taiping (yang dikawal oleh Taiwan) juga tidak dapat mewujudkan EEZ.',
    'verdict_subtitle' => 'Mengapa ia bercanggah dengan UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 dengan jelas menetapkan zon-zon laut berdasarkan garis dasar negara pantai. Tuntutan Garisan Sembilan Titik melangkaui kerangka ini, maka ia tidak boleh disandarkan bersama.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Laut wilayah (batu nautika)',
    'verdict_zone1_body' => 'Kawasan laut negara yang berdaulat, diukur dari garis dasar.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zon ekonomi eksklusif',
    'verdict_zone2_body' => 'EEZ — negara pantai mempunyai hak kedaulatan ke atas sumber dalam lingkungan ini.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Pelantar benua (maksimum, batu nautika)',
    'verdict_zone3_body' => 'Hak ke atas sumber dasar laut, menurut syarat geologi yang ditetapkan.',
    'verdict_foot' => 'Dalam kerangka ini, “hak sejarah” yang merangkumi seluruh kawasan laut terbuka — seperti yang diimplikasikan oleh Garisan Sembilan Titik — <em>telah digantikan</em> oleh rejim undang-undang UNCLOS yang turut disertai oleh China.',
];
