<?php

return [
    'witnesses_index' => 'Peta Kuno',
    'witnesses_label' => 'Peta Kuno China',
    'witnesses_title' => 'Hanya sampai ke selatan',
    'witnesses_title_accent' => 'Pulau Hainan',
    'witnesses_lead' => 'Peta-peta kuno yang dilukis oleh pengarang China — disusun mengikut masa — semuanya menunjukkan <em>Pulau Hainan sebagai titik paling selatan</em> China, tanpa Kepulauan Paracel atau Kepulauan Spratly. Bahan disusun berdasarkan <em>Kedaulatan negara Vietnam di dua kepulauan Hoàng Sa dan Trường Sa</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Kanta pembesar',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— titik paling selatan wilayah —',
    'witnesses_map1_svg_era' => 'Dinasti Song · 1136',
    'witnesses_map1_title' => 'Peta Dinasti Song, 1136',
    'witnesses_map1_body' => 'Wilayah China berakhir di Pulau Hainan — Kepulauan Paracel dan Kepulauan Spratly berada di luar kawasan kedaulatan.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'had d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Peta d\'Anville, 1735',
    'witnesses_map2_body' => 'Dibuat oleh J.-B. B. d\'Anville; salinan 1740 pernah dihadiahkan oleh Canselor Jerman kepada pemimpin China. Wilayah Dinasti Qing berakhir di Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"titik paling selatan China"',
    'witnesses_map3_svg_era' => 'Qing dinasti langsung di bawah wilayah · 1904',
    'witnesses_map3_title' => 'Atlas geografi wilayah langsung di bawah Dinasti Qing',
    'witnesses_map3_body' => 'Dicetak oleh Dinasti Qing — dengan jelas menyatakan bahawa titik paling selatan wilayah China ialah Pulau Hainan.',
    'witnesses_quote' => 'Peta China yang pernah diterbitkan sendiri tidak melukis Kepulauan Paracel — Kepulauan Spratly sebagai sebahagian daripada wilayah mereka.',
    'witnesses_timeline_aria' => 'Garis masa peta kuno China',
    'witnesses_year_aria' => 'Tarikh',
    'lightbox_aria' => 'Lihat imej diperbesarkan',
    'lightbox_close' => 'Tutup',
    'lightbox_prev' => 'Imej sebelumnya',
    'lightbox_next' => 'Imej seterusnya',
];
