<?php

return [
    'footer_index' => 'Номын сан',
    'footer_crest_eyebrow' => 'Номын сантай үнэний түүхийг төгсгөв',
    'footer_crest_quote' => '“Өмнөд Хятадын тэнгис дэх энх тайван нь <b>олон улсын эрх зүй</b>-н суурин дээр тогтдог.”',
    'footer_crest_sub' => 'Өшөө үзэн ядалтгүй · Зөвхөн үнэн',
    'footer_nav_aria' => 'Хуудасны доод хэсгийн үйлдлүүд',
    'footer_btn_top' => 'Хуудасны эхэнд очих',
    'footer_btn_verdict' => '2016 оны PCA-ийн шийдвэр',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Есөн зурааст шугмын шаардлага',
    'footer_brand_eyebrow' => 'Тусгай сэдэв · Вьетнамын бүрэн эрх',
    'footer_brand_body' => 'Есөн зурааст шугамыг бодитой үнэн, олон улсын эрх зүй, 2016 оны PCA-ийн шийдвэр, түүхэн баримтуудаар тайлбарлана — <strong>"Параселийн арлууд ба Спратлийн арлууд"</strong>-ын бүрэн эрхийн талаархи нарийвчилсан хуудсуудыг дэмжинэ. Хятад улсын үндэслэлгүй шаардлагыг түүх, нотолгоогоор няцаана.',
    'footer_refs_title' => 'Эх сурвалж',
    'footer_ref1' => 'PCA-ийн шийдвэр, 2016-07-12',
    'footer_ref2' => 'UNCLOS 1982 — бүрэн эх',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Түүхэн баримт, эртний газрын зургууд',
    'footer_toc_title' => 'Хуудасны агуулга',
    'footer_toc1' => 'Есөн зурааст шугам гэж юу вэ',
    'footer_toc2' => 'Гарал үүсэл',
    'footer_toc3' => 'Яагаад маргаантай вэ',
    'footer_toc4' => 'Яагаад олон улс эсэргүүцдэг вэ',
    'footer_toc5' => 'Чимээгүй гэрчүүд',
    'footer_toc6' => '2016 оны PCA-ийн шийдвэр',
    'footer_toc7' => 'Параселийн арлууд – Спратлийн арлууд',
    'footer_copy_eyebrow' => 'Ашгийн бус төсөл',
    'footer_copy_title' => 'Параселийн арлууд – Спратлийн арлууд нь Вьетнамынх',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Вьетнамын бүрэн эрхийн экосистем дэх Есөн зурааст шугмын тусгай хуудас.',
    'footer_copy_body' => 'Есөн зурааст шугмын шаардлагыг <strong>бодитой үнэн</strong>, <strong>олон улсын эрх зүй</strong>, 2016 оны PCA-ийн шийдвэр, түүхэн баримтуудаар тайлбарлана — Параселийн арлууд ба Спратлийн арлуудын бүрэн эрхийн талаархи нарийвчилсан хуудсуудыг дэмжинэ.',
    'footer_copy_ecosystem_aria' => 'Нэг төслийн бусад хуудас',
    'footer_copy_ecosystem_label' => 'Нэг экосистем',
    'footer_copy_disclaimer' => 'Агуулга нь боловсрол, ойлголт нэмэгдүүлэх зорилготой; Вьетнамын төрийн албан ёсны байр суурийг орлохгүй.',
    'footer_copy' => '<strong>© :year Есөн зурааст шугам</strong> — Ашгийн бус <strong>Параселийн арлууд – Спратлийн арлууд нь Вьетнамынх</strong> төслийн нэг хэсэг бөгөөд дараах системд хамаарна: <a href="https://paracelislands.net/mn" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/mn" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/mn" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/mn" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/mn" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Хуудасны агуулгын амлалт',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016 оны PCA-ийн шийдвэр',
    'footer_chip3' => 'Түүхэн нотолгоо',
    'footer_chip4' => 'Эртний газрын зургууд',
    'footer_chip5' => 'Бодитой үнэн',
    'footer_chip6' => 'Өмнөд Хятадын тэнгисийн энх тайван',
];
