<?php

return [
    'footer_index' => 'Номын сан',
    'footer_crest_eyebrow' => 'Номын санг баримтаар төгсгөе',
    'footer_crest_quote' => '“Өмнөд Хятадын тэнгис дэх энх тайван нь <b>олон улсын эрх зүй</b>-н суурин дээр тогтдог.”',
    'footer_crest_sub' => 'Өш хонзон биш · Зөвхөн үнэн',
    'footer_nav_aria' => 'Хуудасны төгсгөлийн үйлдлүүд',
    'footer_btn_top' => 'Хуудасны эхлэл рүү',
    'footer_btn_verdict' => 'PCA-ийн 2016 оны шийдвэр',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Есөн зурааст шугамын нэхэмжлэл',
    'footer_brand_eyebrow' => 'Тусгай сэдэв · Вьетнамын бүрэн эрх',
    'footer_brand_body' => 'Есөн зурааст шугамыг бодит үнэн, олон улсын эрх зүй, PCA-ийн 2016 оны шийдвэр болон түүхэн баримтаар тайлбарлаж, <strong>"Параселийн арлууд ба Спратлийн арлууд"</strong>-ын бүрэн эрхийн тухай нарийвчилсан хуудсуудыг дэмжинэ. Хятадын үндэслэлгүй нэхэмжлэлийг түүх, нотолгоогоор няцаана.',
    'footer_refs_title' => 'Эх сурвалжууд',
    'footer_ref1' => 'PCA-ийн шийдвэр, 2016.07.12',
    'footer_ref2' => '1982 оны UNCLOS — бүрэн эх',
    'footer_ref3' => 'Limits in the Seas №143 (АНУ-ын Төрийн департамент)',
    'footer_ref4' => 'Түүхэн баримт & эртний газрын зургууд',
    'footer_toc_title' => 'Хуудасны агуулга',
    'footer_toc1' => 'Есөн зурааст шугам гэж юу вэ',
    'footer_toc2' => 'Гарал үүсэл',
    'footer_toc3' => 'Яагаад маргаантай вэ',
    'footer_toc4' => 'Яагаад олон улс эсэргүүцдэг вэ',
    'footer_toc5' => 'Дуугүй гэрчүүд',
    'footer_toc6' => 'PCA-ийн 2016 оны шийдвэр',
    'footer_toc7' => 'Параселийн арлууд – Спратлийн арлууд',
    'footer_copy_eyebrow' => 'Ашгийн бус төсөл',
    'footer_copy_title' => 'Параселийн арлууд – Спратлийн арлууд нь Вьетнамынх',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Вьетнамын бүрэн эрхийн экосистем доторх Есөн зурааст шугамын тусгай хуудас.',
    'footer_copy_body' => 'Есөн зурааст шугамын нэхэмжлэлийг <strong>объектив үнэн</strong>, <strong>олон улсын эрх зүй</strong>, PCA-ийн 2016 оны шийдвэр болон түүхэн баримтаар тайлбарлаж, Параселийн арлууд ба Спратлийн арлуудын бүрэн эрхийн тухай нарийвчилсан хуудсуудыг дэмжинэ.',
    'footer_copy_ecosystem_aria' => 'Ижил төслийн бусад хуудсууд',
    'footer_copy_ecosystem_label' => 'Ижил экосистем',
    'footer_copy_disclaimer' => 'Агуулга нь боловсрол, ойлголт нэмэгдүүлэх зорилготой; Вьетнам улсын албан ёсны байр суурийг орлохгүй.',
    'footer_copy' => '<strong>© :year Есөн зурааст шугам</strong> — <strong>Параселийн арлууд – Спратлийн арлууд нь Вьетнамынх</strong> ашгийн бус төслийн нэг хэсэг бөгөөд дараах системийн бүрэлдэхүүн: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Хуудасны агуулгын баталгаа',
    'footer_chip1' => '1982 оны UNCLOS',
    'footer_chip2' => 'PCA-ийн 2016 оны шийдвэр',
    'footer_chip3' => 'Түүхэн нотолгоо',
    'footer_chip4' => 'Эртний газрын зургууд',
    'footer_chip5' => 'Объектив үнэн',
    'footer_chip6' => 'Өмнөд Хятадын тэнгисийн энх тайван',
];
