<?php

return [
    'footer_index' => 'Номын сан',
    'footer_crest_eyebrow' => 'Номын сангийн үнэнийг нэгтгэнэ',
    'footer_crest_quote' => '“Өмнөд Хятадын тэнгис дэх энх тайван нь <b>олон улсын эрх зүй</b>-н суурин дээр тогтдог.”',
    'footer_crest_sub' => 'Үзэн ядалтгүй · Зөвхөн үнэн',
    'footer_nav_aria' => 'Хуудасны төгсгөлийн үйлдлүүд',
    'footer_btn_top' => 'Хуудасны эхлэл рүү',
    'footer_btn_verdict' => 'PCA 2016 оны шийдвэр',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Есөн зурааст шугам',
    'footer_brand_body' => 'Баримтад тулгуурласан, бодитой тайлбар бүхий, олон улсын эрх зүй болон түүхэн баримт бичгүүдэд үндэслэсэн хуудас — Есөн зурааст шугамын нэхэмжлэлийг уриа лоозонгоор бус, нотолгоогоор няцаана.',
    'footer_refs_title' => 'Иш татсан эх сурвалжууд',
    'footer_ref1' => 'PCA-ийн шийдвэр, 2016.07.12',
    'footer_ref2' => '1982 оны UNCLOS — бүрэн эх',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Түүхэн материал ба эртний газрын зургууд',
    'footer_toc_title' => 'Хуудасны агуулга',
    'footer_toc1' => 'Есөн зурааст шугам гэж юу вэ',
    'footer_toc2' => 'Гарал үүсэл',
    'footer_toc3' => 'Яагаад маргаантай вэ',
    'footer_toc4' => 'Яагаад олон улс эсэргүүцдэг вэ',
    'footer_toc5' => 'Чимээгүй гэрчүүд',
    'footer_toc6' => 'PCA 2016 оны шийдвэр',
    'footer_toc7' => 'Параселийн арлууд - Спратлийн арлууд',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Өмнөд Хятадын тэнгисийн тухай бодитой үнэн.<br>Экосистем: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Координатгүй',
];
