<?php

return [
    'nav_logo_name' => 'Есөн зурааст шугам',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Есөн зурааст шугам',
    'nav_rail_aria' => 'Сэдвээр навигац хийх',
    'nav_rail_what' => 'Тодорхойлолт',
    'nav_rail_origin' => 'Үүсэл гарал',
    'nav_rail_dispute' => 'Маргаан',
    'nav_rail_opposition' => 'Эсэргүүцэл',
    'nav_rail_witnesses' => 'Эртний газрын зураг',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Параселийн арлууд - Спратлийн арлууд',
    'nav_sound_off' => 'Дэвсгэр хөгжмийг асаах',
    'nav_sound_on' => 'Дэвсгэр хөгжмийг унтраах',
    'nav_share' => 'Хуваалцах',
    'dialog_title' => 'Дэлгэцийн хэл',
    'language' => 'Хэл',
    'display_hint' => ':count хэл',
    'search_placeholder' => 'Хэл хайх…',
    'cancel' => 'Цуцлах',
    'apply' => 'Хэрэглэх',
    'sound_off' => 'Дэвсгэр дууг асаах',
    'sound_on' => 'Дэвсгэр дууг унтраах',
    'lang_trigger' => 'Хэл сонгох',
    'close' => 'Хаах',
    'no_results' => 'Хэл олдсонгүй',
    'contribute' => 'Хуваалцах',
];
