<?php

return [
    'footer_index' => 'Китепкана',
    'footer_crest_eyebrow' => 'Чындык китепканасынын аягы',
    'footer_crest_quote' => '“Түштүк Кытай деңизиндеги тынчтык <bэл аралык укуктун</b> негизинде курулат.”',
    'footer_crest_sub' => 'Жек көрүү жок · Болгону чындык',
    'footer_nav_aria' => 'Барактын ылдый жагындагы аракеттер',
    'footer_btn_top' => 'Беттин башына кайтуу',
    'footer_btn_verdict' => '2016-жылкы PCA чечими',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Тогуз сызык чеги',
    'footer_brand_body' => 'Объективдүү чындыкка, эл аралык укукка жана тарыхый документтерге негизделген түшүндүрмө барагы — Тогуз сызык чегине болгон дооматты ураандар менен эмес, далилдер менен четке кагат.',
    'footer_refs_title' => 'Шилтеме булактар',
    'footer_ref1' => 'PCA чечими, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — толук текст',
    'footer_ref3' => 'Limits in the Seas №143 (АКШ Мамлекеттик департаменти)',
    'footer_ref4' => 'Тарыхый материалдар жана эски карталар',
    'footer_toc_title' => 'Барактын мазмуну',
    'footer_toc1' => 'Тогуз сызык чеги деген эмне',
    'footer_toc2' => 'Келип чыгышы',
    'footer_toc3' => 'Эмне үчүн талаш жаратат',
    'footer_toc4' => 'Эмне үчүн эл аралык коомчулук каршы',
    'footer_toc5' => 'Тынч күбөлөр',
    'footer_toc6' => '2016-жылкы PCA чечими',
    'footer_toc7' => 'Парасел аралдары – Спратли аралдары',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Түштүк Кытай деңизи тууралуу объективдүү чындык.<br>Экосистема: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Координат жок',
];
