<?php

return [
    'footer_index' => 'Китепкана',
    'footer_crest_eyebrow' => 'Чындык китепканасынын аягы',
    'footer_crest_quote' => '“Түштүк Кытай деңизиндеги тынчтык <b>эл аралык укуктун</b> негизинде курулат.”',
    'footer_crest_sub' => 'Жек көрүү жок · Болгону чындык',
    'footer_nav_aria' => 'Төмөнкү бөлүктөгү аракеттер',
    'footer_btn_top' => 'Жогоруга кайтуу',
    'footer_btn_verdict' => 'PCA 2016 чечими',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Тогуз сызык чеги боюнча доомат',
    'footer_brand_eyebrow' => 'Атайын баракча · Вьетнамдын эгемендүүлүгү',
    'footer_brand_body' => 'Тогуз сызык чегин объективдүү чындык, эл аралык укук, PCA 2016 чечими жана тарыхый булактар аркылуу түшүндүрөт — <strong>"Парасел аралдары жана Спратли аралдары"</strong> эки архипелагынын эгемендүүлүгү тууралуу терең баракчаларды толуктайт. Кытайдын акылга сыйбас дооматын тарых жана далилдер аркылуу четке кагат.',
    'footer_refs_title' => 'Шилтеме булактар',
    'footer_ref1' => 'PCA чечими, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — толук текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Тарыхый материалдар жана эски карталар',
    'footer_toc_title' => 'Барактын мазмуну',
    'footer_toc1' => 'Тогуз сызык чеги деген эмне',
    'footer_toc2' => 'Келип чыгышы',
    'footer_toc3' => 'Эмне үчүн талаш жаратат',
    'footer_toc4' => 'Эмне үчүн эл аралык коомчулук каршы',
    'footer_toc5' => 'Тынч күбөлөр',
    'footer_toc6' => 'PCA 2016 чечими',
    'footer_toc7' => 'Парасел аралдары – Спратли аралдары',
    'footer_copy_eyebrow' => 'Коммерциялык эмес долбоор',
    'footer_copy_title' => 'Парасел аралдары – Спратли аралдары Вьетнамга таандык',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Вьетнамдын эгемендүүлүк экосистемасындагы Тогуз сызык чеги тууралуу атайын баракча.',
    'footer_copy_body' => 'Тогуз сызык чеги боюнча доомат <strong>объективдүү чындык</strong>, <strong>эл аралык укук</strong>, PCA 2016 чечими жана тарыхый материалдар аркылуу түшүндүрүлөт — Парасел аралдары жана Спратли аралдарынын эгемендүүлүгү тууралуу терең баракчаларды толуктайт.',
    'footer_copy_ecosystem_aria' => 'Ошол эле долбоордогу барактар',
    'footer_copy_ecosystem_label' => 'Бир экосистема',
    'footer_copy_disclaimer' => 'Мазмун билим берүү жана маалымдуулукту жогорулатуу үчүн арналган; Вьетнам мамлекетинин расмий көз карашын алмаштырбайт.',
    'footer_copy' => '<strong>© :year Тогуз сызык чеги</strong> — <strong>Парасел аралдары – Спратли аралдары Вьетнамга таандык</strong> коммерциялык эмес долбоорунун бир бөлүгү, төмөнкү системага кирет: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Барактын мазмундук кепилдиктери',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016 чечими',
    'footer_chip3' => 'Тарыхый далилдер',
    'footer_chip4' => 'Эски карталар',
    'footer_chip5' => 'Объективдүү чындык',
    'footer_chip6' => 'Түштүк Кытай деңизиндеги тынчтык',
];
