<?php

return [
    'footer_index' => 'Китепкана',
    'footer_crest_eyebrow' => 'Чындык китепканасын жыйынтыктоо',
    'footer_crest_quote' => '“Түштүк Кытай деңизиндеги тынчтык <b>эл аралык укуктун</b> негизинде курулат.”',
    'footer_crest_sub' => 'Жек көрүү жок · Болгону чындык',
    'footer_nav_aria' => 'Барактын ылдый жагындагы аракеттер',
    'footer_btn_top' => 'Барактын башына кайтуу',
    'footer_btn_verdict' => '2016-жылкы PCA чечими',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Тогуз сызык чеги боюнча дооматтар',
    'footer_brand_eyebrow' => 'Атайын барак · Вьетнамдын эгемендүүлүгү',
    'footer_brand_body' => 'Тогуз сызык чегин объективдүү чындык, эл аралык укук, 2016-жылкы PCA чечими жана тарыхый булактар аркылуу түшүндүрөт — эки архипелагдын <strong>"Парасел аралдары жана Спратли аралдары"</strong> эгемендүүлүгү боюнча терең барактарды толуктайт. Кытайдын негизсиз дооматтарын тарых жана далилдер менен жокко чыгарат.',
    'footer_refs_title' => 'Шилтеме булактары',
    'footer_ref1' => 'PCA чечими, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — толук текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Тарыхый материалдар жана байыркы карталар',
    'footer_toc_title' => 'Барактын мазмуну',
    'footer_toc1' => 'Тогуз сызык чеги деген эмне',
    'footer_toc2' => 'Келип чыгышы',
    'footer_toc3' => 'Эмне үчүн талаш жаратат',
    'footer_toc4' => 'Эмне үчүн эл аралык коомчулук каршы',
    'footer_toc5' => 'Тынч күбөлөр',
    'footer_toc6' => '2016-жылкы PCA чечими',
    'footer_toc7' => 'Парасел аралдары – Спратли аралдары',
    'footer_copy_eyebrow' => 'Коммерциялык эмес долбоор',
    'footer_copy_title' => 'Парасел аралдары – Спратли аралдары Вьетнамга таандык',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Вьетнамдын эгемендүүлүк экосистемасындагы Тогуз сызык чеги тууралуу атайын барак.',
    'footer_copy_body' => 'Тогуз сызык чеги дооматын <strong>объективдүү чындык</strong>, <strong>эл аралык укук</strong>, 2016-жылкы PCA чечими жана тарыхый булактар аркылуу түшүндүрөт — Парасел аралдары жана Спратли аралдарынын эгемендүүлүгү боюнча терең барактарды толуктайт.',
    'footer_copy_ecosystem_aria' => 'Ошол эле долбоордогу барактар',
    'footer_copy_ecosystem_label' => 'Ошол эле экосистема',
    'footer_copy_disclaimer' => 'Мазмун билим берүү жана маалымдуулукту жогорулатуу үчүн; Вьетнам мамлекетинин расмий көз карашын алмаштырбайт.',
    'footer_copy' => '<strong>© :year Тогуз сызык чеги</strong> — Коммерциялык эмес долбоордун бир бөлүгү <strong>Парасел аралдары – Спратли аралдары Вьетнамга таандык</strong> системасына кирет: <a href="https://paracelislands.net/ky" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ky" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ky" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ky" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ky" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Барак мазмунунун милдеттенмеси',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => '2016-жылкы PCA чечими',
    'footer_chip3' => 'Тарыхый далилдер',
    'footer_chip4' => 'Байыркы карталар',
    'footer_chip5' => 'Объективдүү чындык',
    'footer_chip6' => 'Түштүк Кытай деңизиндеги тынчтык',
];
