<?php

return [
    'nav_logo_name' => 'Тогуз сызык чеги',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Тогуз сызык чеги',
    'nav_rail_aria' => 'Бөлүмдөр боюнча навигация',
    'nav_rail_what' => 'Аныктама',
    'nav_rail_origin' => 'Келип чыгышы',
    'nav_rail_dispute' => 'Талаш-тартыш',
    'nav_rail_opposition' => 'Каршы пикир',
    'nav_rail_witnesses' => 'Байыркы карталар',
    'nav_rail_verdict' => '2016 PCA',
    'nav_rail_sovereignty' => 'Парасел аралдары – Спратли аралдары',
    'nav_sound_off' => 'Коштоочу музыканы күйгүзүү',
    'nav_sound_on' => 'Коштоочу музыканы өчүрүү',
    'nav_share' => 'Бөлүшүү',
    'dialog_title' => 'Көрсөтүү тили',
    'language' => 'Тил',
    'display_hint' => ':count тил',
    'search_placeholder' => 'Тилди издөө…',
    'cancel' => 'Жокко чыгаруу',
    'apply' => 'Колдонуу',
    'sound_off' => 'Коштоочу үндү күйгүзүү',
    'sound_on' => 'Коштоочу үндү өчүрүү',
    'lang_trigger' => 'Тилди тандоо',
    'close' => 'Жабуу',
    'no_results' => 'Тил табылган жок',
    'contribute' => 'Бөлүшүү',
];
