<?php

return [
    'footer_index' => 'Biblioteca',
    'footer_crest_eyebrow' => 'Encerrar a biblioteca da verdade',
    'footer_crest_quote' => '“A paz no Mar do Sul da China é construída sobre a base do <b>Direito internacional</b>.”',
    'footer_crest_sub' => 'Sem ódio · Apenas a verdade',
    'footer_nav_aria' => 'Ações do rodapé',
    'footer_btn_top' => 'Voltar ao topo',
    'footer_btn_verdict' => 'Sentença PCA de 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linha dos Nove Traços',
    'footer_brand_body' => 'Uma página explicativa baseada em fatos objetivos, no direito internacional e em documentos históricos — refutando a reivindicação da Linha dos Nove Traços com provas, não com slogans.',
    'footer_refs_title' => 'Fontes de referência',
    'footer_ref1' => 'Sentença da PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — texto integral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Materiais históricos e mapas antigos',
    'footer_toc_title' => 'Índice da página',
    'footer_toc1' => 'O que é a Linha dos Nove Traços',
    'footer_toc2' => 'Origem',
    'footer_toc3' => 'Por que gera controvérsia',
    'footer_toc4' => 'Por que a comunidade internacional se opõe',
    'footer_toc5' => 'Testemunhas silenciosas',
    'footer_toc6' => 'Sentença da PCA de 2016',
    'footer_toc7' => 'Ilhas Paracel - Ilhas Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Verdade objetiva sobre o Mar do Sul da China.<br>Ecossistema: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Sem coordenadas',
];
