<?php

return [
    'footer_index' => 'Biblioteca',
    'footer_crest_eyebrow' => 'Encerrando a biblioteca da verdade',
    'footer_crest_quote' => '“A paz no Mar do Sul da China é construída sobre a base do <b>Direito internacional</b>.”',
    'footer_crest_sub' => 'Sem ódio · Apenas a verdade',
    'footer_nav_aria' => 'Ações no rodapé',
    'footer_btn_top' => 'Voltar ao topo',
    'footer_btn_verdict' => 'Sentença da PCA de 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Reivindicação da Linha dos Nove Traços',
    'footer_brand_eyebrow' => 'Página temática · Soberania do Vietname',
    'footer_brand_body' => 'Explicação da Linha dos Nove Traços por meio da verdade objetiva, do direito internacional, da sentença da PCA de 2016 e de documentos históricos — complementar às páginas aprofundadas sobre a soberania dos dois arquipélagos <strong>"Ilhas Paracel e Ilhas Spratly"</strong>. Refuta a reivindicação ilógica da China com base na história e nas evidências.',
    'footer_refs_title' => 'Fontes de referência',
    'footer_ref1' => 'Sentença da PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — texto integral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documentos históricos e mapas antigos',
    'footer_toc_title' => 'Índice da página',
    'footer_toc1' => 'O que é a Linha dos Nove Traços',
    'footer_toc2' => 'Origem',
    'footer_toc3' => 'Por que é controversa',
    'footer_toc4' => 'Por que a comunidade internacional se opõe',
    'footer_toc5' => 'Testemunhas silenciosas',
    'footer_toc6' => 'Sentença da PCA de 2016',
    'footer_toc7' => 'Ilhas Paracel – Ilhas Spratly',
    'footer_copy_eyebrow' => 'Projeto sem fins lucrativos',
    'footer_copy_title' => 'As Ilhas Paracel – Ilhas Spratly pertencem ao Vietname',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Página temática sobre a Linha dos Nove Traços no ecossistema da soberania do Vietname.',
    'footer_copy_body' => 'Explicação da reivindicação da Linha dos Nove Traços por meio da <strong>verdade objetiva</strong>, do <strong>direito internacional</strong>, da sentença da PCA de 2016 e de documentos históricos — complementar às páginas aprofundadas sobre a soberania dos arquipélagos Ilhas Paracel e Ilhas Spratly.',
    'footer_copy_ecosystem_aria' => 'Páginas do mesmo projeto',
    'footer_copy_ecosystem_label' => 'Mesmo ecossistema',
    'footer_copy_disclaimer' => 'O conteúdo tem fins educativos e de sensibilização; não substitui a posição oficial do Estado do Vietname.',
    'footer_copy' => '<strong>© :year Linha dos Nove Traços</strong> — Parte do projeto sem fins lucrativos <strong>As Ilhas Paracel – Ilhas Spratly pertencem ao Vietname</strong> dentro do sistema: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Compromisso de conteúdo da página',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Sentença da PCA de 2016',
    'footer_chip3' => 'Evidências históricas',
    'footer_chip4' => 'Mapas antigos',
    'footer_chip5' => 'Verdade objetiva',
    'footer_chip6' => 'Paz no Mar do Sul da China',
];
