<?php

return [
    'nav_logo_name' => 'Linha dos Nove Traços',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linha dos Nove Traços',
    'nav_rail_aria' => 'Navegação por seção',
    'nav_rail_what' => 'Definição',
    'nav_rail_origin' => 'Origem',
    'nav_rail_dispute' => 'Controvérsia',
    'nav_rail_opposition' => 'Oposição',
    'nav_rail_witnesses' => 'Mapas antigos',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Ilhas Paracel - Ilhas Spratly',
    'nav_sound_off' => 'Ativar música de fundo',
    'nav_sound_on' => 'Desativar música de fundo',
    'nav_share' => 'Compartilhar',
    'dialog_title' => 'Idioma de exibição',
    'language' => 'Idioma',
    'display_hint' => ':count idiomas',
    'search_placeholder' => 'Pesquisar idioma…',
    'cancel' => 'Cancelar',
    'apply' => 'Aplicar',
    'sound_off' => 'Ativar som de fundo',
    'sound_on' => 'Desativar som de fundo',
    'lang_trigger' => 'Selecionar idioma',
    'close' => 'Fechar',
    'no_results' => 'Nenhum idioma encontrado',
    'contribute' => 'Compartilhar',
];
