<?php

return [
    'opposition_index' => 'Oposição',
    'opposition_label' => 'Por que a comunidade internacional se opõe',
    'opposition_title' => 'A oposição baseia-se em',
    'opposition_title_accent' => 'direito, não em emoções',
    'opposition_lead' => 'Logo após a Linha dos Nove Traços ser apresentada às Nações Unidas em 2009, vários países e académicos protestaram — com argumentos jurídicos específicos.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maio',
    'opposition_voice1_title' => 'Vietname · Malásia · Indonésia',
    'opposition_voice1_body' => 'Um dia após a China apresentar o mapa da Linha dos Nove Traços ao Secretário-Geral das Nações Unidas (7/5/2009), estes países enviaram sucessivamente notas diplomáticas de اعتراضo, rejeitando a reivindicação.',
    'opposition_voice1_chip1' => 'Nota diplomática de اعتراضo',
    'opposition_voice1_chip2' => 'Incompatível com a UNCLOS de 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipinas',
    'opposition_voice2_body' => 'Enviou uma nota diplomática às Nações Unidas, declarando que a reivindicação da China no Mar da China Meridional era “sem base no direito internacional” — o precedente para o caso posteriormente submetido ao Tribunal Arbitral.',
    'opposition_voice2_chip1' => 'Precedente do caso PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministério dos Negócios Estrangeiros dos Estados Unidos — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'A análise mostrou: os mapas de diferentes anos são inconsistentes quanto à posição da linha; a linha avança sobre o continente em vez de seguir a linha mediana; e muitas formações não cumprem os critérios de “ilha” para gerar ZEE.',
    'opposition_voice3_chip1' => 'Não reúne requisitos jurídicos',
    'opposition_voice3_chip2' => 'Análise oficial',
    'opposition_voice4_year' => 'Académico',
    'opposition_voice4_title' => 'A “área de águas históricas” está ultrapassada',
    'opposition_voice4_body' => 'Este conceito aplica-se apenas a baías e enseadas próximas da costa — não pode abranger uma vasta área de mar aberto. Em 2003, a própria Taiwan também rejeitou a política de “águas históricas” proposta em 1993.',
    'opposition_voice4_chip1' => 'Nem mesmo os académicos chineses estão de acordo',
];
