<?php

return [
    'sovereignty_index' => 'Ilhas Paracel - Ilhas Spratly',
    'sovereignty_label' => 'Conclusão inevitável',
    'sovereignty_title' => 'Ilhas Paracel - Ilhas Spratly',
    'sovereignty_title_accent' => 'são do Vietname',
    'sovereignty_lead' => 'Esta página explica a Linha dos Nove Traços. A conclusão responde à pergunta seguinte: quem tem soberania sobre as duas ilhas, Paracel e Spratly? Segundo a história da administração e o direito internacional, a resposta consistente é Vietname.',
    'sovereignty_thesis_label' => 'Tese sintetizada',
    'sovereignty_thesis_lock1' => 'Sem base jurídica de coordenadas',
    'sovereignty_thesis_lock2' => 'Rejeitada pelo PCA 2016',
    'sovereignty_thesis_lock3' => 'Mapas antigos não a abrangem',
    'sovereignty_thesis_body' => 'Após os seis pontos acima, três aspetos ficam claros: a Linha dos Nove Traços foi desenhada à mão, sem coordenadas jurídicas; o Tribunal Arbitral de 2016 rejeitou a pretensão; e os mapas antigos da própria China não abrangiam o Mar do Sul da China. A soberania do Vietname não se baseia em slogans, mas no facto de o Estado vietnamita — desde o tempo dos senhores Nguyễn — ter administrado, de forma pacífica e contínua, quando as duas ilhas ainda eram terra sem dono.',
    'sovereignty_spine_caption' => 'Marco de administração contínua',
    'sovereignty_spine_title' => 'Uma linha do tempo, sem interrupção',
    'sovereignty_spine_range' => 'Século XVII → presente',
    'sovereignty_chron1_year' => 'Séc. XVII',
    'sovereignty_chron1_title' => 'Equipa Hoàng Sa',
    'sovereignty_chron1_body' => 'Os senhores Nguyễn enviavam a equipa Hoàng Sa para reconhecer, medir rotas marítimas e explorar o mar — exercendo autoridade administrativa efetiva.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Rei Gia Long',
    'sovereignty_chron2_body' => 'Hasteou a bandeira no arquipélago de Ilhas Paracel, afirmando a soberania do Vietname perante o mundo da época.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Rei Minh Mạng',
    'sovereignty_chron3_body' => 'Mediu, ergueu estelas e registou o arquipélago nos mapas oficiais da corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Sucessão contínua',
    'sovereignty_chron4_body' => 'A França reconheceu e continuou a administração; anexou Paracel à província de Thừa Thiên — base para o Estado vietnamita atual.',
    'sovereignty_chron5_year' => 'Presente',
    'sovereignty_chron5_title' => 'Direito e prática',
    'sovereignty_chron5_body' => 'O Vietname administra com base na UNCLOS, na diplomacia e nos arquivos históricos; a pretensão da Linha dos Nove Traços não pode substituir estas provas.',
    'sovereignty_balance_label' => 'Equilíbrio das provas',
    'sovereignty_balance_medallion_title' => 'Comparação entre os dois lados',
    'sovereignty_vn_tag' => 'Lado do Vietname',
    'sovereignty_vn_title' => 'Soberania estabelecida por atos',
    'sovereignty_vn_body' => 'Posse efetiva quando a terra ainda estava sem dono, seguida de administração pública ao longo de séculos — com decretos imperiais, estelas, mapas e registos administrativos. Esta abordagem está em conformidade com a UNCLOS e com a prática internacional.',
    'sovereignty_dash_tag' => 'Lado da Linha dos Nove Traços',
    'sovereignty_dash_title' => 'Uma pretensão não substitui provas',
    'sovereignty_dash_body' => 'Uma linha desenhada em 1948, sem coordenadas, foi rejeitada pelo PCA 2016 e é contrária à UNCLOS — como exposto nos pontos 03 a 06. Por isso, a conclusão sobre a soberania das duas ilhas não pode basear-se na Linha dos Nove Traços.',
    'sovereignty_seal_quote' => 'O Vietname resolve disputas por <strong>meios pacíficos</strong>, com base no direito internacional — especialmente a UNCLOS 1982 — visando um Mar do Sul da China pacífico, cooperativo e em desenvolvimento.',
    'sovereignty_seal_cite' => 'Posição do Vietname · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Projeto principal no mesmo ecossistema',
    'sovereignty_next_title' => 'Leia todas as provas sobre as Ilhas Paracel - Ilhas Spratly',
    'sovereignty_next_body' => 'O dossiê detalhado — documentos, mapas, cronologia e fundamentos jurídicos — está em <strong>paracelislands.net</strong>, onde o tema da soberania das duas ilhas é apresentado de forma completa. A página que está a ler apenas faz a ligação lógica da Linha dos Nove Traços até essa conclusão.',
    'sovereignty_next_cta' => 'Abrir paracelislands.net',
];
