<?php

return [
    'sovereignty_index' => 'Ilhas Paracel - Ilhas Spratly',
    'sovereignty_label' => 'Conclusão necessária',
    'sovereignty_title' => 'Ilhas Paracel - Ilhas Spratly',
    'sovereignty_title_accent' => 'são do Vietname',
    'sovereignty_lead' => 'Esta página explica a Linha dos Nove Traços. A conclusão responde à questão seguinte: quem tem soberania sobre as duas arquipélagos, as Ilhas Paracel e as Ilhas Spratly? Segundo a história da administração e o direito internacional, a resposta consistente é o Vietname.',
    'sovereignty_thesis_label' => 'Tese consolidada',
    'sovereignty_thesis_lock1' => 'Sem coordenadas jurídicas',
    'sovereignty_thesis_lock2' => 'A PCA de 2016 rejeitou',
    'sovereignty_thesis_lock3' => 'Mapas antigos não abrangem',
    'sovereignty_thesis_body' => 'Após as seis secções acima, três pontos estão claros: a Linha dos Nove Traços foi desenhada à mão, sem coordenadas jurídicas; o Tribunal Arbitral de 2016 rejeitou a pretensão; e os mapas antigos da própria China não abrangem o Mar do Sul da China. A soberania do Vietname não se baseia em slogans, mas no facto de o Estado vietnamita — desde a época dos senhores Nguyễn — ter administrado de forma pacífica e contínua, quando os dois arquipélagos ainda eram terra de ninguém.',
    'sovereignty_spine_caption' => 'Marco de administração contínua',
    'sovereignty_spine_title' => 'Uma linha do tempo, sem interrupção',
    'sovereignty_spine_range' => 'Século XVII → presente',
    'sovereignty_chron1_year' => 'Séc. XVII',
    'sovereignty_chron1_title' => 'Equipe Hoàng Sa',
    'sovereignty_chron1_body' => 'Os senhores Nguyễn enviaram a equipe Hoàng Sa para inspecionar, medir as rotas marítimas e explorar no mar — exercendo o poder de administração de facto.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Rei Gia Long',
    'sovereignty_chron2_body' => 'Hasteou a bandeira nas Ilhas Paracel, afirmando a soberania do Vietname perante o mundo da época.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Rei Minh Mạng',
    'sovereignty_chron3_body' => 'Foram feitas medições, erguidas estelas e registadas as ilhas nos mapas oficiais da corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Sucessão contínua',
    'sovereignty_chron4_body' => 'A França reconheceu e continuou a administração; anexou Hoàng Sa à província de Thừa Thiên — base para o atual Estado do Vietname.',
    'sovereignty_chron5_year' => 'Presente',
    'sovereignty_chron5_title' => 'Direito e prática',
    'sovereignty_chron5_body' => 'O Vietname administra em conformidade com a UNCLOS, a diplomacia e os arquivos; a pretensão da Linha dos Nove Traços não pode substituir esta prova.',
    'sovereignty_balance_label' => 'Equilíbrio das provas',
    'sovereignty_balance_medallion_title' => 'Comparação dos dois lados',
    'sovereignty_vn_tag' => 'Lado vietnamita',
    'sovereignty_vn_title' => 'Soberania estabelecida por atos',
    'sovereignty_vn_body' => 'Posse efetiva quando a terra ainda era de ninguém, seguida de administração pública ao longo de muitos séculos — com documentos imperiais, estelas, mapas e registos administrativos. Esta prática está em conformidade com a UNCLOS e com os costumes internacionais.',
    'sovereignty_dash_tag' => 'Lado da Linha dos Nove Traços',
    'sovereignty_dash_title' => 'A pretensão não compensa a prova',
    'sovereignty_dash_body' => 'Uma linha desenhada em 1948, sem coordenadas, foi rejeitada pela PCA em 2016 e é contrária à UNCLOS — como demonstrado nas secções 03 a 06. É por isso que a conclusão sobre a soberania das duas arquipélagos não pode basear-se na Linha dos Nove Traços.',
    'sovereignty_seal_quote' => 'O Vietname resolve as disputas por <strong>meios pacíficos</strong>, com base no direito internacional — em particular a UNCLOS de 1982 — com vista a um Mar do Sul da China pacífico, cooperativo e em desenvolvimento.',
    'sovereignty_seal_cite' => 'Posição do Vietname · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Projeto principal no mesmo ecossistema',
    'sovereignty_next_title' => 'Leia a prova completa sobre as Ilhas Paracel - Ilhas Spratly',
    'sovereignty_next_body' => 'O dossiê detalhado — documentos, mapas, linha do tempo e argumentos jurídicos — está no site <strong>paracelislands.net</strong>, que apresenta de forma abrangente o tema da soberania das duas arquipélagos. A página que está a ler liga logicamente a Linha dos Nove Traços a essa conclusão.',
    'sovereignty_next_cta' => 'Abrir paracelislands.net',
];
