<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Sentença internacional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'os três "Não"',
    'verdict_lead' => 'Em 12/7/2016, a Corte Permanente de Arbitragem (PCA), em Haia — constituída nos termos do Anexo VII da UNCLOS, no caso Filipinas contra a China — proferiu uma sentença que rejeitou a reivindicação da Linha dos Nove Traços. <em>Toque em cada cartão para ler o texto integral.</em>',
    'verdict_card1_khong' => 'NÃO',
    'verdict_card1_title' => 'direitos históricos',
    'verdict_card1_short' => 'Não há base jurídica para a China invocar direitos históricos sobre os recursos nas águas situadas dentro da Linha dos Nove Traços.',
    'verdict_card1_quote' => '“Não há base jurídica para a China invocar direitos históricos sobre os recursos situados nas águas dentro da Linha dos Nove Traços.”',
    'verdict_card1_more' => '+ Ler a sentença',
    'verdict_card2_khong' => 'NÃO',
    'verdict_card2_title' => 'entidade geradora de ZEE',
    'verdict_card2_short' => 'Nenhuma entidade nas Ilhas Spratly reúne as condições para gerar uma zona econômica exclusiva para a China — incluindo a Ilha Ba Bình.',
    'verdict_card2_quote' => '“Nenhuma entidade nas Ilhas Spratly é capaz de gerar uma zona econômica exclusiva.”',
    'verdict_card2_more' => '+ Ler a sentença',
    'verdict_card3_khong' => 'NÃO',
    'verdict_card3_title' => 'conduta lícita',
    'verdict_card3_short' => 'A China violou os direitos soberanos das Filipinas, obstruiu a pesca e causou danos ao meio ambiente marinho.',
    'verdict_card3_quote' => '“A China violou os direitos soberanos das Filipinas, interferiu nas atividades de pesca em Scarborough Shoal e causou danos graves ao meio ambiente dos recifes de coral.”',
    'verdict_card3_more' => '+ Ler a sentença',
    'verdict_extra1' => 'A Linha dos Nove Traços desenhada unilateralmente pela China <strong>não é compatível</strong> com a UNCLOS de 1982.',
    'verdict_extra2' => 'A China causou danos ao ecossistema das Ilhas Spratly por meio da exploração excessiva e da construção de ilhas artificiais.',
    'verdict_extra3' => 'As ações da China aumentam o risco de conflito com as Filipinas.',
    'verdict_extra4' => 'A Ilha Ba Bình (controlada por Taiwan) também não pode gerar uma ZEE.',
    'verdict_subtitle' => 'Por que ela entra em conflito com a UNCLOS?',
    'verdict_subtitle_body' => 'A UNCLOS de 1982 define claramente as zonas marítimas com base na linha de base do Estado costeiro. A reivindicação da Linha dos Nove Traços vai além dessa estrutura e, portanto, não pode ser conciliada com ela.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mar territorial (milhas náuticas)',
    'verdict_zone1_body' => 'Zona marítima sob soberania do Estado, medida a partir da linha de base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona econômica exclusiva',
    'verdict_zone2_body' => 'ZEE — o Estado costeiro tem direitos soberanos sobre os recursos nessa área.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Plataforma continental (máximo, milhas náuticas)',
    'verdict_zone3_body' => 'Direitos sobre os recursos do leito marinho, conforme condições geológicas determinadas.',
    'verdict_foot' => 'Nessa estrutura, os “direitos históricos” que abrangem toda uma extensão de mar aberto — como a Linha dos Nove Traços sugere — <em>foram substituídos</em> pelo regime jurídico da UNCLOS, da qual a própria China também é parte.',
];
