<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Sentença internacional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'os três "Nãos"',
    'verdict_lead' => 'Em 12/7/2016, o Tribunal Permanente de Arbitragem (PCA) em Haia — constituído nos termos do Anexo VII da UNCLOS, no caso Filipinas contra a China — proferiu uma sentença rejeitando a reivindicação da Linha dos Nove Traços. <em>Clique em cada cartão para ler o texto completo.</em>',
    'verdict_card1_khong' => 'NÃO',
    'verdict_card1_title' => 'direitos históricos',
    'verdict_card1_short' => 'Não há base jurídica para a China invocar direitos históricos sobre os recursos nas águas dentro da Linha dos Nove Traços.',
    'verdict_card1_quote' => '“Não há fundamento jurídico para a China invocar direitos históricos sobre os recursos localizados nas águas dentro da Linha dos Nove Traços.”',
    'verdict_card1_more' => '+ Ler a sentença',
    'verdict_card2_khong' => 'NÃO',
    'verdict_card2_title' => 'entidade geradora de ZEE',
    'verdict_card2_short' => 'Nenhuma entidade no arquipélago de Ilhas Spratly reúne as condições para gerar uma zona económica exclusiva para a China — nem mesmo a Ilha Ba Bình.',
    'verdict_card2_quote' => '“Nenhuma entidade nas Ilhas Spratly é capaz de gerar uma zona económica exclusiva.”',
    'verdict_card2_more' => '+ Ler a sentença',
    'verdict_card3_khong' => 'NÃO',
    'verdict_card3_title' => 'conduta lícita',
    'verdict_card3_short' => 'A China violou os direitos soberanos das Filipinas, dificultou a pesca e causou danos ao meio ambiente marinho.',
    'verdict_card3_quote' => '“A China violou os direitos soberanos das Filipinas, interferiu nas atividades de pesca no Banco de Scarborough e causou danos graves ao ambiente dos recifes de coral.”',
    'verdict_card3_more' => '+ Ler a sentença',
    'verdict_extra1' => 'A Linha dos Nove Traços, traçada unilateralmente pela China, <strong>não é compatível</strong> com a UNCLOS de 1982.',
    'verdict_extra2' => 'A China causou danos ao ecossistema das Ilhas Spratly por meio de sobreexploração e construção de ilhas artificiais.',
    'verdict_extra3' => 'As ações da China aumentam o risco de conflito com as Filipinas.',
    'verdict_extra4' => 'A Ilha Ba Bình (sob controle de Taiwan) também não pode gerar uma ZEE.',
    'verdict_subtitle' => 'Por que isso entra em conflito com a UNCLOS?',
    'verdict_subtitle_body' => 'A UNCLOS de 1982 delimita claramente as zonas marítimas com base na linha de base do Estado costeiro. A reivindicação da Linha dos Nove Traços ultrapassa esse quadro e, por isso, não pode ser conciliada com ele.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mar territorial (milhas náuticas)',
    'verdict_zone1_body' => 'Área marítima sob soberania do Estado, contada a partir da linha de base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona económica exclusiva',
    'verdict_zone2_body' => 'ZEE — o Estado costeiro tem direitos soberanos sobre os recursos dentro desta área.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Plataforma continental (máximo, milhas náuticas)',
    'verdict_zone3_body' => 'Direitos sobre os recursos do fundo do mar, conforme as condições geológicas determinadas.',
    'verdict_foot' => 'Neste quadro, os “direitos históricos” que abrangem toda uma área de alto-mar — como a Linha dos Nove Traços sugere — <em>foram substituídos</em> pelo regime jurídico da UNCLOS, da qual a própria China também é membro.',
];
