<?php

return [
    'witnesses_index' => 'Mapa antigo',
    'witnesses_label' => 'Mapa antigo da China',
    'witnesses_title' => 'O ponto mais ao sul chega apenas até',
    'witnesses_title_accent' => 'a ilha de Hainan',
    'witnesses_lead' => 'Os mapas antigos desenhados por autores chineses — organizados em ordem cronológica — mostram todos <em>a ilha de Hainan como o ponto mais ao sul</em> da China, sem Hoàng Sa nem Trường Sa. Documentação compilada segundo <em>Soberania nacional do Vietname nas duas arquipélagos Hoàng Sa e Trường Sa</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Lupa',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— extremo sul do território —',
    'witnesses_map1_svg_era' => 'Dinastia Song · 1136',
    'witnesses_map1_title' => 'Mapa da dinastia Song, 1136',
    'witnesses_map1_body' => 'O território de China termina na ilha de Hainan — as Ilhas Paracel e as Ilhas Spratly ficam fora dos limites.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'limite de d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Mapa de d\'Anville, 1735',
    'witnesses_map2_body' => 'Desenhado por J.-B. B. d\'Anville; a cópia de 1740 foi oferecida pelo chanceler alemão ao líder de China. O território da dinastia Qing terminava em Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"extremo sul de China"',
    'witnesses_map3_svg_era' => 'Império Qing · 1904',
    'witnesses_map3_title' => 'Mapa geográfico completo das províncias sob a administração direta imperial',
    'witnesses_map3_body' => 'Impresso pela dinastia Qing — indica claramente que o extremo sul do território de China era a ilha de Hainan.',
    'witnesses_quote' => 'Os próprios mapas chineses já publicados nunca desenharam Hoàng Sa — Trường Sa como parte do seu território.',
    'witnesses_timeline_aria' => 'Linha do tempo dos mapas antigos da China',
    'witnesses_year_aria' => 'Data',
    'lightbox_aria' => 'Ver imagem ampliada',
    'lightbox_close' => 'Fechar',
    'lightbox_prev' => 'Imagem anterior',
    'lightbox_next' => 'Próxima imagem',
];
