<?php

return [
    'footer_index' => 'Libreria',
    'footer_crest_eyebrow' => 'Coro della biblioteca della verità',
    'footer_crest_quote' => '“La pace nel Mar Cinese Meridionale si costruisce sulle fondamenta del <b>diritto internazionale</b>.”',
    'footer_crest_sub' => 'Nessun odio · Solo la verità',
    'footer_nav_aria' => 'Azioni del footer',
    'footer_btn_top' => 'Torna all’inizio',
    'footer_btn_verdict' => 'Sentenza PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linea dei nove trattini',
    'footer_brand_body' => 'Una pagina esplicativa basata sulla verità oggettiva, sul diritto internazionale e sui documenti storici — che confuta le rivendicazioni della Linea dei nove trattini con prove, non con slogan.',
    'footer_refs_title' => 'Fonti di riferimento',
    'footer_ref1' => 'Sentenza PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — testo integrale',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Materiali storici e mappe antiche',
    'footer_toc_title' => 'Indice della pagina',
    'footer_toc1' => 'Che cos’è la Linea dei nove trattini',
    'footer_toc2' => 'Origine',
    'footer_toc3' => 'Perché è controversa',
    'footer_toc4' => 'Perché la comunità internazionale la respinge',
    'footer_toc5' => 'Testimoni silenziosi',
    'footer_toc6' => 'Sentenza PCA 2016',
    'footer_toc7' => 'Isole Paracel - Isole Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Verità oggettiva sul Mar Cinese Meridionale.<br>Ecosistema: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Nessuna coordinata',
];
