<?php

return [
    'footer_index' => 'Biblioteca',
    'footer_crest_eyebrow' => 'Sigillare la biblioteca della verità',
    'footer_crest_quote' => '“La pace nel Mar Cinese Meridionale si costruisce sulla base del <b>diritto internazionale</b>.”',
    'footer_crest_sub' => 'Nessun odio · Solo verità',
    'footer_nav_aria' => 'Azioni del piè di pagina',
    'footer_btn_top' => 'Torna all\'inizio',
    'footer_btn_verdict' => 'Sentenza PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Rivendicazione della Linea dei nove trattini',
    'footer_brand_eyebrow' => 'Sezione tematica · Sovranità del Vietnam',
    'footer_brand_body' => 'Spiegazione della Linea dei nove trattini attraverso fatti oggettivi, diritto internazionale, la sentenza PCA 2016 e documenti storici — a complemento delle pagine approfondite sulla sovranità delle due isole <strong>"Isole Paracel e Isole Spratly"</strong>. Confutazione delle pretese irragionevoli della Cina con la storia e le prove.',
    'footer_refs_title' => 'Fonti di riferimento',
    'footer_ref1' => 'Sentenza PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — testo completo',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documenti storici e mappe antiche',
    'footer_toc_title' => 'Indice della pagina',
    'footer_toc1' => 'Che cos\'è la Linea dei nove trattini',
    'footer_toc2' => 'Origine',
    'footer_toc3' => 'Perché è controversa',
    'footer_toc4' => 'Perché è respinta a livello internazionale',
    'footer_toc5' => 'Testimoni silenziosi',
    'footer_toc6' => 'Sentenza PCA 2016',
    'footer_toc7' => 'Isole Paracel – Isole Spratly',
    'footer_copy_eyebrow' => 'Progetto senza scopo di lucro',
    'footer_copy_title' => 'Le Isole Paracel – Isole Spratly appartengono al Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Sito tematico sulla Linea dei nove trattini nell\'ecosistema della sovranità del Vietnam.',
    'footer_copy_body' => 'Spiegazione della rivendicazione della Linea dei nove trattini attraverso <strong>fatti oggettivi</strong>, <strong>diritto internazionale</strong>, la sentenza PCA 2016 e documenti storici — a complemento delle pagine di approfondimento sulla sovranità delle due isole Paracel e Spratly.',
    'footer_copy_ecosystem_aria' => 'Siti dello stesso progetto',
    'footer_copy_ecosystem_label' => 'Stesso ecosistema',
    'footer_copy_disclaimer' => 'Il contenuto ha scopo educativo e di sensibilizzazione; non sostituisce la posizione ufficiale dello Stato del Vietnam.',
    'footer_copy' => '<strong>© :year Linea dei nove trattini</strong> — Parte del progetto senza scopo di lucro <strong>Le Isole Paracel – Isole Spratly appartengono al Vietnam</strong> nel sistema: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Impegno per i contenuti del sito',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Sentenza PCA 2016',
    'footer_chip3' => 'Prove storiche',
    'footer_chip4' => 'Mappe antiche',
    'footer_chip5' => 'Fatti oggettivi',
    'footer_chip6' => 'Pace nel Mar Cinese Meridionale',
];
