<?php

return [
    'nav_logo_name' => 'Linea dei nove trattini',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linea dei nove trattini',
    'nav_rail_aria' => 'Navigazione per sezioni',
    'nav_rail_what' => 'Definizione',
    'nav_rail_origin' => 'Origine',
    'nav_rail_dispute' => 'Controversia',
    'nav_rail_opposition' => 'Opposizione',
    'nav_rail_witnesses' => 'Mappe antiche',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Isole Paracel - Isole Spratly',
    'nav_sound_off' => 'Attiva la musica di sottofondo',
    'nav_sound_on' => 'Disattiva la musica di sottofondo',
    'nav_share' => 'Condividi',
    'dialog_title' => 'Lingua di visualizzazione',
    'language' => 'Lingua',
    'display_hint' => ':count lingue',
    'search_placeholder' => 'Cerca una lingua…',
    'cancel' => 'Annulla',
    'apply' => 'Applica',
    'sound_off' => 'Attiva l\'audio di sottofondo',
    'sound_on' => 'Disattiva l\'audio di sottofondo',
    'lang_trigger' => 'Scegli la lingua',
    'close' => 'Chiudi',
    'no_results' => 'Nessuna lingua trovata',
    'contribute' => 'Condividi',
];
