<?php

return [
    'opposition_index' => 'Opposizione',
    'opposition_label' => 'Perché la comunità internazionale si oppone',
    'opposition_title' => 'L’opposizione si basa su',
    'opposition_title_accent' => 'il diritto, non sulle emozioni',
    'opposition_lead' => 'Subito dopo che la Linea dei nove trattini fu presentata alle Nazioni Unite nel 2009, molti Stati e studiosi si opposero — con argomentazioni giuridiche specifiche.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maggio',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Appena un giorno dopo che la Cina presentò la mappa della Linea dei nove trattini al Segretario Generale delle Nazioni Unite (7/5/2009), questi Paesi inviarono successivamente note diplomatiche di protesta, respingendo la rivendicazione.',
    'opposition_voice1_chip1' => 'Nota diplomatica di protesta',
    'opposition_voice1_chip2' => 'Non conforme alla UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippine',
    'opposition_voice2_body' => 'Inviò una lettera diplomatica alle Nazioni Unite, dichiarando che la rivendicazione della Cina nel Mar Cinese Meridionale era “priva di fondamento secondo il diritto internazionale” — premessa del successivo ricorso all’Arbitrato.',
    'opposition_voice2_chip1' => 'Premessa del caso PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Ministero degli Affari Esteri degli Stati Uniti — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'L’analisi ha evidenziato che: le mappe di vari anni erano incoerenti nella posizione della linea; la linea invadeva la terraferma invece di seguire la linea mediana; molti elementi non soddisfacevano i requisiti di “isola” per avere una ZEE.',
    'opposition_voice3_chip1' => 'Non soddisfa i requisiti giuridici',
    'opposition_voice3_chip2' => 'Analisi ufficiale',
    'opposition_voice4_year' => 'Accademico',
    'opposition_voice4_title' => 'La “acque storiche” è superata',
    'opposition_voice4_body' => 'Questo concetto si applica solo a baie e insenature costiere — non può estendersi a un’ampia area di mare aperto. Nel 2003, anche Taiwan ha respinto la politica delle “acque storiche” formulata nel 1993.',
    'opposition_voice4_chip1' => 'Anche gli studiosi cinesi non sono concordi',
];
