<?php

return [
    'opposition_index' => 'Opposizione',
    'opposition_label' => 'Perché il mondo si oppone',
    'opposition_title' => 'L’opposizione si basa su',
    'opposition_title_accent' => 'il diritto, non sulle emozioni',
    'opposition_lead' => 'Subito dopo che la Linea dei nove trattini fu presentata alle Nazioni Unite nel 2009, molti Paesi e studiosi la respinsero — con argomentazioni giuridiche specifiche.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Maggio',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'A solo un giorno dalla presentazione da parte della Cina della mappa della Linea dei nove trattini al Segretario Generale delle Nazioni Unite (7/5/2009), questi Paesi inviarono rispettivamente note verbali di protesta, respingendo la rivendicazione.',
    'opposition_voice1_chip1' => 'Nota verbale di protesta',
    'opposition_voice1_chip2' => 'Non conforme alla UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filippine',
    'opposition_voice2_body' => 'Inviò una lettera diplomatica alle Nazioni Unite, dichiarando che la rivendicazione della Cina nel Mar Cinese Meridionale era “priva di fondamento secondo il diritto internazionale” — premessa del successivo arbitrato.',
    'opposition_voice2_chip1' => 'Premessa del caso PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Dipartimento di Stato degli Stati Uniti — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'L’analisi ha evidenziato che le mappe dei vari anni sono incoerenti nella posizione della linea tratteggiata; la linea penetra nell’entroterra invece di seguire la linea mediana; numerose entità non soddisfano i requisiti di “isola” per avere una EEZ.',
    'opposition_voice3_chip1' => 'Non soddisfa i requisiti giuridici',
    'opposition_voice3_chip2' => 'Analisi ufficiale',
    'opposition_voice4_year' => 'Accademico',
    'opposition_voice4_title' => 'Il “mare storico” è obsoleto',
    'opposition_voice4_body' => 'Questo concetto si applica solo a baie e insenature costiere — non può coprire un’intera vasta area di mare aperto. Nel 2003, anche Taiwan respinse la politica del “mare storico” formulata nel 1993.',
    'opposition_voice4_chip1' => 'Anche gli studiosi cinesi non sono d’accordo',
];
