<?php

return [
    'sovereignty_index' => 'Isole Paracel - Isole Spratly',
    'sovereignty_label' => 'Conclusione inevitabile',
    'sovereignty_title' => 'Isole Paracel - Isole Spratly',
    'sovereignty_title_accent' => 'appartengono al Vietnam',
    'sovereignty_lead' => 'Questa pagina spiega la Linea dei nove trattini. La conclusione risponde alla domanda successiva: chi ha la sovranità sulle due arcipelaghi delle Isole Paracel e delle Isole Spratly? Secondo la gestione storica e il diritto internazionale, la risposta coerente è il Vietnam.',
    'sovereignty_thesis_label' => 'Tesi sintetica',
    'sovereignty_thesis_lock1' => 'Nessuna base giuridica geografica',
    'sovereignty_thesis_lock2' => 'La PCA 2016 l\'ha respinta',
    'sovereignty_thesis_lock3' => 'Le mappe antiche non la coprono',
    'sovereignty_thesis_body' => 'Dopo i sei punti precedenti, tre aspetti sono chiari: la Linea dei nove trattini è tracciata a mano, senza coordinate giuridiche; il Tribunale Arbitrale del 2016 ha respinto la pretesa; le antiche mappe della Cina stessa non coprono il Mar Cinese Meridionale. La sovranità del Vietnam non si fonda su slogan, ma sul fatto che lo Stato vietnamita — fin dai tempi dei signori Nguyễn — ha amministrato pacificamente e in modo continuo quando i due arcipelaghi erano ancora terra nullius.',
    'sovereignty_spine_caption' => 'Pietre miliari di una gestione continua',
    'sovereignty_spine_title' => 'Una linea del tempo, senza interruzioni',
    'sovereignty_spine_range' => 'XVII secolo → oggi',
    'sovereignty_chron1_year' => 'XVII sec.',
    'sovereignty_chron1_title' => 'Squadra di Hoàng Sa',
    'sovereignty_chron1_body' => 'I signori Nguyễn inviarono la squadra di Hoàng Sa per ispezionare, rilevare le rotte marittime e sfruttare le risorse in mare — esercitando un controllo effettivo.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Re Gia Long',
    'sovereignty_chron2_body' => 'Fece innalzare la bandiera sulle Isole Paracel, affermando la sovranità del Vietnam davanti al mondo dell\'epoca.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Re Minh Mạng',
    'sovereignty_chron3_body' => 'Furono effettuati rilievi, erette stele e le isole vennero registrate sulle mappe ufficiali della corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Successione continua',
    'sovereignty_chron4_body' => 'La Francia riconobbe e continuò l\'amministrazione; le Isole Paracel furono incorporate nella provincia di Thừa Thiên — base per l\'attuale Stato del Vietnam.',
    'sovereignty_chron5_year' => 'Oggi',
    'sovereignty_chron5_title' => 'Diritto e prassi',
    'sovereignty_chron5_body' => 'Il Vietnam amministra in conformità all\'UNCLOS, alla diplomazia e agli archivi; la pretesa della Linea dei nove trattini non può sostituire queste prove.',
    'sovereignty_balance_label' => 'Bilanciamento delle prove',
    'sovereignty_balance_medallion_title' => 'Confronto tra le due parti',
    'sovereignty_vn_tag' => 'Parte del Vietnam',
    'sovereignty_vn_title' => 'Sovranità stabilita attraverso atti',
    'sovereignty_vn_body' => 'Occupazione effettiva quando la terra era ancora terra nullius, seguita da un\'amministrazione pubblica per molti secoli — con editti imperiali, stele, mappe e documenti amministrativi. Questo approccio è conforme all\'UNCLOS e alla prassi internazionale.',
    'sovereignty_dash_tag' => 'Parte della Linea dei nove trattini',
    'sovereignty_dash_title' => 'Una pretesa non può colmare le prove',
    'sovereignty_dash_body' => 'Una linea tracciata nel 1948, senza coordinate, è stata respinta dalla PCA nel 2016 ed è contraria all\'UNCLOS — come illustrato nei punti 03-06. Ecco perché la conclusione sulla sovranità dei due arcipelaghi non può basarsi sulla Linea dei nove trattini.',
    'sovereignty_seal_quote' => 'Il Vietnam risolve le controversie con <strong>mezzi pacifici</strong>, sulla base del diritto internazionale — in particolare dell\'UNCLOS del 1982 — mirando a un Mar Cinese Meridionale pacifico, cooperativo e prospero.',
    'sovereignty_seal_cite' => 'Posizione del Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Progetto principale nello stesso ecosistema',
    'sovereignty_next_title' => 'Leggi integralmente le prove sulle Isole Paracel - Isole Spratly',
    'sovereignty_next_body' => 'Il dossier dettagliato — documenti, mappe, linea del tempo e argomentazioni giuridiche — si trova sul sito <strong>paracelislands.net</strong>, che presenta in modo completo il tema della sovranità sui due arcipelaghi. La pagina che stai leggendo collega logicamente la Linea dei nove trattini a questa conclusione.',
    'sovereignty_next_cta' => 'Apri paracelislands.net',
];
