<?php

return [
    'sovereignty_index' => 'Isole Paracel - Isole Spratly',
    'sovereignty_label' => 'Conclusione inevitabile',
    'sovereignty_title' => 'Isole Paracel - Isole Spratly',
    'sovereignty_title_accent' => 'sono del Vietnam',
    'sovereignty_lead' => 'Questa pagina spiega la Linea dei nove trattini. La conclusione risponde alla domanda successiva: chi ha la sovranità sulle due isole Isole Paracel e Isole Spratly? Secondo la storia dell’amministrazione e il diritto internazionale, la risposta coerente è il Vietnam.',
    'sovereignty_thesis_label' => 'Tesi sintetica',
    'sovereignty_thesis_lock1' => 'Nessuna coordinata giuridica',
    'sovereignty_thesis_lock2' => 'PCA 2016 respinge',
    'sovereignty_thesis_lock3' => 'Le antiche mappe non coprono',
    'sovereignty_thesis_body' => 'Dopo i sei punti sopra, tre elementi sono chiari: la Linea dei nove trattini è tracciata a mano, senza coordinate giuridiche; il Tribunale arbitrale del 2016 ha respinto la rivendicazione; le antiche mappe della stessa Cina non coprono il Mar Cinese Meridionale. La sovranità del Vietnam non si basa su slogan, ma sul fatto che lo Stato vietnamita — fin dall’epoca dei signori Nguyễn — ha amministrato in modo pacifico e continuo quando le due isole erano ancora terra nullius.',
    'sovereignty_spine_caption' => 'Tappe di amministrazione continua',
    'sovereignty_spine_title' => 'Una linea temporale, senza interruzioni',
    'sovereignty_spine_range' => 'XVII secolo → oggi',
    'sovereignty_chron1_year' => 'XVII sec.',
    'sovereignty_chron1_title' => 'Squadra di Hoàng Sa',
    'sovereignty_chron1_body' => 'I signori Nguyễn inviarono la squadra di Hoàng Sa per ricognizione, rilevamento delle rotte marittime e sfruttamento in mare — esercitando un controllo effettivo.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Re Gia Long',
    'sovereignty_chron2_body' => 'Fece issare la bandiera sulle Isole Paracel, affermando la sovranità del Vietnam davanti al mondo dell’epoca.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Re Minh Mạng',
    'sovereignty_chron3_body' => 'Fece eseguire misurazioni, erigere stele e registrare le isole sulle mappe ufficiali della corte.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuità di successione',
    'sovereignty_chron4_body' => 'La Francia ne riconobbe e proseguì l’amministrazione; le Isole Paracel furono annesse alla provincia di Thừa Thiên — una base per l’attuale Stato del Vietnam.',
    'sovereignty_chron5_year' => 'Oggi',
    'sovereignty_chron5_title' => 'Diritto e prassi',
    'sovereignty_chron5_body' => 'Il Vietnam amministra in conformità con l’UNCLOS, la diplomazia e gli archivi; la rivendicazione della Linea dei nove trattini non può sostituire queste prove.',
    'sovereignty_balance_label' => 'Equilibrio delle prove',
    'sovereignty_balance_medallion_title' => 'Confronto tra le due parti',
    'sovereignty_vn_tag' => 'Lato Vietnam',
    'sovereignty_vn_title' => 'Sovranità stabilita dagli atti',
    'sovereignty_vn_body' => 'Occupazione effettiva quando la terra era ancora nullius, seguita da amministrazione pubblica per secoli — con editti imperiali, stele, mappe e documenti amministrativi. Questo metodo è conforme all’UNCLOS e alla prassi internazionale.',
    'sovereignty_dash_tag' => 'Lato Linea dei nove trattini',
    'sovereignty_dash_title' => 'Una rivendicazione che non sostituisce le prove',
    'sovereignty_dash_body' => 'Una linea tracciata nel 1948, senza coordinate, è stata respinta dalla PCA nel 2016 ed è contraria all’UNCLOS — come illustrato nei punti 03 a 06. Ecco perché la conclusione sulla sovranità delle due isole non può basarsi sulla Linea dei nove trattini.',
    'sovereignty_seal_quote' => 'Il Vietnam risolve le controversie con <strong>mezzi pacifici</strong>, sulla base del diritto internazionale — in particolare l’UNCLOS 1982 — mirando a un Mar Cinese Meridionale di pace, cooperazione e sviluppo.',
    'sovereignty_seal_cite' => 'Posizione del Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Progetto principale nello stesso ecosistema',
    'sovereignty_next_title' => 'Leggi integralmente le prove sulle Isole Paracel - Isole Spratly',
    'sovereignty_next_body' => 'Il dossier dettagliato — documenti, mappe, cronologia e argomentazioni giuridiche — si trova sul sito <strong>paracelislands.net</strong>, che presenta in modo completo il tema della sovranità sulle due isole. La pagina che stai leggendo collega soltanto, in modo logico, la Linea dei nove trattini a tale conclusione.',
    'sovereignty_next_cta' => 'Apri paracelislands.net',
];
