<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Verdetto internazionale',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'i tre “No”',
    'verdict_lead' => 'Il 12/7/2016, il Tribunale Arbitrale Permanente (PCA) dell’Aia — istituito secondo l’Allegato VII della UNCLOS, nel caso Filippine contro Cina — ha emesso una sentenza che respingeva le rivendicazioni della Linea dei nove trattini. <em>Clicca su ciascuna scheda per leggere il testo completo.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'diritto storico',
    'verdict_card1_short' => 'Non vi è alcuna base giuridica per cui la Cina possa rivendicare diritti storici sulle risorse nelle acque comprese nella Linea dei nove trattini.',
    'verdict_card1_quote' => '“Non vi è alcuna base giuridica per cui la Cina possa rivendicare diritti storici sulle risorse situate nelle acque all’interno della Linea dei nove trattini.”',
    'verdict_card1_more' => '+ Leggi il verdetto',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'entità che genera una ZEE',
    'verdict_card2_short' => 'Nessuna entità nelle Isole Spratly è idonea a generare una zona economica esclusiva per la Cina — compresa l’isola di Ba Bình.',
    'verdict_card2_quote' => '“Nessuna entità nelle Isole Spratly è in grado di generare una zona economica esclusiva.”',
    'verdict_card2_more' => '+ Leggi il verdetto',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'condotta legale',
    'verdict_card3_short' => 'La Cina ha violato i diritti sovrani del Vietnam, ostacolato la pesca e danneggiato l’ambiente marino.',
    'verdict_card3_quote' => '“La Cina ha violato i diritti sovrani del Vietnam, interferito con le attività di pesca alla barriera di Scarborough e causato gravi danni all’ambiente della barriera corallina.”',
    'verdict_card3_more' => '+ Leggi il verdetto',
    'verdict_extra1' => 'La Linea dei nove trattini tracciata unilateralmente dalla Cina <strong>non è conforme</strong> alla UNCLOS del 1982.',
    'verdict_extra2' => 'La Cina ha danneggiato l’ecosistema delle Isole Spratly attraverso lo sfruttamento eccessivo e la costruzione di isole artificiali.',
    'verdict_extra3' => 'Le azioni della Cina aumentano il rischio di conflitto con il Vietnam.',
    'verdict_extra4' => 'L’isola di Ba Bình (controllata da Taiwan) inoltre non può generare una ZEE.',
    'verdict_subtitle' => 'Perché è in conflitto con la UNCLOS?',
    'verdict_subtitle_body' => 'La UNCLOS 1982 definisce chiaramente le zone marittime in base alle linee di base dello Stato costiero. La rivendicazione della Linea dei nove trattini va oltre questo quadro, quindi non può essere sovrapposta ad esso.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mare territoriale (miglia nautiche)',
    'verdict_zone1_body' => 'Zona marittima sotto sovranità nazionale, misurata a partire dalle linee di base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona economica esclusiva',
    'verdict_zone2_body' => 'ZEE — lo Stato costiero ha diritti sovrani sulle risorse entro questo limite.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Piattaforma continentale (massimo, miglia nautiche)',
    'verdict_zone3_body' => 'Diritti sulle risorse del fondale marino, secondo condizioni geologiche definite.',
    'verdict_foot' => 'In questo quadro, i “diritti storici” che abbracciano un’intera area di mare aperto — come implica la Linea dei nove trattini — <em>sono stati sostituiti</em> dal regime giuridico della UNCLOS, di cui anche la Cina è parte.',
];
