<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Sentenza internazionale',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'i tre "No"',
    'verdict_lead' => 'Il 12/7/2016, il Tribunale arbitrale permanente (PCA) dell\'Aia — istituito ai sensi dell\'Allegato VII dell\'UNCLOS, nel caso delle Filippine contro la Cina — ha emesso una sentenza che respinge le rivendicazioni della Linea dei nove trattini. <em>Fai clic su ogni scheda per leggere il testo integrale.</em>',
    'verdict_card1_khong' => 'NO',
    'verdict_card1_title' => 'diritto storico',
    'verdict_card1_short' => 'Non esiste alcuna base giuridica per cui la Cina invochi diritti storici sulle risorse nelle acque racchiuse dalla Linea dei nove trattini.',
    'verdict_card1_quote' => '“Non esiste alcuna base giuridica per cui la Cina invochi diritti storici sulle risorse situate nelle acque all\'interno della Linea dei nove trattini.”',
    'verdict_card1_more' => '+ Leggi la sentenza',
    'verdict_card2_khong' => 'NO',
    'verdict_card2_title' => 'entità che genera una ZEE',
    'verdict_card2_short' => 'Nessuna entità delle Isole Spratly è idonea a generare una zona economica esclusiva per la Cina — neppure l\'isola di Ba Bình.',
    'verdict_card2_quote' => '“Nessuna entità delle Isole Spratly è in grado di generare una zona economica esclusiva.”',
    'verdict_card2_more' => '+ Leggi la sentenza',
    'verdict_card3_khong' => 'NO',
    'verdict_card3_title' => 'comportamento legittimo',
    'verdict_card3_short' => 'La Cina ha violato i diritti sovrani delle Filippine, ostacolato la pesca e danneggiato l\'ambiente marino.',
    'verdict_card3_quote' => '“La Cina ha violato i diritti sovrani delle Filippine, interferito con le attività di pesca presso il banco di Scarborough e causato gravi danni all\'ambiente della barriera corallina.”',
    'verdict_card3_more' => '+ Leggi la sentenza',
    'verdict_extra1' => 'La Linea dei nove trattini tracciata unilateralmente dalla Cina <strong>non è conforme</strong> all\'UNCLOS 1982.',
    'verdict_extra2' => 'La Cina ha causato danni all\'ecosistema delle Isole Spratly attraverso lo sfruttamento eccessivo e la costruzione di isole artificiali.',
    'verdict_extra3' => 'Le azioni della Cina aumentano il rischio di conflitto con le Filippine.',
    'verdict_extra4' => 'Anche l\'isola di Ba Bình (controllata da Taiwan) non può generare una ZEE.',
    'verdict_subtitle' => 'Perché è in conflitto con l\'UNCLOS?',
    'verdict_subtitle_body' => 'L\'UNCLOS 1982 definisce chiaramente le zone marittime sulla base delle linee di base dello Stato costiero. Le rivendicazioni della Linea dei nove trattini esulano da questo quadro e quindi non possono essere poste sullo stesso piano.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Mare territoriale (miglia nautiche)',
    'verdict_zone1_body' => 'Zona marittima soggetta alla sovranità dello Stato, misurata a partire dalle linee di base.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona economica esclusiva',
    'verdict_zone2_body' => 'ZEE — lo Stato costiero ha diritti sovrani sulle risorse entro questo limite.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Piattaforma continentale (massimo, miglia nautiche)',
    'verdict_zone3_body' => 'Diritti sulle risorse del fondo marino, secondo condizioni geologiche determinate.',
    'verdict_foot' => 'In questo quadro, i “diritti storici” che si estendono su un\'intera area di alto mare — come implica la Linea dei nove trattini — <em>sono stati sostituiti</em> dal regime giuridico dell\'UNCLOS, di cui anche la Cina è parte.',
];
