<?php

return [
    'witnesses_index' => 'Carte antiche',
    'witnesses_label' => 'Carte antiche cinesi',
    'witnesses_title' => 'L’estremo meridionale arriva solo fino a',
    'witnesses_title_accent' => 'isola di Hainan',
    'witnesses_lead' => 'Le carte antiche disegnate da autori cinesi — ordinate in sequenza cronologica — mostrano tutte <em>l’isola di Hainan come limite meridionale estremo</em> della Cina, senza Isole Paracel né Isole Spratly. Materiale sintetizzato da <em>Sovranità nazionale del Vietnam sulle due arcipelaghi delle Isole Paracel e delle Isole Spratly</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Lente d’ingrandimento',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— limite meridionale del territorio —',
    'witnesses_map1_svg_era' => 'Dinastia Song · 1136',
    'witnesses_map1_title' => 'Mappa della dinastia Song, 1136',
    'witnesses_map1_body' => 'Il territorio della Cina si fermava all’isola di Hainan — le Isole Paracel e le Isole Spratly erano al di fuori dei suoi confini.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'confine di d’Anville',
    'witnesses_map2_svg_era' => 'd’Anville · 1735',
    'witnesses_map2_title' => 'Mappa di d’Anville, 1735',
    'witnesses_map2_body' => 'Disegnata da J.-B. B. d’Anville; la copia del 1740 fu donata dal Cancelliere tedesco a un leader cinese. Il territorio della dinastia Qing si fermava a Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"estremo sud della Cina"',
    'witnesses_map3_svg_era' => 'Atlante geografico delle province sotto il dominio imperiale · 1904',
    'witnesses_map3_title' => 'Atlante geografico delle province sotto il dominio imperiale',
    'witnesses_map3_body' => 'Stampato sotto la dinastia Qing — indica chiaramente che il punto più meridionale del territorio cinese era l’isola di Hainan.',
    'witnesses_quote' => 'Le stesse carte della Cina pubblicate in passato non raffiguravano le Isole Paracel e le Isole Spratly come parte del loro territorio.',
    'witnesses_timeline_aria' => 'Cronologia delle antiche carte cinesi',
    'witnesses_year_aria' => 'Datazione',
    'lightbox_aria' => 'Visualizza immagine ingrandita',
    'lightbox_close' => 'Chiudi',
    'lightbox_prev' => 'Immagine precedente',
    'lightbox_next' => 'Immagine successiva',
];
