<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Завршетак библиотеке чињеница',
    'footer_crest_quote' => '„Мир у Јужном кинеском мору гради се на темељу <b>међународног права</b>.“',
    'footer_crest_sub' => 'Без мржње · Само чињенице',
    'footer_nav_aria' => 'Акције у подножју странице',
    'footer_btn_top' => 'На врх странице',
    'footer_btn_verdict' => 'Одлука PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Захтев за Линија девет цртица',
    'footer_brand_eyebrow' => 'Тематска страница · Суверенитет Вијетнама',
    'footer_brand_body' => 'Објашњење Линија девет цртица кроз објективне чињенице, међународно право, одлуку PCA 2016 и историјску грађу — допуна детаљним страницама о суверенитету над два архипелага <strong>"Параселска острва и Спратли острва"</strong>. Оспоравање неоснованих захтева Кине на основу историје и доказа.',
    'footer_refs_title' => 'Извори',
    'footer_ref1' => 'Одлука PCA, 12. 7. 2016.',
    'footer_ref2' => 'UNCLOS 1982 — цео текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Историјска грађа и старе карте',
    'footer_toc_title' => 'Садржај странице',
    'footer_toc1' => 'Шта је Линија девет цртица',
    'footer_toc2' => 'Порекло',
    'footer_toc3' => 'Зашто је спорна',
    'footer_toc4' => 'Зашто је међународно оспоравана',
    'footer_toc5' => 'Тихи сведоци',
    'footer_toc6' => 'Одлука PCA 2016',
    'footer_toc7' => 'Параселска острва – Спратли острва',
    'footer_copy_eyebrow' => 'Непрофитни пројекат',
    'footer_copy_title' => 'Параселска острва – Спратли острва су део Вијетнама',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Тематска страница о Линија девет цртица у суверенитетском екосистему Вијетнама.',
    'footer_copy_body' => 'Објашњење захтева Линија девет цртица кроз <strong>објективне чињенице</strong>, <strong>међународно право</strong>, одлуку PCA 2016 и историјску грађу — допуна детаљним страницама о суверенитету над архипелазима Параселска острва и Спратли острва.',
    'footer_copy_ecosystem_aria' => 'Странице истог пројекта',
    'footer_copy_ecosystem_label' => 'Исти екосистем',
    'footer_copy_disclaimer' => 'Садржај је намењен образовању и подизању свести; не замењује званичан став Државе Вијетнам.',
    'footer_copy' => '<strong>© :year Линија девет цртица</strong> — Део непрофитног пројекта <strong>Параселска острва – Спратли острва су део Вијетнама</strong> у оквиру система: <a href="https://paracelislands.net/sr" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/sr" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/sr" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/sr" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/sr" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Потврда садржаја странице',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Одлука PCA 2016',
    'footer_chip3' => 'Историјски докази',
    'footer_chip4' => 'Старе карте',
    'footer_chip5' => 'Објективне чињенице',
    'footer_chip6' => 'Мир у Јужном кинеском мору',
];
