<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Завршетак библиотеке истине',
    'footer_crest_quote' => '„Мир у Јужном кинеском мору гради се на темељу <b>међународног права</b>.“',
    'footer_crest_sub' => 'Без мржње · Само истина',
    'footer_nav_aria' => 'Акције у подножју странице',
    'footer_btn_top' => 'На врх странице',
    'footer_btn_verdict' => 'Пресуда PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Линија девет цртица',
    'footer_brand_body' => 'Страница која објашњава на основу објективних чињеница, међународног права и историјских докумената — побија захтеве Линија девет цртица доказима, а не паролама.',
    'footer_refs_title' => 'Извори',
    'footer_ref1' => 'Пресуда PCA, 12. 7. 2016.',
    'footer_ref2' => 'UNCLOS 1982 — пуни текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Историјски материјали и старе карте',
    'footer_toc_title' => 'Садржај странице',
    'footer_toc1' => 'Шта је Линија девет цртица',
    'footer_toc2' => 'Порекло',
    'footer_toc3' => 'Зашто је спорна',
    'footer_toc4' => 'Зашто јој се међународно противи',
    'footer_toc5' => 'Тихи сведоци',
    'footer_toc6' => 'Пресуда PCA 2016',
    'footer_toc7' => 'Параселска острва – Спратли острва',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Објективна истина о Јужном кинеском мору.<br>Екосистем: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Без координата',
];
