<?php

return [
    'footer_index' => 'Библиотека',
    'footer_crest_eyebrow' => 'Завршетак библиотеке чињеница',
    'footer_crest_quote' => '„Мир у Јужнокинеском мору гради се на темељу <b>међународног права</b>."',
    'footer_crest_sub' => 'Без мржње · Само чињенице',
    'footer_nav_aria' => 'Радње у подножју странице',
    'footer_btn_top' => 'На врх странице',
    'footer_btn_verdict' => 'Одлука PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Спор о Линији девет цртица',
    'footer_brand_eyebrow' => 'Стручна страница · Суверенитет Вијетнам',
    'footer_brand_body' => 'Објашњење Линије девет цртица кроз објективне чињенице, међународно право, одлуку PCA из 2016. и историјске изворе — као допуна детаљним страницама о суверенитету над два архипелага <strong>"Параселска острва и Спратли острва"</strong>. Оспоравање неоснованог потраживања Кина историјом и доказима.',
    'footer_refs_title' => 'Извори',
    'footer_ref1' => 'Одлука PCA, 12. 7. 2016.',
    'footer_ref2' => 'UNCLOS 1982 — цео текст',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Историјски извори и старе карте',
    'footer_toc_title' => 'Садржај странице',
    'footer_toc1' => 'Шта је Линија девет цртица',
    'footer_toc2' => 'Порекло',
    'footer_toc3' => 'Зашто је спорна',
    'footer_toc4' => 'Зашто је међународно одбачена',
    'footer_toc5' => 'Тихи сведоци',
    'footer_toc6' => 'Одлука PCA 2016',
    'footer_toc7' => 'Параселска острва – Спратли острва',
    'footer_copy_eyebrow' => 'Непрофитни пројекат',
    'footer_copy_title' => 'Параселска острва – Спратли острва су Вијетнам',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Стручна страница о Линији девет цртица у екосистему суверенитета Вијетнам.',
    'footer_copy_body' => 'Објашњење потраживања Линије девет цртица кроз <strong>објективне чињенице</strong>, <strong>међународно право</strong>, одлуку PCA 2016. и историјске изворе — као допуна детаљним страницама о суверенитету над два архипелага Параселска острва и Спратли острва.',
    'footer_copy_ecosystem_aria' => 'Странице у истом пројекту',
    'footer_copy_ecosystem_label' => 'У истом екосистему',
    'footer_copy_disclaimer' => 'Садржај је намењен образовању и подизању свести; не замењује званични став Државе Вијетнам.',
    'footer_copy' => '<strong>© :year Линија девет цртица</strong> — Део непрофитног пројекта <strong>Параселска острва – Спратли острва су Вијетнам</strong> у оквиру система: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Обавеза садржаја странице',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Одлука PCA 2016',
    'footer_chip3' => 'Историјски докази',
    'footer_chip4' => 'Старе карте',
    'footer_chip5' => 'Објективне чињенице',
    'footer_chip6' => 'Мир у Јужном кинеском мору',
];
