<?php

return [
    'nav_logo_name' => 'Линија девет цртица',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Линија девет цртица',
    'nav_rail_aria' => 'Навигација по одељцима',
    'nav_rail_what' => 'Дефиниција',
    'nav_rail_origin' => 'Порекло',
    'nav_rail_dispute' => 'Спор',
    'nav_rail_opposition' => 'Противљење',
    'nav_rail_witnesses' => 'Старе карте',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Параселска острва – Спратли острва',
    'nav_sound_off' => 'Укључи позадинску музику',
    'nav_sound_on' => 'Искључи позадинску музику',
    'nav_share' => 'Подели',
    'dialog_title' => 'Језик приказа',
    'language' => 'Језик',
    'display_hint' => ':count језика',
    'search_placeholder' => 'Претражи језик…',
    'cancel' => 'Откажи',
    'apply' => 'Примени',
    'sound_off' => 'Укључи звук у позадини',
    'sound_on' => 'Искључи звук у позадини',
    'lang_trigger' => 'Изабери језик',
    'close' => 'Затвори',
    'no_results' => 'Ниједан језик није пронађен',
    'contribute' => 'Подели',
];
