<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Međunarodna presuda',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tri „ne"',
    'verdict_lead' => 'Dana 12. 7. 2016, Stalni arbitražni sud (PCA) u Hagu — osnovan prema Aneksu VII UNCLOS-a, u slučaju Filipini protiv Kine — doneo je presudu kojom je odbacio zahtev Линија девет цртица. <em>Kliknite na svaku karticu da pročitate pun tekst.</em>',
    'verdict_card1_khong' => 'NE',
    'verdict_card1_title' => 'istorijsko pravo',
    'verdict_card1_short' => 'Ne postoji pravni osnov da Kina ističe istorijsko pravo na resurse u morskom području unutar Линија девет цртица.',
    'verdict_card1_quote' => '„Ne postoji pravni osnov za to da Kina ističe istorijsko pravo na resurse koji se nalaze u morskom području unutar Линија девет цртица.”',
    'verdict_card1_more' => '+ Pročitaj presudu',
    'verdict_card2_khong' => 'NE',
    'verdict_card2_title' => 'subjekat koji stvara EPZ',
    'verdict_card2_short' => 'Nijedan objekat na Spratli ostrva ne ispunjava uslove da stvori isključivu ekonomsku zonu za Kinu — uključujući i ostrvo Ba Bình.',
    'verdict_card2_quote' => '„Ni jedan objekat na Spratli ostrva nije sposoban da stvori isključivu ekonomsku zonu.”',
    'verdict_card2_more' => '+ Pročitaj presudu',
    'verdict_card3_khong' => 'NE',
    'verdict_card3_title' => 'zakonito ponašanje',
    'verdict_card3_short' => 'Kina je povredila suverena prava Filipina, ometala ribolov i nanela štetu morskoj sredini.',
    'verdict_card3_quote' => '„Kina je povredila suverena prava Filipina, ometala ribolovne aktivnosti na grebenu Skarboro i nanela ozbiljnu štetu koralnom ekosistemu.”',
    'verdict_card3_more' => '+ Pročitaj presudu',
    'verdict_extra1' => 'Линија девет цртица koju je Kina sama nacrtala <strong>nije u skladu</strong> sa UNCLOS-om iz 1982.',
    'verdict_extra2' => 'Kina je nanelа štetu ekosistemu Spratli ostrva prekomernom eksploatacijom i izgradnjom veštačkih ostrva.',
    'verdict_extra3' => 'Postupci Kine povećavaju rizik od sukoba sa Filipinima.',
    'verdict_extra4' => 'Ostrvo Ba Bình (koje kontroliše Tajvan) takođe ne može da stvori EPZ.',
    'verdict_subtitle' => 'Zašto je to u sukobu sa UNCLOS-om?',
    'verdict_subtitle_body' => 'UNCLOS iz 1982. jasno određuje morske zone na osnovu osnovne linije priobalne države. Zahtev Линија девет цртица izlazi van tog okvira, pa se ne može uskladiti sa njim.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Teritorijalno more (morske milje)',
    'verdict_zone1_body' => 'Državna morska zona pod suverenitetom, merena od osnovne linije.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Isključiva ekonomska zona',
    'verdict_zone2_body' => 'EPZ — priobalna država ima suverena prava na resurse u ovom području.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Kontinentalni pojas (najviše, morske milje)',
    'verdict_zone3_body' => 'Prava na resurse morskog dna, prema utvrđenim geološkim uslovima.',
    'verdict_foot' => 'U ovom okviru, „istorijsko pravo“ koje obuhvata čitavo otvoreno more — kao što implicira Линија девет цртица — <em>zamenjeno je</em> pravnim režimom UNCLOS-a, čija je i Kina članica.',
];
