<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Menutup perpustakaan kebenaran',
    'footer_crest_quote' => '“Perdamaian di Laut Tiongkok Selatan dibangun di atas fondasi <b>Hukum internasional</b>.”',
    'footer_crest_sub' => 'Tanpa kebencian · Hanya kebenaran',
    'footer_nav_aria' => 'Tindakan di bagian bawah halaman',
    'footer_btn_top' => 'Kembali ke atas',
    'footer_btn_verdict' => 'Putusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Garis Sembilan Titik',
    'footer_brand_body' => 'Sebuah laman penjelasan yang berpijak pada kebenaran objektif, hukum internasional, dan dokumen sejarah — membantah klaim Garis Sembilan Titik dengan bukti, bukan slogan.',
    'footer_refs_title' => 'Sumber referensi',
    'footer_ref1' => 'Putusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks lengkap',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Dokumen sejarah & peta kuno',
    'footer_toc_title' => 'Daftar isi halaman',
    'footer_toc1' => 'Apa itu Garis Sembilan Titik',
    'footer_toc2' => 'Asal-usul',
    'footer_toc3' => 'Mengapa diperdebatkan',
    'footer_toc4' => 'Mengapa ditolak oleh komunitas internasional',
    'footer_toc5' => 'Saksi yang diam',
    'footer_toc6' => 'Putusan PCA 2016',
    'footer_toc7' => 'Kepulauan Paracel – Kepulauan Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Kebenaran objektif tentang Laut Tiongkok Selatan.<br>Ekosistem: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Tanpa koordinat',
];
