<?php

return [
    'footer_index' => 'Perpustakaan',
    'footer_crest_eyebrow' => 'Penutup perpustakaan kebenaran',
    'footer_crest_quote' => '“Perdamaian di Laut Cina Selatan dibangun di atas fondasi <b>hukum internasional</b>.”',
    'footer_crest_sub' => 'Tanpa kebencian · Hanya kebenaran',
    'footer_nav_aria' => 'Tindakan akhir halaman',
    'footer_btn_top' => 'Kembali ke atas',
    'footer_btn_verdict' => 'Putusan PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Klaim Garis Sembilan Titik',
    'footer_brand_eyebrow' => 'Halaman tematik · Kedaulatan Vietnam',
    'footer_brand_body' => 'Menjelaskan Garis Sembilan Titik melalui fakta objektif, hukum internasional, putusan PCA 2016, dan dokumen sejarah — sebagai pelengkap bagi halaman-halaman mendalam tentang kedaulatan atas dua gugusan pulau <strong>"Kepulauan Paracel dan Kepulauan Spratly"</strong>. Menyangkal klaim tidak masuk akal Tiongkok dengan sejarah dan bukti.',
    'footer_refs_title' => 'Sumber rujukan',
    'footer_ref1' => 'Putusan PCA, 12/7/2016',
    'footer_ref2' => 'UNCLOS 1982 — teks lengkap',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Dokumen sejarah & peta kuno',
    'footer_toc_title' => 'Daftar isi halaman',
    'footer_toc1' => 'Apa itu Garis Sembilan Titik',
    'footer_toc2' => 'Asal-usul',
    'footer_toc3' => 'Mengapa diperdebatkan',
    'footer_toc4' => 'Mengapa ditolak secara internasional',
    'footer_toc5' => 'Saksi diam',
    'footer_toc6' => 'Putusan PCA 2016',
    'footer_toc7' => 'Kepulauan Paracel – Kepulauan Spratly',
    'footer_copy_eyebrow' => 'Proyek nirlaba',
    'footer_copy_title' => 'Kepulauan Paracel – Kepulauan Spratly adalah milik Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Halaman tematik tentang Garis Sembilan Titik dalam ekosistem kedaulatan Vietnam.',
    'footer_copy_body' => 'Menjelaskan klaim Garis Sembilan Titik melalui <strong>fakta objektif</strong>, <strong>hukum internasional</strong>, putusan PCA 2016, dan dokumen sejarah — sebagai pelengkap bagi halaman-halaman mendalam tentang kedaulatan atas Kepulauan Paracel dan Kepulauan Spratly.',
    'footer_copy_ecosystem_aria' => 'Halaman-halaman dalam proyek yang sama',
    'footer_copy_ecosystem_label' => 'Satu ekosistem',
    'footer_copy_disclaimer' => 'Konten ini bertujuan untuk pendidikan dan peningkatan kesadaran; bukan pengganti pandangan resmi Negara Vietnam.',
    'footer_copy' => '<strong>© :year Garis Sembilan Titik</strong> — Bagian dari proyek nirlaba <strong>Kepulauan Paracel – Kepulauan Spratly adalah milik Vietnam</strong> dalam sistem: <a href="https://paracelislands.net/id" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/id" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/id" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/id" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/id" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Komitmen konten halaman',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Putusan PCA 2016',
    'footer_chip3' => 'Bukti sejarah',
    'footer_chip4' => 'Peta kuno',
    'footer_chip5' => 'Fakta objektif',
    'footer_chip6' => 'Perdamaian Laut Cina Selatan',
];
