<?php

return [
    'nav_logo_name' => 'Garis Sembilan Titik',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Garis Sembilan Titik',
    'nav_rail_aria' => 'Navigasi per bagian',
    'nav_rail_what' => 'Definisi',
    'nav_rail_origin' => 'Asal-usul',
    'nav_rail_dispute' => 'Sengketa',
    'nav_rail_opposition' => 'Penolakan',
    'nav_rail_witnesses' => 'Peta Kuno',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Kepulauan Paracel - Kepulauan Spratly',
    'nav_sound_off' => 'Nyalakan musik latar',
    'nav_sound_on' => 'Matikan musik latar',
    'nav_share' => 'Bagikan',
    'dialog_title' => 'Bahasa tampilan',
    'language' => 'Bahasa',
    'display_hint' => ':count bahasa',
    'search_placeholder' => 'Cari bahasa…',
    'cancel' => 'Batal',
    'apply' => 'Terapkan',
    'sound_off' => 'Nyalakan suara latar',
    'sound_on' => 'Matikan suara latar',
    'lang_trigger' => 'Pilih bahasa',
    'close' => 'Tutup',
    'no_results' => 'Bahasa tidak ditemukan',
    'contribute' => 'Bagikan',
];
