<?php

return [
    'opposition_index' => 'Penolakan',
    'opposition_label' => 'Mengapa masyarakat internasional menolak',
    'opposition_title' => 'Penolakan didasarkan pada',
    'opposition_title_accent' => 'hukum, bukan emosi',
    'opposition_lead' => 'Segera setelah Garis Sembilan Titik diajukan ke Perserikatan Bangsa-Bangsa pada tahun 2009, banyak negara dan kalangan akademik menyatakan penolakan — dengan argumen hukum yang spesifik.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mei',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonesia',
    'opposition_voice1_body' => 'Hanya satu hari setelah Tiongkok menyerahkan peta Garis Sembilan Titik kepada Sekretaris Jenderal Perserikatan Bangsa-Bangsa (7/5/2009), negara-negara ini secara berturut-turut mengirim nota protes, menolak klaim tersebut.',
    'opposition_voice1_chip1' => 'Nota protes',
    'opposition_voice1_chip2' => 'Tidak sesuai dengan UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipina',
    'opposition_voice2_body' => 'Mengirim surat diplomatik ke Perserikatan Bangsa-Bangsa, menyatakan klaim Tiongkok di Laut Cina Selatan "tidak memiliki dasar menurut hukum internasional" — menjadi dasar bagi gugatan ke Pengadilan Arbitrase kemudian.',
    'opposition_voice2_chip1' => 'Dasar gugatan PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Kementerian Luar Negeri Amerika Serikat — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analisis menunjukkan: peta-peta dari berbagai tahun tidak konsisten mengenai posisi garis putus-putus; garis tersebut meluas ke daratan alih-alih menggunakan garis tengah; banyak fitur tidak memenuhi syarat sebagai “pulau” untuk memiliki EEZ.',
    'opposition_voice3_chip1' => 'Tidak memenuhi syarat hukum',
    'opposition_voice3_chip2' => 'Analisis resmi',
    'opposition_voice4_year' => 'Akademik',
    'opposition_voice4_title' => '“Perairan historis” sudah usang',
    'opposition_voice4_body' => 'Konsep ini hanya berlaku untuk teluk atau perairan tertutup yang dekat pantai — tidak dapat mencakup seluruh wilayah laut lepas yang luas. Pada tahun 2003, Taiwan sendiri juga menolak kebijakan “perairan historis” yang pernah disebutkan pada tahun 1993.',
    'opposition_voice4_chip1' => 'Bahkan akademisi Tiongkok pun tidak sepakat',
];
