<?php

return [
    'sovereignty_index' => 'Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_label' => 'Kesimpulan yang tak terelakkan',
    'sovereignty_title' => 'Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_title_accent' => 'adalah milik Vietnam',
    'sovereignty_lead' => 'Halaman ini menjelaskan Garis Sembilan Titik. Bagian kesimpulan menjawab pertanyaan berikutnya: siapa yang berdaulat atas dua kepulauan, Kepulauan Paracel dan Kepulauan Spratly? Menurut sejarah pengelolaan dan hukum internasional, jawabannya konsisten adalah Vietnam.',
    'sovereignty_thesis_label' => 'Gagasan utama terintegrasi',
    'sovereignty_thesis_lock1' => 'Tidak ada koordinat hukum',
    'sovereignty_thesis_lock2' => 'Putusan PCA 2016 menolak',
    'sovereignty_thesis_lock3' => 'Peta kuno tidak mencakup',
    'sovereignty_thesis_body' => 'Setelah enam bagian di atas, tiga hal menjadi jelas: Garis Sembilan Titik digambar tangan, tanpa koordinat hukum; Pengadilan Arbitrase tahun 2016 menolak klaim tersebut; peta kuno milik Tiongkok sendiri tidak mencakup Laut Cina Selatan. Kedaulatan Vietnam tidak bertumpu pada slogan, melainkan pada fakta bahwa negara Vietnam — sejak masa para penguasa Nguyễn — telah mengelola secara damai dan berkelanjutan ketika kedua kepulauan itu masih merupakan tanah tak bertuan.',
    'sovereignty_spine_caption' => 'Tonggak pengelolaan berkelanjutan',
    'sovereignty_spine_title' => 'Satu linimasa, tanpa terputus',
    'sovereignty_spine_range' => 'Abad XVII → kini',
    'sovereignty_chron1_year' => 'Abad XVII',
    'sovereignty_chron1_title' => 'Pasukan Hoàng Sa',
    'sovereignty_chron1_body' => 'Para penguasa Nguyễn mengirim Pasukan Hoàng Sa untuk melakukan survei, mengukur alur pelayaran, dan mengeksploitasi di laut — menjalankan kewenangan pengelolaan secara nyata.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Raja Gia Long',
    'sovereignty_chron2_body' => 'Mengibarkan bendera di Kepulauan Paracel, menegaskan kedaulatan Vietnam di hadapan dunia pada masa itu.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Raja Minh Mạng',
    'sovereignty_chron3_body' => 'Melakukan pengukuran, mendirikan prasasti, dan mencatat kepulauan itu pada peta resmi istana.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Penerusan berkelanjutan',
    'sovereignty_chron4_body' => 'Prancis mengakui dan melanjutkan pengelolaan; memasukkan Kepulauan Paracel ke Provinsi Thừa Thiên — menjadi landasan bagi Negara Vietnam saat ini.',
    'sovereignty_chron5_year' => 'Kini',
    'sovereignty_chron5_title' => 'Hukum dan praktik',
    'sovereignty_chron5_body' => 'Vietnam mengelola berdasarkan UNCLOS, diplomasi, dan arsip; klaim Garis Sembilan Titik tidak dapat menggantikan bukti ini.',
    'sovereignty_balance_label' => 'Keseimbangan bukti',
    'sovereignty_balance_medallion_title' => 'Perbandingan dua sisi',
    'sovereignty_vn_tag' => 'Pihak Vietnam',
    'sovereignty_vn_title' => 'Kedaulatan ditegakkan melalui tindakan',
    'sovereignty_vn_body' => 'Penguasaan efektif ketika tanah masih tak bertuan, lalu dikelola secara terbuka selama berabad-abad — dengan dokumen kekaisaran, prasasti, peta, dan arsip administrasi. Cara ini sejalan dengan UNCLOS dan praktik internasional.',
    'sovereignty_dash_tag' => 'Pihak Garis Sembilan Titik',
    'sovereignty_dash_title' => 'Klaim tidak dapat menutupi bukti',
    'sovereignty_dash_body' => 'Sebuah garis yang digambar pada tahun 1948, tanpa koordinat, telah ditolak oleh PCA 2016 dan bertentangan dengan UNCLOS — seperti yang telah dijelaskan dalam bagian 03 sampai 06. Itulah sebabnya kesimpulan tentang kedaulatan atas dua kepulauan tidak dapat didasarkan pada Garis Sembilan Titik.',
    'sovereignty_seal_quote' => 'Vietnam menyelesaikan sengketa dengan <strong>langkah-langkah damai</strong>, berdasarkan hukum internasional — khususnya UNCLOS 1982 — menuju Laut Cina Selatan yang damai, kooperatif, dan berkembang.',
    'sovereignty_seal_cite' => 'Sikap Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyek utama dalam ekosistem yang sama',
    'sovereignty_next_title' => 'Baca bukti lengkap tentang Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_next_body' => 'Berkas rinci — dokumen, peta, linimasa, dan argumen hukum — tersedia di situs <strong>paracelislands.net</strong>, yang menyajikan topik kedaulatan atas dua kepulauan secara menyeluruh. Halaman yang Anda baca ini hanya menghubungkan logika dari Garis Sembilan Titik menuju kesimpulan tersebut.',
    'sovereignty_next_cta' => 'Buka paracelislands.net',
];
