<?php

return [
    'sovereignty_index' => 'Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_label' => 'Kesimpulan yang tak terelakkan',
    'sovereignty_title' => 'Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_title_accent' => 'milik Vietnam',
    'sovereignty_lead' => 'Halaman ini menjelaskan Garis Sembilan Titik. Bagian kesimpulan menjawab pertanyaan berikutnya: siapa yang memiliki kedaulatan atas dua kepulauan, Kepulauan Paracel dan Kepulauan Spratly? Menurut sejarah pengelolaan dan hukum internasional, jawabannya secara konsisten adalah Vietnam.',
    'sovereignty_thesis_label' => 'Argumen terpadu',
    'sovereignty_thesis_lock1' => 'Tidak ada koordinat hukum',
    'sovereignty_thesis_lock2' => 'PCA 2016 menolak',
    'sovereignty_thesis_lock3' => 'Peta kuno tidak mencakup',
    'sovereignty_thesis_body' => 'Setelah enam bagian di atas, tiga hal menjadi jelas: Garis Sembilan Titik digambar tangan, tanpa koordinat hukum; Pengadilan Arbitrase tahun 2016 menolak klaim tersebut; peta-peta kuno milik Tiongkok sendiri tidak mencakup Laut China Selatan. Kedaulatan Vietnam tidak bertumpu pada slogan, melainkan pada fakta bahwa negara Vietnam — sejak masa para penguasa Nguyễn — telah mengelola secara damai dan berkesinambungan ketika dua kepulauan itu masih merupakan wilayah tanpa pemilik.',
    'sovereignty_spine_caption' => 'Penanda pengelolaan yang berkelanjutan',
    'sovereignty_spine_title' => 'Satu garis waktu, tanpa jeda',
    'sovereignty_spine_range' => 'Abad ke-17 → kini',
    'sovereignty_chron1_year' => 'Abad XVII',
    'sovereignty_chron1_title' => 'Skuad Paracel',
    'sovereignty_chron1_body' => 'Para penguasa Nguyễn mengirim Skuad Paracel untuk melakukan survei, mengukur rute pelayaran, dan memanfaatkan laut — menjalankan kewenangan pengelolaan secara nyata.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Raja Gia Long',
    'sovereignty_chron2_body' => 'Mengibarkan bendera di Kepulauan Paracel, menegaskan kedaulatan Vietnam di hadapan dunia pada masa itu.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Raja Minh Mạng',
    'sovereignty_chron3_body' => 'Melakukan pengukuran, mendirikan prasasti, dan mencatat kepulauan tersebut pada peta resmi istana.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Suksesi yang berkelanjutan',
    'sovereignty_chron4_body' => 'Prancis mengakui dan melanjutkan pengelolaan; Kepulauan Paracel digabungkan ke Provinsi Thừa Thiên — menjadi dasar bagi Negara Vietnam saat ini.',
    'sovereignty_chron5_year' => 'Kini',
    'sovereignty_chron5_title' => 'Hukum dan praktik',
    'sovereignty_chron5_body' => 'Vietnam mengelola berdasarkan UNCLOS, diplomasi, dan arsip; klaim Garis Sembilan Titik tidak dapat menggantikan bukti ini.',
    'sovereignty_balance_label' => 'Keseimbangan bukti',
    'sovereignty_balance_medallion_title' => 'Perbandingan dua pihak',
    'sovereignty_vn_tag' => 'Pihak Vietnam',
    'sovereignty_vn_title' => 'Kedaulatan ditegakkan melalui tindakan',
    'sovereignty_vn_body' => 'Pendudukan efektif ketika wilayah masih tanpa pemilik, lalu dikelola secara terbuka selama berabad-abad — didukung dekret kekaisaran, prasasti, peta, dan arsip administratif. Cara ini selaras dengan UNCLOS dan praktik internasional.',
    'sovereignty_dash_tag' => 'Pihak Garis Sembilan Titik',
    'sovereignty_dash_title' => 'Klaim tidak dapat menutupi bukti',
    'sovereignty_dash_body' => 'Sebuah garis yang digambar pada tahun 1948, tanpa koordinat, telah ditolak oleh PCA 2016 dan bertentangan dengan UNCLOS — sebagaimana telah dipaparkan pada bagian 03 hingga 06. Itulah sebabnya kesimpulan tentang kedaulatan atas dua kepulauan itu tidak dapat didasarkan pada Garis Sembilan Titik.',
    'sovereignty_seal_quote' => 'Vietnam menyelesaikan sengketa dengan <strong>cara damai</strong>, berdasarkan hukum internasional — khususnya UNCLOS 1982 — dengan tujuan mewujudkan Laut China Selatan yang damai, bekerja sama, dan berkembang.',
    'sovereignty_seal_cite' => 'Sikap Vietnam · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proyek utama dalam ekosistem yang sama',
    'sovereignty_next_title' => 'Baca lengkap bukti tentang Kepulauan Paracel – Kepulauan Spratly',
    'sovereignty_next_body' => 'Berkas rinci — dokumen, peta, garis waktu, dan argumen hukum — tersedia di situs <strong>paracelislands.net</strong>, yang menyajikan topik kedaulatan atas dua kepulauan secara menyeluruh. Halaman yang Anda baca ini hanya menghubungkan logika dari Garis Sembilan Titik menuju kesimpulan tersebut.',
    'sovereignty_next_cta' => 'Buka paracelislands.net',
];
