<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Putusan internasional',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'tiga kata “Tidak”',
    'verdict_lead' => 'Pada 12/7/2016, Pengadilan Arbitrase Permanen (PCA) di Den Haag — dibentuk berdasarkan Lampiran VII UNCLOS, dalam perkara Filipina melawan Tiongkok — mengeluarkan putusan yang menolak klaim Garis Sembilan Titik. <em>Klik setiap kartu untuk membaca teks lengkapnya.</em>',
    'verdict_card1_khong' => 'TIDAK',
    'verdict_card1_title' => 'hak historis',
    'verdict_card1_short' => 'Tidak ada dasar hukum bagi Tiongkok untuk mengemukakan hak historis atas sumber daya di perairan yang berada dalam Garis Sembilan Titik.',
    'verdict_card1_quote' => '“Tidak ada dasar hukum bagi Tiongkok untuk mengemukakan hak historis atas sumber daya yang berada di perairan dalam Garis Sembilan Titik.”',
    'verdict_card1_more' => '+ Baca putusan',
    'verdict_card2_khong' => 'TIDAK',
    'verdict_card2_title' => 'entitas pembentuk ZEE',
    'verdict_card2_short' => 'Tidak ada entitas mana pun di Kepulauan Spratly yang memenuhi syarat untuk membentuk zona ekonomi eksklusif bagi Tiongkok — termasuk Pulau Itu Aba.',
    'verdict_card2_quote' => '“Tidak ada satu pun entitas di Kepulauan Spratly yang mampu membentuk zona ekonomi eksklusif.”',
    'verdict_card2_more' => '+ Baca putusan',
    'verdict_card3_khong' => 'TIDAK',
    'verdict_card3_title' => 'tindakan yang sah',
    'verdict_card3_short' => 'Tiongkok melanggar hak berdaulat Vietnam, menghambat penangkapan ikan, dan merusak lingkungan laut.',
    'verdict_card3_quote' => '“Tiongkok telah melanggar hak berdaulat Filipina, mengintervensi kegiatan penangkapan ikan di Scarborough Shoal, dan menimbulkan kerusakan serius pada lingkungan terumbu karang.”',
    'verdict_card3_more' => '+ Baca putusan',
    'verdict_extra1' => 'Garis Sembilan Titik yang digambar sendiri oleh Tiongkok <strong>tidak sesuai</strong> dengan UNCLOS 1982.',
    'verdict_extra2' => 'Tiongkok menyebabkan kerusakan ekosistem Kepulauan Spratly melalui eksploitasi berlebihan dan pembangunan pulau buatan.',
    'verdict_extra3' => 'Tindakan Tiongkok meningkatkan risiko konflik dengan Filipina.',
    'verdict_extra4' => 'Pulau Itu Aba (yang dikendalikan Taiwan) juga tidak dapat membentuk ZEE.',
    'verdict_subtitle' => 'Mengapa ini bertentangan dengan UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 secara jelas membagi wilayah laut berdasarkan garis pangkal negara pantai. Klaim Garis Sembilan Titik melampaui kerangka ini sehingga tidak dapat disejajarkan.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Laut teritorial (mil laut)',
    'verdict_zone1_body' => 'Wilayah laut negara yang berdaulat, dihitung dari garis pangkal.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona ekonomi eksklusif',
    'verdict_zone2_body' => 'ZEE — negara pantai memiliki hak berdaulat atas sumber daya dalam wilayah ini.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Landas kontinen (maksimum, mil laut)',
    'verdict_zone3_body' => 'Hak atas sumber daya dasar laut, sesuai kondisi geologi yang ditetapkan.',
    'verdict_foot' => 'Dalam kerangka ini, “hak historis” yang mencakup seluruh laut lepas — seperti yang diisyaratkan oleh Garis Sembilan Titik — <em>telah digantikan</em> oleh rezim hukum UNCLOS yang juga menjadi pihak bagi Tiongkok.',
];
