<?php

return [
    'witnesses_index' => 'Peta Kuno',
    'witnesses_label' => 'Peta Kuno Tiongkok',
    'witnesses_title' => 'Batas paling selatan hanya sampai',
    'witnesses_title_accent' => 'Pulau Hainan',
    'witnesses_lead' => 'Peta-peta kuno yang digambar oleh penulis Tiongkok — disusun secara kronologis — semuanya menunjukkan <em>Pulau Hainan sebagai titik paling selatan</em> Tiongkok, tanpa Kepulauan Paracel maupun Kepulauan Spratly. Materi disusun berdasarkan <em>Kedaulatan negara Vietnam di dua kepulauan Kepulauan Paracel dan Kepulauan Spratly</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Perbesar dengan kaca pembesar',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— titik paling selatan wilayah —',
    'witnesses_map1_svg_era' => 'Dinasti Song · 1136',
    'witnesses_map1_title' => 'Peta Dinasti Song, 1136',
    'witnesses_map1_body' => 'Wilayah Tiongkok berhenti di pulau Hainan — Kepulauan Paracel dan Kepulauan Spratly berada di luar wilayahnya.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'batas d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Peta d\'Anville, 1735',
    'witnesses_map2_body' => 'Digambar oleh J.-B. B. d\'Anville; salinan tahun 1740 pernah dihadiahkan oleh Kanselir Jerman kepada pemimpin Tiongkok. Wilayah Dinasti Qing berhenti di Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"titik paling selatan Tiongkok"',
    'witnesses_map3_svg_era' => 'Huangchao zhixian ditu · 1904',
    'witnesses_map3_title' => 'Huangchao zhixian ditu',
    'witnesses_map3_body' => 'Dicetak oleh Dinasti Qing — dengan jelas menyebut titik paling selatan wilayah Tiongkok adalah pulau Hainan.',
    'witnesses_quote' => 'Peta Tiongkok yang pernah diterbitkan sendiri tidak menggambar Kepulauan Paracel — Kepulauan Spratly sebagai wilayah mereka.',
    'witnesses_timeline_aria' => 'Linimasa peta kuno Tiongkok',
    'witnesses_year_aria' => 'Tahun',
    'lightbox_aria' => 'Lihat gambar diperbesar',
    'lightbox_close' => 'Tutup',
    'lightbox_prev' => 'Gambar sebelumnya',
    'lightbox_next' => 'Gambar berikutnya',
];
