<?php

return [
    'footer_index' => 'Bibliotecă',
    'footer_crest_eyebrow' => 'Încheierea bibliotecii adevărului',
    'footer_crest_quote' => '„Pacea în Marea Chinei de Sud se construiește pe temelia <b>dreptului internațional</b>.”',
    'footer_crest_sub' => 'Fără ură · Doar adevăr',
    'footer_nav_aria' => 'Acțiuni la sfârșitul paginii',
    'footer_btn_top' => 'Înapoi sus',
    'footer_btn_verdict' => 'Hotărârea PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net/vi',
    'footer_brand_gold' => 'Susținerea revendicărilor Liniei celor nouă liniuțe',
    'footer_brand_eyebrow' => 'Pagină tematică · Suveranitatea Vietnamului',
    'footer_brand_body' => 'Explicarea Liniei celor nouă liniuțe prin adevăr obiectiv, drept internațional, hotărârea PCA 2016 și documente istorice — completând paginile aprofundate despre suveranitatea asupra celor două arhipelaguri <strong>"Insulele Paracel și Insulele Spratly"</strong>. Respinge revendicările lipsite de temei ale Chinei prin istorie și dovezi.',
    'footer_refs_title' => 'Surse de referință',
    'footer_ref1' => 'Hotărârea PCA, 12.07.2016',
    'footer_ref2' => 'UNCLOS 1982 — text integral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documente istorice și hărți vechi',
    'footer_toc_title' => 'Cuprinsul paginii',
    'footer_toc1' => 'Ce este Linia celor nouă liniuțe',
    'footer_toc2' => 'Origini',
    'footer_toc3' => 'De ce este controversată',
    'footer_toc4' => 'De ce se opune comunitatea internațională',
    'footer_toc5' => 'Martori tăcuți',
    'footer_toc6' => 'Hotărârea PCA 2016',
    'footer_toc7' => 'Insulele Paracel – Insulele Spratly',
    'footer_copy_eyebrow' => 'Proiect non-profit',
    'footer_copy_title' => 'Insulele Paracel – Insulele Spratly aparțin Vietnamului',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Pagină tematică despre Linia celor nouă liniuțe din ecosistemul de suveranitate al Vietnamului.',
    'footer_copy_body' => 'Explicarea revendicării Liniei celor nouă liniuțe prin <strong>adevăr obiectiv</strong>, <strong>drept internațional</strong>, hotărârea PCA 2016 și documente istorice — completând paginile aprofundate despre suveranitatea asupra arhipelagurilor Paracel și Spratly.',
    'footer_copy_ecosystem_aria' => 'Paginile aceluiași proiect',
    'footer_copy_ecosystem_label' => 'În același ecosistem',
    'footer_copy_disclaimer' => 'Conținutul are scop educativ și de conștientizare; nu înlocuiește poziția oficială a statului Vietnam.',
    'footer_copy' => '<strong>© :year Linia celor nouă liniuțe</strong> — O parte a proiectului non-profit <strong>Insulele Paracel – Insulele Spratly aparțin Vietnamului</strong> din sistemul: <a href="https://paracelislands.net/vi" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/vi" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/vi" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/vi" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/vi" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Angajamentul privind conținutul paginii',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Hotărârea PCA 2016',
    'footer_chip3' => 'Dovezi istorice',
    'footer_chip4' => 'Hărți vechi',
    'footer_chip5' => 'Adevăr obiectiv',
    'footer_chip6' => 'Pacea în Marea Chinei de Sud',
];
