<?php

return [
    'footer_index' => 'Bibliotecă',
    'footer_crest_eyebrow' => 'Încheierea bibliotecii adevărului',
    'footer_crest_quote' => '„Pacea în Marea Chinei de Sud se construiește pe temelia <b>dreptului internațional</b>.”',
    'footer_crest_sub' => 'Fără ură · Doar adevăr',
    'footer_nav_aria' => 'Acțiuni la sfârșitul paginii',
    'footer_btn_top' => 'Sus de tot',
    'footer_btn_verdict' => 'Hotărârea PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Linia celor nouă liniuțe',
    'footer_brand_body' => 'Un site explicativ bazat pe adevăr obiectiv, drept internațional și documente istorice — respingând pretenția Linia celor nouă liniuțe prin dovezi, nu prin sloganuri.',
    'footer_refs_title' => 'Surse de referință',
    'footer_ref1' => 'Hotărârea PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — text integral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documente istorice și hărți vechi',
    'footer_toc_title' => 'Cuprinsul paginii',
    'footer_toc1' => 'Ce este Linia celor nouă liniuțe',
    'footer_toc2' => 'Originea',
    'footer_toc3' => 'De ce stârnește controverse',
    'footer_toc4' => 'De ce o respinge comunitatea internațională',
    'footer_toc5' => 'Martori tăcuți',
    'footer_toc6' => 'Hotărârea PCA 2016',
    'footer_toc7' => 'Insulele Paracel – Insulele Spratly',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — Adevărul obiectiv despre Marea Chinei de Sud.<br>Ecosistemul: <a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => 'Fără coordonate',
];
