<?php

return [
    'footer_index' => 'Bibliotecă',
    'footer_crest_eyebrow' => 'Încheierea bibliotecii adevărului',
    'footer_crest_quote' => '„Pacea în Marea Chinei de Sud se construiește pe temelia <b>Dreptului internațional</b>.”',
    'footer_crest_sub' => 'Fără ură · Doar adevăr',
    'footer_nav_aria' => 'Acțiuni în subsol',
    'footer_btn_top' => 'Înapoi sus',
    'footer_btn_verdict' => 'Hotărârea PCA 2016',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => 'Afirmarea Liniei celor nouă liniuțe',
    'footer_brand_eyebrow' => 'Pagină tematică · Suveranitatea Vietnam',
    'footer_brand_body' => 'Explică Linia celor nouă liniuțe prin adevăr obiectiv, drept internațional, hotărârea PCA din 2016 și documente istorice — ca o completare la paginile detaliate despre suveranitatea celor două arhipelaguri <strong>"Insulele Paracel și Insulele Spratly"</strong>. Respinge pretențiile ilogice ale China prin istorie și dovezi.',
    'footer_refs_title' => 'Surse de referință',
    'footer_ref1' => 'Hotărârea PCA, 12/07/2016',
    'footer_ref2' => 'UNCLOS 1982 — text integral',
    'footer_ref3' => 'Limits in the Seas №143 (US DoS)',
    'footer_ref4' => 'Documente istorice și hărți vechi',
    'footer_toc_title' => 'Cuprinsul paginii',
    'footer_toc1' => 'Ce este Linia celor nouă liniuțe',
    'footer_toc2' => 'Originea',
    'footer_toc3' => 'De ce este controversată',
    'footer_toc4' => 'De ce se opune comunitatea internațională',
    'footer_toc5' => 'Martori tăcuți',
    'footer_toc6' => 'Hotărârea PCA 2016',
    'footer_toc7' => 'Insulele Paracel – Insulele Spratly',
    'footer_copy_eyebrow' => 'Proiect non-profit',
    'footer_copy_title' => 'Insulele Paracel – Insulele Spratly aparțin Vietnam',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — Pagină tematică despre Linia celor nouă liniuțe în ecosistemul suveranității Vietnam.',
    'footer_copy_body' => 'Explică pretenția Liniei celor nouă liniuțe prin <strong>adevăr obiectiv</strong>, <strong>drept internațional</strong>, hotărârea PCA din 2016 și documente istorice — ca o completare la paginile detaliate despre suveranitatea arhipelagurilor Insulele Paracel și Insulele Spratly.',
    'footer_copy_ecosystem_aria' => 'Pagini din același proiect',
    'footer_copy_ecosystem_label' => 'Același ecosistem',
    'footer_copy_disclaimer' => 'Conținutul este destinat educării și creșterii gradului de conștientizare; nu înlocuiește poziția oficială a Statului Vietnam.',
    'footer_copy' => '<strong>© :year Linia celor nouă liniuțe</strong> — O parte a proiectului non-profit <strong>Insulele Paracel – Insulele Spratly aparțin Vietnam</strong> în cadrul sistemului: <a href="https://paracelislands.net/ro" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/ro" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/ro" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/ro" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/ro" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => 'Angajamentele conținutului paginii',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'Hotărârea PCA 2016',
    'footer_chip3' => 'Dovezi istorice',
    'footer_chip4' => 'Hărți vechi',
    'footer_chip5' => 'Adevăr obiectiv',
    'footer_chip6' => 'Pacea în Marea Chinei de Sud',
];
