<?php

return [
    'nav_logo_name' => 'Linia celor nouă liniuțe',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => 'Linia celor nouă liniuțe',
    'nav_rail_aria' => 'Navegare după secțiuni',
    'nav_rail_what' => 'Definiție',
    'nav_rail_origin' => 'Origine',
    'nav_rail_dispute' => 'Controverse',
    'nav_rail_opposition' => 'Opoziție',
    'nav_rail_witnesses' => 'Hărți antice',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => 'Insulele Paracel – Insulele Spratly',
    'nav_sound_off' => 'Pornește muzica de fundal',
    'nav_sound_on' => 'Oprește muzica de fundal',
    'nav_share' => 'Partajează',
    'dialog_title' => 'Limba de afișare',
    'language' => 'Limbă',
    'display_hint' => ':count limbi',
    'search_placeholder' => 'Caută o limbă…',
    'cancel' => 'Anulează',
    'apply' => 'Aplică',
    'sound_off' => 'Pornește sunetul de fundal',
    'sound_on' => 'Oprește sunetul de fundal',
    'lang_trigger' => 'Alege limba',
    'close' => 'Închide',
    'no_results' => 'Nu s-a găsit nicio limbă',
    'contribute' => 'Partajează',
];
