<?php

return [
    'opposition_index' => 'Opoziție',
    'opposition_label' => 'De ce se opune comunitatea internațională',
    'opposition_title' => 'Opoziția se bazează pe',
    'opposition_title_accent' => 'drept, nu pe emoții',
    'opposition_lead' => 'Imediat după ce Linia celor nouă liniuțe a fost prezentată la Națiunile Unite în 2009, numeroase state și mediul academic au formulat obiecții — pe baza unor argumente juridice concrete.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonezia',
    'opposition_voice1_body' => 'La numai o zi după ce China a înaintat harta Linia celor nouă liniuțe Secretarului General al Națiunilor Unite (7/5/2009), aceste țări au trimis succesiv note verbale de protest, respingând pretențiile.',
    'opposition_voice1_chip1' => 'Notă verbală de protest',
    'opposition_voice1_chip2' => 'Nu este conformă cu UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipine',
    'opposition_voice2_body' => 'A trimis o scrisoare diplomatică la Națiunile Unite, declarând că pretențiile China în Marea Chinei de Sud sunt „fără temei în dreptul internațional” — o premisă pentru cazul ulterior de la Tribunalul de Arbitraj.',
    'opposition_voice2_chip1' => 'Premisa cazului PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departamentul de Stat al SUA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiza arată: hărțile din diferiți ani sunt inconsistente în privința poziției liniei; linia intră pe uscat în loc să urmeze linia mediană; numeroase entități nu îndeplinesc criteriul de „insulă” pentru a avea ZEE.',
    'opposition_voice3_chip1' => 'Nu întrunește condițiile legale',
    'opposition_voice3_chip2' => 'Analiză oficială',
    'opposition_voice4_year' => 'Academic',
    'opposition_voice4_title' => '„Apele istorice” au devenit depășite',
    'opposition_voice4_body' => 'Acest concept se aplică doar golfurilor și apelor adăpostite din apropierea țărmului — nu poate acoperi o zonă vastă de mare deschisă. În 2003, chiar și Taiwan a respins politica de „ape istorice” menționată anterior în 1993.',
    'opposition_voice4_chip1' => 'Nici măcar cercetătorii din China nu sunt de acord',
];
