<?php

return [
    'opposition_index' => 'Opoziție',
    'opposition_label' => 'De ce se opune comunitatea internațională',
    'opposition_title' => 'Opoziția se bazează pe',
    'opposition_title_accent' => 'drept, nu pe emoții',
    'opposition_lead' => 'Imediat după ce Linia celor nouă liniuțe a fost prezentată Organizației Națiunilor Unite în 2009, numeroase state și cercetători au formulat obiecții — pe baza unor argumente juridice concrete.',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => 'Mai',
    'opposition_voice1_title' => 'Vietnam · Malaysia · Indonezia',
    'opposition_voice1_body' => 'La doar o zi după ce China a prezentat harta Liniei celor nouă liniuțe secretarului general al Organizației Națiunilor Unite (7/5/2009), aceste țări au trimis pe rând note verbale de protest, respingând pretențiile.',
    'opposition_voice1_chip1' => 'Notă verbală de protest',
    'opposition_voice1_chip2' => 'Nu este conformă cu UNCLOS 1982',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '05/04',
    'opposition_voice2_title' => 'Filipine',
    'opposition_voice2_body' => 'A trimis o scrisoare diplomatică la Organizația Națiunilor Unite, declarând că pretențiile Chinei în Marea Chinei de Sud sunt „fără temei în dreptul internațional” — premisa pentru cazul ulterior depus la Tribunalul de Arbitraj.',
    'opposition_voice2_chip1' => 'Premisa cazului PCA',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '05/12',
    'opposition_voice3_title' => 'Departamentul de Stat al SUA — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => 'Analiza a arătat: hărțile din diferiți ani sunt inconsecvente în privința poziției liniei; linia pătrunde în teritoriul continental în loc să urmeze linia mediană; multe entități nu îndeplinesc criteriile de „insulă” pentru a avea o ZEE.',
    'opposition_voice3_chip1' => 'Nu îndeplinește condițiile juridice',
    'opposition_voice3_chip2' => 'Analiză oficială',
    'opposition_voice4_year' => 'Academic',
    'opposition_voice4_title' => '„Apele istorice” sunt depășite',
    'opposition_voice4_body' => 'Acest concept se aplică doar golfurilor și apelor de coastă apropiate de țărm — nu poate acoperi o vastă zonă de mare deschisă. În 2003, chiar și Taiwan a respins politica „apelor istorice” menționată anterior în 1993.',
    'opposition_voice4_chip1' => 'Nici măcar cercetătorii din China nu sunt de acord',
];
