<?php

return [
    'sovereignty_index' => 'Hoàng Sa – Trường Sa',
    'sovereignty_label' => 'Concluzia inevitabilă',
    'sovereignty_title' => 'Insulele Paracel – Insulele Spratly',
    'sovereignty_title_accent' => 'aparțin Vietnamului',
    'sovereignty_lead' => 'Această pagină explică Linia celor nouă liniuțe. Secțiunea de concluzie răspunde la întrebarea următoare: cine are suveranitatea asupra celor două arhipelaguri, Insulele Paracel și Insulele Spratly? Potrivit istoricului administrării și dreptului internațional, răspunsul consecvent este Vietnam.',
    'sovereignty_thesis_label' => 'Teză sintetizată',
    'sovereignty_thesis_lock1' => 'Fără coordonate juridice',
    'sovereignty_thesis_lock2' => 'PCA 2016 a respins',
    'sovereignty_thesis_lock3' => 'Hărțile vechi nu le includ',
    'sovereignty_thesis_body' => 'După cele șase secțiuni de mai sus, trei lucruri sunt clare: Linia celor nouă liniuțe este desenată de mână, fără coordonate juridice; Curtea de Arbitraj din 2016 a respins revendicarea; hărțile vechi ale Chinei însăși nu includ Marea Chinei de Sud. Suveranitatea Vietnamului nu se bazează pe sloganuri, ci pe faptul că statul vietnamez — încă din vremea domnilor Nguyễn — a administrat pașnic și continuu aceste două arhipelaguri când ele erau încă teritoriu fără stăpân.',
    'sovereignty_spine_caption' => 'Reperele administrării continue',
    'sovereignty_spine_title' => 'O cronologie, fără întrerupere',
    'sovereignty_spine_range' => 'Secolul al XVII-lea → prezent',
    'sovereignty_chron1_year' => 'sec. XVII',
    'sovereignty_chron1_title' => 'Echipa Hoàng Sa',
    'sovereignty_chron1_body' => 'Domnii Nguyễn au trimis echipa Hoàng Sa să investigheze, să măsoare rutele maritime și să exploateze pe mare — exercitând o administrare efectivă.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Regele Gia Long',
    'sovereignty_chron2_body' => 'A arborat steagul pe arhipelagul Hoàng Sa, afirmând suveranitatea Vietnamului în fața lumii de atunci.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Regele Minh Mạng',
    'sovereignty_chron3_body' => 'A ordonat măsurători, a ridicat stâlpi/inscripții și a consemnat arhipelagul pe hărțile oficiale ale curții.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Moștenire continuă',
    'sovereignty_chron4_body' => 'Franța a recunoscut și a continuat administrarea; a anexat Hoàng Sa la provincia Thừa Thiên — o bază pentru statul vietnamez de astăzi.',
    'sovereignty_chron5_year' => 'Astăzi',
    'sovereignty_chron5_title' => 'Lege și practică',
    'sovereignty_chron5_body' => 'Vietnamul administrează în conformitate cu UNCLOS, diplomația și arhivele; revendicarea Liniei celor nouă liniuțe nu poate înlocui aceste dovezi.',
    'sovereignty_balance_label' => 'Echilibrul probelor',
    'sovereignty_balance_medallion_title' => 'Confruntarea celor două părți',
    'sovereignty_vn_tag' => 'Partea Vietnamului',
    'sovereignty_vn_title' => 'Suveranitate stabilită prin acte',
    'sovereignty_vn_body' => 'Ocupație efectivă atunci când terenul era fără stăpân, urmată de administrare publică, de-a lungul mai multor secole — cu edicte imperiale, stâlpi/inscripții, hărți și documente administrative. Această practică este conformă cu UNCLOS și cutumele internaționale.',
    'sovereignty_dash_tag' => 'Partea Liniei celor nouă liniuțe',
    'sovereignty_dash_title' => 'O revendicare nu poate compensa lipsa dovezilor',
    'sovereignty_dash_body' => 'O linie desenată în 1948, fără coordonate, a fost respinsă de PCA 2016 și contravine UNCLOS — așa cum au arătat secțiunile 03 până la 06. De aceea, concluzia privind suveranitatea asupra celor două arhipelaguri nu poate fi întemeiată pe Linia celor nouă liniuțe.',
    'sovereignty_seal_quote' => 'Vietnamul soluționează disputele prin <strong>mijloace pașnice</strong>, pe baza dreptului internațional — în special UNCLOS 1982 — urmărind o Mare Chinei de Sud pașnică, cooperantă și dezvoltatoare.',
    'sovereignty_seal_cite' => 'Poziția Vietnamului · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proiectul principal din același ecosistem',
    'sovereignty_next_title' => 'Citește integral probele despre Insulele Paracel – Insulele Spratly',
    'sovereignty_next_body' => 'Dosarul detaliat — documente, hărți, cronologie și argumente juridice — se află pe site-ul <strong>paracelislands.net</strong>, unde tema suveranității asupra celor două arhipelaguri este prezentată în ansamblu. Pagina pe care o citești conectează doar logica de la Linia celor nouă liniuțe la această concluzie.',
    'sovereignty_next_cta' => 'Deschide paracelislands.net',
];
