<?php

return [
    'sovereignty_index' => 'Hoàng Sa – Trường Sa',
    'sovereignty_label' => 'Concluzie inevitabilă',
    'sovereignty_title' => 'Hoàng Sa – Trường Sa',
    'sovereignty_title_accent' => 'sunt ale Vietnamului',
    'sovereignty_lead' => 'Această pagină explică Linia celor nouă liniuțe. Secțiunea de concluzie răspunde la întrebarea următoare: cine are suveranitatea asupra celor două arhipelaguri Hoàng Sa și Trường Sa? Conform istoriei administrării și dreptului internațional, răspunsul consecvent este Vietnam.',
    'sovereignty_thesis_label' => 'Argument sintetic',
    'sovereignty_thesis_lock1' => 'Fără coordonate juridice',
    'sovereignty_thesis_lock2' => 'PCA 2016 respinge',
    'sovereignty_thesis_lock3' => 'Hărțile vechi nu le cuprind',
    'sovereignty_thesis_body' => 'După cele șase secțiuni de mai sus, trei puncte sunt clare: Linia celor nouă liniuțe este trasată de mână și nu are coordonate juridice; Curtea de Arbitraj din 2016 a respins pretenția; hărțile vechi ale Chinei însăși nu cuprind Marea Chinei de Sud. Suveranitatea Vietnamului nu se bazează pe sloganuri, ci pe faptul că statul vietnamez — încă din vremea domnilor Nguyễn — a administrat în mod pașnic și continuu când cele două arhipelaguri erau încă teritoriu fără stăpân.',
    'sovereignty_spine_caption' => 'Repere ale administrării continue',
    'sovereignty_spine_title' => 'O cronologie, fără întreruperi',
    'sovereignty_spine_range' => 'Secolul al XVII-lea → prezent',
    'sovereignty_chron1_year' => 'sec. XVII',
    'sovereignty_chron1_title' => 'Echipa Hoàng Sa',
    'sovereignty_chron1_body' => 'Domnii Nguyễn au trimis echipa Hoàng Sa pentru a face recunoașteri, a măsura rutele maritime și a desfășura activități pe mare — exercitând administrarea efectivă.',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => 'Regele Gia Long',
    'sovereignty_chron2_body' => 'A arborat steagul pe arhipelagul Hoàng Sa, reafirmând suveranitatea Vietnamului în fața lumii contemporane.',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => 'Regele Minh Mạng',
    'sovereignty_chron3_body' => 'A ordonat măsurători, a ridicat stâlpi de hotar și a consemnat arhipelagul pe hărțile oficiale ale curții.',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => 'Continuitate succesorala',
    'sovereignty_chron4_body' => 'Franța a recunoscut și a continuat administrarea; a anexat Hoàng Sa la provincia Thừa Thiên — bază pentru actualul Stat al Vietnamului.',
    'sovereignty_chron5_year' => 'Prezent',
    'sovereignty_chron5_title' => 'Drept și practică',
    'sovereignty_chron5_body' => 'Vietnam administrează conform UNCLOS, diplomației și dosarelor de arhivă; pretenția Liniei celor nouă liniuțe nu poate înlocui aceste dovezi.',
    'sovereignty_balance_label' => 'Echilibrul probelor',
    'sovereignty_balance_medallion_title' => 'Comparație între cele două părți',
    'sovereignty_vn_tag' => 'Partea Vietnamului',
    'sovereignty_vn_title' => 'Suveranitate stabilită prin fapte',
    'sovereignty_vn_body' => 'Ocupație efectivă atunci când teritoriul era fără stăpân, urmată de administrare publică timp de secole — cu documente imperiale, stâlpi, hărți și arhive administrative. Această practică este în concordanță cu UNCLOS și cu uzanțele internaționale.',
    'sovereignty_dash_tag' => 'Partea Liniei celor nouă liniuțe',
    'sovereignty_dash_title' => 'O pretenție nu poate compensa dovezile',
    'sovereignty_dash_body' => 'O linie desenată în 1948, fără coordonate, a fost respinsă de PCA 2016 și contravine UNCLOS — așa cum au arătat secțiunile 03 până la 06. De aceea, concluzia privind suveranitatea asupra celor două arhipelaguri nu poate fi bazată pe Linia celor nouă liniuțe.',
    'sovereignty_seal_quote' => 'Vietnamul soluționează disputele prin <strong>mijloace pașnice</strong>, pe baza dreptului internațional — în special UNCLOS 1982 — urmărind o Mare a Chinei de Sud pașnică, cooperantă și în dezvoltare.',
    'sovereignty_seal_cite' => 'Poziția Vietnamului · UNCLOS 1982',
    'sovereignty_next_eyebrow' => 'Proiectul principal din același ecosistem',
    'sovereignty_next_title' => 'Citește integral dovezile despre Hoàng Sa – Trường Sa',
    'sovereignty_next_body' => 'Dosarul detaliat — documente, hărți, cronologie și argumente juridice — se află pe site-ul <strong>paracelislands.net</strong>, unde este prezentat în mod complet subiectul suveranității asupra celor două arhipelaguri. Pagina pe care o citești conectează doar logic Linia celor nouă liniuțe la această concluzie.',
    'sovereignty_next_cta' => 'Deschide paracelislands.net',
];
