<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => 'Hotărâre internațională',
    'verdict_title' => 'PCA 2016:',
    'verdict_title_accent' => 'trei „Nu”',
    'verdict_lead' => 'La 12/7/2016, Curtea Permanentă de Arbitraj (PCA) de la Haga — constituită în temeiul Anexei VII la UNCLOS, în cauza Philippines împotriva China — a pronunțat o hotărâre care a respins pretenția privind Linia celor nouă liniuțe. <em>Apăsați pe fiecare card pentru a citi textul integral.</em>',
    'verdict_card1_khong' => 'NU',
    'verdict_card1_title' => 'drepturi istorice',
    'verdict_card1_short' => 'Nu există bază juridică pentru ca China să invoce drepturi istorice asupra resurselor din apele aflate în interiorul Liniei celor nouă liniuțe.',
    'verdict_card1_quote' => '„Nu există temei juridic pentru ca China să invoce drepturi istorice asupra resurselor aflate în apele din interiorul Liniei celor nouă liniuțe.”',
    'verdict_card1_more' => '+ Citiți hotărârea',
    'verdict_card2_khong' => 'NU',
    'verdict_card2_title' => 'entități care generează ZEE',
    'verdict_card2_short' => 'Nicio entitate din Insulele Spratly nu îndeplinește condițiile pentru a crea o zonă economică exclusivă pentru China — inclusiv insula Ba Bình.',
    'verdict_card2_quote' => '„Nicio entitate din Insulele Spratly nu are capacitatea de a crea o zonă economică exclusivă.”',
    'verdict_card2_more' => '+ Citiți hotărârea',
    'verdict_card3_khong' => 'NU',
    'verdict_card3_title' => 'conduită legală',
    'verdict_card3_short' => 'China a încălcat drepturile suverane ale Philippines, a împiedicat pescuitul și a prejudiciat mediul marin.',
    'verdict_card3_quote' => '„China a încălcat drepturile suverane ale Philippines, a intervenit în activitățile de pescuit la reciful Scarborough și a provocat daune grave mediului recifal de corali.”',
    'verdict_card3_more' => '+ Citiți hotărârea',
    'verdict_extra1' => 'Linia celor nouă liniuțe trasată unilateral de China <strong>nu este compatibilă</strong> cu UNCLOS 1982.',
    'verdict_extra2' => 'China a cauzat prejudicii ecosistemului din Insulele Spratly prin supraexploatare și construirea de insule artificiale.',
    'verdict_extra3' => 'Acțiunile Chinei au sporit riscul de conflict cu Philippines.',
    'verdict_extra4' => 'Insula Ba Bình (aflată sub controlul Taiwanului) nu poate, de asemenea, să creeze o ZEE.',
    'verdict_subtitle' => 'De ce intră în conflict cu UNCLOS?',
    'verdict_subtitle_body' => 'UNCLOS 1982 delimitează în mod clar zonele maritime pe baza liniei de bază a statului riveran. Pretenția privind Linia celor nouă liniuțe depășește acest cadru, astfel încât nu poate fi reconciliată cu acesta.',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => 'Marea teritorială (mile marine)',
    'verdict_zone1_body' => 'Zona maritimă aflată sub suveranitatea statului, măsurată de la linia de bază.',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => 'Zona economică exclusivă',
    'verdict_zone2_body' => 'ZEE — statul riveran are drepturi suverane asupra resurselor din această zonă.',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => 'Platforma continentală (maxim, mile marine)',
    'verdict_zone3_body' => 'Drepturi asupra resurselor de pe fundul mării, conform condițiilor geologice stabilite.',
    'verdict_foot' => 'În acest cadru, „drepturile istorice” care ar acoperi o întreagă zonă de mare deschisă — așa cum sugerează Linia celor nouă liniuțe — <em>au fost înlocuite</em> de regimul juridic al UNCLOS, la care China este, de asemenea, parte.',
];
