<?php

return [
    'witnesses_index' => 'Hărți antice',
    'witnesses_label' => 'Hărți antice ale Chinei',
    'witnesses_title' => 'Se întinde doar până la extremitatea sudică',
    'witnesses_title_accent' => 'insula Hainan',
    'witnesses_lead' => 'Hărțile antice realizate de autori chinezi — ordonate cronologic — arată toate că <em>insula Hainan este extremitatea sudică</em> a Chinei, fără Insulele Paracel sau Insulele Spratly. Materiale compilate după <em>Suveranitatea națională a Vietnamului asupra celor două arhipelaguri Hoàng Sa și Trường Sa</em> (Trương Minh Dục, 2015).',
    'witnesses_hint' => '⌖ Folosește lupa',
    'witnesses_map1_svg_hainan' => 'Hainan 海南',
    'witnesses_map1_svg_south' => '— punctul cel mai sudic al teritoriului —',
    'witnesses_map1_svg_era' => 'Dinastia Song · 1136',
    'witnesses_map1_title' => 'Hartă din dinastia Song, 1136',
    'witnesses_map1_body' => 'Teritoriul Chinei se oprea la insula Hainan — Insulele Paracel și Insulele Spratly se află în afara granițelor sale.',
    'witnesses_map2_svg_hainan' => 'Hainan',
    'witnesses_map2_svg_south' => 'limita lui d\'Anville',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'Hartă d\'Anville, 1735',
    'witnesses_map2_body' => 'Desenată de J.-B. B. d\'Anville; copia din 1740 a fost oferită de prim-ministrul Germaniei liderilor chinezi. Teritoriul dinastiei Qing se oprea la Hainan.',
    'witnesses_map3_svg_hainan' => '海南 Hainan',
    'witnesses_map3_svg_south' => '"cel mai sudic punct al Chinei"',
    'witnesses_map3_svg_era' => 'Atlas geografic complet al prefecturilor sub administrație imperială · 1904',
    'witnesses_map3_title' => 'Atlas geografic complet al prefecturilor sub administrație imperială',
    'witnesses_map3_body' => 'Tipărit de dinastia Qing — indică în mod clar că punctul cel mai sudic al teritoriului Chinei este insula Hainan.',
    'witnesses_quote' => 'Chiar hărțile Chinei publicate odinioară nu au desenat Insulele Paracel — Insulele Spratly ca parte a teritoriului lor.',
    'witnesses_timeline_aria' => 'Cronologia hărților antice chineze',
    'witnesses_year_aria' => 'Datarea',
    'lightbox_aria' => 'Vizualizează imaginea mărită',
    'lightbox_close' => 'Închide',
    'lightbox_prev' => 'Imaginea anterioară',
    'lightbox_next' => 'Imaginea următoare',
];
