<?php

return [
    'footer_index' => '资料库',
    'footer_crest_eyebrow' => '真相资料库的结语',
    'footer_crest_quote' => '“南海的和平建立在<strong>国际法</strong>的基础之上。”',
    'footer_crest_sub' => '不仇恨 · 只有真相',
    'footer_nav_aria' => '页脚操作',
    'footer_btn_top' => '返回顶部',
    'footer_btn_verdict' => '2016年PCA裁决',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '断续线主张',
    'footer_brand_eyebrow' => '专题页 · 越南主权',
    'footer_brand_body' => '通过客观事实、国际法、2016年PCA裁决和历史资料解释断续线——作为关于两座群岛 <strong>"西沙群岛和南沙群岛"</strong> 主权深度页面的补充。以历史与证据驳斥中国的无理主张。',
    'footer_refs_title' => '参考资料',
    'footer_ref1' => 'PCA裁决，2016年7月12日',
    'footer_ref2' => '《1982年UNCLOS》— 全文',
    'footer_ref3' => '海洋界限第143号（美国国务院）',
    'footer_ref4' => '历史资料与古地图',
    'footer_toc_title' => '页面目录',
    'footer_toc1' => '什么是断续线',
    'footer_toc2' => '起源',
    'footer_toc3' => '为何引发争议',
    'footer_toc4' => '为何遭到国际反对',
    'footer_toc5' => '沉默的见证者',
    'footer_toc6' => '2016年PCA裁决',
    'footer_toc7' => '西沙群岛－南沙群岛',
    'footer_copy_eyebrow' => '非营利项目',
    'footer_copy_title' => '西沙群岛－南沙群岛属于越南',
    'footer_copy_lead' => '<strong>© :year ninedashline.net</strong> — 越南主权生态系统中有关断续线的专题页面。',
    'footer_copy_body' => '通过<strong>客观事实</strong>、<strong>国际法</strong>、2016年PCA裁决和历史资料解释断续线主张——作为关于西沙群岛和南沙群岛主权深度页面的补充。',
    'footer_copy_ecosystem_aria' => '同一项目的页面',
    'footer_copy_ecosystem_label' => '同一生态系统',
    'footer_copy_disclaimer' => '内容旨在教育与提升认知；不取代越南国家的官方立场。',
    'footer_copy' => '<strong>© :year 断续线</strong> — 非营利项目 <strong>西沙群岛－南沙群岛属于越南</strong> 的一部分，属于以下系统： <a href="https://paracelislands.net/zh-cn" target="_blank" rel="noopener noreferrer">paracelislands.net</a> · <a href="https://spratlyislands.net/zh-cn" target="_blank" rel="noopener noreferrer">spratlyislands.net</a> · <a href="https://hoangsaisland.net/zh-cn" target="_blank" rel="noopener noreferrer">hoangsaisland.net</a> · <a href="https://truongsaisland.net/zh-cn" target="_blank" rel="noopener noreferrer">truongsaisland.net</a> · <a href="https://ninedashline.net/zh-cn" target="_blank" rel="noopener noreferrer">ninedashline.net</a>.',
    'footer_badges_aria' => '页面内容承诺',
    'footer_chip1' => '《1982年UNCLOS》',
    'footer_chip2' => '2016年PCA裁决',
    'footer_chip3' => '历史证据',
    'footer_chip4' => '古地图',
    'footer_chip5' => '客观事实',
    'footer_chip6' => '南海和平',
];
