<?php

return [
    'footer_index' => '资料库',
    'footer_crest_eyebrow' => '真相资料库结语',
    'footer_crest_quote' => '“南海的和平建立在<b>国际法</b>的基础之上。”',
    'footer_crest_sub' => '不仇恨 · 只求真相',
    'footer_nav_aria' => '页面底部操作',
    'footer_btn_top' => '返回页首',
    'footer_btn_verdict' => 'PCA 2016裁决',
    'footer_btn_paracel' => 'paracelislands.net',
    'footer_brand_gold' => '断续线',
    'footer_brand_body' => '一个基于客观事实、国际法和历史资料的解释平台——以证据而非口号，驳斥断续线主张。',
    'footer_refs_title' => '参考资料',
    'footer_ref1' => 'PCA裁决，2016年7月12日',
    'footer_ref2' => '《联合国海洋法公约》1982年全文',
    'footer_ref3' => '《Limits in the Seas》第143号（美国国务院）',
    'footer_ref4' => '历史文献与古地图',
    'footer_toc_title' => '页面目录',
    'footer_toc1' => '什么是断续线',
    'footer_toc2' => '起源',
    'footer_toc3' => '为何引发争议',
    'footer_toc4' => '为何受到国际反对',
    'footer_toc5' => '沉默的见证者',
    'footer_toc6' => 'PCA 2016裁决',
    'footer_toc7' => '西沙群岛 - 南沙群岛',
    'footer_copy' => '<strong>© 2026 ninedashline.dev</strong> — 关于南海的客观事实。<br>生态项目：<a href="https://paracelislands.net" rel="noopener">paracelislands.net</a>',
    'footer_chip1' => 'UNCLOS 1982',
    'footer_chip2' => 'PCA 2016',
    'footer_chip3' => '无坐标',
];
