<?php

return [
    'nav_logo_name' => '断续线',
    'nav_logo_primary' => 'NINEDASHLINE',
    'nav_logo_secondary' => '断续线',
    'nav_rail_aria' => '章节导航',
    'nav_rail_what' => '定义',
    'nav_rail_origin' => '起源',
    'nav_rail_dispute' => '争议',
    'nav_rail_opposition' => '反对',
    'nav_rail_witnesses' => '古地图',
    'nav_rail_verdict' => 'PCA 2016',
    'nav_rail_sovereignty' => '西沙群岛 – 南沙群岛',
    'nav_sound_off' => '开启背景音乐',
    'nav_sound_on' => '关闭背景音乐',
    'nav_share' => '分享',
    'dialog_title' => '显示语言',
    'language' => '语言',
    'display_hint' => ':count 种语言',
    'search_placeholder' => '搜索语言…',
    'cancel' => '取消',
    'apply' => '应用',
    'sound_off' => '开启背景音频',
    'sound_on' => '关闭背景音频',
    'lang_trigger' => '选择语言',
    'close' => '关闭',
    'no_results' => '未找到语言',
    'contribute' => '分享',
];
