<?php

return [
    'opposition_index' => '反对',
    'opposition_label' => '国际社会为何反对',
    'opposition_title' => '反对基于',
    'opposition_title_accent' => '法律，而非情绪',
    'opposition_lead' => '自2009年断续线被提交至联合国后，多个国家及学术界随即提出反对意见——其依据是具体的法律论证，而非情绪化立场。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => '越南 · 马来西亚 · 印度尼西亚',
    'opposition_voice1_body' => '中国于2009年5月7日向联合国秘书长提交断续线地图后仅一天，这些国家便陆续递交照会表示反对，否定该项主张。',
    'opposition_voice1_chip1' => '反对照会',
    'opposition_voice1_chip2' => '不符合1982年《联合国海洋法公约》',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => '菲律宾',
    'opposition_voice2_body' => '向联合国提交外交函件，声明中国在南海的主张“缺乏国际法依据”——这也成为后来提起仲裁案的重要前提。',
    'opposition_voice2_chip1' => 'PCA仲裁案前奏',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '12/05',
    'opposition_voice3_title' => '美国国务院 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析指出：不同时期地图上的线段位置并不一致；界线向陆地方向延伸而非采用中间线原则；许多海上地物不符合“岛屿”标准，因此无权产生EEZ。',
    'opposition_voice3_chip1' => '不具备法律条件',
    'opposition_voice3_chip2' => '官方分析报告',
    'opposition_voice4_year' => '学术界',
    'opposition_voice4_title' => '“历史性水域”概念已经过时',
    'opposition_voice4_body' => '该概念仅适用于近岸海湾、港湾等水域，无法覆盖广阔的公海区域。2003年，台湾方面也已否定其1993年曾提出的“历史性水域”政策。',
    'opposition_voice4_chip1' => '即使中国学界也未形成一致意见',
];
