<?php

return [
    'opposition_index' => '反对',
    'opposition_label' => '为什么国际上反对',
    'opposition_title' => '反对基于',
    'opposition_title_accent' => '法律，而不是情绪',
    'opposition_lead' => '在断续线于2009年提交至联合国后，许多国家和学者便提出了反对——并给出了具体的法律论据。',
    'opposition_voice1_year' => '2009',
    'opposition_voice1_date' => '5月',
    'opposition_voice1_title' => '越南 · 马来西亚 · 印度尼西亚',
    'opposition_voice1_body' => '就在中国将断续线地图提交给联合国秘书长后的第二天（2009年5月7日），这些国家先后递交反对照会，否定该主张。',
    'opposition_voice1_chip1' => '反对照会',
    'opposition_voice1_chip2' => '不符合1982年《公约》',
    'opposition_voice2_year' => '2011',
    'opposition_voice2_date' => '04/05',
    'opposition_voice2_title' => '菲律宾',
    'opposition_voice2_body' => '向联合国提交外交照会，声明中国在南海的主张“缺乏国际法依据”——这为随后提起仲裁案奠定了前提。',
    'opposition_voice2_chip1' => 'PCA诉讼前提',
    'opposition_voice3_year' => '2014',
    'opposition_voice3_date' => '12/05',
    'opposition_voice3_title' => '美国国务院 — <em>Limits in the Seas №143</em>',
    'opposition_voice3_body' => '分析指出：各年份地图中断续线的位置并不一致；断续线侵入大陆而非以中线为基准；许多实体不具备成为“岛屿”并拥有EEZ的条件。',
    'opposition_voice3_chip1' => '不符合国家法定条件',
    'opposition_voice3_chip2' => '官方分析',
    'opposition_voice4_year' => '学术',
    'opposition_voice4_title' => '“历史性水域”已过时',
    'opposition_voice4_body' => '这一概念只适用于海湾、近岸内海——无法覆盖大片外海。2003年，连台湾也否定了其在1993年曾提出的“历史性水域”政策。',
    'opposition_voice4_chip1' => '甚至中国学者也未达成一致',
];
