<?php

return [
    'sovereignty_index' => '西沙群岛 - 南沙群岛',
    'sovereignty_label' => '必然结论',
    'sovereignty_title' => '西沙群岛 - 南沙群岛',
    'sovereignty_title_accent' => '属于越南',
    'sovereignty_lead' => '本页解释断续线。结论部分回答下一个问题：谁对西沙群岛和南沙群岛拥有主权？根据历史管理和国际法，一致的答案是越南。',
    'sovereignty_thesis_label' => '综合论点',
    'sovereignty_thesis_lock1' => '无法律坐标',
    'sovereignty_thesis_lock2' => '2016年仲裁裁决已驳回',
    'sovereignty_thesis_lock3' => '古地图未覆盖',
    'sovereignty_thesis_body' => '在上面的六个部分之后，三点已经清楚：断续线是手绘的，没有法律坐标；2016年仲裁庭驳回了该主张；中国自身的古地图也并未覆盖整个东海。越南的主权并不依赖口号，而是基于越南国家——自阮氏主政时期起——在这两群岛还是无主之地时，已对其进行和平且持续的管理。',
    'sovereignty_spine_caption' => '持续管理的节点',
    'sovereignty_spine_title' => '一条没有中断的时间线',
    'sovereignty_spine_range' => '17世纪 → 至今',
    'sovereignty_chron1_year' => '17世纪',
    'sovereignty_chron1_title' => '黄沙队',
    'sovereignty_chron1_body' => '阮氏诸主派遣黄沙队进行勘测、测量航道并开展海上开发——实际行使管理权。',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => '嘉隆帝',
    'sovereignty_chron2_body' => '在西沙群岛插旗，向当时的世界确认越南的主权。',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => '明命帝',
    'sovereignty_chron3_body' => '进行测绘、树碑，并将这些群岛记入朝廷官方地图。',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => '连续继承',
    'sovereignty_chron4_body' => '法国予以承认并继续管理；将西沙群岛并入承天省——这成为今天越南国家的基础。',
    'sovereignty_chron5_year' => '至今',
    'sovereignty_chron5_title' => '法律与实践',
    'sovereignty_chron5_body' => '越南依据UNCLOS、外交和档案资料进行管理；断续线主张无法取代这些证据。',
    'sovereignty_balance_label' => '证据平衡',
    'sovereignty_balance_medallion_title' => '双方对照',
    'sovereignty_vn_tag' => '越南一侧',
    'sovereignty_vn_title' => '主权由行为确立',
    'sovereignty_vn_body' => '在土地仍属无主时取得实际占有，随后历经数百年公开管理——拥有诏书、碑刻、地图与行政档案。此做法符合UNCLOS和国际惯例。',
    'sovereignty_dash_tag' => '断续线一侧',
    'sovereignty_dash_title' => '主张无法替代证据',
    'sovereignty_dash_body' => '1948年的一条线，没有坐标，已被2016年仲裁庭驳回，并且违背UNCLOS——正如第03至06部分所述。因此，关于两群岛主权的结论不能建立在断续线上。',
    'sovereignty_seal_quote' => '越南依据<strong>和平手段</strong>，在国际法——特别是1982年UNCLOS——基础上解决争端，致力于建设一个和平、合作与发展的东海。',
    'sovereignty_seal_cite' => '越南立场 · 1982年UNCLOS',
    'sovereignty_next_eyebrow' => '同一生态中的核心项目',
    'sovereignty_next_title' => '完整阅读西沙群岛 - 南沙群岛的证据',
    'sovereignty_next_body' => '详细档案——文件、地图、时间线和法律论证——都在<strong>paracelislands.net</strong>上，该站全面呈现两群岛主权主题。你正在阅读的页面，只是将断续线与该结论之间的逻辑连接起来。',
    'sovereignty_next_cta' => '打开 paracelislands.net',
];
