<?php

return [
    'sovereignty_index' => '西沙群岛 – 南沙群岛',
    'sovereignty_label' => '必然结论',
    'sovereignty_title' => '西沙群岛 – 南沙群岛',
    'sovereignty_title_accent' => '属于越南',
    'sovereignty_lead' => '本页面解释的是断续线。结论部分回答下一个问题：谁对西沙群岛和南沙群岛拥有主权？根据历史管理实践和国际法，始终一致的答案是越南。',
    'sovereignty_thesis_label' => '综合论点',
    'sovereignty_thesis_lock1' => '没有法律坐标',
    'sovereignty_thesis_lock2' => 'PCA 2016予以否定',
    'sovereignty_thesis_lock3' => '古地图未涵盖该区域',
    'sovereignty_thesis_body' => '经过前六部分的分析，三点已经明确：断续线是手绘而成，没有法律坐标；2016年仲裁庭否定了该主张；中国自身的古地图并未覆盖整个南海。越南的主权主张并非建立在口号之上，而是基于自阮主时期起，在两群岛尚属无主地时即已进行和平且持续的管理。',
    'sovereignty_spine_caption' => '持续管理的重要节点',
    'sovereignty_spine_title' => '一条从未中断的时间线',
    'sovereignty_spine_range' => '17世纪 → 至今',
    'sovereignty_chron1_year' => '17世纪',
    'sovereignty_chron1_title' => '黄沙队',
    'sovereignty_chron1_body' => '阮主派遣黄沙队开展勘察、测量航道并进行海上开发活动——实际行使管理权。',
    'sovereignty_chron2_year' => '1816',
    'sovereignty_chron2_title' => '嘉隆帝',
    'sovereignty_chron2_body' => '在西沙群岛竖立国旗，向当时国际社会宣示越南主权。',
    'sovereignty_chron3_year' => '1834',
    'sovereignty_chron3_title' => '明命帝',
    'sovereignty_chron3_body' => '进行测绘、设立界碑，并将群岛记录于朝廷官方地图之中。',
    'sovereignty_chron4_year' => '1932',
    'sovereignty_chron4_title' => '持续继承',
    'sovereignty_chron4_body' => '法国予以承认并继续管理；将西沙群岛并入承天省——成为当代越南国家主权继承的基础。',
    'sovereignty_chron5_year' => '现今',
    'sovereignty_chron5_title' => '法律与实践',
    'sovereignty_chron5_body' => '越南依据UNCLOS、外交实践及档案资料进行管理；断续线主张无法取代这些证据。',
    'sovereignty_balance_label' => '证据权衡',
    'sovereignty_balance_medallion_title' => '两种主张的对照',
    'sovereignty_vn_tag' => '越南方面',
    'sovereignty_vn_title' => '通过实际行为确立的主权',
    'sovereignty_vn_body' => '在土地尚属无主时进行有效占有，随后数百年来持续公开管理——拥有诏书、界碑、地图和行政档案等证据。这种做法符合UNCLOS及国际惯例。',
    'sovereignty_dash_tag' => '断续线方面',
    'sovereignty_dash_title' => '主张无法替代证据',
    'sovereignty_dash_body' => '一条绘于1948年的线，没有坐标，已被PCA 2016裁决否定，并与UNCLOS相冲突——正如第03至06部分所说明的那样。因此，关于两群岛主权的结论不能建立在断续线之上。',
    'sovereignty_seal_quote' => '越南通过<strong>和平方式</strong>解决争端，以国际法——特别是UNCLOS 1982——为基础，致力于建设和平、合作与发展的南海。',
    'sovereignty_seal_cite' => '越南立场 · UNCLOS 1982',
    'sovereignty_next_eyebrow' => '同一生态体系中的核心项目',
    'sovereignty_next_title' => '阅读关于西沙群岛 – 南沙群岛的完整证据',
    'sovereignty_next_body' => '更详细的档案——包括文献、地图、时间线和法律论据——收录于<strong>paracelislands.net</strong>，该网站系统展示两群岛主权问题的完整内容。您当前阅读的页面仅负责将断续线问题与这一结论在逻辑上连接起来。',
    'sovereignty_next_cta' => '打开 paracelislands.net',
];
