<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '国际裁决',
    'verdict_title' => 'PCA 2016：',
    'verdict_title_accent' => '三个“否定”',
    'verdict_lead' => '2016年7月12日，位于海牙的常设仲裁法院（PCA）——依据《联合国海洋法公约》（UNCLOS）附件七设立，并在菲律宾诉中国案中——作出裁决，否定断续线主张。<em>点击每张卡片可阅读原文。</em>',
    'verdict_card1_khong' => '否',
    'verdict_card1_title' => '历史性权利',
    'verdict_card1_short' => '中国对断续线内海域资源主张历史性权利，缺乏法律依据。',
    'verdict_card1_quote' => '“中国主张对断续线内海域资源享有历史性权利，缺乏法律依据。”',
    'verdict_card1_more' => '+ 阅读裁决',
    'verdict_card2_khong' => '否',
    'verdict_card2_title' => '可产生EEZ的海洋地物',
    'verdict_card2_short' => '南沙群岛中没有任何海洋地物符合为中国产生专属经济区的条件——包括太平岛在内。',
    'verdict_card2_quote' => '“南沙群岛中没有任何海洋地物能够产生专属经济区。”',
    'verdict_card2_more' => '+ 阅读裁决',
    'verdict_card3_khong' => '否',
    'verdict_card3_title' => '合法行为',
    'verdict_card3_short' => '中国侵犯了菲律宾的主权权利，妨碍渔业活动并损害海洋环境。',
    'verdict_card3_quote' => '“中国侵犯了菲律宾的主权权利，干扰黄岩岛海域的渔业活动，并对珊瑚礁环境造成严重损害。”',
    'verdict_card3_more' => '+ 阅读裁决',
    'verdict_extra1' => '中国自行划定的断续线<strong>不符合</strong>《联合国海洋法公约》1982年的规定。',
    'verdict_extra2' => '中国通过过度开发和建设人工岛，对南沙群岛生态系统造成损害。',
    'verdict_extra3' => '中国的相关行动增加了与菲律宾发生冲突的风险。',
    'verdict_extra4' => '太平岛（由台湾控制）同样不能产生专属经济区。',
    'verdict_subtitle' => '为什么它与UNCLOS发生冲突？',
    'verdict_subtitle_body' => '《联合国海洋法公约》（UNCLOS）1982明确依据沿海国家基线划分海域。断续线主张超出了这一法律框架，因此无法与之并存。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '领海（海里）',
    'verdict_zone1_body' => '从基线起算，国家享有主权的海域。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '专属经济区',
    'verdict_zone2_body' => 'EEZ——沿海国家在该范围内对资源享有主权权利。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陆架（最大，海里）',
    'verdict_zone3_body' => '依据地质条件确定的海床资源权利范围。',
    'verdict_foot' => '在这一法律框架下，覆盖整片公海海域的“历史性权利”——如断续线所暗示的那样——<em>已被取代</em>，取而代之的是UNCLOS确立的法律制度，而中国本身也是该公约的缔约方。',
];
