<?php

return [
    'verdict_index' => 'PCA 2016',
    'verdict_label' => '国际裁决',
    'verdict_title' => 'PCA 2016：',
    'verdict_title_accent' => '三个“没有”',
    'verdict_lead' => '2016年7月12日，设于海牙的常设仲裁法院（PCA）——依据《联合国海洋法公约》（UNCLOS）附件七设立，在菲律宾诉中国案中——作出裁决，驳回了断续线主张。<em>点击每个卡片阅读原文。</em>',
    'verdict_card1_khong' => '没有',
    'verdict_card1_title' => '历史性权利',
    'verdict_card1_short' => '中国对断续线范围内海域的资源主张历史性权利，没有法律依据。',
    'verdict_card1_quote' => '“中国就断续线所包围海域内的资源主张历史性权利，没有法律依据。”',
    'verdict_card1_more' => '+ 阅读裁决',
    'verdict_card2_khong' => '没有',
    'verdict_card2_title' => '形成EEZ的实体',
    'verdict_card2_short' => '南沙群岛中没有任何实体具备形成中国专属经济区的资格——包括太平岛。',
    'verdict_card2_quote' => '“南沙群岛中没有任何实体有能力形成专属经济区。”',
    'verdict_card2_more' => '+ 阅读裁决',
    'verdict_card3_khong' => '没有',
    'verdict_card3_title' => '合法行为',
    'verdict_card3_short' => '中国侵犯了菲律宾的主权权利，阻碍捕鱼，并损害海洋环境。',
    'verdict_card3_quote' => '“中国侵犯了菲律宾的主权权利，干涉斯卡伯勒浅滩的捕鱼活动，并对珊瑚礁环境造成严重损害。”',
    'verdict_card3_more' => '+ 阅读裁决',
    'verdict_extra1' => '中国自行绘制的断续线<strong>不符合</strong>1982年《联合国海洋法公约》。',
    'verdict_extra2' => '中国通过过度开发和人工造岛，破坏了南沙群岛的生态系统。',
    'verdict_extra3' => '中国的行为加剧了与菲律宾发生冲突的风险。',
    'verdict_extra4' => '太平岛（由台湾控制）也不能形成EEZ。',
    'verdict_subtitle' => '为什么它与UNCLOS相冲突？',
    'verdict_subtitle_body' => '1982年《联合国海洋法公约》依据沿海国的基线，清楚界定各类海域。断续线主张超出了这一框架，因此无法并置。',
    'verdict_zone1_num' => '12',
    'verdict_zone1_title' => '领海（海里）',
    'verdict_zone1_body' => '从基线起算、国家拥有主权的海域。',
    'verdict_zone2_num' => '200',
    'verdict_zone2_title' => '专属经济区',
    'verdict_zone2_body' => 'EEZ——沿海国在此范围内对资源享有主权权利。',
    'verdict_zone3_num' => '350',
    'verdict_zone3_title' => '大陆架（最大，海里）',
    'verdict_zone3_body' => '依据地质条件确定的海底资源权利。',
    'verdict_foot' => '在这一框架下，“历史性权利”所涵盖的整片公海——正如断续线所暗示的那样——<em>已被</em>UNCLOS的法律制度所取代，而中国本身也是其缔约国之一。',
];
