<?php

return [
    'witnesses_index' => '古地图',
    'witnesses_label' => '中国古地图',
    'witnesses_title' => '最南只到',
    'witnesses_title_accent' => '海南岛',
    'witnesses_lead' => '中国作者绘制的古地图——按时间顺序排列——都显示<em>海南岛是中国最南端</em>，不包含西沙群岛或南沙群岛。资料汇编依据《越南在西沙群岛和南沙群岛两群岛的国家主权》（张明育，2015）。',
    'witnesses_hint' => '⌖ 放大查看',
    'witnesses_map1_svg_hainan' => '海南 海南',
    'witnesses_map1_svg_south' => '— 领土最南端 —',
    'witnesses_map1_svg_era' => '宋朝 · 1136',
    'witnesses_map1_title' => '宋代地图，1136年',
    'witnesses_map1_body' => '中国领土止于海南岛，西沙群岛和南沙群岛均位于疆域之外。',
    'witnesses_map2_svg_hainan' => '海南',
    'witnesses_map2_svg_south' => 'd\'Anville界线',
    'witnesses_map2_svg_era' => 'd\'Anville · 1735',
    'witnesses_map2_title' => 'd\'Anville地图，1735年',
    'witnesses_map2_body' => '由J.-B. B. d\'Anville绘制；其1740年版本复制本曾由德国总理赠予中国领导人。地图显示清朝领土止于海南。',
    'witnesses_map3_svg_hainan' => '海南 海南',
    'witnesses_map3_svg_south' => '“中国最南端”',
    'witnesses_map3_svg_era' => '皇朝直省 · 1904',
    'witnesses_map3_title' => '《皇朝直省地舆全图》',
    'witnesses_map3_body' => '由清朝刊印，明确标示中国领土最南端为海南岛。',
    'witnesses_quote' => '连中国已公布的地图，也没有把西沙群岛——南沙群岛划入其领土。',
    'witnesses_timeline_aria' => '中国古地图时间轴',
    'witnesses_year_aria' => '年代',
    'lightbox_aria' => '查看放大图片',
    'lightbox_close' => '关闭',
    'lightbox_prev' => '上一张',
    'lightbox_next' => '下一张',
];
